OPM/opm-simulators

CMakeLists_files.cmake
ebos/collecttoiorank.hh
ebos/eclcpgridvanguard.hh
ebos/eclwriter.hh
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp

This is needed for OPM/opm-grid#389. With that change the global grid on all processes but the one
with rank 0 (IO process) will be empty and hence they do not have the global grid available anymore (or more precise it is a grid without active cells). Any use of it is most likely will result in an error.  This PR should remove the use of the global grid on all but the IO rank.
Please not that with this Schedule::filterConnections is only called on the IO process since for the other
processes it will remove all well connections. This PR needs to be double checked with all well models,
At least for the traditional one it seems to work.
This PR should work stand alone.

Avoid using global grid (equilGrid) on non-IO processes.

---

CMakeLists_files.cmake
ebos/collecttoiorank.hh
ebos/eclcpgridvanguard.hh
ebos/eclwriter.hh
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp

Original description:
"This is needed for OPM/opm-grid PR 389. With that change the global grid on all processes but the one
with rank 0 (IO process) will be empty and hence they do not have the global grid available anymore (or more precise it is a grid without active cells)..."
For more see #2033

Avoid using global grid on all procs (Backport of pr #2033)

---

jenkins/run-norne.sh

This enables triggering a parallel norne run using 'run norne_parallel'. trigger runs with 4 procs right now.

added: allow running the norne test in parallel

---

opm/simulators/flow/BlackoilModelParametersEbos.hpp
opm/simulators/wells/StandardWell_impl.hpp

For several cases (The latest a slightly modified version of Olympus) the current well operability checking does not work as expected. This adds a easy way to disable the well operability checking. The default is still true, i.e. this does not change the current behavior of the simulator.

Add well operability param

---

opm/simulators/wells/StandardWell_impl.hpp

This fix avoids nan due to very small values (1e-20) for mix[oil] and max[gas]. The nan was triggered after an STOPed water injector (with epsilon cross flow) started up again. 
Fixes a run for a proprietary model.

avoid nan in the density calculation

---

flow/flow.cpp

Use an alterntative `ParseContext` constructor to enable environment variable based settings. 
In master the ParseContext settings are set with the `update`method *after* the environment variables have been processed; i.e. for the four settings which are explicitly set in flow it is not possible to override with environment variables. In current master flow will only warn if the summary section mentions an unknown well; if the current PR is merged this can be changed with:
```bash
bash% export OPM_ERRORS_EXIT1=SUMMARY_UNKNOWN_WELL
bash% flow CASE.DATA
...
Error: Error in keyword:WWIR No such well: C-1H
A fatal error has occured and the application will stop.
Error in keyword:WWIR No such well: C-1H
```

Pass ParseContext settings in constructor

---

flow/flow_onephase.cpp
flow/flow_onephase_energy.cpp

to make it consistent with the rest. OPM/opm-models#530 development
must have been started before the renaming in OPM/opm-models#532
and somehow the old namespace survived.
downstream PR of OPM/opm-models#577

Move BlackOilOnePhaseIndices to Opm namespace

---

ebos/eclcpgridvanguard.hh

This removes a deadlock experienced for some models where we have specified connections to non-active cells.
On non-IO ranks we are using the local grid since in the future there will be no global grid available. Wells connecting cells not on these processors are neglected anyway.
Closes #2101

Filter connections on non-IO ranks and remove parallel deadlock

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

In the case with active solvent (BlackoilWellModel::has_solvent_ is
true, e.g. case 2D_OILWATER_POLYMER.DATA) and one process have no
wells while another has some this lead to numComponents returning
different values. Later this lead to truncated message in MPI_Allgather.
The underlying problem was the usage of numWells() which returns just
the number of local wells. We resort to using wellsActive which
returns whether there any well active regardless which process knows it.

Fix BlackoilWellModel::numComponents for parallel runs.

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

This fixes MPI's truncated message error for simulation with less than 3 phases and on process holding none of the wells.

Fix BlackoilWellModel::numComponents for parallel runs. (Backport of pr #2131)

---

opm/simulators/wells/WellInterface_impl.hpp

Move the checking of THP down the line. For non-convergent solution we don't want to switch to THP. This is sufficient to get a good match on Norne1B.

Check THP in the end

---

ebos/eclbasevanguard.hh

This is a plain C++ commit lifted from #2127 
This will allow the vanguard initialization to proceed even if a deck filename is missing - if the Deck / EclipseState7 / ... objects have been supplied externally.

Skip processing of filename if external deck already exists.

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
tests/test_wellstatefullyimplicitblackoil.cpp
tests/wells_manager_data_wellSTOP.data

For a well which starts in the state `STOP` the perforation pressures are not properly initialized, and the `-1e100` value from: [`WellState` initialization](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/WellState.hpp#L177) spreads around creating havoc.
~~The current PR works for me - I am trying to make a proper test for it.~~ Help from @atgeirr in the debugging process is acknowledged.

Make sure the perforation pressures is initialized also for STOP wells

---

opm/simulators/flow/MissingFeatures.cpp

which was removed by mistake in PR #2162
My mistake.

adding AQUFET back to MissingFeatures.cpp

---

opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp

The major fixes include two parts, incorporating the derivatives from pressure difference, and correcting the way to calculate the initial aquifer pressure, which is important when the initial aquifer pressure is not specified. 
With this PR and the several merged PRs from opm-common, flow managed to give very good results in the targeting aquifer case with Fetkovich aquifers.  
There will be some cleaning up related to aquifer models, maybe also some fixes should be applied to CT aquifer too.

fixing and improvement of the Aquifer models

---

flow/flow_tag.hpp
opm/simulators/flow/FlowMainEbos.hpp

No matter whether requested via --help or printed due to a wrong command line parameter.
Closes #2012.

Only print usage information on one processes.

---

jenkins/run-norne.sh

this way we get curves for both the serial and parallel runs in the well plots.
requires https://github.com/OPM/opm-tests/pull/193

changed: use a separate output dir in the parallel norne test

---

CMakeLists_files.cmake
tests/test_ParallelRestart.cpp

Is very useful while working on extending the data types supported.
Downstream of https://github.com/OPM/opm-common/pull/1265

added: test for serializations in ParallelRestart

---

ebos/eclproblem.hh

When an action condition has been evaluated the set of wells matching the condition is available; that can be used in place of `'?'` in the `WELOPEN` keyword. This PR will just include the matching wells in the log message.

List the matching wells for Action eval

---

tests/test_ParallelRestart.cpp

- Avoid unused symbols warning in serial
- Fix build with gcc5

Janitoring

---

ebos/eclproblem.hh

This is needed to ensure that the `SummaryState` is fully updated before calling the `applyAction`code.

SummaryState is updated at the end of simulator timestep

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

- Move some WellState shut code to separate method.
- Add bool flag open_for_output_ to WellState to ensure that shut wells do not
create output.
Part of the effort to be able to handle ACTIONX in the middle of a report step.

Refactor WellState SHUT

---

ebos/eclbaseaquifermodel.hh
ebos/eclproblem.hh
ebos/eclwriter.hh
opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp
opm/simulators/aquifers/BlackoilAquiferModel.hpp
opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp

This PR adds a new member function,
```C++
AquiferInterface::initFromRestart()
```
that consumes a `vector<data::AquiferData>` constructed from information in the restart file's `XAAQ` vector.  At the moment, we use only the total produced liquid volume and the aquifer pressure.
We implement the interface's member function in terms of the virtual function
```C++
AquiferInterface::assignRestartData()
```
that must be overridden in derived classes.
Implement a trivial such function for Carter-Tracy aquifers, and a function that only stores the aquifer pressure for the Fetkovich aquifer model.
Additionally, record whether or not the aquifer object was initialised from a previous solution.  If so, don't reset total produce liquid volumes or aquifer pressures to their base values from the …

Load aquifer data

---

ebos/eclproblem.hh
opm/simulators/wells/BlackoilWellModel_impl.hpp

The ACTIONX keyword is evaluated at the end of every *time*step, whereas all of the simulator <-> deck interaction is currently at the report step granularity.
This pr is *very much* work in progress; more a draft for discussion.
After some discussion with @atgeirr it is not starting to approach something which can be merged.

Evaluate ACTIONX at the end of every timestep

---

opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ISTLSolverEbosCpr.hpp
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/linalg/ParallelOverlappingILU0.hpp
opm/simulators/linalg/findOverlapRowsAndColumns.hpp

Content of this PR:
- Remove superfluous copyOwnerToAll calls in ILU.
- Set overlap/ghost diagonal to 1 instead of 1e100.
- Create a new sparsity pattern for the parallel system matrix to avoid non-contributing computations in SpMV and ILU factorisation and apply.
The changes result in some improvement in parallel performance. The changes should not alter the convergence or simulation result at all. On a a DualProcessor AMD Epyc7601 node I observed the following runtimes (best of 10) using Flow (ILU) on the Norne model:
| MPI-processes  | master2019.10 + PR | master2019.10 | 
| ------------- | ------------- | ------------- |
|  2                     |        384.49         |      414.0              |
|  4                    |          219.9             |    242.7              |
|  8 …

Remove non-contributing computations in parallel solver by changing matrix sparsity pattern.

---

opm/simulators/utils/ParallelRestart.hpp

more readable, less tedious to add new types.
at least in my opinion. feel free to reject.

changed: use a macro to declare prototypes in ParallelRestart.hpp

---

ebos/eclcpgridvanguard.hh

The function signature has changed upstream. Now we do not need the EclipseState when filtering connections which is one step that will allow us to only store it on the IORank
Downstream of OPM/opm-common#1319

Use ActiveGridCells instead of EclipseGrid when filtering connections.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/WellState.hpp

The first commit is a minor bugfix, but necessary for the functioning of this PR. The open_for_output_ flag should eventually be made redundant.
The second commit fixes an annoyance (warning spamming) discovered during the work with this PR.
The third commit is the actual fix: closing wells as described in the title.

Shut wells under zero WCONPROD when disallowing crossflow

---

tests/test_equil.cc

I spent some wondering why the f... the test failed so hard someone had to call `std::abort( )`

Use throw std::runtime_error() instead of std::abort() in test

---

ebos/eclalugridvanguard.hh
ebos/eclcpgridvanguard.hh

... instead of a reference This is needed as we only want to read the
full deck and construct the EclipseGrid only on the master process
with rank 0. Hence all other ranks will pass a nullptr to this
function. This will be possible with this move from a reference to a
pointer.
downstream of PR OPM/opm-grid#433

Pass a pointer to the EclipseGrid to CpGrid::processEclipseGrid.

---

tests/test_ecl_output.cc

+ `std::cerr`instead of `std::cout`for message

Throw std::runtime_error() instead of std::abort() in test failure

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

Check group constraints from the top to allow for groups down in the hierarchy to switch to its own control.

check groups from top

---

tests/update_reference_data.sh

Avoid non-sense issues in opm-tests.
Downstream of https://github.com/OPM/opm-common/pull/1368

fixed: if not tests failed, do not proceed with update data procedure

---

opm/simulators/wells/MultisegmentWell_impl.hpp

With this fix, a comparison based on the MSW_MODEL_1.DATA test case variants show reasonable agreement between standard and multisegment wells with or without WEFAC.
In the current code, the conservation equations for the mswell are in terms of effective flows. This is similar to the treatment for standard wells. The alternative (formulating the equations in full rates) could be better and clearer in the long run.

Bugfix: correct well efficiency factors for MSW

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellGroupHelpers.hpp

The group reduction rates and REIN and VREP values are recomputed every iterations to account for changing well and group controls. But the values are fixed after the iterations number exceeds the value given by NUPCOL to avoid oscillation.

froze wellState at nupcol iterations

---

ebos/eclmpiserializer.hh
ebos/eclproblem.hh
opm/simulators/utils/ParallelRestart.cpp

Avoid using deck directly on non-root processes when setting up the solvent, polymer and foam modules.
Downstream of https://github.com/OPM/opm-models/pull/584

Avoid global ecl state in setting up additional modules

---

ebos/eclproblem.hh

This commit ensures that the previous solvent restart fix (commit afba6c8e8, PR #2023) does not attempt to index into the data member `solventSaturation_` unless solvent is activated.

Restart: Don't Access Solvent Saturation Unless Active

---

opm/simulators/linalg/FlexibleSolver.hpp
opm/simulators/linalg/OwningTwoLevelPreconditioner.hpp
opm/simulators/linalg/PreconditionerFactory.hpp
tests/test_preconditionerfactory.cpp

This fixes name clashes with DUNE's own factory that is introduced
in DUNE 2.7. Hence it closes issue #2266.
BTW: Dune's factory has more template parameters.

Move PreconditionerFactory into namespace Opm.

---

tests/test_ParallelRestart.cpp

the constructor is explicit with gcc5.
Closes #2271

fixed: use std::make_tuple instead of initializer list

---

opm/simulators/utils/ParallelRestart.hpp

As used here (not in a lambda) it is a GNU extension (related to the C++ Concepts extension) that is not in standard C++14 or C++17. Replacing with the equivalent template notation.

Change auto in prototype to template argument.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellGroupHelpers.hpp

Avoid adding the group contribution from children twice. 
This fixes Norne 4B.

fix for vrep and rein for more then one level of groups

---

ebos/eclequilinitializer.hh

Gave compile error on clang due to narrowing (the int 3 -> bool). Bug did not cause trouble because default number of phases in the fluid state (3) was sufficient.

Pass EnableBrine flag to BlackOilFluidState used for equilibration.

---

CMakeLists.txt
ebos/eclcpgridvanguard.hh
ebos/ecloutputblackoilmodule.hh
ebos/eclproblem.hh
ebos/eclthresholdpressure.hh
ebos/ecltransmissibility.hh
ebos/eclwriter.hh
ebos/equil/initstateequil.hh
tests/test_ecl_output.cc
tests/test_equil.cc

**Update:** This is now starting to shape up, and a merge is not so far away.My plan right now is as follows:
1. Regularly rebase this and the upstream PR's in opm-material and opm-common, let it linger for about a week while I periodically bitch about testing.
2. Update the development branches with review comments[1].
3. Wham-bang-merge - around January 10.th.
When the code has been merged, I intend to clean up opm-common, by completely removing the old `Eclipse3DProperties` implementation and also remove all the temporary build flags. Finally there will be a clean up in opm-simulators/opm-material. For a parallell simulation there are three levels of active cells: 
1. It is *all* `nx * ny * nz` cells in the cartesian box - this is what I typically call *global* in code I write.
2. It …

Simulate with only active cells

---

opm/simulators/utils/ParallelRestart.cpp
tests/test_ParallelRestart.cpp

The `RFTConfig` object gained a new data member and constructor argument, in addition to altering the type of the data member `well_open_rft_name` from an `unordered_set` to an `unordered_map` in PR OPM/opm-common#1412.
Update serialization code accordingly.

Parallel Restart: Chase RFTConfig API Update

---

ebos/ecltransmissibility.hh

in particular, this is preparing for the case where only the
root-process has a deck instance

changed: avoid deck usage

---

flow/flow.cpp

this is already available in the eclipseState.
in particular, this is preparing for the case where only the
root-process has a deck instance.

avoid instancing a new Runspec from deck to obtain active phases

---

ebos/eclproblem.hh
opm/simulators/utils/ParallelRestart.cpp
tests/test_ParallelRestart.cpp

Use EclipseState internalized  variables instead.
Downstream of https://github.com/OPM/opm-common/pull/1424

Avoid deck usage on non-root processes checking for keywords

---

opm/simulators/utils/ParallelRestart.cpp
tests/test_ParallelRestart.cpp

The Runspec class gained a new data member of type SatFuncControls.
Update the serialization code accordingly.
Downstream from OPM/opm-common#1431.

Chase Runspec Member Update

---

compareECLFiles.cmake
ebos/eclproblem.hh
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp

- some janitoring
- some fixes after brine addition
- avoid deck usage setting up thermal law manager
- add a thermal parallel regression test
I am somewhat worried about the coarse tolerances needed for the test to pass, but in any case this is an improvement.
Downstream of https://github.com/OPM/opm-material/pull/390

Parallel thermal simulations

---

ebos/eclcpgridvanguard.hh
ebos/ecltracermodel.hh
opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp

Avoid some deck usage, avoid some dereferencing.
The deck-access avoid is done simple right now, ideally these things would be internalized in EclipseState, but I don't want to be held up by them right now. Furthermore,  since neither tracers nor aquifers currently work in parallel, it's not that big of a deal.

Preparatory changes for single-process parsing

---

opm/simulators/flow/FlowMainEbos.hpp

Before it only ran on the part of the grid owned by process 0.

fixed: run RelpermDiagnostics on the global grid in parallel runs

---

opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

The targeting case is more troublesome due to some wells got shut due to physics limit. 
As a result, this PR is WIP and need to wait for more development of the physics limits first.

Support WGR limit check for WECON

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

As a general rule we don't want to check the current group control. A naive implementation of this did however not work since well controls may change during simulations due to input in the Schedule or closing of wells etc. This PR tries to circumvent this by always checking the first two iterations. An alternative solution is to add an epsilon to avoid switching as has been used in testing branches for groups [#2273] for a long time. The solution suggested in this PR seems more robust.

make group constrain check conditional

---

opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp

The AquiferInterface base class has a member `connection_` which was sent up and down in the class hierarchy as a method parameter. With this PR we just use `this->connection_` instead - main purpose is to increase readability - and simplify this: https://github.com/OPM/opm-simulators/pull/2320

Use member variable in Aquifer code

---

opm/simulators/linalg/ISTLSolverEbos.hpp

I will (ab)use this PR to update reference data as one test fails after jenkins os/compiler bump.

changed: rename local typedef to avoid shadowing warning

---

opm/simulators/utils/ParallelFileMerger.hpp

Just preparing this for when we decide to move to gcc 4.9 as minimum.

changed: use std::regex instead of boost::regex

---

opm/simulators/linalg/ParallelIstlInformation.hpp
opm/simulators/linalg/bda/BdaBridge.cpp
opm/simulators/linalg/bda/BdaBridge.hpp

The first commit is a compile failure on clang (std::pointer_to_binary_function was deprecated already when it was introduced into the code, removed in c++17), the second is just warning suppression.

Remove std::pointer_to_binary_function and silence a warning.

---

opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp
tests/test_ParallelRestart.cpp

The `UDQFunctionTable` can be instantiated without any user data - no need to pass between nodes.

Remove serialization support for UDQFunctionTable and UDQFunction

---

flow/flow.cpp

in that case we do not have an 'instance' of the static mpi helper
class.

fixed: build with dune-fem enabled

---

opm/simulators/utils/ParallelRestart.cpp
opm/simulators/wells/VFPHelpers.hpp
opm/simulators/wells/VFPInjProperties.cpp
opm/simulators/wells/VFPInjProperties.hpp
opm/simulators/wells/VFPProdProperties.cpp
opm/simulators/wells/VFPProdProperties.hpp
tests/test_ParallelRestart.cpp
tests/test_vfpproperties.cpp

Downstream of https://github.com/OPM/opm-common/pull/1478

Drop use of boost::multi_array in VFP classes 

---

flow/flow.cpp
flow/flow_tag.hpp
opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/utils/ParallelFileMerger.hpp

I did not notice these before for some reason.. https://github.com/OPM/opm-material/pull/399 made me notice.

remove last usage of boost::filesystem

---

opm/simulators/linalg/setupPropertyTree.cpp
tests/test_flexiblesolver.cpp
tests/test_preconditionerfactory.cpp

Context: Now that we use std::filesystem, the brokenness of boost::property_tree is the only reason why we need to use non-standard boost packages on rhel6/7. Since I doubt anyone would be doing development on these platforms, at least while using standard boost, I deem it better to disable this functionality to make for pain-free installs for end users.

disable json input for boost 1.48

---

opm/simulators/linalg/ParallelIstlInformation.hpp

strictly speaking the gcc diagnostics are wrong, the typedef is actually
used once templates are invoked on the structs.
simply use the typedef in the structs itself to avoid the warning
like is done for other variants.
replaces https://github.com/OPM/opm-simulators/pull/2345

quell warning about unused local typedef

---

opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp
tests/test_ParallelRestart.cpp

The first commit adds serialization for the `AquiferConfig` class. The second commit adds a commented out POC for how the new `AquiferConfig` class can be used instead of the `Deck` to configure the simulator specific Aquifer functionality. 
@akva2 : Will you complete this work?
Upstream: https://github.com/OPM/opm-common/pull/1458

Add serialization for AquiferConfig

---

ebos/startEbos.hh
opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/MissingFeatures.cpp
opm/simulators/flow/countGlobalCells.hpp
opm/simulators/linalg/ExtractParallelGridInformationToISTL.cpp
opm/simulators/linalg/ExtractParallelGridInformationToISTL.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ISTLSolverEbosCpr.hpp
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/linalg/ParallelIstlInformation.hpp
opm/simulators/timestepping/TimeStepControl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp

- use std::any
- use std::optional
- use internal uppercasing
- avoid lexical_cast
- remove unnecessary includes

Lessen boost usage

---

CMakeLists.txt

Downstream of https://github.com/OPM/opm-common/pull/1492

disable building of tests if Boost::test is not found

---

opm/simulators/utils/ParallelRestart.cpp
tests/test_ParallelRestart.cpp

Use an alternative constructor in the serialization of WellSegments.
Downstream of: https://github.com/OPM/opm-common/pull/1503

Simplify serialization of WellSegments

---

CMakeLists.txt

We experienced weired linker errors when using host compiler version for compilation that were not supported by the nvcc used to compile the cuda code:
```
[ 15%] Linking CXX executable bin/test_timer
/usr/bin/ld: /home/mblatt/src/dune/opm-2.6/opm-common/opm-seq/lib/libopmcommon.a(Parser.cpp.o): in function `Opm::(anonymous namespace)::file& std::vector<Opm::(anonymous namespace)::file, std::allocator<Opm::(anonymous namespace)::file> >::emplace_back<std::filesystem::__cxx11::path&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(std::filesystem::__cxx11::path&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
Parser.cpp:(.text+0x1096): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()' …
```

Make mixing incompatible host compiler/device compiler versions fail.

---

jenkins/run-norne.sh

the simulator handles this itself. this fixes errors in the
well plot script when only parallel norne is run.

fixed: do not make root dir

---

CMakeLists.txt

It seems like the VERSION_GREATER_EQUAL operator for boolean expressions was introduced after CMake 3.6 and hence the current check whether to activate CUDA or not is broken in version 3.6 and below.
This PR fixes this by using VERSION_GREATER.
Closes #2375.

Make Cmake version check for CUDA work for CMake 3.6.

---

ebos/eclproblem.hh
tests/test_norne_pvt.cpp

setup is now done all from state, which means it can be done
independently on all processes
Downstream of https://github.com/OPM/opm-material/pull/411
Downstream of https://github.com/OPM/opm-models/pull/597

changed: no need to serialize the FluidSystem any more

---

ebos/eclbasevanguard.hh
flow/flow.cpp

Add a commandline switch `--sched-restart` to flow which can regulate how the schedule information should be initialized when restarting. When using `--sched-restart=true` the simulator will use the historical schedule section to initialize, whereas with `--sched-restart=false` the simulator will initialize from the restart file. The ability to initialize from the restart file is very much work in progress, and this will go through several stages:
1. (This PR) flow can *not* initialize from the restart file - and if you pass `--sched-restart=false` flow will bail with an exception; the default is of course `--sched-restart=true`.
2. When the basic functionality is in place we remove the `throw` and flow will initialize from the restart file if you pass `--sched-restart=false` - but the …

Add commandline switch --sched-restart to control restart init

---

opm/simulators/utils/FieldPropsDataHandle.hpp

Fixes the fallout form #2406 (breaking serial build)

Only compile FieldPropsDataHandle if MPI was found

---

opm/simulators/flow/MissingFeatures.cpp

fixed: VAPPARS is supported, remove from unsupported features list

---

CMakeLists_files.cmake
ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
ebos/ecltransmissibility.hh
opm/simulators/utils/ParallelEclipseState.hpp
opm/simulators/utils/PropsCentroidsDataHandle.hpp

They are attached to the cells as well and are now distributed during CpGrid::loadBalance. Due to this change we also rename FieldPropsDataHandle to PropsCentroidsDataHandle.
Based on and includes PR #2406 and is rebased onto current master

Also distribute the centroids when loadbalancing CpGrid.

---

ebos/eclequilinitializer.hh

There is not reason to it as a vector of cartesian size as we access its entries by the compressed element index. This should save space and speedup the lookup.
A further step would be to either remove this class or move the initialization into an function of the class that directly return the vector. The class is currently only temporarily initiated by eclproblem to copy out the values of the vector [here](/OPM/opm-simulators/blob/master/ebos/eclproblem.hh#L2408-L2423)

Shrink EclEquilInitializer::initialFluidStates_.

---

compareECLFiles.cmake
tests/run-restart-regressionTest.sh

Ref https://github.com/OPM/opm-simulators/pull/2432

fixed: do not abuse TEST_ARGS in restart test machinery

---

compareECLFiles.cmake

Adds a flag `--sched-restart` to the test driver for restart tests. For now the value `true` is passed - which corresponds to the current default (and only working alternative). This is a preparation to enable regression testing of the feature: opm/opm-common#1396

Add --sched-restart flag when running restart regression tests

---

ebos/eclmpiserializer.hh
opm/simulators/utils/ParallelEclipseState.cpp
opm/simulators/utils/ParallelEclipseState.hpp

now users only have to implement a single method for
packsize/pack/unpack.
Prerequisites:
https://github.com/OPM/opm-material/pull/412
https://github.com/OPM/opm-simulators/pull/2436

changed: simplify eclmpiserializer

---

ebos/eclcpgridvanguard.hh
ebos/equil/initstateequil.hh
opm/simulators/utils/ParallelEclipseState.cpp
opm/simulators/utils/ParallelEclipseState.hpp

With this PR `ParallelEclipseState` will be able to autocreate data for somekeywords that have not been explicitly specified in the input file (just like the serial version). For now this still happens by wasting some space, creating global arrays of cartesian size and then compressing them manually. We use this to get rid off using the get_global_* accessors initstateequil.hh except for the temperature stuff which appears to be buggy in parallel (issue #2423) and hence might lead to differing results.
As a drive-by improvement we get rid off (at least) one unneccessary copy (PVTNUM) and on my system this give us  a 10% performance boost for Norne on 4 processors due to faster assembly.

Autocreate parallel fieldprops and use compressed ones in initstateequil.hh

---

opm/simulators/flow/MissingFeatures.cpp

Add keywords WEIR (Energy Injection Rate) and WEIR (Energy Injection Rate).

Add missing keywords to list

---

opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp

this to avoid having to explicitly instance the templates for
various enums when serialization functions are moved into classes.
@blattms this is a compromise between control of the number of instanced templates
and convenience.

changed: move the serialization template definitions for generic scalars

---

compareECLFiles.cmake
flow/flow.cpp

Along with opm/opm-common#1436 this can now restart the testcases in opm-test with `--sched-restart=false`. There is is still *much* more work to be done before we can say that the case of restarting only from the restart-file is generally solved - see upstream.

Restart flow from restart state

---

ebos/eclmpiserializer.hh
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp
tests/test_ParallelRestart.cpp

Downstream of https://github.com/OPM/opm-common/pull/1567
Note; the use of a lambda in the vector method might seem overkill but it will make more sense later.

Remove old serialization for SummaryNode

---

ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
ebos/eclthresholdpressure.hh
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ParallelOverlappingILU0.hpp
opm/simulators/linalg/findOverlapRowsAndColumns.hpp

This PR require https://github.com/OPM/opm-grid/pull/430 in opm-grid, and in addition to what is contained there, the following is changed:
- Command line argument --owners-first, that turn on/off "owners first" ordering of cells in the parallel grid. Default is off.
- SpMV, inner product and ILU that utilise the "owners first" ordering, and therefore avoids some superfluous computations.
On dual Intel Xeon E5-2670 2.6GHz 8-core CPU nodes this time, some modest improvement in parallel performance was achieved on Norne:
| P | master: time / iter     | owners-first: time / iter  |
|---|--------------------| -----------------------|
| 2  |  426.57 / 25339     |    408.73  /  25179        |
| 4  |     259.07 / 25571    |      245.40 / 25209      |
| 8  |     181.15 / 25026     |     174.39 / …

[For testing] Enable "owners first" ordering. Altered SpMV, SP and ILU.

---

CMakeLists_files.cmake
ebos/eclproblem.hh
flow/flow.cpp
opm/simulators/flow/FlowMainEbos.hpp

Argh, I always forget to check this!

fixed: do not build ParallelRestart test without MPI

---

opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ISTLSolverEbosCpr.hpp
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/linalg/findOverlapRowsAndColumns.hpp

That the local ids were consecutive and starting from 0 was just a coincidence and they should never be used to access linear systems or vectors. This commit fixes this by using the correct mappers instead.
It is a preparation needed to fix the idsets of CpGrid.
Note the we removed some computations from the constructor of ISTLSolverEbosCpr as it inherits from ISTLSolverEbos and the operations already happnen in constructor of the base class.

Do not use local id set to index matrices.

---

ebos/eclbasevanguard.hh
opm/core/props/satfunc/RelpermDiagnostics.hpp
opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
opm/simulators/flow/FlowMainEbos.hpp
tests/test_relpermdiagnostics.cpp

Use the [EndpointScaling](https://github.com/OPM/opm-common/blob/master/opm/parser/eclipse/EclipseState/EndpointScaling.hpp) instead of `deck.hasKeyword("SCALESRC")` in the relperm diagnostic. *This reduces deck usage.*
Observe that the semantic of the two is not 100% identical:
Old:
```
if (deck.hasKeyword("SCALESRC")) {
// do stuff 
}
```
New:
```
if (deck.hasKeyword("SCALESRC")) {
const auto& keyword = deck.getKeyword("SCALESRC");
if (keyword.getRecord(0).getItem(0) == "YES") {
// do stuff
}
}
```
i.e. the `EndpointSCaling`based implementation checks the value of the `SCALESRC`keyword, which the old implementation ignored.

Relperm diag no deck

---

opm/simulators/utils/PropsCentroidsDataHandle.hpp

as the issue in CpGrid was fixed, recently. See PRs #2458 and OPM/opm-grid#459.

Rely on local ids being persistent across grid modifications

---

ebos/ecltransmissibility.hh

this was actually broken by an upstream change from return-by-reference
to return-by-value (https://github.com/OPM/opm-common/commit/a595e68608830b5c643f19f881422b7d4b80f357), but we were lucky, the return value was
kept in memory until end of block it seems.

avoid potentially uninitialized warnings in serial

---

ebos/collecttoiorank.hh
ebos/eclwellmanager.hh
ebos/eclwriter.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This PR has changes that make parameters: currentProductionGroupControl and currentInjectionGroupControl available for writing Eclipse compatible restart files and for use as Summary file data. The content of the restart files will be changed as a consequence of using this information, to be included in a separate PR in opm-common.  
I would like to get this pull request merged soon since it is required to use together with other PRs for further work / improvment of the eclipse compatible restart files.

Make available current Production/Injection Group Control parameters for use in  Restart

---

ebos/eclbasevanguard.hh

externalDeck = nullptr -> internalDeck was parsed.
i have no idea why we have this external/internal deck in the first place.
now this caught me by surprise! i was doing memory profiling to see why memory usage in parallel was still unexpectedly high in parallel, and boy was i surprised when deck parsing showed up on non-root processes.

fixed: double-parsing of the deck

---

CMakeLists.txt
CMakeLists_files.cmake
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/bda/BdaBridge.cpp
opm/simulators/linalg/bda/BdaBridge.hpp
opm/simulators/linalg/bda/WellContributions.cu
opm/simulators/linalg/bda/WellContributions.hpp
opm/simulators/linalg/bda/cusparseSolverBackend.cu
opm/simulators/linalg/bda/cusparseSolverBackend.hpp
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp

This PR adds the WellContributions class, and allows the cusparseSolver to be used without `--matrix-add-well-contributions=true. The wellcontributions can be processed coupled (like previous PR) or separate (default).
The use must pass
```
--use-gpu=true
```
Notes:
- Assumes `BlackoilWellModel` only has `StandardWell`, probably not scalable, but NORNE only uses these.
- All wells are applied simultaneously, this means that the columnIndices in `StandardWell::duneB_` and `duneC_` must be unique, to prevent write-after-write hazards.
- Applying the wellcontributions on GPU takes <1 second for a full NORNE run (< 0.7% of linear solve time).
- It might be better to do 1 `addMatrix()` call instead of 3 when adding the data of a well to the `WellContributions` object.
- A `WellContributions` …

Separate wellcontributions for gpu

---

CMakeLists.txt

9.7 was a local change to see whether deactivating CUDA for old version works locally.
Completes #2488

Check for cuda 9.0 or newer as we are supposed to.

---

tests/test_ParallelRestart.cpp

this allows us to macrofy the test instantations.
Downstream of https://github.com/OPM/opm-common/pull/1621

changed: use serialization objects from opm-common in tests

---

ebos/eclmpiserializer.hh
opm/simulators/linalg/ISTLSolverEbos.hpp

The first commit fixes a compile error with clang.
The second just silences warnings.

Fix ptr() template for strict compilers (clang)

---

ebos/eclwriter.hh
opm/simulators/flow/FlowMainEbos.hpp

- Use unit system from state
- Remove additional call to checkMissingFeatures (already called from flow.cpp / flow_tag.hpp).
With these, https://github.com/OPM/opm-common/pull/1627 and https://github.com/OPM/opm-simulators/pull/2495 I can finally run flow without a deck instance. This potentially yields huge memory savings on root process in large parallel runs. 
I'm not trying to take the convenience vs sanity fight now, but just as a FYI; On one case I am looking at this means we need 4GB insteady of 8GB on root process..

Avoid deck usage in simulator

---

opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ParallelOverlappingILU0.hpp
opm/simulators/linalg/PreconditionerFactory.hpp
opm/simulators/linalg/PressureTransferPolicy.hpp

when running flow_blackoil_dunecpr with the defaults we experienced severs convergence issues with SPE1CASE2, because the decomposition was never recalculated. This is fixed in PR.
Closes #2490

Fixes ILU0 when using flexible solvers.

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This PR uses the new restart file support for active well control target modes to save and restore the ~run's~ wells' active targets.

Save and Restore Well's Current Control Target Mode

---

ebos/eclbasevanguard.hh
flow/flow.cpp
flow/flow_tag.hpp
tests/test_norne_pvt.cpp
tests/test_stoppedwells.cpp
tests/test_wellmodel.cpp
tests/test_wellstatefullyimplicitblackoil.cpp

Downstream of: https://github.com/OPM/opm-common/pull/1636
The new PYACTION keyword allows for loading a Python module and then run the `run()` function in that module during the simulation. The module is internalized by the Python interpreter on parse time (from opm-common) - that is essential to enable early error detection.If we do not have Python enabled the Python keywords are ignored in the Schedule construction.
The `python`argument which is added to the `Schedule`constructor is an instance of [this](https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/Python/Python.cpp). Iff this version of opm-common has been compiled with `OPM_ENABLE_EMBEDDED_PYTHON` the `Python`instance holds on to an interpreter - otherwise it is just an empty shell.
Will probably make a …

Add Python argument to Schedule constructor

---

compareECLFiles.cmake

This adds a restart regression test based on the MSW model in opm-tests. The restart is invoked with `--sched-restart=false`

Add integration test for restart & MSW

---

ebos/eclbasevanguard.hh

I have tested the owner-first ordering on a number of cases and a number of process counts. It has consistently yielded better performance. Hence, I suggest we enable it  by default.

Enable owner first ordering by default

---

compareECLFiles.cmake
ebos/equil/initstateequil.hh

The `InitialStateComputer::temperature_` array, previously used, was of Cartesian size, but used as if it only contained the values of the cells of a region. With this commit `InitialStateComputer::temperature_` is a compressed local array and we explicitly copy out only the region values when computing RS/RV.
Closes #2423.
Needs  #2446 to be merged first! Won't work otherwise

Use correct region temperature when calculating RS/RV

---

flow/flow.cpp

causes a throw on gcc-9.
closes https://github.com/OPM/opm-simulators/issues/2508

changed: avoid calling parent_path on paths that has none

---

CMakeLists_files.cmake
opm/simulators/timestepping/ConvergenceReport.hpp
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/TargetCalculator.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This is a cleaned-up version of #2332.
The points noted as missing in that PR have been addressed (efficiency factors, refactoring), and more (much more).
The code in this PR has been developed by @totto82 and @atgeirr, so much of has already been read by two persons. Before merging this, I think the following is what should be done:
- The authors read through it again...
- It is verified to not interfere with existing cases, in particular model 2 (regression tests as well as Norne in parallel has been checked already).
- One or more new integration tests have been added to verify the new functionality. This will be done based on new decks expected to be pushed to opm-tests by tomorrow.
- A separate reviewer takes a look at the code.

Group controls at wells (cleaned)

---

opm/simulators/flow/Main.hpp

Downstream from: https://github.com/OPM/opm-common/pull/1689

The "default" Schedule constructor has Python argument

---

python/CMakeLists.txt

this is necessary to allow building all modules in a 'super-build' with python enabled.

changed: check for pre-existing pybind11 target

---

CMakeLists_files.cmake

Pull request #2521 forgot to add `Main.hpp` to `CMakeLists_files.cmake`. Adding `Main.hpp` to `CMakeLists_files.cmake` will enable [`OpmInstall.cmake`](https://github.com/OPM/opm-common/blob/master/cmake/Modules/OpmInstall.cmake) to install the file to `$CMAKE_INSTALL_PREFIX/include/opm/simulators/flow` when running `make install`.

Add Main.hpp to CMakeLists_files.cmake.

---

flow/flow.cpp
opm/simulators/flow/Main.hpp

Redoing PR #2523 to fixup commit history (see https://github.com/OPM/opm-simulators/pull/2523#issuecomment-61340898)
Addresses the comments in PR #2521 regarding code duplication in `Main.hpp` and `flow_tag.hpp`. This PR merges the code in `flow_tag.hpp` into `Main.hpp` such that `flow_tag.hpp` can be eliminated (which will be done in PR #2524).

Merge flow_tag.hpp into Main.hpp (new try)

---

ebos/equil/initstateequil.hh
tests/test_equil.cc

This Pull Request introduces new helper classes,
* `Opm::EQUIL::Details::PressureTable<>`
* `Opm::EQUIL::Details::PhaseSaturations<>`
that colectively subsume the responsibility of the existing helper functions
* `Opm::EQUIL::phasePressures<>()`
* `Opm::EQUIL::phaseSaturations<>()`
and generalise that functionality to arbitrary depth points within single cells.  This is in preparation of adding support for the `N < 0` case of the initial fluid in place procedure defined in the `EQUIL`
keyword.  The `PhaseSaturations` class consumes an already equlibrated pressure table for the pertinent equilibration region, calculates capillary pressure values and inverts Pc curves to derive saturation values. If the capillary pressure curves are constant within a cell, then a simple depth consideration …

Refactor Equilibration Procedure

---

opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
opm/simulators/timestepping/SimulatorReport.cpp
opm/simulators/timestepping/SimulatorReport.hpp

Depends on OPM/opm-common#1692.
This simply queries the `exitStatus()` of the schedule at the start of a report timestep. It does not honor the value, that could be added but require modifying the return values down a chain of calls, so I did not implement that (yet), is it important? What does the commercial sims do?
I tested it using an ACTIONX condition to stop simulation, and behaviour is consistent in the following sense: if I use the "gas rate > 100 k" condition, with `EXIT` the last timestep has just above 100k gas rate. If I instead do `WELOPEN * SHUT`, the last timestep with nonzero rate is the same as the last above, with the same rate.

Stop simulating if the schedule has set an exit condition.

---

CMakeLists.txt

tests fail to execute in super-build otherwise

fixed: use PROJECT_BINARY_DIR, not CMAKE_BINARY_DIR

---

CMakeLists.txt
compareECLFiles.cmake
tests/run-test.sh

to execute these you have to use ctest -C ExtraTests
or 'make extra_test'.
As discussed in meeting. Right now these only execute the runs, meant as a POC.
Downstream of https://github.com/OPM/opm-common/pull/1678

add norne and norne_parallel as ExtraTests

---

ebos/equil/equilibrationhelpers.hh
ebos/equil/initstateequil.hh
tests/test_equil.cc

This Pull Request adds a very early, alpha-quality implementation of the "horizontal subdivision" strategy (N < 0) of the EQUIL directive. This in turn enables more accurate derivations of the initial fluids in place.
Interactions with SWATINIT are completely untested, and the initial Rs/Rv derivations in this context are possibly incomplete.  More work is likely needed in this area, but this does at least enable more widespread testing.
This PR depends on (and includes) #2527 and must not be merged before that PR is in master.
Below is an example using [MOD4_GRP](https://github.com/OPM/opm-tests/blob/e3e4747457f9d8168909d89afc3657d6ea8523d0/model4/MOD4_GRP.DATA) from OPM-Tests, with the equilibration directive changed as
```diff
EQUIL
-- datum    Pres     OWC            Pcow  GOC    Pcog …
```

 Equilibration: Add Experimental Support for Horizontal Subdivision

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellInterface_impl.hpp

The target reduction due to wells not under group control is applied on the group under control level or on levels where the guiderates are explicitly set.

Fix how the group reduction works

---

opm/simulators/flow/MissingFeatures.cpp

The `VISCREF`keyword is supported.

Remove VISCREF from MissingFeatures

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellInterface_impl.hpp

1) Only check GCONSALE limits at the end of a timestep. NB. The simulator still throws if some of the limits are violated
2) BUGFIX: don't remove gas consumption twice
Tested on `9_3B_---_STW/MSW` and `9_3C_---_STW/MSW`

Fix GCONSALE

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

This is sufficient to run the 9_4[B,C,D] test cases in opm-tests/model2.

use nupcol to avoid oscillation between group controls

---

opm/simulators/linalg/PreconditionerFactory.hpp

SeqILU0/SeqILU0 are removed in master and one should use SeqILU.
Closes #2568

Complete future-proofing ILU usage in the preconditioner factory.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

Introduced, but not actually used, in #2564.

Remove Unused 'currentControl' Variable

---

opm/simulators/flow/Main.hpp

Without this, properties set in the static variants of flow such as
flow_blackoil_dunecpr.cpp will be honored in the run. However, the
text for '--help' and the property printout in the .DBG file will not
reflect the true type tag, but the default.
This bug was added during the recent refactoring of all Flow variants
to use the same initialization and setup code.

Ensure that the typetag used for initialization is correct.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

The solvent model was forgotten when separate re-injection group was implemented.

Fix solvent reinjection when different reinjection group is given

---

CMakeLists.txt

At least on Debian 10 the standard c++ compiler is g++-8, but CUDA only supports g++-7 and our test for CUDA in cmake did send an error in that case/combination which is quite annoying.
The reason was that check_language(CUDA) did not honor the CMAKE_CUDA_FLAGS variable and always used the default g++7, but enable_language(CUDA) did honor it. As we do set the underlying host compiler the fromer reported that CUDA is available while the latter marked the CUDA compiler as broken.
With this commit we work around this by setting the environment variable ENV{CUDAHOSTCXX} which nvcc will use. Hence now we only try to enable CUDA if it is compatible with the C++ compiler

Prevent Cmake error for CUDA with incompatible c++ compiler.

---

opm/simulators/flow/FlowMainEbos.hpp

I missed this fallout of #2586, sorry for that! Added a comment in the code to explain what is going on.
Yes, this means we need at least one test for the static sims.

Do not run setupParameter_() twice for the static-typed sims.

---

tests/test_milu.cpp
tests/test_norne_pvt.cpp
tests/test_relpermdiagnostics.cpp

quell deprecation warnings with boost 1.71

---

opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/linalg/WriteSystemMatrixHelper.hpp

Triggered only when using the flexible solver and a solver verbosity > 10.
Compared to #2593, I have cleaned up whitespace (tabs->spaces) and some other minor changes. One behaviour change: I have made the time part of the filename longer (12 characters) and padded with zeros so that filenames are more similar and can be sorted.
I planned to use another mechanism than verbosity to control this, but decided that can wait. Contrary to what is written in #2593 one can get matrices written without using a JSON file for the linear solver config, by using the `--flow-linear-solver-verbosity` parameter.
I think this can be merged. In a way, it is my review of #2593... So unless there are objections, I'll self-merge it tomorrow. @hnil please check that you are ok with the changes.

Add a writeSystem() helper and use it to write system matrices.

---

opm/simulators/flow/BlackoilModelEbos.hpp
opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/NonlinearSolverEbos.hpp
opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
opm/simulators/timestepping/SimulatorReport.cpp
opm/simulators/timestepping/SimulatorReport.hpp
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

This started from, and replaces #2595.
The real changes I have made are (in addition to code formatting fixes such as tabs):
- Refactor to not use inheritance. The proposed way was a bit hard to understand. As it stands now I think it is more straightforward.
- Refactored how failure reports are treated. In the (new) SimulatorReport class (the old is now SimulatorReportSingle), as single reports are added they are both added to the vector of reports, and cumulated into either the `success` or `failure` member. This allowed to remove the explicit treatment of failures from two classes.
- The performance report is written to `<CASENAME>.STEPINFO`.
- Successful and failed steps are in the same report (distinguish with the converged flag).
- The report is made more human-readable, in …

Add writing detailed performance report

---

opm/simulators/flow/MissingFeatures.cpp

We've supported that operator for quite some time.

Remove 'MAXVALUE' From List of Missing Features

---

opm/simulators/flow/Main.hpp
python/CMakeLists.txt
python/simulators/CMakeLists.txt
python/simulators/simulators.cpp

A simplified version of PR #2518 that uses a deck filename to construct the simulator.
After private discussion with @joakim-hove it was decided that the construction of the blackoil simulator from Python using `deck`, `eclipseState`, `schedule`, and `summaryConfig` as constructor arguments (as implemented in #2518) should be replaced by a constructor taking only the deck filename as parameter.
A rewrite of the Python bindings for the blackoil simulator using pybind11 as introduced in #2127. The new version uses the refactored `flow.cpp` introduced in #2516 and thus avoids duplication
of the code in `simulators.cpp`.
This PR will be the starting point for implementing the Python bindings introduced in #2403.

Python bindings for the blackoil simulator (simplified).

---

opm/simulators/linalg/WriteSystemMatrixHelper.hpp

as there already is a specialization for an arbitrary Block
and that one leads to compile errors because we redefine it
in OPM (and miss some other specializations for Opm:MatrixBlock,
e.g. isNumber).
Fixes fallout from #2599

For DUNE 2.7 and up we need to specialize for Opm:MatrixBlock

---

opm/simulators/linalg/FlexibleSolver.hpp

Previously all the ranks print linear solver statistics in verbose mode which cluttered the output in parallel runs. Now only rank 0 will print like it should be.

Make only rank zero honor verbosity in flexible solvers.

---

opm/simulators/linalg/FlowLinearSolverParameters.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/setupPropertyTree_impl.hpp

Previously, one had to call a seperate binary called flow_blackoil_dunecpr. Unforntunately, that was only built if users requested that the tests (`-DBUILD_TESTING=ON`) and the flow variants (`-DBUILD_FLOW_VARIANTS=ON`) should be built. In addition it would use a slightly different nonlinear solver implementation.
With this commit flow can be asked to either use CPR (`--use-cpr=true --matrix-add-well-contributions=true`) or to use the flexible solvers bx setting the `--linear-solver-configuration` option. In all other cases the usual solver implementations are still used.
Note that the flexible solvers still need `--matrix-add-well-contributions=true` and hence cannot cope with multi-segment wells.

Make flexible solvers and CPR accessible for flow binary.

---

opm/simulators/linalg/ParallelOverlappingILU0.hpp

If the user requested CPR/AMG with ILU0, the uninitialized valued caused an arbritrary (quite high) fill-in level to be used which stalled the computation and exhausted memory when running parallel.
Contains only the fix from PR #2601

Fixed unitialized value for ILU when using flexible solvers.

---

opm/simulators/linalg/ISTLSolverEbos.hpp

There was a time when we supported a different matrix for the preconditioner but that option must have been silently dropped somewhen. Still there were several variables in the code for it present which are dropped with this PR.
In addition I discovered that we sometimes use the wrong matrix (derefernced nullptr) for scaling and fixed.
Based on PR #2608

Use correct matrix for scaling and get rid of unused preconditioner matrix member

---

CMakeLists_files.cmake
opm/simulators/linalg/MatrixMarketSpecializations.hpp
opm/simulators/linalg/WriteSystemMatrixHelper.hpp

Code was copied from Dune and not placed in its own file. This is unfortunate, and muddles ownership and license issues, for which I apologize (I was the one who did this). The content in question has been placed in its own file, with a notice at the top about origin and license.
Turns out there was another issue: the WriteSystemMatrixHelper.hpp file was never added to the file list for installation, so it could presumably cause failures downstream. That has also been addressed here.
@blattms please indicate if you think this is a good way to handle the issue.

Split file to ensure correct authorship and license is applied.

---

flow/flow_ebos_blackoil.cpp
flow/flow_ebos_blackoil.hpp
opm/simulators/flow/Main.hpp

NOTE: this pull request depends on #2555 which should be merged first.
A rewrite/resubmission of the outdated PR #2543.
Refactors `flow_ebos_blackoil.cpp` such that we can choose not to execute the whole simulation using the `flowEbosBlackoilMain()` function but instead only initialize by calling `flowEbosBlackoilMainInit()`. This is necessary in order to implement a Python `step()` method that can advance the simulator one report step at a time.
Also adds a method `initFlowEbosBlackoil()` to `Main.hpp` that can be used directly from the Python interface's `BlackOilSimulator` object to gain access to the `FlowMainEbos` object before it has initialized the simulation main loop.

Refactors flow_ebos_blackoil.cpp (2)

---

opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/bda/BdaBridge.cpp
opm/simulators/linalg/bda/BdaBridge.hpp

Due to the changes in #2613 we experienced linker errors as the matrix passed to the `BdaBridge` was made const there and these functions have not been instantiated. But the bridge needs a mutable matrix as it overwriter zero diagonal values. This PR uses a const cast to pass a mutable matrix to the BdaBridge to fix this. In addition we simplify the explcite template instantiation a bit with a macro.

Fix Gpu fallout pr 2612

---

opm/simulators/linalg/PreconditionerFactory.hpp

This allows us to set the ILU width and MILU variant. Some people experienced compile issues with this, let's see if Jenkins is ok.
I have also set the relaxation to 1.0 as discussed in #2601, now in a separate commit.

Specialize amgSmootherArgs() for ParallelOverlappingILU0

---

opm/simulators/linalg/setupPropertyTree_impl.hpp

Previously, we always used quasiimpes.

Use "trueimpes" for weight_type for configuration cpr_trueimpes.

---

flow/flow_ebos_blackoil.cpp
python/CMakeLists.txt
python/simulators/CMakeLists.txt

- Quell unused parameter warnings
- Fix build for python bindings in a super-build
- Quell (shadowing) warnings from PyBind11

Some janitoring

---

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp

Made the construct of timestepping use the same parts of tuning as the updateTuning. This fixed a problem with using tuning in restart runs.

made constructor consistent with updateTuning

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

This writes a single message about switching for groups, including what it is switching from and to, which is consistent for injectors and producers. The master is wrong for injectors, where it will print "Group X exceeding RATE..." if it is RATE it is switching *from* (not to).

Correct messages for group control switching.

---

opm/simulators/linalg/setupPropertyTree_impl.hpp

Based on the config posted by @hnil in PR #2608, we use trueimpes as default. Still we only use 1 step of pre- and postsmoothing as this is faster for Norne than what was proposed. Added some more cleanups without any effects, tool
Total time
| trueimpes 2 steps | trueimpes 1 step | quasiimpes 1 step |
|---|---|---|
| 640 | 594 | 650 |

Modify cpr defaults (for better performance)

---

opm/simulators/linalg/ISTLSolverEbos.hpp

This added to ISTLSolverEbosFlexible in PRs #2593 and #2594  and should be available form ISTLSolverEbos for consistency reasons, too. Done with this commit.

Write out the linear system when ultra high verbosity is requested.

---

CMakeLists_files.cmake
opm/simulators/linalg/bda/MultisegmentWellContribution.cpp
opm/simulators/linalg/bda/MultisegmentWellContribution.hpp
opm/simulators/linalg/bda/WellContributions.cu
opm/simulators/linalg/bda/WellContributions.hpp
opm/simulators/linalg/bda/cuda_header.hpp
opm/simulators/linalg/bda/cusparseSolverBackend.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

The MultisegmentWells are actually applied on CPU via SuiteSparse/UMFPACK.
some notes:
- The MultisegmentWells are applied on the CPU, this involves copying vectors x and y to the CPU, applying C, applying D using UMFPACK, applying B, copying vector y to the GPU. This is done twice per linear iteration, and incurs huge transfer costs. Applying the MultisegmentWells fully on GPU can be done in a later PR.
- The cusparseSolver object receives a WellContributions object, this object contains the data for StandardWells, plus a vector with pointers to MultisegmentWellContribution objects. StandardWells are applied simultaneously on GPU, thus their data should be in 1 array. MultisegmentWells are applied sequentially on CPU.
- An OpmLog::warning is printed if BlackoilWellModel cannot determine …

cusparseSolver can now handle MultisegmentWells

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

Check GCONSALE Limits: Remove Unused Variable

---

ebos/eclbasevanguard.hh

See discussion here: https://github.com/OPM/opm-common/issues/1396
Since some time ago the basic initialize restarted run from the restart file has been merged, and it works for all the restart tests in our test-suite, and also two field cases from Equinor. *But* - it certainly will not work for a lot of models, so when this PR is merged people's restart cases might very well break. They can get the current working behavior back with `--sched-restart=True`. There will be many fallouts which must be fixed, I can certainly do my part in fixing these fallouts - but I it will be a large task and I can not do it alone. 
During the discussion as part of https://github.com/OPM/opm-common/issues/1396 it was agreed that initializing from the restart file was the correct way to go, if we are to …

Default to initialize from restart file in case of restarted run

---

opm-simulators-prereqs.cmake

UMFPack is used unconditionally in the multisegment well code.
To fully work this also needs OPM/opm-common#1796

Mark SuiteSparse as required.

---

ebos/eclbaseaquifermodel.hh
ebos/eclbasevanguard.hh
ebos/eclequilinitializer.hh
ebos/eclfluxmodule.hh
ebos/eclthresholdpressure.hh
ebos/ecltransmissibility.hh
ebos/eclwellmanager.hh
ebos/equil/initstateequil.hh
ebos/startEbos.hh
ebos/vtkecltracermodule.hh
flow/flow_blackoil_dunecpr.cpp
flow/flow_onephase.cpp
flow/flow_onephase_energy.cpp
opm/simulators/flow/BlackoilModelParametersEbos.hpp
opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/NonlinearSolverEbos.hpp
opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
opm/simulators/linalg/FlowLinearSolverParameters.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp

`NEW_PROP_TAG` is now a definition and not just a declaration.
Eliminate superfluous declarations, include headers with definitions.
Make one necessary forward declaration explicit.
Has to be merged at the same time as OPM/opm-models#591

adapt to changes in the property system

---

opm/simulators/flow/FlowMainEbos.hpp

A resubmission of commit b25f489 in PR #2403 and PR #2441 to work with the current master.
Continues the work in PR #2619 to refactor `FlowMainEbos.hpp` to work with the Python bindings.
We need to refactor `runSimulator()` to avoid code duplication when `executeStepInit()` is implemented (to be called from the Python interface and implemented in a upcoming PR). Here, `runSimulator()` is refactored into a `runSimulatorInitOrRun()` that takes a callback function. When `runSimulatorInit()` is implemented (upcoming PR) it will pass a different callback that only initializes the simulator. Currently, `runSimulator()` passes the callback `runSimulatorRunCallback_()` which runs the whole simulation. The code outputting the simulation summary in `runSimulator()` is also refactored into a …

Refactor runSimulator().

---

ebos/eclbasevanguard.hh

Without this, rank 0 gets an empty case name, resulting in buggy VTK output with filenames containing the genereric stem "sim" rather than the case name as stem.

Always create proper case name.

---

opm/simulators/flow/BlackoilModelParametersEbos.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp

The motivation for this PR is to improve the convergence on the 9_4E_..MSW test case in opm-models. The number of convergence failures for the well goes from 7466 in master to 0. (with enable-tuning=true)  Needs testing no bigger models.

Improve convergence msw

---

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp

This fixes a bug that would tag a well as consistently failing (i.e. for three chops) even if it had only caused chopping once. Also reduces the default minimum timestep reached before we check for consistently failing wells, as the existing default was deemed too strict and close down wells earlier than necessary. This could have some performance penalty, in that we might waste more iterations only to drop a well and restart the step, but as well closures are relatively speaking uncommon events, it is not likely to be noticeable.

Fix bug in well closing, and allow more chopping by default.

---

opm/simulators/flow/Main.hpp

Previously only the master process was aware of the error and flow did
deadlock in parallel runs if there were parser errors
encountered. With this commit all processes are made aware of the
problem and flow aborts with an error code.

Prevent deadlock after parsing if there were error in parallel

---

CMakeLists.txt
CMakeLists_files.cmake
opm/simulators/utils/moduleVersion.cpp

this to minimize re-linking due to compile timestamp support
Downstream of https://github.com/OPM/opm-common/pull/1812

changed: move moduleVersion to a separate object library

---

compareECLFiles.cmake
tests/run-parallel-restart-regressionTest.sh

- The parallel test gets a designated driver
- The serial test is run with default adpative timestepping
The main point about these changes is to enable the base run to go with `--enable-adaptive-time-stepping=true` - which is required to get the the base run of: #2658 through

Changes in running of restart regression tests

---

CMakeLists.txt

we need the update-version target to run to generate the
necessary headers.

fixed: fix parallel builds

---

ebos/eclmpiserializer.hh
opm/simulators/wells/MultisegmentWell_impl.hpp

Downstream of: https://github.com/OPM/opm-common/pull/1801
~~This code is not yet ready; while refactoring I discovered a method in the MSW implementation which actually mutated the `SpiralICD` instance held by the Schedule object - that was technically allowed in the previous api which had `const std::shared_ptr< mutable >` - but was it intentional - seems suspicious to me!̃~~
Hmmm: pack and unpack of std::variant<> - seems tricky?

Use std::variant access to Segment::icd

---

opm/simulators/utils/ParallelRestart.hpp

The 'std::string' case is covered by a call to ADD_PACK_PROTOTYPES.
This resolves #2513.

Remove Redundant 'packSize' Declaration

---

tests/update_reference_data.sh

This way we are less at risk of overrunning GitHub's 256 character limit for issue/PR title lengths when a PR happens to affect many regression tests.

update_data: Move List of Changed Tests to Commit Message Body

---

ebos/eclthresholdpressure.hh

this was harmless unless enableExperiments was given, since
the deck ref is not used otherwise, but it caused an UBSAN issue
when run in parallel.

changed: delay deck dereference

---

ebos/ecltransmissibility.hh
ebos/eclwriter.hh

Up to now We always assumed that cardDims[i]>1 holds. which it does for most of the cases. But when e.g. simulating a vertical stack of 5 cells flow would report the transmissibilities in the Z direction in TRANX and output TRANZ as zero. Similar problems should be there for 2D grids.
With this commit we actually check whether there can be neighbors in the X and Y direction to prevent this behavior.

[bugfix] Fix TRANXYZ for problems with less than 3 dimensions.

---

compareECLFiles.cmake

Testing of #2661 indicates that something is not working as expected when restarting MSW without reading the schedule part. This modifies the test to let #2661 through.

change MSW restart test to read the schedule

---

compareECLFiles.cmake
opm/simulators/wells/MSWellHelpers.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

Tested on some relevant test cases and on the big model. 
It mixes pressure derivatives for the density calculations. But since the pressure does not vary to much it should not matter much, but it may introduce some inaccuracy in the matrix.

Fix upwinding for friction, acceleration, valve and SIGD for MSW

---

opm/simulators/utils/ParallelRestart.cpp

See: https://github.com/OPM/opm-common/pull/1823
This patch (from @bska) recovers serial build on my machine

Add actionState argument also for non MPI branch

---

CMakeLists_files.cmake
opm/simulators/linalg/FlexibleSolver.cpp
opm/simulators/linalg/FlexibleSolver.hpp
opm/simulators/linalg/FlexibleSolver1.cpp
opm/simulators/linalg/FlexibleSolver2.cpp
opm/simulators/linalg/FlexibleSolver3.cpp
opm/simulators/linalg/FlexibleSolver4.cpp
opm/simulators/linalg/FlexibleSolver_impl.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/linalg/PressureSolverPolicy.hpp
tests/test_flexiblesolver.cpp

This is a sketch of an attempt to reduce compile times related to the linear solver subsystems. The code right here successfully compiles and links the test_flexiblesolver.cpp unit test, but not Flow. However, but exchanging which lines are commented in/out in the "explicit instantiations" section, *and* changing the signature of one of the constructors to avoid using `enable_if` I get Flow to link. My immediate concerns are:
- Is there a way to get things to link properly without changing any of the FlexibleSolver interface? (Constructor signature issue.)
- Is there a robust way to keep all the code in the usual header file, for clients that do not want to or cannot link to a pre-instantiated target, while at the same time avoiding that code being used to instantiate for Flow? I can only …

Use explicit instantiation for FlexibleSolver to reduce compile times.

---

opm/simulators/flow/Main.hpp

avoids unused warnings when building without

make parseSuccess dependent on MPI

---

opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp

A resubmission of commit bb20804 in PR #2403 and PR #2442 to work with the current master.
Continues the work in #2619 and #2631 to refactor main simulation loop in `flow` to work with the Python bindings.
The `run()` method in `SimulatorFullyImplicitBlackoilEbos.hpp` is refactored in preparation for the implementation of a Python `step()` (and `step_init()`) function (to be implemented in a later commit). Currently `run()` is called from `runSimulatorInitOrRun()` in `FlowMainEbos.hpp` using the `runSimulatorRunCallback_()`. Later, there will be other callbacks like `runSimulatorStepInitCallback_()`, and `runSimulatorStepCallback_()`, that will need to call different parts of the code in `run()`. The `run()` function is thus refactored into `run()`, `runInit()`, `runStep()`, and …

Refactor run() in `SimulatorFullyImplicitBlackoilEbos.hpp`

---

opm/simulators/linalg/ISTLSolverEbos.hpp

Simply removes the superfluent and wrong copy in ISTLSolverEbos::solve and in addition uses ISTLSolverEbos::getMatrix() more consistently.
`--owner-cells-first` should go eventually if the flexible solvers support operators.
Alternative to #2681 as described there.

Alternative fix running in parallel with --owner-cells-first=false

---

CMakeLists_files.cmake
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/WellOperators.hpp

This introduces a new class WellModelAsLinearOperator adapting a well model (only) into an actual Dune::LinearOperator, this prevents the TypeTag dependent type from leaking into the type of i.e. the WellModelMatrixAdapter instantiation.
As a side benefit, the adapter classes can now adapt (i.e. combine with a matrix operator) any linear operator. They could be renamed as a consequence, but I think that is better left alone until we actually change usage.

Move well operators to separate file, and generalize

---

opm/simulators/linalg/PreconditionerFactory.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp

The new constructor requires information that is available in the communicator, but not directly. I have not seen a performance loss compared to existing default. The necessary processing takes place only when constructing the preconditioner, not updating it, so when/if we move to update rather than recreate the preconditioner also for ILU0 there will be a small gain there.
If the required information (that the ordering is "ghost last") can be obtained in an easier way from the communication object I would be happy to change this! Unfortunately making a new communication subclass will not work due to some explicit specializations for OwnerOverlapCommunication in dune-istl. Other ways of passing "extra info" to the factory can also be considered. For now I think this is an acceptable …

Make ghost-last feature available in PreconditionerFactory.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

This reduce oscillations on the big model. 
Needs some more testing before it can be merged.

use rates from previous time-step in the guiderate conversion 

---

opm/simulators/linalg/FlexibleSolver.hpp
opm/simulators/linalg/FlexibleSolver_impl.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/linalg/PressureSolverPolicy.hpp
tests/test_flexiblesolver.cpp

This changes the FlexibleSolver to be constructed using a `Dune::AssembledLinearOperator<Matrix, Vector, Vector>` instead of a `Matrix`. (The `Matrix` and `Vector` template arguments to the class are the same as before.)
The preconditioners will be constructed passing the operator's getmat() result, while the operator itself will be used in the iterative solvers. So the wells-as-operator approach can now be used. On Norne, I get bitwise identical results with ILU0 through FlexibleSolver as I get with the default solver (tested with 8 processes). For some preconditioners such as CPR, it looks as if it is still preferable to have --matrix-add-well-contributions=true, but at least the space of possibilities is now wider.

Allow well operators with FlexibleSolver.

---

opm/simulators/linalg/PressureSolverPolicy.hpp

This commit makes the constructor` PressureInverseOperator` that accepts a `Dune::OwnerOverlapCopyCommunication<>` object contingent on having MPI.  The type does not exist otherwise.

Don't Name Type that does not Exist in Sequential Configurations

---

ebos/collecttoiorank.hh
ebos/eclwellmanager.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

This commit makes the 'groupData()' function return a
```C++
map<string, Opm::data::GroupData>
```
object instead of a
```C++
map<string, Opm::data::GroupConstraints>
```
object.  The `GroupData` structure adds a level of indirection to the current per-group summary quantities that are directly assigned by the simulator.  While here, also move the assignment of the current group constraints/control values out to a separate helper to reduce the body of the per-group loop in `groupData()`.
This is in preparation of adding support for reporting group-level production/injection guiderates (`G[OGW][IP]GR`) to the summary file.
---
Note: This PR is the companion to upstream PR OPM/opm-common#1853.  This PR **must not** be merged without also merging the upstream PR lest there be a build break.

Simulator Group Data: Chase Upstream API Update

---

opm/simulators/linalg/bda/WellContributions.cpp
opm/simulators/linalg/bda/openclSolverBackend.cpp

PR #2682 introduced some new warnings (shadowing variables, and catching exceptions by value). This PR fixes them.
Would be nice if @Tongdongq would tell his 2 cents on this (especially the shadowed variables).

Fix some warnings in the OpenCl Solver.

---

CMakeLists.txt

This caused compile failure on a system without the c++ OpenCL binding header cl.hpp.
I will self-merge when green since it is an obvious bug, and since it is critical for me (causes build failure).

Fix CMake variable case bug.

---

opm/simulators/linalg/bda/WellContributions.cpp
opm/simulators/linalg/bda/WellContributions.cu
opm/simulators/linalg/bda/WellContributions.hpp

With Multisegment wells we allocate WellContributions::hx and hy with `CudaMallocHost`. Yet we tried to deallocate them with `delete[]`. This caused segementation faults e.g. for model1/MSW_MODEL_1. Now we use `CudaFreeHost` for freeing if we used CUDA.
Closes #2719

Also free memory allocated with CUDA later with CUDA

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

Alternatively it could be marked as [[maybe_unused]] if it will be used sometime in the future.

Remove unused variable groups from BlackoilWellModel::wellsToState.

---

opm/simulators/wells/MSWellHelpers.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

Currently, we decompose the diagonal matrix every time we apply the well equations. With this change we will store the decomoposition and reuse whenever possible. This will ease the fixing of #2654 and save an additional decomposition there.  But already now this speeds up computation by ~3%. 
Iteration counts stay exactly the same with this change.

Reuse umfpack decomposition for multisegment wells.

---

opm/simulators/utils/ParallelRestart.cpp

need to have this data on non-root processes.

fixed: have to broadcast summarystate on restart

---

flow/flow_ebos_blackoil.cpp
flow/flow_ebos_brine.cpp
flow/flow_ebos_energy.cpp
flow/flow_ebos_foam.cpp
flow/flow_ebos_gasoil.cpp
flow/flow_ebos_oilwater.cpp
flow/flow_ebos_oilwater_brine.cpp
flow/flow_ebos_oilwater_polymer.cpp
flow/flow_ebos_oilwater_polymer_injectivity.cpp
flow/flow_ebos_polymer.cpp
flow/flow_ebos_solvent.cpp
opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/Main.hpp

Make `Opm::FlowMainEbos` capture the variables `argc`, `argv`, `outputCout`, and `outputFiles`. Passing the variables to the constructor and saving them as class variables in `Opm::FlowMainEbos` makes the implementation of the Python interface simpler. For example, the `step_init()` method (see PR #2690) does not need to ask `Opm::Main` about the values of the variables when it needs to run `execute()` in `FlowMainEbos`.
Another advantage of this refactoring could be that less variables needs to be passed around from `Opm::Main`, to the static flow modules `flow_ebos_xxx.cpp`, and then again to `FlowMainEbos`.

Capture the variables argc, argv, outputCout, and outputFiles in Opm::FlowMainEbos

---

opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/Main.hpp
opm/simulators/flow/python/simulators.hpp
python/simulators/CMakeLists.txt
python/simulators/simulators.cpp

Note: This PR depends on #2689 which should be merged first.
A resubmission of commit 11eaa3d7 in PR #2403 and PR #2443 and continues the work in #2555 implementing Python bindings to the flow simulator.
The step_init() method initializes the simulation. It is required for the Python script to run step_init() before calling the step() method (which will be implemented in the next commit).

Implements the Python step_init() function

---

opm/simulators/flow/BlackoilModelEbos.hpp
opm/simulators/flow/BlackoilModelParametersEbos.hpp

Previously we used relaxed tolerance once a certain number of Newton steps was exceeded. Now we check for all cells violating CNV locally and if their pore volume is less than a certaun fraction (default 3%) we use the relaxed tolerance (default: 1e9)
Original idea originated from Norce / @andlaus / @totto82 and was introduced in ebos.
This decreases runtime 
| model | branch | total time |
|---|---|---|
| Norne | master | 614 |
| Norne | PR  | 552|
| Model2 | master | 3411 |
| Model2 | PR | 2876 |
If somebody has better name than RelaxedMaxPvFraction for the command line parameter then I am happy to change them. Maybe they should be the same as for ebos (EclNewtonRelaxedVolumeFraction)?

relaxed tolerance for CNV if only small fraction of PV is violated

---

opm/simulators/flow/BlackoilModelEbos.hpp
opm/simulators/flow/BlackoilModelParametersEbos.hpp

Default values are MaxStrictIter=8 and RelaxedPvFraction=1.0.
To activate relaxed pv fraction set MaxStrictIter to 0 and
fraction below 1.

Finally fix selection for relaxed tolerance.

---

ebos/eclmpiserializer.hh

See discussion here: https://github.com/OPM/opm-simulators/pull/2733
I fully acknowledge @bska's point, but I see no other way around this than reintroducing the `const_cast< >`. Unless someone as a better alternative I intend to merge this solution.
Upstream: https://github.com/OPM/opm-common/pull/1886

Use const_cast< > in variant serialization

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

Especially, grab a copy of the "oldControl" to avoid reading through a reference for which the underlying object is reset in
```
setCurrent*GroupControl()
```
This in turn avoids generating confusing diagnostic messages of the form
```
Switching production control mode for group G from FLD to FLD
```

Broken Constraints: Fix Diagnostic Message

---

ebos/eclproblem.hh

Remove left parenthesis character left over from transitioning to the type-based parameter system.  The `'('` produced a build failure which only manifested in debug builds.
Thanks to Håkon Hægland for bringing the issue to our attention.
Fixes #2747.

Fix Debug Build

---

opm/simulators/timestepping/ConvergenceReport.hpp
opm/simulators/timestepping/gatherConvergenceReport.cpp
opm/simulators/wells/WellConnectionAuxiliaryModule.hpp
opm/simulators/wells/WellInterface_impl.hpp

avoids unnecessary copies.
quells some clang(-10) warnings.

fixed: use const refs in foreach constructs

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This PR adds support for reporting the simulator's guiderate values at the well and group levels to the output layer through the `wellData()` and `groupData()` member functions.  We add several new member functions that collectively assemble the values and assign them to objects of type `Opm::data::GuideRateValue` (PR OPM/opm-common#1868) for subsequent output to the summary and restart files.
In particular
```
getGuideRateValues(const Well&) const
getGuideRateValues(const Group&) const
```
retrieve the guiderate values for all phases for those individual wells and groups for which the `guideRate_` data member defines a value.  The most complicated function of this PR is
```
calculateAllGroupGuideRates
```
which aggregates those individual contributions from the well (leaf) level up to …

Report Guiderates at Well and Group Levels

---

opm/simulators/linalg/bda/WellContributions.cpp

These seemed familar and I would have sworn that I already fixed them
somewhen. Might have been reintroduced by rebasing.

[opencl] Fixes shadowing variable warnings.

---

opm/simulators/flow/Main.hpp

Also re-add the ability to do strict parsing.
I would add that there are some details of this code I still suspect may not be 100% correct after the summer's refactoring. For example, we pass a `nullptr` for the `unique_ptr<ErrorGuard>` argument of `readDeck()`, and construct a default one on the inside, not sure why?

Reinstate lost logging of header and parameters.

---

opm/simulators/flow/Main.hpp

…and tell the user the deck has been read.
This is a very minor improvement, but without it a user or developer can easily assume that the simulator hangs or spends excessive time on deck reading whereas it actually hangs or is slow in a later part of the initialization.

Use log mechanism for info output

---

opm/simulators/wells/RateConverter.hpp

RateConverter itself already copies this and offers the mapping.
With this commit we just use that.

Prevent another copy of cell to region mapping in RateConverter.

---

opm/simulators/timestepping/SimulatorReport.cpp
opm/simulators/timestepping/SimulatorReport.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

And changes the indentation of the linear solver setup time a little to show it is part of the linear solve time.
Basically, we want to monitor how costly the well related code. 
The summary of the timing looks like the following with this PR for SPE1 case running. 
```
Number of MPI processes:      1
Threads per MPI process:      2
Total time (seconds):         14.6889
Solver time (seconds):        14.6547
Assembly time (seconds):     4.83799 (Failed: 0; 0%)
Well assembly time (seconds): 1.33701 (Failed: 0; 0%)
Linear solve time (seconds): 9.04144 (Failed: 0; 0%)
Linear solve setup time (seconds): 0.000130328 (Failed: 0; 0%)
Update time (seconds):       0.242177 (Failed: 0; 0%)
Output write time (seconds): 0.0977013
Overall Well Iterations:      0 (Failed: 0; -nan%)
Overall …
```

adding timing for the well assembly

---

ebos/collecttoiorank.hh
ebos/ecloutputblackoilmodule.hh

We used a method isGlobalIdxOnThisRank to determine whether to write
an entry for a summary keyword (like BPR). Unfortunately, this did
exactly what the name suggested, but we actually passed a cartesian
index to it. That meant that a lower cartesian index might have found on
many processes (with different cartesian index and hence resulting in
wrong values), while higher for ones no process would have been found
with it (resulting in writing zeros).
With this commit we store a sorted list of cartesian indices and query
that in the renamed and restructured function isCartesianidxOnThisRank.
Most probably this broke during refactoring.
Closes #2665

Fixes determining whether index of summary keyword is on process.

---

ebos/ecltransmissibility.hh

It really fixes only this and tries to make the code simpler and less opaque.
There are still other bugs in the pinch treatment, tough (see #2776). But these will need some update_data and are more risky. One should consider merging this before

fix insideCartElmIdx and outsideCartElmIdx order for faces in parallel (2) 

---

compareECLFiles.cmake
tests/update_reference_data.sh

Add regression for [this](https://github.com/OPM/opm-tests/blob/master/pinch/PINCH_MULTZ_ALL_BARRIER.DATA) case. ~~Should be ready to be merged when https://github.com/OPM/opm-common/pull/1905 has been merged~~

Add test of PINCH::ALL + MULTZ with a barrier

---

ebos/ecltransmissibility.hh

Proposal of fix to potential bug found in discussion of #2773, it includes that PR.
Using just one direction seemed wrong as we use both the smallest multiplier is requested and TransMult might store values for both directions. Hence this commit makes the behaviour consistent in both cases.
Note that we take the minimum in one direction and apply that and then in the other directions and apply that. Hence the two minimums might belong to different faces of the cartesian grid.  
One could of course insist that the multipliers belong to the same undirectional face.

Apply minimum of Z multiplier for PINCH(5)==ALL, Prepare for PINCH(5)==TOP

---

opm/simulators/flow/MissingFeatures.cpp

Updating the missing features list.

Removed OPERATER and OPERNUM since they are supported.

---

opm/simulators/utils/readDeck.cpp

As the ErrorGuard also dumps warnings we now always dump it (previously only on error) to get these messages in the
console.
If there are error encountered, we log a meaningful error message (the real cause was missing previously) and do a
graceful exit after MPI_Finalize.
Close #2764

Improves error handling and reporting in parallel.

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This is intended to improve the parallel scalability of a part of the well code by reducing the number of comm.sum() calls doing all-all communication to just one call, instead of one per well and several per group. Not expecting large impact until the number of processes gets to 32 or above.

Rewrite communicateGroupRates() to do a single sum().

---

opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/python/simulators.hpp
python/simulators/simulators.cpp

A resubmission of commit 8e4f748 in PR #2403 and PR #2444 and continues the work in #2690 implementing Python bindings to the flow simulator.
The Python `step()` method advances the simulator one report step. Before calling `step()` for the first time, `step_init()` must have been called.

Implements a Python step() method.

---

ebos/ecltransmissibility.hh
opm/simulators/utils/ParallelEclipseState.cpp
opm/simulators/utils/ParallelEclipseState.hpp
opm/simulators/utils/PropsCentroidsDataHandle.hpp

These are the downstream changes from OPM/opm-common#1932.
We now communicate the complete FieldData during the load balancing as this is needed to correctly apply the modifications from the TranCalculator. Of course we also broadcasts its data and store in ParallelFieldPropsmanager. To apply then transmissibility modifications, we copy the calculated transmissibilities to appropriates arrays, apply the modifications using the calculator and afterwards copy them back.

Fixes application of transmissibility modifiers from the edit section.

---

ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
ebos/ecloutputblackoilmodule.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

Previously, we exported an unordered map containing all names of wells that are not present in the local part of the grid.
As we envision to have wells that are distributed across multiple processors, this information does not seem to be enough. We need
to be able to set up communication for each well. To do this we need to find out who handles perforations of each well.
We now export a full list of well name together with a boolean indicating whether it perforates local cells (vector of pair of string
and bool).
downstream of OPM/opm-grid#487

Refactored how well information is exported after load balancing.

---

compareECLFiles.cmake
ebos/eclproblem.hh
opm/simulators/flow/BlackoilModelParametersEbos.hpp

Following the implementation in https://github.com/OPM/opm-simulators/pull/2701 it is natural to revisit our default numerical parameters. This is a tedious process, checking numerical performance, scaling and accuracy of solution. Given the many parameters involved, I suggest doing it in a step-wise fashion. This is the first step. I have tested on a large number of models at this point and believe that the changes here consistently improve computational time, both on single- and MPI-simulations. I also believe the accuracy of the solution and robustness of the numerics is improved across the board. Hence, I suggest this is reviewed/merged, while work continues to find more improvements.

New numerical defaults

---

ebos/eclproblem.hh
opm/simulators/flow/BlackoilModelEbos.hpp

1) This makes sure that the intensive quantities is always available i.e. we can quarry them directly from the cache. 
2) It make sure that the update of the intensive quantities are done at a reasonable place. I.e. currently it is most often done in the assembly of the well model -> strange timing 
3) Update of the intensive quantities is expensive. This make sure it is done using OPENMP. Since this is currently done in a loop in the well model that is not parallel. This gives a speed up if more than 1 tread is used. 
Depends on OPM/opm-models#626

Invalidate and update the intensive quantities at the same time

---

CMakeLists.txt
external/fmtlib/LICENSE.rst
external/fmtlib/README.opm
external/fmtlib/include/fmt/chrono.h
external/fmtlib/include/fmt/color.h
external/fmtlib/include/fmt/compile.h
external/fmtlib/include/fmt/core.h
external/fmtlib/include/fmt/format-inl.h
external/fmtlib/include/fmt/format.h
external/fmtlib/include/fmt/locale.h
external/fmtlib/include/fmt/os.h
external/fmtlib/include/fmt/ostream.h
external/fmtlib/include/fmt/posix.h
external/fmtlib/include/fmt/printf.h
external/fmtlib/include/fmt/ranges.h
opm/simulators/utils/readDeck.cpp

This is part of the effort to improve error messages. A pattern we have had in flow is that the error message is displayed more than one time - typically with different formatting for a nice visual effect. While working on this I try to enforce the following principle:
1. At the point where we have all relevant context - that might be right when the error is encountered or a couple of frames up - we issue a call to `OpmLog::error()` and throw an exception.
2. If/when we catch the exception at a later stage **we trust that the error message has already reached the user with the previous call to `OpmLog::error()`, and do not output `exc.what()` in any way**. 
Th gist of this PR is that the error messages (i.e. `exception.what()`) is not output again in the `readDeck()` code - we trust that …

Flow exceptions

---

CMakeLists.txt
python/simulators/CMakeLists.txt

This avoids rebuilding the objects for the python binding if the binding is built inline with the main buildsystem.
Reduces build time on jenkins a little.

changed: reuse objects if building python inline

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftRuntime.hpp
opm/simulators/wells/GasLiftRuntime_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

Depends on https://github.com/OPM/opm-common/pull/1968.
Implements gas lift optimization for a single well. Support for gas lift optimization for multi-segment wells, groups of wells and networks is not implemented yet.
The keywords `LIFTOPT`, `WLIFTOPT`, and `VFPPROD` are used to supply parameters for the optimization. Also adds support for summary output of liftgas injection rate via summary keyword `WGLIR`.

Implements support for gas lift optimization.

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

also use the bool conditions for conditional deref'ing with the indices.
this helps avoid maybe uninitialized warnings with gcc.
please review carefully, but i think this should be equivalent.

fixed: make some indices constexpr

---

opm/simulators/linalg/ParallelOverlappingILU0.hpp
opm/simulators/timestepping/ConvergenceReport.hpp
opm/simulators/timestepping/gatherConvergenceReport.cpp
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/gatherDeferredLogger.cpp

New clang version, new warnings...
This bunch is all about using references in range-for loops. Or not, for `vector<bool>`, of course!

Silence warnings from range-for.

---

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
opm/simulators/timestepping/TimeStepControl.cpp
opm/simulators/timestepping/TimeStepControl.hpp

This PR adds
- a new timestepping options "newtoniterationcount" which increase(decrease) timestep if number of newton iterations is smaller(larger) than the target newton iterations. The increase and decrease is give by TimeStepControlGrowthRate and TimeStepControlDecayRate
- a option to control the damping of the pid+(newton)iteration control
TimeStepControlGrowthDampingFactor
TimeStepControlDecayDampingFactor  
can be used to damp the increase/decrease of the timestep based on iterations counts. 
Defaults stays the same --> does not change any results.

add options for timestepping

---

CMakeLists_files.cmake
opm/simulators/wells/WellProdIndexCalculator.cpp
opm/simulators/wells/WellProdIndexCalculator.hpp
tests/test_wellprodindexcalculator.cpp

Switches between using the logarithmic and unit scaling factor based on whether or not the well has an explicit, positive drainage radius (`WELSPECS` item 7).  Does presently not include the D factor.
Add a set of unit tests to exercise the facility.

Add Calculator for Connection/Well Productivity Index

---

opm/simulators/linalg/bda/MultisegmentWellContribution.hpp
opm/simulators/linalg/bda/WellContributions.hpp

nvcc exits compilation if the header dune/istl/basearray.hh (form DUNE 2.6) is included as it does not seem to understand the friend declaration there (friend class for a struct).
```
/usr/include/dune/istl/basearray.hh:101:49: error: ‘typename Dune::Imp::base_array_unmanaged<B, A>::RealIterator’ names ‘template<class B, class A> template<class T> struct Dune::Imp::base_array_unmanaged<B, A>::RealIterator’, which is not a type
friend class RealIterator<const ValueType>;
^
```

Fixes compilation of CUDA.

---

CMakeLists.txt

more than 4 is problematic on some build machines.
please backport.

changed: run tests on 4 processors

---

opm/simulators/wells/WellState.hpp

Injection temperature reported was always 68 F (=20C) irrespective of temperature set by  WTEMP.
Now the  temperature as set by WTEMP is reported for the injector, which is consistent with commercial simulator.
For nonthermal decks both injectors and producers report now the standard condition temperature of 60 F (=15.56 C).
For thermal decks,  I am planning to make producers report the temperature at same reference depth as the BHP.

fix temperature reporting for injectors

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

The Polymer, Brine, and Solvent quantities would be extracted from elements `0..#perf-1` of their pertinent container rather than from the elements associated to the particular well.

Extract Correct Connection-Level Rates

---

ebos/eclbasevanguard.hh

Unfortunately restarting without reading historic schedule is a long term effort. In order to avoid excessive problems for users, I suggest we switch the default until we are closer to support restarting without historic schedule available.

Switch default for restarting to read historic schedule

---

opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/python/simulators.hpp
python/simulators/simulators.cpp

Implements a Python `step_cleanup()` method.
Continues the work in #2735 on implementing Python bindings for `flow`. The `step_cleanup()` method should be called after the last `step()` call to finalize the simulation.

Implements a Python step_cleanup() method.

---

opm/simulators/linalg/PreconditionerFactory.hpp
opm/simulators/linalg/setupPropertyTree.cpp

In OPM the matrix graph might be unsymmetric as we do not store the full sparsity pattern for copy rows but only the diagonal.
Unfortunately, DUNE assumes that matrices from finite elements and finite volumes have a symmetric sparsity pattern for copy rows to and uses this assumption to create the graphs for PTScotch/ParMETIS more easily. But PTScotch/ParMetis assume a symmetric graph.
Closes #2894 for me.
There are other possible (and better) fixes mentioned in #2894. But this one seemed the quickest and should be good enough for the release (Reverting OPM/opm-common#2061 would not cut it for ParMETIS).

Always accumulates data in AMG to 1 process on coarse levels.

---

opm/simulators/wells/StandardWell_impl.hpp

1) Corrected phaseIsActive with PhaseIdx argument instead of CompIdx argument in "subtraction of dissolved gas from oil phase and vapporized oil from gas phase".
2) Fix for well accumulation calculation in case oil is absent.

Two fixes in StandardWell_impl.hpp

---

compareECLFiles.cmake
opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp

Our default time stepping routine is too aggressive, by in\creasing time step until convergence failure. By letting the next time step cut back a little when we exceed eight newton iterations, we can avoid many convergence problems while keeping numerical performance good. This is particularly beneficial in the prediction part of the simulation.

Switched time step control and changed damping factor for it

---

CMakeLists.txt
ebos/eclpolyhedralgridvanguard.hh
ebos/eclproblem.hh
ebos/eclwriter.hh
flow/flow_blackoil_poly.cpp
flow/flow_ebos_blackoil.cpp
opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/linalg/findOverlapRowsAndColumns.hpp

Currently the simulator creates the polyhedreal grid from an eclGrid from opm-common
TODO (but not in this PR)
- make it possible to create the grid directly from DGF or MRST format
- fix issue on norne.
- add a test case to make sure this continues to work
Depends on OPM/opm-grid#500

Make a flow version that uses the polyhedreal grid

---

opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

This changes the innermost part of the well assembly to be a new function calculateSinglePerf(), that is const. Then all the code that modifies the residual and jacobians (or rather, the B, C and D matrices) is in a more compact location (lines 612-643 for per-perforation assembly and lines 649-674 for per-well assembly).
@blattms Hopefully this makes it easier to implement distributed wells. Note that this is still a bit of WIP, and will likely be squashed and modified before merging. Please give feedback on any changes you would like to see to make your job easier.

Refactor well calculations

---

opm/simulators/linalg/MatrixBlock.hpp
opm/simulators/wells/MSWellHelpers.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

This allows the `--matrix-add-well-contributions=true` option for multisegment wells. However the implementation should be considered experimental for the following reasons:
- Very limited testing so far (only small msw test cases from opm-tests, as well as the original "model 2").
- In testing with "model 2" occasional linear solver failures happen, which could indicate either a problem with this code, or more broadly a problem with the MSW formulation itself, or a combination. However, similar solver failures happen also with `--matrix-add-well-contributions=false` when running with cpr, which makes it less likely that the new code is at fault.
- The code inverts the D matrix, which is a square matrix with (4 * number of segments) rows and columns. Inverting a nontrivial matrix is of …

Implement addWellContributions() for multi-segment wells

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/GasLiftRuntime.hpp
opm/simulators/wells/GasLiftRuntime_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

A const well state was passed to functions that were modifying it by calling setALQ(). Now the setALQ() method is made non-const, mutable references to the well state are passed where sensible. The getALQ() method uses map::at() instead of map::operator[] and no longer modifies current_alq_. Removed two unused functions.
With this, it is now easy to see which methods modify the well state and which don't. The alq-related members in the WellStateFullyImplicitBlackoil class are no longer 'mutable'-qualified.
Please verify that the gas lift feature still works with this, I think there is no test for it in jenkins currently? @totto82 @hakonhagland

Make consistent use of const for alq-related state.

---

ebos/ecloutputblackoilmodule.hh

This is a step towards implementing support for the summary keyword `ROEW`, to calculate these values we need access to the original in place values for the different regions. These values must be passed from the simulator to the summary output code. 
The interface for passing non trivial values from the simulator to the summary output is not in a very good shape, this PR contains minimum steps in order to support the ROEW keyword.
Requires: https://github.com/OPM/opm-common/pull/2114

Pass region in place values to the summary writer

---

opm/simulators/wells/StandardWell_impl.hpp

There seems to be no need to assign the same value consecutively as often as there are phases. To the very least it is confusing.

StandardWell only assing primary_variables_[WQTotal] once.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This adds the gas lift rates (as ALQ) into the network calculations to determine pressure drops in the network.

Add the option to include gas lift for network calculations.

---

CMakeLists.txt
debian/rules
python/simulators/CMakeLists.txt

add cmake option to disable the python tests
Due to bugs in the openmpi on bionic, this test fails to execute properly in pbuilder environments. 
Instead of rebuilding openmpi without dynamic loading (which is the suggested fix) and potentially break users
systems, this is a non-intrusive workaround to be used for packaging.
Also add explicit option for python support to make it visible in cmake frontends.

Disable python tests in debian packaging

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This PR ensures that we calculate the well and connection level per-phase steady-state productivity index (PI) at the end of a completed time step (triggered from `endTimeStep()`).
We add a new data member,
```
BlackoilWellModel<>::prod_index_calc_
```
which holds one `WellProdIndexCalculator` for each of the process' local wells and a new interface member function
```
WellInterface::updateProductivityIndex
```
which uses a per-well PI calculator to actually compute the PI values and store those in the `WellState`.  Implement this member function for both `StandardWell` and `MultisegmentWell`.  Were it not for `getMobility` existing only in the derived classes, the two equal implementations could be merged and moved to the interface.
We also add a new data member to the …

Unconditionally Calculate PI at End of Timestep 

---

opm/simulators/linalg/PreconditionerFactory.hpp

Use SymmetricDependency instead of SymmetricMatrixDependency. Our matrices are structurally symmetric, but not numerically symmetric.
This change reduces the number of linear iterations on Norne with CPR by more than 10%, and also reduces the nonlinear iterations by 5%. On model 2, linear iterations are down 20% and Newton iterations 5%.
To reproduce on Norne: use the options `--matrix-add-well-contributions=true --linsolver=cpr`.
To reproduce on model 2 (for best performance): additionally add `--linear-solver-max-iter=30 --linear-solver-reduction=5e-3`.
Change suggested by @hnil.

Use better-suited AMG criterion.

---

ebos/eclcpgridvanguard.hh
opm/simulators/utils/ParallelSerialization.cpp
opm/simulators/utils/ParallelSerialization.hpp

It would remove perforated cells from wells that cross the local domain's border. That would make it impossible to figure out the
first connection. In addition we would not be able to check that the connections exist (as rank 0 would have the complete information -> inconsistency).
This is cherry-picked from the work on distributed wells.
The filtering removes all connections from wells in the schedule that are not in the local domain of the process. It is only performed on processes with rank greater than zero (as zero needs all the information for output?). As currently a process either has all or no possible connections of a well in it's domain and the wells that have none are not treated anyway, this change should have no effect.

Do not filter connections on the schedule of the loadbalanced grid.

---

opm/simulators/linalg/PreconditionerFactory.hpp
opm/simulators/linalg/setupPropertyTree.cpp

This allows more flexibility to change AMG options from a JSON setup. In particular, the prolongationdamping parameter looks like it can significantly improve performance.
The below JSON setup can be used for experimentation. It sets "beta" to 0 and "prolongationdamping" to 1.0, otherwise it is just like the default `--linsolver=cpr` option. Save the file as (for example) "cpr-experiment.json" and use it with `--linsolver=cpr-experiment.json`.
When testing this (or CPR with other parameters) it is still recommended to add `--matrix-add-well-contributions=true`. For some cases such as model 2 it is also good to tighten the linear solver tolerance a little, to for example 5e-3.
Running on 8 processes, Norne runtimes with this is 15-20% faster than the default ILU0 option on my system. For …

Add more AMG options to allow setting from JSON.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

The original code assumed that
```C++
well_container_.size() == numLocalWells()
```
This assumption does not hold when wells open/shut dynamically in the context of `WECON` and/or `WTEST`.
Switch to indexing into the `prod_index_calc_` vector using the well's own linear index instead of manually advancing iterators.
Pointy Hat: [at]bska

Well PI: Use Appropriate Calculator for Each Well

---

ebos/eclproblem.hh

Remove unnecessary check for saturation for single-phase, and remove check for gas saturation  when oil is not present.

Remove unnecessary check for saturations

---

opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell_impl.hpp

This simplifies the code a bit and will work with distributed wells. Previously, we assumed that all non-shut perforations are stored locally. That does not hold any more.

Use WellInterface::perf_data_ to calculate PI.

---

opm/simulators/wells/WellInterface_impl.hpp

IMHO this might have happened if perf_data_ is empty or if the last connection is closed. (Discovered while working on distributed wells but might happen already before!)

[bugfix] Do not iterate pass end of perf_data_ in initCompletions

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

This PR adds a new helper function,
```
WellInterfacePtr createWellPointer(wellID, reportStep) const
```
which is responsible for creating appropriately typed derived well pointers depending on well types (multi-segment vs. standard). This, in turn, allows us to centralise this logic and use the same factory function both when creating the `well_container_` and when forming the well-test objects.
Finally, this helper will become useful for calculating PI/II values of shut/stopped wells in the context of WELPI.

Well Model: Add Helper for Well Pointer Creation

---

ebos/collecttoiorank.hh
ebos/ecloutputblackoilmodule.hh
ebos/eclwriter.hh
tests/test_ecl_output.cc

I have written some MPI stuff:
Thing goes as follows:
1. There is a family of summary keywords `WBP, WBP4, WBP5` and `WBP9`. These are different ways to calculate an average well pressure based on the completed cells and their neighbours. 
2. In opm-common there is a class [`PAvgCalculatorCollection`](https://github.com/OPM/opm-common/blob/master/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculatorCollection.hpp) which holds on to the wells which want to calculate the `WBPx` keywords. The most important method for the current PR is the `::index_list()` which returns all the global indices where we need the pressure.
3. This PR will distribute the `index_list` to all PE's and then assemble the requested pressures and update `PAvgCalculatorCollection` instance and pass it to the …

Wbp collect

---

opm/simulators/flow/MissingFeatures.cpp
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellProdIndexCalculator.cpp
opm/simulators/wells/WellProdIndexCalculator.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
tests/test_wellprodindexcalculator.cpp

This PR adds an initial implementation of the `WELPI` feature.  At this time there are still issues that need ironing out, especially for injection wells, but I believe we're ready for more widespread testing.
We rely on actual PI values being calculated at the well level at the end of each time step and use those values, in the event of a `WELPI` request, to calculate CTF scaling factors and apply those factors to all subsequent editions of the well provided the connection factors are eligible for `WELPI`-based rescaling.
If we trigger a rescaling event we also reset the `WellState`'s internal copies of the CTFs and reinitialize the Well PI calculators to ensure the rescaling takes effect immediately.  Since we rely on PI values being available at the end of each time step we must also …

Initial Implementation of WELPI Feature

---

tests/test_parallelwellinfo.cpp

BOOST_TEST is not available in older versions of boost.
in particular this broke building on rh6/7.

changed: use BOOST_CHECK instead of BOOST_TEST

---

opm/simulators/wells/ParallelWellInfo.cpp

The one previously used is unfortunately protected upstream (not noticed with gcc <=8).
Fixes fallout from #2947

Use a custom handle for copying doubles for above.

---

opm/simulators/flow/BlackoilModelEbos.hpp

Small drive-by change. May as well use constexpr here to get some code elimination.

Use constexpr members in BlackoilModelEbos to eliminate unnecessary code

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
tests/MpiFixture.hpp
tests/test_wellstatefullyimplicitblackoil.cpp

This is done by first examining the local perforations. For this this part is factored out into  a virtual method reportConnections, whose results are later gathered on the process that owns the well.
#2947 is included and needs to be merged first. This one is the next urgent ones to reduce the (already quite high) rebase efforts. There are several people working on the well code.

2nd part distributed stdwells: Write reports only for wells owned.

---

opm/simulators/flow/BlackoilModelParametersEbos.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

This should improve initialization in general, and is required to successfully run some cases depending on the network option.
We should verify it does not break things before merging though.

Make --alternative-well-rate-init=true the default.

---

opm/simulators/wells/WellGroupHelpers.cpp

as should be done in all cpp files.
Probably did not surface in master but it does in my branches.

[bugfix] Include config.h in WellGroupHelpers.cpp

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

This PR moves the operability checking to the wellInterface class to make it usable for both well models.
only
checkOperabilityUnderBHPLimitProducer 
checkOperabilityUnderTHPLimitProducer
updateIPR
are specialized. 
The two first are almost identical and could be moved to the wellInterface class with changes to some of the functions. But not in this PR since it will change unrelated code. 
The updateIPR needs to be specialized since the pressure gradient is calculated differently in the Standard well and the MSW well. 
The PR has been tested on some toy-cases and on a big model where this PR is sufficient and necessary for Flow to finish the simulation.

Check operability for MSW

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

In order to fully support #2936 we need to differentiate between `SHUT` wells and `STOP` wells - this is a step on the way. 
Mel: Long and winding road

Use enum Well::Status for well status in WellState

---

opm/simulators/flow/BlackoilModelEbos.hpp
opm/simulators/flow/NonlinearSolverEbos.hpp
opm/simulators/timestepping/SimulatorReport.cpp
opm/simulators/timestepping/SimulatorReport.hpp

For some MSW cases like MOD4_GRP 50% of the time is spend computing well potentials during pre/post processing. This just shows this to the user. With this the solver time almost equals the sum of its components. 
Dump from a MOD4_GRP run. Note that this is a local branch with several improvements, for master the pre/post step dominates even more.  
```
Number of MPI processes:         1
Threads per MPI process:         2
Total time (seconds):           23.14 
Solver time (seconds):          23.13 
Assembly time (seconds):        6.22 (Failed: 0.8; 13.0%)
Well assembly (seconds):      3.77 (Failed: 0.5; 14.2%)
Linear solve time (seconds):    4.00 (Failed: 0.6; 15.1%)
Linear setup (seconds):       0.88 (Failed: 0.1; 13.2%)
Update time (seconds):          1.65 (Failed: 0.2; 12.7%)
Pre/post …
```

Add report for pre/post time

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

If the well was shut in the previous report step we should not use the previous `WellState` to initialize it for this report step. In the case of wells which have been shut dynamically (due to well testing or ACTIONX) we previously nevertheless initialized the well (with more or less stale values). With this PR we skip the initialization in this case. This will lead to a data update because result will not be identical due to different initialisation. 
When this has been merged - with the necessary data updates, #2936 should be ready directly green in Jenkins :crossed_fingers:

Skip previously shut wells in WellState init

---

opm/simulators/linalg/setupPropertyTree_impl.hpp

I was getting warnings about redefined definitions (e.g. HAVE_PARMETIS).

Do not include config.h in header (not even in *_impl.hpp)

---

ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
ebos/eclpolyhedralgridvanguard.hh
ebos/eclproblem.hh
opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp
opm/simulators/aquifers/BlackoilAquiferModel.hpp
opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp

This PR modifies the aquifer model to use the dune interface. Similar to what is done for the initialization code in https://github.com/OPM/opm-simulators/pull/2941 
I have also removed the usage of the inputGrid since this will not be available in a partitioned grid.

Dunify aquifers

---

opm/simulators/flow/MissingFeatures.cpp

Seems we forgot to remove this when it got implemented.

Remove WSEGAICD from missing features

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

Initialize the well rates with well potentials when computing rates from bhp or bhp(thp)
The bhp was already initialized.
Scale the segment rates and pressure to adapt to changes in well rate and bhp
Improves convergence of the well potential calculations
Gives significant speed up on the NORNE_X_MSW cases in https://github.com/OPM/opm-tests/norne

Initial well rates with the well potentials and scale the segment rates

---

opm/simulators/wells/WellInterface_impl.hpp

We don't want to automatically shut wells stopped by the user. 
Wells stopped due to issues with operability should be triggered by isOperable() if I read the code correctly.

don't shut stopped wells

---

ebos/ecloutputblackoilmodule.hh

This works better in two-phase runs (G/O or O/W).

Extract SOIL Directly for 'BOSAT' Summary Vector

---

opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp

Basic serialization of `std::chrono::system_clock::time_point`- the current PR serializes through `std::time_t`, for general `std::chrono` time_points this will lead to a loss of precision. But since time is currently treated with `std::time_t` in opm this should be sufficient for now.
This PR is required to get https://github.com/OPM/opm-common/pull/2178 through.

Serialize std::chrono::system_clock::time_point through std::time_t

---

opm/core/props/satfunc/RelpermDiagnostics.cpp
opm/core/props/satfunc/RelpermDiagnostics_impl.hpp

The API for extracting unscaled (raw) saturation end-points has changed in opm-material.  Follow that change here.

Relperm Diagnostics: Chase EPS API Update

---

ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh

Gives the user a hint and a way to fix the empty partition issue by using a stricter imbalance tolerance. 
Depends on OPM/opm-grid#507

dynamically set zoltan imbalance tolerance

---

opm/simulators/wells/StandardWell_impl.hpp

We don't want to check the well operability in every inner iterations only in the outer iterations. This also makes the logic for the standard well code the same as the MSW code. Current default is to not use inner iterations for standard wells so it should not affect the simulations running with default options.

move well operability check for STW

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/ParallelWellInfo.cpp
opm/simulators/wells/ParallelWellInfo.hpp
opm/simulators/wells/StandardWell_impl.hpp
tests/test_parallelwellinfo.cpp

This is tested manually and finally produces the correct result. Currenty, it is still not possible to request that wells might be cut  by process boundaries. I will prepare some more PRs for that later.
Current functionaility should remain unchanged, but there is no an additional copy if we need to access values
from perforations above. If that turns out to slow things down, then we can remove that copy for sequential runs. That would be some work.

Final fixes to make distributed wells work for Norne.

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

This PR contains two fixes
1) make sure the correct well  indices are used for gasoil+energy
2) fix 2 phase for WELLPI by making sure the fluidstate is accessed by the canonical phase index and not the active phase position provided by the phaseUsage.

fix well model for gasoil thermal

---

opm/core/props/satfunc/RelpermDiagnostics.cpp

Following OPM/opm-material#438 we no longer need to pass the "family" as an argument.

Chase Unscaled Endpoint API Update

---

opm/simulators/wells/MultisegmentWell_impl.hpp

In the current code the well model is first copied in computeWellPotentials(...) and then in computeWellRatesWithBhp(...)
This should not alter any results.

dont copy the well model in computeWellPotentials

---

ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
opm/simulators/flow/BlackoilModelParametersEbos.hpp

We introduce a new parameter --enable-distributed-wells=<true|false> for this. During startup we check that the model either only has standard wells or that multisegement wells are actively interpreted as standard wells (by way of passing --enable-multisegment-wells=false as an option).
Note that the typetag property `UseMultisegmentWells` is now there twice once for `TypeTag` of `EclBaseVanguard` as template parameter and once for `TTag::FlowModelParameters` as template parameter. If there is a better way, please let me know. This drove me crazy and it seemed the only way to make all tests compile.
Needs OPM/opm-grid#511

Activate distributed wells in the simulator

---

CMakeLists.txt
compareECLFiles.cmake
ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
flow/flow_distribute_z.cpp
opm/simulators/flow/BlackoilModelParametersEbos.hpp

Additionally adds a flow executable that only distributes cells in z-direction. Executable is named flow_distribute_z and uses the external load balancing information. It can be used to test the distributed standard wells on SPE9 with 4 or more processes.
Automatic test of this is still missing as I need to find how to best do this. Suggestions welcome.
Based on #3029  and hence needs OPM/opm-grid#511

Support external loadbalancers in EclCpGridVanguard

---

ebos/ecloutputblackoilmodule.hh

In particular, treat `BSOIL`, `BSGAS`, `BSWAT`, and `BPRESSUR` as aliases for `BOSAT`, `BGSAT`, `BWSAT`, and `BPR` respectively.

Support Aliases for Block Level Quantities

---

opm/simulators/linalg/bda/openclSolverBackend.cpp

This is needed to use the CPU backend of PoCL http://portablecl.org/ which seems handy for debugging and probably other things.

Allow usage of non-gpu devices with OpenCL.

---

opm/simulators/aquifers/AquiferInterface.hpp

Since: https://github.com/OPM/opm-common/pull/2297 this multiplier has been fixed at 1.0

Remove multiplier in aquifer connected area

---

CMakeLists.txt
ebos/eclproblem.hh
ebos/ecltransmissibility.hh
flow/flow_bo_diffusion.cpp
flow/flow_co2_diffusion.cpp

This PR adds 
1) code to compute diffusivity in the eclTransmissibility class. Only called if diffusion is enabled. i.e. should not affect the standard Flow. 
2) Adds optional oil-gas-diffusion and bo-diffusion variants of Flow. 
Depends on OPM/opm-models#640

Add diffusion in Flow

---

ebos/eclproblem.hh

Reverts OPM/opm-simulators#3085
As [pointed out](https://github.com/OPM/opm-simulators/pull/3085#issuecomment-787941326) this introduces `fmtlib`usage in a header. Sorry. Reverting

Revert "Use fmt::format() for two messages"

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

No need to spam the log with multiple messages with the same content.

only log changes of group controls on rank 0

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

The first commit makes some throws in `getWellResiduals` thread safe. 
The second make sure that the group related quantities are communicated before the wellTest

Fix MPI issues in the well model

---

opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellInterface_impl.hpp

We have a model that has a tree of groups (three levels of groups below the topmost group F(topmost)->G1->G2->G3, wells only below G3). When we have a VREP constraint target on G1 and a group efficiency factor g1<1 results are wrong (We actually sometimes inject more than we should and there is a lot of switching in the group control modes). If on the other hand g1 is applied to G2 and G1 has group efficiency factor 1, the results are (nearly) correct.
~This is my rather naive attempt to always apply g1 to the topmost group G1. It does not really work and even worse injection drops to zero at some stage and has problems coming up again.~
~1ce5c598 is how I understood @atgeirr's private comment. (I also tested it standalone and it lead to injection dropping way below production and even …

Apply gefac also on topmost VREP controlled group

---

opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

This adds support for POTN (default is RATE) in WECON.

add support for POTN in WECON

---

ebos/ecloutputblackoilmodule.hh

When this is merged we can also remove a function from the `RestartConfig`class - simplifying that API will simplify the last pieces of the Schedule refactoring ....

Remove superfluos function call

---

opm/simulators/timestepping/SimulatorReport.cpp

fix ordering of first line in *INFOSTEP files, more specifically switches LSolve and LSetup mark

fix ordering of first line in *INFOSTEP files

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This change the logic of the well control copying between episodes
The new logic 
1) Always initialize with valid control from eclipeState
2) Copy control from the last time step for existing wells. 
Note that the new logic is consistent with the rest of the initialization of the well state.

make sure wells has valid controls

---

CMakeLists.txt

If fmtlib is present on the system we used that one in the normal mode (not header only). Otherwise we fallback to the embedded one header only. Searching for the library is done on opm-common.
Replacement of #3058. Needs OPM/opm-common#2348

Enable usage of fmtlib on the system.

---

ebos/eclmpiserializer.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/TargetCalculator.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

With this commit the guiderate logic used for the production groups is also used for injectors
This allows for setting guiderates explicit at different group levels
Only RATE, NETV and VOID guiderate type is supported.
Needs to be merged together with OPM/opm-common#2355

Add support for explicit guiderate for injection groups

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
tests/test_wellstatefullyimplicitblackoil.cpp

This PR sets the `data::Well::dynamicStatus` based on the dynamically updated 'Schedule' object (i.e., from ACTIONX and similar) and the results of well/operability testing (`WECON` and/or `WTEST`).  If a well is closed due to economic limits (`WECON`) we still provide summary-style data at the timestep that closed the well, but omit this data at later steps until the well reopens.
We add a new parameter to `WellState::report()` to distinguish these situations.
This is in preparation of making the `BlackoilWellModel` manage both open and shut wells alike

Record dynamic wellstatus

---

ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh

That way we don't get "unused variable" warnings when someone defines `NDEBUG`.  While here, also switch to using `Geometry` references where appropriate to avoid needlessly copying `Geometry` objects.

Push 'corners' Object into Assert

---

ebos/eclproblem.hh
ebos/ecltransmissibility.hh

This PR is for testing the performance impact of enabling diffusion by default. You still need to add DIFFUSE to your deck to actually model diffusion.

FOR TESTING. Enable Diffusion by default

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This is a rebased and trimmed-down version of the earlier PR #2936.  In particular, this PR prepares for the case of having the well state incorporate all wells on a process, not just the open/active ones.
This supersedes and closes #2936.

Don't Initialize Well State for Shut Wells

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

This will need some more testing before it can be considered for merging.

only compute guiderates at the beginning of a timestep

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

In eagerness to fix one issue I accidentally introduced another. Interesting that this did not surface during testing. Don't we have any test that start as history and move to prediction?

reset target from wconprod and wconinje

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

use the Bavg value stored in wellInterface class to avoid passing it round. 
This is a first step to align some of the interfaces to make it possible to use more of the same code for standard and multi-segmented wells.

only compute Bavg once pr timestep

---

ebos/eclproblem.hh
ebos/ecltransmissibility.hh

Depends on OPM/opm-models#645
Fix issue reported in #3132 
Change to compute the thermal conductivity the same way as for the permeability and diffusivity. It now used the cell center from eclipseState not the grid.

Fix thermal conductivity

---

ebos/eclpeacemanwell.hh
ebos/eclwellmanager.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

This is effectively no change - but for me it is easier to read; the motivation is https://github.com/OPM/opm-simulators/pull/3116 which needs an additional storing away of the previous well state. With this PR that can be implemented as:
```
well_model.commitWellState();
```
whereas the same functionality in current master must be implemented as:
```
well_model.prev_well_state_ = well_model.well_state_
```
That might be a bit into the future - but I would assume this was also a smell step in a direction to wrangle the mutable state object out of the model object.
Use of this PR is illustrated in the last commit of #3116

Access well state variables through accessor functions

---

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp

With the recent improvements in the convergence of the well model the simulator is able to keep alive wells that needs to die. Increasing this parameter will help them die a bit earlier. 
It goes without saying that this needs proper testing before it can be merged. I have tested it on the norne family where it shows good improvement on some of the cases.

change default MinTimeStepBeforeShuttingProblematicWellsInDays to 0.01

---

ebos/ecloutputblackoilmodule.hh

This commit adds support for calculating and reporting block-level values of the relative permeability of oil in the two-phase oil/gas and oil/water subsystems of a three-phase simulation run.  These are activated through summary keywords `BKROG` and `BKROW`, respectively.

Support Block-Level Two-Phase Subsystem Kro Summary Output

---

ebos/eclwellmanager.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

Update: after a review comment from @bska this code has been completely reworked.
If some connections have been closed there will be a difference between the number of connections in the well model and the number of connections loaded from the restart file. This should take that into account.

Well init restart bug

---

compareECLFiles.cmake

Verifies that norne can restart; the results are not checked in any way.
Will fail hard until: https://github.com/OPM/opm-simulators/pull/3156 is merged

Add test which loads a restart case for norne and runs one timestep

---

opm/simulators/linalg/bda/BdaBridge.cpp

also take chance to break an extremely long line

fixed: mark possibly unused variables as such to quell warnings

---

ebos/equil/initstateequil.hh

When reading the release 2020.10 announcement I came over issue #2889. 
This is a fix.

extrapolate saltvd table

---

opm/simulators/linalg/bda/BILU0.cpp
opm/simulators/linalg/bda/ChowPatelIlu.cpp

As CHOW_PATEL usage will be very rare, it's info is only printed when enabled.
Printing the number of colors found is printed more often, as that info is generally interesting.
`BILU0 reordering strategy: level_scheduling` is always printed, with the chosen reordering.

Always print CHOW_PATEL info if used

---

CMakeLists_files.cmake
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GroupState.cpp
opm/simulators/wells/GroupState.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
tests/test_GroupState.cpp
tests/test_wellstatefullyimplicitblackoil.cpp

I am working on restart. It is hard work. I think initializing the WellState correctly is an important part of this. The WellState class is large and a bit unwieldy - to get a better overview I have started to pull group related properties out of the wellstate and into a new `GroupState`. Posting this early to get comments right away if this is something the powers that be don't desire.; the second commit will be steadily expanded to include all the group related stuff from the existsing `WellState`
**Update**: This should be ready for review and merge now. This is not exactly pure gold, but at least pulling all group related stuff out from the `WellState` to the new `GroupState` class makes it slightly easier to have an overview. The `GroupState` implementation can certainly be improved. …

Wellstate split

---

opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

Switching between injection and production is a big event that need some special case. 
Depens on OPM/opm-common#2431

Use the event for swithing between producer and injector 

---

opm/simulators/wells/StandardWell_impl.hpp

This makes the code for update target for thp the same for standard wells (stw) producers as for stw injectors and msw injectors and producers. 
@atgeirr Do you remember (or know) why this is done differently for the stw producers.

get bhp from thp without solving

---

examples/printvfp.cpp
opm/simulators/utils/ParallelEclipseState.cpp
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp
opm/simulators/utils/readDeck.cpp
tests/test_stoppedwells.cpp
tests/test_vfpproperties.cpp
tests/test_wellstatefullyimplicitblackoil.cpp

fixed: include required headers where needed

---

opm/simulators/wells/GroupState.cpp
opm/simulators/wells/GroupState.hpp
tests/test_GroupState.cpp

Add functionality to create a json dump of the GroupState object. Initially created to debug: #3174, but code on My machine indicates that this will also be valuable when debugging the restart capabilities.

Add json dump to GroupState

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

These are used as part of calculating the BHP/THP when computing new potential rates in models that feature VFP tables and must therefore be properly initialised in the next report step's well state object.

Forward Potential Rates to Next Report Step

---

ebos/eclproblem.hh

The Actionx machinery records the simulation time when an action has evaluated to true. This PR fixes the recording time - which was locked to report_step time in master, instead of actual simulation time.

Record the correct simulation time in ActionState

---

CMakeLists_files.cmake
ebos/eclpeacemanwell.hh
ebos/eclproblem.hh
ebos/eclwellmanager.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GroupState.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/TargetCalculator.hpp
opm/simulators/wells/WGState.cpp
opm/simulators/wells/WGState.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This is a second attempt at #3171 and #3173 combined.
This PR will remove the `GroupState` member from the `WellStateFullyIMplicitBlackOil` and create a microscopic class `WGState`which handles the well state and group state together as a pair. I am not saying that this very good, or the final destination for this refactoring, but the current code is more explicit, and that is in my opinion a step in the right direction.
The commits Step 1, Step 2, ... is just the way I organized the work. Will squash everything before merge. 
This quite banal refactoring was really hard work; when such conceptually simple refactorings are so hard I think that is the code trying to tell you something.

Use groupstate2

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This commit includes the shut wells in `wells_ecl_` and expands the PI/II value calculation to apply to those shut wells too.  With this in place we are able to run cases that have a `WELPI` keyword before the well opens, even at the very first report step.

Compute Well-Level PI For Shut Wells 

---

CMakeLists_files.cmake
opm/core/props/phaseUsageFromDeck.cpp
opm/core/props/phaseUsageFromDeck.hpp
opm/simulators/flow/countGlobalCells.cpp
opm/simulators/flow/countGlobalCells.hpp
opm/simulators/utils/ParallelFileMerger.cpp
opm/simulators/utils/ParallelFileMerger.hpp
tests/test_wellstatefullyimplicitblackoil.cpp

Some small low-hanging fruits that can be moved to separate compilation units to avoid recompilation in each simulator object.

Move to separate compilation units

---

tests/test_wellmodel.cpp

The `WellInterface::initCompletions()` member function needs these.

Well Model Test: Supply Valid 'ecl_index' Values

---

CMakeLists.txt

mark the parallel test NO_COMPILE and specify the binary

fixed: do not build test_parallelwellinfo.cpp twice

---

ebos/equil/initstateequil.hh

Currently the simulator will return initial pressure 0 if item 9 is > 0 without any warning to the user other than non-physical result and convergence issues.

add throw for unsupported positive item 9 in EQUIL

---

opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp

use explicit template instantation. to avoid rebuilding
this code over and over (minor), and to avoid includes in headers.

WellGroupHelpers: make templates private

---

CMakeLists_files.cmake
opm/simulators/wells/TargetCalculator.cpp
opm/simulators/wells/TargetCalculator.hpp
opm/simulators/wells/WellGroupHelpers.cpp

use explicit instantation to avoid some templates being
instanced a lot of places in a lot of objects.

TargetCalculator: move to separate compile unit

---

opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp

The approach was suggested by @jalvestad 
And initial testing on norne and model2 is promising.

Initialize empty producers using mobility and transmissibility ratio 

---

CMakeLists_files.cmake
opm/simulators/wells/WellContainer.hpp
tests/test_wellstatefullyimplicitblackoil.cpp

A small container class to hold well (or group) objects of type `T`. The class is introduced in order to facilitate safe and partial refactoring of the WellState class - if the WellContainer turns out be useful it can live on - otherwise it should be removed/replaced as part of the refactoring.

Wellcontainer

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

add useInnerIteration method and move assembleWellEq to the well interface to avoid code duplication. 
These changes are cherry-picked from #3158 and should not change any results.

Avoid code duplication

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellContainer.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

Use `WellContainer<Events>` to manage per well events.
Upstream: https://github.com/OPM/opm-common/pull/2463

Distribute events

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellState.hpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

Make sure that all loops over the perforations of a well use an index spanning just over that wells perforations ... clear ehh?? Main point is to pull everything related to the offset of the per-well first perforation outside of the loops.
This is a preparation to be able to use a per-well vector for perforation rates.

Perforations well index

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

This was broken in commit b5580f39f (PR #3222) which removed the `start_perf_next_well` symbol but did not update every use location.

Restore Debug Builds

---

CMakeLists_files.cmake
ebos/eclcpgridvanguard.hh
ebos/eclgenericcpgridvanguard.cc
ebos/eclgenericcpgridvanguard.hh

Stick independent parts in a separate compile unit and use explicit template instantation.
This way, we compile this code only once instead of for every simulator object.
One could argue that more of the template parameters could be removed, but I did not want to remove possible flexibility from the typetag.
This sit on top of https://github.com/OPM/opm-simulators/pull/3218 which should be processed first.
Downstream of OPM/opm-models#655
Downstream of OPM/opm-grid#534

Separate eclcpgridvanguard.hh into typetag dependent/independent code

---

CMakeLists_files.cmake
ebos/eclcpgridvanguard.hh
ebos/eclpolyhedralgridvanguard.hh
ebos/eclproblem.hh
ebos/ecltransmissibility.cc
ebos/ecltransmissibility.hh
ebos/eclwriter.hh

This allows using explicit template instantation to only compile this code (a few times) per grid instead of in each simulator object.
This sits on top of https://github.com/OPM/opm-simulators/pull/3219 which must be processed first.

Separate eclctransmissibility.hh into typetag dependent/independent code

---

CMakeLists_files.cmake
ebos/eclgenericthresholdpressure.cc
ebos/eclgenericthresholdpressure.hh
ebos/eclthresholdpressure.hh

this allows using explicit template instantation to only
compile this code per grid, not per simulator object

eclthresholdpressure: split in typetag dependent/independent parts

---

opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

The only commit I'm unsure about is https://github.com/OPM/opm-simulators/commit/ab4772aba8c5f62810a7da060520e75e73dedf1b as I'm getting mixed messages whether the intention is to hardcode the well code to double precision or not. If that is the intention, we should use double instead of Scalar to avoid confusion.

Small cleanups in WellInterface

---

opm/simulators/flow/KeywordValidation.cpp
opm/simulators/flow/KeywordValidation.hpp
tests/test_keyword_validator.cpp

This pull request implements a very small improvement in the reporting of invalid item values. The current behavior is to always print the record number, even if there is only a single record. This changes the behavior to only include the record number if there is more than one record.

Simplify the error message on invalid item values for keywords with only a single record

---

opm/simulators/wells/WellStateFullyImplicitBlackoil.cpp
opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp

Veeery small trivial changes in MSW WellState code - just to start warming up there.

Reorder variables and remove .reserve() calls

---

opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp
opm/simulators/aquifers/AquiferNumerical.hpp
opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp

This PR switches to using `map<>::insert_or_assign()` as the primary interface for collecting dynamic aquifer data.  In turn, this activates move semantics for the substructures and reduces the number of times the data is copied.
Insert_or_assign requires the key, so provide this value&mdash;i.e., the aquifer ID&mdash;as part of the `AquiferInterface`.

Reduce Aquifer Data Copying

---

CMakeLists_files.cmake
ebos/eclgenerictracermodel.cc
ebos/eclgenerictracermodel.hh
ebos/ecltracermodel.hh

this allows using explicit template instantation to only
compile this code per grid, not per simulator object

ecltracermodel: split in typetag dependent and typetag-independent parts

---

ebos/eclbasevanguard.hh
opm/simulators/flow/BlackoilModelParametersEbos.hpp

it is used there. now eclbasevanguard.hh includes
BlackoilModelParametersEbos, instead of the other way around.

changed: move Deck parameter to BlackoilModelParametersEbos

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

The variable indices were incorrect for water/gas cases and single-phase cases. There is some choice for the water/gas case, we chose to keep the water fraction variable instead of the gas fraction variable in that case. See table summarizing indices in the new comment in the code.
Not tested with a gas/water case with MSW, as I do not have access to such a case (as far as I know).

Fix incorrect indices for 1 and 2-phase cases with MSW.

---

opm/simulators/wells/GasLiftStage2.hpp
opm/simulators/wells/GasLiftStage2_impl.hpp

When making gas lift parallel, see PR #3148, `redistributeALQ()` did not reserve space for the decremental and incremental gradients. Later in the execution thread when push_back() was called to add elements to the vectors, the capacity of the vector could get exceeded and hence the internal representation of the vector could be reallocated. This seems to have caused access to undefined memory errors since the iterators into the vectors were long longer valid.

Fixes a bug in GasLiftStage2_impl.hpp

---

CMakeLists_files.cmake
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterfaceGeneric.hpp
opm/simulators/wells/WellInterface_impl.hpp

This is a first step in reducing the amount of rebuilds due to changes in well code.
I realize there's a lot of things going on with wells, so I leave it to those doing "real" changes to time when to merge this. I'll handle any rebasing until then.

changed: split out non-typetag dependent code from WellInterface

---

ebos/eclcpgridvanguard.hh
ebos/eclpolyhedralgridvanguard.hh
ebos/eclproblem.hh
ebos/ecltransmissibility.cc
ebos/ecltransmissibility.hh

- the diffusion one is basically done on runtime anyways
- the energy one gives some small code elimination gains
however, it complicates the writing of downstream templates.

remove template parameters for enableEnergy/Diffusion in transmissibility

---

opm/simulators/wells/GasLiftSingleWellGeneric.hpp

Make constants used in subclasses protected.

---

opm/simulators/wells/WellState.hpp

Minor minor - just assemble all the `WellState`members which are not/will not become `WellContainer`members in one place

Assemble all non-wellcontainer WellState members

---

opm/simulators/wells/MultisegmentWell_impl.hpp

I *think* there is a bug in the handling of the pressure drop terms in the `WellState` object for MSW wells. Typical code looks like this:
```C++
for (int seg=0; seg < numSegments(); seg++) {
...
well_state.segPressDrop()[seg] = .....
}
```
the problem with this code is that the `seg` variable only runs over the number of segments for *this particular well*, whereas the `WellState::segment_pressure_drop_` vector expects an index in the range `[0, total_number_of_segments_in_reservoir>`. With this PR the segment index is offset by the index location of the top segment before the `WellState` array is accessed.
The code in question is only used for summary output, and should therefor not affect the calculations as such. I have stumbled upon this while working with #3296 - so it is not …

Bug in wellstate handling for pressure drop in MSW wells?

---

ebos/eclbaseaquifermodel.hh
ebos/eclgenericwriter.cc
ebos/eclgenericwriter.hh
ebos/eclproblem.hh
ebos/eclwriter.hh
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp
opm/simulators/aquifers/AquiferNumerical.hpp
opm/simulators/aquifers/BlackoilAquiferModel.hpp
opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp
tests/test_ParallelRestart.cpp

This PR adds logic to communicate more dynamic aquifer values between the simulation and I/O layers.  In particular, we ensure that we allocate the `aquFet` and `aquCT` substructures of the dynamic aquifer data as appropriate and that we collect this information on the I/O rank as part of the restart output process. We furthermore make the `ParallelRestart` facility aware of dynamic aquifer data in preparation of loading these values from the restart file.

Prepare to Save/Restore Richer Set of Aquifer Values

---

opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp

`<Disclaimer>`
I might have misunderstood the intended content of the `WellState::well_rates` member
`</Disclaimer>`
The `well_rates` member of the `WellState`object is a map over all wells, where a bool element indicates whether the well is owned by the current process. In current master this is only explicitly initialized for the local wells, and then the structure is subsequently updated (by accident ??) when the rate is assigned with `operator[]` - however the bool part of the `std::pair<bool, std::vector<double>>` is not explicitly assigned this way.
With this PR the `well_rates`member is explicitly assigned for *all* wells, and then the rate update is done with `at( wname )` instead of `operator[](wname)`

Make sure all wells are added to the well_rates map

---

opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp

The segment pressure drop is the sum of three terms - the pressure drop due to friction, acceleration and hydrostatic change. With this PR the segment pressure drop is implemented as a function instead of a seperate member.
This is an intermediate step on the way towards: #3297.

Remove segment pressure drop as separate variable

---

ebos/eclgenericwriter.cc
ebos/eclgenericwriter.hh
ebos/eclproblem.hh
ebos/eclwriter.hh
tests/test_ecl_output.cc

order of constructing and obtaining global transmissibilities
was off. replace constructor argument with a setter so it can be
set at the appropriate time.
closes #3328

eclwriter: fix regression in parallel

---

ebos/eclgenericoutputblackoilmodule.cc
ebos/eclgenericoutputblackoilmodule.hh
ebos/ecloutputblackoilmodule.hh
ebos/eclwriter.hh

EnableTemperature is true as default, i.e. the temperature is now passed to the restart machinery as default.
It will however be ignored and not written to the restart file if the user does not specify --enable-opm-restart-file=true

Pass the temperature to the restart machinary if enableTemperature is true

---

opm/simulators/wells/WellState.cpp

This is more of a question than an actual PR. In current master the well potentials can carry over to the next report step; the logic is quite complex with respect to previous step closed or not .... I have not gone through it in all detail.
Point is that with: #3336 the wellpotensials are explicitly cleared at the start of the report step (and then fetched from previous if there is a relevant previous!). If this PR is correct there will be a data update.

Explicitly zero well potentials at the start of report step

---

CMakeLists_files.cmake
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/SegmentState.cpp
opm/simulators/wells/SegmentState.hpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp
tests/test_wellstate.cpp

This is an alternative to #3297.
Implement a small class `SegmentState` to manage the MSW properties of the WellState object.
This PR is complete; but there are also two partial PRs which can be reviewed & merged separately. 
Part1: #3324 
Part2: #3329

Segment state2

---

ebos/ebos_plain.cc
ebos/eclproblem.hh
opm/simulators/wells/WellInterface_impl.hpp
tests/test_ecl_output.cc
tests/test_equil.cc

rather, only set it where we want to use it. this avoids including
eclwellmanager.hh and eclpeacemanwell.hh unnecessarily in
simulator objects (where BlackoilWellModel is used).

changed: do not set the ebos well model as default type

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

Unused which is a good thing since it does not compile if you instance it. No such member in segmentSet()

MSW: drop unused method

---

opm/simulators/wells/WellState.cpp

Commit 6a21371b5 (PR #3344) removed `num_perf_this_well` but did not make all requisite changes.  Fix an accompanying `assert` to restore builds that do not define `NDEBUG`.
Supersedes and closes #3356.

Restore Debug Build

---

CMakeLists_files.cmake
opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.cpp
opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
opm/simulators/flow/countGlobalCells.hpp
opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp
opm/simulators/timestepping/AdaptiveSimulatorTimer.hpp
opm/simulators/timestepping/AdaptiveTimeSteppingEbos.cpp
opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
opm/simulators/timestepping/SimulatorTimer.cpp
opm/simulators/timestepping/SimulatorTimer.hpp
opm/simulators/timestepping/SimulatorTimerInterface.cpp
opm/simulators/timestepping/SimulatorTimerInterface.hpp
opm/simulators/timestepping/TimeStepControl.cpp
opm/simulators/timestepping/TimeStepControl.hpp

This removes the need to parse boost/date_time headers in all simulator objects.

Avoid boost/date_time in simulator objects

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterfaceFluidSystem.cpp
opm/simulators/wells/WellInterfaceFluidSystem.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterfaceGeneric.hpp
opm/simulators/wells/WellInterfaceIndices.cpp
opm/simulators/wells/WellInterfaceIndices.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp
tests/test_wellmodel.cpp

The new perforation datastructeres in WellState do not need this any longer.

Remove first perf member from Well classes

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/RateConverter.hpp
opm/simulators/wells/WellInterfaceEval.cpp
opm/simulators/wells/WellInterfaceFluidSystem.cpp

The standard RESV coefficients use the average RS and RV values from the reservoir. For injection we assume no dissolved gas or vaporized oil. This is supposed to fix the issue reported by @bska in #3349

removed dissolved gas and vapporized oil from RESV injection rates

---

opm/simulators/wells/WellState.cpp

The `Schedule::Well` objects will always have all connections on all processors - i.e. the `global_num_perf_this_well` can be initialized from here, without performing a collective sum. 
An important part of the motivation for the change is to check my own understanding?

Use ecl well for total number of connections

---

opm/simulators/wells/WellState.cpp

I might very well have misunderstood something here, but my understanding goes as follows:
1. We copy the state of the perforation rates from the previous step - this is good for convergence, but not essential for correctness.
2. If the number of the perforations have changed - either because new perforations have been specified in the input, or alternatively due to loadbalancing - we do not copy the previous perforation rates but rather initialize with an average rate.
In current master the check for change in perforation numbers is global - taking all processers into account, whereas I with this PR suggest checking just the local process for changes in number of perforations. I realize that this *can* optionally lead to a situation where perforations on process 1 get initialized by …

Suggestion: Simplify check for number of perforations

---

opm/simulators/flow/BlackoilModelParametersEbos.hpp

An embarrassing bug in #3355. The testing was done on #3331, where the limit was hard-coded to 3.

change get param from bool to int

---

opm/simulators/flow/KeywordValidation.cpp
opm/simulators/flow/KeywordValidation.hpp
opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
opm/simulators/utils/PartiallySupportedFlowKeywords.hpp
opm/simulators/utils/readDeck.cpp
tests/test_keyword_validator.cpp

The recently added keyword validation code could only check values of items against a list of options. This pull request adds the option to call a predicate function to test the value of an item. This allows for a broad range of tests, such as checking the sign of a value, or for  a range of values. The cost in complications of the specification of the validations is minor: one field is added to the struct used to define a check.
A test has been added that demonstrates this approach using a lambda function as a predicate.
In addition to this improvement, checking of items with double value types has been added.
**EDIT:** Decided to go for the simpler solution. Everything is done via a validator function, and a small helper class was added to be able to easily define lists of permitted …

 Add keyword validation using a predicate function

---

CMakeLists_files.cmake
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp
opm/simulators/wells/GasLiftSingleWell.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp
opm/simulators/wells/GasLiftSingleWell_impl.hpp
opm/simulators/wells/GasLiftStage2.cpp
opm/simulators/wells/GasLiftStage2.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp
tests/test_glift1.cpp

Check group limits in gas lift stage 1 to avoid adding too much ALQ which must anyway later be removed in stage 2. This should make the optimization more efficient for small ALQ increment values. Also adds MPI support.

Check group limits in gas lift stage 1

---

CMakeLists_files.cmake
opm/simulators/linalg/bda/BdaBridge.cpp
tests/test_cusparseSolver.cpp
tests/test_openclSolver.cpp

Copied `test_preconditionerfactory.cpp` and replaced Dune with cusparseSolver and openclSolver.
It needs `getSparsityPattern()` like in the `BdaBridge`, but that is not a public method.
It also creates an empty `WellContributions`.
The values in the `expected` vector are different, but both cusparseSolver and openclSolver converge for NORNE.

Added tests for cusparseSolver and openclSolver

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp

This PR does two things
1) It scales the well rates for wells under group control when its groups control changes
2) It adds an epsilon to avoid inf scales for wells with current rate zero. 
It still under testing. But I will make a draft PR to utilize our testing framework.

Scale well rates after group switching

---

ebos/eclfluxmodule.hh
opm/simulators/utils/DeferredLogger.cpp
opm/simulators/utils/DeferredLogger.hpp

It makes gcc10 emit a warning. Also a minor header cleanup.

fixed: do not assert conditions guaranteed by unsigned

---

compareECLFiles.cmake

This PR adds support for setting a non-default case directory in the
```cmake
add_test_compare_restarted_simulation
add_test_compare_parallel_restarted_simulation
```
wrapper functions.  This, in turn, is helpful when creating restarted cases for the aquifer models.

Add Support for 'DIR' Parameter in Restart Test Macro

---

ebos/collecttoiorank.cc
ebos/eclgenericoutputblackoilmodule.hh

Debian 11 is near, and then ci will move to 2.7. Let us be ready.

quell dune2.7+ warning

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp
tests/test_glift1.cpp

`GasLiftGroupInfo.cpp` did not include `config.h` which caused the macro `HAVE_MPI` to be undefined which again caused the file to be compiled with `Dune::Communication<No_Comm>` instead of with `Dune::Communication<MPI_Comm>`. This later caused linking problems with files that used MPI.

Add missing header file to GasLiftGroupInfo.cpp

---

ebos/eclgenericoutputblackoilmodule.cc
ebos/eclgenericoutputblackoilmodule.hh
ebos/ecloutputblackoilmodule.hh
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/WellState.cpp

This PR distinguishes the reference condition pore volume from the dynamic, pressure (and/or temperature) dependent pore volume value.  Previously we would report the latter as the `PORV` value in the "Field Totals" and "FIPNUM region" reports, but this commit switches to reporting the former instead&mdash;mostly for compatibility. We still report the dynamic pore volume value, but now we report this on a line of its own, before the table, using one of the forms
```
Field total pressure dependent pore volume = 12345 RM3
FIPNUM report region 1 pressure dependent pore volume = 123 RM3
```

Report Pressure Dependent Pore Volume in PRT File

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

This PR protects against `Opm::Well` instances for which the sets of connections are empty.  In those cases, do not put entries in the well container as there is no influence on the systems of non-linear equations.

Don't Create Well Instance for Wells With No Connections

---

opm/simulators/wells/WellGroupHelpers.cpp

When combining guiderates form potentials, WGRUPCON and GCONINJE/GCONPROD the guiderates comes with different units. 
Testing indicates that using SI units may not be the preferred option. I mark it draft since more testing is needed. @GitPaean Does this effect your test case?

scale guiderates from si

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterfaceFluidSystem.cpp
opm/simulators/wells/WellInterfaceFluidSystem.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterfaceGeneric.hpp
opm/simulators/wells/WellInterface_impl.hpp

This seems to help significantly for some key models. 
The code for getting the well part of the group target is at least at a first glance ripe for refactoring. The similar logic is used 4 places. But since this fix is urgent, and the refactoring nontrivial, I suggest that happens another day. 
I have tested this on the norne family and on a proprietary model.

handle GRUP in wellState from target

---

ebos/collecttoiorank.cc
opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferNumerical.hpp
opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp
tests/test_ParallelRestart.cpp

This PR switches to using the new `typeData` interface for representing type-specific aquifer data items introduced in OPM/opm-common#2496.  In particular we use the new `typeData.is<>()` and `typeData.get<>()` member functions to query and access the data that is specific to each aquifer type (e.g., Carter-Tracy or numerical).
While here, also expand the reported data items for numerical aquifers to one initial pressure value for each aquifer cell.  This is needed for restart purposes.

Chase Type Specific Aquifer Data API Change 

---

opm/simulators/utils/UnsupportedFlowKeywords.cpp

Add GRAVITY keyword to UnsupportedFlowKeywords with message to use DENSITY instead.

Add GRAVITY keyword to UnsupportedFlowKeywords

---

opm/simulators/wells/GasLiftGroupInfo.cpp

Fixes two-phase Oil/Water runs.  Probably needs more refinement later.

Don't Access Phase Rates Unless Active

---

opm/simulators/linalg/FlexibleSolver.hpp
opm/simulators/linalg/FlexibleSolver_impl.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
opm/simulators/linalg/OwningTwoLevelPreconditioner.hpp
opm/simulators/linalg/PreconditionerFactory.hpp
opm/simulators/linalg/PressureSolverPolicy.hpp
opm/simulators/linalg/PressureTransferPolicy.hpp
opm/simulators/linalg/setupPropertyTree.cpp
tests/options_flexiblesolver.json
tests/test_flexiblesolver.cpp
tests/test_preconditionerfactory.cpp

Previously, the user had to specify it in the json file read from the FlexibleSolver or 1 was used. Unfortunately, the index depends on the model used and it seem rather opaque to a user what that index is.
With this commit we determine the pressure index from the model.

Determine index of pressure from model used to increase usability

---

compareECLFiles.cmake
tests/run-summary-restart-regressionTest.sh

Add a test driver to run a restart test where only the summary results are compared. Suggested "improvement" for situations where it is not (yet) possible to achieve full restart capability.

Restart summary only

---

ebos/eclgenericvanguard.cc
ebos/eclgenericvanguard.hh
opm/simulators/flow/Main.hpp
opm/simulators/utils/readDeck.cpp
opm/simulators/utils/readDeck.hpp

With this PR the `UDQState` can be initialized external to the vanguard. This is necessary to enable restart from models with UDQ.
I will disavow the current code any day including Sundays, but I have tried to follow the existing pattern as close as possible - for all that is worth.

Assemble UDQState external to the vanguard

---

ebos/eclproblem.hh
opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
opm/simulators/utils/UnsupportedFlowKeywords.cpp

Default tracer switch set to `true`. Also, `TRACERS` and `TRACER` have now status as "partly supported".

Default activation of tracer model.

---

ebos/eclgenericoutputblackoilmodule.cc

The function does not use that argument.

Don't Pass 'log' Argument to 'Schedule::rst_file'

---

opm/simulators/linalg/bda/Reorder.cpp
tests/test_flexiblesolver.cpp
tests/test_preconditionerfactory.cpp

In particular, don't print uninitialized memory (`Reorder.cpp:left`) and don't capture objects (`prm`) that aren't actually used.  While
here, refactor the initialization of the MT19937 random number generator.  Constructing this object is too expensive to do for each try, especially when we can just run the generator in place.

Address Static Code Analysis Warnings

---

opm/simulators/wells/WellInterfaceFluidSystem.cpp

Discovered while working on: #3451 
To me it looks like a bug in current master - where only a local variable is updated, instead of updating the shared `WellState`object.
This is also fixed in #3451 - but there in different implementation.

BUG? Make sure WellState injection control is updated

---

opm/simulators/wells/WellInterfaceFluidSystem.cpp
opm/simulators/wells/WellInterfaceFluidSystem.hpp

This is a first step towards being able to check constraints with a `const WellState` argument. Lost steam halfways.
As part of the work a bug (I think) was discovered - that will be highlighted in a separate PR against master (#3452)
.

Check production and injection constraints separately

---

tests/test_glift1.cpp

I think this is the correct fix. It certainly fixes the assertion (ref https://github.com/OPM/opm-common/pull/2594)

fixed: add missing initialization call

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell_impl.hpp

1) potentials are computed before the WECON test are done. Relevant if potentials are used in WECON
2) re-compute potentials for pressure controlled wells if the rates are trivial.

Make sure potentials are computed in some corner cases

---

CMakeLists_files.cmake
opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GlobalWellInfo.cpp
opm/simulators/wells/GlobalWellInfo.hpp
opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWellGeneric.cpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/SingleWellState.cpp
opm/simulators/wells/SingleWellState.hpp
opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/StandardWellGeneric.cpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellContainer.hpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellInterfaceEval.cpp
opm/simulators/wells/WellInterfaceFluidSystem.cpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp
tests/test_wellstate.cpp

Some time ago there was a significant refactoring of the WellState class in order to support/facilitate restart. 
With this PR that refactoring is taken a step further - a new class/struct `SingleWellState`is created and (nearly) all state information is assembled there. The current PR is nearly a pure reorganisation - in a subsequent PR we can reap simplification benefits many places.

Add SingleWellState 

---

CMakeLists.txt

In #3468  forgot to test the build without the variants and/or poly grid simulators enabled. Remedy this. Closes #3469

fix build without variants and/or poly grid

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp

The output layer expects its input values to be strictly SI, but we know that the `GuideRate` container's values are in output units.
This PR uses an API that was introduced in OPM/opm-common#2605.

Report Guiderate Values in Strict SI Units

---

compareECLFiles.cmake
tests/update_reference_data.sh

this allows updating opm-tests reference data repository
with the current results.
this is useful for devs as some of the tests only pass on the
CI system due to slight differences. you can now run this
before applying changes, and thus only reveal real regressions
introduced by your changes.
Downstream of https://github.com/OPM/opm-common/pull/2613
@joakim-hove took a while but here you go. please test.

added: 'update_data' custom target

---

opm/simulators/wells/RateConverter.hpp

an attempt to fix the failure https://ci.opm-project.org/job/opm-simulators-PR-builder/2766/testReport/junit/(root)/mpi/compareParallelSim_flow_onephase_energy_SPE1CASE2_THERMAL_ONEPHASE/ from https://github.com/OPM/opm-simulators/pull/3418#issuecomment-892716714
It is a bug introduced in https://github.com/OPM/opm-simulators/pull/3445 , not sure how it was missed from the jenkins test. 
And also, the current version is a quick attempt. I do not have the full knowledge about how the gas-water system is developed, the current version might introduce some inconsistency. 
Anyway, it is an attempt.

consindering the situation of single water phase for RateConverter

---

opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellInterfaceEval.cpp
opm/simulators/wells/WellInterfaceFluidSystem.cpp

This basically reverts changes applied in PR #3095.
With this gefac is only applied while accumulating rates from the level below.

Fixes related to GEFAC

---

ebos/eclproblem.hh
opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp
opm/simulators/aquifers/AquiferNumerical.hpp
opm/simulators/utils/readDeck.cpp

This PR activates restart support for analytical aquifers. Analytic aquifer keywords do not exist in the input file for restarted runs since the 'SOLUTION' section is empty apart from from the `RESTART` specification.
We use the `RestartIO::Aquifer` (OPM/opm-common#2526) class to load the information from the restart file and then assign this information to the `AquiferConfig` object hosted by the `EclipseState`.  Loading `Schedule` information from the restart file is still contingent on the `--sched-restart=false` command line setting.  We support all aquifer types currently supported by the simulator, namely
* Carter&ndash;Tracy
* Fetkovich
* Numerical
Numerical aquifer restart support is limited to restoring the cumulative water production and initial aquifer cell pressures from the …

Load Analytic Aquifers From Restart File

---

compareECLFiles.cmake

We add one sequential and one parallel restart test for each aquifer test model currently in the repository.

Activate Sequential and Parallel Restart Tests With Aquifers

---

opm/simulators/flow/BlackoilModelParametersEbos.hpp

More testing indicates that 3 is too small. In particular for challenging cases. It will slightly increase the simulation time for one of the model we test in benchmark, but for many other it will give both better performance and also sometimes more accurate results since premature shutting of wells are avoided. 8 seems to be a good compromise. Always applying inner iterations sometimes gives unwanted oscillation and non-converged solutions.

Change default MaxNewtonIterationsWithInnerWellIterations to 8

---

opm/simulators/utils/readDeck.cpp

Defition of the communicator was moved inside a `#if HAVE_MPI` there. This commit queries the communicator again below to fix this.

[bugfix] Fix sequential run after #979

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
tests/test_wellmodel.cpp

using Indices directly more clearly shows where the data comes
from without having to hop through hoops to do so.
This is a style thing more than anything else so personal preferences play a big role. Feel free to reject.

drop aliases for Indices entries

---

opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp

Again this is mostly a style choice. Having huge lists of using statements is visual noise and such lists tend to be 'add only', meaning the lists keep growing over time and are seldom kept clean. Instead we qualify members using 'this' at call sites.

Drop using statements

---

opm/simulators/wells/RegionAverageCalculator.hpp

This should fix model 2 regression. 
A more elegant solution would be to make the RegionMapping.hpp parallel aware. But that is a task for another time and person. @bska or @blattms Cool if one of you could take a look at this some time.

Handle empty region in average calculator

---

ebos/eclgenericcpgridvanguard.cc
ebos/eclgenericoutputblackoilmodule.cc
ebos/eclgenericthresholdpressure.cc
ebos/eclgenerictracermodel.cc
ebos/eclgenericwriter.cc
ebos/eclmpiserializer.hh
ebos/ecltransmissibility.cc
opm/simulators/linalg/FlexibleSolver_impl.hpp
opm/simulators/linalg/ParallelOverlappingILU0.hpp
tests/test_milu.cpp

Fixes:
- The layout parameter of MultipleCodimMultipleGeomTypeMapper was deprecated for a long time and removed in DUNE 2.8
- bilu_backsolve is deprecated and one should use Dune::ILU::blockILU0Decomposition.
- Compilation was broken due to inclusion order problems with our firstmatrixelement method (that is now CamelCase).
needs OPM/opm-models#668

Fixes and removes deprecation warnings for Dune 2.8

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp

Note 1. For stw this is just a rename to make the naming consistent with MSW.
Gives significant speed up, especially in parallel where the well potential calculations  for MSW used to take up most of the simulation time. 
Moreover the change avoids too early closing of wells due to issues with the operability check.

Do not iterate inside computeBhpFromThp in MSW

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/WellGroupHelpers.cpp
opm/simulators/wells/WellGroupHelpers.hpp

This PR also removes the passing of the non-constant wellState to the groupState update code since groupState is separated from the wellState now.

pass updated well rates totarget reduction not the nupcol ones 

---

opm/simulators/utils/DeferredLogger.hpp
opm/simulators/utils/DeferredLoggingErrorHelpers.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

Previously, exceptions happening at this stage have deadlocked flow. E.g.  `UniformTabulated2DFunction` in opm-material throws a `NumericalIssue` if the values passed are outside the tabulated reason. This function is e.g. called in 2-phase CO2-storage cases during `BlackoilModel::initializeWellState`.
BTW: This is only the first step as it is not very user friendly that a simulation aborts at this stage.

bugfix: Detect exception during beginReportStep in parallel & abort

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/SingleWellState.cpp
opm/simulators/wells/SingleWellState.hpp
opm/simulators/wells/WellInterface_impl.hpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp

without this PR the well will open and be included in the well container, but the output will be trivial since the status is still SHUT.

update status after WTEST

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WGState.cpp
opm/simulators/wells/WGState.hpp

If the simulator fails after a well opens due to well testing we want to also revert the wellTestState. Adding the wellTestState to the WGState class automatically includes it in the resetWGState and commitWGState logic.

add well_test_state to WGState

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellInterface_impl.hpp

If a well/group control change all wells belonging to the same group are potentially affected. Calling updateWellStateFromTarget between every update makes the rates more consistent and thus avoids oscillations.

Update well rates from target during well/group control update

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterfaceFluidSystem.cpp
opm/simulators/wells/WellInterfaceFluidSystem.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterfaceGeneric.hpp
opm/simulators/wells/WellInterface_impl.hpp

Use class `SingleWellState` instead of full `WellState` container in some locations. More to come.

Use single well state

---

opm/simulators/utils/readDeck.cpp

Modulo bugs - and come on - how likely is that? This PR should complete the restart support for models with ACTIONX (in serial)

Load Action state from restart file

---

ebos/eclbasevanguard.hh
ebos/ecltransmissibility.cc
ebos/ecltransmissibility.hh

For 10 Million cell problems my compute server (128 RAM) starts to swap, when I use debugging tools in parallel runs. I assume that this might get an issue for others, too.
Now we consistently use unordered_map for the mapping.
Not in it's final state, yet. There already are mappings in the vanguard that we might be able to reuse.

Save space for cartesianToCompressed mapping.

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/StandardWellGeneric.cpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp

The `WellState` class had a `bool` switch whether to perform gas lift optimization - it was always on. Just removed with this PR in the long time quest of simplifying the `WellState` class. If runtime switching of the GLO should be brought back in, I don't think the `WellState`is the correct home for such a future variable?

Remove unused query/switch code for GLO - it is always on

---

opm/simulators/utils/ParallelSerialization.cpp
opm/simulators/utils/ParallelSerialization.hpp
opm/simulators/utils/readDeck.cpp

To ensure that the UDQState and ActionState are broadcasted for a restart run

Broadcast UDQState and Action state after restart loading

---

opm/simulators/flow/FlowMainEbos.hpp

In current master it is difficult to use exceptions in the simulator code, because when only when process throws an exception the other processes will quite quickly deadlock in a subsequent collective communication.
With this PR `MPI_Abort(MPI_COMM_WORLD)`will be called in the catch all clause of flow execution and we can safely use arbitrary `std::exceptions` in the simulator. (The simulator will come tumbling down in flames - but I consider that far superior to a deadlock).
Exactly how this should be done is maybe outside my MPI competence - but I *really* hope something like this can be merged.

Call MPI_Abort() in main catch all clause

---

opm/simulators/flow/BlackoilModelParametersEbos.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterfaceGeneric.hpp
opm/simulators/wells/WellInterface_impl.hpp

shutting inoperable wells during iterations seems to create more problems than it solves. There may be cases where this is a feature, so I suggest that we keep it as an option.

stop updating operability during iterations

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp

Avoid deadlock in parallel when wells are shut.

communicate before usage not after

---

opm/simulators/utils/PartiallySupportedFlowKeywords.cpp

Keyword Validation Fixes: GCONINJE, WTEST and AQUCT. Just minor edsits

Keyword Validation Fixes: GCONINJE, WTEST and AQUCT

---

opm/simulators/flow/BlackoilModelParametersEbos.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

This can potentially stabilize the convergence in some special cases.

restrict maximum number of times a well can switch to the same control

---

compareECLFiles.cmake
tests/run-init-regressionTest.sh
tests/run-porv-acceptanceTest.sh
tests/run-regressionTest.sh
tests/update_reference_data.sh

This restarts the simulation at a specified step. It then compares the results from this run to a separate,
existing regression data set.
By request from @alfbr 
It includes a rebased version of https://github.com/OPM/opm-simulators/pull/3072 as I rely on this functionality.
Still somewhat drafty, I need to test it on the CI system..

Add support for regression restart tests

---

ebos/eclalugridvanguard.hh
ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
ebos/eclgenericcpgridvanguard.cc
ebos/eclpolyhedralgridvanguard.hh
ebos/ecltransmissibility.cc
ebos/ecltransmissibility.hh

In addition to transmissibilities We will need this for the tracers,
too, and should prevent code duplication.

[refactor] Move cell centroid lookup magic to vanguard for reuse.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp

Small refactoring for WTEST restart

Use plain WellTestState::hasWellClosed() without reason

---

opm/simulators/utils/readDeck.cpp
opm/simulators/utils/readDeck.hpp

Mostly to reduce the number of nested conditionals and long lines.

Extract Helper Functions From readDeck

---

ebos/eclgenericcpgridvanguard.cc

This method avoids resorting to const_cast tricks.

Reset ACTNUM at EclipseState Level

---

opm/simulators/flow/BlackoilModelEbos.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface_impl.hpp

Remove assert for infinite primary variables update and handle exceptions that might be thrown in the linearize method of the well model correctly.
Superseeds #3574 and combines it with totto82/opm-simulators#11. Rebased on current master-

remove assert for isfinite and correctly handle exceptions

---

opm/simulators/utils/readDeck.cpp

The communicator is only needed in parallel builds.

Mark 'comm' As Potentially Unused

---

compareECLFiles.cmake
tests/run-init-regressionTest.sh
tests/run-porv-acceptanceTest.sh
tests/run-regressionTest.sh

Add test flag `RESTART_SCHED`when registering a restart test. The purpose of this switch is to be able to pass `--sched-restart=true` or `--sched-restart=false` to the restarted run. If the `RESTART_SCHED`argument is not supplied flow will restart with whatever is default behavior.

Restart sched flag

---

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp

Sometimes you just want you're simulation to run through. 
Note 1. It is false pr default. 
Note 2. It is set to true if TUNING is enabled

Option for continue on solver convergence failure

---

CMakeLists.txt
opm/simulators/linalg/bda/BILU0.cpp
opm/simulators/linalg/bda/BILU0.hpp
opm/simulators/linalg/bda/ChowPatelIlu.cpp
opm/simulators/linalg/bda/ChowPatelIlu.hpp
opm/simulators/linalg/bda/opencl.hpp
opm/simulators/linalg/bda/openclKernels.hpp
opm/simulators/linalg/bda/openclSolverBackend.cpp
opm/simulators/linalg/bda/openclSolverBackend.hpp

On new Debian versions (probably others) there is no cl.hpp file anymore. Except for NVIDIA (that still ships opencl headers from the stone age while at the same time claiming that they support shiny OpenCL 3.0), other vendors seem to at least ship cl2.hpp file. NVIDIA users should install the package opencl-headers (with the headers provided by Khronos).
This PR resorts to using cl2.hpp instead of cl.hpp.
Note that for the newest header package there will be a deprecation warning that one should use opencl.hpp instead.
Hopefully closes #3643

[enhancement][opencl} Use cl2.hpp instead of cl.hpp (missing on bullseye)

---

ebos/collecttoiorank.cc
ebos/eclgenericcpgridvanguard.cc
ebos/eclgenericproblem.cc
ebos/eclgenericthresholdpressure.cc
ebos/eclgenerictracermodel.cc
ebos/eclgenericwriter.cc
ebos/ecltransmissibility.cc
opm/simulators/linalg/ISTLSolverEbosFlexible.hpp

by adding the missing needed explicit template instantiation and fixing how element mapper is instantiated.
@atgeirr Please backport to release.
Closes #3626

Fixes compilation with dune-fem 2.8

---

CMakeLists.txt

Ebos is removed from the upstream shortly after the release.

Disable installing ebos, just for release 2021.10.

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp

This PR introduces a new helper class `GroupTreeWalker`, currently private to the `BlackWellModelGeneric.cpp` implementation file, that is based on the code in #3613 for accumulating group-level injection and production guide rate values.  The user can add visitor operations for wells and groups, typically with side effects, and then choose whether to run a preorder walk (visit groups before their children) or a post-order walk (visit children&mdash;especially wells&mdash;before their parents).
We use this helper class to ensure that we always extract and report pertinent injection guide rates at the well level (i.e., `WxIGR`) if at least one of the groups in the well's upline to the FIELD group has an entry for the corresponding phase in `GCONINJE`.  This is for increased compatibility …

Report Well Level Injection Guide Rates if Group Controlled

---

flow/flow_ebos_blackoil.cpp
flow/flow_ebos_brine.cpp
flow/flow_ebos_energy.cpp
flow/flow_ebos_extbo.cpp
flow/flow_ebos_foam.cpp
flow/flow_ebos_gasoil.cpp
flow/flow_ebos_gaswater.cpp
flow/flow_ebos_micp.cpp
flow/flow_ebos_oilwater.cpp
flow/flow_ebos_oilwater_brine.cpp
flow/flow_ebos_oilwater_polymer.cpp
flow/flow_ebos_oilwater_polymer_injectivity.cpp
flow/flow_ebos_polymer.cpp
flow/flow_ebos_solvent.cpp

Initialization is now done in the Main::initMPI() method. For configurations with dune-fem, this also caused crashes
with dune-fem versions prior to 2.8.

Remove extra MPI initialization.

---

ebos/equil/equilibrationhelpers.hh

Change `assert( numeric_test )` to `throw` and `std::isfinite()` 
See also: https://github.com/OPM/opm-material/pull/481

Replace numerical assert check with std::isfinite() and throw

---

opm/simulators/linalg/bda/amgclSolverBackend.cpp

Removed message in amgclbackend was:
```
warning: catching polymorphic type ‘class boost::property_tree::json_parser::json_parser_error’ by value
[-Wcatch-value=]
```

Fixes warning about catching polymorphic type by value.

---

opm/simulators/wells/VFPHelpers.cpp
opm/simulators/wells/VFPHelpers.hpp

We don't need to copy those mapping tables on each call.

Switch to Passing VFP Wrapper Tables as References

---

ebos/eclproblem.hh
opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/SingleWellState.cpp
opm/simulators/wells/SingleWellState.hpp

In the case an ACTIONX block has keywords affecting wellrates - e.g. `WCONPROD` we need to force an update of the wellrates used in the simulator. This PR is mainly a refactoring to extract the functionality to update rates out from the `WellState::init()` - so that it can be called halways through a report step. The actual change is in the last commit. Must be combined with: https://github.com/OPM/opm-common/pull/2801 to produce correct results.
The essence of the refactoring is:
1. Functionality is moved from `WellState` to `SingleWellState`
2. Code is split in an injector function and a producer function.
3. The pressure in the first connection which can be used as BHP limit is assigned to the `PerfData` structure at construction time.
The refactoring in the first N -1 commits can very …

Update rates after actionx

---

CMakeLists_files.cmake
opm/core/props/BlackoilPhases.cpp
opm/core/props/BlackoilPhases.hpp
tests/test_wellstate.cpp

Add a constructor to enable creating `PhaseUsage` objects without a Deck. Good for testing at least.

Create PhaseUsage constructor

---

opm/simulators/utils/UnsupportedFlowKeywords.cpp

The input layer now converts this input to DENSITY data.

Mark GRAVITY Keyword as Supported in the Simulator

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp

Testing on modified versions of tests from model5. We are currently working on adding more tests for gasslift that should also cover LRAT and WRAT controlled groups. 
Note that the first commit is unrelated and fixes a bug in runOptimize1 that is not used by default. It is only triggered if compiled if line https://github.com/OPM/opm-simulators/blob/ad44564f277c7923960c43bba1295375aad24bb8/opm/simulators/wells/GasLiftSingleWellGeneric.cpp#L61 is set to true.

Add check for group production control for LRAT and WRAT in the gasslift code

---

ebos/eclgenericcpgridvanguard.cc
ebos/eclproblem.hh
opm/simulators/utils/ParallelSerialization.cpp
opm/simulators/utils/ParallelSerialization.hpp

When MULT? has been updated runtime in the SCHEDULE section we need to broadcast the updated `TransMult` container.
Depends on: https://github.com/OPM/opm-common/pull/2822

Broadcast mult update

---

opm/simulators/utils/ParallelSerialization.hpp

The ParallelSerialization compile unit is not built in parallel. My bad.

fix: serial build after PR #3671

---

opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/WellGroupHelpers.cpp

Slightly more efficient communication is good, no?

GasLiftGroupInfo: use a array to allow for one sum call

---

opm/simulators/utils/ParallelRestart.hpp

annoyingly, dune has a casting operator for mpicollectivecommunication
-> MPIComm but for some reason does not have a casting operator for
the dummy collectivecommunication -> No_Comm

fix serial build after PR #3675

---

opm/simulators/flow/Main.hpp
python/simulators/PyBlackOilSimulator.cpp
python/simulators/simulators.cpp

Motivation is getting rid of the FLOW_BLACKOIL_ONLY hack.

Use Main::runStatic in PyBlackoilSimulator

---

opm/simulators/linalg/bda/WellContributions.cpp

OpenCL header was included and OpenclKernels used unconditionally in WellContributions.cpp. As this file is also compiled if CUDA is found, it lead to undefined references for e.g. cl::CommandQueue if opencl headers were there and compile error if not.
The header is included (if needed) and appropriately guarded in WellContributions.hpp, already.

Fixes compilation of WellContributions with deactivated OpenCL.

---

opm/simulators/flow/BlackoilModelEbos.hpp

In some models there will be only a few cells with rather high pore volume representing the numerical aquifer. Including them (as non-violated cells) in the ratio will make the ratio lower than without the aquifer there and might lead to accepting vectors as converged when they should not.
Problem found by and hint of fix was given by @totto82.
Needs OPM/opm-grid#555
Closes #3627

Exclude pv of numerical aquifer cells in ratio of cells violating CNV

---

ebos/eclgenericoutputblackoilmodule.cc

The Flow specific `PORV_RC` and `TMULT_RC` solution arrays were tagged as ECLIPSE compatible.  Mark them as Flow specific so they do not cause restart problems in the ECLIPSE compatible case.

Fix Incorrect Solution Array Tag

---

CMakeLists_files.cmake
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/bda/BdaBridge.cpp
opm/simulators/linalg/bda/BdaBridge.hpp
opm/simulators/linalg/bda/BdaSolver.hpp
opm/simulators/linalg/bda/WellContributions.cpp
opm/simulators/linalg/bda/WellContributions.cu
opm/simulators/linalg/bda/WellContributions.hpp
opm/simulators/linalg/bda/cuWellContributions.cu
opm/simulators/linalg/bda/cuWellContributions.hpp
opm/simulators/linalg/bda/cusparseSolverBackend.cu
opm/simulators/linalg/bda/openclSolverBackend.cpp
opm/simulators/linalg/bda/openclWellContributions.cpp
opm/simulators/linalg/bda/openclWellContributions.hpp
tests/test_cusparseSolver.cpp
tests/test_openclSolver.cpp

split in API specific classes for Cuda/OpenCL
this to
1) it's cleaner
2) it avoids pulling in openCL code in cuda classes which leads to clashes between nvidia headers and opencl.hpp
there is still too much API specific things in interface between the
bda components to work through a virtual interface so we still have to cast
to the relevant implementation in various places.
sits on top of #3690 which should be processed first.

Refactor BDA well contributions

---

opm/simulators/linalg/GraphColoring.hpp
opm/simulators/timestepping/AdaptiveSimulatorTimer.hpp

Without this compilation fails on Debian unstable.

Include limits header where needed for g++-11

---

opm/simulators/wells/WellInterfaceFluidSystem.cpp

First PR to remove wrong usage of asserts.

remove assert and handle opposite rates in wecon related fractions. 

---

tests/run-regressionTest.sh
tests/update_reference_data.sh

When the restart test option is invoked for the regression tests currently the equivalent of these shell commands are invoked:
```bash
mkdir $RESULT_PATH/restart
cp $RESULT_PATH/$CASE.UNRST $RESULT_PATH/restart
cd $RESULT_PATH/restart
flow $CASE --sched-restart ....
```
The important point is that the name `$CASE` is used both for the initial simulation and the restarted simulation, and in particular the result file `restart/$CASE.UNRST` will contain a mix of the base case simulation and the restarted simulation. In this PR I suggest renaming the restarted simulation `${CASE}_RESTART` - discovered while debugging the failure of #3694
Will require a data update.

Suggestion: Rename restart case to ${CASE}_RESTART in regression test

---

CMakeLists_files.cmake

My knee-jerk removal of duplicates caused issues here. We do not want to build the WellContribution.cpp without a backend.
Discovered as it broke the nightly focal build.

fixed: build without any bda backend

---

CMakeLists_files.cmake
ebos/eclgenerictracermodel.cc
ebos/eclgenerictracermodel.hh
ebos/ecltracermodel.hh
opm/simulators/utils/VectorVectorDataHandle.hpp

Needs OPM/opm-grid#552
Marking as WIP as it not perfect yet:
- There are deviations in a parallel run that seem to add up during the run (A few percent difference). I am a bit unsure whether this is to be expected or still a bug.
- Did not check restart output, but I am silently assuming that this wrong in parallel (albeit for the wells it magically worked out of the box)
- Distributed wells have not been checked yet. Might be broken, too.
Is there a tool to inspect the binary restart file?

[feature] Adds support for computing tracers in parallel runs.

---

compareECLFiles.cmake
tests/run-parallel-restart-regressionTest.sh
tests/run-restart-regressionTest.sh
tests/run-summary-restart-regressionTest.sh

Use the `rst_deck` application from opm-common to create the `CASE_RESTART.DATA` decks on the fly when restart testing. The advantage of this is that it is not necessary to create explicit restart decks like [SPE1CASE2_ACTNUM_RESTART](https://github.com/OPM/opm-tests/blob/master/spe1/SPE1CASE2_ACTNUM_RESTART.DATA) manually first to enable restart testing.

Create CASE_RESTART deck on the fly when restart testing

---

opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

The cell pressure is independent of well model and belongs to the interface.
This should move the MSW model one step closer to supporting GasWater cases.

Move getPerfCellPressure to wellInterface

---

ebos/eclgenerictracermodel.cc
ebos/eclgenerictracermodel.hh
ebos/eclproblem.hh
ebos/ecltracermodel.hh

In order to support restarting the tracer model the initialization has been split in two steps.

Tracer rst init2

---

ebos/eclgenerictracermodel.cc
ebos/eclgenerictracermodel.hh
ebos/eclproblem.hh
ebos/ecltracermodel.hh

The tracer support is now enabled by default - I don't see many people running flow as:
```
flow --enable-tracer=false CASE.DATA
```
I therefor suggest just removing the switch.

Suggestion: Remove enable switch for tracer support

---

opm/simulators/wells/StandardWellEval.cpp

If original sum ~ 1 and relaxed_update ~ 0 the factor could -> inf
and trigger the assert.
The 1.1. factor will make sure this does not happen

Fix assert in relaxation factor in std well

---

opm/simulators/wells/WellInterfaceFluidSystem.cpp

Only relevant is non default parameters are used
```
--shut-unsolvable-wells = true
```
or
```
--enable-well-operabilty-check-iter=true
```
that shuts wells during time-step

Only check operable wells for wecon

---

CMakeLists_files.cmake

The `test_solvetransposed3x3.cpp` was always included, even when no OpenCL was found, causing a compilation error. Sorry for that.
I'm still testing this.
@bska @blattms

Only include test if opencl is found

---

opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp

As discussed in PR #3728, I think it is better to move the two methods `reduceALQtoGroupTarget()` and `checkGroupTargetsViolated()` from `OptimizeState` to the parent class, then it is not necessary to abuse
`OptimizeState` in `maybeAdjustALQbeforeOptimizeLoop_()` just to call `reduceALQtoGroupTarget()`.
Also fixes a typo (as discussed in PR #3729) in `reduceALQtoGrouptTarget()` where the water rate is updated with the gas flow rate instead of the water flow rate. Should be like this:
```
water_rate = -potentials[this->parent.water_pos_];
```
instead of
```
water_rate = -potentials[this->parent.gas_pos_];
```

Small clean up in GasLiftSingleWellGeneric.cpp

---

opm/simulators/wells/StandardWell_impl.hpp

Resent testing indicates that we may not want to iterate when computing well potentials.  More testing it needed and I therefore make it a draft.

Do not iterate when computing well potentials for standard wells

---

compareECLFiles.cmake
tests/run-regressionTest.sh
tests/update_reference_data.sh

I'm missing the possibility to specify more that one restart step when adding a new teset with **add_test_compareECLFiles** in **compareECLFiles.cmake**.  I would suggest that we allow for specifying more that one step by separating these with a comma (as shown below)
```CMake
add_test_compareECLFiles(CASENAME base_wt_tracer
FILENAME BASE_WT_TRACER
SIMULATOR flow
ABS_TOL ${abs_tol}
REL_TOL ${rel_tol}
DIR tracer
RESTART_STEP 1,3,7)
```
I have updated the script tests/run-regressionTest.sh in this PR to support this, and there is not much needed. Notice that the reference solutions for restarts need to be renamed 
example  in **opm-tests/spe1/opm-simulation-reference/flow/restart**
```
SPE1CASE2_RESTART.INIT -> SPE1CASE2_RESTART_60.INIT
SPE1CASE2_RESTART.SMSPEC -> …
```

Multiple restart tests

---

compareECLFiles.cmake
opm/simulators/flow/Main.hpp
tests/run-split-comm-test.sh

This allows for testing the simulator with the artifically split communicator, in order to verify that there is no inappropriate usage of the world communicator.
@blattms this is not (yet) the test you asked for, but the code change that should allow the test to be writte easily (and without compiling an extra dozen flow binaries).
I have two questions:
- Since the parameter system is not up at the time we initialize MPI, I had to write a special treatment. This is in the function handleTestSplitCommunicatorCmdLine_(), basically you put "--test-split-communicator=true" as the VERY FIRST argument to the program, then you activate the feature. Is this ok? It means it is easy to write a command line to test it, but on the other hand it is a bit of a hack. The argument only superficially …

Replace DEMONSTRATE_RUN_WITH_NONWORLD_COMM macro with runtime bool.

---

opm/simulators/utils/PartiallySupportedFlowKeywords.cpp

ROCKCOMP(ROCKOPT) only supports REVERS and IRREVERS options.

Validate ROCKCOMP Update

---

opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp

Note this PR builds on #3747 which should be merged first.
Continues the work in #3747 to fix up repetitive code in `GasLiftSingleWellGeneric.cpp`.  In this PR `getOilRateWithGroupLimit_()`, `getGasRateWithGroupLimit_()`, `getWaterRateWithGroupLimit_()`, and `getLiquidRateWithGroupLimit_()` is refactored into a single generic method called `getRateWithGroupLimit_()`. 
Note that this change also includes a bug fix, see [this comment](https://github.com/OPM/opm-simulators/pull/3673/files#r771027732) and I guess this could be a reason to why the solution for the case [`4_GLIFT_MODEL5`](https://github.com/OPM/opm-tests/blob/master/model5/4_GLIFT_MODEL5.DATA) changes:
here `4_GLIFT_MODEL5_F1` is with the code in the master branch, `4_GLIFT_MODEL5_F2` (which is identical to the curve for …

Refactor some methods in `GasLiftSingleWellGeneric.cpp`

---

opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp

This is in agreement with [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#con2-by-default-make-member-functions-const): _A member function should be marked `const` unless it changes the object’s observable state. This gives a more precise statement of design intent, better readability, more errors caught by the compiler, and sometimes more optimization opportunities_.

Made some methods in GasLiftGroupInfo const

---

opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp

Note this PR includes #3748 which should be merged first. 
Continues the work in #3748 of cleaning up some methods in `GasLiftSingleWellGeneric.cpp` to get rid of repetitive code and make it easier to maintain the code in the future.
This last commit refactors `getOilRateWithLimit_()`, `getGasRateWithLimit_()`, and  `getWaterRateWithLimit_()`. The common part of the methods is split out into a new method called `getRateWithLimit_()`.
I have tested this PR with the case [`4_GLIFT_MODEL5`](https://github.com/OPM/opm-tests/blob/master/model5/4_GLIFT_MODEL5.DATA) and there was no difference in the solution for FGLIR (field gas lift injection rate) compared to the solution for #3748 which indicates that the numerical solution is not affected by this commit.

Refactor some methods in `GasLiftSingleWellGeneric.cpp` (part 2)

---

opm/simulators/wells/StandardWell_impl.hpp

This is needed to get consistent estimates for the summary vectors
* `{F,G,W}OP{R,T}{F,S}` &mdash; Free/Vaporized Oil Production Rate/Cumulative Volume
* `{F,G,W}GP{R,T}{F,S}` &mdash; Free/Dissolved Gas Production Rate/Cumulative Volume
in the case of distributed wells.
Thanks to [at]blattms for the suggested fix.

Accumulate Dissolved Gas and Vaporized Oil Flow Rates Across Ranks

---

compareECLFiles.cmake

This would have detected OPM/opm-common#2922 as the test fails with master.
Needs OPM/opm-common#2923 to succeed.

Let ctest test 3_A_MPI_MULTFLT_SCHED_MODEL2 in parallel.

---

opencl-source-provider.cmake

Otherwise the definitions determined by CMake are not available to opm/simulators/linalg/bda/opencl.hpp and choosing the correct header might fail.
On my system this at least fixes a warning.
Fallout from #3749

Include config.h in clSources.cpp to include correct openCL header.

---

CMakeLists_files.cmake

Fixes build without opencl after #3750

fixed: conditionally build test_csrToCscOffsetMap

---

opm/simulators/wells/MultisegmentWellGeneric.cpp
opm/simulators/wells/MultisegmentWellGeneric.hpp

The new functionality is `bruteForceBracket()`, which tries to find the bracket that contains the bhp solution in a brute force manner. 
The current approach is very supplemental, only trying to use this brute force method to handle the situation that the existing method fails.  There probably some room for optimize, while the current PR represents a quick solution for the problem with little risk of breaking existing successful running. 
Other parts in this PR are pure refactoring to make the function `computeBhpAtThpLimitProd()` more readable.

fixing the failure that bhp could not be calculated with thp limit

---

opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

Item 3 in liftopt sets a delay time between each gaslift optimization
LIFTOPT item 3 = 15 is used in GLIFTOPT_9.DATA in gaslift and with this change the simulator behave as expected.

support none trivial item 3 in LIFTOPT.

---

opm/simulators/wells/VFPInjProperties.cpp

it is a finding from one of the test cases. We do not have a situation to verify about the producers, so we do not include producers in this PR although probably should be the same. 
Basically, this is an injector with zero GRAT control. The reference results output zero THP values regardless the BHP values of the well.

return zero thp value for extremely small injection rate

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

The guide rates needs updated rates to be accurate while the initial well rates for newly opened well needs the guiderates to get good estimates. Adding an extra update on the guiderate during the first iterations thus improves the accuracy of the simulator.

Update guiderates after with new rates from newly opened wells

---

CMakeLists_files.cmake

The headers `BlackoilWellModel.hpp`, `StandardWell.hpp`,and `WellInterface.hpp` all include various `GasLift*.hpp` headers directly. That means that any client code that uses those well-related headers will need to have the `GasLift*` headers available too.
Also sorts the headers under `opm/simulators/wells` to make the file easier to read.

Add gas lift headers to PUBLIC_HEADER_FILES

---

opm/simulators/wells/GasLiftCommon.hpp

The order of the initialization of member variables in the constructor should match the order in which the variables are declared in the class.

Silence reorder warning in GasLiftCommon

---

opm/simulators/flow/Main.hpp
opm/simulators/utils/ParallelFileMerger.cpp
opm/simulators/utils/readDeck.cpp
opm/simulators/utils/readDeck.hpp

There was a fallout when skipping concating these files to the default ones (PR #1708). We should also have deactivated creating these files at all. As a result these files appeared in all aborted parallel runs.
This change now prevents creating and logging to these files in parallel in a default run (--enable-parallel-logging-fallout-warning=false).
Developers can still activate logging and concating to see whether everything is only logged on the io process by passing --enable-parallel-logging-fallout-warning=true.
Alternative to #3725.
Closes #3709

Prevent multiple *.?.dbg/prt files in production parallel runs.

---

opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp
opm/simulators/wells/GasLiftSingleWell.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp
opm/simulators/wells/GasLiftSingleWell_impl.hpp
opm/simulators/wells/GasLiftStage2.cpp

Continues the work in #3751 of cleaning up code in `GasLiftSingleWellGeneric.cpp` to get rid of repetitive code and make it easier to maintain the code in the future.
Introduces two new data types `BasicRates` and `LimitedRates` to capture oil, gas, and water rates, and whether they have been limited by well or group targets. This reduces the number of variables that are passed to and returned from various methods and thus makes the code easier to read.
I tested this PR with the case [`4_GLIFT_MODEL5`](https://github.com/OPM/opm-tests/blob/master/model5/4_GLIFT_MODEL5.DATA) and there was no difference in the solution for GGLIR (group gas lift injection rate for group `PLAT-A`) compared to the solution with the code in the master branch, indicating that the numerical solution is not …

Refactor code in GasLiftSingleWellGeneric.cpp (part 3)

---

tests/update_reference_data.sh

the formatting for the standard git status output is unstable,
and has changed in newer versions of the git client. this lead
to missing lines in untracked files.

fixed: use the --porcelain option when parsing git status

---

opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp

Dont increase gaslift if the groups alq + gas production rate is above the given target (GLIFTOPT item 3)
We also need to add the logic where we decrease gaslift if the groups alq + gas production rate is above target. That will be a later PR.

Add support for maximum total gas (alq + gas rate) in GLIFTOPT

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp
opm/simulators/wells/GasLiftStage2.cpp
opm/simulators/wells/GasLiftWellState.hpp

This makes sure the guide rates (i.e. the distribution between wells/groups) are updated when gaslift changes during iterations.
(LIFTOPT item 4 = YES) and as a result reduce oscillations in the solution.

update well potentials in wellState along with alq and update guide rates accordingly

---

opm/simulators/wells/GlobalWellInfo.hpp

This generates warnings when using GCC's `-Wpedantic` option.

Remove Extraneous Semicolon

---

CMakeLists_files.cmake
ebos/eclgenericoutputblackoilmodule.cc
ebos/eclgenericoutputblackoilmodule.hh
ebos/eclinterregflows.cc
ebos/eclinterregflows.hh
ebos/ecloutputblackoilmodule.hh
ebos/eclwriter.hh
tests/test_eclinterregflows.cpp

This PR introduces a new helper class
```C++
Opm::EclInterRegFlowMapSingleFIP
```
that wraps an object of type
```C++
Opm::data::InterRegFlowMap
```
(see OPM/opm-common#2945) along with the MPI rank's notion of a FIP region array definition (e.g., the local `FIPNUM` array).  The new single-FIP flow map is responsible for accumulating local contributions to the inter-region flows defined by that FIP array.  In the case of connections between MPI ranks, the rank that owns the lowest region ID accumulates the associate flow rates.
We also add a new grid traversal that calculates and aggregates surface condition component flow rates across the bulk connections.  While presently restricted to accumulating inter-region flows, this pass can also be extended to supporting the 3D restart vectors …

Accumulate Inter-Region Phase Flow Rate Contributions

---

ebos/eclgenericoutputblackoilmodule.hh
ebos/eclinterregflows.hh
ebos/eclwriter.hh

This is a potentially expensive operation and so we should not run it unless such values are actually needed for output purposes (e.g., inter-region flow summary vectors).

Don't Capture Local Flux Data Unless Needed

---

ebos/ecloutputblackoilmodule.hh

This PR adds support for calculating/extracting the block-level phase pressures for water (`BWPR`) and gas (`BGPR`) for summary output purposes.

Support Calculating Phase Pressures for Water/Gas at Block Level

---

opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftSingleWell.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp
opm/simulators/wells/GasLiftSingleWell_impl.hpp
opm/simulators/wells/GasLiftStage2.cpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterfaceGeneric.hpp
opm/simulators/wells/WellInterface_impl.hpp

Make VFP calculations work for the two-phase oil-water case. The plan is to address the issue with gas lift optimization in  #3668. 
Currently the VFP calculations requires three-phase input data, see the documentation for keyword `VFPPROD` and its implementation in [VFPProdProperties.cpp](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/VFPProdProperties.cpp). To extend the VFP calculations to the two-phase oil-water case, it might be enough to set the gas flow rate to a dummy value in VFPPROD record 5 (GFR values) and supplying a dummy input value for the gas rate to the methods in `VFPProdProperties.cpp`? 
This change does at least make the test case `GASLIFT-TST02` in #3668 run to the end. The next step is to see how the summary output compares with Eclipse and …

Extend VFP calculations to two-phase flow.

---

tests/test_vfpproperties.cpp

Refer to https://github.com/OPM/opm-common/pull/2971. In order to use the new constructor proposed in that PR, the constructor must now be passed a boolean variable signalling if gaslift is active.

Use new VFPProdTable constructor 

---

opm/simulators/wells/SegmentState.cpp
tests/test_wellstate.cpp

when bhp is changed. It is much safer and more reasonable.
using multiplication is more likely to have dramatic values.

using addition to update segment pressure when bhp is changed

---

python/simulators/CMakeLists.txt

Instead of always using site-packages we query the sitepackages path from Python. If it matches dist-packages then we use dist-packages if we install below /usr, otherwise site-packages is used.
This will also make sure that the Python files end up in the same location as for the ones of opm-common. This should make using them easier.
The inconsistency before was that on Debian we install into dist-packages for opm-common and here we always into site-packages. This created quite some confusion (on all sides), see #3822. And does not work as expected.
BTW only 100% consistent if OPM/opm-common#2978 is also merged

[python] Make sure Python files are installed similar to opm-common.

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftCommon.cpp
opm/simulators/wells/GasLiftCommon.hpp
opm/simulators/wells/GasLiftGroupInfo.cpp
opm/simulators/wells/GasLiftGroupInfo.hpp
opm/simulators/wells/GasLiftSingleWell.hpp
opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp
opm/simulators/wells/GasLiftSingleWell_impl.hpp
opm/simulators/wells/GasLiftStage2.cpp
opm/simulators/wells/GasLiftStage2.hpp
tests/test_glift1.cpp

Some of the gas lift debugging output code outputs identical messages for all ranks. In some cases this is probably not desirable, in other cases it can be desirable if the output is prefixed by the rank number. Then it can be used as a debugging aid to verify that all ranks outputs identical messages.
This PR also cleans up the code by moving common parts of code to the common base class `GasLiftCommon`.
See also #3842.

Cleanup gaslift debugging output code

---

opm/simulators/wells/WellInterfaceFluidSystem.cpp
opm/simulators/wells/WellInterfaceFluidSystem.hpp
opm/simulators/wells/WellInterfaceGeneric.hpp
opm/simulators/wells/WellInterface_impl.hpp

This means that we may temporary allow a producer to operate with thp below its limit if that gives a higher production. The operability of these wells will be tested along with wells under thp and bhp control.

Avoid switching to thp control if production is decreasing or injection is increasing

---

opm/simulators/flow/Main.hpp
opm/simulators/utils/readDeck.cpp
opm/simulators/utils/readDeck.hpp

If no cell has a valid corner-point geometry, typically caused by using `GDFILE` to read non-finite data such as all `ZCORN = -1.0E+20`, then we must not attempt to generate a grid structure.  If we do, we will typically just fail somewhere deep down in the corner-point processing code and generate a diagnostic message that's hard to decipher.
With this commit we instead output a diagnostic message of the form
```
Error: No active cell in input grid has valid/finite cell geometry
Please check geometry keywords, especially if grid is imported through GDFILE
Program threw an exception: Allocating the simulation vanguard failed: No active cell in input grid has valid/finite cell geometry
Please check geometry keywords, especially if grid is imported through GDFILE
```
This may not be a lot …

Don't Process Corner-Point Data If No Valid Cell Geometry

---

opm/simulators/wells/WellInterfaceFluidSystem.cpp

The motivation is to avoid premature closing of wells due to
1) inaccurate potentials
2) inaccurate ratios based on negative rates

Avoid premature closing of wells due to econ limits

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWellEval.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/StandardWellEval.hpp
opm/simulators/wells/StandardWell_impl.hpp

If d=1-rs*rv=0 we can not back-compute the surface volumes from the reservoir volumes. 
This PR consists of 2 commits. 
1) Avoid hard throw when d <=0 in MSW model and instead continue as if rs = rv = 0 for that connection. This fix is motivated by a field model and is sufficient for the simulator to finish the run. 
2) The second is still WIP in that it is not tested at all. When grabbing for "d = " I noticed that most places there was no guards for d = 0. The solution proposed for d<=0 is to continue as if rs = rv = 0.

Fix d issues 

---

opm/simulators/utils/moduleVersion.cpp

In combination with the relevant changes in opm-common this prevent flow in binary Linux packages from having a timestamp in the executable that changes with every rebuild.
With the changes in opm-common  one can now set the variable OPM_BINARY_PACKAGE_VERSION to a meaningful version string (Debian 11.2: 2021.10-4). If that is done and flow is built from tarballs it will now not have a time stamp and print the package version to the PRT file. E.g.
```
Flow Version     =  2021.10 (Debian 11.2: 2021.10-1)
```
Note that without setting the variable or when building from a git repository there is no change.
Downstream of OPM/opm-common#2980
Closes #3832

Use empty string for buildtime if BUILD_TIMESTAMP is not set.

---

ebos/ecloutputblackoilmodule.hh

This PR adds support for the block level solvent saturation summary output keyword `BNSAT`.

Retrieve Block Level Solvent Saturation When Requested

---

opm/simulators/wells/WellInterface_impl.hpp

Looks like it gives better results for some test cases. Creating this one for performance checking. 
Notably, I think inner iterations are more essential for multisegment wells.

[testing] always using inner iterations for testing purpose.

---

redhat/opm-simulators.spec

- add parameter for which toolset to use
- build against openmpi3
- build with python support
- add boolean flags for the different mpi builds (mostly for testing)
- add parameter for appending extra token to package names.
this can be used for allowing multiple versions to be installed on the
same system.

update redhat packaging

---

opm/simulators/timestepping/ConvergenceReport.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellInterface_impl.hpp

Should not be affect default behavior. But fixes some fallout's in the shut-unsolvable-wells option.

fix to --shut-unsolvable-wells=true option

---

opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWellEval.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

This should not change the behavior but avoid unexpected "errors"  counts in the error summary. 
Issue reported by @tskille

avoid throw for nan residuals instead return well as unconverged

---

opm/simulators/wells/GasLiftSingleWellGeneric.cpp
opm/simulators/wells/GasLiftSingleWellGeneric.hpp
opm/simulators/wells/WellInterface.hpp
opm/simulators/wells/WellInterface_impl.hpp

Assigns a maximum ALQ value to each GLIFT producer when doing well testing in `beginTimeStep()`. This is done to allow the well to attain a positive potential and thereby be considered as open. Then, later in the timestep, when `assemble()` is called, the full gas lift optimization procedure can adjust the ALQ to its "correct" value.
It is also observed that in some cases when gas lift is switched off by setting ALQ to zero, and later in the schedule is switched back on again, it might not be possible to determine bhp from thp (the iteration fails to converge) for low small ALQ values. Instead of aborting the gas lift optimization, we should try increasing ALQ until we get convergence or until the maximum ALQ for the well is reached.
With this change to the code, test case …

Well testing of gas lift wells

---

opm/simulators/wells/StandardWell_impl.hpp

Currently [GASLIFT-02](https://github.com/OPM/opm-tests/blob/master/gaslift/GASLIFT-02.DATA) fails with an assertion error:
```
Starting time step 0, stepsize 16 days, at day 32/60, date = 01-Feb-2021
Restart file written for report step  1/58, date = 01-Feb-2021 00:00:00
flow: /home/hakon/test/opm/opm-simulators/opm/simulators/wells/WellInterfaceGeneric.cpp:655: Opm::WellInterfaceGeneric::computeBhpAtThpLimitProdCommon(const std::function<std::vector<double>(double)>&, const Opm::SummaryState&, double, double, double, Opm::DeferredLogger&) const::<lambda(const std::vector<double>&)>: Assertion `rates.size() == 3' failed.
[hakon-Precision-7530:716293] *** Process received signal ***
[hakon-Precision-7530:716293] Signal: Aborted (6)
```
VFP calculations for two phase gas lift does not work …

WIP: Fix assertion error for GASLIFT-02

---

opm/simulators/wells/WellInterfaceGeneric.cpp

Based on testing on the Norne prediction cases in opm-tests/norne/
This needs more testing/discussion before it can be merged.

tighten approximated solution bhpFromThpLimit from 3 to 0.1 bar

---

opm/simulators/wells/MultisegmentWell.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp

Attempt to improve convergence for problematic MSW wells. With default parameters i.e. 
regularization_factor_ms_wells_ = 1.0 this PR does not have any effect. 
The idea is to increase the default regularization factor to > 1.0 in later PR.

regularize MSW equation when iter > strict_inner_iter

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellInterface_impl.hpp

Some fixups for combination STOP + shut_unsolvable_wells=true (default is false) 
This also change default behavior for wells with STOP that do not converge when time step is less than threshold. 
Tested on the norne prediction tests in opm-tests/norne

Fix STOP in combination with inoperable/unsolvable

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/SingleWellState.cpp
opm/simulators/wells/SingleWellState.hpp
opm/simulators/wells/WellInterfaceFluidSystem.cpp
opm/simulators/wells/WellInterface_impl.hpp

This fixes another fallout related to trivial group rates. See #3887 This time the well control starts oscillating between group (with target 0) and THP. This PR explicitly prevent switching to THP control if the target is zero. 
At the current stage only the case where the group target is zero is flagged, we may want to consider also flagging cases where the well has trivial target.

fix trivial group target

---

opm/simulators/wells/WellInterface_impl.hpp

This fixes (avoids premature shutting of a well) a corner case where a well is controlled by a group that has zero rate. Due to numerical instability the well still gets an epsilon rate and skip the improved initialization used for wells with trivial rate. Adding an epsilon in the check is sufficient to keep the well open and ready for production when the group gets a non-trivial target.

use alternative init for wells with all rates less than eps

---

opm/simulators/utils/readDeck.cpp

Actually one should rename the function used from opm-common, too.
But that is for later...

Spelling fix geomtry -> geometry.

---

opm/simulators/wells/SingleWellState.cpp

config.h goes first in *all* compile units..
hopefully will fix odr violation reported here; 
https://launchpadlibrarian.net/598757949/buildlog_ubuntu-jammy-amd64.opm-simulators_2022.04-rc1-1~jammy_BUILDING.txt.gz

fixed: add missing config.h include

---

opm/simulators/utils/readDeck.cpp

Actually one should rename the function used from opm-common, too.
But that is for later...
Backport of #3895 to release.

[backport] Spelling fix geomtry -> geometry.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

In `BlackoilWellModel<TypeTag>::prepareTimeStep(DeferredLogger& deferred_logger)`, when some well event happen, we update the well state to match the new control type. 
Before we use the well for well solving, we need to update the primary variables and Evaluation related to wells.

update primary variables in prepareTimeStep after updating the well target

---

opm/simulators/wells/MultisegmentWell_impl.hpp

Should not affect the simulator with default setup, but see #3906

reset regularize_ before starting the inner iterations

---

opm/simulators/utils/readDeck.cpp

This gives more information to the user and hopefully aids them in resolving the underlying issue.

Emit Actual Message on Input Failure

---

opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/python/PyBlackOilSimulator.hpp
python/simulators/CMakeLists.txt
python/simulators/PyBlackOilSimulator.cpp
python/simulators/__init__.py
python/test/test_basic.py
python/test/test_schedule.py

Depends on upstream https://github.com/OPM/opm-common/pull/3020
Adds some methods that enables `Opm::Schedule` to be dynamically modified from Python. A test case, `test_schedule.py` illustrates the use case.

Dynamically update Opm::Schedule from Python

---

ebos/eclcpgridvanguard.hh
ebos/eclgenericcpgridvanguard.cc
ebos/eclgenericcpgridvanguard.hh

Commit 5067ce2f27e64c05c04a634de93b91aee6685afa (initially OPM/opm-models@e22366d4a, PR https://github.com/OPM/opm-models/pull/103) implicitly assumed that the `gridv` parameter would coincide with `grid_->leafGridView()`.  Make this assumption explicit.
Resolves #3927.

Use Consistent Grid Views for Transmissibility Calculation

---

opm/simulators/linalg/bda/BdaBridge.cpp
opm/simulators/linalg/bda/BdaBridge.hpp

The block-jacobi-ILU preconditioner did not work with `cusparseSolver`, due to zeros on the diagonal.
They were supposed to be removed by `checkZeroDiagonal()`, but this was bugged.
It used only one array for both `matrix` and `jacMatrix`, whereas they each need their own.
Also other minor changes were made.

Fix: zeros were not replaced correctly in the diagonal for GPU

---

opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp

The current check for operability using IPR is different between STW and MSW. STW return inoperable if at one of the components has negative(for producers) IPR. For MSW it checks if the sum is negative. This PR changes both so that only well where all components have negative IPRs are inoperable. I mark it as WIP and draft since I still don't understand how the well operability differs between the components.

Fix well operability

---

ebos/eclcpgridvanguard.hh
ebos/eclgenericcpgridvanguard.cc
ebos/eclgenericcpgridvanguard.hh

In #3927 an inconsistency was reported, and subsequently resolved in #3929. The issue was that one grid view was passed in as an argument, and another one was obtained from the grid, then both were used in the function. The previous fix removed the argument, and used always the one from the grid. The current fix does the opposite: re-instate the argument, and do not use the one from the grid.
The reason for this, is that if the GridView type used to instantiate the class (ultimately same as the TypeTag's GridView) is different from the grid's LeafGridView, this does not compile. This happens when dune-fem is found and used, then the view held by the vanguard is of a different type.
The current fix is therefore an improvement (as now it compiles...). But it points out that we may have many …

Re-add grid view argument to doLoadBalance_().

---

ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
ebos/eclgenericcpgridvanguard.cc
ebos/eclgenericcpgridvanguard.hh
ebos/eclgenericvanguard.hh
opm/simulators/linalg/ISTLSolverEbos.hpp

The block-Jacobi partitioner (commit https://github.com/OPM/opm-simulators/commit/e360c00b73dca89be9f1716c9a704905576b7792, PR #3815) uses grid interfaces that are only available in CpGrid and this blocks introducing other grid managers such as ALUGrid.  Since the partitioner was only added for OpenCL, guard special purposes accesses with HAVE_OPENCL.
This is a temporary measure and we will venture to restore the partitioner later, although possibly restricted to CpGrid only.

Temporarily Limit Block-Jacobi Partitioner to OpenCL Only

---

opm/simulators/linalg/bda/opencl/BILU0.cpp
opm/simulators/linalg/bda/opencl/openclSolverBackend.cpp

When `verbosity>=3`, the openclSolver will time certain components, like the preconditioner application, spmv, and well application, and print them.
To get accurate timings, the solver must wait for the opencl kernels to finish, which it did not before.
This uses `queue->finish()`, this works because `openclSolver` only ever uses one queue. If multiple queues were to be used, for example when overlapping copying and computation, or having two kernels simultaneously, changes have to be made.
I wanted to put `if(verbosity>=3)queue->finish();` into an inlined function before.
But I've also merged some of the timers, so that they only work when their results are actually used. The `Dune::Timer` is lightweight, but the `if(verbosity>=3)` should be even more lightweight.

Fix: verbose timing for openclSolver

---

opm/simulators/wells/StandardWellEval.cpp

Fixes bug introduced in 06a8b0ee in #3937.
Keeping the wells separate would cause convergence issues on GPU (both cusparse and opencl).
@blattms

Fix stdwell apply on GPU

---

opm/simulators/linalg/bda/opencl/BILU0.cpp
opm/simulators/linalg/bda/opencl/kernels/ILU_apply1.cl
opm/simulators/linalg/bda/opencl/kernels/ILU_apply1_fm.cl
opm/simulators/linalg/bda/opencl/kernels/ILU_apply2.cl
opm/simulators/linalg/bda/opencl/kernels/ILU_apply2_fm.cl
opm/simulators/linalg/bda/opencl/openclKernels.cpp
opm/simulators/linalg/bda/opencl/openclKernels.hpp

The ILU apply kernels launched `Nb/32` workgroups, where `Nb` is the number of blockrows in the matrix. This is wasteful, since due to level_scheduling, the number of blockrows processed in parallel is less than that. It now launches one workgroup for each blockrow.
Also changed the workgroup size to 64, this is slightly faster for a bigger case.
The ILU decomposition kernel always launched 1024 workgroups, it now also launches one workgroup for each blockrow.
Performance gains are marginal.

Tweak opencl launch params

---

opm/simulators/utils/UnsupportedFlowKeywords.cpp

Remove MINPORV, keyword from unsupported keyword list, opm-common PR to follow to handle keyword. Remove RTEMPA and TEMPVD, as these are already supported.

Unsupported keywords

---

opm/simulators/wells/StandardWell_impl.hpp

If we compute a sum over all perforations than we need to cater for the case of distributed wells. That is we need to also sum up  over all processes involved after performing the local sum.
One of these global sums was missing in computeWellConnectionDensitesPressures for producers when we compute the weights based on well transmissibilities.

[bugfix] Fix well transmissibility weights for distributed wells.

---

opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellState.cpp

We should always keep in mind that the number local perforations is no sign/hint for the number of perforations the well would have in a sequential run. Hence returning in a function because `perf_data` is empty might lead to deadlocks and checking whether all perforations are empty needs communication. Both is fixed with this PR and now Norne runs with distributed wells even for @andrthu patch of opm-grid.
Such a small fix that needed lots of debugging time... Amazing.

[bugfix] Fixes deadlocks with agressively distributed wells

---

CMakeLists_files.cmake
opm/simulators/aquifers/AquiferAnalytical.hpp
opm/simulators/aquifers/AquiferCarterTracy.hpp
opm/simulators/aquifers/AquiferFetkovich.hpp
opm/simulators/aquifers/AquiferInterface.hpp
opm/simulators/aquifers/AquiferNumerical.hpp
opm/simulators/aquifers/BlackoilAquiferModel.hpp
opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp

Refactor to have a common base for analytical and numerical aquifers, and then use them through this interface in the BlackOilAquiferModel.

BlackOilAquiferModel: use implementations through interface

---

CMakeLists_files.cmake
ebos/eclequilinitializer.hh
ebos/equil/equilibrationhelpers.cc
ebos/equil/equilibrationhelpers.hh
ebos/equil/initstateequil.cc
ebos/equil/initstateequil.hh
tests/test_equil.cc

Allows for building once, instead of once per simulator object. Saves 4-5 seconds per simulator object on my box.

Make the equilbrium initialization code a private template

---

compareECLFiles.cmake
ebos/eclgenericoutputblackoilmodule.cc
tests/update_reference_data.sh

Commit 6d3da3d2e (PR #3397) introduced the notion of a "dynamic", pressure dependent pore-volume and switched the `PoreVolume` aggregates to reference condition evaluation for output to the `PORV` field in the .PRT file.  We did however fail to update all existing uses of `PoreVolume` which introduced an inconsistency.  In particular, for simulation models without hydrocarbons&mdash;e.g., a single-phase water run&mdash;the numerator of the volume weighted average would include
pressure effects through the rock compressibility but the denominator would not.
Thanks to Edmund Stephens for discovering the issue and providing an example model for analysing the underlying issue.
Resolves #3984

Fix Averaged Quantities for Non-HC Simulations

---

opm/simulators/utils/readDeck.cpp

With this, the tag limit of 10 is used from the very start of the run, and not only after the deck has been read.
This eliminates duplicate warnings (in excess of 10) during deck reading, they will still appear in the PRT and DBG files, however.

Limit warnings to terminal during deck input.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp

We already have the mapping available, and using the equilGrid() is only valid on rank 0.

Bugfix and simplification of cartesian mapping.

---

opm/simulators/linalg/ParallelIstlInformation.cpp

Commit 371b2592f (PR #4010) misordered the closing brace of a namespace and the conditional declarations dependent upon MPI availability.  This commit restores the expected order and fixes non-MPI builds.

Restore Non-MPI Builds

---

CMakeLists_files.cmake
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/ParallelOverlappingILU0.cpp
opm/simulators/linalg/ParallelOverlappingILU0.hpp
opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
opm/simulators/linalg/PreconditionerFactory_impl.hpp
tests/test_milu.cpp

i chose to split in a separate _impl file because this code is so
generic that there may be downstream users who want to use on other
matrix types than what we use in opm-simulators.

put ParallelOverlappingILU0 in separate compile unit

---

opm/simulators/utils/ParallelRestart.cpp
opm/simulators/utils/ParallelRestart.hpp

Since Rates is not longer a POD, it needs explicit packSize()/pack()/unpack() support. This also applies to classes containing Rates, namely Connection and Segment.
On my system, restart fails in parallel due to this bug (the rates member of some connection becomes corrupt). If it works for you now, it is just "luck"...
(Drive-by fix: also added initialization of two dummy arguments that generates warnings when used for getting packSize().)
Requires OPM/opm-common#3104

Add packing support for classes needing it.

---

opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp

Moving it ensures it is also done for restart simulation runs. Without this, the well model will actually initialize the IQs, but only for owned cells, not overlap/ghost cells, which caused parallel failure.
This is not detected with the traditional linearizer, as the updating of ElementContexts will lead to evaluation of the missing cells, but with the TpfaLinearizer parallel restart fails without this.
Cherry-picked from https://github.com/OPM/opm-simulators/pull/4017

Ensure intensive quantities are calculated at start of simulation.

---

ebos/eclactionhandler.cc

End users typically do not care that a particular action did NOT trigger at a particular time and these messages will typically reduce the utility of the `CASE.PRT` file.  On important field cases we've seen more than 100,000 such messages in a single run which is quite overwhelming.
Since we're now directing the messages to the `.DBG` file instead we're not taking away any diagnostic ability, merely altering the location of the information.

Direct All Non-Triggered Action Messages to Debug File

---

tests/test_ParallelRestart.cpp

Sits on top of https://github.com/OPM/opm-simulators/pull/4056
Downstream of https://github.com/OPM/opm-common/pull/3119
Temporarily we now have two tests for serializing CellData, one using the direct Mpi::pack/unpack/packsize and one using the eclmpiserializer.

added: data::CellData mpiserializer test

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

Use compressedIndexForInterior() for mapping cartesian indices.

---

opm/simulators/utils/ParallelRestart.cpp

This keeps popping up and I keep forgetting it.
While the code in the primitive serializer has dummy implementations without MPI, an annoying issue in dune keeps biting us.
CollectiveCommunication&lt;<MPI_Comm&gt;> has a casting operator to MPI_Comm.
However, CollectiveCommunication&lt;Dune::No_Comm&gt; has no casting operator to Dune::No_Comm.
We rely on the casting operator so we can use the collectivecommunication as a MPI_comm where appropriate. And then it all breaks in serial..

fixed: do not include EclMpiSerializer without mpi

---

CMakeLists_files.cmake
ebos/eclgenerictracermodel.cc
opm/simulators/linalg/ISTLSolverEbos.cpp
opm/simulators/linalg/ISTLSolverEbos.hpp
tests/test_glift1.cpp

in particular this means simulator objects are now not dependent on FlexibleSolver.hpp and BdaBridge.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4019

put parts of ISTLSolverEbos in separate compile unit

---

ebos/eclmpiserializer.hh
opm/simulators/utils/MPIPacker.cpp
opm/simulators/utils/MPIPacker.hpp

No need for this in the packer.
Also fix predicate for vector to allow custom allocators.
Sits on top of https://github.com/OPM/opm-simulators/pull/4087

Optionals are handled in serializer

---

ebos/eclmpiserializer.hh
opm/simulators/utils/MPIPacker.cpp
opm/simulators/utils/MPIPacker.hpp

Thus we can remove support in MPIPacker.
Sits on top of https://github.com/OPM/opm-simulators/pull/4089

Handle all maps in serializer

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

As requested by @OPMUSER  in https://github.com/OPM/opm-simulators/pull/3837#issuecomment-1141853225
I dropped the switching history RATE->FLE->RATE i.e. only the final change is dumped to the terminal. 
The old logging is moved to .DBG so if you are interested in detailed switching history you will find it there. 
I suggest doing the same for the wells as
ORAT->GRAT->ORAT type of output may not be that useful for the user IMO.

cleanup group switching output to terminal

---

ebos/eclmpiserializer.hh
opm/simulators/utils/MPIPacker.cpp
opm/simulators/utils/MPIPacker.hpp
opm/simulators/utils/ParallelSerialization.cpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
tests/test_broadcast.cpp

Handle all vectors in eclmpiserializer and remove support in MPIPacker.
This contains some more changes, in particular we need to move the variadic broadcast support into the serializer since that previously relied on the vector support in the MPIPacker.

mpiserializer: handle all vectors

---

ebos/eclmpiserializer.hh
tests/test_broadcast.cpp

change the test to broadcast from rank 1 instead of 0 so this bug does not resurface.
i screwed up juggling all my branches and accidentially squashed the fix for this is the wrong branch. sorry for that.

fixed: wrong root rank in variadic broadcast

---

opm/simulators/wells/MultisegmentWellEval.cpp

for multisegment wells.
The scenario is that an injector is with zero rate control, and we get something like `-2.e-233` value for the primary variable and triggered assertion failure
```
MultisegmentWellEval.cpp:1783: void Opm::MultisegmentWellEval<FluidSystem, Indices, Scalar>::updateUpwindingSegments() [with FluidSystem = Opm::BlackOilFluidSystem<double, Opm::BlackOilDefaultIndexTraits>; Indices = Opm::BlackOilIndices<0, 0, 0, 0, false, false, 0, 0>; Scalar = double]: 
Assertion `! (baseif_.isInjector() && primary_variables_evaluation_[seg][GTotal] < 0.)' failed.
```

avoiding wrong sign for QTotal primary variable for top segment

---

CMakeLists_files.cmake
ebos/eclmpiserializer.hh
opm/simulators/utils/MPIPacker.cpp
opm/simulators/utils/MPIPacker.hpp

to limit the overload party, we put packing details for
specific types in separate structs.
emit compiler error if unsupported type is given,
better to detect this on compile time rather than runtime.
also adds array packing for POD vector/arrays.
Sits on top of https://github.com/OPM/opm-simulators/pull/4106

Refactor MPIPacker

---

ebos/eclmpiserializer.hh
opm/simulators/utils/MPIPacker.cpp
opm/simulators/utils/ParallelEclipseState.hpp

Simplify the user interface for the serializer. All ops can now go through operator().
Downstream of https://github.com/OPM/opm-common/pull/3148
Sits on top of https://github.com/OPM/opm-simulators/pull/4107

Simplifications in serializer

---

opm/simulators/wells/VFPProperties.hpp

a class with a reference member cannot be default initialized, so constructor is implicitly deleted. quells a clang warning

fixed: remove default constructor declaration

---

CMakeLists_files.cmake
ebos/eclbasevanguard.hh
ebos/eclcpgridvanguard.hh
ebos/eclgenericcpgridvanguard.cc
ebos/eclgenericcpgridvanguard.hh
ebos/eclgenericvanguard.hh
opm/simulators/utils/SetupZoltanParams.cpp
opm/simulators/utils/SetupZoltanParams.hpp

modeled after the linsolver support. a few built-in presets, as well as reading options from a json file
Downstream of https://github.com/OPM/opm-grid/pull/586

added: command line option for zoltan customization

---

opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp

With the master branch, it uses the `wells_ecl` to determine whether wells are active, then SHUT wells might be counted. 
This is an effort to make this part cleaned up a little bit. 
`wellsActive()` or `localWellsActive()` are used many places, more testing and investigation will be required, so it is working in progress.

Fix wells active determination 

---

compareECLFiles.cmake
opm/simulators/linalg/FlowLinearSolverParameters.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/bda/BdaBridge.hpp
opm/simulators/linalg/bda/opencl/BISAI.cpp
opm/simulators/linalg/bda/opencl/openclSolverBackend.cpp
opm/simulators/linalg/bda/opencl/openclSolverBackend.hpp
opm/simulators/linalg/setupPropertyTree.cpp
opm/simulators/linalg/setupPropertyTree.hpp

Has been requested by many, so here it is. Also changes references to the option in comments. Not changing variable or member names.
The second commit removes the misleading dummy ISAI configuration option, but the ability to say `--linear-solver=isai` is kept for the benefit of the OpenCL code (we need to thing about how we want to make these things better integrated and simpler for the user).

Rename --linsolver option to --linear-solver

---

opm/simulators/linalg/FlowLinearSolverParameters.hpp

This is one of several PRs that will rename some command line parameters for greater consistency, as agreed with Atgeirr in #4096
Here we rename FlowLinearSolverVerbosity to LinearSolverVerbosity.

LinearSolverVerbosity

---

opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
opm/simulators/utils/UnsupportedFlowKeywords.cpp
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModelGeneric.cpp
opm/simulators/wells/BlackoilWellModelGeneric.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterfaceGeneric.hpp

If the network solution changes we may iterate the solution process, recalculating the well and network solution if a network solution for a group changes and either:
- the group has a well that is under thp control, or
- the group has a well that is not under thp control, but would break the new thp limit.
Not much tested yet, therefore a draft PR.

Add iterations to the network model

---

python/simulators/CMakeLists.txt

This seems to be a more stable approach as it does not produce
```
/usr/bin/python3.9: can't open file
'/home/mblatt/src/dune/opm-2.9/opm-common//install.py': [Errno 2] No such file or directory
```
for rebuilds after failed attempts.
Closes #4138

Use CMake's find_file to find install.py

---

opm/simulators/flow/NonlinearSolverEbos.hpp

This is one of several PRs that will rename some command line parameters for greater consistency, as agreed with Atgeirr in #4096
Here we rename FlowNewtonMinIterations to NewtonMinIterations

Rename option FlowNewtonMinIterations to NewtonMinIterations

---

CMakeLists.txt
ebos/eclequilinitializer.hh
flow/flow_ebos_gasoil.cpp
flow/flow_ebos_gasoildiffuse.cpp
flow/flow_ebos_gasoildiffuse.hpp
flow/flow_ebos_gaswater.cpp
flow/flow_ebos_oilwater.cpp
flow/flow_ebos_onephase.cpp
flow/flow_gasoildiffuse.cpp
opm/simulators/flow/Main.hpp

All other use cases still use the traditional linearizer.

Make the TPFA linearizer default for 1/2/3 phase blackoil.

---

ebos/eclproblem.hh

introduce a common function for looping over grid cells and updating something based on compressedDofIdx and the intensive quantities. do this by passing a std::function (ie lambdas).
update various functions having this structure to use the new common function. this to reduce code duplication. while at it const some more variables and reduce some long statements.

Refactor property updating in EclProblem

---

ebos/eclinterregflows.cc
opm/core/props/BlackoilPhases.cpp
opm/core/props/phaseUsageFromDeck.cpp
opm/core/props/satfunc/RelpermDiagnostics.cpp
opm/core/props/satfunc/RelpermDiagnostics.hpp
opm/simulators/flow/KeywordValidation.cpp
opm/simulators/flow/ValidationFunctions.cpp
opm/simulators/linalg/bda/FPGAUtils.cpp
opm/simulators/linalg/bda/Reorder.cpp
opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp
opm/simulators/utils/ParallelFileMerger.cpp
opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
opm/simulators/utils/UnsupportedFlowKeywords.cpp
opm/simulators/utils/moduleVersion.cpp
opm/simulators/wells/ALQState.cpp
opm/simulators/wells/GlobalWellInfo.cpp
opm/simulators/wells/GroupState.cpp
opm/simulators/wells/PerfData.cpp
opm/simulators/wells/SegmentState.cpp
opm/simulators/wells/WGState.cpp
opm/simulators/wells/WellProdIndexCalculator.cpp
tests/test_ALQState.cpp
tests/test_GroupState.cpp
tests/test_keyword_validator.cpp
tests/test_thresholdpressure.cpp

One should never include config.h in a header. To the very least it results in redefined macros.
Let's hope we don't rely on this elsewhere (have not tried compilation :grimacing: )

Move include of config.h to cpp-file

---

ebos/ecltracermodel.hh

As far as I can tell, there is no reason to update the whole element context here.
This yields a 10% reduction in the pre/post step for Norne on my machine.

Optimize EclTracerModel::updateStorageCache

---

opm/simulators/linalg/MILU.hpp

This removes a GCC warning message on higher warning levels.

Remove Trailing Semicolon on Function's Close Brace

---

opm/simulators/flow/FlowMainEbos.hpp

Requires https://github.com/OPM/opm-models/pull/735 to compile with non-diffusion-enabled TypeTags.

Hide all vtk parameters.

---

opm/simulators/utils/MPIPacker.cpp

Needed in upcoming work for communicating dynamic phase quantities per segment in a multisegmented well.

Add Serialization Support for std::bitset<3>

---

opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWellEval.hpp
opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/StandardWellEval.hpp
opm/simulators/wells/StandardWellGeneric.cpp
opm/simulators/wells/StandardWellGeneric.hpp

There is no reason to omit WellContributions if neither CUDA nor OpenCL is found as the implementations/functions only use C++- To the contrary, the defines used for deactivating were not consistent with usage elsewhere and resulted in compiler erorrs for exotic configuration

Fix compilation with amgcl/vexcl and without CUDA/OpenCL.

---

opm/simulators/wells/WellInterfaceGeneric.cpp

Note that the full switching history (i.e. pr iteration) is still reported to the debug file. 
The change was suggested by @OPMUSER

only output final change of well control

---

tests/test_blackoil_amg.cpp

Code that used these was recently removed.

Remove unused variables.

---

CMakeLists_files.cmake

Otherwise we get undefined references. Fixes problems introduced with #4157

[bugfix] Unconditionally compile WellContributions.cpp et al

---

opm/simulators/flow/BlackoilModelEbos.hpp

We are using the same tolerances for the MB and CNV for energy and the various mass balance equations. The motivation of this change is to make the energy tolerance more comparable with the ones for mass.

scale energy residual to have the same relative order as the mass balance residuals

---

CMakeLists_files.cmake

Downstream of https://github.com/OPM/opm-common/pull/3181

fixed: damaris depends on mpi

---

CMakeLists_files.cmake

According to https://cmake.org/cmake/help/latest/module/FindMPI.html the capitalized version is what we should use.
(Same as in opm-common.)

Use MPI_FOUND not MPI_Found.

---

opm/simulators/linalg/FlowLinearSolverParameters.hpp

I didn't realize `registerParameters()` works like that.
Fixes https://github.com/OPM/opm-simulators/issues/4202.
Still testing it.
@blattms

Removed default declaration in wrong place

---

opm/simulators/utils/UnsupportedFlowKeywords.cpp

Remove KRNUM from Unsupported Keyword List, as it is now supported. This should be back-ported, to prevent a warning stating the keyword is not supported.

Remove KRNUM from Unsupported Keyword List (Back-Port)

---

opm/simulators/flow/NonlinearSolverEbos.hpp
regressionTests.cmake

Now it is consistent with other options (e.g. NewtonMinIterations.
Needs OPM/opm-models#741

Rename option FlowNewtonMaxIterations to NewtonMaxIterations.

---

opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/StandardWellGeneric.cpp
opm/simulators/wells/StandardWellGeneric.hpp

no reason to pass a reference here, just use return

changed: use return value

---

opm/simulators/flow/FlowMainEbos.hpp

This change was missing from #4185.

Unhide NewtonMaxIterations.

---

opm/simulators/linalg/getQuasiImpesWeights.hpp

Make a normalization of the trueimpes weights. Maybe better exist but this fixes some issues.
It also highlight the need for the analytic weighs, which is in a seperate pullrequest

- made heuristic scaling of trueimpes

---

opm/simulators/wells/MultisegmentWell.hpp

It does not looks like used anywhere and it caused failed debug running by using it.

removing unused number_segments from MultisegmentWell

---

opm/simulators/utils/UnsupportedFlowKeywords.cpp

This PR relates to 
- https://github.com/OPM/opm-common/pull/3187
- https://github.com/OPM/opm-material/pull/538
- https://github.com/OPM/opm-models/pull/744

removed RWGSALT from unsupported keywords list

---

opm/simulators/wells/BlackoilWellModelConstraints.cpp
opm/simulators/wells/BlackoilWellModelGeneric.cpp

We want to keep the last group control for the terminal output i.e. use insert_or_assign instead of just insert.

fix group switch logging

---

opm/simulators/wells/WellState.cpp

With the addition of tracer information in the `data::Rates` object we must relax the assumption that the object is POD.  Switch to using the `Point2PointCommunicator` protocol for gathering connection solutions on the well's owner before transferring well solution objects to the I/O rank.
While here, also supply user-defined message tags in P2P exchange calls during `CollectToIORank::collect()`.  That way we're not dependent on class-level static data to create new tags for each message.
Closes OPM/opm-common#2921.

Support Variable Length Connection Data in Distributed Wells

---

opm/simulators/linalg/setupPropertyTree.cpp

Previously, passing --use-gmres=true had now effect. Probably was lost when introducing FlexibleSolver. With this change the FlexibleSolver will now use GMRes if the option is true.
Closes #4240

[bugfix] recover support for selecting GMRes as solver.

---

opm/simulators/linalg/FlowLinearSolverParameters.hpp

It is unused since 2018 when we moved away from autodiff implementation.
Marked for release but it is not pressing. But should not appear in the reference manual.
Closes #4241

Remove ununsed ancient LinearSolverRequireFullSparsityPattern option.

---

ebos/eclgenericoutputblackoilmodule.cc

A misprint led to erroneously reporting the gas viscosity here.
Reported by: [at]EdmundStephens on GitHub.
Resolves #4246.

Report Water Viscosity as WAT_VISC

---

doc/man1/flow.1

Done directly on the release as the parameters between master and release already diverged.
E.g. --opencl-ilu-parallel is master whereas --opencl-ilu-reorder is release.

Update flow manpage for release.

---

opm/simulators/wells/RateConverter.hpp

This commit adds a new overload of the `calcReservoirVoidageRates()` member function.  The new overload does not depend on the user calling `defineState()`, but instead takes state variables as direct input arguments.
Reimplement the state-dependent overload in terms of the new function.  The immediate use case is calculating additional dynamic quantities per segment in a multisegmented well model, mostly for reporting purposes.

Make Reservoir Voidage Rate Calculator Independent

---

opm/simulators/wells/MultisegmentWell_impl.hpp

Remove assert. Not sure why it maybe triggered.

removed assert in cprw for strictly positive diagonal well coupling

---

opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWellEval.hpp
opm/simulators/wells/RateConverter.hpp
opm/simulators/wells/SegmentState.cpp
opm/simulators/wells/SegmentState.hpp
opm/simulators/wells/WellState.cpp
opm/simulators/wells/WellState.hpp

In particular, report local condition segment flow velocities, segment holdup fractions, and segment phase viscosities.  To this end, expand the `SegmentState` to hold these additional quantities and update the values as part of [`updateWellStateFromPrimaryVariables()`](https://github.com/OPM/opm-simulators/blob/776180c08110d28790ff5cc783df2d19542ba3b9/opm/simulators/wells/MultisegmentWellEval.cpp#L1497).
We remark that the definition of the segment flow velocity is a little dubious and that we probably will have to revisit this definition (flow rate divided by cross-sectional area) at a later date.  Nevertheless, this PR is sufficiently ready to start testing segment-related RFT file output on more cases.

Convey More Dynamic State Values per Segment to Output Layer

---

opm/simulators/wells/StandardWell_impl.hpp

The well flux for injection perforations depends on the mobility in the cell. ie. we dont use the upstream value. this can lead to problems if the mobility depends strongly on temperature. The proposed change fixes the issue reported in #4244 
An alternative fix is to set the mobility of the injection perforation to Scalar but that will also affect non-isothermal cases. Initial testing indicates that this may have minor negative impact on convergence. Any comments?

remove derivative in thermal flux for injectors

---

opm/simulators/wells/MultisegmentWellEval.cpp

it might introduce inf/nan in the Jacobian matrix.
At the beginning, was thinking to return zero emulsionViscosity for small liquid_fraction, but zero viscosity is something weird. In the PR, basically, we make `liquid_fraction * emulsionViscosity` to be zero.  Maybe less strange. 
Please suggest.

not calculating emulsionViscosity for small liquid_fraction

---

opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/StandardWellGeneric.cpp
opm/simulators/wells/StandardWellGeneric.hpp

this to avoid ussage of BVectorWell in interface. in preparation for moving BVectorWell out of the well hierarchy.

changed: pass the actual update value to relaxationFactorRate

---

opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/WellInterfaceIndices.cpp

more readable.
since we now only instance for BlackoilDefaultIndexTraits, avoid repeating this.

simplify instantations

---

opm/simulators/wells/WellGroupHelpers.cpp

In WellGroupHelpers we unconditional referenced the region member of GPMaint. Unfortunately, that is a std:optional and doing this can create quite some havoc.
Now we stop processing if it is unset. Not sure whether this is what we want, though.
Drive-by fix. Unfortunately, not the issue that I am after.

[bugfix] Do not unconditionally dereference std::optional.

---

CMakeLists_files.cmake
opm/simulators/wells/BlackoilWellModel.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWellEquations.cpp
opm/simulators/wells/StandardWellEquations.hpp
opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/StandardWellEval.hpp
opm/simulators/wells/StandardWellGeneric.cpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellInterface.hpp

This is a container class for the equation system, as well as methods for applying to vectors.
- better code organization
- less instances. instead of one instance per index instance there is now one instance per block size (1..6).
This is part of a process to refactor the equation system and assembly of this from in standard well, as drafted in https://github.com/OPM/opm-simulators/pull/4238. All data members are still public, but this will be remedied later.
Sits on top of https://github.com/OPM/opm-simulators/pull/4237

added: StandardWellEquations

---

CMakeLists_files.cmake
opm/simulators/wells/StandardWellAssemble.cpp
opm/simulators/wells/StandardWellAssemble.hpp
opm/simulators/wells/StandardWellEquations.hpp
opm/simulators/wells/StandardWellEval.cpp
opm/simulators/wells/StandardWellEval.hpp
opm/simulators/wells/StandardWell_impl.hpp

This continues https://github.com/OPM/opm-simulators/pull/4268
Here we move assemble functions to a separate class, and make the equation system private in StandardWellEquations.
A friend declaration is used to allow the assembler (mutable) access to the matrices/vectors.

Added: StandardWellAssemble

---

opm/simulators/wells/StandardWellAssemble.cpp
opm/simulators/wells/StandardWellAssemble.hpp
opm/simulators/wells/StandardWell_impl.hpp

- pass primary variables as parameter
- use the evaluation type

StandardWellAssemble: simplify by using primary variables class

---

ebos/eclgenericthresholdpressure.cc
ebos/eclgenericthresholdpressure.hh
ebos/eclthresholdpressure.hh

To avoid deck usage in the simulators.
Downstream of https://github.com/OPM/opm-common/pull/3225

Use internalized THPRESFT

---

ebos/eclgenericproblem.cc
ebos/eclgenericvanguard.cc
ebos/eclgenericvanguard.hh
opm/simulators/flow/Main.hpp
opm/simulators/utils/readDeck.cpp
opm/simulators/utils/readDeck.hpp
python/simulators/PyBlackOilSimulator.cpp

No reason holding on to the deck during simulations, just a waste of memory. Let's remedy that
Sits on top of
https://github.com/OPM/opm-simulators/pull/4284
https://github.com/OPM/opm-simulators/pull/4285
And is downstream of 
https://github.com/OPM/opm-common/pull/3225

Remove Deck member from simulators

---

opm/simulators/utils/PartiallySupportedFlowKeywords.cpp

While there are a few arrays we admittedly don't create, the level of support is now sufficiently complete that declaring values other than `'NO'` as "supported" is warranted.

Promote Segment Data in WRFTPLT to Supported Status

---

opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWellEval.hpp

No real reason for this, other than wrongly categorized member functions.

MultisegmentWell: avoid mutable matrices/vectors

---

ebos/collecttoiorank.hh
ebos/eclwriter.hh
opm/simulators/utils/DamarisOutputModule.cpp
opm/simulators/utils/initDamarisXmlFile.cpp

This enables the damaris server to order data correctly in the HDF5 file. The necessary changes on the Damaris side are not yet merged there, but have been tested locally. In any case, the changes in this PR do not cause any trouble with the existing version of Damaris.

Write global cell index to damaris

---

tests/test_norne_pvt.cpp

Required by upstream https://github.com/OPM/opm-common/pull/3266 but can be processed before.

add missing include after upstream header removal

---

ebos/ecltransmissibility.cc

Previously, a barrier between cells in Z-direction was only honored if it was done using MULTZ. We disregarded MULTZ- completely when calculating the TRANZ over pinched cells.
Now we also take into account MULTZ-.
Please note that this PR will always does this and not only with this in the deck:
```
GRIDOPTS
'YES'		0 / 
```
Not 100% sure whether this is what we want.
This is to fix an issue with tests in OPM/opm-tests#872.
Needs OPM/opm-common#3272 to work as expected.

Honor MULTZ- when determining TRANSZ over pinched cells (pinch all)

---

CMakeLists_files.cmake
opm/simulators/flow/ConvergenceOutputConfiguration.cpp
opm/simulators/flow/ConvergenceOutputConfiguration.hpp
opm/simulators/flow/FlowMainEbos.hpp
opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
tests/test_convergenceoutputconfiguration.cpp

This PR introduces a new helper class,
```
ConvergenceOutputConfiguration
```
which parses comma separated option strings into a runtime configuration object for whether to output additional convergence information and, if so, what information to output.
Supported option string values are
* `"none"`&mdash;Dont want any additional convergence output.
* `"steps"`&mdash;Want additional convergence output pertaining to the converged solution at the end of each timestep.
* `"iteration"`&mdash;Want additional convergence output pertaining to each non-linar ieration in each timestep.
Option value `"none"` overrides all other options.  In other words, if the user requests `"none"`, then there will be no additional convergence output, even if there are other options in the option string.
We add a …

Don't Output INFOSTEP File by Default

---

opm/simulators/wells/MultisegmentWellGeneric.cpp
opm/simulators/wells/WellState.cpp

[bugfix] Throw for connections not attached to segments .
If there are connections of a multisegment well that are not connected to any segment, we throw with a meaningful error message instead of a silent segmentation fault. In that case an invalid segment index of zero will be returned. The corresponding storage index returned by segmentToNumberIndex becomes -1. This previously lead to segmentation faults when using it to index a container.
~There might be connections of a multisegment well that are not connected to any segment. In that case an invalid segment index of zero will be returned. The corresponding storage index returned by segmentToNumberIndex becomes -1. This will lead to segmentation faults when using it to index a container.~
~With this patch we check whether a connection …

[bugfix,mswells] Throw for connections not attached to segments correctly.

---

CMakeLists_files.cmake
opm/simulators/flow/BlackoilModelEbos.hpp
opm/simulators/flow/ExtraConvergenceOutputThread.cpp
opm/simulators/flow/ExtraConvergenceOutputThread.hpp
opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
tests/test_convergenceoutputconfiguration.cpp

This PR enables outputting non-linear convergence metrics, i.e., the MB and CNV values, per phase, for each non-linear iteration in each timestep.  If the user passes the option value `"iterations"` to the `--extra-convergence-output` command line option (PR #4322), this PR will create a new output file, `CASE.INFOITER`, that holds
* report step
* time step within that report step
* elapsed time
* MB and CNV values per phase
* well convergence status
for each non-linear iteration.
We use an asynchronous file writing procedure and confer ownership of the report step's unprocessed convergence reports to this procedure just before the end of
```
SimulatorFullyImplicitBlackoilEbos::runStep()
```
At that point, the convergence reports are about to go out of scope. The asynchronous protocol …

Output Non-Linear Convergence to Separate File if Requested

---

opm/simulators/utils/DeferredLoggingErrorHelpers.hpp
opm/simulators/wells/BlackoilWellModel_impl.hpp
opm/simulators/wells/GasLiftCommon.cpp
opm/simulators/wells/GasLiftCommon.hpp
opm/simulators/wells/GasLiftSingleWell.hpp
opm/simulators/wells/GasLiftSingleWell_impl.hpp
opm/simulators/wells/MultisegmentWellEval.cpp
opm/simulators/wells/MultisegmentWellSegments.cpp
opm/simulators/wells/MultisegmentWell_impl.hpp
opm/simulators/wells/StandardWell.hpp
opm/simulators/wells/StandardWellPrimaryVariables.cpp
opm/simulators/wells/StandardWell_impl.hpp
opm/simulators/wells/WellAssemble.cpp
opm/simulators/wells/WellConvergence.cpp
opm/simulators/wells/WellInterfaceGeneric.cpp
opm/simulators/wells/WellInterface_impl.hpp

Instead use {fmt} at callsites where available or simple string::operator+(..).
Waiting for #4292

Avoid use of sstream in deferred logger header / macros

---

opm/simulators/linalg/FlowLinearSolverParameters.hpp
opm/simulators/linalg/ISTLSolverEbos.hpp
opm/simulators/linalg/setupPropertyTree.cpp

Combining a number of minor adjustments for simpler and more consistent and robust use of the cpr options.
- Remove two unused parameters. CprEllSolvetype is never used, and CprEllMaxIter
is not used correctly as is (if used, it should change the maximum iterations of
the coarse solver, not the repeats of the preconditioner) and is better left for
JSON file customization.
- Make the default AMG setup for "cpr" (including "cpr_trueimpes" and "cpr_quasiimpes")
match the setup for "cprw". In particular, beta = 0.0 (not 1e-5) and
prolongationdamping = 1.0 (not 1.6).
- Just as we override the default maximum number of linear iterations for cpr and cprw
(unless the user actually specified on the command line) to 20 instead of 100, we
change the default reduction to be 0.005 instead of 0.01.
- …

Adjust cpr-related defaults
