OPM/opm-simulators

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
Shut is renamed to stopped in the wellsManager in order to better
reflect the name logic in the deck. This PR implements the nessesary
change in opm-autodiff
This PR depends on OPM/opm-core#709
> Account for the renaming in the wellsManager

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
A temporary copy is added to avoid inclusion of dissolved gas when the
vaporized oil contribution is added in the accumulation term for the oil
phase.
This PR adress the issue raised by @bska in #267.
> BUGFIX: Avoid inclusion of disgas in the vapoil contribution

- tests/test_transmissibilitymultipliers.cpp
Previously, there were a completely different check for `UnstructuredGrid` and `CpGrid`. The latter probably not working properly due to missing support in the DUNE grid interface.
This commit resorts the code to use the `UgGridHelpers` abstraction instead of `UnstructuredGrid`'s legacy grid interface. Thus one code can be used to do the checks for both grids. For UG the code compiles and the test is successful. For `CpGrid` it compiles but of course the test still fails due to missing
transmissibility multiplier support. Therefore it is still deactivated.
This PR does not rely on any other one.
Once this and #272 is merged I will create a PR that makes calculation of transmissibilities possible for `CpGrid`.
> Ports transmissibilities test to grid helpers

- opm/autodiff/GridHelpers.cpp
- opm/autodiff/GridHelpers.hpp
It uses the iterator over the cell faces to identify the face tag in constant time. As CpGrid also needs the cell index we add it to the face cell iterator.
This is similar to pull request OPM/opm-core#720 and adds the funtionality for CpGrid. It needs OPM/dune-cornerpoint#121.
It supersedes #271 which will be closed.
> Adds free function to access the face tag to UgGridHelpers.

- opm/autodiff/GeoProps.hpp
- opm/autodiff/GridHelpers.hpp
- tests/test_transmissibilitymultipliers.cpp
With this PR it is finally possible to use CpGrid for calculating the transmissibilities. Therefore now the test of the transmissibilities is actived without any warnings. Of course the test is successful
> Implement generic transmissibilities computations using the GridHelpers

- opm/autodiff/BlackoilPropsAd.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/BlackoilPropsAdInterface.hpp
- opm/autodiff/FullyImplicitBlackoilSolver.hpp
The initial definition of the phase indices seems to be in
opm/core/props/BlackoilPhases.hpp. Nevertheless there were
several redefinitions of the same or similar enums (either
Aqua, Liquid, and Vapor, or Water, Oil, and Gas). Surprisingly
most often these definitions did not use the original values.
This is bound to break if there is a change upstream.
This patch limits the definition to one place in opm-autodiff,
namely opm/autodiff/BlackoilPropsAdInterface.hpp. To avoid
downstream confusion we define both the Water and Aqua triplets.
In addition we define the maximum number of phases to use at compile
time.
> Unifies the phase indices with the ones in opm-core.

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
This PR fixes all places where the code was not acknowledging that the wells pointer could be zero when no wells were specified in the deck. The results for SPE9 are identical. From that I deduct that also Norne still runs ;-). I would appreciate  if somebody could take a look at this.
> Allow sim_fibo_ad to run without wells.

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This PR fixes the gcc 4.4 issue. I have stopped using gcc 4.4 around 2010. So these things will occur in the future.
> remove template keyword.

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This PR introduces a small change that throws an Opm::NumericalProblem exception when one of the residuals is either NaN or to large. The tolerance for "to large" is numeric_limits<double>::max() by default but can by user specified.
> Restart solver when residual is nan or to large.

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- Failed to set all rates to zero initially. Used by stopped wells.
- Could set out-of-bounds index if number of controls changed.
> Fix issues in WellStateFullyImplicitBlackoil::init().

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
It took me quite some time to understand the computations done
e.g. during the detection of oscillations, where the stuff returned
by residuals() is used as a vector of doubles. It turns out that
residuals() actually returns the norm of the residuals. To clarify this
we rename residuals() to computeResidualNorms() and residuals to
residual_norms. Having my dare devil day today, I even try to document the
method. (This documented method might feel kind of lonely between the others,
now;). Hopefully this saves others some time.
> Renames residuals() to computeResidualNorms()

- opm/autodiff/GeoProps.hpp
The results of this PR is showed in https://github.com/OPM/opm-core/pull/734#issuecomment-71953906 .
*Note*: this PR doesn't change the results of full NORNE case, maybe even improve it a little bit, the full test hasn't been done.
> Use original grid cell volume to compute pore volume.

- opm/autodiff/AutoDiffBlock.hpp
Apparently Eigen cannot handle empty containers during reserve correctly.
Therfore we check for the size of the vector and if it is zero simply create
empty jacobians.
Closes #290
> Fixes raisal of assertion in Eigen because of empty vector and matrices. Fixes #290

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
The convergence check needs to compute quite some global reductions. Unfortunately, the current code successfully hides this behind the Eigen functions called. This commit partly refactors the code such that the reductions in getConvergence appear in one place. Thus we will be able to use one reduction to compute them. This preliminary to the parallelization; it will be based on this commit. Nevertheless I felt the need to create a PR now, because several people seem to be working on this part of the code. Note that the current behaviour is not changed by this code.
> Restructure newton convergence for parallelization

- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
The bhp limit for RESV controlled wells in historical mode should be 1 atm. 
TODO: Allow WELTARG to change this bhp limit. 
Tested on norne.
> Hardcode bhp limit for WCONHIST/RESV to 1 atm.

- examples/sim_fibo_ad.cpp
- examples/sim_fibo_ad_cp.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoil.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
The output for FullySimulatorOilBlackImplicit  class has been reorganized by implementing a class fulfilling the OutputWriter interface. This revision is necessary for upcoming implementation of backup/restore and parallel output features.
> Revision of black oil output by putting everything into a single class following the OutputWriter IF.

- dune.module
It caused dunecontrol to abort because of using a comma as a separator.
This commit removes the erroneous comma and adds a required version.
I apologize for the lack of testing the previous PR.
> [bugfix] Fixes dependency clause of #296

- CMakeLists_files.cmake
- opm/autodiff/BackupRestore.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
This first implementation is mainly to support faster debugging. When the parameter backupfile (providing a filname for a backup file) is given, then the solution and wellstate at the report steps is stores for later restart at any of the written report steps. This PR depends on PRs opm-core #737  and opm-autodiff #285.
Upon start of the simulation if the parameter restorefile is provided the solution and wellstate from that file is read and the timer is advanced. Once the desired reportstep is read, simulation is continued.
> BlackoilOutputWriter: added support for backup and restore.

- opm/autodiff/GeoProps.hpp
PR https://github.com/OPM/opm-parser/pull/416 and https://github.com/OPM/opm-core/pull/750 should go first,
Note: the default behavior is to get the "same" PV as ECLIPSE,  only if the user set MINPVF in the deck, the total PV will be different with ECLIPSE within an acceptable tolerance.
> support MINPVF.

- CMakeLists_files.cmake
- examples/sim_fibo_ad_cp.cpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/ExtractParallelGridInformationToISTL.cpp
- opm/autodiff/ExtractParallelGridInformationToISTL.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
- opm/autodiff/NewtonIterationBlackoilInterface.hpp
- opm/autodiff/NewtonIterationBlackoilSimple.cpp
- opm/autodiff/NewtonIterationBlackoilSimple.hpp
With this PR this PR it is possible to detect whether a parallel CPGrid is used by the simulator. In that case
we extract the information from the grid and pass to the parallel dune-istl solvers.
Note that for the other cases (sequential run or no procs ==1) the simulator should do exactly the same as before.
Note further that real parallel runs are still not possible as we have to distributed the data first (that is all the properties stuff). I will attack this week and post another PR for it.
> Adds parallel solver support for sim_fibo_ad_cp

- opm/autodiff/NewtonIterationBlackoilCPR.hpp
- opm/autodiff/NewtonIterationBlackoilSimple.hpp
This an alternative to PR #303
During the constructor the underlying object only holds smart
pointers and an empty vector. The FullyImplicitBlackoilSolver
obtains  a reference to it from the NewtInterationInterface instances.
Therefore copying boost::any and storing it by value should be cheap
and safe.
> Store the boost::any of ParallelIstlInformation by value. (Alternative to #303)

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This quirk is required to build in Statoil (gcc44?)
> The stream::open() functions require c_str()

- CMakeLists_files.cmake
- examples/sim_fibo_ad_cp.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
- opm/autodiff/RedistributeDataHandles.hpp
- tests/test_boprops_ad.cpp
With this PR we add the possibility to start with a global representation
of a simulator that is read on each process and afterwards this presentation
is redistributed among the processors together with the properties and
state data needed to initialize the simulation.
There still is no parallel well handling and no parallel output. But with the
equilibrium example of @dr-robertk and deactivated output we can already
perform parallel runs.
We still need two levels of overlap cells to get correct results.
> Adds data redistribution capabilities and makes sim_fibo_ad_cp parallel.

- examples/sim_fibo_ad.cpp
- examples/sim_fibo_ad_cp.cpp
The signature of the opm-core thresholdPressures(...) method is changed  - changed parameter list in call to thresholdPressures in sim_fibo_ad.cpp
> opm-166: Fix due to signature change in method thresholdPressures

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This removes some false-positive unused function warnings (functions that were in the anonymous namespace and only used from templates), as well as removing an actually unused function that was not warned about (because it was a template).
> Fix warnings

- examples/sim_fibo_ad_cp.cpp
- opm/autodiff/RedistributeDataHandles.hpp
Previously BlackoilPropsDataHandle did hold a grid for sending
and receiving that were either not used or we could prevent their
usage. Therefore this commit removes them from the class and queries
all needed information from the property objects.
> Remove the unsused grid members from BlackoilPropsDataHandle.

- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
The existing implementation computed limit targets for RESV for PRODUCER wells. For INJECTOR wells, the limit modification necessary was ignored, resulting in wrong behaviour (more correct would have been to refuse accepting RESV for injectors).
This fixes #307.
> Implement RESV limit targets for INJECTOR wells.

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
The average well block pressure is used instead of the well cell
pressure when the well properties are evaluated.
Temperature, rs, rv, phase conditions are still well cells values.
Perforation pressures are stored in the well state
> Use the average well block pressure when evaluating the properties

- examples/sim_fibo_ad_cp.cpp
- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
Before this PR each rank would print status about the simulation to the terminal. This duplicate information did clutter the screen quite a bit. Now only rank 0 is responsible for the output.
> Print status output only on rank 0 for parallel runs.

- examples/sim_fibo_ad_cp.cpp
- opm/autodiff/GridHelpers.cpp
- opm/autodiff/GridHelpers.hpp
With now generic implementation of the initStateEquil in opm-core
we added the necessary grid helper functionlality for CpGrid and activated
the processing if the EQUIL keyword is there.
This PR is based on OPM/opm-core#761
> Modified sim_fibo_ad_cp to also allow running with EQUIL keyword.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/RedistributeDataHandles.hpp
- tests/fluid.data
- tests/test_rateconverter.cpp
This PR is based on #318 and therefore at the moment it is hard to tell apart the additional content in this, I may rebase it if #318 is merged to improve readability.
It contains two basic fixes:
- The `pvtTableIdx_` member is removed from `BlackoilPropsAdFromDeck`, and a bug fixed (initialisation of `cellPvtRegionIdx_`, the `pvtTableIdx_` received the data instead).
- Make the `test_rateconverter` test succeed again.
Edit: I forgot to list the most important fix in this PR:
- Fix pvt region behaviour. The existing code did not pass an array of regions (with the same size as the requested number of data points) to underlying classes, but the array of cell's region indices.
> Fix pvt regions

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
Probably appeared due to copy-and-paste, will merge immediately.
> Remove unused variable.

- opm/autodiff/RedistributeDataHandles.hpp
During BlackoilStateDataHandle::gather we did read values from the
state where we should only receive values to. With this commit we
read from the state where we should send values.
Kudos to Bard for noticing this.
> [bugfix] read only from the sendState in BlackoilStateDataHandle.

- opm/autodiff/GeoProps.hpp
- opm/autodiff/GridHelpers.cpp
- opm/autodiff/GridHelpers.hpp
This PR moves all the grid helper functions that do not depend on Eigen to the module where the grid is declared and implement.
This is the first out of three PRs that should be merged simultaneously. The first and second one are OPM/opm-core#764 and OPM/dune-cornerpoint#130.
As a result we only have one `faceCentroid(int)` function the returns `const double*` and `FieldVector<double,3>` for `UnstructuredGrid` and `CpGrid`, respectively. The code is adapted to this.
> Moves functions that do not depend on Eigen to Opm::UgGridHelpers. [3/3]

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
This PR implements the output of Newton and Linear Solver iterations at the end of a simulation (flow).
Also:
1) A parameter tolerance_wells has been added to make the tolerance user adjustable. 
2) terminal output can now be disabled by setting output_terminal to false
As usual, default behaviour is the same as before.
> Output Newton and Lienar solver iterations

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/BlackoilPropsAdInterface.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/ImpesTPFAAD.cpp
- opm/autodiff/RateConverter.hpp
- tests/test_boprops_ad.cpp
This PR simplifies the viscosity and formation volume factor interfaces: only a single function for each phase remains, the one that takes AD objects. This results in a massive reduction of copy-and-pasted almost-identical functions, making it much easier to get a grip on the property classes and their interface.
The downsides are:
- Potential for a slight performance degradation in places where no derivatives are needed, see the commit message of fbf06c0, If a problem, this can be handled by making the `bOil()`, `muGas()` etc. functions explicitly use a simpler treatment for input with no derivatives, this has so far only been done in `BlackoilPropsAdFromDeck::muWat()`.
- Slight increase in code complexity in those same few places. One way to deal with this is to make convenience …
> Simplify properties

- opm/autodiff/RateConverter.hpp
Avoid storing return value in reference.
Normally this is OK for by-value returns, but here the right hand side was changed to call ADB::value(), which returns by reference.
This should fix the test failures that reported in #327.
> Fix for test failures after #327.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/BlackoilPropsAdInterface.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/ImpesTPFAAD.cpp
- opm/autodiff/ImpesTPFAAD.hpp
- opm/autodiff/RateConverter.hpp
With this, the `rsSat`, `rvSat` and `relperm()` overloaded methods are reduced to a single function.
> Further simplify properties

- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
This PR depends on OPM/opm-core#769 (opm-core). Here, the fix is to also write the first and last step when using adaptive substepping. The Writer internally keeps track of the `reportSteps` and only writes these once. I checked the result with
> SimFullyImplBO: write simulation state at all report step and in the end.

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This refactors some parts of the simulator to reduce the re-calculation of capillary and phase pressures. The changes are relatively minor. On my system, this yields a runtime reduction of approximately 5-10%.
There is still a little more to be gained, but it would require a somewhat larger change to the simulator structure than the current PR.
I also fixed a few whitespace issues nearby the changes I made. Add ?w=1 in the URL to review without whitespace changes.
> Reduce recalculation of phase pressures

- examples/sim_simple.cpp
- opm/autodiff/AutoDiffBlock.hpp
- opm/autodiff/AutoDiffHelpers.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/ImpesTPFAAD.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/TransportSolverTwophaseAd.cpp
- tests/test_block.cpp
This makes the `AutoDiffBlock::function()` take only rvalue reference arguments, in order to avoid copying. Consequently, this PR also adds the use of `std::move` in many places, to adapt to it.
Some other modifications (using `swap()`, moves and references) are also made to reduce copying overhead. This has been tested to reduce runtime around 5-10%, performance results may vary but should be universally better than before.
One could argue that we should keep a backward-compatible `function()` overload. I have chosen not to, to force the issue and ensure that an inefficient version is not used.
> Use move semantics to gain performance

- CMakeLists_files.cmake
- opm/autodiff/AutoDiffHelpers.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- tests/test_autodiffhelpers.cpp
The existing implementation of vertcat() is extremely inefficient, and its use is always followed by collapseJacs() to merge all Jacobians into a single matrix. The new function combines these operations and also apply them straightaway to a vector of AutoDiffBlock objects (instead of just two at a time).
Performance gain for me is approx. 5%. Tested to give same results as before on SPE9.
> Add new vertcatCollapseJacs() helper and use it

- examples/flow.cpp
- examples/flow_cp.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
this PR adapts to the EclipseWriter API change of OPM/opm-core#772 and must thus be merged synchronously.
> also pass the deck to the output writer

- examples/flow.cpp
- examples/flow_cp.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This reverts commit 88730e855f6e24bd08fccbb10df5cd1be425b435.
it is now required for OPM/opm-core#776
> Revert "also pass the deck to the output writer"

- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
This PR adds more parameters to steer the Newton and linear solvers. 
* `FullyImplicitBlackOil`: added min newton iteration, needed for Norne
* `NewtonIterationBlackoilCPR`: allow to use BiCG and adapt to parameter changes in CPR
* CPR: added tolerances as parameters and changed parameters for AMG.
Tested with SPE9 and Norne (see opm-data).
> More parameter for solvers.

- examples/flow_cp.cpp
After this, flow_cp can run standard tests such as SPE9 on a serial configuration.
> Bugfix: distribute only if comm size is strictly > 1.

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This minor output error has been there for a long time.
> Fix convergence table labels (water, oil swapped).

- opm/autodiff/GeoProps.hpp
This fixes a bug introduced by PR 335.
> Use generic function instead of UnstructuredGrid interface.

- opm/autodiff/BackupRestore.hpp
> fixed: use size_t and not unsigned long

- examples/flow.cpp
- examples/flow_cp.cpp
Any argument that is not handled by the parameter parser will be assumed to be a deck filename. Only one is accepted, and if given, it will override any deck_filename=<something> on the command line or in parameter files.
Note: the parameter parser handles arguments of the following types:
`key=value` (note no space around `=` or in the strings)
`parameterfile.xml`
`parameterfile.param`
So an argument like DECK.DATA will be treated as a deck filename.
This requires OPM/opm-core#786.
> Accept single deck filename as command line argument.

- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/ImpesTPFAAD.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilSimple.cpp
- opm/autodiff/TransportSolverTwophaseAd.cpp
Consequently throw LinearSolverException when the linear solver was not converged. 
Since LinearSolverProblem is derived from std::runtime_error everything should work as
before.
> std::runtime_error --> LinearSolverProblem. 

- examples/flow.cpp
- examples/flow_cp.cpp
This requires OPM/opm-core#789.
I intend to put this in the release branch as well.
> Use more appropriate end-of-sim timing output.

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This small change is necessary to make SPE3 run without adaptive time stepping for comparisons with ECL. The results of the other test cases are not changed and run times stay the same.
This should also be merged into the release branch.
> FullyImplicitBlockOil: increase max_allowed_residual to 1e7.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
This PR fixes the restore of data when last report step that was written is selected. 
If still possible, this could go into the release.
> BlackoilOutputWriter: fix restore when last step is selected.

- opm/autodiff/CPRPreconditioner.hpp
Previously only passed the parallel information to the ILU preconditioner,
but of course needs this information to set up the communication, too.
With this commit we pass the parallel information object to AMG's constructor.
> [bugfix] Pass parallel information to AMG preconditioner within CPR.

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This PR contains a fix in the wellbore mixture calculations. With this fix, oscillations in the results seen for instance in the BHP in well C-4H in the norne model disappear. The second commit that sets the target values as initial conditions is necessary for the fix to handle large changes in well controlls. For instance events where gas injectors becomes water injectors. The last commit is necessary in order to run spe3 using default parameters. 
Tested on the SPEs and norne. 
The run time on Norne is increased approx 10% due to convergence issues on a few critical time steps.
> Modify welleq

- examples/flow.cpp
The "standard terminal" in windows/ubuntu is typically 80 columns wide. This PR reformats the header of flow so that it has no extra linebreaks in such a standard terminal. 
The output during simulation, however, remains unformated at ~90 columns wide.
> Reformated flow header to fit 80 columns

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
The well residuals are scaled with the volume factor before convergence is checked to avoid too large weight on the gas phase. The default tolerance is changed such that the overall run time is less than 10% more than before, while still improving the results for some critical wells.
> Check scaled well residuals for convergence

- examples/flow.cpp
- examples/flow_cp.cpp
This addresses issue #372, in which an exception thrown from main() ends up in a core dump. Simply changes throws in main() to return EXIT_FAILURE.
> Changed throw in main() to return EXIT_FAILURE

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
This method seems to be some leftover from refactoring.
In flow we now use computeResidualNorms() instead and
residualNorm() is not used anywhere. Therefore this commit
removes it to prevent confusion.
> Removes unused residualNorm method.

- examples/flow_cp.cpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/RedistributeDataHandles.hpp
During recent tests I experienced some convergence issues when running in parallel, Some of them are already handled in PR OPM/dune-cornerpoint#142. The rest of them is now handled here in this PR.
Now we get comparable convergence for the equilibrium (SPE1 without wells) test case together with a nice speedup. Due to the smaller problem size per process in the parallel runs, the parallel runs the speedup in the assembly is superlinear. This most probably due to better cache reuse (in Eigen?) and will not carry over to the larger cases.
Nevertheless we get a nearly linear speedup for CPR/ILU for small number of processes.
> Fixes convergence issues with the parallel CPR

- examples/flow_cp.cpp
- opm/autodiff/CPRPreconditioner.hpp
Previously, each process did print its own statistics to std::cout. This result in the same ouput printed multiple (the number of processes) times.
Together with and based upon PR OPM/opm-core#800 this PR drastically decreases the noise. Now only the process with rank equal to zero will print to standard out.
Note: PR OPM/opm-core#800 needs to be merged before this one.
> Prevent printing stats on more than 1 process for CPR.

- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
- opm/autodiff/RedistributeDataHandles.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
This PR fixes a bunch of problems during parallel runs. Among them
- Correctly compute the infinity norm in parallel.
- Setup the parallel communication information for the whole system and use where necessary, i.e.
the ILU preconditioner and for matrix vector products of the whole system.
- Port @totto82 changes in PR #375  to the parallel use case.
Note: Currently this is only tested with SPE1 and the equilibrium case (i.e. SPE1 without wells) and constant time stepping. For these cases it seems to produce reasonable results. The more advanced time stepping schemes are still broken as we need to modify OPM/opm-core for it. I will do this in the following days.
This PR require OPM/opm-core#803 to be merged first.
> Fix parallel communication  for whole system

- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
It does this simply by passing the information about the parallelization to the adaptive time stepper.
This PR is based upon OPM/opm-core#805 which needs to be merged before this one.
> Activates the parallelism in the adaptive time stepping schemes.

- CMakeLists_files.cmake
This restores `make install` in opm-autodiff.
> Record New and Renamed Files

- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
After the recent refactoring, solver and model parameter objects are created every timestep, creating lots of unneeded output. With this, they will only be created once.
> Create solver and model parameters only once.

- examples/flow.cpp
- examples/flow_cp.cpp
With the new opm-parser `IOConfig` object (retrievable from `EclipseState`), output interval of restart files are now governed from the deck by the keywords RPTSCHED and RPTRST. 
Before this was implemented the output interval (`N`) could be set from command line param. 
This PR reintroduces this functionality, implemented by calling a new "override" method in `IOConfig`. 
Setting `N=0` means no write of restart files at all.
This PR depends on PR OPM/opm-parser#495 being merged first.
> OPM-212: Added parameter override of IOConfig Restart write setting

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
Also:
- call using asImpl(),
- remove extraAddWellEq().
This change is done to facilitate using the new solve-well-equations feature recently merged with downstream variants such as flow_polymer.
> Add more parameters to addWellContributionToMassBalanceEq.

- CMakeLists_files.cmake
- examples/flow.cpp
- examples/flow_cp.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/NewtonIterationUtilities.cpp
- opm/autodiff/NewtonIterationUtilities.hpp
This adds a new option to flow (and flow_cp), `use_interleaved`. When set to true, the CPR preconditioner is not used. Instead, we structure the matrix in an interleaved fashion, ordering all equations and variables associated with a cell together, so it becomes a sparse block matrix with 3x3 blocks (three phases only for now). Then we do an ILU0-preconditioned solve of the system.
On SPE9 speed is a little better than with the CPR preconditioner (less than 10% improvement). While I had hoped for more, there is some overhead (for example building the interleaved block matrix), that hopefully could be reduced. On Norne, I have not run through the whole case, just a few minutes, and while it seemed a little faster per iteration, it ran into convergence issues more quickly, cutting the …
> Add new linear solver approach: block-structured matrix.

- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
Botched due to case-insensitive file system.
> Fix case in include statement.

- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
Another fix for bugs in the earlier merged PR. This time due to lack of testing on system without MPI.
> Move parallel overload into HAVE_MPI block.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
Note: do not merge until a companion PR in opm-polymer is ready.
The method has been split in three parts:
```
computeWellFlux(const SolutionState& state,
const std::vector<ADB>& mob_perfcells,
const std::vector<ADB>& b_perfcells,
V& aliveWells,
std::vector<ADB>& cq_s);
void
updatePerfPhaseRatesAndPressures(const std::vector<ADB>& cq_s,
const SolutionState& state,
WellState& xw);
void
addWellFluxEq(const std::vector<ADB>& cq_s,
const SolutionState& state);
```
This reduces the function length, although most of the content of addWellEq() now is in computeWellFlux(), so that function is still quite long. It also allows us to use smaller sets of function arguments, which makes methods easier to understand.
Finally, it makes it easier to create derived models with custom behaviour.
> Refactor addWellEq().

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
Eliminating a redundant recalculation and changing the order of some operations yields a small performance benefit (on the order of perhaps 3% on SPE9).
Some of the private fluid methods of the class have got simplified interfaces, especially fluidDensity() which now receives the b factor as an argument instead of recalculating it.
Tested on SPE9 and a few steps of Norne (not a full run).
> Performance enhancements and simplifications for BlackoilModelBase

- examples/flow.cpp
- opm/autodiff/GeoProps.hpp
This PR fixes the issue with the use_local_perm flag in flow when used with CpGrid. 
The real problem, that the normals in CpGrid and UnstructuredGrid are scaled differently, remains.
> Fix use of local perm for flow_cp.

- opm/autodiff/RedistributeDataHandles.hpp
With this, opm-autodiff compiles with no warnings for me.
> Avoid unused argument warning.

- opm/autodiff/GridHelpers.hpp
This PR addes a specialization for PolyhedralGrid to make flow compile when used with PolyhedralGrid. 
To use PolyhedralGrid, in flow.cpp replace 
typedef UnstructuredGrid  Grid;
GridManager gridManager( eclipseState->getEclipseGrid(), porv );
const Grid& grid = *(gridManager.c_grid());
by 
typedef Dune::PolyhedralGrid< 3 , 3 > Grid;
Grid grid( deck, porv );
> GridHelpers: added specialization for PolyhedralGrid.

- opm/autodiff/AutoDiffHelpers.hpp
This fixes a bug that would cause a null pointer reference whenever HelperOps was constructed without an EclipseState argument.
Also simplify a trinary conditional.
> Fix nnc treatment

- opm/autodiff/AutoDiffHelpers.hpp
This caused Eigen assert() failures in debug mode when running without NNCs (which apply to all current test cases).
Will self-merge as it is a trivial-yet-critical fix.
> Fixed Eigen array dimensions must be respected in resize().

- examples/flow.cpp
I think this is a serious bug for the parallel case, could you please check, @blattms?
> Pass parallel info to NewtonIteration... classes.

- opm/autodiff/AutoDiffHelpers.hpp
For g++-4.4 support for nullptr is not complete. Using it
to initialize an empty shared_ptr breaks compilation:
```
/home/mblatt/src/dune/opm/opm-autodiff/opm/autodiff/AutoDiffHelpers.hpp: In constructor ‘Opm::HelperOps::HelperOps(const Grid&, Opm::EclipseStateConstPtr)’:
/home/mblatt/src/dune/opm/opm-autodiff/opm/autodiff/AutoDiffHelpers.hpp:87: error: no match for ternary ‘operator?:’ in ‘(bool)eclState ? eclState->.Opm::EclipseState::getNNC() : nullptr’
/home/mblatt/src/dune/opm/opm-autodiff/opm/autodiff/AutoDiffHelpers.hpp:87: note: candidates are: operator?:(bool, const Opm::NNC* std::__shared_ptr<const Opm::NNC, (__gnu_cxx::_Lock_policy)2u>::*, const Opm::NNC* std::__shared_ptr<const Opm::NNC, (__gnu_cxx::_Lock_policy)2u>::*) <built-in> …
```
> Prevents initializing std::shared_ptr from nullptr to suit gcc-4.4

- opm/autodiff/DuneMatrix.hpp
This issue has been resolved in dune-istl 2.4 and we can remove it for the newer dune versions. 
For dune versions < 2.4 we have to keep it around.
> DuneMatrix: remove hackery of defining private as protected.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- tests/test_boprops_ad.cpp
Fixing the usual suspects: unused arguments and boost includes.
> Silence warnings.

- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
It avoids the using of `formEllipticSystem()` and `vercatCollapseJacs()`, which take a significant amount of computing time during the non-linear solutions.
The performance tests are conducted with the single option `use_interleaved=true` and all the other options defaulted. 
Testing with SPE9 indicates more than 10% performance enhancement. Testing with Norne only shows about 7% performance enhancement. It should also be a little more than 10% according to the profiling analysis. (My computer is showing some performance instability, which I am looking for causes. Different running with same parameters can show different performance (can be more than 10% different).)
To run through with Norne with `use_interleaved=true`, PR OPM/opm-core#851 is required. 
This PR is done with @atgeirr …
> optimizing the formInterleavedSystem().

- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
It appears I misunderstood the return type of the ScalarProductChooser, it happens to be a regular pointer that must be put in a smart pointer manually.
> Fix minor memory leak

- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent_impl.hpp
The function in question could just as well lose the argument, but that would require a minor rewrite in opm-polymer as well.
> Silence unused argument warning.

- opm/autodiff/RedistributeDataHandles.hpp
Previously, we tried to make an empty container bigger by
resizing it with its current size. Of course this is wrong and does
not change anything. With this commit we use the size of another
container which already has the correct size.
> Fixes parallel sat oilmax size

- opm/autodiff/BackupRestore.hpp
```
stream.read( (char *) container.data(), dataSize );
```
for container=std::string is illegal, as we are not allowed to modify data(). Changed by reading into a temporary first, and then constructing the string. Should not have any side effects.
> Fix bug reading directly into data owned by std::string

- CMakeLists_files.cmake
- examples/flow.cpp
- examples/flow_solvent.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/createGlobalCellArray.hpp
this is required for OPM/opm-core#834
the problem is that function overloads are only seen by code which is defined after the overload has been declared. To make `Opm::Evaluation` work correctly in conjunction with `Dune::FieldMatrix`, the
`Dune::absreal()` function must be overloaded, so the `Evaluation.hpp` header file must be included _before_ `densematrix.hh`.
A cleaner way to get around this problem is to make `Dune::absreal()` a function template and specialize it. The problem is that (a) this requires to get a patch accepted in Dune and (b) (more relevantly) the
earliest release which will include the new version of this file will be the Dune 3.0 (which is possibly going to be 2.5 judging from previous experience). Since this is most likely probably be > 1.5 years away, it is a …
> add a few missing "#include <Evaluation.hpp>"

- opm/autodiff/SimulatorBase_impl.hpp
Explicitly adds bhp control on rate controlled history matching injector. The default bhp limit is a large number to make sure that the well does not switch. Alternatively bhp limit can be specified using
`WELTARG`. This is typically done to make sure the bhp limit stays within the pressure limits in the PVT tables. Support for `WELTARG` is also added to the history matching producers (`WCONHIST`) 
Tested to make sure that it does not effect the SPEs and norne.
> Add support for WCONINJH

- opm/autodiff/RedistributeDataHandles.hpp
With this commit we pass the well information to
the loadbalance method of CpGrid to ensure that
each well is stored completely on one process.
This is a follow up to PR OPM/dune-cornerpoint#163 that is used now for flow_cp
> Use well information during load balancing.

- examples/flow.cpp
- examples/flow_solvent.cpp
- opm/autodiff/BlackoilModelParameters.cpp
Use the more stable interleaved solver instead of CPR as default
Solve well equation initially as default
Most of the testing lately has been done with the interleaved solver and solve_welleq_initially_  =true. It gives significant speed up for norne and some for the SPEs
> Change defaults

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
If this option was set there were some branches in
the code that did depend on the local number of wells
but should depend on the number of wells in the reservoir
no matter on which process they are stored.
With this commit we introduce BlackOilModelBase::localWellsActive()
which only takes local wells into account. The function now
BlackOilModelBase::wellsActive() considers all active wells in the
reservoir.
> Fixes parallel runs with solve_welleq_initially

- CMakeLists_files.cmake
- opm/autodiff/CPRPreconditioner.hpp
The include of ParallelRestrictedAdditiveSchwarz.hh was a left over
from some experiments and should not be here yet.
> Removes unused experimental header include to fix build.

- CMakeLists_files.cmake
- examples/sim_simple.cpp
- opm/autodiff/AutoDiffBlock.hpp
- opm/autodiff/AutoDiffHelpers.hpp
- opm/autodiff/AutoDiffMatrix.hpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/ImpesTPFAAD.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilSimple.cpp
- opm/autodiff/NewtonIterationUtilities.cpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/autodiff/TransportSolverTwophaseAd.cpp
- opm/autodiff/VFPInjProperties.cpp
- opm/autodiff/VFPProdProperties.cpp
- opm/autodiff/fastSparseProduct.hpp
- tests/test_autodiffhelpers.cpp
- tests/test_autodiffmatrix.cpp
- tests/test_block.cpp
This significantly improves performance of flow by keeping track of matrix types. The gist of it is that if a is zero, identity or a purely diagonal matrix, we can use specialized multiplication/addition/etc. methods that are faster than a general sparse (op) sparse method.
Tested that it gives same result as master.
> Autodiff matrix types

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/LinearisedBlackoilResidual.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
Updating the scaling factors based on average formation volume factors during each time step instead of the hard-coded scaling factors. 
The hard-coded scaling factors are based on SPE9, while it has been working surprisingly well. 
The performance tests are little not stable though, which is still dominated by the general iteration process. 
For some input parameters, such as `solve_welleq_initially` and `use_interleaved` set true, with this PR, it can be faster for about 8%, while it still depends largely on whether some certain solution failures happens. 
For some other parameters, it can be slightly slower.
For SPE9, it can be slower, while for SPE9, the fast solution from my side is that no scaling for the mass balance equations with `use_interleaved`. 
With this PR, another `bool` …
> update scaling factors for mass balance equations.

- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
When running Norne with the interleaved solver sometimes exceptions
(diagonal matrix block is not invertible) occur for some rows in the
ILU decomposition. In a parallel run this means that some, but not all
processes will see the exceptions. This leads to a classic deadlock.
With this commit we catch the exception during the setup of the preconditioner,
determine with the other processes whether there were any exceptions, and
in this case all the processes will throw an exception.
Currently this limited to Dune::MatrixBlockError, but we could extend this.
> Introduces parallel exception handling for ILU0 preconditioner.

- opm/autodiff/AutoDiffMatrix.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/createGlobalCellArray.hpp
This also simplifies the `init()` method of `BlackoilPropsAdFromDeck`, since it no longer requires 2 of its old arguments.
> Silence some more warnings.

- CMakeLists_files.cmake
- examples/flow.cpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
This PR implements the communication of the distributed data to an I/O rank and therefore allows to use the serial `EclipseWriter`. 
However, it is not expected that this technique will scale as the number of cores grow. That is why the name is `ParallelDebugOutput`. This PR depends on OPM/opm-core#882.
@atgeirr: Could you test the matlab output?
> ParallelDebugOutput: make the output in ecl format work in parallel.

- opm/autodiff/AutoDiffMatrix.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
This PR improves the performance of `formInterleavedSystem(...)` by assembling the system in a different order. 
It also makes changes the enums for matrix types in `AutoDiffMatrix` to more descriptive names.
> Faster form interleaved

- opm/autodiff/BlackoilModelBase_impl.hpp
There might be wells without any perforations. It it happens
to be the last well will supscript over the bounds. In other
cases we actually return the correction for the next well.
Not sure whether returning 0 makes any sense, though.
> Return 0 as hydrostatic correction for unperforated cells.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
This refactoring has the following aims:
- use active phases (not "canonical phases") in the convergence logic,
- move towards making it possible to run flow with just two phases,
- make it easier for other models to reuse this implementation (removes more than 200 lines from opm-polymer).
It does not:
- eliminate the duplication between the `getConvergence()` and `getWellConvergence()` methods.
To do this some concepts have been reconsidered. We already had a model method `numPhases()`, that is now (as before) intended to give the number of active physical fluid phases. A new method `numMaterials()` has been added, this is intended to be the number of materials that are conserved (i.e., should be equal to `residual_.material_balance_eq.size()`). I think it might be misleading to call …
> Refactor convergence reduction and report

- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
I would recommend that developers turn on `-Wshadow` to catch these potentially confusing situations.
> Silence warnings (shadowing and unused argument).

- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
This PR implemented the Interleaved Newton step for variable np by extracting all components that depend on a fixed `np` into a separate template class. The `computeNewtonIncrement` then uses a switch case statement to iterate through the currently used variable `np`.  Currently available are `np = {2,...,6}`. Extension are easily possible. 
This has been tested on SPE9, Norne, and the solvent test cases.
> NewtonBlackølInterationInterleaved: allow np to be variable.

- tests/test_vfpproperties.cpp
- tests/test_welldensitysegmented.cpp
Required for building, self-merging.
> Add "allow crossflow" argument to add_well() calls.

- CMakeLists.txt
- examples/flow.cpp
- opm/autodiff/AutoDiffBlock.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
This pull request cuts the total runtime by around 20% compared to current master in my experiments, and produces the exact same results as master. It runs part of the assembly in parallel using OpenMP.
One caveat is that some printout may suffer from race conditions when using multiple threads, but that will hopefully be taken care of with a proper logger.
The pull request should not affect anyone, unless they enable USE_OPENMP in CMake. Then, the only side effect should be faster execution time, but more CPU use whilst running a simulation. 
I have not tested this in conjunction with MPI, but it should in theory be compatible.
> Parallel assembly (partial)

- CMakeLists.txt
- CMakeLists_files.cmake
1. Have removed old - completely stale cmake switch `INCLUDE_NON_PUBLIC_TESTS`
2. Will look for `opm-data` and run `flow` on SPE1 case as a test.
Observe that the integration test is currently just a `it runs through with exit(0)` test.
> Use opm data

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
There is a using `BaseType::wellMap` directive that redirects all the
well map accesses to the base class. In consequence the local wellMap_
is alway empty and just makes debugging harder. Therefore it is
removed in this commit.
> Removes superfluous wellMap_ member from WellStateFullyImplicitBlackoil

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
In the rare occasion that there are no wells in the model the _wells pointer in
BlackoilModelBase is a null pointer. Therefore we need to test whether it is
null and only process well information if it is not.
This problem was reintroduced with PR #460 and gets fixed by this
one. No we can run the equilibrium examples without wells again.
Sorry for the inconvenience.
This is PR #510 but without the change to loadbalance which should not have been there.
> Cater for wells null pointer

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
When running parallel one cannot use Eigen::Array::mean() for this
as the it is just a local part of the complete array. With this commit
we correctly compute the number of global cells in the grid and use this
together with a parallel reduction to compute a global mean value.
> Correctly compute the scaling factor for the equations in parallel.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/RedistributeDataHandles.hpp
Somehow I was mislead by the name rock properties that the data stored in
them is not associated to grid cells, but to rock regions. With this commit
we determine the porosity and permeability by communication.
This needs PR OPM/opm-core#918
> Communicate rock properties, too.

- examples/flow.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/RedistributeDataHandles.hpp
Since the refactoring to using opm-material a material law  manager for
the global grid was used. This meant that the properties used for
elements of the local grid were wrong. Additionally the 
SaturationPropsFromDeck with BlackoilPropsFromDeck was only copied. Leading at least to a waste of space.
Therefore we resort to initailizing a process local version with the local material layout manager.
Please note the this PR needs PR OPM/opm-material#77 merged first.
Also note that this PR will conflict with #518. Therefore I need to update the PR that will be merged later.
> Use local material manager by communication

- opm/autodiff/BlackoilModelBase_impl.hpp
As it is just used to compute the tempV value there is no need to
copy it to a new vector. With commit we use a reference to
geo.poreVolume() instead to prevent the copy.
A typical drive-by-improvement ;)
> Prevent copying the porevolume when checking for convergence.

- examples/flow_solvent.cpp
- opm/autodiff/RedistributeDataHandles.hpp
In PR #523 the parameters of the method  distributeGridAndData were changed. Unfortunately this PR failed to change the call in flow_solvent accordingsly. This PR fixes this.
I am sorry for the produced trouble, in case you guys compile with MPI activated.
> Adapts flow_solvent to change in redistribution interface.

- opm/autodiff/RedistributeDataHandles.hpp
This is my proposed fix for #526. Note that this is yet untested. Hopefully @GitPaean can test it.
Closes #526
> Only specialize distributeGridAndData for CpGrid if MPI is found.

- CMakeLists_files.cmake
This was forgotten earlier.
I do not think this is critical to backport to the release, since flow_solvent is still somewhat experimental, but if @totto82 disagrees I'll reconsider it. The current situation is that flow_solvent is not installed with the binary packages because of this.
> Add flow_solvent to list of programs to be installed.

- opm/autodiff/AutoDiff.hpp
- tests/test_syntax.cpp
This fixes a bug in the (convertible to) Scalar / AutoDiff operator, and modifies the test to make the buggy code fail.
The AutoDiff class is not used much and may be removed in the future, still it's good to avoid having known bugs in it!
> Fix bug in scalar autodiff

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/NewtonSolver.hpp
- opm/autodiff/NewtonSolver_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
This PR moves the computation of the relative time error from TimeStepControl.cpp to the Model class, BlackoilModelBase. The default behavior has not been changed. 
As a next step we can investigate better implementations of || u^n+1 -u^n || / || u^n+1 ||
> BlackOilModelBase: revision of adaptive time stepping.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/BlackoilPropsAdInterface.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/ImpesTPFAAD.cpp
- tests/test_boprops_ad.cpp
The surface density function returns one value pr cell to allow for non-constant surface densities.
Tested on the usual cases with no effects on the results.
> Support for non-constant surface densities

- opm/autodiff/RateConverter.hpp
- opm/autodiff/SimulatorBase_impl.hpp
Previously, local averages were calculated and used in the
well equations. With this commit we add versions of defineState and
calcAverages that take into account the parallel domain decomposition
and calculate correct averages.
> Calculate parallel averages in RateConverter.

- examples/flow.cpp
- examples/flow_solvent.cpp
to be able to determine the threshold pressure from the initial
condition it needs to be able to access the initial condition, i.e.,
the initial simulator state, material properties object and gravity
constant need to be passed to the thresholdPressure() function.
this is a follow-up of OPM/opm-core#907.
> adapt to the threshold pressure related API changes

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
This renames `NewtonSolver` -> `NonlinearSolver`, and changes the relationship between the solver and the model classes.
After this, the `NonlinearSolver` will call the `nonlinearIteration()` method of the model class, instead of calling `assemble()`, `solveJacobianSystem()`, `updateState()` and `getConvergence()` etc. The provided implementation of `nonlinearIteration()` in the `BlackoilModelBase` class does these things now, so the derived models do not need to change. The results, output and performance should be unchanged.
The change is intended to make the solver/model relation more flexible and less strongly coupled. This will make it possible to implement for example sequential implicit models.
Note that this conflicts with #529. It also requires a follow-up PR in opm-polymer (will …
> Refactor nonlinear solver

- opm/autodiff/BlackoilModelBase_impl.hpp
This is needed by derived models. This fixes OPM/opm-polymer#160.
> Add asImpl() to method calls.

- opm/autodiff/GeoProps.hpp
Cell centers and depths based on the cell corners is used instead of the cell centroids. 
This PR improves the match with Eclipse on the new model and norne.
> Use cell centers based on cell corners

- examples/flow.cpp
- examples/flow_solvent.cpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent_impl.hpp
i.e. it now supports stuff like MULTFLT in the schedule
section. Possibly, the MPI-parallel code paths need some fixes. (but
if the geology is not changed during the simulation, the parallel code
will do the same as before.)
the most fundamental change of this patch is that the
reference/pointer to the DerivedGeology object is made non-constant. IMO
that's okay, though, because the geology can no longer assumed to be
constant over the whole simulation run.
> implement abililty to change the geology during the simulation run

- opm/autodiff/GridHelpers.hpp
Suppresses warnings from boost.
Will self-merge (trivial PR).
> Move boost include inside warning-suppressed block.

- CMakeLists_files.cmake
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
- opm/autodiff/ParallelRestrictedAdditiveSchwarz.hpp
- opm/autodiff/RedistributeDataHandles.hpp
This PR needs OPM/dune-cornerpoint#195
With this PR I am able to run Norne in parallel with the interleaved version of flow_mpi and actually get a speedup. There is still the problem that the linear iterations increase a bit to much.  The current picture is
Test run on a workstation with two Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz. Each with 6 cores that can handle two threads.
Run using my branch this PR  and OPM/dune-cornerpoint#195 for the transmissibilities during loadbalancing. I used default arguments for the run. Processes are evenly distributed between the cpus (using `bysocket --report-bindings --bind-to-core` options for `mpirun` of OpenMPI)
procs |   total |  solver | n_lin | n_nonlin |   speedup 
-------|---------|---------|-------|----------|-----------
1 | 2104.59 | …
> Parallel overlapping ILU0

- CMakeLists.txt
- CMakeLists_files.cmake
- examples/flow_multisegment.cpp
- examples/flow_multisegment_mpi.cpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/WellMultiSegment.cpp
- opm/autodiff/WellMultiSegment.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/autodiff/WellStateMultiSegment.hpp
This PR adds a new derived model that supports multi-segment wells.
It is a very large PR, so it will be demanding to review. In the interest of saving time and effort we have tried to explain some choices we have made here, as well as provide some guidance as to what we think should be looked at.
The PR makes only limited changes to the existing `BlackoilModelBase` class, the new functionality is accessed through the new `BlackoilMultiSegmentModel` class.  A new main program, `flow_multisegment.cpp`, has been added that uses the new model. This has been done to minimise disruption to the regular version of flow. The only difference in the main programs is the simulator class used, so later refactoring of this should be trivial.
In the longer term we may want to refactor the whole well …
> Support multi-segment wells

- examples/flow.cpp
- examples/flow_polymer.cpp
- examples/flow_solvent.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/ParallelRestrictedAdditiveSchwarz.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
Since the EclipseState was added as a data member, it is no longer necessary to pass it as an argument. This also fixes the situation that there were two `schedule` variables in run(), causing a warning.
We also add warning suppression header includes to ParallelRestrictedAdditiveSchwarz.hpp.
> Remove unneeded function parameter for SimulatorBase::run(), fix warnings.

- opm/autodiff/BlackoilModelBase_impl.hpp
Since PR #541 the arrays cq_s, mob_perfcells, and b_perfcells are
empty if there are no wells in the domain of the process. This
caused segementation faults at various places where we compute
on the wells. With this commit we now guard this places using
asImpl().localWellsActive() and only using the array if the call
returns true.
This PR closes #556
> Guard access of well variable with asImpl().localWellsActive()

- examples/flow.cpp
- examples/flow_multisegment.cpp
- examples/flow_polymer.cpp
- examples/flow_solvent.cpp
- opm/autodiff/AutoDiffHelpers.hpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/GeoProps.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
This PR changes the following
1) NNCs in the deck a read and stored in geoprops instead of in autodiff helpers
2) Threshold pressures are calculated and appended to the threshold pressure vector 
Depends on OPM/opm-parser#635, OPM/opm-core#928 and OPM/dune-cornerpoint#193
This PR supersedes #539. The difference between this PR and #539 is that this PR does not use the pinchProcessor to generate the pinch connections.
> NNC and threshold pressure

- opm/autodiff/AutoDiffHelpers.hpp
> Silence int vs. size_t warnings.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
Change due to change in method signature for method extractPvtTableIndex() in opm-core. 
Must be merged together with 
https://github.com/OPM/opm-core/pull/940
> OPM-163: Changed signature for method extractPvtTableIndex

- opm/autodiff/SolventPropsAdFromDeck.cpp
This change was missing for some reason in #569.
Will self-merge as this is a small but critical fix.
I wonder how this could happen, though?
> Fix change in signature of extractPvtTableIndex() in solvent props.

- opm/autodiff/FlowMain.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/autodiff/WellMultiSegment.cpp
- opm/polymer/PolymerProperties.hpp
- tests/test_vfpproperties.cpp
Several files stopped compiling due to relying on opm-parser headers doing
includes. From opm-parser PR-656 https://github.com/OPM/opm-parser/pull/656
this assumption is no longer valid.
> Fixes includes wrt opm-parser PR-656

- CMakeLists.txt
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- tests/test_restart.cpp
@dr-robertk : Now the code is moved to the BlackoilOutputWriter class to have IO in one place. The names of the new methods (initFromRestartFile, isRestart..) does not go well with the "Writer" part of the classname, but this code is soon to be refactored i guess (IO will be moved to parser) so I think the names are good for now. 
This PR includes the following:
- If a restart have been initiated with the keywords RESTART and SKIPREST, 
WellState and ReservoirState are initialized with OPM_XWEL and SOLUTION data from the restart file,   respectively. 
For now the following data is read from restart file:
Solution data:   pressure, temperature, saturation, RS and RV
XWEL data:   temperature, bhp, perfpress, perfrates, wellrates
- The current time of the simulator timer are set to the start …
> Start Flow from restart file

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
A user-defined default constructor is required in this situation unless explicitly using the empty-brace-init syntax.
See discussion here:
http://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a
It is possible that gcc is less strict than clang here, anyway the minor change below restores complilation with clang on my system, and I will therefore self-merge.
> Fix minor issue with const POD requirements.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
this PR replaces the PVT classes from opm-core by the ones provided by opm-material. to use it OPM/opm-material#114 is required.
Motivation
==
the main motivation for this change is the ability to properly handle temperature derivatives of the quantities. also, it is easier to add new features like "viscosibility" with the approach taken by the PVT classes of opm-material than it is to do this with the ones of opm-core. Finally, the computational performance seems to be slightly better with this (see below).
Performance
==
I mainly used the SPE9_CP dataset to compare performance. Each branch was run 10 times and the timing was measured (I also tried to configure my system in such a way that the measurement noise was reduced as much as possible: no turbo boost, no hyperthreading, fixed CPU …
> use the blackoil PVT classes from opm-material instead of the opm-core ones

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent_impl.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/autodiff/SolventPropsAdFromDeck.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
Miscibility effects are added to the solvent model and effective density and viscosity calculated using the Todd-Longstaff model. 
Tested using SPE1CASE2_SOLVENT_MISC_TL.DATA and SPE9_CP_SOLVENT_CO2_MISC_TL.DATA found in opm-data/solvent_test_suite
Note. Commit 69792d0 introduces changes to the BlackoilModel and the PolymerModel without effecting the results or the performance.
> Add miscible effects to the solvent model 

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/LinearisedBlackoilResidual.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
This PR add the possibility to use the AMG preconditioner for the Interleaved solver (when UMFPACK is disabled) and other small changes: 
- Fix residual is too large output. 
- ILU0 with relaxation parameter 0.9 
- single precision solvers when dt < 20 days
- print total time after each report step (for performance comparison)
> AMG for Interleaved solver and other goodies.

- opm/autodiff/DuneMatrix.hpp
Due to the upcomming release the name changes (`j`->`j_`, `nnz`->`nnz_`) already appear
in 2.4.1. This commit now checks for 2.4.1 and newer instead of 3.0 and newer.
> Account for variable change in 2.4.1

- CMakeLists_files.cmake
- opm/autodiff/AutoDiffBlock.hpp
- opm/autodiff/AutoDiffMatrix.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/fastSparseOperations.hpp
- opm/autodiff/fastSparseProduct.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
This PR improves performance of flow by introducing an improved sparse add method for AutoDiffMatrix. When two SparseMatrix have the same sparsity pattern, we can simply add all matrix entries. Performance improvement of close to 10% has been discovered with SPE9 and Norne. 
This PR already includes #578. I will rebase once the other PR is merged.
> Fast sparse add.

- opm/autodiff/AutoDiffBlock.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/autodiff/SolventPropsAdFromDeck.hpp
Support PVT, SFUN and MISC regions in the solvent properties. 
- mapping from cell to region is computed for SATNUM and MISCNUM 
- element-wise power operator is implemented in AutoDiffBlock
- TL parameter is represented element-wise (but still constant)
Needs OPM/opm-parser#686
> Support regions in the solvent model 

- tests/test_restart.cpp
1. Fix the relative numeric limits in the restart test - hopefully this is now promoted from *works in Statoil* status.
2. Added an extra double value for to represent the absolute difference in comparisons.
Regard 2 - there was an ert f.... up which has broken the build: https://github.com/OPM/opm-autodiff/issues/591 - sorry about that.
> Fix restart test

- opm/autodiff/FlowMain.hpp
- opm/autodiff/RedistributeDataHandles.hpp
Since the support for threshold pressures running Norne with
flow_mpi aborted error messages like
```
Program threw an exception: [/home/mblatt/DUNE-test/opm-autodiff/opm/autodiff/BlackoilModelBase_impl.hpp:383] Illegal size of threshold_pressures input ( 153924 ), must be equal to number of faces + nncs ( 78316 + 0 ).
```
This commit now distributes the threshold pressures (if present) just like the rest
of the model properties and Norne does not abort here any more.
Please note:
1. If there are NNCs flow_mpi will abort with an error.
2. We might want to resort to reading and calculating the threshold pressure
(and maybe other properties) on distributed grids instead of using communication.
Fixes #589
> Fixes the exception for models with threshold pressures.

- opm/autodiff/BackupRestore.hpp
- opm/autodiff/fastSparseOperations.hpp
This PR fixes a bug in the backup/restore due to a mix between size_t (64 bit) and unsigned int (32 bit).
It also includes a small change in fast sparse operations.
> Bugfix in backup/restore.

- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/polymer/PolymerProperties.hpp
- tests/test_restart.cpp
- tests/test_vfpproperties.cpp
OPM/opm-parser#677 changes the return types for the Deck family of classes.
This patch fixes all broken code from that patch set.
https://github.com/OPM/opm-parser/pull/677
> Change Deck access methods/types to references

- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
Since it came quite as a surprise to me that this can be the case, the
better fix is possibly to unconditionally create an ADB for
temperature.
> BlackoilPropsAdFromDeck: allow the AutoDiffBlock which represents temperature to be empty

- opm/polymer/IncompTpfaPolymer.cpp
- opm/polymer/IncompTpfaPolymer.hpp
- opm/polymer/PolymerState.hpp
- The PolymerState class will derive from SimulatorState, instead of
containing a TwoPhaseState instance.
- The Polymer calculation methods take PolymerState& input argument
instead of TwoPhaseState&
This is a followup to: https://github.com/OPM/opm-core/pull/954
OK: Have now run Norne successfully - in my opinion ready to be merged.
> PolymerState changes

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/polymer/IncompTpfaPolymer.cpp
- opm/polymer/IncompTpfaPolymer.hpp
Both detected by compiler warnings. Minor bugs probably had no ill effects though.
> Fix minor initialization and overriding bugs.

- opm/autodiff/FlowMain.hpp
This is the follow-up to OPM/opm-core#965.
> Adapt to removed init() parameter.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/autodiff/SolventPropsAdFromDeck.hpp
the changes are all pretty trivial: all of them remove of some header file `#include ` statements which do not exist anymore after the opm-core PVT classes have been removed and the addition of `#include ` statements for classes which where previously included via the old PVT headers (i.e., by transitivity).
> fix the fallout of the removal of the opm-core black-oil PVT classes

- opm/autodiff/FlowMainSolvent.hpp
> Skip the relperm diagnostics for the solvent model.

- opm/autodiff/AutoDiffBlock.hpp
- tests/test_block.cpp
A power method where both f and g are ADB variables is added
using the general derivative rule
(f^g)' = f^g * ln(f) * g' + g * f^(g-1) * f'
Tests are added to test_block.cpp
> Add power method for general f^g in the AutoDiffBlock

- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
to reduce some extra cost when multi-segment well is not involved.
The functions mainly affected are `addWellFlux`, `computeSegmentFluidProperties` and `computeWellConnectionPerssures`, which show relatively bigger performance degeneration due to handling usual wells as multi-segment well with one segment. 
The performance difference between flow_multisegment and flow is much smaller (1% or 2%, which is hard to test accurately due to the performance fluctuation of the computer itself.) now.
The results from flow_multisegment are not changed by this PR.
> adding flag to wops_ms_ to indicate if MSW is involved.

- opm/autodiff/FlowMainSolvent.hpp
This PR need https://github.com/OPM/opm-core/pull/972.
@totto82 I have test one of opm-data/solvent_test_suit, would you like to test more or the cases that have issues?
> enable relperm diagnostics for solvent model.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This PR adds the possibility to spawn an extra thread for writing the output. I tested with Norne and SPE9 and the results look the same. However, it should be discussed if the cxx-11 feature std::async can be used or a similar implementation with OpenMP needs to be done (by somebody else). Right now the old state remains default, i.e. no async output.
> Asynchronous output.

- opm/autodiff/BlackoilModelBase_impl.hpp
- The initial rates are only set to target values for single phase
producers (orat, wrat, grat).
- For injectors compi is used to determine the initial target rates.
Tested on SPE1 and SPE9 where ORAT is substituted with LRAT.
> Bugfix. Fix setting initial rates in updateWellControls

- opm/autodiff/FlowMainPolymer.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
Not ready for merging yet. 
Comparing with the direct solver, the interleaved solver gives about 14 times faster performance with the 3D_plyshlog test cases in opm-data and does not change the results. 
The scaling factor for the polymer equation currently takes the same scaling factor with the water equation. Not sure if it is the optimal one, while it is an okay one comparing with some other trivial options. 
The CPR solver does not work yet. 
There remains one compiling error though. No clue why it happens and comment will be appreciated. 
```
607 /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/FlowMainPolymer.hpp:109:57: error: expected primary-expression before ‘>’ token
608                  solver_approach = param_.get<std::string>("solver_approach");
```
> making the interleaved solver works for blackoil polymer simulator.

- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent_impl.hpp
The first commit treats shut wells, the second avoids negative values to the scaled relperm endpoints. This PR is needed in order to run all the SPE5 cases successfully.
> Fixes to the solvent model

- CMakeLists_files.cmake
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/autodiff/SolventPropsAdFromDeck.hpp
- tests/test_solventprops_ad.cpp
The Todd-Longstaff model is extended to incorporate pressure effects
The solvent viscosity is then caculated as
mu_eff = mu_s^(1-\alpha * \omega) * mu_mix^(\alpha * \omega)
where \omega accounts for the porous media effects and \alpha =
\alpha(pressure) accounts for the miscibility of the solvent and oil
when contacted.
The \alpha values can be given using the TLPMIXPA keyword
If no entries are given to TLPMIXPA the table specified using PMISC will
be used as default.
IF TLPMIXPA does not appear in the grid \alpha = 1 and the pressure
effect is neglected.
This is tested in test_solventprops_ad.cpp
> Implement pressure effects in the Todd-Longstaff mixing parameter

- dune.module
this restores the ability to build opm-autodiff and all dependencies
using `dunecontrol`. Except for opm-common adding these dependencies
is not really required because they were inherited from other modules,
but stating them explicitly is good style IMO.
> dune.module: add all modules which opm-autodiff depends on explicitly

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
Some refactoring to avoid code duplication. Mostly related to extracting data for the wells. 
- `ExtractWellPerfProperties()` is used to compute well perforation properties for the solvent model. This avoids duplication of assemble()
- `computePropertiesForWellConnectionPressures()` is added to the base model in order to tailor this for the solvent model. 
- The last commit fixes a bug that prohibited `flow_solvent` to run deck where solvent is not specified.
Tested on norne and the solvent tests
> Refactor the solvent model 

- .travis.yml
The opm-autodiff module depends on opm-output so that module must be available in Travis builds.
> Request requisite module opm-output in Travis builds

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
We introduce a `StandardWells` class to handle the current well model we are using, which will be distinguished with the `MultisegmentWells` and other possible well models later in the future. Different well models will be treated separately eventually. 
It is just the very first step, more PRs will come later. 
It is tested with Flow, Flow_polymer, Flow_multisegment and Flow_solvent. It is tested with Norne and SPE9 for Flow.  For other simulators, one example for each. It does not change any results.
> A first step towards Wells refactoring

- jenkins/build-opm-simulators.sh
- jenkins/run-norne.sh
- jenkins/run-polymer.sh
- jenkins/run-spe.sh
Use shared copy of opm-data when possible
- The user can supply OPM_DATA_ROOT directly and this is used.
- The user can supply OPM_DATA_ROOT_PREDEFINED and this is used unless there is a PR against opm-data specified in the trigger.
This is used to minimize the network traffic on the jenkins resource. opm-data is updated nightly, and this nightly updated copy is used unless otherwise instructed.
This commit also enables the opm-data integration tests on all runs.
> Use shared copy of opm-data when possible

- examples/opm_init_check.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/polymer/PolymerProperties.hpp
This PR changes the use of EclipseState's API in opm-parser, see PR [Introduce Eclipse3DProperties #751](https://github.com/OPM/opm-parser/pull/751) in other repo.
The only changes are from `->` to `.` and use `state.getEclipseProperties()`.  Also added some `const auto& x` where we previously copied.
> Using new EclipseState API, made ->s into .s

- opm/simulators/SimulatorCompressibleTwophase.cpp
- opm/simulators/SimulatorIncompTwophase.cpp
This was disabled when the facilities were moved to opm-output. Now that the simulators are in the opm-simulators module and not opm-core we can re-enable it.
> Re-enable output for 2-phase sims.

- opm/polymer/PolymerProperties.cpp
- opm/polymer/PolymerProperties.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- opm/polymer/fullyimplicit/PolymerPropsAd.cpp
- opm/polymer/fullyimplicit/PolymerPropsAd.hpp
The current master is using effective water viscosity for both water and polymer, which is wrong. 
The PR did not change the results of the current polymer cases in the opm-data, since the omega values are 1, effective water viscosity and effective polymer viscosity are the same.
> using effective polymer viscosity for polymer mobility calculation.

- opm/polymer/CompressibleTpfaPolymer.cpp
- opm/polymer/PolymerProperties.cpp
- opm/polymer/PolymerProperties.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/PolymerPropsAd.cpp
- opm/polymer/fullyimplicit/PolymerPropsAd.hpp
The current implementation always use the visc[0] as the water viscosity. The problem has been hidden because we have been using constant water viscosity for most of our polymer cases. 
With this PR, we will be able to handle dependent water viscosity.
> correcting buggy pointer usage for visc parameters in effective viscosity calcuation

- opm/autodiff/BackupRestore.hpp
This PR makes the backup-restore functionality in opm-simulators work again. 
@joakim-hove: Don't worry, we are still testing the ECL restart file functionality ;-).
> BackupRestore: remove all specializations for BlackoilState.

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWellsSolvent.hpp
- opm/autodiff/StandardWellsSolvent_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellHelpers.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
Moving the following functions related to Wells from `BlackoilModelBase` to `StandardWells`. 
. `computePropertiesForWellConnectionPressures`
. `computeWellConnectionDensitesPressures`
. `extractWellPerfProperties` 
. `computeWellFlux`
. `updatePerfPhaseRatesAndPressures`
. `updateWellState`
. `updateWellControls`
A derived class `StandardWellsSolvent` is introduced to handle the solvent related well stuff. 
Some temporary interfaces such as `extractWellPerfProperties` and `updateWellState` are kept for `BlackoilModeBase` for recovering the running of `flow_multisegment`. They will be removed when we get the point to remove `BlackoilMultisegmentModel`. 
The PR is tested for `flow` with SPE9 and Norne. `flow_polymer` with one 3D polymer case. `flow_solvent` with `SPE1CASE2_SOLVENT.DATA`. …
> Moving more well related functions to StandardWells

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
This PR does moves the computation of well potentials to the model class in order to use `computeWellFlux()` to calculate the well potentials. The main drawback with the current approach is that the well potentials are calculated every iteration even if they are not needed.
The long term fix would be to `computeWellPotentials()` only for the initial iteration and then update the well controls directly. (Not via the `WellsManager` as it is now). This will also avoid storage of well potentials in the `WellState`.
A short term fix that would avoid performance regression in the test cases is to add a logic that only calculates well potentials if it is needed.
Currently, no tests are conducted to measure the performance loss of this PR.
This PR should not be merged before potential performance …
> Fix well potential calculations

- opm/autodiff/BlackoilModel.hpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/StandardWellsSolvent.hpp
- opm/autodiff/StandardWellsSolvent_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
Adding the WellModel as a template Class for `BlackoilModelBase`. 
The previous implementation will  cause two std_wells_ with different types in the BlackoilSolventModel, which is actually buggy. 
Not result change for `flow`, `flow_solvent`, `flow_polymer` and `flow_multisegment` is observed.
> Wells refactoring_adding WellModel as template class

- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/StandardWellsSolvent.hpp
- opm/autodiff/StandardWellsSolvent_impl.hpp
Adding the bool flag `has_solvent_` to `StandardWellsSolvent`, so that the running with `flow_solvent` with cases without solvent can be recovered. 
It is tested with `SPE1CASE2.DATA` and `SPE9.DATA`.
> adding the has_solvent_ flag to StandardWellsSolvent

- opm/autodiff/FlowMainPolymer.hpp
It is tested with `SPE1CASE2.DATA` and `SPE9.DATA` and polymer running.
> fixing flow_polymer running cases without polymer.

- opm/autodiff/AutoDiffBlock.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/StandardWells_impl.hpp
- opm/simulators/thresholdPressures.hpp
This PR enables running a two phase test case with plausible results
This PR should have no side effects for running existing three phase simulations. See also the twin PR in opm-core which should be merged simultaneously with this one
> Two phase bugfixes

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
This is a followup to: https://github.com/OPM/opm-parser/pull/777.
I started out with an intention of fixing: https://github.com/OPM/opm-parser/issues/773 - however as mentioned here: https://github.com/OPM/opm-parser/issues/773#issuecomment-214395099 I got cold feet and backed off from any substantial changes. 
The end result is that this PR is extremely trivial.
> Change method name -> IOConfig::restart()

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWellsSolvent.hpp
- opm/autodiff/StandardWellsSolvent_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
The following functions are moved from `BlackoilModelBase` to `StandardWells`.
.`addWellFluxEq`, `addWellControlEq`, `computeWellConnectionPressures`, `computeWellPotentials`, `variableWellStateIndices` and `variableWellStateInitials`. 
Now it is difficult to do more movement without beginning working on the multi-segment wells side. 
The PR is tested for `flow`, `flow_polymer`, `flow_solvent`, and `flow_multisegment`.
> More functions moved to StandardWells

- opm/autodiff/AutoDiffHelpers.hpp
this partially fixes the build on ubuntu xenial.
it also breaks due to an updated eigen, but with this
you can build with the old eigen instead of the distro
supplied eigen.
> fixed: build with g++ 5.3

- opm/autodiff/FlowMain.hpp
- opm/autodiff/GeoProps.hpp
* Changed default output directory in FlowMain to be "." instead of "output".  This is consistent with Eclipse
* Removed one * to reflect changes in Parser API.  This depends on OPM/opm-parser#791
> The getNNC API in Parser changed; remove *

- opm/autodiff/FlowMain.hpp
May be necessary on some platforms for the current dir (".").
Please check, @qilicun, if this fixes issue #682.
> Check if dir already exists before creating.

- opm/autodiff/FlowMainSolvent.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- For some cases (for instance involving solvent flow) the reasoning for
only adding the pressure derivatives seems to fail. As getting the
sparsity pattern is non-trivial, in terms of work, the full sparsity
pattern is only added when specified by the parameter
"require_full_sparsity_pattern"
- For solvent runs "require_full_sparsity_pattern" defaults to true for
all other runs the default is to only extract the sparsity pattern from
the pressure derivatives.
> Add the option of computing the full sparity pattern based on all phases

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEnums.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
If hydrocarbonstate is not provided by the state fall back to
the old behavior of computing the hydrocarbonstate from the saturations
Depends on OPM/opm-core#1015 
Tested on various cases
case  |This PR | | Master | |
--------|-----|-----|-----|-----
| Newton | Linear | Newton | Linear
SPE1CASE1 | 224 | 1279 | 222 |1251| 
SPE3CASE1 | 323 |2652 | 323| 2653|
SPE9_CP | 224 |1257 | 222| 1251 |
norne | 1631| 25173 | 1625| 25216|
simple2D (polymer) | 904 |3849 | 905| 3844 |
SPE5CASE1 (solvent) | 812 |3953 | 813 |3963 |
Based on this teste, it is a somewhat inconclusive whether this improves the convergence 
My motivation for providing this PR is 
1. It is more consistent. The hydrocarbon state is determined in updatestate except for the initialization before the frist timestep. It doesn't …
> Use stored hydrocarbonstate to get primal variables

- opm/autodiff/BlackoilSolventModel_impl.hpp
Includes: 
- fixes to make liveoil and solvent work together 
- some convergence fixes in the TL model. 
- changes in how the sparsity pattern is determined 
Note: The last point effects the standard blackoil model, the two first ones only the solvent model. 
Note2: With this PR the updatestate in the solvent model no longer uses updatestate in the base model. I plan to restructure this part later to avoid code copying, but would like to wait until this part of the code matures.
> Changes needed to run Model 2 with co2

- opm/autodiff/StandardWells_impl.hpp
The use of parenthesis is wrong according to Cramer's rule. 
It is a bug pointed out by @totto82 in OPM/opm-simulators#684 . 
It should not change the results significantly, while thorough tests need to be done before merging.
> fixing application of rs and rv to the volumeRatio calculation.

- opm/autodiff/FlowMain.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
The non-cartesian connections are required by the output facilities, while the truly non-neighbour connections (meaning those not in the grid) should be used by all other code.
Test of Norne still running locally, seems ok so far, but this should be tested carefully for both results and performance.
> Separate non-neighbour and non-cartesian connections.

- opm/autodiff/RedistributeDataHandles.hpp
This is needed since hydro carbon state is used to get the
primal variables in PR #687. Therefore we now distribute the
state along with rest of the black oil state variable at the
start of a parallel simulation.
This closes issue #695
> Correctly distribute the hydro carbon state for parallel runs.

- opm/autodiff/ParallelDebugOutput.hpp
ParallelDebugOutput will always dereference its member variable
globalReservoirState_ even if it will not be used for any output.
In g++ this throws when using -D_GLIBCXX_DEBUG -DDEBUG -DGLIBCXX_FORCE_NEW.
I any case we will have a dangling reference into Nirvana in
PackUnPackSimulationDataContainer. This commit fixes this by always
initializing the pointer globalReservoirState_. In the case where the rank
does not perform any output its size will be zero.
This closes #697.
> Prevent dereferencing a null pointer during parallel output.

- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
On my system I got
```c++
error: variable ‘std::ofstream file’ has initializer but incomplete type
std::ofstream file(fname.str().c_str());
```
This is fixed with this commit by including fstream. Previously, this include might have happened implicitely.
> Fix incomplete type error for std::ofstream in examples

- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
This PR adds a user flag to allow to ignore the convergence failure of the linear solver. 
For Model 2 this gives a speedup according to totto82.
The default behavior remains unchanged.
> Ignore linear solver convergence failure.

- opm/autodiff/FlowMain.hpp
This PR separate debug and other information into different files.  The hidden file ``.XXX.DEBUG`` file will contain all the developer-centric information. This PR depends on https://github.com/OPM/opm-common/pull/131
> Write debug information into a separate file.

- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorBase_impl.hpp
Gas saturation is used as primal variable if DISGAS and VAPOIL is
not activated. 
Needs OPM/opm-core#1025
> Adds has_disgas and has_vapoil flags to hydrocarbonstate initialization

- opm/autodiff/StandardWells_impl.hpp
Instead of writing to std::cout.
Without this, the messages will only appear in terminal output and not in the PRT log file.
> Log well control switching message.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
this was an involuntary omission in the "local AD" to "dense AD" rename...
I'm open to change this to a better suffix, so feel free to suggest one in the comments. It should probably be noted that this PR is self contained, but for consistency reasons it would be beneficial to merge it together with its opm-core counterpart.
> rename some variables from "Lad" to "Eval" (was: to "Dad")

- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
This is a follow up to PR #700 which only covered ILU as a preconditioner
> Make CPR preconditioner honor linear_solver_ignoreconvergencefailure

- opm/autodiff/BlackoilModelBase_impl.hpp
It was computing a global maximum before, which obviously is not the same thing. Therefore this really fixes a bug that I probably should have noticed a long time ago. Well, better late than never.
This needs PR OPM/opm-core#1026 to be merged first!
> Fix the parallel L-infinity norm calculation.

- opm/autodiff/AutoDiffHelpers.hpp
This is the first of a series of minor features that are used by upcoming sequential split models. I'm trying to keep the disruption minimal by doing one small feature at a time.
> Add connection_cells member of HelperOps.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
A minor fix with no changes to behavior. Will self-merge when tests are green unless someone objects.
> Use const reference parameters for prepareStep()

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
This makes it easier to run without, for example for debugging. The default is 'true', preserving existing behaviour.
Again, unless objected to I intend to self-merge this fairly quickly after the tests are green.
> Add use_update_stabilization parameter.

- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
Adds a mutable `model()` accessor and more importantly, a new `step()` method that allows us to separate the concepts of initial state (start of timestep) and starting state for iterations.
Will self-merge after tests are green unless objected to.
> Refine nonlinear solver interface

- opm/autodiff/MultisegmentWells.cpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/WellMultiSegment.cpp
- opm/autodiff/WellMultiSegment.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp
- tests/test_multisegmentwells.cpp
The shared_ptr aliasing is deprecated, and in the Well case this has
been removed upstream.
Upstream. https://github.com/OPM/opm-parser/pull/849
> Well shared_ptr alias deprecated

- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
The changes are:
- Make the `WellOps` struct public (needed by transport solver).
- Make it possible to store and retrieve total reservoir volume perforation fluxes with `getStoredWellPerforationFluxes()`, controlled by a flag set by `setStoreWellPerforationFluxesFlag()`, defaulting to `false` (needed by pressure solver).
This should not change any results or performance for the fully implicit solvers.
> Changes to well model for supporting sequential approach.

- opm/autodiff/FlowMain.hpp
Remove guard against 2 phase cases for EQUIL initialization. 
Depends on OPM/opm-core#1027
> Allow for 2 phase initialization using EQUIL

- CMakeLists.txt
- CMakeLists_files.cmake
- examples/flow_sequential.cpp
- opm/autodiff/BlackoilPressureModel.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/FlowMainSequential.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/SimulatorSequentialBlackoil.hpp
This PR adds sequential solvers, including a simulator variant using them (flow_sequential.cpp) with an integration test (running SPE1, same as for fully implicit).
The sequential code is capable of running several (but not all) test cases without tuning or special parameters, but reducing ds_max a bit (from default 0.2 to say 0.1) helps with transport solver convergence. The Norne model runs fine (esp. with a little tuning). A parameter iterate_to_fully_implicit (defaults to false) is available, when set the simulator will iterate with alternating pressure and transport solves towards the fully implicit solution. Although that takes a lot extra time it serves as a correctness check.
Performance is not competitive with fully implicit at this point: essentially both the pressure and …
> Experimental sequential solvers

- opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp
When we do not use PLYSHLOG shear model, the diameter of the well-bore does not need to be specified explicitly, which is required for the calculation of the representative radius.
> only calculating representative radius when having PLYSHLOG.

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
In that case we cannot call numPhases() on the wells as it produces
a floating point exception. As we do not use that information in this case
anyway, we simply use -1 instead to prevent the call.
Closes #731
> Fix handling of no wells in WellStateFullyImplicitBlackoil.hpp

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/MultisegmentWells_impl.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
As for each well only one process is responsible, the output process
does not see all wells. Ergo some well switching information was never
printed in a parallel run.
Therefore with this commit the well switching
message is printed regardless on which process it appears.
> Print all well switching in parallel.

- opm/autodiff/BlackoilModelBase_impl.hpp
This is used to compute the Euclidian product for the saturations.
Thes are ordered in an interleaved manner (all saturations for cell
with index 0, the all for index 1, ...). Up to now the implementation
assumed a different ordering: blockwise (all saturations for phase 0 first,
then all saturations phase 1, ...).
With this commit the computation uses the right assumption.
Closes #713
> Fixes the parallel Euclidian product for multiple phases.

- opm/autodiff/FlowMain.hpp
With this PR the param system will look for 'nosim', and you can start flow as:
```txt
flow nosim=true DECK.DATA
```
The purpose of this is to facilitate faster and simpler debugging of INIT and EGRID files. 
Depends on: https://github.com/OPM/opm-parser/pull/864
> Will look for param: 'nosim' and override deck.

- CMakeLists.txt
- opm/autodiff/FlowMain.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- tests/compare_INIT.py
Warning: This is work in progress, but it is posted here for early review and discussion, in case I am on the wrong track entirely.
Further plans:
1. These must be merged: https://github.com/OPM/opm-output/pull/51 :  https://github.com/OPM/opm-common/pull/149
2. ~~The method `EclipseWriter::writeInit( )` writes the `CASE.INIT` *and* `CASE.EGRID` files - i.e. the files which are written *before* the actual simulation starts. I wish to rename that to e.g. `EclipseWriter::writeStatic( )`.~~ Update: have renamed to `EclipseWriter::writeInitAndEgrid( )`.
3. ~~The `NNC` argument should be removed from the `EclipseWriter` constructor, it should rather be passed to the `EclipseWriter::writeStatic( )` method - where it will be dispatched to the `EclipseWriter::writeEGRID()` and …
> Write TRAN? to the INIT file.

- opm/autodiff/SimulatorBase_impl.hpp
Previously each process printed this to the terminal
> Use termininal_output_ to only print time step status once for parallel runs

- CMakeLists.txt
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilPressureModel.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer_impl.hpp
- tests/test_multisegmentwells.cpp
Based on the current requirement, it supports the economic limit related to minimum oil rate, minimum gas rate, and water cut. 
Other limits like gas-oil ratio, water-gas ratio, minimum liquid rate, are relatively easy to add. Will add them when having time. 
Ending the running after some well is closed is not supported. 
Secondary water-cut limit treatment, which is related to how to handle when it is about to remove the last connection of the well due to water-cut limit, is not supported yet. 
The workover on exceeding water-cut, GOR, WGR or GLR limit only support closing the worst-offending connection. 
It is dependent on the PR OPM/opm-core#1051
> Support of Keyword WECON. 

- CMakeLists_files.cmake
- opm/autodiff/FlowMain.hpp
- opm/autodiff/MissingFeatures.cpp
- opm/autodiff/MissingFeatures.hpp
The intention of this PR is to output messages for the keywords which are supported by opm-parser but not by flow. 
This PR only deal with the unsupported keywords. For the case that partially supported keywords and partially supported options, that are much more complicated and need more consideration.
The keywords listed in this PR may not include all the unsupported keywords or some of them probably have been already supported but I did aware. In any of these two case, please feel free to make comments.
> Diagnostics keywords that not supported by flow.

- opm/autodiff/MissingFeatures.cpp
removing `COMPSEGS` and `PLMIXPAR` from the unsupported keyword list. 
And it looks like a list not easy to maintain.
> correcting the list for the missing features

- tests/compare_INIT.py
- tests/test_restart.cpp
There has been a bug in the code comparing binary eclipse keywords  -this is fixed here: https://github.com/Ensembles/ert/pull/1168 
With the fix applied some of the existing integration tests fail; this PR adjusts limits so that the tests pass again. 
This *might* have been the source of some of the confusion regarding the real state of restart support in flow.
> Fixup from bug in ert comparison code.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
If the well iterations is ``std::numeric_limits<int>::min()``, it should not do the counting.
> fix well iterations counting bugs.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilPressureModel.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
models may need a more detailed picture of where they are in the
simulation. Note that since the timer objects are available at every
call site, this is also not a very deep change.
this PR has a cyclic depency with  OPM/opm-core#1052 and must thus merged synchronously.
> pass the simulation timer object instead of the time step size

- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
while the printed number of "Non linear iterations" was correct in a
strict sense, it was very confusing if one was working on the
linearization code because the last Newton iteration of each time step
was linearized but not solved for (and the solution was thus not
updated hence it does not count as a "non linear iteration"). This
makes sense for large problems were the total runtime is completely
dominated by the performance of the linear solver, but smaller
problems exhibit the opposite behavior (i.e., for them, runtime is
typically dominated by the linearization proceedure), so one is more
interested in the number of linearizations, not the number of linear
solves.
note that this PR needs a (small) companion  in opm-core.
> distinguish between the number of non linear iterations and the number of linearizations

- opm/autodiff/GeoProps.hpp
After commit 2620dda  multiplyHalfIntersections_(..) was called before the ntg values where modified. 
This fix restores the good match for norne. 
This PR should also close #782
> BUGFIX. Use the modified NTG values in multiplyHalfIntersections_(..)

- opm/autodiff/MissingFeatures.cpp
- opm/autodiff/MissingFeatures.hpp
There are some options of the keywords only partially supported by flow, handle them automatically is not that easy, so we decided to handle them manually, the lucky thing is that the number of these kind of keywords is limited. 
Any feedback and suggestions are welcome.
> Handle partially supported options manually.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
The first commit is just a minor argument reordering - that is a required companion to this: https://github.com/OPM/opm-output/pull/79
The second commit is mainly text/documentation to illustrate how we now can start adding simulator calculated properties to the restart file.
> Illustrate support of properties like KRW and FLUX in restart file.

- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
This is #766 (rebased) with some commits added.
There are still some minor defects, that can be fixed later: use of numbers instead of named (enum) constants for example, but it should be ready to go in. I will merge when tests are green.
@qilicun, I'd appreciate if you could test that commit b5e986d did not ruin anything, in particular the compressible polymer simulator (the one that is not a Flow variant).
> Output total fluid in place

- opm/autodiff/GeoProps.hpp
Make sure that inactive cells are not included in the averaging.
Tested on Norne and it does not effect the results. (unchanged residuals) 
Thanks @andlaus for noticing. 
See issue #786
> BUGFIX. Correctly handle ACTNUM in minPvFillProps_()

- examples/opm_init_check.cpp
- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/GridInit.hpp
- tests/test_boprops_ad.cpp
- tests/test_rateconverter.cpp
- tests/test_transmissibilitymultipliers.cpp
This is a followup to: 
parser: https://github.com/OPM/opm-parser/pull/905 
core: https://github.com/OPM/opm-core/pull/1059 
grid: https://github.com/OPM/opm-grid/pull/230
This will not actually use any new functionality; only ensure that things compile.
> shared_ptr<EclipseGrid> -> const EclipseGrid&

- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Previously, the call was made after the grid was distributed.
This means that each process wrote it, but only with his cells
active which was just a part of the whole domain.
With this PR we make the writeInit call before distributing the
grid and make sure that only one process calls it.
Closes #765.
> Call writeInit with global grid and properties.

- opm/autodiff/ParallelDebugOutput.hpp
The order of an unordered_map is quite unpredictable. (The same order will only hold with the same hash function, comparison operator, and insertion order). Therefore we cannot assume that the global SimulationDataContainer uses the same order for the cell data as the local one (This was done before this commit). But we can assume that the local one uses the same order on every
process.
Before this PR data got mixed up (e.g. gasoilratio with surfacevol) when gathering local data for writing eclipse files on the master process. This PR fixes this.
Instead of iterating over the cell data of the global state when writing the data received, we again iterate over the cell data of the local state and simply use the key to request the correct data for writing from the global state.
Closes #772
> Do not assume ordering in an unordered_map when gathering data.

- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
When running in parallel a well state object with the well information of the whole grid needs to constructed to gather the information from all processes. Previously, this was done with the report step exported by thetimer. This was wrong for the following reason:
The output occurs after solving the time step and the timer is already incremented. This means that we constructed the well state for gathering the data for the next report step, already. Unfortunately, at that step some wells that we have computed results for might have been shut. In that case an exception with message "global state does not contain well ..." was thrown.
This problem occured for Model number 2 and might have been due to shut wells because of banned cross flow. With this PR Model number 2 runs through again …
> Fix step number used by parallel io and OutputWriter::writeTimeStep

- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Pass an `EclipseGrid` instance to the output writer instead of the `const int*` global/active mapping. Depends on:
Parser: https://github.com/OPM/opm-parser/pull/915
Output: https://github.com/OPM/opm-output/pull/87
> Updated OutputWriter signature.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Check that we actually have data values for relative permeability properties `{WAT,OIL,GAS}KR` before attempting to output the arrays.
While here, also correct an apparent misprint in the criterion for whether or not to activate relperm output.  We should check `liquid_active` and `vapour_active`, not `aqua_active`, when considering OILKR and GASKR properties respectively.
> phase-KR: Don't emit empty property arrays

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
Somehow rsSat/rvSat were never set in original PR, and this should fix that issue. 
Related to issue OPM/opm-output#88
> Bugfix for output writer

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
Its first implementation computed wrong results in parallel. With this commit we now have completely parallelized the computations and the results seem correct for parallel runs with norne.
Closes #807.
Includes and closes #828
> Correctly parallelize computeFluidInPlace

- opm/autodiff/FlowMain.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/RedistributeDataHandles.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent_impl.hpp
- opm/autodiff/SimulatorSequentialBlackoil.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer_impl.hpp
- tests/test_multisegmentwells.cpp
Instead of the WellsManager guessing which wells are handled by other processes we now use the output of the load balancer to compute wells that are handled by other processes.
With the previous approach it was not possible to calculate this information correctly. Wells with only one completion next to the border of the processes' partition were represented on multiple processes. In addition wells that the eclipse schedule section defined with completions on non-active cells in sequential runs were not at all calculated in parallel runs.
With the new approach the CpGrid::loadBalance routine returns the set names of wells that are not handled by this process when setting up the simulation. This information is then used throughout the simulation.
This PR needs OPM/opm-core#1062 and …
> Use names of defunct wells from loadbalancer for wellsmanager

- opm/autodiff/BlackoilSolventModel_impl.hpp
Updated solvent model similar as in #825
Store rsSat and rvSat in simulator container for output.
Fixes issue #831
> BUGFIX. Store RsSat and RvSat in simulator container also in the Solvent model

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
Output well rates for all present phases, not just for three phase flow.
Not sure if there's a reason this was done in the first place, but the patch seems to work well for my two phase case.
> Output well rates for present phases

- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
Discovered by warnings from recent clang.
Trivial change, intend to self-merge when green.
> Do not move when it would disable copy elision.

- opm/autodiff/SimulatorBase_impl.hpp
Previously, for all steps zero was reported. With this commit
we set these numbers in the SimulatorReport and now they end
up correctly in step_timings.txt
> Correct number of (nonlineat) iterations/linearizations in step_timing.txt

- opm/simulators/thresholdPressures.hpp
most of these patches should be pretty harmless. The exception is the first patch which uses the phase pressure instead of the reference pressure to calculate the phase densities.
Norne and "Model 2" both seem to work and there were no obvious performance regressions...
> Default threshold pressure fixes

- opm/autodiff/SimulatorBase_impl.hpp
if the paramter use_TUNING=true, the adaptive time-stepper will
initialize with relevant values from the TUNING keywords.
Default is set to false. So this should not change the behavior of the current simulations. 
Depends on OPM/opm-core#1076
> Add an option for using values from TUNING in the timestepping.

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/MultisegmentWells.cpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/MultisegmentWells_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellHelpers.hpp
- opm/simulators/ParallelFileMerger.hpp
- opm/simulators/WellSwitchingLogger.cpp
- opm/simulators/WellSwitchingLogger.hpp
- tests/test_multisegmentwells.cpp
- tests/test_wellswitchlogger.cpp
Before this PR logging was done  regardless whether it was a sequential or a parallel run. Leading to  multiple processes logging simultaneously to the same file and causing message loss.
This PR fixes this in the following ways:
- If possible log only on one process.That is the case if all processes have the same information.
- Gather all messages about well switching on a root process and log there. (This might cost us some runtime, though)
- To prevent losses and surprises (if the above does either not suffice or we missed some parts): Each process now logs to its own file and after the simulation is finished the log of non-root processes are 
append to the default log files.
Closes #830 in most parts. One exception is the logging within OPM_THROW which will still happen on all …
> Fix parallel output

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/MultisegmentWells.cpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/MultisegmentWells_impl.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/simulators/WellSwitchingLogger.hpp
That version does not provide a default constructor for
CollectiveCommunication, Therefore we now use
MPIHelper::getCollectiveCommunication() for the default
constructor argument.
Discovered by build error in jenkins. http://80.240.129.131:8080/job/opm-simulators/139
> Make WellSwitchingLogger work with DUNE 2.3

- opm/autodiff/BlackoilModelEbos.hpp
"if necessary" means that the solution has changed (which is the case
iff the linear solver needs to do some work...
On my machine the time required to solve the Norne deck went down from 1022.59 seconds to 993 seconds. Note that this there is some additional performance to be gained if the linearization is "short circuted", but that is also quite a bit more work...
> flow_ebos: only invalidate the intensive quantities after an iteration if necessary

- opm/simulators/ParallelFileMerger.hpp
This is currently still happening due to the implementation of OPM_THROW whenever the linear solver does not converge. This happens quite often and we might not want to get overwhelmed by the issue tracker.
> Do not refer users to issue tracker if multiple procs log.

- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
All ranks were still writing to step_timing.txt at the same time.
This made it unusable for parallel runs. With this commit only
one processes writes to this file.
> Let only one rank write to step_timing.txt

- opm/autodiff/Compat.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
- opm/polymer/SimulatorPolymer.cpp
this merges the latest master version and mobs up afterward in order to make flow_ebos compatible with the latest master versions of the other OPM modules.
once again, the culprit for the build breakage was an API change in opm-output. (which I think was a change for the better, BTW.) I suppose this means that the frankenstein branch should be merged soon after the release in order to avoid to continue breaking the flow_ebos build twice a week.
> Frankenstein merge master v4

- examples/sim_simple.cpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/polymer/SimulatorCompressiblePolymer.cpp
- opm/polymer/SimulatorPolymer.cpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- tests/test_boprops_ad.cpp
- tests/test_multisegmentwells.cpp
- tests/test_rateconverter.cpp
- tests/test_solventprops_ad.cpp
- tests/test_welldensitysegmented.cpp
the one which is in opm-parser is now a drop-in replacement.
see OPM/opm-parser#936 for details.
> adapt to the removal of the unit system of opm-core

- opm/autodiff/BlackoilDetails.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
note that I don't know if these changes are semantically correct (I
doubt it), but this patch fixes the valgrind complaints I saw for
SPE9_CP and on Norne.
Also, this makes the timing of flow_ebos for SPE9 determinisic between
runs: without this, I got some random time steps fail in a given run
and in the next run a completely different set of timesteps
failed. Since this was on the same same machine, without any
recompiles and no changes to the deck or any other input parameters, I
initially attributed the behavior to cosmic rays ;)
@totto82: could you have a thorough look on this?
> frankenstein: fix some valgrind complaints

- opm/autodiff/FlowMain.hpp
With this PR, MESSAGES keyword is supported now. Depends on https://github.com/OPM/opm-parser/pull/921 and https://github.com/OPM/opm-common/pull/173
> support MESSAGES keyword.

- opm/autodiff/FlowMain.hpp
PR #820 was merged too quickly, as it was incompatible with the shared_ptr purge, and I forgot to re-run the tests before merging.
I will self-merge this right away to fix the compile breakage.
> Compile fix

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationUtilities.cpp
- opm/autodiff/NewtonIterationUtilities.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This addresses #824, and also ensures only the first rank writes log messages.
Requires OPM/opm-common#185 (but not vice versa).
Related to OPM/opm-core#1090, but they can be merged independently.
> Convergence failure classification, fix for parallel logging

- opm/autodiff/Compat.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
A downstream change (and actual fix, this was always broken) for https://github.com/OPM/opm-output/pull/98
@totto82 Please help me test this.
> WIP: Output data wells sans vectors

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
Normal meaning SWAT, PRESSURE, RS etc.
Extra meaning KR, VISC etc. as asked for in RPTRST.
Due to some error previously, we no longer actually passed the extra data to the output facility. Maybe a rebasing bug, in any case discovered by compiler warnings (unused argument).
I believe this should be the last PR for the release!
> Bugfix: pass both normal and extra data to output.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelEnums.hpp
This weak enum is really just an alias for four other constants which in
turn alias another enum. Since they're mostly used for indexing they're
relaxed to constexpr ints.
> Remove weak enum Opm::Phase; replace with constexpr

- jenkins/run-polymer.sh
- jenkins/run-spe.sh
This replaces the use of the compare_eclipse.py in integration tests with compareECL from opm-output.
The results are identical, except for the average relative deviation. The python script has a bug; it replaces (small) negative values with zeros in the data, but does not do the same for the reference. Thus you end up with a relative error of 1 for all these cells, and this significantly affects the average.
> Use compareECL in integration tests

- opm/autodiff/FlowMain.hpp
the reason for this is that otherwise there's a chicken-and-egg
problem: exceptions which are thrown before the logging system has
been initialized -- most prominently while parsing the deck -- cause
the simulator to silently abort without any user notification which
can be very confusing. On the other hand, initializing the logging
system requires a fully initialized EclipseState object,
i.e. currently to initialze the logging system the deck must be parsed
and in order to print the exceptions thrown while parsing the deck one
needs the logging system...
> FlowMain: use std::cout to print exceptions to the terminal

- opm/autodiff/DuneMatrix.hpp
One of the variables now has a trailing underline. With this PR we can use DUNE 2.5
> Cater for variable name change in BCRSMatrix of DUNE 2.5

- opm/autodiff/BlackoilModelEbos.hpp
this is required once OPM/ewoms#85 goes in.
> adapt to the rename of "applications/ebos" to "ebos" inside eWoms

- opm/simulators/ParallelFileMerger.hpp
The regex we are using might also consider a file named bla.2.blub.
In that case it is not nice to throw an exception. Instead we print
a message to std::cerr.
Closes #897
> Do not throw for unrecognized file when merging log files.

- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Previously, the eclipseGrid used by EclipseWriter was constructed from
the one in the EclipseState with the current CpGrid. Unfortunately the
latter was the distributed version resembling only the local part that
the processor works on. Therefore the information about the active cells
was wrong when writing results (which raised an exception in the writer).
With this commit we construct the EclipseWriter before distributing the grid
and use this writer later on in the OutputWriter.
Closes #892
> Fix using local active cells for writing eclipse files in parallel.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
When the targets like, BHP or WRAT or ORAT, we are able to set the `WellState` to match the target value. As a result, we can get almost always zero residual for the well control equations, which is also why we do not care much about this residual and even not outputting them. 
When come to some types of combined control, like RESV, LRAT, REIN, VREP, and so on, we can not set the `WellState` based on the targets, then we get some non-zero residuals. The current tolerance is set to be `barsa`, which is 1e5, make the checking not working actually. 
With this PR, we set the tolerance for 1.e-7 by default and also we output the evolution of the residual of the well control equations. 
It is tested on Norne, it does not change the well curves. It reduced the non-linear iteration and linear …
> checking the residual for the well control equations.

- CMakeLists_files.cmake
some fun with the build system: binaries that are supposed to be installed need to be added to PROGRAM_SOURCE_FILES in addition to EXAMPLE_SOURCE_FILES.  I guess I picked the wrong template (e.g. `flow_multisegment`) when I originally added `flow_ebos`. This hopefully fixes the `make install` problems reported by @nairr in #990.
> add flow_ebos to the programs which are going to be installed

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
Implements FIP for flow_ebos
Known issues
1) Not tested for 2p and in parallel. 
2) Original FIP is calculated after the first time step instead of before. 
@babrodtk There is slight mismatch between the FIP calculated with flow_ebos and flow. Could you test this PR and judge whether the mismatch is acceptable or not. 
When this PR is merged. Flow and flow_ebos is supposed to have the same ecl output capabilities.
> Frankenstein fip output

- opm/autodiff/BlackoilModelEbos.hpp
mainly, the "linsolver_" attribute is called "istlSolver_" in the
BlackoilModelEbos class. Also, this problem possibly only occured if
MPI was enabled...
> flow_ebos: fix the build

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/StandardWellsDense.hpp
1. restrict pressure changes. Set default to 1.0 (this also effects flow)
2. change default number of linear iterations to 150
3. tell stabilized newton that the residual oscillates even if it oscillates in
only one phase (this also effects flow)
4. avoid problems related to division on small numbers
Tested on SPE9, norne and Model 2. 
Note that number of non-linear and linear iterations is not counted if not converged. So even if the number of linear and non-linear iterations increases in the table below, this does not mean that the actual number of non-linear and linear iterations increases. 
| |SPE9|SPE9 this PR|Norne |Norne this PR| Model 2 | Model 2 this PR |
|-|-|-|-|-|-|-|
|Problems| 3 |0 | 10 | 4 | 88 |29|  
|Linear #|1305|1340|24239|25356|47245|50576|
|Non lin. …
> Improvments in convergence for flow_ebos

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
as usual for such errors, this was found using valgrind.
since this is pretty obviously mistake, I'll self merge.
> flow_ebos: fix a memory error in the fluid in place code

- CMakeLists.txt
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
this time, there were some (rather simple) conflicts due to rename of `flow` to `flow_legacy` in master.
> Frankenstein merge master v11

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Fixes spelling fallout introduced in #900
> Fix spelling in warning about unhandled parallel ouput.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
There is already a generic one with the Grid implementation
being the template parameter in the header file. The other
implementation using UnstructuredGrid does exactly the same.
Therefore we remove it with this commit.
> Removed second implementation of matlab output.

- opm/autodiff/BlackoilSolventState.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Silencing a few warnings.
The warnings related to shadowing global declaration of `Oil`, `Water` and `Gas` in `BlackoilModelEnums.hpp` remains, and also the shadowing of global declaration of `M`, `V` and `DataBlock` through `BlackoilModeBase_impl.hpp`.
> a few warning fixing.

- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This PR further aligns parallel output with the one done in a serial. Previously outputting data in addition to the cell data registered with in `SimulationDataContainer` was not possible in a parallel run. Now we use the `data::Solution` map when gathering data. As this also gets the user requested cell data, we output this in parallel now, too.
Norne seems to run fine. Will test with Model 2 also.
> Allow output for user requested data in parallel runs.

- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/NonlinearSolver_impl.hpp
Make sure flow in Frankenstein and flow in master uses the same default
values
This PR revert changes effecting flow that was merged in #916. I plan to add these changes to #880 instead. In this way the results and performance of flow stays unchanged when Frankenstein is merged into master.
> Revert som changes in default values

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/MultisegmentWells.cpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/MultisegmentWells_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWellsSolvent.hpp
- opm/autodiff/StandardWellsSolvent_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- tests/test_multisegmentwells.cpp
The updating of the well production targets within a group is designed based on our current way in handling schedule and well control, which means the WellsManager is always rebuilt at the beginning of the time step. 
The wells switch to group control when they violate the targets provided by the group control. 
When we need to update the well targets or we just update the well targets, we do not consider the current solution is converged. 
Updating targets during the time step is something new to the simulators. 
The wells are either under `individual control` due to their own limits or under `group control` under the targets provided through group control. They always begin with `individual control`, then switch to `group control` when they violate the group targets. 
The following two …
> group control_updating well production targets within a group

- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer_impl.hpp
This fixes a bug introduced when `Opm::Parser::parseFile()` started returning `Deck` directly instead of shared pointers. Basically,
```C++
*deck = ...
```
is always an error for a default-constructed shared (or unique) pointer.
> Do not assign to dereferenced null pointers.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/StandardWellsDense.hpp
This bug was introduced by unification of the linear solvers due to a throw for non-convergent solves. 
This PR also fixed the applyscaleadd method in the overloaded linear operator.
> Bug fix for reusing cached intensive quantities.

- opm/autodiff/ParallelDebugOutput.hpp
This PR simply removes an unused variable in ParallelDebugOutput.
> ParallelDebugOutput: remove unused variable and tabbing.

- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
With this PR we should finally write all the data of the wells in a parallel run.
Still, we might want to use data::Wells for the gathering in the future. Currently this code in limited to Blackoil.
> Read write perforation rates, pressure, phase reates, and control of wells.

- CMakeLists.txt
- compareECLFiles.cmake
- add ability to test simulators other than 'flow'
- remove old SPE1CASE2 test that only executed and did no comparison
- move the SPE1CASE1 flow_sequential test to an actual regression test
data update: https://github.com/OPM/opm-data/pull/142
please process ASAP to avoid duplicated work
> Redo existing tests

- compareECLFiles.cmake
- tests/run-parallel-regressionTest.sh
this compares the output of a serial and a parallel run for a simulation.
note this is just a draft. the tests all currently fail.the number of processes is hardcoded to 4 and my choice of models was just because those were the examples used earlier.
do you agree this is a good idea and if so, which models, which processes? 
in any case these models should pass i imagine. i have set very slack tolerances for the tests to point out that eventually we have differing values in integer fields. so i assume my understanding of the io is broken; i thought it was all based on serialization so ultimately we write the same data in the same order (up to rounding) from one process in either runs.
> add new regression test class: parallel

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
This (or some variant) should take care of https://github.com/OPM/opm-output/issues/145
> fixed: [WAT|OIL|GAS)KR are ratios and thus dimensionless

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/WellStateFullyImplicitBlackoilDense.hpp
this PR adds the capability to run twophase simulations with flow_ebos (so far only the oil-water case has been tested. everything else will likely fail but it shouldn't be too much effort to fix this if there is interest in it.)
@totto82 verified that the results for flow_ebos and flow_legacy (and maybe Eclipse) are identical for the twophase version SPE-1 which is in opm-data and for the Brugge case. Also, model 2 and Norne both are unaffected when it comes to the results and to performance.
Be aware that this PR also requires changes in opm-material and ewoms.
> Implement two phase blackoil

- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/WellStateFullyImplicitBlackoilDense.hpp
the compiler suggested braces around the conditions, and by look of
it, it was right: these asserts most likely want express that only the
threephase case or the twophase case without gas are handled...
I stumbled over this while doing #957.
> StandardWellsDense: fix two assertations

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilPressureModel.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- opm/simulators/WellSwitchingLogger.cpp
- opm/simulators/WellSwitchingLogger.hpp
this is the compagnion PR to OPM/opm-core#1112. I've made sure that everything still compiles and that no additional unit tests fail. I've also checked that `flow_legacy` and `flow_ebos` work as expected for the Norne deck:
```
==> flow_ebos.log <==
[...]
Total time taken (seconds):   761.545
Solver time (seconds):        745.516
Assembly time (seconds):     355.981
Linear solve time (seconds): 319.673
Update time time (seconds):  2.69076
Output write time (seconds): 16.9406
Overall Linearizations:       1964
Overall Newton Iterations:    1621
Overall Linear Iterations:    24638
==> flow_legacy.log <==
[...]
Total time taken (seconds):   1259.69
Solver time (seconds):        1253.5
Assembly time (seconds):     701.505
Linear solve time (seconds): 352.299
Update time time (seconds): …
```
> extend and clean up the SimulatorReport

- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
Seperating the updateWellStateWithTarget from updateWellControls, will update the controls when any of the control constraints gets broken.
The reason is that the updated (once) well control can still break some of the other constraints. We need to choose one control to make sure all the constraints are honored.
It will be more important for the cases that the wells has more different controls (can be from the group controls) at the same time, and potentially it will reduce the number of the Newton iterations. 
A preliminary test show it does not change the results of Norne while reduces the iterations a little bit. 
Master branch (from the PR #906 )
```
90163 Total time taken (seconds):  2107.52
90164 Solver time (seconds):       2096.43
90165 Overall Linearizations:      1980
90166 …
```
> [WIP] making the updateWellControls an iterative process for StandardWells

- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
Reverts OPM/opm-simulators#965
Sorry. The PR is verified to be a bad proposal. We should revert it.
> Revert "changing polymer production concentration to be the grid block concnetration."

- CMakeLists_files.cmake
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
- opm/autodiff/SimulatorIncompTwophaseAd.cpp
- opm/polymer/SimulatorCompressiblePolymer.cpp
- opm/polymer/SimulatorPolymer.cpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp
- opm/simulators/SimulatorCompressibleTwophase.cpp
- opm/simulators/SimulatorIncompTwophase.cpp
- opm/simulators/vtk/writeVtkData.cpp
- opm/simulators/vtk/writeVtkData.hpp
This moves the writeVtkData() function from opm-output to here, and resurrects the UnstructuredGrid version that was commented out.
The first commit just cleans up whitespace in the file list.
> Re-add vtk writing functionality

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/GridInit.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
this patch also includes code to make FlowMainEbos more autonomous (i.e. it does not derive from FlowMainBase anymore). this allows more flexibility how and what stuff gets created. Note that this implies that parts of #947 are included here (in particular the grid initialization).
this is the companion PR for OPM/ewoms#102.
> flow_ebos: do not use (smart) pointers for opm-parser objects anymore

- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
this makes use of the `resetLocale()` function introduced by OPM/opm-common#221.
> flow*: reset the locale settings on startup

- opm/autodiff/StandardWellsDense.hpp
this wasn't noticed earlier because it only bites in the water-oil
case and only if NDEBUG is not defined.
> StandardWellsDense: fix assert for the 2p case

- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/StandardWellsSolvent.hpp
- opm/autodiff/StandardWellsSolvent_impl.hpp
- opm/autodiff/WellDensitySegmented.cpp
- opm/autodiff/WellDensitySegmented.hpp
This PR copies computeWellFlux(...) and Opm::WellDensitySegmented::computeConnectionDensities(...)
and removes solvent from the gas phase before it is multiplied with the rv values. It is possible to avoid some of the copying, but that would require interface changes that effects all other well models. I plan to revisit the well model for the solvent model when implementing the solvent model using Evaluation class. 
In addition it fixes a bug in the relperm manipulation by removing the special treatment for the no Oil situation in the gas relperm. 
Tested on SPE5 and Model2
> Fixes in solvent model related to handling vapoil in the well model

- opm/autodiff/FlowMainEbos.hpp
I probably did not see this warning when testing f7910af7d70 because I'm currently flooded by deprecation warnings stemming from Eigen. (these warnings are caused because I use Ubuntu 16.04 and an
old version of Eigen is cloned by the build system that is not system installed.)
@totto82: please merge if this fixes #976.
> FlowMainEbos: fix the output of the initial condition

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/StandardWellsDense.hpp
This is work done by @osae. 
1) changes dp_max_rel default to 0.2
2) introduces a dbhp_max_rel parameter to restrict the bhp update in the
updateWellState() (instead of using the dp_max_rel) Default is set to
1.0
3) Restrict rs and rv between 0 and the saturated value
4) Set rs and rv to zero for the water only cases
5) Guard against zero rs and rv when calculating the maximum allowed rs
and rv change.
Tested on Norne, Model 2 and Model 2.2
Number of problems for the different models with and without this fix
Case this PR master 
Norne       10       45
Model 2    21       78
Model 2.2 200   248
> Fixes in the Appelyard in updateState and updateWellState

- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
This (hopefully) fixes the issue with SPE1CASE2, in which the field total fluid in place is reported in the wrong units.
> Fixed missing unit conversion for total fluid in place

- opm/autodiff/NonlinearSolver_impl.hpp
This OPM_THROW was introduced lately and results in all processes
logging the failure. With this commit the message is logged only once.
> Only log messages about failed timesteps on one processes.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/VFPHelpers.hpp
- opm/autodiff/VFPInjProperties.cpp
- opm/autodiff/VFPInjProperties.hpp
- opm/autodiff/VFPProdProperties.cpp
- opm/autodiff/VFPProdProperties.hpp
Prepare for changing the size of the blocks by using template BVectors and
Evaluation. 
Shouldn't effect the simulators performance or results.
> Use templates to avoid hardcoded typedef

- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- opm/polymer/fullyimplicit/PolymerPropsAd.cpp
- opm/polymer/fullyimplicit/PolymerPropsAd.hpp
We corrected a bug in the polymer convection term and changed the formulation calculating the injection mobility (assuming polymer fully mixed in wellbore.)
The change basically only affects the results with non-fully mixed polymer. Good agreements are achieved for all the test examples we have and it is not well tested with shear calculation with non-fully mixed polymer (`omega != 1`, we include a suggestion in the PR, while not having an example to verify the suggestion.).
> fixing the calculation when polymer not fully mixed

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
In the current code the cache is always invalidated, with this PR it is only invalidated when
1) the solution is updated
2) the time step fails
depend on OPM/opm-core#1117
Tested on SPE9, norne and Model 2.
> Reuse cache revisited

- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
Removed well_s, which appears to me to be unused?
The line in question gave me compilation errors with the most recent Eigen release (complaining about operator+= being private, did not dig any further)
> Removed unused variable / compilation fix Eigen 3.3.1

- opm/autodiff/BlackoilModelEnums.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/BlackoilPropsAdInterface.hpp
- opm/autodiff/ImpesTPFAAD.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
- tests/test_boprops_ad.cpp
I consider the blackoil model enums to be pretty low level while the "FluidProperties" code is IMO quite high level. this, using the latter to define the former constitutes a layering violation IMO. note that the fix is to simply use the enums from opm-core directly.
> BlackoilModelEnums: don't use high-level classes

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/VFPInjProperties.cpp
- opm/autodiff/VFPInjProperties.hpp
- opm/autodiff/VFPProdProperties.cpp
- opm/autodiff/VFPProdProperties.hpp
- opm/autodiff/WellHelpers.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
this code mostly used the Eigen vectors as arrays anyway, so let's use `std::vector`.
also, this patch only "mostly eliminates" Eigen from from these parts of the code because the source files of the VFP code still use AutoDiffBlock; Unfortunately this cannot easily be changed because `flow_legacy` depends on these methods. (`flow_ebos` does not use the incriminating methods.)
> mostly eliminate Eigen in the FIP and VFP code

- opm/autodiff/StandardWellsDense.hpp
In that case `wells_manager.c_wells()` returns a null pointer
which made `updateListEconLimited` segfault. With this commit
we treat a null wells_struct as having zero wells.
With this this and #1001 opm-data/equilibrium at least runs
through in parallel. Results will be checked next.
> Make StandardWellsDense support cases with no wells.

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Up to now parallel runs aborted due to an exception with the message "FIP not yet implemented for MPI". With this commit we do the computation in parallel, too. And flow_ebos runs a bit longer in parallel ...
> Implement parallel fip total computation.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/NonlinearSolver_impl.hpp
in C++ references may be assumed to be non-null. thanks to @atgeirr for pointing this out.
(note: this PR also fixes a harmless sign comparison warning in the non-linear solver.)
> avoid relying on undefined behaviour

- opm/autodiff/SimulatorBase_impl.hpp
This was (accidentally?) introduced in c880efae5be (labelled
"mostly eliminate Eigen in the FIP and VFP code"). As it is neither
present in flow_ebos nor in flow_mpi and was previously removed in
ccec17f8 (labelled "Fixed missing unit conversion for total fluid in place")
I assume that this is a bug.
> Fix unit conversion of fip totals (pav) again.

- opm/autodiff/StandardWells_impl.hpp
Dense case was handled in PR #1002. I was not aware that the same
regression was in the legacy code. wells_manager.c_wells() might return
a null pointer if there are no wells in the domain of a process. In this case
we treat it as having zero wells.
> Make StandardWells support cases with no wells.

- opm/autodiff/BlackoilModelEbos.hpp
it was not used for real for a while anyway.
> BlackoilModelEbos: remove the last traces of "SolutionState"

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
the most significant change is that only a "PhaseUsage" object must be passed to its constructor instead of a full "fluid object". also, the pointers to the vector of "active" phases has been converted into a full object. (this helps to avoid potential use-after-free errors.)
> small improvements to StandardWellsDense

- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
If it is not requested then output_dir is not created and boost
will throw an exception if we try to read from a non existing
directory.
> Only try to merge files from a parallel run if ouptput requested.

- opm/autodiff/FlowMain.hpp
This allows us to run some cases that apparently are generated without various DIMS keywords. I think it is probably quite safe, in the sense that the parser is not likely to fail reading such decks, become confused etc.
> Warn instead of throw when missing DIMS keyword.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
Implementing the group controls for flow_ebos. VREP is a little special and possibly need to handle with other issues together, like OPM/opm-simulators#1011.  Will be proposed in another PR. 
This PR calculate the well potentials, and distribute the group target within different wells dynamically. GEFAC is also handled. The testing results are fine. 
This PR needs OPM/opm-core#1134 to get correct results, while not dependent on that PR in term of compiling.
> Group controls for flow_ebos

- jenkins/build.sh
- tests/update_helper.sh
- tests/update_reference_data.sh
This PR adds a couple of scripts that aid in updating the opm-data repository. 
The script update_helper.sh can be run as 
```
tests/update_helper.sh -t <build-threads> -d <path-to-opm-data-checkout>
```
and is based on the script by @akva2 
The script then checks out fresh copies of the required repositories, builds, and finally prints out the commands you can run to update opm-data with the newly generated reference data, and how to compare them with the script in opm-data (see OPM/opm-data#157 )
> Added script to update opm-data references

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
The initial solution in ebos and  in flowEbos are different in cases where
SWATINIT is present. Pass the initial solution and recalculate the
intensive quantities to make sure that the flowEbos initial solution is
used.
> BUGFIX Pass solution from flowEbos to ebos initially

- compareECLFiles.cmake
As part of a (quite minor) reorganisation of the writing of restart files there are now two failing regression tests when running in parallel: https://ci.opm-project.org/job/opm-simulators-PR-builder/215/testReport/
At least for the SPE_9 case I am quite certain that problem is as follows:
Previously the values had wrong units, after the units have been corrected to the numerical values are ~10^5 larger, and the fixed absolute deviation is now too small, giving a false positive.
In this PR the tolerances are increased with a factor 10.
> Increased tolerances when running parallel tests.

- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp
Followup to: https://github.com/OPM/opm-output/pull/152
Previously the list of keywords to load from a restart file was hardcoded in the opm-output, now the `load_from_restart_file( )` takes a map of keys to load. With the current follow-up patch the hardcoding has just been moved into the opm-simulator.
The PR also contains some minor refactorings:
1. The `EclipseWriter` class has been renamed `EclipseIO`.
2. The functionality to load restart information is a method on the `EclipseIO` class.
In addition a namespace `RestartIO{ ... }` with functions `save()` and `load( )` has been created as part of:  https://github.com/OPM/opm-output/pull/152 - using these functions client scope (i.e. `flow_xxx`) can save and load restart files completely bypassing the IO configuration from the deck / …
> Passing keys to the restart load function.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
This PR basically implements the VREP group control for the StandardWellsDense.
The test results from my own SPE9 based group control examples are pretty good. 
It requires the PRs OPM/opm-simulators#1037 and OPM/opm-core#1137 to get the correct result.
> Group ebos vrep

- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
- tests/test_multisegmentwells.cpp
this information is already part of the EclipseState. The reason why this should IMO be avoided is that this enforces an implementation detail (ordering of the permeability matrices) of the simulator on the well model. If this needs to be done for performance reasons, IMO it would be smarter to pass an array of matrices, instead of passing a raw array of doubles.  I doubt that this is necessary, though: completing the full Norne deck takes about 0.25 seconds longer on my machine, that's substantially less than 0.1% of the total runtime.
> do not explicitly pass the permeability to the well model anymore

- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
seems like #1042 was a bit premature. sorry for this. this patch also does not `std::move` the  `unique_ptr` for `eclIO` anymore. (IMO, that's a semantically quite strange thing to do.)
> fix the build

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
Causes a crash in opm-output, as it seems to expect data has been correctly sized by caller. Ref https://github.com/OPM/opm-output/pull/162
> fixed: calculate FIP in substeps for summary output

- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilPressureModel.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
- opm/autodiff/SimulatorIncompTwophaseAd.cpp
- opm/polymer/SimulatorCompressiblePolymer.cpp
- opm/polymer/SimulatorPolymer.cpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp
- opm/simulators/SimulatorCompressibleTwophase.cpp
- opm/simulators/SimulatorIncompTwophase.cpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
- opm/simulators/timestepping/SimulatorTimer.cpp
- tests/test_singlecellsolves.cpp
Since this is quite trivial but required to restore the build, I'll speed-self-merge (new term!) right away.
(Have run local compile and tests only.)
> Change include paths for moved headers.

- opm/autodiff/BlackoilModelParameters.cpp
Some tests require smaller `tolerance_wells` when running with flow_ebos to make the well curves convergent. I specifies with 1.e-4, which is a tenth of the defaulted one. 
It helps the test get the converged results. In the below link, the blue line is the result from flow_ebos with default tolerance_wells, the yellow line is the result with flow_ebos with smaller tolerance_wells from this PR.
https://www.dropbox.com/s/4am5g3rn1scgolv/comparison_with_different_tolerance.png?dl=0
However, it also increases the running time of Norne by 1%-2%. 
Norne with current master branch. 
```
89350 Total time taken (seconds):   1482.55
89351 Solver time (seconds):        1457.5
89352  Assembly time (seconds):     797.135
89353  Linear solve time (seconds): 566.846
89354  Update time (seconds): …
```
> [Discussion] using smaller tolerance_wells for StandardWellsDense

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This fixes spelling of auxiliary, which I think by mistake has been spelled auxillary (double l) in opm-output and also opm-simulators. 
This PR requires that the sibling PR in opm-simulators is also merged. 
Sibling PR is here: OPM/opm-output#165
> Renamed auxillary to auxiliary

- opm/autodiff/FlowMain.hpp
The sole purpose of this PR is to trigger the functionality to update reference data; it must be merged though to get a valid sha in the opm-data commit messages.
> White spcae change.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This enables output of bubble point and dew point pressures to a restart file. 
This PR requires that OPM/opm-material#204 is merged.
This will fail with an exception if we are unable to find the dew point / bubble point pressure. See 
opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp:571
and
opm/material/fluidsystems/blackoilpvt/LiveOilPvt.hpp:540
I'm not entirely sure how to best handle this situation, and I'm open to ideas.
> Added output of dew and bubble point pressures

- tests/analyze_ecl_failure.sh
- tests/analyze_summary_failure.sh
- tests/run-init-regressionTest.sh
- tests/run-parallel-regressionTest.sh
- tests/run-regressionTest.sh
- tests/run-restart-regressionTest.sh
This adds a script that performs more analysis on a failed summary regression test failure.
It will
- print number of failed keywords.
- Print number of levels each keyword failed at.
- Print maximum deviations for each keyword. 
In particular this is useful as it will check that "old" keywords still pass the test for failures caused by addition of new keyword(s).
The maximum deviations will measure the severity of failures on a per-field basis for human considerations.
Equivalent functionality for the other comparison types will follow but let's shake down the monkeys for this one first.
@alfbr this should cover both cases we discussed on Tuesday.
Requires https://github.com/OPM/opm-output/pull/161
> [WIP] Perform more analysis of summary regression test failures

- opm/autodiff/fastSparseOperations.hpp
This enables compiling with Eigen 3.3, since they changed the use of Index. See
http://eigen.tuxfamily.org/index.php?title=3.3#Index_typedef
for reference
> This enables compiling with Eigen 3.3

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This addresses issue #1061 by supporting the E300 keywords VWAT VOIL VGAS.
> Updated so that VOIL/VGAS/VWAT are supported keywords

- opm/autodiff/fastSparseOperations.hpp
I think this is a better approach to achieve what was done in #1070 . If the version numbers are not set correctly the code will fail to compile which is not the case with the approach proposed here.
> Revert PR 1070 to use auto instead of preprocessor statements.

- CMakeLists_files.cmake
- opm/autodiff/Compat.cpp
- opm/autodiff/Compat.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/WellStateFullyImplicitBlackoilDense.hpp
This replaces #1071 and contains the following fix:
- the well state object is properly initialized from restart data.
It should make no difference in any non-restart run, and have no effect on performance.
> Towards fixing restart for flow_ebos

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This enables writing the internal flow_ebos simulator state to the restart file for the initial conditions. 
This essentially dumps the internal state of the simulator before starting the simulation instead of dumping the initial conditions used to construct the simulator.
For the Norne case, it addes missing variables for the first report step (e.g., such as GAS_KR, WAT_KR, ...)
It also changes some of the existing output *for the first output step* (all subsequent steps are identical):
- 330 cells have a slightly different PRESSURE (e.g., 0.2764*4662*E+03 vs 0.2764*7656*E+03. I've been unable to track down the cause of this difference. Any ideas?
- The same cells appear to also have a different RS (e.g., 0.1*0677000*E+03 vs 0.1*2498261*E+03) and RV (e.g., 0.627*09332*E-04 vs …
> Added writing initial timestep data to restart

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This fixes (for me) the error 
```
Error: Program threw an exception: Wrongly sized data array passed to output for keyword GIPG, size=0, expected=44431.
```
on Norne which just appeared this morning.
It simply moves the FIP-computation to before output to file.
> Moved computation of FIP before output to summary

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
I cannot see why log should be required in the if-test, and I think this is a bug which would not output PDPB if log is set to false
> Fixed apparent bug in outputting PDPB

- opm/autodiff/Compat.cpp
- opm/autodiff/Compat.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
This replaces #1079. The description in that PR still applies (with minor modifications):
Together with OPM/opm-output#172, this makes perfect restarting (in the sense of making a restarted simulator run reproduce the exact same results as the original run) possible for the SPE1CASE2(_RESTART).DATA test case.
It adds the following:
- Read and write the adaptive timestepper's suggested next time step (through a new field "OPMEXTRA"), this requires OPM/opm-output#172.
- Add a feature to preserve SI units (avoiding unit conversions) and write data as doubles. This is triggered by setting `restart_double_si=true` (default is `false`) on the command line or in the parameter file. This only requires existing opm-output features.
We know that for perfect restarting of other cases we will (at …
> Improve restarting

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
It provides a strategy to reset the zero thp value when no thp control is involved anymore.
It should not change any running results of all the current examples, while trying to avoid outputting distracting thp values. 
Compared with OPM/opm-core#1143, it provides a strategy to recover the zero THP output when no THP control/limit is involved anymore.  Maybe it should just go ahead to the end of `init()` function.
> when no THP control/limit, thp value will be set to zero.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Followup to: https://github.com/OPM/opm-output/pull/174
> Mark OPMEXTRA as not required restart data.

- opm/autodiff/BlackoilModelEbos.hpp
Previously entries attached to cells that are present on multiply processes were acumulated several times.
This is currently untested since the parallel output of flow_ebos is broken. Therefore marked as work in progress
> Switch off non-owner entries during accumulation in getConvergence

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Most importantly, this makes the code that computes the field totals also consider compressibility, so that for SPE1 (where there's only one region), the field totals are now the same as the region numbers.
this PR fixes a few other issues as well: the numbers for water only regions should now be meaningful (the wrong pore volume was used to in the denominator, the numbers for e.g. region 8 in Norne are now much closer to those of E100), the `computeFluidInPlace()` method of `BlackoilModelEbos` is cleaned up, the FIP is reported the first time before the first report step and the parallel and the non-parallel code paths to compute the field totals are unified. I've also verified that the results for parallel and sequential runs are identical for Norne and SPE1.
> Fixes for the fluid in place code

- opm/autodiff/StandardWellsDense_impl.hpp
Using rs rv from grid cells when calculating the volume ratio during `computeWellFlux()` for `StandardWellsDense`.
Using the old form makes it easy to get zero `d` and causes `NaN` later, which happens during well potential calculation with Model 2.2. 
So far I have not seen it improves or breaks anything else compared with the mater branch.  For norne, it makes `flow_ebos` slightly slower. 
@totto82 , could you please suggest whether this is a correct thing to do or not?
> [Discussion] using rs rv from grid cells when calculating the volume ratio

- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
- opm/simulators/timestepping/TimeStepControl.cpp
1) The time step after an event can either be set using
timestep_in_days_after_event 
or using the TUNING keyword in the deck.
2) A timestep control pid+newtoniteration that adjust the timestep based on number of Newton iterations is made available. 
Default is to not use any of this. So this should not effect any results.
> Set timesteps after events

- jenkins/run-norne.sh
sometimes it is easier to compare without the extra data in the graphs
@atgeirr as requested
> added: generate a plot without ecl reference for norne runs

- opm/autodiff/ISTLSolver.hpp
In upstream they expect to be used with FieldMatrix as the block type only. Thus it it is impossible to use AMG with a direct coarse solver within OPM. With this patch it would be possible if we did not use field type float.
This is one part of the fix needed for #962. The other would be to deactivate using float.
> Specialize direct solver for Dune::MatrixBlock.

- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This increases the lifespan of restart files in the sense that old restart files (from before OPMEXTRA was added) can now be used for restarting (although initial timestep will often be different from the original run, since that is what is saved in OPMEXTRA).
I have tested that this works correctly using old and new restart data for the SPE1CASE2(_RESTART) case in opm-data.
@dr-robertk Hope this makes things easier for your testing!
> Allow restarting without OPMEXTRA field in restart file.

- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- tests/run-init-regressionTest.sh
- tests/run-parallel-regressionTest.sh
- tests/run-regressionTest.sh
- tests/run-restart-regressionTest.sh
This changes the default output directory of flow_legacy and flow_ebos. Currently we default to the current directory, with this PR we will default to the directory where the data deck is found. According to @nairr and @alfbr this is what engineers would expect. Behaviour when specifying output_dir is as before: everything is written to the specified directory.
At the same time, I have taken the opportunity to clean up a little. One minor change is that before, some things would default to be written to the `output` directory instead of the current dir. This has now been unified.
There might be Jenkins or Travis failures because of this. I have only fixed the in-module tests. Hopefully @akva2 can assist if necessary.
> Change default output dir

- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
Using wellSurfaceVolumeFraction() (Q_p / (Q_w + Q_o + Q_g) ) instead of wellVolumeFraction() and wellVolumeFractionScaled() in a few places, especially the phase composition inside the wellbore. 
Also adjust the getQs a little bit to avoid using `comp_frac` for producers. 
Similar to OPM/opm-simulators#1083, thorough test will be required before merging.  Have not seen any simulation is broken and it improves the running of Model 2.2 in my testing branch, while it needs to be verified again. 
And, the new function is a relatively expensive function to call, should we introduce more variables (there are quite a few already) in StandardWellsDense or we just call it as a function everytime?
> [WIP] using surface volume fraction instead of wellVolumeFraction() and wellVolumeFractionScaled() in a few places

- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/RedistributeDataHandles.hpp
Before this PR the output writer was  never initialized with the global grid in parallel. Therefore only the active cells of process 0 were honored as active cells. With this PR this is changed and at least the grid and the transmissibilties are writen for the whole domain.
Beware: Dynamic data is still somehow missing in parallel output for ebos.
Needs OPM/opm-grid#263
> Fix output writer setup

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
This PR is only targeted at output and should not effect the simulations at all. 
1) Fixes output of rs and rv for the free gas and free oil case, and the water only case. 
2) Makes the initial output of rs, rv, bo, bg, rho_o and rho_g Ecl compatible.
> Fix output of rs and rv. 

- opm/autodiff/BlackoilModelEbos.hpp
This used to be done in solveJacobianSystem(), but this method is only supposed to solve the linearized system of equations, not to modify it IMO.
I tested this patch with Norne: It did not change anything obvious.
> BlackoilModelEbos: apply the well residual in assemble()

- opm/autodiff/BlackoilDetails.hpp
- opm/autodiff/BlackoilModelEbos.hpp
Currently, all parallel DUNE grid store some cells in addition to interior cells. Therefore assuming that the global number of cells (i.e. the number of cells a sequential grid needs to cover the same whole domain with indentical cells) is not the sum of the number of cells of the local grid. Previously, the latter was used.
> [Ebos,bugfix] Correctly compute the global number of cells.

- opm/autodiff/BlackoilModelEbos.hpp
Both used cachedIntensiveQuantities unconditionally but for non-interior elements this method returns null pointers which get dereferenced. this PR resort to iterating over the grid and using the element context.
According to @andlaus this does not pose a performance regression or he owes me a beer. How about a check of the performance with Norne, @andlaus?
> Make update state  and getConvergence work for non interior elements

- compareECLFiles.cmake
- jenkins/run-norne.sh
- jenkins/run-spe.sh
- opm/autodiff/FlowMain.hpp
the results of `flow_legacy` and `flow_ebos` are not bit-wise identical. The same tests using `flow_ebos`  should to be added when re-organizing the unit tests the next time.
> make the unit tests to explicitly use flow_legacy instead of flow

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/WellSwitchingLogger.cpp
- opm/simulators/WellSwitchingLogger.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
This fixes a minor bug in output (cumulative times and iterations for substeps), makes "too many nonlinear iterations" a Problem, not an Error, and makes some formatting improvements while at it.
Screenshot below.
> Refined output to terminal and log

- opm/autodiff/GridInit.hpp
- opm/autodiff/ParallelDebugOutput.hpp
This PR enables the capability to compile flow_ebos with PolyhedralGrid and thus falling back to UnstructuredGrid. This is mainly for comparison and debugging.
> Allow to run flow_ebos with PolyhedralGrid (UnstructuredGrid)

- opm/autodiff/ISTLSolver.hpp
These are not aware whether they are parallel or not. Therefore the user should only specify a verbose verbosity only on one rank. Otherwise the terminal output will be cluttered with similar messagesfrom all ranks.
With this commit we do this on the process responsible for terminal
output.
> Fix verbosity parameter used for parallel istl solvers.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
- tests/test_vfpproperties.cpp
- tests/test_welldensitysegmented.cpp
Compute relperms for each well completion based on saturation table ids
(satnums)
Depends on  OPM/opm-parser#1045, OPM/opm-core#1145 and OPM/opm-material#??? 
This PR together with its parents implements support for specifying saturation table numbers for completions. Improves Model 2.2. results significantly. 
Does not work in combination with hysteresis and end-point scaling. I want to add a warning for this, but where/how should I add this warning?
> Support for saturation table for each well completion

- CMakeLists_files.cmake
- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorIncompTwophaseAd.cpp
- opm/polymer/SimulatorCompressiblePolymer.cpp
- opm/polymer/SimulatorPolymer.cpp
- opm/simulators/SimulatorCompressibleTwophase.cpp
- opm/simulators/SimulatorIncompTwophase.cpp
- opm/simulators/ensureDirectoryExists.cpp
- opm/simulators/ensureDirectoryExists.hpp
This refactors the creation of directories, and should fix an issue reported by @dr-robertk in #1116.
The refactoring also should make it easy to replace the routine (possibly avoiding boost filesystem) later.
@dr-robertk please review this and check if this PR solves your problem.
> Refactor directory creation

- tests/update_reference_data.sh
Probably forgotten in the reorganization process. I hope this will fix Jenkins runs for #1084.
I intend to self-merge this when green.
> Fix data update directory for flow_sequential test.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/Compat.cpp
- opm/autodiff/Compat.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
This requires OPM/opm-material#209 to be merged first. Writes hysteresis parameters to restart file, and reads them if restarting from existing simulation.
> Adds hysteresis output and input (for restarting)

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/polymer/SimulatorCompressiblePolymer.hpp
- opm/polymer/SimulatorPolymer.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
the performance summary at the end of a Norne run which are printed by `flow_ebos` now looks like this on my machine:
```
Total time (seconds):         773.757
Solver time (seconds):        753.349
Assembly time (seconds):     377.218 (Failed: 23.537; 6.23965%)
Linear solve time (seconds): 352.022 (Failed: 23.2757; 6.61201%)
Update time (seconds):       16.3658 (Failed: 1.13149; 6.91375%)
Output write time (seconds): 22.5991
Overall Well Iterations:      870 (Failed: 35; 4.02299%)
Overall Linearizations:       2098 (Failed: 136; 6.48236%)
Overall Newton Iterations:    1756 (Failed: 136; 7.74487%)
Overall Linear Iterations:    26572 (Failed: 1786; 6.72136%)
```
for the flow_legacy family, nothing changes.
this PR depends on OPM/opm-core#1154.
> flow_ebos: print statistics about failed time steps

- compareECLFiles.cmake
or are these called integration tests? anyway, these are the tests which use the decks from opm-data. This should put flow_ebos testing on the same level as flow_legacy.
to succeed, OPM/opm-data#200 is required.
> add unit tests for flow_ebos analogous to flow_legacy

- CMakeLists.txt
`flow_ebos` should be now capable of doing everything that `flow_legacy` can and recently all testing seems to have been centered on `flow_ebos`. note that `flow_ebos` does not yet support some more
advanced/exotic features like MPI, solvents, polymer, etc., but neither does the plain `flow_legacy` binary. until `flow_ebos` supports these features, the specialized simulators thus continue to use the legacy code paths.
> make the default flow point to flow_ebos instead of flow_legacy

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/autodiff/WellStateFullyImplicitBlackoilDense.hpp
- tests/test_multisegmentwells.cpp
The PR includes mostly the following revisions
1. Moving the calculation of well potentials at the beginning of each `time step` instead of the end of previous `report step`, which is the better and more correct thing to do.
In the old way, we always use the well potentials from the end of the last `report step`. For many cases, it will be fine. The well potentials will be invalid when a new well is newly added, since we do not have this well yet in the last report step. 
And also, there are some decks, the size of the report step is pretty big, half year / 1 year. For some period, the well potentials will change significantly during the report step, updating the well potentials during the report step is also more desirable.  
When THP is involved, the well potentials are closely related …
> [WIP] Changes to improve the StandardWellsDense

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
This fixes another serious bug and makes SPE1 finally converge in parallel. Even though this fix is rather trivial it took me quite some find it. Somehow I was under the impression that we only compute values in the convergence check on interior elements. This is turned out not to be the case and explained why the nonlinear solver did not convergence even when I solved the linear systems exactly on one master process.
I finally changed my mind regarding who to compute the global sums and maxima and concur with @dr-robertk and @andlaus that we should do this using the grid information and standard algorithm. I included this change in this PR.
Would be nice if this would make into the release. Sequential results should remain unchanged.
> [bugfix,flow_ebos] Fix parallel convergence max

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
this is an alternative to #1145. IMO it is slightly better because it does not require an additional parameter for the `getRestartData()` method and also touches slightly fewer lines of code.
> only output the bubble and dew point pressures if they are available

- CMakeLists.txt
this allows to use `make flow` instead of `make flow_ebos flow` to build the stuff.
IMO this is just a convenience measure to make the build infinitesimally more bullet-proof and is thus not important enough to be included into the release.
> add 'flow_ebos' to the dependencies of the 'flow' target

- opm/autodiff/SimulatorBase_impl.hpp
This avoids assert() failures in Eigen for legacy flow on 2-phase cases (at least one tested case fails without this PR and succeeds with it).
> Fix bug in two-phase case.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This small change is sufficient to restore running the OLYMPIC benchmark case with flow_legacy. I will merge it once tested unless objections are raised.
> Only push non-empty data to output.

- CMakeLists.txt
got lost due to a bad conflict resolution in 7c4dfa784d6090874702a59ab76d7dbb4de873ce
@babrodtk (thanks for report!)
> fixed: re-add installation of the 'flow' symlink

- opm/autodiff/NewtonIterationBlackoilInterface.hpp
this prevents GCC-7's address sanitizer from complaining about a delete for a new of a different type. (i.e., the new is for the derived class, but if the destructor is non-virtual only the dtor of the base class is called if a pointer to the base class is deleted.)
finding this was quite some fun, mainly because it took a while to grasp what the issue was.
this should also go into the release branch.
> NewtonIterationBlackoilInterface: make its destructor virtual

- opm/autodiff/BlackoilTransportModel.hpp
Bug caused assert() failures for debug mode runs, which lead to test failures in debug mode. Also, the Norne case would throw due to missing data for output.
> Fix output of relative permeability for sequential model.

- opm/autodiff/FlowMainEbos.hpp
since flow_ebos is the new silverback simulator of the opm-simulators clan, it should itself as "flow"(the old silverback announces itself as "flow_legacy" already).
Also, some people seem to have been confused by the eWoms version and codename. Since this information only exhibits limited value IMO, let's remove it here.
> flow_ebos: update banner

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/MultisegmentWells_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellDensitySegmented.cpp
- opm/autodiff/WellDensitySegmented.hpp
- opm/autodiff/WellStateFullyImplicitBlackoilDense.hpp
- tests/test_welldensitysegmented.cpp
1) Pass TypeTag as template parameter instead of all the properties.
2) Let the code loop over number of equations /components instead of number of phases.
This should not effect any of the standard blackoil cases. 
Tested on Brugge (2p), norne and Model2_0. All gives the same convergence history.
> Prepare for 2p and  extended models.

- opm/autodiff/Compat.cpp
Depends on and fixes test failure due to OPM/opm-core#1162
> Don't output SSOL if no solvent

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
it was already almost unused (except for output). this may even imply a small performance improvement because the transmissibilities do not need to be calculated twice.
> flow_ebos: remove the legacy geologic properties object

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolver.hpp
This was previously deactivated because of the single precision support of flow_legacy and missing single-precision support for UMFPack. Whenever UMFPack was available there was no AMG for flow.
As flow_ebos does not use single precision this commit allows using amg at least for flow_ebos even in the presence of UMFpack. For flow_legacy everything stays the same.
> Allow usage of AMG if flow_ebos is used and UMFPack is available.

- opm/autodiff/BlackoilSolventModel_impl.hpp
This prevent SEGFAULT if you try to run a standard blackoil case using flow_solvent. Not many do I think, so I don't think this is very critical. But it is good to have the possibility when testing.
> BUGFIX Don't try to compute effective properties for FIP if no solvent

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/ThreadHandle.hpp
1) fix MPI deadlock caused by MPI_Bcast call only initiated on ioRank. in writeTimeStepWithCellProperties.
2) ThreadHandle now waits on destruction until all objects have been dealt with.
This PR fixes the issues raised by @blattms in #1188 .
> Bugfix: fix MPI deadlock in output when asyncOutput is enabled.

- CMakeLists_files.cmake
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/multiPhaseUpwind.cpp
- opm/autodiff/multiPhaseUpwind.hpp
- tests/test_multiphaseupwind.cpp
This PR moves the multiphase upwinding logic to a free function. The benefits are:
- Easier to test, unit test has therefore been added.
- Easier to use from other solvers, this function is used in the reordering transport solver.
The refactoring should not change any results, and the only simulator affected is flow_sequential which still should be considered experimental, so I intend to self-merge it when green, unless someone objects or volunteers to review.
> Multiphase upwind refactor

- opm/autodiff/WellStateFullyImplicitBlackoilDense.hpp
> Fix minor warning (returning a const double).

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This resolves the segfault when output=false is used.
> [bugfix] Only create asyncOutput when output is enabled globally.

- CMakeLists_files.cmake
- opm/autodiff/DebugTimeReport.hpp
This small utility is useful for simple timekeeping for numerical experiments. It reports time since construction when it goes out of scope.
Intend to self-merge when green, as it has no effect whatsoever on other code.
> Add DebugTimeReport utility.

- opm/autodiff/FlowMain.hpp
(Another minor improvement mined from my work on a reordering transport solver, to make that PR less messy when it arrives...)
Added "all_messages_to_terminal" parameter (defaulting to false), if true, all messages (including note and debug) will be sent to the terminal.
In addition, parser messages are tagged, to make the terminal output less likely to be overwhelmed.
Since this actually affects flow itself I don't think I should review and merge this, @dr-robertk or @andlaus, could one of you do this?
> Logging flexibility improvements.

- opm/autodiff/StandardWellsDense_impl.hpp
This PR fixes the invalid read mentioned by @akva2 in #1192 .
> [bugfix] Fix invalid read in WellDenseStandard when used with 2P Model.

- opm/autodiff/NonlinearSolver_impl.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
Multiple problems/warnings are displayed in certain instances to report an issue and provide additional information about the issue; Used OpmLog::info to display the additional information
> Logging of multiple problems/warnings

- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This requires OPM/opm-output#191, and adapts opm-simulators to that API change (allowing misc data for summary output). It also takes advantage of that to pass TCPU for summary output (it will only be written if requested in the deck using the TCPU or PERFORMA keywords).
The timing number passed for this is actually the total solver time taken, which does not include output for example. Possibly this should be amended, and expanded with more misc data (iteration counts etc.) as needed.
@alfbr could you see if this is a reasonable match for your needs?
> Implement TCPU

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
instead of the BlackoilModelEbos, which reduces some confusion and also
removes a few unnecessary wrapping functions.
This PR should not change the result.
> making wellMod_ in WellModelMatrixAdapter is actually a well model

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
no excuse, i forgot to test https://github.com/OPM/opm-output/pull/193 with downstreams
> fixed: constructor has been made explicit

- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
This PR removes the debug info introduced to the terminal output through #1168 and also adds more detailed catch blocks for `NumericalProblems`. However, the `maxiter()` information is removed from the terminal output but can still be viewed in the debug file.
> remove debug info from convergence failure terminal output

- compareECLFiles.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
This PR reduces the maximum number of Newton iterations from 15 to 10, and -- more importantly -- it ignores the maximum-residual-in-all-cells criterion (CNV) for the nineth and the tenth iterations, i.e., after iteration 8 only the aggregate mass balance and the well residual criterions are considered.
I've tested this on Norne, Model 2, Model 2 realization 0 and realization 5 and I made sure that all opm-simulators tests still pass on my machine. With this PR merged, the simulator seems to be significantly more stable (e.g. it works fine with OPM/opm-material#220 applied) and performance seems to also improve by 5 to 10% even for cases  where complete breakdowns do not occur, i.e. Norne.
The results of the unit tests stay identical. That said, since the time stepping is different, the …
> Improve stability by changing the convergence check

- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
This PR improves the speed of the ILU preconditioner by storing the upper triangular matrix in a more memory coherent way. The previous implementation required backwards iteration for the upper triangular which is not optimal. This PR does not change anything on the algorithmic side. 
For NORNE the runtime reduces from 745.171 sec to 671.636. Similar or better improvements can be observed for Model2.
> Faster ILU implementation.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/RedistributeDataHandles.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
the only thing that was used of this class was the phase usage object, but the phase usage object can be accessed via much leaner interfaces.
The old BlackoilPropsFromDeck (without "Ad") is still required to compute the initial condition, but the init code should be refactored soon anyway.
this PR depends on OPM/ewoms#197
> flow_ebos: do not use BlackoilPropsAdFromDeck anymore

- opm/simulators/timestepping/SimulatorTimer.cpp
Downstream of: https://github.com/OPM/opm-parser/pull/1092
> Changed to TimeMap api - using std::time_t

- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Possible values are none, log, and all. The first does not do any logging
to files. The second does log to files but does not create and log to
the DEBUG file. The latter uses all possible files.
Alternative to #1225 as requested by @atgeirr and @joakim-hove
> Use output to skip debug or all files

- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
If output=false is requested we created an empty file.
Now that file will only be created if output was requested
and it will only be opened on one rank in a parallel run.
> Only create step_timing.txt file if it gets written to.

- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
This PR contains the following contents related to StandardWellsDense
1. remove the order switching of well primary variables 
2. remove the order switching of well equations. 
3. remove the unused function `ebosCompToFlowPhaseIdx`
Notably, this PR only contains removal of stuff. 
Since the solvent related variable/equation currently always holds the last position, we omit the solvent related in the following discussion. The first change is more significant than the second one. We discuss mostly about the first change. 
In the well state, we assume the information in `wellSolution` in order is  bhp/rate, water fraction, gas fraction. 
In the function `assembleWellEq`, we use `flowToEbosPvIdx` to switch the order of the well primary variables a little bit, while the definition of the …
> Not switching the order of well primary variables and well equations

- compareECLFiles.cmake
This case produced test errors on my system. The results produced were equivalent but with relative errors above tolerance.
The production curves oscillate very strongly, yet the comparison routine only looks at the values at a single point in time, and does not compare to the overall magnitude (over time). Therefore, when comparing near the bottom of a "wave" a small error compared to the overall magnitude (value at top of a "wave") can be categorised as a large relative error.
I think that long-term we should revise the comparison tool to extract the maximum (or perhaps average) value from the reference, and use that as basis for relative error comparisons. In the short term, I believe this case is somewhat unique among our tests (regarding the oscillating curves), and that it is …
> Relax the tolerance for the SPE5 case.

- opm/autodiff/ISTLSolver.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
- Removes multiple problem linear solver failure
- Removes whitespaces before timestep chopped message to ensure consistency of message formating
> Multiple problem logging for linear solver failure

- CMakeLists_files.cmake
- examples/flow_ebos_polymer.cpp
- examples/flow_ebos_solvent.cpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/Compat.cpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/FlowMainPolymer.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
Separate executables are added for solvent and polymer. 
The well model are adjusted to take care of polymer without adding extra equations for the polymer. 
Tested and verified on the test cases in polymer_test_suite. 
This PR should not effect the standard black-oil simulations.  
Depends on OPM/opm-core#1169 and OPM/ewoms#195
> Add flow_ebos_polymer and flow_ebos_solvent

- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
This should restore the build for those on older compilers at least.
Today we had two separate issues that caused Jenkins trouble.
First was that I forgot to co-merge OPM/opm-data#232. That was a pure human error on my behalf.
The second was that C++17 code was merged. I do not quite understand why Jenkins accepted it, I would have assumed that when asking for C++11 as we do C++17 is not considered?
In any case, with this PR I hope both issues are laid to rest. I will self-merge when (if...) Jenkins is green on this.
> [bugfix][StandardWellsDense] Remove auto from method parameter list, take 2

- examples/flow_ebos.cpp
- examples/flow_legacy.cpp
- examples/flow_mpi.cpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/StandardWellsDense.hpp
- opm/simulators/ParallelFileMerger.hpp
Actually, it did not as it did set the define either wrong
or in the wrong locations. This commit fixes this and finally
makes AMG available.
> Fix the PR that said it activated AMG.

- CMakeLists_files.cmake
- examples/flow_reorder.cpp
- opm/autodiff/BlackoilPressureModel.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/BlackoilReorderingTransportModel.hpp
This implements an experimental reordering transport model for the implicit sequential formulation of the black-oil problem. The model has plenty of debugging and experimental features, is not quite feature complete (multi-cell block solve missing) and has at least one unfound bug (it cannot run the Norne case even though it *should* be able to). On the other hand, this does not affect any fully-implicit code at all, so it should be quite safe to merge.
This class has been lying around in a branch for a long time now, I think it should be brought into the open, in spite of its warts.
@andlaus could you review this? It's based on the Evaluation class so I think you should find it somewhat familiar.
> Reordering transport model

- CMakeLists_files.cmake
- compareECLFiles.cmake
- examples/flow_ebos_2p.cpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
This PR adds an executable for two-phases cases with hard coded numEq = 2. This results in faster execution times for theses cases. This PR needs https://github.com/OPM/ewoms/pull/204.
> Added two-phase executable for numEq = 2.

- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
The versions are missing the specialized code for inverting a 3x3 matrix that makes the algorithms quite a bit more stable. This made running Norne with 4 processor take forever due to minimal time steps. The reason  why we might have only experienced this in parallel to such extend might be that in the overlap/ghost region the properties of the matrix entries might be a bit different because of missing off-diagonal values.
Maybe this instability is also the cause for some of the parallel test failures produced by PRs not related to parallelism at all (reordering well euations and the likes).
This is the least invasive change to fix the problem. It simple uses our own MatrixBlock as the block_type of BCRSMatrix. That class has a specialised version of the matrix inversion for 3x3 block …
> Work around unstable matrix block inversion in DUNE 2.3 und 2.4

- opm/autodiff/StandardWellsDense_impl.hpp
Using more clear standards to tell if it is a two-phase case.
When `numComp < numEq`, it looks like it can also be the case with polymer, which makes the following `assert` not sensible. 
Since it is a small change, it will be helpful for other development if this PR can get in quickly. 
@totto82 , do you think the change makes sense?
> fixing the running of polymer cases.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
If the user requests FOE (field overall efficiency) output, then we must provide the output facilities with OIP (oil in place) data to be able to compute it.
A simple and minor fix, I intend to self-merge when tests are green.
> Create oil-in-place data if overall efficiency is requested by output.

- compareECLFiles.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
to fix the running of the group control. 
Very originally, the BlackoilModelEbos and SimulatorFullyImplicitBlackoilEbos have their own rate converters. StandardWellsDense points to the one in BlackoilModelEbos.  Due to some later code change, StandardWellsDense points to the one in SimulatorFullyImplicitBlackoilEbos, which causes the failure of running with VREP group control. 
With this PR, we make the SimulatorFullyImplicitBlackoilEbos, BlackoilModelEbos, and StandardWellsDense use the same rate_converter to fix the problem.
> Simulator Blackoil and StandardWellsDense uses same rate_converter

- opm/autodiff/BlackoilReorderingTransportModel.hpp
Various minor (and less minor...) bugs have been fixed.
With this, it is possible to run the Norne case with flow_reorder, with two caveats: you must set ds_max=0.1 (the default is too large for this case) to make it run through, and it does not support VAPPARS (yet).
A note on (the lack of) performance:
performance is not too bad considering that it runs the legacy assembly for the pressure solve, and again to verify the residuals after solving (1800 seconds on Norne). I expect that it can be significantly improved. Making a local-ad pressure solver would give the biggest gain.
I intend to self-merge this when green, as it
- affects no other code, and
- is an experimental simulator.
> Fixing bugs and improving the reordering solver

- opm/autodiff/BlackoilReorderingTransportModel.hpp
This should fix warnings reported by other users. Curiously, clang did not give me a warning, even upon instantiation of the template. I have kept the commented-out lines as they are useful for continued debugging and experimentation (the solver should still be counted as experimental).
@akva2 I hope this removes all warnings you got.
> Silence unused variable warnings.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/Compat.cpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/RateConverter.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/autodiff/WellStateFullyImplicitBlackoilDense.hpp
**Motivation** 
Currently the solution state is stored both as global arrays in the BlackoilState and as local solution variables  for each cell in ebos and great care need to be taken to communicate the solution between these two storages. The aim of this PR is to avoid this duplication. This PR does not remove the BlackoilState completely from flow_ebos, it is still kept in the signature of the step methods in AdaptiveTimeStepping and NonlinearSolver. And also in the initialization, for restart and for output of the initial state. After the initial step, an empty reservoirState is passed around in the code to avoid abuse. 
**Changes**
1) Use the solution variable directly in RelativeChange(...)
2) Add a method in the RateConverter that takes the simulator instead of the state.
3) Pass …
> Remove reservoirState from BlackoilModelEbos

- tests/test_wellmodel.cpp
to avoid using C++14 specific functions.
This is to fixed the issue reported in #1264.
> not using std::make_unique in test_wellmodel

- opm/autodiff/StandardWell_impl.hpp
reported by @hnil , while I did not see the compilation warning.
> removing a few unused nw variable in StandardWell_impl.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
It appears summary files by convention expect all substep data points to be chunked together with the data point at the end of the report step. The report step index passed is used by opm-output to chunk the data points, we therefore must pass the same index for all data points that should be in the same chunk.
This is intended to fix a problem reported by Statoil. Marked as WIP as I cannot test that this actually solves their issue, so @alfbr you have to test this PR and report back if it addresses your problem without breaking anything!
> Fix report step number associated with substeps.

- opm/autodiff/StandardWell_impl.hpp
For example in opm-data/spe9group, it improves the well curves of the injection wells in a relatively more significant way while makes the result of the production wells slightly worse. 
https://www.dropbox.com/s/riykfil01lf5f0r/spe9-group.pdf?dl=0
For some other examples, it improves the result slightly. 
It should not change anything for cases without `GEFAC` or `WEFAC` keywords, which are the most of the cases we have.
> correcting the way to use efficiency factor in assembleWelEq

- compareECLFiles.cmake
After this it should just be the autodiffmatrix test left to fix.
> Further slacken coarse test tolerance for the benefit of test 27.

- tests/test_autodiffmatrix.cpp
eigen returns a matrix with all coefficients stored from the operator/
this makes the comparison fail as x has no nonzeros. this broke the autodiffmatrix test.
not very happy about this but i see no other way to go about it.
> workaround eigen 3.3.2 issue

- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
- opm/autodiff/StandardWell_impl.hpp
- use std::remove_const
- remove unused variables
> Quell warnings

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Currently, the ReservoirState passed to the method and converted
to the initial solution of the Ebos simulator might have wrong
values in the ghost layer (this is the case for SPE9, Norne, Model 2).
This commit uses the syncOverlap method to update these values once they
are converted to the Ebos solution. The  ReservoirState remains untouched.
This is enough to have consistent values throughout the simulation and only
introduces one additional communication step.
> Communicate the ebos solution at the beginning of the run method.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/RateConverter.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
- opm/autodiff/WellInterface.hpp
- tests/test_rateconverter.cpp
- pressure, rs and rv is averaged using hydrocarbon pore volume weights.
- pvtRegions is used as input in the conversion factor calculations.
- the pvt cell of the first well cell is used as the pvt index.
(Completing a well in two different PVT regions sounds like a very bad
idea anyway)
- FIP region support is added to the rate converter also for the ebos
interface.
> Use pore volume weighted averaged hydrocarbon state in rateConverted.

- opm/autodiff/BlackoilModelEbos.hpp
It is a design to recover the old way to handle the oscillation before #1250, to avoid some performance degeneration for parallel running which was reported by @blattms . 
Not sure how it impacts serial and parallel running of other cases yet.  By theory, it should be okay, since the way handling oscillation introduced with #1250 only improves slightly for other running.  Recovering that should not introduce big performance degeneration. 
Anyway, this PR is only for testing purpose for now should not be considered to be merged before thorough testing.
> avoiding the oscillation treatment applied to well solution

- opm/autodiff/StandardWell_impl.hpp
this one was only seen in debug builds.
> quell signed/unsigned mismatch warning

- CMakeLists_files.cmake
- examples/flow.cpp
- examples/flow_ebos.cpp
- examples/flow_ebos_2p.cpp
- examples/flow_ebos_polymer.cpp
- examples/flow_ebos_solvent.cpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/flow_ebos_blackoil.cpp
- opm/simulators/flow_ebos_blackoil.hpp
- opm/simulators/flow_ebos_gasoil.cpp
- opm/simulators/flow_ebos_gasoil.hpp
- opm/simulators/flow_ebos_oilwater.cpp
- opm/simulators/flow_ebos_oilwater.hpp
- opm/simulators/flow_ebos_polymer.cpp
- opm/simulators/flow_ebos_polymer.hpp
- opm/simulators/flow_ebos_solvent.cpp
- opm/simulators/flow_ebos_solvent.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
The motivation for this PR is that currently the build fails on my Ubuntu 17.10 laptop with two processes because that machine "only" has 8 GB of RAM (granted, the optimization options may have been a bit too excessive). under the new scheme, each specialization of the simulator
is put into a separate compile unit which is part of libopmsimulators. this has the advantages that the specialized simulators and the main binary automatically stay consistent, the compilation is faster (2m25s vs 4m16s on my machine) because all compile units can be built in parallel and that compilation takes up less RAM because there is no need to instantiate all specializations in a single compile unit.
on the minus side, all specializations must now always be compiled, the approach means slightly more work …
> Improve polymorphic flow

- opm/autodiff/FlowMainEbos.hpp
The old message was not really accurate anymore because flow also supports the polymer and solvent extensions. (Also, the parentheses around the version were because they are not necessary.)
v2: use the message proposed by [at]atgeirr
> update flow startup message

- opm/autodiff/BlackoilModelEbos.hpp
this needs to merged before OPM/ewoms#227. the PR can be merged before OPM/ewoms#227, but it will cause spurious deprecation warnings. (i.e., it is best to merge OPM/ewoms#227 and this one together, permission to do so for the eWoms part is hereby granted to everyone.)
> do not set the SimulationParameter property anymore

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/DuneMatrix.hpp
- opm/autodiff/ExtractParallelGridInformationToISTL.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- tests/test_transmissibilitymultipliers.cpp
We are targetting DUNE 2.4.* and 2.5.* currently. Therefore this commit removes
the if checks for lower versions to cleanup the code.
> [cleanup] Removes unnecessary if clauses for unsupported DUNE versions.

- opm/autodiff/BlackoilModelParameters.cpp
It happens during addressing the comments of PR #1279. 
I did not realize when putting ms wells related parameter inside `if` condition, I have to move `use_multisegment_well_` before the `if` condition. 
I did not realize it since most of times we have been using default parameters. 
Without this PR, means people can not tweak all the multisegment well related parameters.
> checking use_multisegment_well_ first in BlackoilModelParameters

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Reverts OPM/opm-simulators#1306
This makes the commit in question win the prize for being the most-flipped piece of code in OPM.
After the original commit (in #1286) was reverted (in #1306) it was discovered that even as performance for 8 threads recovered (if not fully), now the solution was a bit off. At least further away from the serial solution than it used to be. The choice between a slow (with 8 threads) solution and a wrong one is forced: we must for now take the slow one, while the whole situation is investigated further.
I'll merge this reversion straight away, as there have been quite a bit of offline discussions about it.
> Revert "Revert "Communicate the ebos solution at the beginning of the run method"

- opm/autodiff/MSWellHelpers.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
this was caused by the recent work on multisegmented wells. If UMFPack is available, it compiled.
@akva2: this is a candidate for backporting to the release/2017.10 branch.
> make the build work if UMFPACK is not available

- compareECLFiles.cmake
- opm/autodiff/MSWellHelpers.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
when calling invDXDirect. When the exception got thrown, better way is to stop the running, I am not sure how to do it in a good way here. 
Without this PR, users get the information 
```Opm::NumericalProblem,"Error encounted when solving well equations"```
> giving more information when umfpack is not available.

- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/StandardWell.hpp
3x3 matrix block inversion in FieldMatrix is numerically unstable
including version 2.5.0. Therefore the previous if clause was wrong
as it activated the use of FieldMatrix already for 2.5.0 (the version
in Debian stable). With this commit we use MatrixBlock for version 2.5.0.
This PR is an update of #1240 for DUNE 2.5.
I am sorry that this fell through the cracks and I only posted this now. 
As 2.5.0 is the version of DUNE in Debian stretch this should definitely end up in the Debian packages. Please note that this might also fix the different time stepping seen for some SPE cases after updating the jenkins server.
> Use MatrixBlock instead of FieldMatrix for DUNE 2.5.0

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/RateConverter.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/WellDensitySegmented.cpp
- opm/autodiff/WellDensitySegmented.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
This PR contain the main part of PR #1313 
The wellModel is now persistent over the time steps,
with an update method called every reportStep/episode.
This allows the following simplifications:
1. move the wellState to the WellModel
2. add a ref to the ebosSimulator to the wellModel
3. clean up the parameters passed to the wellModel methods
4. move RESV handling to the WellModel and the rateConverter
5. move the econLimit update to the WellModel
> Minimized PR: Make the wellModel self-contained

- opm/autodiff/BlackoilModelEbos.hpp
This was moved to assemble() some time ago but according to my logic it
belongs in the solve method since this is only a trick to solve the well
equations simultaneously with the reservoir equations.
A buggy side effect of the currect implementation was that the well
residual was considered in the convergence test. I.e. this move changes
the convergence behaviour of the simulator.
> Apply the well residuals to cell residuals in SolveJacobianSystem

- debian/control
former is used on stretch, latter is used on xenial
> changed: make libdune-uggrid-dev an alternative for libug-dev

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
It can be just me that had problems in `Water, Oil, Gas` with the ones in `BlackPhases` ones.  Following the change in #1323, this PR tries to use only `Water Oil Gas` in the well model and also WellStateFullyImplictBlackOil. It makes the statement like 
```C++
const int water_pos = pu.phase_pos[Water]
```
much easier to read, especially for newcomers. 
It can go further to some other files, like WellDensitySegmented, VFP related, RateConverter and SimFIBODetails. It is not good  redefine it again and again (even like the one in WellStateFullImplicitBlackoil in this PR), it can be good to make it in some header files. 
The old way is `BlackoilModelEnums.hpp`, while it contains some codes we would like to get rid of. 
Should we keep using it while removing the unwanted parts when possible, …
> replacing BlackoilPhases:: with Oil Water Gas in well model

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
Trying to move our output in a direction more tailored to users. Nothing removed, but some messages that seems developer centric have been removed from the PRT file but kept in the DEBUG file.
> LOG and PRT file clean-up

- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/RedistributeDataHandles.hpp
This adapts to the new function signature as of OPM/opm-output#216. It uses the
newly introduced map of integer vectors to print the MPI ranks in a parallel run.
I have not tested whether what is printed makes sense. But this change is needed to compile opm-simulators with the PR of opm-output
> Adapt writeInitial call to use integer vectors for printing ranks

- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/RedistributeDataHandles.hpp
This saves space and it is allowed and recommended (spacewise) to
use integer arrays with only values for active cells in writeInitial. This addresses the comments made in #1336
> Disregard non-active cells when writing MPI_RANK in writeInitial.

- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
Most notably the blackoilState is not returned by the initialization
code anymore, instead the initialization class is returned.
Depents on OPM/opm-core#1187
TODO: 
Fails on the multisegmented well test case. Needs investigation. 
Not tested on the big cases.
> Adapt to the refactoring of the Equil initialization code

- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
in StandardWell.
The only thing changes the behavior is the following statement. 
```
+            if (well_type_ == INJECTOR && wpolymer() == 0.) {
+                return;
+            }
```
And move all the polymer related in StandardWell into a function updateWaterMobilityWithPolymer for better clarity.
> fixing a polymer running with both shear and non-fully mixed polymer. 

- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
This PR effects results and convergence on most of the cases. I have verified that it doesn't introduce any big problems on any of the big models. Since the timestepping is changed most test should fail.
> Use 1 day as default initial time step

- opm/autodiff/BlackoilModelEbos.hpp
Move the `beginEpisode()`/`endEpisode()` call to ebos to `beginReportStep()`/`endReportStep()` and `beginTimeStep()`/`endTimeStep()` call to ebos to `prepareStep()`/`afterStep()`. 
I have verified that this does not change anything on the big models. (diff master.PRT thisPR.PRT shows only random fluctuation in timing).
> Put the ebosSimulator start and end methods where it belongs

- compareECLFiles.cmake
With this change no simulations have "failed steps" with current master.
> Increase max_iter for ctests SPE5 and 2D_THREEPHASE_POLY_HETER

- opm/autodiff/FlowMainEbos.hpp
This fixes a minor issue when GridView defined in ewoms is not Grid::LeafGridView.
> [bugfix] make code compile when GridView is not Grid::LeafGridView.

- opm/autodiff/BlackoilModelParameters.cpp
This helps stabilizing the convergence for difficult cases. Tested on norne, Model 2-0 and Model 2-5.
> Change dp_max_rel default from 1.0 to 0.3

- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
Without this, the log output from some subsystems (such as the parameters) will be lost as there is no log picking it up.  If no-one beats me to it I'll self-merge when green.
@andlaus if you want to get OpmLog output from some ewoms programs this is the simplest way.
> Add setupSimpleDefaultLogging() to old two-phase sims.

- compareECLFiles.cmake
This was hidden by the MPI issue fixed in https://github.com/OPM/opm-common/pull/317
> fixed: do not add parallel regression test if MPI is not enabled

- CMakeLists_files.cmake
these files take the longest to compile. moving them to the beginning speeds things up for parallel fulll rebuilds because the remaining compile units can be processed while dealing with the flow_ebos files. currently, the build stalls if these files are at the bottom of the list because they are required for the library.
> move the flow_ebos_*.cpp files to the beginning of the source list

- compareECLFiles.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilOutputEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
This PR makse #1384 redundant. 
1) Remove unused output code
2) Pass output_dir and double_si_restart parameters to ebos 
Depends on OPM/ewoms#278, OPM/opm-grid#302, OPM/opm-output#235
Test failure is expected and new reference data is needed before this is merged.
> Use FIP, EGRID and INIT output code in ebos. 

- CMakeLists.txt
- CMakeLists_files.cmake
instead of unconditionally adding, and then conditionally removing
again. follow-up after @andlaus comment yesterday.
istl-conditionals removed since istl is a hard dependency for opm-simulators.
> changed: only add conditionally built files if they are to be built

- opm/autodiff/BlackoilWellModel_impl.hpp
Should again be possible to run with no wells.
> Ensure we do not dereference nullptr.

- opm/core/wells/WellsManager.cpp
- opm/core/wells/WellsManager_impl.hpp
In cases where the user wish to verify that the model initializes properly it is useful to run the .DATA file without any wells.
Calling wells()->number_of_wells on nullptr causes segmentation fault. This
occurs when running a deck without wells. Allowing WellsManager::init to
continue for decks without wells enables the well struct to be set.
Authored by Sveinung Rundhovde & Lars Petter Hauge
> Allow Wells struct initialization without wells

- opm/autodiff/BlackoilOutputEbos.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/RateConverter.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
Adding dissolution gas production rate, dissolution oil production rate and the three reservoir phase rate for output purpose. It works well for my only simple test case, while it will face big challenges when cross flow and multiple FIP regions are involved. 
It depends on PR OPM/opm-parser#1211 and OPM/opm-output#253. 
And also, we probably should not update these values always, we should check the `SummaryCfg` to see if we need these values are needed for output purpose. 
Please help to test it. If there are some discrepancy is found, please help to share your case with me for debugging purpose.   
The following is the comparison plot of my test cases. 
[temp_3d_cases.pdf](https://github.com/OPM/opm-simulators/files/1724267/temp_3d_cases.pdf)
> [WIP] Populating reservoir rate related output

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellConnectionAuxiliaryModule.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- tests/test_multmatrixtransposed.cpp
Currently, we never pass the full matrix to the precondioner but  a matrix that does not include the well contributions. Only for the linear operator we use the full matrix. The idea was (past tense!) to include the well influences into the matrix passed to the preconditioner and hopefully get a better one and improve the time to solution.
This PR adds a flag matrix_add_well_contributions which does that when set to true (default is false).
Well, this kind of works fine for SPE9 (total time drops from 28.8234 sec. to 26.1497). Unfortunately, for both Norne and Model 2 we the time needed for the solution increases (Norne 12%, Model 2 3%). This is due to differently failing nonlinear solves and therefore more linearizations.
But maybe this PR is missing something, @totto82 ?
Anyway I think …
> Add possibility to use matrix with well connections for preconditioner.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
For the linear operator we use the old approach of first applying the reservoir part and then
the contributions of the wells.
With this a run with `matrix_add_well_contributions=true` results in
```
Total time (seconds):         701.562
Solver time (seconds):        697.49
Assembly time (seconds):     360.866 (Failed: 10.3181; 2.85925%)
Linear solve time (seconds): 312.278 (Failed: 8.73115; 2.79596%)
Update time (seconds):       14.8467 (Failed: 0.462793; 3.11714%)
Output write time (seconds): 5.25062
Overall Well Iterations:      968 (Failed: 12; 1.23967%)
Overall Linearizations:       1925 (Failed: 55; 2.85714%)
Overall Newton Iterations:    1587 (Failed: 55; 3.46566%)
Overall Linear Iterations:    23263 (Failed: 616; 2.64798%)
```
with `matrix_add_well_contributions=false` (default): …
> If requested use matrix with well contributions only for the preconditioner.

- tests/test_blackoil_amg.cpp
Minor fix, in line with #1406.
> Leave BOOST_TEST_DYN_LINK setting to the build system.

- opm/autodiff/BlackoilModelEbos.hpp
Shift intensiveQuantities each timestep. 
If enableStorageCache is true the call just returns (i.e. no performance penalty for the default case)
> Bugfix. enableStorageCache=false

- opm/core/wells/WellsGroup.cpp
just to silence a warning resulting from OPM/opm-common#348 .  It should only be merged if the upstream PR is merged.
> adding POLYMW to the injectorType determination

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/ThreadHandle.hpp
this is the mop-up PR for OPM/ewoms#299. it is required because the default for the output directory now exhibits slightly different semantics and the `ThreadHandle` mechanism has been replaced by `Tasklets` in eWoms. For this reason, the old `ThreadHandle` code is moved to here the in order to having to touch legacy code as little as possible.
> tasklets mop-up

- tests/test_multmatrixtransposed.cpp
At least for dune 2.4.1, statement like `Mat2 res2 = {{}, {}}` will cause problem when initializing the matrix, please refer to https://github.com/OPM/opm-simulators/issues/1432 for more report. 
Not sure if it is the best way to fix the problem though. 
To avoid future similar problem, maybe we should keep `-DDEBUG` for jenkins tests.
> fixing test_multmatrixtransposed

- opm/autodiff/MissingFeatures.cpp
Followup to: https://github.com/OPM/opm-common/pull/370 - mark keywords as unsupported.
> Mark LGR related keywords as unsupported

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
Use a relaxed tolerance for individual cells (CNV) when `iter > max_strict_iter`. `tolerance_cnv_relaxed_` is defaulted to 1.0;
This is a safer version of the current approach of ignoring CNV for `iter > max_strict_iter`. Setting `tolerance_cnv_relaxed_` to a large number will give back the current approach.
I have tested this on Model 2 rel 0 and rel 5 and on the CO2 cases. In general this increases the run time of the simulator and makes it more accurate. 
For Model 2 rel 5 this gives an increase of run time of 25%, without giving much improved accuracy. 
For some of the CO2 cases this improves the accuracy significantly with < 10% increase in time. 
others are more or less unaffected.
I have tested different variants of this PR as well as different default tolerances and the current …
> Add option for relaxed CNV tolerance

- opm/core/simulator/SimulatorReport.cpp
Some implementations do not get a transitive definition of class "ostringstream" in scope through the other headers and therefore fail to compile the member function
```C++
void SimulatorReport::reportStep(std::ostringstream&);
```
Prompted by PR #1433 (commit 7c9dab1a).
> Include <sstream> for Class "ostringstream"

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/RateConverter.hpp
Some minor issues notices while debugging the CO2CASE. 
1) Fix initial fluid distribution in the well, by solving the well equation one extra time before the first timestep.  
2) Get the correct RESV values for the under-saturated case. 
I have tested this on norne and model 2 rel 0 and rel 5. There are no performance loss and the overall results are improved slightly compared to our reference simulator. The WOPTF results are improved noticeable for model 2 for some wells ( the wells in the under-saturated region).
> Some minor fixes to RESV and initial well composition 

- opm/autodiff/WellConnectionAuxiliaryModule.hpp
this is the mop-up PR required for OPM/ewoms#309
> adapt to the removal of the `ewoms/aux` directory

- opm/autodiff/ISTLSolver.hpp
This fixes the issue with dune 2.5 and the polymer cases in opm-data
I have tested this on several of the polymer and co2 cases and plan to run a test on the model 2 realizations.
> keep using the block inversion algorithm in OPM

- opm/autodiff/ParallelOverlappingILU0.hpp
Discovered while debugging and investigating issues related to inversion of matrix blocks, #1464.
In the serial case, the *preconditioner* would essentially never throw, and the solution process would move on. Eventually the Krylov solver would not manage to reduce the residual and signal failure. With this change, inversion failures in the preconditioner will immediately throw.
There is one potential downside: if the Krylov solver could have continued successfully, in spite of a failing preconditioner, we no longer get that opportunity. However I expect this to be a very rare occurrence after #1464 is merged.
> Make sure we (re-)throw MatrixBlockError also in the serial case.

- opm/simulators/thresholdPressures.hpp
See opm/opm-common#410
Observe that the changes in this repo are on a "get it to compile basis"; i.e. the `flow_legacy` simulators will not load THPRES values from the restart file (however - if they are still in the deck - that will still work).
> Load thpres

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellDensitySegmented.cpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellmodel.cpp
This is part of the efforts to have proper VFP support. At the stage, it only recovers to the extent of the VFP capacity of the `flow_legacy`, while it not suitable for more general THP/VFP treatment yet. 
Please do not merge before requesting. 
`Adding well control equations` is the major part, basically, it reduces the complexity of the functions `getQs` and `updateWellstate`, and also, it provides functionality to monitor the convergence of the well control equations.
> Adding well control equations

- opm/autodiff/FlowMainEbos.hpp
as this preconditioner is still considered experimental and fails miserably for some models. Users can select CPR using the command line.
> Deactivate selection of CPR via eclipse keyword

- opm/autodiff/FlowMainEbos.hpp
this was forgotten when moving the output writing code into the ebos core. (this does not really matter for most people because asynchronous output is wanted anyway and it was unconditionally enabled.)
> Pass the async_output parameter to core ebos

- opm/autodiff/FlowMainEbos.hpp
This is a preparation for turning on OpenMP compilation by default. With OpenMP turned on by default, four threads seems a bit aggressive as the first attempt at a sensible default value. Two threads on the other hand consistently seems to provide a small performance improvement on CPUs with hyperthreading (which today is most CPUs), even when all physical cores are used with MPI. Reverting back to four threads by default can be done at any point in the future if deemed a better default.
For single process runs, using two threads for assembly provides 10%-15% reduction in total computational time. Hence, this change will give a nice boost for flow.
> Reduce default number of threads from four to two with OpenMP

- opm/autodiff/BlackoilModelEbos.hpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp
in conjunction with #1512, this makes VTK output work out of the box if `--enable-vtk-output=true` is specified:
> flow: fix the time held by the simulator object

- opm/simulators/timestepping/SimulatorTimer.cpp
Apparently required by boost::posix_time::milliseconds.
I ran into this while checking something else. A question is why did this only trigger now? I have not installed a new Boost lately to my knowledge.
> Cast argument for milliseconds() call to an integer.

- compareECLFiles.cmake
- tests/run-porv-acceptanceTest.sh
This adds an acceptance test based on the PORV of Norne. Being an acceptance test means in this context:
- Only PORV is verified.
- The tolerances are strict.
- The underlying reference will not be updated by Jenkins' update_data trigger.
The run-porv-acceptanceTest.sh script is almost a duplicate of run-init-regressionTest.sh. The differences are in the directory of the reference data, and passing "-k PORV" to the comparison tool.
This requires OPM/opm-common#439, or it may give misleading results.
> Add PORV acceptance test running Norne.

- opm/autodiff/BlackoilModelEbos.hpp
this has not been required anymore since the output code was moved to the ebos core.
> flow: do not set the ExportGlobalTransmissibility property anymore

- examples/compute_initial_state.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/FlowMain.hpp
- opm/core/simulator/EquilibrationHelpers.hpp
- tests/test_equil_legacy.cpp
- tests/test_wellmodel.cpp
this is required in conjunction with OPM/opm-material#304.
note that almost the only thing which is affected is legacy code.
> adapt to the fluid system naming convention change in opm-material

- CMakeLists_files.cmake
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/GraphColoring.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
- tests/test_graphcoloring.cpp
- tests/test_milu.cpp
For convenience this is based on #1479 (and adds support for milu to ILUn). From that PR the  following MILU variants can be requested via the ilu_milu command line parameter:
- MILU_0 is the unmodified ILU0, i.e. the default preconditioner
- MILU_1 will add the dropped entries to the diagonal (traditional MILU)
- MILU_2 will add the sum of the absolute values of the dropped elemets to the diagonal
- MILU_3 if diagonal is positive add sum of dropped row entrires. Otherwise substract them.
- MILU_4 if diagonal is positive add sum of dropped row entrires. Otherwise do nothing
As expected (if one reads the literature carefully) red black ordering gives worse convergence rates but when allowing considerable fill-in one iteration gets so fast that the runtime improves compared to natural …
> Added support for red black ilu

- CMakeLists_files.cmake
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
- tests/test_milu.cpp
Using the parameter `ilu_milu=true|false` (default=`false`) the user can now choose to use the modified ILU0 decomposition. If selected values will not be dropped for nonzero entries but added to the diagonal of U.
This approach will result in `A*e = L*U*e` for vector `e` with all entries being 1.
In theory this approach should be better than ILU. In practice (read anisotropy, discontinuous coefficients) it turns out to be worse. E.g I am seeing a lot of timestep chopping for Norne and other cases.
> Adds possibility to use modified ILU0 (MILU0) decomposition

- compareECLFiles.cmake
- tests/run-restart-regressionTest.sh
This is an attempt to solve the test failures in: https://github.com/OPM/opm-common/pull/463
The approach is that the deck used for the restartfile is loaded and then written out again in the temporry test CWD. 
Depends on: https://github.com/OPM/opm-common/pull/470
> Relocate restart data file in tests

- tests/run-regressionTest.sh
in particular this leads to issues with tests sharing result dir.
i noticed that spe12 was always marked for update when update_data was ran. this is the reason. it shares data directory with spe11. since spe11 ran after, it removed the files for spe12 and thus the test was always added to the list of changed tests. furthermore we could never update the spe12 data due to this.
> changed: do not remove the result path in regression tests

- examples/flow.cpp
this fixes the terse error message if no input deck has been found mentioned in OPM/ewoms#364.
@akva2: please merge if this is what you had in mind.
> print usage message if the input case cannot be found

- opm/autodiff/FlowMainEbos.hpp
this may avoid a compiler warning under some circumstances.
> FlowMainEbos: remove unused typedef `ThreadManager`

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParametersEbos.hpp
after OPM/ewoms#351 there is not much reason for `flow` to roll its own code for the newton-raphson update. I've tested this with norne and the performance and the results seem to stay the same, but I expect some numerical noise so that quite a few tests ought to fail and I did not test this with other relevant decks such as Model 2 and Olympus.
> flow: use the update procedure of the eWoms blackoil model

- opm/autodiff/FlowMainEbos.hpp
This fixes OpenMP. Not entirely sure this is where the call is wanted etc etc, but at least it points out the issue.
Without this call, manager returns 1 thread and we crash and burn in the fvbaselinearizer due to missing contexts.
> fixed: need to init ewoms thread manager

- opm/autodiff/BlackoilModelParametersEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
This sets the number of threads to 2 if openMP is available. once OPM/ewoms#377 is merged, this PR is required to keep the current default behaviour, but the present PR can be merged independently.
Note that I still think it is better to specify `--threads-per-process` explicitly, but this patch is better than the current machinery...
> flow: default to 2 threads if OpenMP is available

- tests/run-regressionTest.sh
The string literal 'ignore_extra' is from the Github commnt string is
interpreted as a "-x" switch to the comparison script.
@akva2 : I don't know if you want this in at all; or if it is done in the correct way. I think this can be useful - e.g. for the testing of https://github.com/OPM/opm-common/pull/454 - but I will *not* fight it.
> Enable -x switch to comparison scripts with jenkins

- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
which causes compilation warning.
The warning is introduced in #1512.
> removing the extra ; after BEGIN_PROPERTIES and END_PROPERTIES

- opm/autodiff/FlowMainEbos.hpp
This fixes fallout from the merge of PR #1512. Since then the
ParallelFileMerger was always given the current directory even if
another output directory was requested. This resulted in
CASENAME.procid.EXT files in that directory never being merged and removed.
Now the ParallelFileMerger gets the output directory path again and does its merges.
> [bugfix] Make parallel file merge work again for any --output-dir.

- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/NonlinearSolverEbos.hpp
During testing we needed to increase the number of iterations to get all simulations through. Please double check that I have done this the right places, I find setting of defaults quite confusing at this point in time. The legacy code and the new parameter system co-existing is not helping in this respect. These changes are presumed uncontroversial, so hopefully possible to merge. More controversial changes will be posted in a separate PR.
> Increase default maximum iterations for both non-linear and linear solver

- flow/flow.cpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
also, add a "reading deck" output. The idea is to make `flow`'s behaviour less surprising by preventing people from thinking that it got stuck after starting `flow` for a large deck.
> flow: print the startup banner immediately

- opm/autodiff/RateConverter.hpp
if a phase is disabled the active index (in the context of the well model this accessed via `PhasePos`/`phaseUsage`) is `-1` which leads to some hiccups if it is used to actually access some data.
I suspect that this is the cause for the jenkins failure of #1604 because the 2p oil-water testcase with aquifiers passes on my local machine.
> well model: fix valgrind complaints if either oil or gas are disabled

- opm/autodiff/AquiferCarterTracy.hpp
- opm/autodiff/BlackoilAquiferModel.hpp
- opm/autodiff/BlackoilAquiferModel_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This uses the new-and-shiny aquifer API of core ebos. also, this PR cleans the Aquifer code up a bit:
- do not use the intensive quantities cache directly anymore. (i.e.,  that code should now work if the IQ cache is disabled)
- do not fiddle with the global Jacobian matrix and residual vector directly. Instead, implement the water fluxes to the reservoir as a source term like wells.
one thing that did not become fully clear to me is if each aquifer ought to be assumed to be in contact with the whole reservoir or just a few cells on the boundary. The current implementation goes down the former path, while, without any deeper knowledge, I would rather suppose that the latter applies. maybe my understanding of this is just too limited, though.
> let aquifers be managed by core ebos

- opm/autodiff/BlackoilDetails.hpp
- opm/autodiff/BlackoilModelEbos.hpp
In parallel Flow, the ILU factorization of the local matrix is based on the entire local matrix, composed of rows, corresponding to both interior and overlap cells. This is a mistake, since overlap rows are not correct. 
One should instead restrict the ILU factorization to the "interior" local matrix. An easy way of achieving this in Flow without changing the data structures is to zero out overlap rows, but leaving infinity (or a large number) in the diagonal. This is implemented in this pull request, by altering the method solveJacobianSystem in the BlackoilModelEbos class.
The improvements in convergence of the linear solver for parallel Flow are quite good, and can be observed in tables below for the Norne and Modell 2 cases (note that results for Norne comes from a somewhat older …
> Ignoring overlap cells in parallel ILU factorization

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
The main purpose of this PR is to make it possible to call the well model from the code base (used by flow) in ewoms. The main difference in the code is that now assemble() does no longer apply the well terms to the residual and the Jacobian, instead this is done later in computeTotalRatesForDof(). 
TODO.
> Use ewoms well api for the well model

- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
It only applies to `producers` now. And solvent model is not handled yet.
For now, we have two fraction variables (F_w for water, F_g for gas) (one more when solvent is present) as primary variables for well. In theory, fraction values should always be between 0 and 1.0. (0. <= F_w <= 1.0,  0. <= F_g <= 1.0).  For oil,   0. <= (F_o = 1.0 - (F_w + F_g)) <= 1.0.
Due to numerical overshoot, from time to time, we can get some undesired fraction values. Like F_p {p = w, 0, g} is negative or above 1.0.
The current implementation is something as follows, (slightly more complicated while the spirit is the same)
if F_p < 0.  then F_p = 0.;
if F_p > 1. , then F_p = 1.;
As a result, when this numerical chopping happens, we can get some zero fractions (numerically). As a result, we get some zero …
> relaxation to avoid overshoot of fractions of StandardWell

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
When there is some events happen to a well, we use the control mode
from the DECK, and update the WellState based on the new control model.
Otherwise, we can use the control mode from the previous well state,
and keep the values from the previous well state as an intial guess.
> detecting whether some well control events happens to a well

- opm/core/linalg/ParallelIstlInformation.hpp
Should hopefully fix the Jenkins post-builder failure.
> Add missing include for std::vector.

- opm/autodiff/BlackoilWellModel_impl.hpp
when the solveWellEq did not get converged.
Due to economic reason or other causes, the number of the wells in Wells and well_container_ can be different (number of wells in well_container is always equal to or smaller than the wells in Wells). 
When recovering from the non-successful solveWellEq, we should do the for loop for the wells in the well_container instead of Wells. Otherwise, it can cause segmentation error.
> fixing different well number between Wells and Well_containers

- opm/autodiff/StandardWell.hpp
- tests/test_invert.cpp
- tests/test_multmatrixtransposed.cpp
to avoid legacy code in tests. the second commit has no functional reason, but it seems cleaner to me.
> Use ebos ISTL class

- opm/autodiff/MatrixBlock.hpp
Fixes issue causing Jenkins post-builder to break, as described in a new comment in #1617.
Since this is rather trivial yet cruical, I will self-merge immediately.
> Add missing includes

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/VFPHelpers.hpp
- opm/autodiff/VFPProdProperties.cpp
- opm/autodiff/VFPProdProperties.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
In this PR, the two major functions introduced are:
1. calculate the inflow performance relationship (IPR) based on the current reservoir state
2. when there is a well switched to THP control, we will update well state based on the IPR. 
It should only change the convergence behavoir of the test `52 - compareECLFiles_flow+SPE1CASE1_METRIC_VFP1`, while not impact other cases at all, since there is no THP control involved.
> update well state with THP target based on inflow performance relationship

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
otherwise, it might not be initialized if the well does not exisit in
previous well state, which will result in undefined behavoir.
it causes failure in running some realizations.
> using control in DECK to initialize the control in WellState

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
PR #1555 caused a almost 5% regression of the run time of most models. The reason is that now the update of the intensive quantities is done in the well model in the method updatePerforationIntensiveQuantities() which are not OpenMP parallel . This PR makes sure that only the intensive quantities of the perforated cells are updated and thus restores the performance.
NB. There are several other call to  updatePerforationIntensiveQuantities() in the well model that are not  OpenMP parallel, that could cause similar unexpected problems in the future. These should be addressed in later PRs. But currently they do not cause any performance regression, since they are only called when the intensive quantities are cached.
> Speed up add cell rates

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
With this, we refactor BlackoilModelEbos::getConvergence() to use the ConvergenceReport class, and store such objects for all timesteps and iterations.
This may initially be useful for debugging, but the intention is to use this to decide when a well is causing too much trouble by causing timesteps cuts, to close that well.
> Store ConvergenceReport objects

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
With this, we avoid some cases where timesteps are chopped repeatedly, sometimes to the point of terminating the simulation. Such deep chopping is avoided by shutting misbehaving wells. A well is misbehaving if:
- the timestep would be chopped below a minimum limit (currently set to 0.25 day)
- we have tried this step at least K times (currently K is set to 3)
- each of those times, the well failed to converge.
We also enforce a maximum timestep limit that is only applied when THP constraints are active (currently set to 16 days).
> Shut time-chopping wells

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
This fixes two crashing bugs in the WTEST implementation that only bite when run in parallel.
Note that there are still *output* bugs in the WTEST implementation, so for now one must expect the following diagnostic:
```
WARNING: There has been logging to file ./3D_WECON.1.DBG by process 1
WARNING: There has been logging to file ./3D_WECON.1.PRT by process 1
```
... and find some output related to WTEST appended to the end of the DBG file instead of at the appropriate location. Fixing the output bugs is less critical, but should be done.
> Fix WTEST in parallel

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/NonlinearSolverEbos.hpp
- opm/autodiff/RateConverterLegacy.hpp
- opm/autodiff/SimFIBODetails.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- tests/test_stoppedwells.cpp
This allows (re)moving of the following files
```
opm/autodiff/RateConverter.hpp
opm/autodiff/Compat.cpp
opm/autodiff/Compat.hpp
opm/core/props/BlackoilPropertiesInterface.hpp
opm/core/simulator/BlackoilState.cpp
opm/core/simulator/BlackoilState.hpp
opm/core/simulator/BlackoilStateToFluidState.hpp
opm/core/utility/initHydroCarbonState.hpp
opm/polymer/PolymerBlackoilState.cpp
opm/polymer/PolymerBlackoilState.hpp
tests/test_blackoilstate.cpp
```
Superseeds #1660
> Remove usage of BlackoilState class

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
changed wellpointer from unique to shared to make it accecible from outside the wellmodel
add method for surfacevolume well connection rate
changes are needed for tracerModel PR 
Depends on: OPM/opm-common#562 and OPM/ewoms#431
> add method for getting the surfacevolume well connection rate

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
In the post-merge discussion of #1658, @totto82 raised two problems:
- history matching wells were shut on one case,
- an infinite loop could occur.
This PR addresses the second problem.
About the first problem (shutting history wells), I cannot see how that would happen. I think the current master can print a message about shutting a well even though it would not actually shut it (if not a prediction well), and I hope that this holds for the case observed by @totto82 (if not, I need more information to fix). In any case, that printing error has been fixed here.
> Fix potential infinite loop

- flow/flow.cpp
this is the new and hip way to query this information from the ECL parser.
> flow: use eclipseState.simulatorConfig().isThermal() to determine whether energy ought to be conserved

- CMakeLists.txt
- flow/flow.cpp
Yes yes yes; we all agree this is grose. The `--version` commandline argument should have been handled by the parameter system, but it was not clear to me how to get that system to handle parameters without a trailing `=value` part?
If this PR is merged we will get the following behavior: When `flow` is invoked *exactly* as:
```
flow --version
```
it will print
```
flow $version
```
on stdout and `exit(0)`. The purpose of this is for *other programs* to be able easily check the version of a `flow` binary.
> Add special case handling of commandline argument "--version"

- opm/autodiff/BlackoilWellModel_impl.hpp
In the current master there can be an infinite loop if a well is shut down due to causing timestep cuts on the very first (sub)timestep of a report step, if the well had an event (new well or WCONPROD) at the start of the report step.
The fix uses information already stored in the WellTestState, but a new query function was needed, so this depends on OPM/opm-common#588.
> Avoid opening well that was shut on same time step.

- opm/autodiff/StandardWellV_impl.hpp
the way to get the result of an evaluation is by return value, i.e.,
z = fn.eval(x, y);
not by passing a separate argument to the eval() function like
fn.eval(x, y, z);
the `XYTabulated2DFunction` used the latter approach causing an API inconsistency with all other tabulation classes in opm-material. OPM/opm-material#319 fixes that but requires this mop-up as a consequence.
> use the common API opm-material for functions

- opm/autodiff/BlackoilDetails.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilModelParametersEbos.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/FlowLinearSolverParameters.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolverEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This PR
1) Adapt the ISTLSolverEbos class to the ewoms linear solver interface. i.e. adds methods prepareRhs(...), prepareMatrix(...) and solve(...)
2) Sets the linear solver to FlowIstlSolver and start calling it from the BlackoilModelEbos 
3) Moves makeOverlapRowsInvalid and WellModelMatrixAdapter from BlackoilModelEbos to ISTLSolverEbos
The PR should not give changes in results nor performance for any of the models.
> Adapt to linear solver api from ewoms

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/SimFIBODetails.hpp
- opm/core/wells/WellsManager.cpp
It depends the https://github.com/OPM/opm-parser/pull/1168 . 
Trying to handle the history matching well in the proper way instead of always being treated as RESV control wells. 
Basically, it tried to fixed the issue reported in https://github.com/OPM/opm-simulators/issues/1011 .
> Fixing history mode

- flow/flow.cpp
- flow/flow_ebos_blackoil.cpp
- flow/flow_ebos_blackoil.hpp
- flow/flow_ebos_energy.cpp
- flow/flow_ebos_energy.hpp
- flow/flow_ebos_gasoil.cpp
- flow/flow_ebos_gasoil.hpp
- flow/flow_ebos_oilwater.cpp
- flow/flow_ebos_oilwater.hpp
- flow/flow_ebos_oilwater_polymer.cpp
- flow/flow_ebos_oilwater_polymer.hpp
- flow/flow_ebos_polymer.cpp
- flow/flow_ebos_polymer.hpp
- flow/flow_ebos_solvent.cpp
- flow/flow_ebos_solvent.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
The parsing process creates four top level objects: `Deck, EclipseState, Schedule` and `SummaryConfig`. With the advent of the `ErrorGuard` class it makes sense to create all four objects with the same `ErrorGuard` instance - to ensure that the maximum amount of error messages are presented to the user, before we jump ship.
With this PR ~~-and the accompanying in ewoms,~~ all four objects are created in flow.cpp and then all are set in the ewoms model using setExternalXXXX(). This also enables a new flag `--ecl-strict-parsing` which will give the *all strict* behavior.
~~Depends on: https://github.com/OPM/ewoms/pull/457~~
> Create all objects

- opm/simulators/gatherDeferredLogger.cpp
The MPI_Pack() function does not support pointers-to-const until MPI-3.
This is the same type of change as the earlier PR #1637.
> Deferred Logger: Support Older MPI Implementations

- opm/autodiff/BlackoilWellModel_impl.hpp
Previously, this method did not take parallelism into account but just checked the local wells for the constraints. Depending on the load balancing of the wells this sometimes led to different return values of the function on different processors. As the output is used to limit the time step size, different processors were sometimes using different time steps in their local computations. This screwed up convergence checks int the nonlinear operator such that only some processor thought convergence was already achieved while others wanted to do more iterations.
With this commit the method now returns whether there is any well on any processor with the constraint being true.
Tested with model 2 using 2 processors. Test with 4 processors is running now.
> Make BlackoilWellModel::hasTHPConstraints() work correctly in parallel.

- opm/autodiff/FlowMainEbos.hpp
- opm/simulators/ParallelFileMerger.hpp
One PR three changes:
1. Use always uppercase *.PRT and *.DBG. 
2. When construcing the logfile names always strip the extension.
3. Only warn about and append parallel logging fallout if explicitly requested using new option --enable-logging-fallout-warning
Coments:
1) Seems consistent as all other output files seem to use that convention, too.  There was a comment/Issue about this but I cannot find it.
2) Is needed as we can start flow like `flow MODEL.` (omitting DATA) and would get MODEL..DBG and MODEL..PRT files.
3) Only annoys users that are not developing flow using MPI
> Warn about parallel logging fallout only on request / Use uppercase logfiles

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/ISTLSolverEbos.hpp
this is required to keep the linear solver of eWoms and opm-simulators identical, cf OPM/ewoms#461.
> adapt to the new preparation procedure of ewoms linear solvers

- opm/autodiff/ParallelOverlappingILU0.hpp
This silences a warning from clang. Base classes with virtual functions should always have a virtual destructor (although in this case there was no harm).
> Add virtual destructor to base class.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/ISTLSolverEbos.hpp
I tested #1712 without deriving the `EclFlowProblem` type tag from `FlowIstlSolver`, and it worked because the linear solver was still `Opm::ISTLSolverEbos` as the linear solver is set via the `LinearSolverSplice` a few lines down.
This time, I verified that the `Ewoms::Linear::ParallelBiCGStabSolverBackend` was used if the offending line was commented out. also, Norne worked fine with the default solver as long as the Schur complement for the wells was done explicitly.
Finally, the naming of the eWoms API is a bit inconsistent (`setMatrix()` vs. `setResidual()`). any opinions here? I'm fine with whatever.
> Properly adapt to the new linear solver API used by eWoms

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWellV.hpp
- opm/autodiff/StandardWellV_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
use deferred logging to log correctly in parallel for wells
> Correct Logging for Black Oil Well Model for parallel runs

- opm/autodiff/ParallelOverlappingILU0.hpp
Somehow some standard output when running MILU () is still there and
it really clutters the output and and makes it unusable. This commit
removes it from flow.
> Remove bogus debug output printing in MILU.

- flow/flow.cpp
- flow/flow_ebos_blackoil.cpp
- flow/flow_ebos_blackoil.hpp
- flow/flow_ebos_energy.cpp
- flow/flow_ebos_energy.hpp
- flow/flow_ebos_gasoil.cpp
- flow/flow_ebos_gasoil.hpp
- flow/flow_ebos_oilwater.cpp
- flow/flow_ebos_oilwater.hpp
- flow/flow_ebos_oilwater_polymer.cpp
- flow/flow_ebos_oilwater_polymer.hpp
- flow/flow_ebos_polymer.cpp
- flow/flow_ebos_polymer.hpp
- flow/flow_ebos_solvent.cpp
- flow/flow_ebos_solvent.hpp
this actually adds the external setup time to the TCPU output in `flow`. It depends on OPM/ewoms#470.
> flow: account for external setup costs

- flow/flow.cpp
This is mainly to get access to the `update_data` command for this PR: https://github.com/OPM/opm-common/pull/644
> Remove unused ParameterGroup.hpp header file

- opm/autodiff/FlowMainEbos.hpp
they are not used by `flow`. cf OPM/ewoms#479
> do not print the new core-ebos time step tuning parameters in the usage message

- flow/flow.cpp
- opm/autodiff/MissingFeatures.cpp
- opm/autodiff/MissingFeatures.hpp
Downstream of: https://github.com/OPM/opm-common/pull/617
> The missing features check takes a ParseContext argument

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
using the eWoms API for wells, the Schur compliment was not applied at all. If `BlackOilWellModel::linearize()` was made non-trivial, the Schur complement was applied twice in `flow`. With this patch, we only apply this using the eWoms API (in `BlackOilWellModel::linearize()`). I could not observe an effect on the convergence behaviour of `flow` for the cases which I tested (Norne and realization 5 of Model 2).
> well model: fix application of Schur complements

- opm/autodiff/BlackoilAquiferModel.hpp
- opm/autodiff/BlackoilAquiferModel_impl.hpp
the original purpose of these methods is to provide a checkpoint/restart mechanism using an ad-hoc file format. They might also be useful/required for implementing the adjoint functionality, though.
> aquifers: add missing serialize() and deserialize() methods

- ebos/eclproblem.hh
- opm/autodiff/FlowMainEbos.hpp
this is the downstream of OPM/ewoms#486: this property is actually not used by `flow` because `flow` implements its own Newton method, but it not renaming the property prevents `flow` from building.
> EclProblem: Rename NewtonRawTolerance to NewtonTolerance

- CMakeLists.txt
- ebos/ebos.cc
- ebos/ebos.hh
- ebos/eclequilinitializer.hh
- ebos/eclnewtonmethod.hh
- ebos/eclproblem.hh
- ebos/eclwellmanager.hh
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolverEbos.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
- opm/autodiff/WellInterface.hpp
This enables `ebos` to run Norne and other non-trivial data sets. While at it, adapt the tolerances by `ebos`.
This patch only affects the research simulator, i.e. `flow` is unaffected by it.
> ebos: use the same well model, aquifer model and linear solver as flow

- ebos/ecltransmissibility.hh
to make the current targeting case to run through. 
Something wired is that, now it runs, while I could not find the warning message anywhere.
> warning instead of throwing for nnc between active cells and inactive cells

- opm/autodiff/StandardWellV_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
Following the sign of the production rates and injection rates.
It is something we figured out when improving the multisegment well model, while it impacts much more cases with StandardWell, which are the most of the cases. 
So we created this PR for StandardWell separately for testing.
> correcting the sign of the accumulation term of StandardWell

- CMakeLists.txt
- ebos/ebos_gasoil.cc
- ebos/ebos_oilwater.cc
- ebos/ebos_plain.cc
- ebos/ebos_polymer.cc
- ebos/ebos_solvent.cc
- ebos/ebos_thermal.cc
these variants should cover most of the common use cases. For developers, the main advantage of using one of these instead of `flow` is that they have faster round-trip times because they build faster: 53 seconds for `ebos` instead 1 minute 25 for `flow` on my machine with 32 parallel build threads (for machines that have fewer than 9 physical cores, the difference is likely even larger).
That said, there are no plans to provide simulators for combinations of blackoil extensions or a "all-in-one" simulator like `flow`: If someone is interested in e.g., an oil-water simulator with polymer and energy enabled, a separate self-compiled executable should be added locally.
> add some ebos variants

- tests/test_equil.cc
This fixes hardcoded phase indices, at least the test succeeds with both current master (w, o, g) and a different (o, w, g) phase ordering. Component ordering does not matter here.
> Replace hardcoded phase indexing.

- opm/autodiff/BlackoilAmg.hpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FlowLinearSolverParameters.hpp
- opm/autodiff/ISTLSolverEbos.hpp
- tests/test_blackoil_amg.cpp
- tests/test_invert.cpp
- tests/test_multmatrixtransposed.cpp
This PR contains the work by @hnil on improving the CPR solver. It does not include any other solvers used for testing (such as amgcl), nor does it include the modifications to re-use parts of the preconditioner (that will come in a later PR). It should be ready for review.
Good options are:
% using one iteration of loop solver with quasiimpes
--use-cpr=true --cpr-max-iter=1 --cpr-ell-solvetype=0 --system-strategy="quasiimpes" --matrix-add-well-contributions=true
% using one iteration of loop solver with true impes
--use-cpr=true --cpr-max-iter=1 --cpr-ell-solvetype=0 --system-strategy="trueimpes" --matrix-add-well-contributions=true
% an alterative which normaly is slow but very good good on spe10
--use-cpr=true --cpr-max-iter=20 --cpr-ell-solvetype=3 --system-strategy="quasiimpes" …
> Improve CPR solver

- CMakeLists.txt
- ebos/ebos_altidx.cc
for some reason, this yields quite different results for norne than the default variant, e.g. when comparing PRESSURE, we get
```
> compareECL -k PRESSURE -t UNRST ebos/NORNE_ATW2013 ebos_altidx/NORNE_ATW2013 1 1e-4
Comparing 'ebos/NORNE_ATW2013' to 'ebos_altidx/NORNE_ATW2013'.
Comparing PRESSURE...
Occurrence in first file    = 9
Occurrence in second file   = 9
Value index                 = 0
(first value, second value) = (254.195, 253.191)
Program threw an exception: [/home/and/src/opm-common/build-cmake/fake-src/examples/test_util/EclRegressionTest.cpp:161] Deviations exceed tolerances.
The absolute deviation is 1.00311, and the tolerance limit is 1.
The relative deviation is 0.00394624, and the tolerance limit is 0.0001.
```
IMO this is a bug, but the reasons for it are currently …
> add an ebos variant which uses completely different numbering for phases and components

- ebos/eclproblem.hh
- opm/autodiff/ISTLSolverEbos.hpp
remove the unused `initialTemperature_` array in `EclProblem` and do not use the uninitialized `isIoRank_` member in `ISTLSolverEbos` anymore.
> Minor cleanups

- ebos/eclproblem.hh
the only thing which this does so far is to introduce the respective property and `ebos` will abort the run if the deck requests API tracking.
As usual for experimental features, `flow` is unaffected.
> ebos: add a stub implementation for API tracking

- ebos/alucartesianindexmapper.hh
- ebos/ebos.hh
- ebos/ecltracermodel.hh
- ebos/eclwriter.hh
this is part of the release maintainance. in this context "core ebos headers" means the headers located underneath the `ebos` directory which do not include the well model headers, and only those which are concerned with non-exotic functionality, e.g., the PolyhedralGrid and ALUGrid vanguards are not changed.
> ebos: make its core headers self sufficient

- opm/autodiff/MissingFeatures.cpp
See: https://github.com/OPM/opm-common/issues/701
The RPTSCEHD, WTEST and EDITNNC are (to best of my knowledge) fully supported all the way through and should be remowed from this list. The ECHO and NOECHO keywords are not supported - but if/when we are to support them that will be in the input layer, so it is really not the simulators business to complain about that.
> Update missing features

- ebos/ecloutputblackoilmodule.hh
Due to loadbalancing this vector might be empty under some circumstances.
Hence the old code would dereference the `end` iterator which is a bug.
> Cater for empty fipnum vectors in output code.

- ebos/eclproblem.hh
- ebos/eclthresholdpressure.hh
this is the simulator side of OPM/opm-common#693. Since this is an experimental feature, `flow` is unaffected.
> Support THPRESFT

- CMakeLists_files.cmake
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellstatefullyimplicitblackoil.cpp
This pull request extends class `WellStateFullyImplictBlackoil` to report segment-related quantities as `Opm::data::Segment` objects (included in `Opm::data::WellRates` objects).  All wells have at least a top
segment in the context of WellState FIBO, so there is a meaningful value to report for each well.
We put the extraction of segment-related quantities into a new helper function
```
WellStateFullyImplicitBlackoil::reportSegmentResults()
```
to avoid cluttering up the body of `report()` more than absolutely needed.
The primary use-case for this is assigning appropriate values to items 8 through 11 of restart vector `RSEG`.  In turn, this will enable restoring these quantities from a restart file.
The implementation is based on reading the surrounding and calling source code, so I am …
> WellState FIBO: Return Segment Vectors from report()

- flow/flow.cpp
- tests/test_vfpproperties.cpp
this is needed because of the API change implied by OPM/opm-common#710.
> also pass the parseContext and errorGuard to Opm::checkDeck()

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
it is just a temporary approach to recover the prediction case. In the
case, there is no group control, while there is some requirements of
well potential output.
> not throw for failure when failing in calculating well potentials

- ebos/ecltransmissibility.hh
Unfortunately, we first created NNC with applied EDITNNC and then still used the original NNC data to set the transmissibility. Thus we were actually ignoring EDITNNC.
This commit fixes this by using the data structure that has EDITNNC applied.
> [bugfix] Use NNC data with applied EDITNCC for transmissibility.

- opm/autodiff/BlackoilModelParametersEbos.hpp
With this, the multisegment well model will be used by default for wells that are defined as multisegment in the input deck. Override this on the command line with `--use-multisegment-well=false` to force using the standard well model for such wells.
> Enable multi-segment wells by default.

- compareECLFiles.cmake
- opm/autodiff/BlackoilWellModel_impl.hpp
And also removing the explicit using of `--use-multisegment-well` in `compareECLFiles` since the multisegment well is activated by default through PR #1807
> Correcting a small assertion mistake introduce in PR#1803

- opm/simulators/DeferredLogger.cpp
- opm/simulators/DeferredLogger.hpp
- opm/simulators/DeferredLoggingErrorHelpers.hpp
This keeps from logging the same messages again. Also add `clearMessages()` method, which is useful to clear the local container after gathering into a global container (which leaves the local containers untouched).
> Clear DeferredLogger's message container after logging.

- ebos/ebos.hh
this avoids regressions for decks that use well testing and makes `ebos` work as expected if UMFPACK is not available, but obviously it will not work for decks that use multisegment wells in earnest.
`flow` is unaffected by this because it does not use this type tag.
> ebos: use the non-multisegmented well model by default

- ebos/eclbasevanguard.hh
this enables the deck diagnostics (the saturation function diagnostics from opm-simulators and opm-common's `Opm::checkDeck()`) for the `ebos` simulators. as usual, `flow` is unaffected by this.
> Ebos deck diagnostics

- ebos/eclproblem.hh
it is read in the beginRestart() method, reorder code accordingly.
ref valgrind log
```
==45745== Conditional jump or move depends on uninitialised value(s)
==45745==    at 0x177DC2A: double const& std::min<double>(double const&, double const&) (stl_algobase.h:200)
==45745==    by 0x17FF497: Ewoms::EclProblem<Ewoms::Properties::TTag::EclFlowProblem>::readEclRestartSolution_() (eclproblem.hh:2450)
==45745==    by 0x17C9451: Ewoms::EclProblem<Ewoms::Properties::TTag::EclFlowProblem>::initialSolutionApplied() (eclproblem.hh:1482)
==45745==    by 0x17B4198: Ewoms::FvBaseDiscretization<Ewoms::Properties::TTag::EclFlowProblem>::applyInitialSolution() (fvbasediscretization.hh:599)
==45745==    by 0x179C0CD: Opm::FlowMainEbos<Ewoms::Properties::TTag::EclFlowProblem>::setupEbosSimulator() …
```
> fixed: use of restartTimeStep() before it has been read

- opm/simulators/linalg/BlackoilAmg.hpp
- opm/simulators/linalg/BlackoilAmgCpr.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/ParallelOverlappingILU0.hpp
- opm/simulators/linalg/ParallelRestrictedAdditiveSchwarz.hpp
- opm/simulators/linalg/amgcpr.hh
This PR fixes compilation issues with flow when using the current DUNE master. In dune-istl the return value of the ConstructionTraits and the Constructor parameters have been changed from raw pointers to std::shared_ptr.
> Adjust to shared_ptr change in dune-istl >= 2.7.

- ebos/eclproblem.hh
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
this PR is a follow-up to #1775. It actually ensures that the correct time step and episode sizes are used by flow. For some reason, this seems to require a data update, but I have not drilled into why this is the case yet and I would like to avoid wasting too much time on this.
maybe @bska or @GitPaean know what could cause the difference...
> flow: provide the correct episode size

- ebos/eclbasevanguard.hh
This just adds a empty container for summary values to be  
used by udq and actionx
To be filled later see #1831
> add a summary state member in eclproblem

- ebos/eclwriter.hh
This restores restart for a model where not every episode is stored. 
in  `void readEclRestartSolution_() `
the episodeidx is set `initconfig.getRestartStep() - 1;`
while the output writer in opm-common expects the episode index to be equal to   `initconfig.getRestartStep()`
A better fix may be to pass the episodeidx from initconfig directly?
Any comment @andlaus?
> Fix episode index for restart

- ebos/ecloutputblackoilmodule.hh
Provide output data for:
BOSAT
BWKR
BOKR
BKRO
BGKR
BKRG
BKRW
BWPC
BGPC
BVWAT
BWVIS
BVGAS
BGVIS
BVOIL
BOVIS
This pull request is needed in order to output Summary data, see pull request OPM/opm-common#724
>  Changes to provide Summary data output of additional block variables

- flow/flow.cpp
Previously, each process did this in a parallel run which clutters the terminal output quite a bit in a parallel run.
> Let only master process print information about exception.

- flow/flow.cpp
Previously this was only done if there were no other parameters on the
command line. That approach feels a bit unusual.
> If requested always print version and exit.

- tests/update_reference_data.sh
If a simulation run intentionally changes an RFT file, then that change should be reflected in the new reference data.
This is in preparation of merging PRs OPM/opm-common#765 and #1833.
> Update Data: Make Protocol Aware of RFT Files

- opm/simulators/utils/DeferredLoggingErrorHelpers.hpp
With this change we throw something we actually catch.
> throw runtime_error instead of logic_error

- ebos/eclcpgridvanguard.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/ecltracermodel.hh
- ebos/eclwellmanager.hh
- opm/autodiff/SimFIBODetails.hpp
- opm/core/wells/WellCollection.cpp
- opm/core/wells/WellCollection.hpp
- opm/core/wells/WellsGroup.cpp
- opm/core/wells/WellsGroup.hpp
- opm/core/wells/WellsManager.cpp
- opm/core/wells/WellsManager.hpp
- opm/core/wells/WellsManager_impl.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellV.hpp
- opm/simulators/wells/StandardWellV_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellConnectionAuxiliaryModule.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellcollection.cpp
- tests/test_wellmodel.cpp
- tests/test_wellsgroup.cpp
- tests/test_wellstatefullyimplicitblackoil.cpp
With this PR the simulator is updated to use the new `Well2` class from opm-common. The changes in this PR are mostly mechanical - and include:
1. The well type has been renamed to `Well2`.
2. The previous API made extensive use of naked `Well *` pointers, we now use `Well2` or `Well2&`.
3. Previously the properties - like connection sets and production properties were all accessed through a function with a timestep argument - that has been removed.
Downstream of: https://github.com/OPM/opm-common/pull/731
The work in opm-common should get more testing and scrutiny before merge, but the part here  should not change significantly whatever happens to opm-common - and hence should be ready for review.
> Use new well implementation Well2 from opm-common

- flow/flow.cpp
No reason to `throw` our way out of `main`.
> Return EXIT_FAILURE in main() instead of rethrow

- ebos/eclwellmanager.hh
- opm/autodiff/SimFIBODetails.hpp
- opm/core/wells/WellsGroup.cpp
- opm/core/wells/WellsManager.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/StandardWellV_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_wellsgroup.cpp
This is now ready for review - and merging. Observe that essentials of the current PR is that well controls come from the `well.injectionControls(const summaryState&)` and `well.productionControls(const summaryState&)` functions instead of the previous `well.getInjectionProperties()` and `well.getProductionProperties()` methods. Currently the `SummaryState` is typically just default instantiated, and as such no UDA evaluation can be performed - that is still OK, as the same still applies to corresponding opm-common PR.
Actually passing the simulators `SummaryState` instance around will be the topic of a subsequent PR #one-step-at-a-time.
Followup to: https://github.com/OPM/opm-common/pull/762
Merged: ~~After: https://github.com/OPM/opm-simulators/pull/1815~~
> Use wells2 controls

- opm/simulators/wells/BlackoilWellModel_impl.hpp
:disappointed:  - merging #1831 broke master - a new use of `WellxxxProperties` had been merged since the last jenkins run.
Fixup here.
> Fixup: Use ProductionControls and InjectionControls

- ebos/eclproblem.hh
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This makes restart possible without EQUIL i.e. it fixes  #1828. 
Not tested on the "real" case that motivated the simple test case.
> Make it possible to restart without computing initial conditions

- ebos/eclproblem.hh
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
Now that the book keeping for time stepping is correct even in `flow`, this parameter has become redundant.
> EclProblem: remove the isSubstep parameter from writeOutput()

- tests/run-regressionTest.sh
update of script `run-regressionTest.sh`. Should be merged after PR OPM/opm-common#765. This PR will enable testing of RFT files if these are found in opm-tests reference folder.
Has been tested locally by manually copying RFT files from opm-simulators/build/tests/results folders
```
./flow+msw_model_1/MSW_MODEL_1.RFT   => opm-tests/model1/opm-simulation-reference/flow/MSW_MODEL_1.RFT
./flow+base_model_1/BASE_MODEL_1.RFT  => opm-tests/model1/opm-simulation-reference/flow/BASE_MODEL_1.RFT  
.flow+faults_model_1/FAULTS_MODEL_1.RFT  => opm-tests/model1/opm-simulation-reference/flow/FAULTS_MODEL_1.RFT
```
> run compareECL once, checking all files in one go

- ebos/eclbasevanguard.hh
- ebos/eclwriter.hh
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Followup to: https://github.com/OPM/opm-common/pull/795
Again a step in UDQ/ACTIONX sequel
> Call Summary::eval() and ::add_timestep separately 

- CMakeLists.txt
- ebos/ebos_blackoil.cc
- ebos/ebos_blackoil.hh
- ebos/ebos_gasoil.cc
- ebos/ebos_gasoil.hh
- ebos/ebos_gasoil_main.cc
- ebos/ebos_main.cc
- ebos/ebos_oilwater.cc
- ebos/ebos_oilwater.hh
- ebos/ebos_oilwater_main.cc
- ebos/ebos_polymer.hh
- ebos/ebos_polymer_main.cc
- ebos/ebos_solvent.cc
- ebos/ebos_solvent.hh
- ebos/ebos_solvent_main.cc
- ebos/ebos_thermal.cc
- ebos/ebos_thermal.hh
- ebos/ebos_thermal_main.cc
- ebos/eclbasevanguard.hh
- ebos/mebos_main.cc
- flow/flow_ebos_blackoil.cpp
- flow/flow_ebos_energy.cpp
- flow/flow_ebos_gasoil.cpp
- flow/flow_ebos_oilwater.cpp
- flow/flow_ebos_oilwater_polymer.cpp
- flow/flow_ebos_polymer.cpp
- flow/flow_ebos_solvent.cpp
- flow/flow_tag.hpp
`mebos` works similarly as `flow`, but in contrast to `flow`, `mebos` only creates the deck in the common code path whilst the 'EclipseState' and the other higher-level parser objects are always created internally by the vanguard. this approach avoids code duplication and the worst effects of parser API creep.
to avoid having to compile non-trivial compile units multiple times, the actual code of the variants is moved into `ebos_$VARIANT.{hh,cc}` files and the respective compile units are each put into a small static library whilst the main function of said libraries are invoked by either the multiplexed or the respective specialized simulator's `main()`. This is also somewhat similar of how `flow` works, with the difference that `mebos` uses the blackoil variant to determine the …
> add `mebos`, a multiplexed ebos variant

- ebos/eclproblem.hh
Now Ebos outputs summary data for each substep as it should. This should not affect Flow.
> Let the output writer determine what to write in ebos

- opm/core/wells/WellCollection.cpp
- opm/core/wells/WellCollection.hpp
- opm/core/wells/WellsGroup.cpp
- opm/core/wells/WellsGroup.hpp
- opm/core/wells/WellsManager.cpp
- opm/core/wells/WellsManager.hpp
- opm/core/wells/WellsManager_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_wellcollection.cpp
- tests/test_wellsgroup.cpp
Code previously used a local - fresh copy to initialize the well controls, now we use the shared `SummaryState`which has UDQ variables initialized.
Depends on: https://github.com/OPM/opm-common/pull/820
> Use the shared SummaryState instance when initializing well rates

- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
When there are multiple time steps between two report steps, it can be difficult to see where in the total simulation time a time step is. Hence, there has been user request for the time steps to include the same day and date information found in report steps. This PR provides that.
> Adding time and date to time step report

- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
Two important wtest messages was only visible in the DBG-file. With this pull request they are now also shown in the terminal/LOG and in the PRT file.
> Moved well test messages from debug to log and prt

- tests/test_nncsorter.cpp
This caused some issues on my machine and it is supposed to be done by any compile unit anyway.
> NNC sorter test: include config.h

- opm/simulators/flow/FlowMainEbos.hpp
Now prints an error message in this case:
```
../../opm-simulators/opm-parallel/bin/flow  --outputsir=bla SPE1CASE2.D
**********************************************************************
*                                                                    *
*                      This is flow 2019.10-pre                      *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*             including solvent and polymer capabilities.            *
*          For more information, see https://opm-project.org         *
*                                                                    *
**********************************************************************
Reading deck file 'SPE1CASE2.DATA' …
```
> Notify user that we are aborting because of unused keywords.

- opm/core/wells/well_controls.c
While here, also print both `ctrls1` and `ctrls2` instead of printing `ctrls2` twice.
> Format Specifier '%p' Requires Pointers to Void

- ebos/ebos.hh
- ebos/eclproblem.hh
- opm/simulators/flow/FlowMainEbos.hpp
Together with OPM/ewoms#522, this improves the time integration code of `EclProblem`. This piece of code caused problems when I was using `ebos` for one of the confidential decks I need to work with when tuning was enabled and the minimum time step size was undercut. Since `flow` rolls its own time stepping code, it is almost certainly unaffected.
@totto82: It would be good if you could ensure that the confidential cases which I recently lost access to do not regress with tuning enabled. (I still expect the majority of them to be faster without tuning, but if tuning is enabled, `ebos` with these patches ought not to be slower than on the current master.)
> Improve time integration

- ebos/ebos_blackoil.cc
- opm/simulators/flow/FlowMainEbos.hpp
this is the downstream for OPM/ewoms#524. With this patch, there's no change at all for `flow` compared to the current behavior, `ebos` and its variants will complain when it encounters unused parameters and the `--help` handling is correct for `mebos`.
> mebos, flow: adapt to the eWoms changes in handling unknown parameters

- opm/simulators/wells/MultisegmentWell_impl.hpp
Negative values can happen if the pressure is outside the table range. 
This makes the soon to come test case involving MSW injector reasonable well potentials.
> Make sure rvmax and rsmax is non-negtive in the getSurfaceVolume for MSW

- ebos/ebos.hh
this is the companion PR to OPM/ewoms#526. It flips the default behavior when encountering a failed time integration for the minimum time step size for `ebos`. as usual, `flow` is unaffected by OPM/ewoms#526 as well as by this.
> ebos: by default, do not abort the simulation as quickly

- compareECLFiles.cmake
- tests/update_reference_data.sh
When https://github.com/OPM/opm-common/pull/870 is merged I consider the UDQ/UDA features sufficiently mature to enable integration testing. Some random plots shown below - more can be provided.
Although I am probably the most trigger happy self-merger around I will *not* push this one in - but I sincerely hope someone else will do!
PS: When this is in I might go and get really drunk - this has been a long haul.
> Add UDQ_WCONPROD model to integration testing

- flow/flow.cpp
The output code used to have an unfriendly error mode in which we would unceremoniously crash&mdash;without writing any data&mdash;if some declared array dimensions from RUNSPEC weren't big enough to hold all the dynamic objects (wells, groups, connections &c).
Since commit OPM/opm-common@7986e99e (PR OPM/opm-common#640) we've had an extension that sizes the output tables according to the maximum of the active number of entities (e.g., number of connections, groups, wells, wells per group) and the declared maximums in RUNSPEC keyword WELLDIMS.  On the other hand if the active number of entities exceeds the declared maximums, then the output files won't be compatible with ECLIPSE, and users with access to ECLIPSE won't be able to restart an ECLIPSE run from an OPM base run.
This PR …
> Flow: Verify Consistent Array Dimensions

- opm/simulators/flow/MissingFeatures.cpp
See: #1930 - fixed the `COMPORD` keyword in the machinery for partially supported keywords.
> Fix error message for COMPORD partially support keyword

- ebos/eclbasevanguard.hh
- ebos/eclcpgridvanguard.hh
Add command line option for edge-weight strategy in CpGrid loadBalance method. The option is:
--edge-weights-method=INTEGER  Choose edge-weighing strategy: 0=uniform, 1=trans, 2=log(trans). Default: 1
These options depend on the opm-grid PR: https://github.com/OPM/opm-grid/pull/373.
> Edge weights method

- tests/update_reference_data.sh
Resurrected from: #1927. I have been more-than-usually dim when it comes to the arguments in the `tests`directory - would be good if @akva2 could quality check it.
This should be safe to merge right away, the other parts of #1927 - which have been superseded by  https://github.com/OPM/opm-common/pull/876 - can not be merged before #1928 / #1970 has been fully solved.
> Change testname for UDQ test

- compareECLFiles.cmake
This should hopefully allow running the rest of the tests in parallel, while not slowing down the parallel tests to a grind.
> changed: mark parallel tests for serial execution

- opm/simulators/flow/MissingFeatures.cpp
The `COMPDAT`keyword had sneaked in on the list of unsupported keywords.
> Remove COMPDAT from list of unsupported keywords

- flow/flow.cpp
- flow/flow_blackoil_dunecpr.cpp
- flow/flow_ebos_blackoil.cpp
- flow/flow_ebos_blackoil.hpp
- flow/flow_ebos_energy.cpp
- flow/flow_ebos_energy.hpp
- flow/flow_ebos_foam.cpp
- flow/flow_ebos_foam.hpp
- flow/flow_ebos_gasoil.cpp
- flow/flow_ebos_gasoil.hpp
- flow/flow_ebos_oilwater.cpp
- flow/flow_ebos_oilwater.hpp
- flow/flow_ebos_oilwater_polymer.cpp
- flow/flow_ebos_oilwater_polymer.hpp
- flow/flow_ebos_oilwater_polymer_injectivity.cpp
- flow/flow_ebos_oilwater_polymer_injectivity.hpp
- flow/flow_ebos_polymer.cpp
- flow/flow_ebos_polymer.hpp
- flow/flow_ebos_solvent.cpp
- flow/flow_ebos_solvent.hpp
- flow/flow_tag.hpp
- opm/simulators/flow/FlowMainEbos.hpp
[This](https://github.com/OPM/opm-common/pull/933) was created and merged to put messages like:
```
6 Reading GAS      from: /path/udq_actionx/UDQ_WCONPROD.DATA:45
```
in the `.PRT` file - but it turned out that no messages appeared in the file, and as debugged by @attgeir - that was because the logging system was not initialized when the parsing was performed. This PR shuffles things a bit around, to facilitate initialization of the logging system before the parsing starts. It even works on Atgeirrs machine.
NB: this endevaour has revealed that *no* log messages originating from the opm-common setup process have been logged!
> Setup logging before the simulator is initialized

- ebos/eclproblem.hh
- ebos/ecltracermodel.hh
- ebos/eclwellmanager.hh
- opm/core/wells/WellCollection.cpp
- opm/core/wells/WellsGroup.cpp
- opm/core/wells/WellsManager.cpp
- opm/core/wells/WellsManager_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/SimFIBODetails.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellmodel.cpp
Followup to: https://github.com/OPM/opm-common/pull/972
> Adapt to enum changes

- flow/flow.cpp
With the current master, if the output directory does not exist, no DBG or PRT files will be created. This is because the code that checks for its existence is now run only after the creation of the log streams, which in turn was moved recently to get proper logging from the parser.
With the PR, it works again as intended.
> Ensure output dir exists before creating log streams.

- tests/update_reference_data.sh
A while back .rft was added to the list of files.
Since most cases lack these files, we got a lot of false positives leading to confusing commit messages in the update_data trigger.
> fixed: don't flag error if rfts are missing (most cases lack them)

- opm/core/wells/WellsManager_impl.hpp
getCellThicknes changed to getCellThickness. This should be merged together with PR OPM/opm-common#1009 in opm-common
(Edit: corrected link to point to the opm-common PR instead of a PR in this repo)
> Fixed typo for EclipseGrid member function

- flow/flow.cpp
- opm/simulators/flow/FlowMainEbos.hpp
Currently, the deck will be parsed fully before aborting. This PR moves the checking for unknown parameters to the static `setupParameters_()` method, where already things like parameter and property printing is checked for.
> Abort the run before reading the deck if there are unknown params.

- ebos/ecloutputblackoilmodule.hh
In particular, the `.type()` function is renamed to `.category()`, and it no longer returns a LibECL type.  Similarly, the `.num()` function has been renamed to `.numericID()`.
Downstream from OPM/opm-common#1049.
> Chase SummaryState API Change

- opm/simulators/flow/FlowMainEbos.hpp
The PRT header has been confusing. In particular, users have been mistaking kernel version for flow version. With these changes there should not be room for any confusion in that respect.
> Make PRT header self-explanatory

- opm/simulators/wells/StandardWell_impl.hpp
Only occurs when compiling with -DNDEBUG since the body of the for-loop is an assert using the loop variable. Loop is now deactivated.
> Fixes unused variable warning in standard wells.

- opm/simulators/wells/StandardWell_impl.hpp
Only occurs when compiling with -DNDEBUG since the body of the
for-loop is an assert using the loop variable. Loop is now deactivated.
this is PR #2058 backported to the release
> Fixes unused variable warning in standard wells. (PR 2058 backported)

- flow/flow.cpp
This starts with #2059 
While discussing a suitable fix for #2059 with @atgeirr it became clear that there is a divide through the code when it comes to logging and parallell behavior:
**opm-common:** This module is totally unaware of MPI and parallell execution. The opm-common code makes many calls to `OpmLog::xxxx()` - these messages will come repeated for every PE. Up until quite recently there has been a bug in the setup of the logging, which resulted in *no messages from opm-common* - we therefor never saw these repeated messages. This bug was fixed  ~1 month ago, and now log messages from opm-common are repeated for every PE - as pointed out in #2059.
For opm-common the situation is that any logging message should be identical on all PE's, and we are only interested in the messages …
> stdout logging only for rank 0
