OPM/opm-simulators

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
The number of perforations may change due to completions beeing shut.
If the number of perforations changes the perfPhaseRates are set to
equal the wellRates/(number of perforations) instead of the values from
the previous time step.
> Only copy perfPhaseRates if number of perforations is equal.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
The derivatives of the vappars are included in the Jacobian.
To avoid inf derivatives for vap<1, the oil saturation is restricted
from below by sqrt(epsilon).
With this PR, Norne run smoothly past the troublesome parts from 484 days.
> Include derivatives of vappars

- dune.module
This is in line with and closes issue #295
> Explicitly list dune-istl as a dependency.

- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
Remove warning about unused variable.
> convergenceReduction: remove warning.

- examples/opm_init_check.cpp
- opm/autodiff/BackupRestore.hpp
- opm/autodiff/BlackoilPropsAd.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/RedistributeDataHandles.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
With this the number of warnings emitted is severely reduced (there are still some that I am still working to get rid of). Also adapt to a modified WellsManager constructor, OPM/opm-core#758.
> Fix warnings and adapt to API changes

- opm/autodiff/FullyImplicitBlackoilSolver.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
This PR allows to set tolerances for the Newton and Linear solver in the parameter file. 
The default values are the same as before.
> Allow tolerances to be set in parameter files.

- examples/flow.cpp
- examples/flow_cp.cpp
Followup to: https://github.com/OPM/opm-parser/pull/398
> Using OpmLog instead of explicit logger

- examples/flow_cp.cpp
Moved output directory code near top again, changed rank query to use Dune::MPIHelper instead of the grid.
> Fix compile error instroduced by merging #275.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
this adds the "plumbing" in the simulator for OPM/opm-core#765. On my machine, there were no ctest regressions, SPE1 and SPE9 did neither regress with regard to the results nor peformance and the "thermal SPE1" testcase (which is going to be a separate PR for opm-data) ran through.
I haven't tested if `make install` is useable and if it works on old compilers like GCC 4.4. This should done by some Jenkins instance, though.
> Implement temperature dependent density

- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
Also, make the parameters const to avoid this problem in the future.
> NewtonIterationBlackoilCPR: fix uninitialized parameter

- opm/autodiff/CPRPreconditioner.hpp
This PR restores the compatibility with the DUNE 2.2 version. 
DISCLAIMER: I really DON'T recommend to use DUNE 2.2, since it's relatively old and also slower, i.e. when  running flow on SPE9 and Norne there are significant performance decreases. So use DUNE 2.3.1 instead. I also recommend to not support DUNE 2.2 anymore.
> CPRPreconditioner: make compile with DUNE 2.2.

- opm/autodiff/GeoProps.hpp
The volume weighted averaged NTG values are used to get more reasonable x
and y transmissibilities for the cells effected by the MINPV grid
processing algorithm.
This commit starts the process of supporting the MINPVF keyword
where upscaled properties are used for the merged/filled cells.
The remaining work will be done after MINPV is supported in the same way 
as the industry standard simulator. 
Tested on Norne. It reduces the discrepancy in well C-1H.
> Use average NTG values for merged cells due to MINPV algorithm

- examples/flow.cpp
- examples/flow_cp.cpp
The new startup message:
- Looks better.
- Gives the URL to OPM.
- Tells people that flow_cp is experimental.
This is a PR to master, but I may include this in the release branch as well.
> Provide nicer startup message that includes opm-project URL.

- debian/control
Please backport to release branch.
> update debian packaging

- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp
These should work well for both Norne and the SPE cases.
> Modify default solver parameters.

- examples/flow.cpp
- examples/flow_cp.cpp
Will only initialize and write INIT/EGRID files if NOSIM keyword is spesified in the deck.
Requisres that this https://github.com/OPM/opm-parser/pull/446
is merged first.
> Implemented NOSIM keyword.

- opm/autodiff/RedistributeDataHandles.hpp
The usual size_t versus int stuff...
> Fix unsigned/signed comparison warning.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/SimulatorBase_impl.hpp
This PR is the updated version of the PR OPM/opm-autodiff#396 with updating most of the comments there. The new PR is producing exactly the same behavior with the original PR when running the Norne case. 
Some warnings are generated compared with the master branch, which should also be fixed before merging.
> Solve well equation initially_continuing from PR OPM/opm-autodiff#396

- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
Forgot to push this, sorry for the extra PR.
> Move forming interleaved matrix to own function

- opm/autodiff/AutoDiffHelpers.hpp
- opm/autodiff/BlackoilModel.hpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
1. NNC are added the grad, div and average operators
2. NNC are added the upwindSelector
3. NNC transmissibilities are added to the face transmissibilities
Tested on a modified SPE1 case where NNC are added.
Does not effect Norne. 
@qilicun I would appriciate if you could test this in combination with PINCH and MINPV
Depends on OPM/opm-parser#491
> Add support for NNC in the simulator

- opm/autodiff/SimulatorBase_impl.hpp
is_parallel_run_ was not correctly initialized since it was initialized inside another if statement. 
This PR fixed this.
> SimulatorBase[bugfix]: is_parallel_run_ was not initialized correctly.

- examples/flow.cpp
- examples/opm_init_check.cpp
- examples/sim_2p_incomp_ad.cpp
- tests/test_boprops_ad.cpp
- tests/test_rateconverter.cpp
- tests/test_transmissibilitymultipliers.cpp
Followup PR to: https://github.com/OPM/opm-parser/pull/527
> Added ParseMode argument to parse and EclipseState

- examples/flow.cpp
Followup to: https://github.com/OPM/opm-parser/pull/546
> Using new string based ParseMode api.

- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
Restores compilation in debug mode.
> Change assert() to use actual variables present.

- CMakeLists_files.cmake
Seems somebody was in a hurry and didn't test this.
> fixed: install correct files

- opm/autodiff/VFPInjProperties.cpp
- opm/autodiff/VFPProdProperties.cpp
Variable was used only in assert().
> Silence unused variable warning (release mode only).

- opm/autodiff/BlackoilModelBase_impl.hpp
- tests/test_vfpproperties.cpp
This PR adds support for proper(?) switching to and from THP control. 
Appears to work for non-trivial synthetic case, but has not been properly verified.
> Targets for switching to/from THP control (Vertical flow performance)

- examples/flow.cpp
- examples/flow_solvent.cpp
Dependent on: https://github.com/OPM/opm-core/pull/857
> Added suport for new Threshold Pressure behavior

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
https://github.com/OPM/opm-parser/pull/570
> Using TableManager to get tables.

- opm/autodiff/BlackoilSolventModel_impl.hpp
> BUGFIX Fix out of bounds error

- opm/autodiff/AdditionalObjectDeleter.hpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
With this PR and zoltan activated via OPM/dune-cornerpoint#163 and #459 it is finally possible to at least run norne in parallel with the interleaved ordering/blocks.
> Fix parallel flow_cp for the interleaved case

- examples/flow.cpp
- examples/flow_solvent.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
> Update for removed constructor args.

- opm/autodiff/RateConverter.hpp
In the process, generalise the notion of region properties.  We introduce a new helper class
```C++
Details::RegionAttributes<RegionId, Attributes>
```
that provides lookup from a `RegionId`, typically an `int`, to a user-defined set of `Attributes`--in this case pressure and temperature.
While here, mark `SurfaceToReservoirVoidage::calcCoeff()` as `const` because it doesn't need to modify any internal state and refactor the implementation to eliminate repeated calculations of
```C++
ADB::constant(X)
```
Note: This depends on OPM/opm-core#872 and must be merged in concert.
> Chase API update of opm-core's RegionMapping

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorBase_impl.hpp
This PR needs OPM/opm-core#884.
> SolverFullyImpl: avoid multiple output of redundant information in parallel.

- opm/autodiff/ParallelDebugOutput.hpp
> Silence unused argument warning.

- examples/flow.cpp
- examples/flow_solvent.cpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This PR revised the ParallelDebugOutput such that it is only used in parallel simulations.
> ParallelDebugOutput: only use parallel output when mpi size > 1.

- opm/autodiff/AutoDiffBlock.hpp
- opm/autodiff/AutoDiffMatrix.hpp
- tests/test_autodiffmatrix.cpp
This PR adds documentation to AutoDiffMatrix, and changes the how to create an identity matrix.
> Autodiffmatrix beautification

- opm/autodiff/SolventPropsAdFromDeck.cpp
Followup to: OPM/opm-parser#585
Comments are welcome - but this should not be merged before the opm-parser PR is merged.
> Changed Table code to use TableContainer

- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
Fixes some very minor deficiencies of #496.
> Fix compile warning and error message.

- examples/flow.cpp
- examples/flow_solvent.cpp
- examples/sim_2p_incomp_ad.cpp
- opm/autodiff/AutoDiffHelpers.hpp
- opm/autodiff/AutoDiffMatrix.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/ImpesTPFAAD.cpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationBlackoilSimple.cpp
- opm/autodiff/NewtonIterationUtilities.cpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
- opm/autodiff/SimulatorIncompTwophaseAd.cpp
- opm/autodiff/SolventPropsAdFromDeck.hpp
- opm/autodiff/TransportSolverTwophaseAd.cpp
- opm/autodiff/VFPInjProperties.cpp
- opm/autodiff/VFPProdProperties.cpp
- opm/autodiff/WellDensitySegmented.cpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
this needs to be merged after OPM/opm-common#55
> Error macros to opm common

- redhat/opm-autodiff.spec
> update redhat packaging

- examples/flow.cpp
1. Added new parameter group string: "solver_approach" which can take
the values {direct, cpr, interleaved}.
2. Hierarchy:
i   If a value is set in the parameter group that takes absolute
presedence.
ii  If the Eclipse input deck asks for CPR - you get CPR.
iii You get the flow default - currently interleaved
> Changes to solver approach configuration:

- opm/autodiff/RedistributeDataHandles.hpp
Since the refactoring of @dr-robertk there is no need for this anymore.
> Remove unnecessary shared_ptr for geology and black oil properties during redistribution.

- CMakeLists_files.cmake
- dune.module
- examples/flow.cpp
- examples/flow_solvent.cpp
- opm/autodiff/moduleVersion.cpp
- opm/autodiff/moduleVersion.hpp
The new moduleVersionName() function is used to print the version name in the startup messages of the flow simulators.
> Add moduleVersion() utility and update dune.version.

- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
> ParallelDebugOutput: initialize wells with current report step number.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
This also required the minIter() accessor to be made public, so I made all of the remaining accessors public.
This fixes #544.
> Honor the min_iter parameter.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
Fix build issue in Debug mode. See comments in #554
> Fix typo in BlackoilPropsAdFromDeck

- opm/autodiff/BlackoilModelBase_impl.hpp
> Improve threshold pressure mismatch error message.

- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent_impl.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/polymer/PolymerInflow.cpp
- opm/polymer/PolymerInflow.hpp
- opm/polymer/PolymerProperties.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer_impl.hpp
This PR is a followup to: https://github.com/OPM/opm-parser/pull/649
The initial purpose of this PR was to adapt to the new Table api from opm-parser, however as a side effect the main volume in changes is in the `flow_solvent` and `flow_polymer` implementations where the `Deck` class was incorrectly used to infer solvent and polymer properties respectively.
OK - this has now run through Norne successfully.
> Table column

- opm/autodiff/GeoProps.hpp
- opm/polymer/PolymerProperties.cpp
- opm/polymer/PolymerProperties.hpp
- tests/test_vfpproperties.cpp
Adopting to opm-parser PR#661, add previously missing includes.
OPM/opm-parser#661
> Improve includes from opm-parser

- opm/autodiff/DuneMatrix.hpp
In the current master of dune-istl some member variables of BCRSMatrix have changed. This PR takes care of this change.
> DuneMatrix: adjust to changes in dune 3.0

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
opm-parser pull #695
https://github.com/OPM/opm-parser/pull/695
Can be merged before upstream.
> Add missing opm-parser headers

- opm/autodiff/FlowMain.hpp
This PR is the first try to integrate relperm diagnostics into flow, that is before running the simulator, check relative permeability first and write all the information to log file.
Any comments are welcome.
> integrate relperm diagnostics into flow.

- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/SolventPropsAdFromDeck.cpp
- opm/autodiff/SolventPropsAdFromDeck.hpp
Pressure effects are added to relative permeability, capillary pressure,
viscosity and density miscibility. 
Tested on the SPE1 and SPE9 test cases see OPM/opm-data#89
> Add support for PMISC

- opm/autodiff/FlowMain.hpp
EclipsePRTLog has full functionalities of StreamLog and CounterLog, will have more functionalities later.
> use EclipsePRTLog.

- examples/opm_init_check.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
- tests/test_boprops_ad.cpp
- tests/test_rateconverter.cpp
- tests/test_transmissibilitymultipliers.cpp
- tests/test_vfpproperties.cpp
Depend on https://github.com/OPM/opm-core/pull/976
> Rename parse mode

- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
OpmLog is on its way from parser to common; 
when these PRs have been merged, this one should be merged. 
https://github.com/OPM/opm-common/pull/90/files
https://github.com/OPM/opm-parser/pull/721
https://github.com/OPM/opm-core/pull/978
> Changed includes due to OpmLog moved from parser to common

- CMakeLists_files.cmake
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/BackupRestore.hpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/BlackoilSolventState.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/RedistributeDataHandles.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/TransportSolverTwophaseAd.cpp
- opm/polymer/CompressibleTpfaPolymer.cpp
- opm/polymer/IncompTpfaPolymer.cpp
- opm/polymer/IncompTpfaPolymer.hpp
- opm/polymer/PolymerBlackoilState.cpp
- opm/polymer/PolymerBlackoilState.hpp
- opm/polymer/PolymerState.cpp
- opm/polymer/PolymerState.hpp
- opm/polymer/SimulatorCompressiblePolymer.cpp
- opm/polymer/SimulatorPolymer.cpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/polymerUtilities.cpp
- tests/test_rateconverter.cpp
- tests/test_singlecellsolves.cpp
OK - I know think this is ready for a review; would also like to run the Norne case before merge. Will post here when that is done.
This still applies: https://github.com/OPM/opm-autodiff/issues/601
> Replaced SimulatorState -> SimulationDataContainer

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
> Revert "Asynchronous output."

- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
- opm/autodiff/SimulatorIncompTwophaseAd.cpp
- opm/polymer/SimulatorCompressiblePolymer.cpp
- opm/polymer/SimulatorPolymer.cpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp
- opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp
As OutputWriter has been deleted from opm-core
Only changes in includes
> Refactored to use OutputWriter from opm-output

- opm/autodiff/FlowMain.hpp
Enables flow to accept a basename for a case by appending a .DATA suffix
should it not be provided. It already supported reading the basename
from a .DATA extension file, but not opening said file by handing it to
the parser.
> Flow accepts base name for input Deck

- opm/autodiff/FlowMain.hpp
Depends on https://github.com/OPM/opm-core/pull/987
> adapt changes to relpermDiagnostics.

- jenkins/README.md
- jenkins/build-opm-autodiff.sh
- jenkins/build-pr.sh
- jenkins/build.sh
This is the build scripts for this module, ref OPM/opm-common#102 and OPM/opm-parser#743
> Jenkins reboot

- tests/test_solventprops_ad.cpp
- fix mismatch between grid size and the test cell size
- avoid using new
This PR address #630
> Fixes to test_solventprops_ad

- CMakeLists_files.cmake
- examples/sim_2p_comp_reorder.cpp
- opm/simulators/SimulatorCompressibleTwophase.cpp
- opm/simulators/SimulatorCompressibleTwophase.hpp
- opm/simulators/SimulatorIncompTwophase.cpp
- opm/simulators/SimulatorIncompTwophase.hpp
- opm/simulators/thresholdPressures.hpp
- tests/test_thresholdpressure.cpp
This was requested by @atgeirr 
Do note that the test is disabled, like it was in opm-core.
> Import some files from opm core (with history)

- CMakeLists_files.cmake
- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- opm/autodiff/FlowMain.hpp
- opm/simulators/SimulatorCompressibleTwophase.cpp
- opm/simulators/SimulatorIncompTwophase.cpp
- opm/simulators/thresholdPressures.hpp
This completes the job started in #642:
- Import file that was forgotten (sim_2p_incomp.cpp).
- Update the CMake file lists.
- Update include file locations.
> Import simulator, update code

- examples/opm_init_check.cpp
- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/GridInit.hpp
- tests/test_boprops_ad.cpp
- tests/test_rateconverter.cpp
- tests/test_thresholdpressure.cpp
- tests/test_transmissibilitymultipliers.cpp
Using new EclipseState.getInputGrid API in Parser
See OPM/opm-parser#769
> Using getInputGrid API from Parser

- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
With this I have no warnings from this module.
> Silence some recently introduced warnings.

- CMakeLists.txt
> Add flow mpi installation

- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Dependant on https://github.com/OPM/opm-parser/pull/784 and https://github.com/OPM/opm-output/pull/21
> Remove parameters from EclipseWriter constructor

- jenkins/build-opm-simulators.sh
- jenkins/build-pr.sh
- jenkins/build.sh
changes done related to downstream triggers made
it easier to build upstreams as well
depends on https://github.com/OPM/opm-common/pull/111
> simplify jenkins build scripts a little

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
This PR uses the HAVE_PTHREAD variable introduced in PR opm-common #116 to set the default value for async output. It also fixes a minor issue that the output thread is only spawned on the I/O rank.
> Use HAVE_PTHREAD to enable async output.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
WIP (testing travis + jenkins)
> WIP trying disabling async output default setting

- opm/autodiff/FlowMain.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
* Compute NNC information from a grid
* Pass NNC information to EclipseWriter
Most importantly:  `simulator.run` and `writer.writeInit` now take NNC arguments.
I'm open for moving the code that actually fetches the NNC information away from FlowMain if we have a better place (for you and for me) to put it.
Depends on
* OPM/opm-output#27
* OPM/opm-parser#806
> Introducing NNC output

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorBase_impl.hpp
Write the terminal output messages to log file, needs opm-core https://github.com/OPM/opm-core/pull/1010.
> write simulation details to log file.

- tests/test_restart.cpp
Trying to chase the current Travis + Jenkins failure in the `compare_restart_files` test. Unfortunately it works on my machine&trade; - so a bit difficult to debug. The current PR has some solidifying changes which make sense anyway.
> Some checks for file open and file has keyword.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
this is the opm-simulators part of OPM/opm-material#147. the PR must be merged in lockstep lest there be breakage...
> rename "local AD" to "dense AD"

- opm/autodiff/FlowMain.hpp
Needs both https://github.com/OPM/opm-common/pull/135 and  https://github.com/OPM/opm-parser/pull/830
> Support new message type: Prtinfo

- opm/autodiff/FlowMain.hpp
Forgot to let flow use this https://github.com/OPM/opm-common/pull/137
> use default prefix.

- opm/autodiff/FlowMain.hpp
Add two blank line to improve the readability.
> Add blank line before and after "Reading Parameters"

- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Keep up with an interface change in opm-output.
upstream: https://github.com/OPM/opm-output/pull/46
> Pass NNC to OutputWriter constructor

- opm/autodiff/FlowMain.hpp
Ensure that the parameter is asked for (and logged to the debug log) also if defaulted.
Will self-merge after tests are green unless objected to.
> Refine setting of (linear) solver_approach.

- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/WellStateMultiSegment.hpp
> Clone the Wells pointer for output use later.

- CMakeLists.txt
it is a 2D case with H__ pressure drop specification, and it takes about 2 second to run.
It depends on OPM/opm-data#110 .
> adding a test for flow_multisegment

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/MultisegmentWells.cpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
There were variuous places in the code that had problems with null well pointers. These are fixed with this PR. Together with OPM/opm-core#1050 this PR closes #741
> Fix wells for null pointers

- opm/autodiff/BlackoilTransportModel.hpp
Will self-merge immediately since this fixes the build that was broken by merging #711 (because #737 was merged first).
> Adapt to changed updateWellControls() signature.

- opm/autodiff/FlowMain.hpp
- opm/autodiff/NonlinearSolver.hpp
- opm/autodiff/NonlinearSolver_impl.hpp
Fix minor bug with "nosim" parameter, and silence warnings due to using unsigned integers.
> Fix minor bug and warning

- CMakeLists.txt
- tests/compare_INIT.py
This PR only updates the keywords checked in the INIT regression test.
Depends on:
1. https://github.com/Ensembles/ert/pull/1165
2. https://github.com/OPM/opm-output/pull/64
> Regression testing on SPE1 DX, DY, DZ and DEPTH

- opm/polymer/PolymerInflow.cpp
without this fix, polymer concentration injection will not correct.
> fix polymer in flow bug.

- opm/polymer/PolymerInflow.cpp
The previous implementation will set the polymer rates to the wrong wells. This PR fix the bug.
> Fix polymer rates bug

- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
> well iterations should start from 0.

- opm/autodiff/FlowMain.hpp
Small update to stay in sync with parser, ref OPM/opm-parser#887
> Match RestartConfig interface in opm-parser

- opm/polymer/PolymerInflow.cpp
https://github.com/OPM/opm-simulators/pull/791
> look for water injector only, if not find, just continue to next step.

- jenkins/build-opm-simulators.sh
- jenkins/build-pr.sh
- jenkins/build.sh
Depends on https://github.com/OPM/opm-common/pull/168
> simplify jenkins build scripts after ert reorganization

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
With this PR, the PAV numbers in FIP report for OPM is quite close to that in ECLIPSE.
> Correct the formulation for PAV calculations.

- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Not needed since some past reorganization.
> Remove unused include.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilPressureModel.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
Enables outputting cell data to UNRST files (RPTRST keyword).
See also sibling pull request in OPM/opm-output#84 and OPM/opm-core#1060
> Output writer cell data

- opm/autodiff/BlackoilModelBase_impl.hpp
This PR should solve the issue of https://github.com/OPM/opm-simulators/issues/809
> Remove SolutionState dependency in FIP calculation.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
This fixes some code that was missing in #805 in the Polymer model
> Added missing code for polymer model for output

- opm/autodiff/GeoProps.hpp
this simplifies handling the pore volume by centralising the code,
i.e., moving it into opm-parser. (in particular, it makes the MINPV
handling consistent with the active cells which get removed by the
grid.) If eclipse turns out to be inconsistent here, we need to deal
with atrocities like the MULTREGP keyword on a case-by-case basis,
i.e., it would considerably uglify the code and be an additional
maintainance burden.
see OPM/opm-parser#909 for the opm-parser part.
> use the PORV 3D property from opm-parser to determine the pore volume

- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
fixes a regression caused by 65b512e9036db0a52edc89c0aae1aa3e980262f7
> fix output of gas phase

- CMakeLists_files.cmake
- opm/autodiff/Compat.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
- opm/polymer/SimulatorPolymer.cpp
once more, a merge of the current master branch into the frankenstein branch. since this PR only affects the frankenstein branch, the fixes which this PR adds on top of the merge are rather trivial (it changes a few include statements) and it needed to fix the build I'll just self-merge.
> Frankenstein merge master v2

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
With this PR model 2 runs with flow_ebos
The results are not the same as for flow. I will continue to investigate why.
> Frankenstein fixes for model2

- opm/autodiff/StandardWellsDense.hpp
This implements the same hack that is used in flow. With this fix Model 2 results are ok until 1500 days when MULTFLT appears. Changes in geoprops in not yet supported in ebos.
> Allow crossflow if all perforations is crossflowing

- opm/autodiff/SimulatorBase_impl.hpp
https://github.com/OPM/opm-parser/pull/930
> Schedule::getGroup returns reference, not pointer

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
This PR adds the features to send data needed for summary files to output. 
Depends on OPM/opm-output#97
> Summary data output

- debian/control
- debian/mk_orig_source
- debian/rules
brings back packages on ubuntu xenial
> changed: bundle eigen3 in the original tarball for debian

- redhat/opm-simulators.spec
> update redhat6 packaging

- opm/autodiff/MultisegmentWells_impl.hpp
- opm/simulators/WellSwitchingLogger.cpp
- opm/simulators/WellSwitchingLogger.hpp
Also a minor warning fix.
Replaces #858.
> Compile fixes

- CMakeLists_files.cmake
- debian/control
- debian/mk_orig_source
- debian/rules
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/MultisegmentWells_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellHelpers.hpp
- opm/autodiff/WellStateFullyImplicitBlackoilSolvent.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
- opm/simulators/ParallelFileMerger.hpp
- opm/simulators/WellSwitchingLogger.cpp
- opm/simulators/WellSwitchingLogger.hpp
- opm/simulators/thresholdPressures.hpp
- redhat/opm-simulators.spec
- tests/test_multisegmentwells.cpp
- tests/test_wellswitchlogger.cpp
this merges the current opm-simulator master branch into 'frankenstein'. since neither the release nor master is affected by this an it is (probably) required to use the master versions of the dependencies, I'll self merge this without delay. (if something breaks, it can be reverted.)
> Frankenstein merge master v3

- opm/autodiff/Compat.hpp
- opm/autodiff/GeoProps.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/SimulatorPolymer.cpp
Followup to: https://github.com/OPM/opm-output/pull/101
OK - this should now be ready for review and merge.
> data::Solution for opm-output communication.

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This is the compagnion PR to OPM/ewoms#74. the actual work is done in the EclProblem. this patch just prevents appling the modifier deck twice...
> flow_ebos: support for geology changes during the simulation

- opm/autodiff/BlackoilModelEbos.hpp
Keep track of whether it is a restart or not and invalidate the
intensiveQuantitiesCache in ebos when restarting the timestep due to
convergence issues.
> Frankenstein: InvalidateCache when restaring the timestep

- examples/sim_simple.cpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/polymer/SimulatorCompressiblePolymer.cpp
- opm/polymer/SimulatorPolymer.cpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- tests/test_boprops_ad.cpp
- tests/test_multisegmentwells.cpp
- tests/test_rateconverter.cpp
- tests/test_solventprops_ad.cpp
- tests/test_welldensitysegmented.cpp
the daily master merge, maybe this should be done automatically ;)
> Frankenstein merge master v5

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Errors were found in FIP handling and output.
This should fix issue #877, can you verify that @ANerd?
> Bugfix: properly handle two-phase cases.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilSequentialModel.hpp
- opm/autodiff/Compat.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/NewtonIterationUtilities.cpp
- opm/autodiff/NewtonIterationUtilities.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
the usual master merge into `frankenstein`.
since this does not change anything semantically and it only affects the `frankenstein` branch, I'll self merge immediately.
> Frankenstein merge master v7

- jenkins/build.sh
thanks goes to @akva2 for pointing this out...
I'll self merge this once jenkins is happy because it is only for the frankenstein branch and pretty trivial.
> add ewoms to the list upstream modules for jenkins

- opm/autodiff/BlackoilDetails.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/StandardWellsDense.hpp
This PR removes last traces of Eigen classes from BlackoilModelEbos. This needs testing Model 2 and 3 and 4.
> Remove Eigen from BlackoilModelEbos.

- opm/autodiff/BlackoilPropsAdFromDeck.cpp
> use accessor methods to access the value and derivatives of Evaluation objects

- CMakeLists_files.cmake
- opm/autodiff/BlackoilDetails.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.cpp
- opm/autodiff/StandardWellsDense.hpp
Removal of temporary variable creation in WellModel::apply.
Make flow and flow_ebos use the same linear solver setup.
> [WIP] some cleanup and features for Frankenstone.

- dune.module
- opm/autodiff/FlowMain.hpp
this time, the changes are rather trivial...
> Frankenstein merge master v9

- opm/autodiff/Compat.hpp
Member has been removed upstream.
https://github.com/OPM/opm-output/pull/132
> Remove Solution.sdc assignment

- opm/autodiff/BlackoilModelEbos.hpp
I'm not really sure if the fix is semantically correct (Dune
communicators are strange beasts if you're new to them), but at least
this patch fixes the build without MPI and the resulting flow_ebos
binary seems to work fine.
I'll self-merge this immediately as it is rather simple and fixes an issue encountered in the real world by @akva2. Patches for fixing this  in a better way are highly welcome!
> fix the build if MPI is not available

- opm/autodiff/FlowMainEbos.hpp
... to make apparent from the output which simulator was used.
> flow_ebos: alter the startup message

- jenkins/run-norne.sh
> added: ability to run norne using flow_ebos

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
Some part of the output facility was temporary commented out as "quick fixes". This PR fixes the real problems and also wraps some output into if(phase_exist) to make it work for 2p runs.
> Frankenstein output fixes

- opm/autodiff/BlackoilSolventState.cpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
this time there were no conflicts, but I think it is be good to merge the master once more...
> Frankenstein merge master v12

- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
this broke after the latest master merge (again, the reason were API
changes. this time they did not lead to merge conflicts.)
I've verified that flow_ebos works with Norne and that the performance
did not regress.
> flow_ebos: fix the build

- CMakeLists_files.cmake
- opm/autodiff/AutoDiffMatrix.hpp
- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilMultiSegmentModel.hpp
- opm/autodiff/BlackoilMultiSegmentModel_impl.hpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/MultisegmentWells.cpp
- opm/autodiff/MultisegmentWells.hpp
- opm/autodiff/MultisegmentWells_impl.hpp
- opm/autodiff/SimulatorBase_impl.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilMultiSegment_impl.hpp
- opm/autodiff/StandardWells.hpp
- opm/autodiff/StandardWellsSolvent.hpp
- opm/autodiff/StandardWellsSolvent_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
- tests/test_multisegmentwells.cpp
this fixes the (easy) merge conflicts which were introduced yesterday evening. it also contains patches for the file lists and AutoDiffMatrix issues found by @atgeirr in #800.
> Frankenstein merge master v13

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/ParallelDebugOutput.hpp
> Quell some compiler warnings

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelParameters.cpp
- opm/autodiff/BlackoilModelParameters.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
This PR introduces a parameter to change the threshold for the time step in days below which single precision in the linear solvers should be used. 
Furthermore, a flag for the use of AMG in introduced.
> Introduce parameter for time step in days when single precision should be used.

- opm/autodiff/FlowMain.hpp
Downstream of https://github.com/OPM/opm-output/pull/140
> Rename to EclipseWriter.writeInitial

- opm/autodiff/MultisegmentWells_impl.hpp
updatePerfPhaseRatesAndPressures() and addWellFluxEq(). 
In case no wells exist on this process.
> adding localWellsActive() checking for two MSW functions

- opm/autodiff/StandardWellsDense.hpp
once more, it seems like we became a victim of the combinatorial
explosion of possibilities.
thanks goes to @bska for catching this.
> flow_ebos: fix build with debugging flags

- jenkins/run-norne.sh
> changed: use a separate output dir for each simulator in norne integration test

- opm/autodiff/SimulatorBase_impl.hpp
Downstream of https://github.com/OPM/opm-parser/pull/981
> Mini deck is reference, not pointer

- opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
To be more consistent with the way in handling the injection well. 
It dos not make any results better and it does not damage any previous successful result. It is just the correct way from the current understanding.
> changing polymer production concentration to be the grid block concnetration.

- opm/polymer/SimulatorPolymer.cpp
In an attempt to clean up opm-output we would like (re)move some unused/deprecated files: https://github.com/OPM/opm-output/pull/131
In this PR we remove the calls to `writeECLData` - which means that the [two-phase polymer simulator](https://github.com/OPM/opm-simulators/blob/master/examples/sim_poly2p_comp_reorder.cpp) will not write Eclipse binary output any longer. If this particualar simulator should retain/regain that capability the properly maintained functionality of opm-output should be used.
> Removed all calls to writeECLData.

- opm/autodiff/BlackoilModelEbos.hpp
With this flow and flow_ebos results are much closer. Tested on Model 2.
> BUGFIX pass pvtnum to density in convertResults() in FlowEbos

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This should apply the same output fixes for ebos as was made for legacy, see #987
> Fix for FIP output in ebos

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
Silencing various warnings. None seem to indicate errors, although I had to look *very* carefully at the ISTLSolver.hpp code to be sure...
> Silence warnings

- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/sim_poly_fi2p_comp_ad.cpp
- opm/autodiff/FlowMain.hpp
Requires https://github.com/OPM/opm-parser/pull/1013 and https://github.com/OPM/opm-core/pull/1124
> RockCompressibility takes only EclipseState

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
> Added missing global sum for FIP totals.

- opm/autodiff/Compat.hpp
Followup to: https://github.com/OPM/opm-output/pull/153
> Fixed output units RS and RV.

- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
the canonical source is now the EclProblem object.
> flow_ebos: remove the redundant gravity objects

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutputEbos.hpp
this synchronizes SimulatorFullyImplicitBlackoilEbos with the flow_legacy version (SimulatorFullyImplicitBlackoil). this PR contains the first two patches of what used to be #1025. (that stuff was unrelated to the fluid in place functionality.)
> Flow ebos sync with flow legacy

- opm/autodiff/StandardWellsDense.hpp
The original StandardWellsDense does not provide correct strategy to enforce combined rate control like LRAT. 
With this fix, it can provide correct LRAT control. 
It is still WIP, and this part of code is pretty complicated. Please let me know if you find anything missing.
> fixing the LRAT control for StandardWellsDense

- compareECLFiles.cmake
Relaxed test tolerances for restart tests.
> Relaxed epsilon for restart test.

- compareECLFiles.cmake
- tests/update_reference_data.sh
work in progress. ignore for now, do NOT merge
> refinement in regression data update script to aid automation

- CMakeLists_files.cmake
- examples/wells_example.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorBase.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
- opm/simulators/timestepping/SimulatorTimer.cpp
- opm/simulators/timestepping/SimulatorTimer.hpp
- opm/simulators/timestepping/SimulatorTimerInterface.hpp
- opm/simulators/timestepping/TimeStepControl.cpp
- opm/simulators/timestepping/TimeStepControl.hpp
- opm/simulators/timestepping/TimeStepControlInterface.hpp
- tests/TESTTIMER.DATA
- tests/test_timer.cpp
As requested, this imports the AdaptiveTimeStepping class from opm-core.
Do not merge this branch as-is, it's a bit interleaved with other fixes so I will have to rewrite it to reflect reality as seen in upstream before it is merged, but I open early so nobody else redo the same work (it's just a matter of rerunning my script).
> Import adaptive time stepping and associated classes

- opm/autodiff/GeoProps.hpp
Face centers are computed using the cell corners. With this
implementation the face center seen from a cell may be different from the
face center seen from its neighbor.
Face normals with area lengths are calculated using the face corners
directly not using a triangulation point in the center of the face.
This gives transmissibility almost equal to eclipse.
Depends on OPM/opm-grid#261
> Start using face geometry computed the Ecl way

- opm/autodiff/BlackoilModelEbos.hpp
Simply homogenizes whitespace in part of the code.
> Minor whitespace fixes to be consistent with surrounding code

- opm/autodiff/StandardWellsDense_impl.hpp
For the wells having a THP constraints, their THP values should be updated always. Otherwise, the control switching will not work correctly. 
The PR makes the flow_ebos having the same results with flow, while not tested against Eclipse yet. 
And also, the output of thp values not correct. They are always zero, will looking into it later.
> update the thp value for flow_ebos

- tests/update_reference_data.sh
> added: update norne integration test from jenkins trigger

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
this should fix #988, but please test before merge.
> Flow ebos fix fip

- opm/autodiff/BlackoilModelEbos.hpp
This PR is for @andlaus to possibly fix it "the right way". What I've done below does not appear to be correct, and I'm unsure what is actually wrong.
> Update for writing initial values to restart file

- compareECLFiles.cmake
- Now that restart tests pass with flow_ebos, enable the tests. 
- Also enable the init test with flow_ebos - it passes fine against the flow reference.
> Enable ebos tests

- tests/run-parallel-regressionTest.sh
- tests/run-regressionTest.sh
- tests/run-restart-regressionTest.sh
> changed: print some banners during test comparisons

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Adds information regarding report step, elapsed time, simulation date, simulator name, version, field title etc to the fip output
> Add timestamp fip output

- opm/autodiff/FlowMain.hpp
See: https://github.com/OPM/opm-simulators/issues/1099
> Policy change: warn when missing well/group.

- opm/autodiff/StandardWellsDense_impl.hpp
More careful determination of the most restrictive bhp value when computing the well potentials. 
The original implementation causes problem in the following situation
1. The thp constraints appears earlier than bhp constraints in the well_controls struct.
2. There is no bhp constraint associated with the well.
If we can ensure that the wells can always have some kind of bhp constraints, the implementation can be simplified further by removing the hard-coded default values. 
This code should only impact the examples with wells under group control and with bhp and thp constraints.  I do not have result for this kind of example yet. It does not break any results from group control. 
Anyway, unless we can ensure the implementation by looking at the logic of the code, it is better to verify …
> more careful determination of the most restrictive bhp value

- compareECLFiles.cmake
- tests/update_reference_data.sh
forgot to update these in https://github.com/OPM/opm-simulators/pull/1096
> fixed: paths in data update script

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/Compat.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
This adds SOMAX to the restart files. Will have a conflict with #1084, as they somewhat overlap.
> Added somax to input/output to restart file

- tests/run-init-regressionTest.sh
- tests/run-regressionTest.sh
- tests/update_reference_data.sh
reference data paths have been updated to reflect simulator data is for.
> update scripts to use new paths for reference data

- jenkins/run-norne.sh
there always has to be something that slips...
> fixed: forgotten paths in 7bbb4a2a288b31681c59a31673cb605ec2ecd574

- jenkins/run-spe.sh
Hopefully this fixes the Jenkins run spe request.
Intend to self-merge if green.
> Add executable name to reference data locations.

- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
Minor changes to terminal output message tag and classification
> Minor terminal output modifications

- opm/autodiff/Compat.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
Followup to: https://github.com/OPM/opm-output/pull/180
> Using optional restart loading instead of extra.

- opm/autodiff/BlackoilModelBase.hpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilPropsAdFromDeck.hpp
- opm/autodiff/Compat.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
This addresses #1144 by supporting output of PBUB/PDEW. Results appear plausible to me, but have not been thoroughly tested (yet).
> This adds bubble/dew point pressure output to legacy flow

- tests/update_reference_data.sh
this patch has been factored out of #1133 and maybe it even works, but the reasoning for the merge commit probably needs some improvement. (right @akva2?) Thus, this PR is mainly meant as a starting point for further discussions.
> update update_reference_data.sh to also update the flow_ebos reference solutions

- opm/autodiff/BlackoilModelEbos.hpp
> Make initial viscosity output similar with Ecl

- opm/autodiff/BlackoilSolventModel.hpp
- opm/autodiff/BlackoilSolventModel_impl.hpp
This fixes flow_solvent runs for me.
Should go into release, so let's get this tested quickly!
> Workaround: ensure properties necessary for FIP are computed.

- debian/rules
- redhat/opm-simulators.spec
Backports from 2017.04 release branch.
> disable native tuning in packaging

- opm/autodiff/FlowMain.hpp
> Dummy commit

- opm/autodiff/FlowMainEbos.hpp
Adds header for .PRT file with the following information
1. Flow binary information
2. host names(s)/ machine names
3. host hardware
4. Operating system
5. User
6. System time and date
> PRT header

- CMakeLists.txt
The cmake output in travis is swamped with warnings from Eigen.
> Added -Wno-dev to Eigen cmake args.

- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
> FIX output the correct next timestep after convergece failure

- compareECLFiles.cmake
- jenkins/run-polymer.sh
- tests/update_reference_data.sh
Note: This is just a suggestion, if you prefer to not add this, just say so.
The current files in opm-data will fail, so an update_data has to be performed if this is wanted. You have to merge https://github.com/OPM/opm-data/pull/217 before doing the update.
> add regression test for flow_polymer

- compareECLFiles.cmake
- tests/update_reference_data.sh
Same procedure as last time: Merge the upstreams, then run update_data on this to generate jenkins data.
> add spe5 flow_solvent regression test

- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
Initialized all Eval vars used in the wells model.
> [cleanup] initialized Eval variables with 0.

- opm/autodiff/BlackoilTransportModel.hpp
This fixes some bugs discovered using the iterated sequential implicit formulation, and simplifies the code a little bit.
> Transport solver bugfixes

- tests/analyze_ecl_failure.sh
- tests/analyze_summary_failure.sh
Noticed when investigating a test failure.
@akva2 please test and verify these changes (and merge if happy)
> Make scripts run on older bash versions.

- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
DO NOT MERGE THIS.
I just want to see whether the regressions of #1186 vanish with these changes.
> This is the faster ilu pull request but with the traversal of the columns of upper in the original ordering

- opm/autodiff/BlackoilModelEbos.hpp
During computation of the convergence properties several temporary vectors of length number of cells are created although not needed. This PR fixes this.
> Ebos::getConvergence: removed unnecessary creation of vectors of length nCells.

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.hpp
- opm/simulators/timestepping/SimulatorTimerInterface.hpp
This is when writing the first time step as is this is the first step when OIP is available.
With this change FOE will be calculated by opm-output if FOE and FOIP is requested.
Needs OPM/opm-output#198
> Write the initial OIP values if requested.

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWellsDense.hpp
- opm/autodiff/StandardWellsDense_impl.hpp
the output of the THP is still not yet correct, and not sure how it got broken.
> Fixing vfp related running with flow_ebos

- opm/autodiff/BlackoilModelEbos.hpp
Avoids some unnecessary re-scaling of the residual and the jacobian. Gives a small speed up on the models I have tested. Depends on OPM/ewoms#205
> Ask ebos to formulate the equation by surface volumes directly

- opm/autodiff/BlackoilModelEbos.hpp
We do this by switching to output the global index of the cells.
In a first step the problematic cell indices are gather on process 0.
Then they are logged there.
This should prevent spurious ouput at the end of PRT and DEBUG files after the
simulation time is printed. This happened previously for some parallel
runs of model 2. Unfortunately, it seems these problems do not appear any
more for the current master. At least I could not reproduce them.
> Output bubble/dew point computation problems only on rank 0.

- tests/update_reference_data.sh
was missing in 1950052684035c8dc8b82532735a74c17e0d9e2c
> add spe9group to reference data update script

- opm/autodiff/StandardWellsDense_impl.hpp
to recover the model 2 running.
> not throwing when encountering multisegment wells.

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/ISTLSolver.hpp
- tests/test_invert.cpp
Motivation: Run field case model with CO2 injection.
> Add invert4x4 specialization for invertMatrix()

- opm/autodiff/StandardWellsDense_impl.hpp
Previously all ranks logged the message and did clutter the
output files quite a bit.
> Log debug messages about wells only on master.

- tests/update_reference_data.sh
data update script was missed when this changed.
> fixed: spe1_2p is not run with flow_ebos, it is run with flow_ebos_2p

- compareECLFiles.cmake
> Improve test macros modified

- tests/update_reference_data.sh
Useful in any case since flow is the new wine after all.
> add flow simulators to the data update script

- opm/autodiff/WellInterface_impl.hpp
this PR tries to close #1142. 
I am not sure what is the darker blue blocks in front of some lines are, maybe I accidentally used TAB?
> handling WELL workover over ratio economic limit.

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This reverts commit 9adc4d5d3cab514d2707ee5b285ba61b0c441072.
> Revert "Communicate the ebos solution at the beginning of the run method

- opm/autodiff/FlowMainEbos.hpp
the ThreadManager from ebos was not called which resulted in some havoc when attempting multi-threaded runs.
this PR depends on OPM/ewoms#234.
> flow_ebos: fix the OpenMP functionality

- opm/autodiff/MultisegmentWell_impl.hpp
which were left from the previous PR #1317.
I must not be thinking well. Sorry about that.
> removing more HAVE_UMFAPACK related in MultisegmentWell_impl

- opm/autodiff/BlackoilModelEbos.hpp
Updating the solution variable in updateState() was conceptually wrong
and lead to incorrect results if the linear solver failed before the
updateState() method was called. i.e. in the first iteration.
This fixes parallel result regression on Model 2.
> BUGFIX Update the solution variable in ebos

- compareECLFiles.cmake
- tests/update_reference_data.sh
I have been tasked with cleaning up the regression test suite.
This is step 1 - removing duplicate tests.
Side stream: https://github.com/OPM/opm-data/pull/271
> remove unwanted/duplicate tests

- compareECLFiles.cmake
- opm/autodiff/WellInterface_impl.hpp
- tests/update_reference_data.sh
this
- moves the MSW_2D_H test to flow
- adds polymer_simple2D to flow
- moves the spe5 solvent test to flow
- moves the parallel spe3 test to flow (no idea why i didn't do that in the previous PR..)
- adds the msw_3d_hfa test for flow
- update the reference data update script to allow addition of new data
> Add and move tests

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
This refactors the fluid-in-place related parts of the run() method, making it clearer and shorter.
> Refactor FIP in run() method

- CHANGELOG.md
- README.md
Affects no code, will self-merge immediately.
> Update README, add CHANGELOG.

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Depends on OPM/opm-parser#1159
> Only update TUNING after event

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/RateConverter.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- tests/test_wellmodel.cpp
Compute the conversion factor for solvent using the RateConverter.hpp
> Make it possible to combine solvent and RESV

- jenkins/run-polymer.sh
missed a change in the removal PR.
> fixed: run polymer integration test with flow, not recently removed flow_polymer

- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Just to clean up the .DEBUG file.
> Only read use_TUNING param once.

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- tests/test_wellmodel.cpp
some cleaning up in the well model related. Far from finished, will continue later. 
Stopping here to handle other higher-priority issue. 
1. removing the usage of Wells in resetWellControlFromState
2. removing the dumplicated numComponents in WellInterface
3. removing the "`current`" argment in updateWellStateWithTarget
And some other small cleaning up. 
It should not change any result in any way, while will run the several big models to report back.
> Cleaningup well models

- CMakeLists_files.cmake
- opm/core/utility/DataMap.hpp
- opm/core/utility/Event.cpp
- opm/core/utility/Event.hpp
- opm/core/utility/Event_impl.hpp
- opm/core/utility/NullStream.cpp
- opm/core/utility/NullStream.hpp
- opm/core/utility/share_obj.hpp
- tests/test_event.cpp
Upstream: https://github.com/OPM/opm-core/pull/1193
> Import some utils from opm-core

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
1) Trust ebos to provide the correct initial solution also when SWATINIT is applied. 
2) Use the code in ebos for the explicit setting of the initial solution using (PRESSURE, SWAT etc. )
3) Output the initial solution from ebos. 
Tested on Model 2. 
Depends on OPM/ewoms#241
> Only compute the initial solution once. 

- opm/autodiff/BlackoilWellModel_impl.hpp
@atgeirr , please help to confirm it works for your case.
> making the single phase RESV injection work.

- CMakeLists.txt
- CMakeLists_files.cmake
- tutorials/CMakeLists.txt
- tutorials/generate_doc_figures.py
- tutorials/tutorial1.cpp
- tutorials/tutorial2.cpp
- tutorials/tutorial3.cpp
- tutorials/tutorial4.cpp
Upstream: https://github.com/OPM/opm-core/pull/1197
> Import tutorials from opm-core

- opm/autodiff/BlackoilModelEbos.hpp
Merged together with OPM/ewoms#253
> Adapt to changed initial FluidState type in ebos

- CMakeLists.txt
- opm-simulators-prereqs.cmake
Upstream: https://github.com/OPM/opm-common/pull/304
> changed: put prereqs in module itself

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/NewtonIterationBlackoilCPR.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
Two first commits are build fixes, the last a warning removal commit.
> Fix build with dune 2.6

- examples/flow.cpp
- opm/autodiff/BlackoilModelBase_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilPropsAdFromDeck.cpp
- opm/autodiff/BlackoilTransportModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/MSWellHelpers.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/StandardWells_impl.hpp
- opm/simulators/flow_ebos_blackoil.cpp
- opm/simulators/flow_ebos_gasoil.cpp
- opm/simulators/flow_ebos_oilwater.cpp
- opm/simulators/flow_ebos_polymer.cpp
- opm/simulators/flow_ebos_solvent.cpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
this is the `opm-simulators` part of OPM/opm-common#332
> adapt to the move of infrastructure from opm-common to opm-material

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilOutputEbos.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/RateConverter.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/flow_ebos_blackoil.cpp
- opm/simulators/flow_ebos_gasoil.cpp
- opm/simulators/flow_ebos_oilwater.cpp
- opm/simulators/flow_ebos_polymer.cpp
- opm/simulators/flow_ebos_solvent.cpp
- tests/test_blackoilstate.cpp
- tests/test_stoppedwells.cpp
- tests/test_thresholdpressure.cpp
- tests/test_wellsmanager.cpp
this is the downstream mop-up for OPM/ewoms#285
> adapt to the gridManager() -> vanguard() change in ewoms

- compareECLFiles.cmake
This one was missed when the others were changed.
> Use PROJECT_BINARY_DIR instead of CMAKE_BINARY_DIR.

- compareECLFiles.cmake
- tests/update_reference_data.sh
> Add integration test with no wells.

- opm/autodiff/FlowMainEbos.hpp
> Fix default output dir

- CMakeLists_files.cmake
- compareECLFiles.cmake
- examples/flow.cpp
- opm/simulators/flow_ebos_oilwater_polymer.cpp
- opm/simulators/flow_ebos_oilwater_polymer.hpp
- tests/update_reference_data.sh
It does not work yet, so it is WIP.
> trying to add the functionality to handle oil/water polymer

- opm/autodiff/StandardWell_impl.hpp
for example, distr = 0 1 0, for rate control, F = 1 0 0, we will get a
zero F_target, then it is wrong to do the division with F_target.
It is okay when target = 0. When target != 0, the result is already very
wrong. Non-linear iteration can send us anywhere, not sure the best
solution for this kind of strange situation.
It was reported by @odd, while I am not sure it is something should go in. 
For the current StandardWell we are trying to have the control target in implicitly through kind of manual way, it is possible that having a control equation explicitly will solve this kind of situation better.
> trying to fix a problematic situation when updateWellState

- debian/control
- dune.module
- jenkins/build.sh
- opm-simulators-prereqs.cmake
- redhat/opm-simulators.spec
Downstream of https://github.com/OPM/opm-common/pull/341
> adjustments for eclipse support in opm-common

- tests/update_reference_data.sh
leftovers, leftovers for everybody.
> changed: remove repos from regression data update script

- opm/autodiff/FlowMain.hpp
- opm/autodiff/FlowMainEbos.hpp
MessageContainer is desired removed in opm-common. Here are changes that comply.
> Made changes to comply w/ removal of MessageContainer.

- CMakeLists.txt
- compareECLFiles.cmake
Downstream of https://github.com/OPM/opm-common/pull/352
> Use opm-tests

- jenkins/run-norne.sh
- jenkins/run-spe.sh
> fixed: missing opm-data -> opm-tests references

- opm/autodiff/BlackoilAmg.hpp
and also  test the jenkins master branch.
> silencing warning related to extra ; from BlackoilAmg

- opm/autodiff/BlackoilModelEbos.hpp
- opm/simulators/flow_ebos_gasoil.cpp
- opm/simulators/flow_ebos_oilwater.cpp
- opm/simulators/flow_ebos_oilwater_polymer.cpp
these are the minimal changes required by OPM/ewoms#279. No thermal `flow` variant is added by them yet.
> Minimal changes for blackoil energy

- tests/test_vfpproperties.cpp
Avoid using the `VFPProdTables::init()` and default constructor. Only test code updated.
Can be merged alone, but must be merged before: https://github.com/OPM/opm-common/pull/380
> Use VFPProdTable constructor

- opm/autodiff/StandardWell_impl.hpp
- opm/core/simulator/SimulatorReport.hpp
- opm/core/transport/reorder/reordersequence.cpp
- opm/core/utility/miscUtilitiesBlackoil.cpp
- opm/polymer/PolymerProperties.cpp
- opm/polymer/PolymerProperties.hpp
- opm/polymer/TransportSolverTwophaseCompressiblePolymer.cpp
- tutorials/sim_tutorial1.cpp
some trivial sca fixes. the last commit is non-trivial, i think this is what was intended.
> Various small fixes

- tests/update_reference_data.sh
> fixed: missing OPM_DATA_ROOT -> OPM_TESTS_ROOT

- CHANGELOG.md
@totto82 please check before merging. No Jenkins is needed though.
> Updated to reflect changes from the last few months.

- opm/autodiff/VFPInjProperties.cpp
- opm/autodiff/VFPInjProperties.hpp
- opm/autodiff/VFPProdProperties.cpp
- opm/autodiff/VFPProdProperties.hpp
- opm/autodiff/VFPProperties.cpp
- opm/autodiff/VFPProperties.hpp
It depends on the PR https://github.com/OPM/opm-common/pull/386 and should be merged together with https://github.com/OPM/opm-common/pull/386 . 
The two combined are part of the efforts to recover the running related VFP.
> adapting to the interface change of VFP related in parser.

- CMakeLists_files.cmake
- compareECLFiles.cmake
- examples/flow.cpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/simulators/flow_ebos_energy.cpp
- opm/simulators/flow_ebos_energy.hpp
- tests/update_reference_data.sh
The energy simulator should be considered experimental since it is not tested thorough. The model formulation is neither strictly E100 nor E300 but more a combination of these, which makes verification against the ECL simulators harder. Never the less some testing is done on small cases and the results looks reasonable and comparable to the ECL simulators. 
The main part of this work is done by @andlaus
> Add blackoil + energy specialization to Flow

- tests/update_reference_data.sh
> data -> tests

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/VFPHelpers.hpp
- opm/core/simulator/WellState.hpp
Try to address issue #1248 
I looked at the VFP implementation in flow and found some issues. This is a first try to fix them. 
@GitPaean Please check if this solves issue #1248
> WIP fix vfp in flow

- opm/autodiff/BlackoilOutputEbos.hpp
- opm/autodiff/Compat.cpp
- opm/autodiff/Compat.hpp
- opm/autodiff/ParallelDebugOutput.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp
- opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp
See: https://github.com/OPM/opm-common/pull/391
~~The failed second commit does not even compile.~~
> Use RestartValue when saving eclipse output

- opm/autodiff/MissingFeatures.cpp
See: https://github.com/OPM/opm-common/pull/407
Can be merged independently
> Mark keyword GNETINJE as not supported

- opm/autodiff/BlackoilAquiferModel.hpp
- opm/autodiff/BlackoilAquiferModel_impl.hpp
mostly to test the master branch with jenkins.
> removing some whitespaces

- CMakeLists_files.cmake
> Add forgotten new headers to file list for installation.

- opm/autodiff/Compat.cpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/WellConnectionAuxiliaryModule.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/core/simulator/WellState.hpp
- opm/core/wells/WellsManager_impl.hpp
See: https://github.com/OPM/opm-common/pull/419
> Rename Completion -> Connection

- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/core/wells/WellsManager_impl.hpp
See: OPM/opm-common#426
Trivial rename
> Refactor of connections & completions

- opm/autodiff/FlowMainEbos.hpp
- opm/simulators/ParallelFileMerger.hpp
Closes #1504.
@andlaus this may conflict with your PR, I'll leave it to you to merge this or wait.
> Rename .CASE.DEBUG -> CASE.DBG.

- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/core/wells/WellsManager_impl.hpp
See: https://github.com/OPM/opm-common/pull/435
> Completion refactor

- compareECLFiles.cmake
- tests/update_reference_data.sh
0: Drainage curve is used or the wetting phase
1: Imbibition curve is used for the wetting phase
The second test also test the combination solvent + hysteresis.
Depends on OPM/opm-material#300 and OPM/opm-tests#32
> Add  test for cases with Carlson’s hysteresis model

- compareECLFiles.cmake
- tests/update_reference_data.sh
Reverts OPM/opm-simulators#1525
> Revert "Add  test for cases with Carlson’s hysteresis model"

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
> Remove unnecessary includes

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/FlowMainEbos.hpp
this is the mop-up for OPM/ewoms#362
> adapt to the rename of the EclOutputDir parameter to OutputDir in eWoms

- opm/autodiff/FlowMain.hpp
- tests/run-init-regressionTest.sh
- tests/run-parallel-regressionTest.sh
- tests/run-porv-acceptanceTest.sh
- tests/run-regressionTest.sh
- tests/run-restart-regressionTest.sh
See: https://github.com/OPM/ewoms/pull/384 and https://github.com/OPM/opm-common/pull/493
> Make sure the restart files used when testing are OPM style

- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/ISTLSolverEbos.hpp
the second commit fixes a bug that has been there for some time and only surfaced if there was no UMFPack found. The rest removes dead code that appeared due the ISTLSolver.hpp for ebos (command line parameter system
Superseeds #1579 and #1580.
> Remove dead code.

- CMakeLists.txt
- debian/libopm-simulators1-bin.install
- redhat/opm-simulators.spec
Downstream of https://github.com/OPM/opm-common/pull/500
> added: install bash tab completion for flow

- opm/autodiff/AquiferCarterTracy.hpp
> use specialized fluidstate in the aquifer model

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
Re-factoring the well test related functionalities to prepare for the physical limits well test functionalities. 
Well can be shut/closed and re-opened due to reason other than economic reasons. The focus at the moment is PHYSICAL limit.
Nothing in simulation result should be changed by this PR.
> Refactoring well test to prepare for Physical limit related well test. 

- examples/sim_2p_comp_reorder.cpp
- examples/sim_2p_incomp_ad.cpp
- examples/sim_poly2p_comp_reorder.cpp
- examples/sim_poly2p_incomp_reorder.cpp
- examples/wells_example.cpp
- flow/flow.cpp
- opm/autodiff/FlowMain.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
- tests/test_stoppedwells.cpp
- tests/test_wellcollection.cpp
- tests/test_wellmodel.cpp
- tests/test_wellsgroup.cpp
- tests/test_wellsmanager.cpp
Adapt to change in the Schedule constructor. 
Depends on OPM/ewoms#401 and OPM/opm-common#526
> Adapt to changes in schedule interface

- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
Tested on a modified SPE1CASE2 with WPIG output enabled 
Depends on OPM/opm-common#547
> Compute well productivity index and pass it to the output

- flow/flow.cpp
- flow/flow_ebos_blackoil.cpp
- flow/flow_ebos_blackoil.hpp
- flow/flow_ebos_energy.cpp
- flow/flow_ebos_energy.hpp
- flow/flow_ebos_gasoil.cpp
- flow/flow_ebos_gasoil.hpp
- flow/flow_ebos_oilwater.cpp
- flow/flow_ebos_oilwater.hpp
- flow/flow_ebos_oilwater_polymer.cpp
- flow/flow_ebos_oilwater_polymer.hpp
- flow/flow_ebos_polymer.cpp
- flow/flow_ebos_polymer.hpp
- flow/flow_ebos_solvent.cpp
- flow/flow_ebos_solvent.hpp
they are now always created internally by the vanguard.
this requires OPM/ewoms#418
> flow: do not pass the schedule and summaryConfig objects anymore

- CMakeLists.txt
- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/simulators/timestepping/ConvergenceReport.hpp
- opm/simulators/timestepping/gatherConvergenceReport.hpp
- tests/run-parallel-unitTest.sh
- tests/test_convergencereport.cpp
- tests/test_gatherconvergencereport.cpp
- tests/test_wellswitchlogger.cpp
For discussion. Needed later for moving ConvergenceReport objects to higher levels.
> Provide parallel gathering of ConvergenceReport

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
Needs an update of data since more data is added.
> Output of well potential when asked for

- CMakeLists_files.cmake
- opm/autodiff/ISTLSolverEbos.hpp
- opm/autodiff/MPIUtilities.cpp
- opm/autodiff/MPIUtilities.hpp
- opm/autodiff/NewtonIterationUtilities.cpp
- opm/autodiff/NewtonIterationUtilities.hpp
One more small attempt at doing my assigned task.......
> split mpi function from newtoniterationutilities

- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/FlowMainEbos.hpp
motivation: getting rid of BlackoilPropsAdFromDeck in ebos code path
> remove two rogue includes

- opm/simulators/timestepping/gatherConvergenceReport.cpp
Fixes compilation issues of PR #1612 with open-mpi 1.6.5 discovered by @bska.
Compiler complained about not being able to transform const void* to void*
as needed by MPI.
> Make MPI calls in gatherConvergenceReport with void*.

- opm/autodiff/StandardWell_impl.hpp
@GitPaean here, have your lifetime grant for using 'auto' for counter vars ;)
> fixed: signed/unsigned warnings

- CMakeLists_files.cmake
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/CPRPreconditioner.hpp
- opm/autodiff/FlowLinearSolverParameters.hpp
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolver.hpp
- opm/autodiff/ISTLSolverEbos.hpp
- opm/autodiff/NewtonIterationBlackoilInterleaved.hpp
- opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp
Main change is moving the parameters from NewtonIterationBlackoilInterleaved.hpp to a separate file.
> Avoid using legacy stuff for ebos linear solvers.

- tests/update_reference_data.sh
> remove legacy tests from update data script

- opm/core/props/phaseUsageFromDeck.hpp
found it when developing some new code. 
These two `phaseUsageFromDeck` functions  are almost identical. Please comment if I saw it wrongly . (like they are actually different).
> removing some repeated code in phaseUsageFromDeck

- opm/autodiff/AquiferCarterTracy.hpp
Changes:
* Makes the necessary interface changes to check for nullptr instead of values for the influx_coeff and aquifer initial pressure.
* Corrects for the issue where the aquifer makes connections to cell faces adjoining active cells (see AQUANCON item 11).
Upstream: https://github.com/OPM/opm-common/pull/559
> Fixes for carter tracy aquifer model

- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
> Remove repetitive logging info

- opm/autodiff/BlackoilModelEbos.hpp
Fixes an issue reported by @totto82.
> Move throw-if-nan to after storing convergence report.

- opm/autodiff/AquiferCarterTracy.hpp
- opm/autodiff/BlackoilAquiferModel.hpp
- opm/autodiff/BlackoilAquiferModel_impl.hpp
adding the mapping from cartisian indices to the actual grid indices.
> fixing grid_index for AquiferCarterTracy

- opm/core/wells/WellsGroup.cpp
> Fix missing GRAT in switch.

- flow/flow.cpp
- opm/autodiff/FlowMainEbos.hpp
- tests/test_norne_pvt.cpp
- tests/test_relpermdiagnostics.cpp
- tests/test_stoppedwells.cpp
- tests/test_timer.cpp
- tests/test_vfpproperties.cpp
- tests/test_wellcollection.cpp
- tests/test_wellmodel.cpp
- tests/test_wellsgroup.cpp
- tests/test_wellsmanager.cpp
Downstream of: https://github.com/OPM/opm-common/pull/602
> Add ErrorGuard when parsing

- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/WellInterface_impl.hpp
mostly to test the jenkins update_data system.
> removing some white spaces. 

- CMakeLists.txt
- CMakeLists_files.cmake
- opm/simulators/DeferredLogger.cpp
- opm/simulators/DeferredLogger.hpp
- opm/simulators/gatherDeferredLogger.cpp
- opm/simulators/gatherDeferredLogger.hpp
- tests/test_gatherdeferredlogger.cpp
implements deferred logger functionality
> gather deferredLogger implemented

- compareECLFiles.cmake
- tests/update_reference_data.sh
Downstream of https://github.com/OPM/opm-grid/pull/357
> add a regression test using NNCs

- CMakeLists_files.cmake
- opm/autodiff/AquiferCarterTracy.hpp
- opm/autodiff/AquiferFetkovich.hpp
- opm/autodiff/AquiferInterface.hpp
- opm/autodiff/BlackoilAquiferModel_impl.hpp
This pull request is designed to create an AquiferInterface.hpp base class and two derived classes AquiferCarterTracy.hpp and AquiferFetkovich.hpp. This is still a WIP! 
This is linked to PR #1642
> Base class aquifer

- ebos/eclequilinitializer.hh
- ebos/eclnewtonmethod.hh
- ebos/eclproblem.hh
- ebos/eclwellmanager.hh
- opm/autodiff/FlowMainEbos.hpp
- opm/autodiff/ISTLSolverEbos.hpp
- opm/autodiff/ParallelOverlappingILU0.hpp
- opm/autodiff/WellInterface.hpp
this PR contains some random fixes and improvements that do I think not merit individual PRs and which have accumulated on my local copy of opm-simulators during the last weeks.
> Miscellaneous fixes and improvements

- ebos/eclproblem.hh
the idea is to compensate the residual of the final solution of a time step by means of an opposing source term in the next time step. While performance seems to be a few percent worse than the master version when using the same settings, the results often seem to be much better, so we can often get away with more relaxed tolerances.
This patch has been developed as a joint project with @totto82 and @osae.
(Note that `flow` is unaffected by this because drift compensation is an experimental feature and thus disabled within the production simulator.)
> ebos: implement partial elimination of systematic mass defects

- ebos/eclwellmanager.hh
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
- opm/core/wells/WellCollection.cpp
- opm/core/wells/WellCollection.hpp
- opm/core/wells/WellsGroup.hpp
- opm/core/wells/WellsManager_impl.hpp
- tests/test_wellcollection.cpp
- tests/test_wellsgroup.cpp
See: https://github.com/OPM/opm-common/pull/667
> Move well includes to subdirectory Well/

- CMakeLists_files.cmake
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/MSWellHelpers.hpp
- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWell.hpp
- opm/autodiff/StandardWellV.hpp
- opm/autodiff/StandardWellV_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/simulators/DeferredLoggingErrorHelpers.hpp
correct exception handling in wells classes for serial and parallel runs
> correct exception handling in wells for parallel runs

- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/StandardWellV_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/autodiff/WellStateFullyImplicitBlackoil.hpp
Downstream of: https://github.com/OPM/opm-common/pull/688
> Move events

- ebos/eclproblem.hh
this should significantly reduce surprising behavior for users. since this is an experimental feature, `flow` is unaffected.
> ebos: add some checks to make sure that the simulator produces what the deck specifies

- ebos/eclfluxmodule.hh
- ebos/eclproblem.hh
This PR depend on OPM/opm-common#685
> Refactor the boundary conditions code

- opm/autodiff/ISTLSolverEbos.hpp
Fixing index for pressure equation used in gasoil systems.
> Fix cpr oil gas

- ebos/ecloutputblackoilmodule.hh
Downstream of: https://github.com/OPM/opm-common/pull/704
> Use RFTConfig() object to query for RFT active wells

- opm/autodiff/MultisegmentWell.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
It is not used in the simulation, while it is good to keep them updated for output and analysis purpose. 
It expects to fail the tests related to MS wells.
> updating perforation pressure and rates for MSW well

- flow/flow_blackoil_dunecpr.cpp
made the cpr test solver less verbose
> changed verbosity of the cpr solver

- opm/autodiff/BlackoilModelEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
@akva2 This should be part of the release.
> BUGFIX. Make sure that the convergece report is stored before throw

- ebos/eclthresholdpressure.hh
- ebos/ecltransmissibility.hh
- opm/autodiff/AquiferInterface.hpp
- opm/autodiff/BlackoilAquiferModel_impl.hpp
- opm/autodiff/BlackoilModelEbos.hpp
- opm/autodiff/BlackoilWellModel.hpp
- opm/autodiff/BlackoilWellModel_impl.hpp
- opm/autodiff/ISTLSolverEbos.hpp
- opm/autodiff/ISTLSolverEbosCpr.hpp
- opm/autodiff/MultisegmentWell_impl.hpp
- opm/autodiff/StandardWellV_impl.hpp
- opm/autodiff/StandardWell_impl.hpp
- opm/autodiff/WellInterface.hpp
- opm/autodiff/WellInterface_impl.hpp
- opm/core/wells/WellsManager_impl.hpp
- tests/test_ecl_output.cc
Would be nice if this would be merged into the release, too.
> Remove warnings experienced with g++-8 

- ebos/eclwriter.hh
In the case where two were direct vertical neighbors in the grid but not in the underlying cartesian grid (e.g. because of MINPV or pinch outs), we treated them as NNCs and wrote the transmissibilty
to TRANNC.
With this patch we detect this situation (two neighbor cells with identical i and j and no active cells between them) and do not create an NNC in the eclipse output files but write the transmissibility to TRANZ.
> Write transmissibility between direct vertical neighbors into TRANZ.

- ebos/ecloutputblackoilmodule.hh
Found a bug in ecloutputblackoilmodule.hh
> fix typo in fip output

- opm/autodiff/BlackoilModelParametersEbos.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellV.hpp
- opm/simulators/wells/StandardWellV_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
The common part is moved to the well interface class
> Add well potential output to MSW

- ebos/ecloutputblackoilmodule.hh
Currectly output FPRP values, instead of overwriting the FPR values.
> Fix FPRP output

- CMakeLists.txt
- ebos/eclbasevanguard.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclthresholdpressure.hh
- ebos/ecltracermodel.hh
- ebos/tracervdtable.hh
this PR contains a bunch of cleanups -- like typo and whitespace fixes, message improvements, etc -- for ebos. It also adds the possibility to disable aquifer handling in ebos, because I had some severe issues with them for a deck I was recently working on. none of them should have any effect on the simulation results of `flow`...
> Ebos cleanups

- opm/autodiff/FlowMainEbos.hpp
This change will print the encountered unknown keywords to std::cerr (albeit in the format ThisKeyword and not --this-keyword) and abort before running the simulator.
This is an alternative to #1842 that uses existing ewoms functionality. Namely, `Parameters::printUnused()` which returns a bool (Note: a print function that returns a value...)
> Abort if flow is run with unknown keywords.

- ebos/eclwellmanager.hh
- opm/core/wells/WellsManager.cpp
- opm/core/wells/WellsManager.hpp
- opm/core/wells/WellsManager_impl.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_stoppedwells.cpp
- tests/test_wellmodel.cpp
- tests/test_wellsmanager.cpp
- tests/test_wellstatefullyimplicitblackoil.cpp
When this is ready and merged the simulator side of UDQ and ACTIONX is complete&trade;
> Use shared summarystate

- opm/simulators/wells/MSWellHelpers.hpp
This PR depends on OPM/opm-material#337
> Make calculateFrictionFactor evalution  + critical bugfix in MSW friction model

- ebos/eclwriter.hh
Followup to: https://github.com/OPM/opm-common/pull/816
> Remove unused arguments from write task

- ebos/eclbasevanguard.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- tests/test_ecl_output.cc
The last time I wrote MPI code we were searching in the internet with AllTheWeb and Infoseek; feedback welcome. 
As indicated my MPI skills are not razor sharp, and I would like some feedback on that, but apart from that I consider this to be roughly complete and ready for review/comments.
> Summary bcast

- opm/simulators/wells/MultisegmentWell_impl.hpp
This improves both convergence and accuracy of injecting MSW. 
Tested on model 2 realization.
> Upwinding for MSW

- ebos/eclwriter.hh
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellConnectionAuxiliaryModule.hpp
- tests/test_ecl_output.cc
> remove unused variables

- ebos/eclproblem.hh
> Only apply timestep after event at the beginning of an episode

- CMakeLists.txt
- use loops instead of copy-paste
- use object libraries to avoid some unnecessary archives
- tab scrubbing
> changed: simplify buildsystem a little

- opm/simulators/flow/FlowMainEbos.hpp
> Fix typo, indentation and return in unknown-parameter situation.

- opm/core/wells/WellsGroup.cpp
- opm/core/wells/well_controls.c
- opm/core/wells/wells.c
> Some janitoring

- compareECLFiles.cmake
- tests/update_reference_data.sh
Reverts OPM/opm-simulators#1923
Merged by mistake
> Revert "Add UDQ_WCONPROD model to integration testing"

- opm/simulators/linalg/ISTLSolverEbos.hpp
Downstream of https://github.com/OPM/opm-material/pull/347
> suppress some unused variables warnings without mpi

- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
not tested yet, so mark it as WIP. 
Will let know when it is ready for review.
> adding GOR checking for WECON

- opm/core/wells/WellCollection.cpp
- opm/core/wells/WellCollection.hpp
- opm/core/wells/WellsGroup.hpp
- opm/core/wells/WellsManager.hpp
- tests/test_wellcollection.cpp
- tests/test_wellsgroup.cpp
Downstream of https://github.com/OPM/opm-common/pull/881
> Header file Group.hpp moved to Group/Group.hpp

- tests/test_wellsgroup.cpp
Followup to: https://github.com/OPM/opm-common/pull/888
> Remove calls to Schedule::getGroups()

- opm/simulators/flow/MissingFeatures.cpp
Pull request OPM/opm-common#849 added support for this keyword.
> Remove FILLEPS from MissingFeatures

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Make sure well potentials are calculated if a restart file is requested.
> Calculate well potentials: check if restart file output is requestd

- opm/core/wells/WellCollection.cpp
- opm/core/wells/WellCollection.hpp
- opm/core/wells/WellsGroup.cpp
- opm/core/wells/WellsGroup.hpp
- opm/core/wells/WellsManager.hpp
- opm/core/wells/WellsManager_impl.hpp
- tests/test_wellcollection.cpp
- tests/test_wellsgroup.cpp
Followup to: https://github.com/OPM/opm-common/pull/900
> Use class Group2 from opm-common

- opm/simulators/linalg/OwningTwoLevelPreconditioner.hpp
This is intended to fix issue #1941.
> Use a dummy SequentialInformation object for the serial case.

- CMakeLists.txt
- compareECLFiles.cmake
- ebos/ebos_gasoil.cc
- ebos/ebos_oilwater.cc
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- flow/flow.cpp
- flow/flow_ebos_foam.cpp
- flow/flow_ebos_foam.hpp
- flow/flow_ebos_oilwater.cpp
- flow/flow_ebos_oilwater_polymer.cpp
- flow/flow_ebos_oilwater_polymer_injectivity.cpp
- opm/core/props/BlackoilPhases.hpp
- opm/core/props/phaseUsageFromDeck.hpp
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/update_reference_data.sh
This is the companion PR to OPM/ewoms#528.
It also requires OPM/opm-common#883, but that can be merged independently.
> Use foam module

- CMakeLists.txt
- ebos/ebos_foam.cc
- ebos/ebos_foam.hh
- ebos/ebos_foam_main.cc
- ebos/mebos_main.cc
not having this module available in `ebos` seems hughly inelegant to me.
> enable the foam extension for ebos/mebos

- CMakeLists_files.cmake
- opm/core/wells/well_controls.cpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.hpp
This is a follow-up to #1928 adding a commit implementing a workaround. Still in testing.
> [WIP] Handle GRUP-caused uninitialized (-1) well control index

- CMakeLists.txt
- debian/control
- dune.module
- jenkins/build.sh
- opm-simulators-prereqs.cmake
- redhat/opm-simulators.spec
- tests/update_reference_data.sh
Downstream of https://github.com/OPM/ewoms/pull/532
> changed: rename ewoms to opm-models

- ebos/eclproblem.hh
Lo and behold - ACTIONX is coming to town!
The current PR seems to run the [UDQ_ACTIONX](https://github.com/OPM/opm-tests/blob/master/udq_actionx/UDQ_ACTIONX.DATA) testcase - although there is a crash at the end of the simulation (which will be fixed in opm-common).
Observe that I have done things slightly differently from what is the common pattern in ebos based simulators; instead of fetching the required objects through omnipresent back-references I have opted to pass the required arguments explicitly. '
**Update**: In all decency I added WIP label; codewise I actually think this is ready - but quite a lot more testing is needed ....
> Add applyActions() to EclProblem

- ebos/eclproblem.hh
Followup to: https://github.com/OPM/opm-common/pull/979
> Add reportStep argument to Schedule::actions()

- opm/simulators/flow/MissingFeatures.cpp
> Keywords w

- opm/simulators/linalg/BlackoilAmg.hpp
- opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
Downstream of https://github.com/OPM/opm-models/pull/535
> changed: ewoms/linear -> opm/simulators/linalg

- opm/simulators/linalg/BlackoilAmgCpr.hpp
Taken from commit d71f7045 (PR #1998.)
> AmgCpr: Follow Relocation of "matrixblock.hh"

- ebos/eclwellmanager.hh
- ebos/eclwriter.hh
Downstream of https://github.com/OPM/opm-models/pull/538
> changed: ewoms/parallel -> opm/models/parallel

- ebos/eclbasevanguard.hh
- ebos/eclwriter.hh
- tests/test_stoppedwells.cpp
- tests/test_wellcollection.cpp
- tests/test_wellmodel.cpp
- tests/test_wellsgroup.cpp
- tests/test_wellsmanager.cpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1030
> Pass sim start argument to SummaryState constructor

- ebos/equil/equilibrationhelpers.hh
- tests/test_equil.cc
Followup to: https://github.com/OPM/opm-common/pull/1035
See alternative: #2019
> Use new EquilRecord from opm-common

- ebos/eclproblem.hh
Default is still to not use it, i.e this does not change anything.
> Make it possible to test driftCompensation i Flow

- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
Ask for SSOLVENT from the restart files if solvent model. 
Without this fix solvent saturation will always be zero after restart.
> Fix solvent restart

- ebos/eclwriter.hh
- tests/test_ecl_output.cc
This commit adds requisite libecl includes that are needed as an intermediate step for enabling new summary writing independent of libecl.
> Prepare for Making Summary Writing Independent of LibECL

- ebos/eclwriter.hh
- opm/simulators/linalg/MatrixBlock.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
This PR cleans the use of matrices over SparseMatrixAdapter in the various well models to make the code compile, when other linear solver frameworks are used. In addition it contains to minor fixes.
> Cleanup SparseMatrixAdapter.

- opm/simulators/flow/MissingFeatures.cpp
The last of the unsupported W keywords
> Add missing features for W keywords

- opm/core/props/satfunc/RelpermDiagnostics.cpp
- opm/core/props/satfunc/RelpermDiagnostics.hpp
- opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
- tests/test_wellmodel.cpp
This commit just removes some unused references to `GridManager.hpp`. Can the complete `GridManager` class be removed?
> GridManager - is it in use?

- CMakeLists.txt
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- flow/flow_blackoil_dunecpr.cpp
- flow/flow_onephase.cpp
- flow/flow_onephase_energy.cpp
- flow/flow_tag.hpp
- opm/core/props/phaseUsageFromDeck.hpp
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- opm/simulators/timestepping/TimeStepControl.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/RateConverter.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
This is a rebasing and further revision of #1969.
> Enable onephase

- ebos/eclwellmanager.hh
- ebos/eclwriter.hh
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
Stop reading the restart values twice.
> sync restart

- ebos/ecltransmissibility.hh
- opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
Followup to: OPM/opm-common#1051
> Adapt to removal of GridProperty::iget()

- ebos/ebos_altidx.cc
- ebos/ebos_blackoil.cc
- ebos/ebos_foam.cc
- ebos/ebos_gasoil.cc
- ebos/ebos_oilwater.cc
- ebos/ebos_polymer.cc
- ebos/ebos_solvent.cc
- ebos/ebos_thermal.cc
- ebos/eclnewtonmethod.hh
- ebos/eclproblem.hh
- ebos/startEbos.hh
- opm/simulators/flow/FlowMainEbos.hpp
With this .PRT and .DBG files are created also for ebos.
Does not impact Flow. 
Depends on OPM/opm-models#553
> Add logging in ebos

- ebos/ebos_altidx.cc
- ebos/ebos_blackoil.cc
- ebos/ebos_foam.cc
- ebos/ebos_gasoil.cc
- ebos/ebos_oilwater.cc
- ebos/ebos_polymer.cc
- ebos/ebos_solvent.cc
- ebos/ebos_thermal.cc
- ebos/eclnewtonmethod.hh
- ebos/eclproblem.hh
- ebos/startEbos.hh
- opm/simulators/flow/FlowMainEbos.hpp
With this .PRT and .DBG files are created also for ebos
> Add logging in ebos (backport of PR #2048 to release)

- ebos/eclfluxmodule.hh
- ebos/eclproblem.hh
- opm/simulators/flow/MissingFeatures.cpp
> enable rockcomp in flow

- opm/simulators/flow/MissingFeatures.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1122
> Use Location class for keyword location

- flow/flow.cpp
> stdout logging only for rank 0 (backport of PR #2061)

- ebos/eclwellmanager.hh
- ebos/eclwriter.hh
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
> sync restart (backport of PR #2034)

- ebos/collecttoiorank.hh
This is needed to support dune-fem where the local mapper might
be
```C++
MultipleCodimMultipleGeomTypeMapper<GridView<GridPart2GridViewTraits<AdaptiveLeafGridPart<CpGrid, (PartitionIteratorType)4,
false> > >, Dune::Impl::MCMGFailLayout>
```
as opposed to the global one being
```C++
MultipleCodimMultipleGeomTypeMapper<GridView<DefaultLeafGridViewTraits<CpGrid>>, Dune::Impl::MCMGFailLayout>
```
Closes #2095.
> Allow different ElementMapper types in ElementIndexScatterHandle.

- CHANGELOG.md
This surely needs some revisions. Would be nice if these came in via PRs against my branch to save me time.
> Added entries to changelog concerning 2019.10 release

- opm/simulators/wells/MultisegmentWell_impl.hpp
> BUGFIX. Scale MSW injector

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
With this item 11 and item 12 in GCONINJE is supported.
> Support custom vrep and rein group

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
This basically copies the control code from standard well to MSW. Refactoring will be done later after #2108 is merged. Gives excellent results on NORNE_ATW2013_1B_MSW. 
Operabilty check and well potential for MSW is still missing.
> add support for thp control in MSW

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Fix for hierarchy of production groups.
> Fix for hierarchy of production groups. 

- opm/simulators/wells/StandardWell_impl.hpp
The most important improvement here is using the more robust RegulaFalsiBisection nonlinear scalar solver for the bhp-at-thp-limit process.
> Prediction improvements

- ebos/ecloutputblackoilmodule.hh
- ebos/eclwriter.hh
I don't think I am getting the updated values at each time step from the summary state. Could anyone point me out the correct way?
> Add Production and Injection Reports to PRT

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Gives good results on Norne 2a. 
Replaces #2143
> Various group control fixes

- ebos/eclcpgridvanguard.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/ecltracermodel.hh
- ebos/eclwellmanager.hh
- opm/core/wells/WellCollection.cpp
- opm/core/wells/WellCollection.hpp
- opm/core/wells/WellsGroup.cpp
- opm/core/wells/WellsGroup.hpp
- opm/core/wells/WellsManager.cpp
- opm/core/wells/WellsManager.hpp
- opm/core/wells/WellsManager_impl.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/SimFIBODetails.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellConnectionAuxiliaryModule.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellcollection.cpp
- tests/test_wellmodel.cpp
- tests/test_wellsgroup.cpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1217
> Rename Well2 -> Well and Group2 -> Group

- ebos/eclcpgridvanguard.hh
When filterConnections_ is called the grid is not load balanced, yet. Currently that means that grid() will also return the unbalanced grid and all processes will see the whole global grid.
We will change semantics of the unbalanced grid soon: Only the root process will see the whole grid and the others will see an empty partition of it. Hence filtering on this partition will remove all connections on all wells in the schedule for non-root processes and produce wrong results.
For non-root process the filtering needs to be done on the load balanced grid. This is accomplished by this commit.
This PR is needed for the upcoming rebase PR OPM/opm-grid#405 to produce correct results.
> Only filter in filterConnections_ on root process.

- opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
Downstream of: https://github.com/OPM/opm-material/pull/363
> Use EclEpsGridProperties constructor

- opm/simulators/flow/FlowMainEbos.hpp
> Print number of MPI/OMP threads at start and end.

- CMakeLists_files.cmake
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/PerforationData.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_stoppedwells.cpp
- tests/test_wellmodel.cpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Rebased version of #2108 after the Well2->Well and Group2->Group renaming.
> Avoid using the Wells struct.

- ebos/ecltransmissibility.hh
- ebos/eclwriter.hh
Downstream of https://github.com/OPM/opm-common/pull/1259
> changed: nncdata() has been renamed to data()

- opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
Downstream of: https://github.com/OPM/opm-material/pull/365
This is only one additional commit on top of #2165
> Pass actnum

- tests/test_stoppedwells.cpp
Small step in the 3D refactoring saga
> Use EclipseState based Schedule constructor

- opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
Attempt to fix issue reported on #2188 / #2167
> Use active index in RelpermDiagnostic_impl

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Depends on OPM/opm-common#1252
> Group event

- tests/update_reference_data.sh
requested here; https://github.com/OPM/opm-tests/pull/192
Downstream of https://github.com/OPM/opm-common/pull/1263
> Add ascii diff of changes to data update PR

- opm/simulators/flow/MissingFeatures.cpp
This should have been on the release train - my bad.
> Remove keywords from list of missing features

- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
Default is zero. -> should not change anything if not provoked.
> Add option for throwing for small time steps

- ebos/eclproblem.hh
Update message from `applyAction()` to show actual date when action is tested.
> Update output from applyActions() to show date

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Use a bhp control when a well is controlled by a invalided group control
> fix issue when GRUP is used in WCONPROD and WCONINJE and NONE 

- compareECLFiles.cmake
This adds some more parallel tests. Will be useful when working on changing parallelism.
> Add some more parallel tests

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
This is PR #2185 minus the solve every iteration change.
> Support for Gconsale and Gconsump 

- CMakeLists.txt
Add cmake flag to enable 3D property testing.
> Add cmake switch to enable testing of new 3D property implementation

- CMakeLists.txt
- ebos/ebos_oilwaterpolymer.cc
- ebos/ebos_oilwaterpolymer.hh
- ebos/ebos_oilwaterpolymer_main.cc
- ebos/mebos_main.cc
This PR simply adds an oil-water-polymer option for the ebos simulator.
> [feature][ebos] Adding oil-water-polymer option of ebos.

- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Resolves warning from the clang compiler.
> Add override to silence warnings.

- ebos/eclcpgridvanguard.hh
When cells have been deactivated we need to call out to the property contanier with the new active cells map.
> Update the internal ACTNUM in the FieldPropsManager

- ebos/eclcpgridvanguard.hh
> Use Dune communicator instead of raw MPI call

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1344
> Add MPI serialization support for various class types

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Next batch. Downstream of https://github.com/OPM/opm-common/pull/1349
> Add MPI serialization for various types

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1352
> More MPI serialization support

- ebos/femcpgridcompat.hh
- opm/simulators/linalg/BlackoilAmg.hpp
Two minor changes to make code compile with current DUNE master and 2.7 release.
> Fix compilation with DUNE 2.7

- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
I think this will be useful for testing and debugging.
> at option to set the time step size for shutting problematic wells

- ebos/eclpolyhedralgridvanguard.hh
- ebos/eclwriter.hh
- opm/simulators/linalg/ExtractParallelGridInformationToISTL.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/findOverlapRowsAndColumns.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
This PR fixes various issues when switching ebos from CpGrid to PolyhedralGrid.
> Make ebos compile with PolyhedralGrid again.

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
The well efficiency factor should not be in the well control equation.
> Fix bug in the well efficiency factor

- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
- opm/simulators/aquifers/AquiferInterface.hpp
- opm/simulators/aquifers/BlackoilAquiferModel.hpp
- opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
It will make the editing of these files easier.
> re-formatting aquifer files with clang-format

- opm/simulators/flow/MissingFeatures.cpp
This is *really* not supported ;-)
> Mark UDT as not supported

- opm/simulators/wells/StandardWell_impl.hpp
This improves the results on the UDQ_WCONPROD case.
> set bhp control explicilty for well potential calculations

- opm/simulators/aquifers/AquiferFetkovich.hpp
to handle the situation when influx coefficient is not defaulted. 
Will check more tomorrow and some correction or improvement can be added.
It is not completely clear from the document. The indentation is not very convenient for this file.
> fixing the non-defaulted influx coefficient for AquiferFetkovich

- compareECLFiles.cmake
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Tested on the spe9group case. 
We may want to reduce the number of communication points to speed up the run.
> communicate group rates

- ebos/eclproblem.hh
> fix build without mpi

- flow/flow.cpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1393
> Avoid using global ecl state setting up SummaryConfig on non-root processes

- opm/simulators/utils/ParallelRestart.hpp
this was intended to check for 1 process all along. *BLUSH*
> fixed: 0 processes is too 'special' a special case

- flow/flow.cpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1407
See description in upstream PR. While the two last commits, marked with [TEMP] should not really make a difference, they do. With the commits, all tests pass, if you drop the two temp commits, the SPE9_CP_GROUP test fails. I cannot figure out why. Please help.
> Avoid using deck setting up Schedule on non-root processes

- ebos/eclproblem.hh
I see no reason why this code is duplicated like this.
> changed: avoid near-duplicate code

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
Switch all down-stream wells with same phase as the violated group to GRUP control.
> Fix REIN for multi level groups by passing the top phase

- ebos/eclthresholdpressure.hh
- ebos/ecltransmissibility.hh
- ebos/equil/initstateequil.hh
- tests/test_wellmodel.cpp
Downstream of https://github.com/OPM/opm-common/pull/1420
> Remove #include GridProperty

- ebos/eclproblem.hh
- opm/simulators/utils/ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-material/pull/383
> Avoid deck usage on non-root processes setting up FluidSystem

- ebos/eclproblem.hh
Downstream of https://github.com/OPM/opm-material/pull/384
> changed: adjust to split of initFromDeck in EclMaterialManager

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1422
These are the final bits to enable serialization of EclipseState.
As a FYI and motivation; while it's full of hacks, I can now run completely without parsing on non-root processes locally.
> More serialization support

- ebos/eclmpiserializer.hh
- ebos/eclproblem.hh
4 uses, simpler syntax in the problem code. i think this justifies a helper template.
> changed: add helper template to serialize and broadcast static types

- ebos/eclmpiserializer.hh
- ebos/eclproblem.hh
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
downstream of https://github.com/OPM/opm-material/pull/387
> Avoid deck usage on non-root processes setting up MaterialLawManager

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1429
> fix serialization after removed member in IOCOnfig

- ebos/equil/initstateequil.hh
it is now private
Downstream of https://github.com/OPM/opm-common/pull/1435
> don't use templated get and has interface from fieldpropsmanager

- tests/TESTTIMER.DATA
- tests/test_timer.cpp
Add 'SCHEDULE' section header to testdata
> Add schedule

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Update top serialize code
Upstream: https://github.com/OPM/opm-common/pull/1440
> Moved IOConfig to become member of RestartConfig

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
- Use macro for explicit instantations
- Give better error messages in tests
> Some cleanup in serialization

- ebos/eclproblem.hh
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1447
> update for simplified Tuning data structure in opm-common

- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
- opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/1451
> Aquifer refactor

- opm/simulators/linalg/bda/BdaBridge.cpp
fixes linking of flow_onephase with bda/cuda enabled.
no reason to run tests as this code is not used on jenkins.
> fixed: add explicit template instantation for blocksize 1

- CMakeLists.txt
- ebos/eclproblem.hh
- flow/flow.cpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
This PR restores the true asynchronicity for the output and ensures that all output is written before the simulator is finalized.
> Async output.

- dune.module
- ebos/collecttoiorank.hh
- ebos/eclcpgridvanguard.hh
- ebos/ecltracermodel.hh
- ebos/ecltransmissibility.hh
- ebos/eclwriter.hh
- ebos/femcpgridcompat.hh
- flow/flow_blackoil_dunecpr.cpp
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/linalg/BlackoilAmg.hpp
- opm/simulators/linalg/BlackoilAmgCpr.hpp
- opm/simulators/linalg/CPRPreconditioner.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/ISTLSolverEbosCpr.hpp
- opm/simulators/linalg/ParallelOverlappingILU0.hpp
- opm/simulators/linalg/PreconditionerFactory.hpp
- opm/simulators/linalg/amgcpr.hh
- opm/simulators/linalg/twolevelmethodcpr.hh
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/MSWellHelpers.hpp
- tests/DuneIstlTestHelpers.hpp
- tests/test_blackoil_amg.cpp
And quell deprecation warnings with 2.7
> Bump required dune version to 2.6

- opm-simulators-prereqs.cmake
Downstream of https://github.com/OPM/opm-common/pull/1456
> remove usage of CXX11Features module

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1463
> Update enum used in ICD status

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1460
> Remove members from WellSegment class

- ebos/eclbasevanguard.hh
- ebos/startEbos.hh
- opm-simulators-prereqs.cmake
- tests/test_vfpproperties.cpp
- tests/test_wellmodel.cpp
Downstream of https://github.com/OPM/opm-common/pull/1461
> remove boost::filesystem as dependency

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_ParallelRestart.cpp
> Allow for multiple group injection phases

- compareECLFiles.cmake
- ebos/eclproblem.hh
- opm/simulators/flow/MissingFeatures.cpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/run-parallel-regressionTest.sh
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-models/pull/589
Downstream of https://github.com/OPM/opm-material/pull/392
> fixed: call initFromDeck for Brine module

- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
- opm/simulators/aquifers/AquiferInterface.hpp
- opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1452
> Aquifer refactor aquancon

- ebos/eclbasevanguard.hh
- ebos/ecloutputblackoilmodule.hh
- flow/flow.cpp
- flow/flow_tag.hpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_ParallelRestart.cpp
- tests/test_norne_pvt.cpp
- tests/test_vfpproperties.cpp
Dwonstream of: https://github.com/OPM/opm-common/pull/1477
> RestartConfig has moved from EclipseState to Schedule

- ebos/eclproblem.hh
- ebos/ecltransmissibility.hh
Downstream of https://github.com/OPM/opm-common/pull/1504
Replaces #2312
> remove minpvFillNtg a temporary solution while not supporting standard minpv

- flow/flow.cpp
This PR contains the changes necessary in opm-simulators to be able to initialize purely from a restart file. Currently the interesting code is guarded by a
```
const bool init_from_restart_file = false;
```
i.e. it is *disabled*. The current PR can and should(?) be merged now, but actually setting the switch to `true` requires that the work in opm-common is completed. 
Eventually the `init_from_restart_file` should be fixed to `true` - but in an interim period it can optionally be a runtime configurable option - based on e.g. a commandline switch, an env variable, the lunar phase, .... ?
See discussion here: #2359 and here: https://github.com/OPM/opm-common/issues/1396
> Add disabled functionality to init wells and group from restart file

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of: 
https://github.com/OPM/opm-common/pull/1507
https://github.com/OPM/opm-material/pull/404
> Serialize density-temparture class DenT

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1517
Downstream of https://github.com/OPM/opm-material/pull/406
> add mpi serialization for SolventDensityTable

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of OPM/opm-common#1520
> Update for upstream changes to Group.

- ebos/eclproblem.hh
- opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
Downstream of https://github.com/OPM/opm-material/pull/408
> Use compressed properties in material law setup

- ebos/eclproblem.hh
Let's go slow here. Split out from https://github.com/OPM/opm-simulators/pull/2374
> changed: use compressed field properties setting up numbers

- ebos/eclproblem.hh
> changed: use compressed field properties for blackoil extension init conds

- ebos/eclproblem.hh
> use compressed field properties setting up explicit initial conditions

- ebos/ecltransmissibility.hh
> use compressed field properties applying NTG

- ebos/eclthresholdpressure.hh
> use compressed indices setting up ThresholdPressures

- ebos/ecltransmissibility.hh
> use compressed properties setting up permeabilities

- ebos/eclproblem.hh
> use compressed field properties setting up rock parameters

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1523
> adjust to upstream OilVaporization change

- ebos/ecloutputblackoilmodule.hh
> use compressed field property for fipnum

- ebos/ecltransmissibility.hh
> use compressed indices setting up transmissibilities

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1528
Not strictly downstream but related to https://github.com/OPM/opm-material/pull/410
> add mpi serialization for InitConfig::SurfaceConditions

- ebos/ecloutputblackoilmodule.hh
- ebos/eclwellmanager.hh
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.hpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1527
> InjectorType enum is moved out from Well class

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1529
> add mpi serialization for TlmixparTable

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1530
> changed: update FoamConfig serialization

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1535
> add mpi serialization for PolymerConfig

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1534
> add mpi serialization for PlmixparTable

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1536
> add mpi serialization for PlyvmhTable

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1540
> add mpi serialization for Stone1exTable

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1539
> Fix serialization for PlyshlogTable and RocktabTable

- ebos/eclproblem.hh
Downstream of https://github.com/OPM/opm-models/pull/600
> changed: no need to serialize FoamModule any longer

- ebos/eclproblem.hh
Rebased version of conflicting PR #2408 from @akva2
> rebased: changed: no need to serialize BrineModule any longer

- ebos/eclproblem.hh
Rebased version of @akva2's PR #2419 to remove conflicts.
> Rebased #2419: changed: no need to serialize PolymerModule any longer

- ebos/eclmpiserializer.hh
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Prerequisites:
https://github.com/OPM/opm-models/pull/600
https://github.com/OPM/opm-models/pull/601
https://github.com/OPM/opm-models/pull/602
> Drop unused serialization code

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1543
> update mpi serialization for Runspec

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1532
> Update serialization of Dimension class

- ebos/eclproblem.hh
- opm/core/props/satfunc/RelpermDiagnostics.cpp
- opm/core/props/satfunc/RelpermDiagnostics.hpp
- opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-material/pull/412
> No need to serialize MaterialLawManager any longer

- opm/simulators/utils/ParallelEclipseState.cpp
> fixed: serialize AquiferConfig

- opm/simulators/utils/ParallelRestart.cpp
i am confident it is okay to do this in general now.
Downstream of https://github.com/OPM/opm-common/pull/1548
> put the specialized DynamicState serialization functions in normal hierarchy

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1550
> update serialization for relocated KrModel

- flow/flow.cpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1549
> use eclmpiserializer for SummaryConfig broadcast

- opm/simulators/utils/ParallelEclipseState.cpp
- opm/simulators/utils/ParallelEclipseState.hpp
now done in base class.
Downstream of https://github.com/OPM/opm-common/pull/1552
> drop serialization from ParallelEclipseState

- README.md
Will merge straight away, touches no code or testing.
> Remove obsolete information from the README

- ebos/ecloutputblackoilmodule.hh
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1582
> adjust for SummaryNode -> SummaryConfigNode rename

- flow/flow.cpp
- flow/flow_tag.hpp
- opm/simulators/utils/ParallelEclipseState.cpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1565
Closes #2467
> EclMpiSerializer for Schedule

- ebos/eclmpiserializer.hh
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1568
> Internal serialization in EclipseState - part 1

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ParallelRestart.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/2465
Downstream of https://github.com/OPM/opm-common/pull/1578
> Internal serialization in EclipseState - part 3

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of opm/opm-common#1602
> Move Connection ordering attribute from Well to WellConnections

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream from: https://github.com/OPM/opm-common/pull/1603
> Remove numRemoved member from WellConnections

- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1612
> Add global index to Connection

- tests/test_ParallelRestart.cpp
Dwonstream of: https://github.com/OPM/opm-common/pull/1593
> Update serialization testing with PyAction

- ebos/eclmpiserializer.hh
> fixed: broadcasting an int and receiving as a size_t is a very bad idea

- ebos/eclbasevanguard.hh
- flow/flow.cpp
- flow/flow_tag.hpp
- tests/test_norne_pvt.cpp
- tests/test_stoppedwells.cpp
- tests/test_wellmodel.cpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1660
> Use std::shared_ptr for Python handle to Schedule

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1661
> Use only wconnection transmissibility without WellPI scaling

- opm/simulators/linalg/ISTLSolverEbos.hpp
when dune-fem is used in conjunction with opm-simulators.
> [bugfix][ISTLSolverEbos] fix compilation when dune-fem is used in

- opm/simulators/linalg/FlexibleSolver.hpp
Seems needed for some compilers
> [FlexibleSolver] Added missing headers determine IsComm.

- ebos/startEbos.hh
- opm/simulators/flow/FlowMainEbos.hpp
Donwtream of: https://github.com/OPM/opm-common/pull/1681
> MOve String utility in opm-common

- ebos/eclproblem.hh
This is a preparation for calling Python actions. The real change is coming here: https://github.com/OPM/opm-common/pull/1620 - but this PR can be merged alongside with: https://github.com/OPM/opm-common/pull/1694 right away; then the api part of it should be done.
> Add call to evaluate PYACTION in eclproblem::applyActions()

- opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
> remove unused lambda parameter

- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface_impl.hpp
Dwonstream of: https://github.com/OPM/opm-common/pull/1712
> Check availability for group control separately for inj/prod

- compareECLFiles.cmake
Dwonstream of: https://github.com/OPM/opm-common/pull/1716
> Rename config variable for Python

- compareECLFiles.cmake
First attempt in fixing MSW tests that fail locally. Need jenkins to provide new solutions to check.
> Reduced maximum time step on four MSW tests.

- opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
Necessary for reproducing runs with custom parameters.
> Add logging of linear solver parameter tree.

- compareECLFiles.cmake
Just a trivial code change intended to make the WSEGSICD test updated.
> Intended to update WSEGSICD test

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
Add serialize support for `std::optional<T>` - use coming here: #2573
> Add support for serializing std::optional

- compareECLFiles.cmake
- tests/update_reference_data.sh
Last know good test added. The remaining data sets need more work.
> Group tests4

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/TargetCalculator.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Only default action RATE is implemented for violation of maximum sales target
Tested on 9_3D and 9_3E.
> Implement min/max for GCONSALE

- opm/simulators/linalg/ISTLSolverEbosFlexible.hpp
- opm/simulators/linalg/WriteSystemMatrixHelper.hpp
Enables matrix dumping also without MPI. I did not get rid of HAVE_MPI though, since the Dune method called for parallel only exists within HAVE_MPI guards.
Also remove the need for the reinterpret_cast by adding some extra implementation details for more general block matrices. Although the code size is larger, I think this is a better solution, and much simpler from the point of view of the developer.
A final change is ensuring that the output matrices also get ".mm" filename endings in serial runs.
> Improvements to matrix writing facility.

- opm/simulators/flow/FlowMainEbos.hpp
A resubmission of commit 77a151b in PR #2403 and PR #2440 to work with the current master.
Currently, `execute()` calls `runSimulator()` to run the simulation. When the Python `step_init()` is implemented (in a later commit), it will instead call an `executeStepInit()` method that will need to do the same initialization as in the current `execute()` except that it should call a `runSimulatorInit()` method instead of `runSimulator()`. In order to avoid code duplication for `execute()` and `executeStepInit()`, `execute()` is here refactored into an `execute_()` method.
> Refactor `execute()` in `FlowMainEbos.hpp`

- CMakeLists_files.cmake
- examples/printvfp.cpp
I wrote a utility while debugging an issue related to VFP tables, to dump a slice of a table (varying rate and thp, at fixed gfr, wfr and alq).
> Add a small utility to print a slice of a VFP table.

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/MSWellHelpers.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1798
> Rename SpiralICD -> ICD

- opm/simulators/wells/VFPProdProperties.cpp
This reduces (a lot) the annoying debug messages about inf or nan numbers in the VFP input. Should not be merged without quite a bit of testing, but should be considered in the mix of msw improvements.
> Treat zero rate case for VFP tables.

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/1804
> Use WellConnections.segment_perf_length()

- ebos/eclbasevanguard.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_ecl_output.cc
Downstream of: https://github.com/OPM/opm-common/pull/1823
> Add Action::State member to EclPropblem and pass it to io/ActionX

- CMakeLists_files.cmake
- opm/simulators/linalg/FlexibleSolver.hpp
- opm/simulators/linalg/FlexibleSolver1.cpp
- opm/simulators/linalg/FlexibleSolver2.cpp
- opm/simulators/linalg/FlexibleSolver3.cpp
- opm/simulators/linalg/FlexibleSolver4.cpp
- opm/simulators/linalg/FlexibleSolver_impl.hpp
- opm/simulators/linalg/PressureSolverPolicy.hpp
- opm/simulators/linalg/getQuasiImpesWeights.hpp
- tests/test_flexiblesolver.cpp
A followup to #2667 making some minor improvements suggested in that discussion.
> Minor flexible solver improvements

- CMakeLists.txt
- flow/flow_ebos_oilwater_brine.cpp
- flow/flow_ebos_oilwater_brine.hpp
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/Main.hpp
This adds a oil water brine specialization. 
It also change the scaling of the brine residual from b_g to b_w.
> Add oil water brine specialization

- ebos/eclwriter.hh
That way we can use the same code for both the `writeOutput` and the `evalSummaryState` member functions.  While here, also change the declared types of `wellData` and `groupData` to `auto` in preparation of API updates for collecting group- and well level guiderate data.
Finally, apply `const` where possible.
> EclWriter: Refactor Cell Loop out to Helper Function

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Depends on OPM/opm-common#1849
> Add brine to output

- ebos/eclwriter.hh
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1860
> Add data::GroupValues member to RestartValue

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/1864
> Add WListManager argument when constructing ActionContext

- ebos/ecloutputblackoilmodule.hh
This commit ensures that we don't issue misleading warning about output creation directives such as
* `BASIC`
* `FREQ`
* `RESTART`
that could be, and typically are, put into keywords like `RPTRST` and `RPTSCHED`.  Previously, we would interpret these directives as names of cell vectors and we would get very confusing diagnostic messages of the form
```
Keyword 'BASIC' is unhandled for output to file
```
which suggests that `BASIC` is unsupported despite the output system supporting the directive for quite some time.  While here, also apply the same reasoning to the vectors we always output such as `SWAT`, `SGAS`, or `PRESSURE`.
> Cell Data: Don't Warn About Supported Output Directives

- opm/simulators/linalg/bda/BILU0.cpp
rowPerColor only has size numColors!
> [OpenCL] Fixes out of bounds read in reordering code in ILU0.

- ebos/eclequilinitializer.hh
- ebos/eclproblem.hh
- ebos/equil/equilibrationhelpers.hh
- ebos/equil/initstateequil.hh
- opm/simulators/flow/MissingFeatures.cpp
- tests/test_equil.cc
This PR implements SALTVD
Note it is build on top of #2698 for convenience.  i.e. the two first commits should be review as part of #2698.
The current SPE1_BRINE test has 0 for saltvd. I plan to adapt the test to include non-trivial SALTVD. 
I have tested this. And it gives the expected results.
> Implement SALTVD

- ebos/eclmpiserializer.hh
Another elegant and general `std::variant<...>` serialization implementation :-)
Downstream of: https://github.com/OPM/opm-common/pull/1886
> Serialize variant

- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/1890
> Extract UDQ eval to separate function call

- ebos/eclbasevanguard.hh
Downstream of: https://github.com/OPM/opm-common/pull/1889
> Add UDQState member to eclbasevanguard

- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/1896
> Add UDQState argument to output writer

- ebos/alucartesianindexmapper.hh
- ebos/eclbasevanguard.hh
- ebos/mebos_main.cc
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/linalg/BlackoilAmg.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp
- opm/simulators/timestepping/SimulatorTimer.cpp
- opm/simulators/wells/RateConverter.hpp
> use std::make_unique where applicable

- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/bda/WellContributions.cpp
- opm/simulators/linalg/bda/WellContributions.hpp
- opm/simulators/linalg/bda/openclKernels.hpp
- opm/simulators/linalg/bda/openclSolverBackend.cpp
- opm/simulators/linalg/bda/openclSolverBackend.hpp
Clean PR, derived from https://github.com/OPM/opm-simulators/pull/2716
> AddStandardWell functionality in OpenCL backend

- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/1887
> Pass the UDQState member when evaluating UDQ

- opm/simulators/linalg/ISTLSolverEbos.hpp
Closes #2759 
Thanks to @blattms for pointing it out plus implicitly confirming my fix.
> fixed: use the proper linear operator without wells in matrix in serial

- opm/simulators/linalg/bda/WellContributions.cpp
- opm/simulators/linalg/bda/WellContributions.hpp
- opm/simulators/linalg/bda/openclSolverBackend.cpp
- opm/simulators/linalg/bda/openclSolverBackend.hpp
Fixed the out of resources problem (issue #2754).
There are still a lot of time step chopping.
> Fixed out of resources problem 

- compareECLFiles.cmake
- tests/update_reference_data.sh
Enable regression testing of the models with the keyword combination MULTZ + PINCH::ALL
> Add regression testing for MULTZ + PINCH::ALL

- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/1910
> Add report_step argument to UDQConfig::eval()

- ebos/ecloutputblackoilmodule.hh
See: https://github.com/OPM/opm-common/pull/1891 for context
Will now support arbitrary regions. Quite significant refactorings. 
Usage from other modules is unhcanged - could maybe also benefit from some cleanup?
> Started to support summary regions

- ebos/ecloutputblackoilmodule.hh
The salt concentration output unit is density.
> fix output unit salt

- compareECLFiles.cmake
- ebos/ecloutputblackoilmodule.hh
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- tests/update_reference_data.sh
Fixes for oil-water + MSW simulations. A test case will follow.
> Fix oil water for MSW

- opm/simulators/wells/WellGroupHelpers.hpp
This PR switches the helper function
```
WellGroupHelpers::updateGuideRateForGroups<>()
```
to include efficiency factors in the potential rates at grouptree levels below a particular group.  We furthermore switch the helper function
```
WellGroupHelpers::updateGuideRatesForWells<>()
```
to not include efficiency factors at all.
The motivation for this change is that efficiency factors always apply to the level we're accumulating rate values into rather than to the rate values themselves.
>  Include All Pertinent EFACs In Guiderate Potential Updates

- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/readDeck.cpp
- opm/simulators/utils/readDeck.hpp
- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/1921
> Fix optional deserialization

- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1924
> Rename Location -> KeywordLocation

- ebos/equil/initstateequil.hh
- opm/simulators/flow/BlackoilModelEbos.hpp
> Remove references to unused class SimulationDataContainer

- ebos/collecttoiorank.hh
- ebos/ecldummygradientcalculator.hh
- ebos/eclfluxmodule.hh
- ebos/eclproblem.hh
- ebos/eclthresholdpressure.hh
- ebos/ecltransmissibility.hh
- ebos/eclwellmanager.hh
- ebos/eclwriter.hh
- opm/simulators/flow/NonlinearSolverEbos.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/ParallelOverlappingILU0.hpp
- opm/simulators/wells/WellInterface.hpp
See: https://github.com/OPM/opm-material/pull/428
> Remove unused #include of exceptions

- opm/simulators/flow/NonlinearSolverEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
> Add #include <opm/common/Exceptions.hpp>

- ebos/eclmpiserializer.hh
This happened for instance if serialization was attempted for a type that was not supported.
This then led to jobs hanging on jenkins, until timeout.
> fixed: avoid deadlocks in parallel if serialization throws

- ebos/ecloutputblackoilmodule.hh
For isothermal simulations (enableEnergy=false) but with non-constant temperature (RTEMPVD) we may want to output the temperature.
> output temperature when TEMP is set

- ebos/equil/equilibrationhelpers.hh
This is a rebase of #2607. 
I reran locally the performance test with 8 processes for Norne and model2, and my results are not quite the same as the benchmarks published earlier.
Norne, master:
```
Number of MPI processes:      8
Threads per MPI process:      1
Total time (seconds):         211.044
Solver time (seconds):        210.996
Assembly time (seconds):     60.3752 (Failed: 1.32051; 2.18717%)
Well assembly time (seconds): 15.6091 (Failed: 0.349605; 2.23975%)
Linear solve time (seconds): 117.269 (Failed: 2.37956; 2.02915%)
Linear solve setup time (seconds): 0.0065505 (Failed: 2.4991e-05; 0.381513%)
Update time (seconds):       5.77192 (Failed: 0.130375; 2.25877%)
Output write time (seconds): 2.22048
Overall Well Iterations:      928 (Failed: 5; 0.538793%)
Overall Linearizations: …
```
> Replace root finder with opm-common implementation

- ebos/eclproblem.hh
This PR does the following: 
1) move  update of quantities used in hysteresis and vappers from  beginEpisode to beginTimeStep. This will change the results. 
REMOVED FROM THIS PR
2) Don't update the intensive quantities due to update of hysteresis, vappers and rockcomp properties. The values should not change due to this, but the derivatives may. I.e. it could effect the newton convergence. 
REMOVED FROM THIS PR
I have not notices any major impact on the results. This should however be tested carefully.
> Change when hysteresis and vappers are updated

- opm/simulators/flow/MissingFeatures.cpp
Downstream of: https://github.com/OPM/opm-common/pull/1946
> Pass location to ParseContext.handleError()

- ebos/eclproblem.hh
Depends on OPM/opm-common#1974 (if you want reasonable results)
> Add support for ROCKTAB

- ebos/eclbasevanguard.hh
- ebos/eclcpgridvanguard.hh
This is downstream of OPM/opm-grid#491.
> Add command line parameter --serial-partitioning.

- ebos/eclproblem.hh
- opm/simulators/linalg/bda/MultisegmentWellContribution.cpp
- opm/simulators/linalg/bda/MultisegmentWellContribution.hpp
- opm/simulators/linalg/bda/WellContributions.cpp
- opm/simulators/linalg/bda/WellContributions.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
This probably would create conflicts when merged before #2821.
> Fixes compilation with DUNE 2.7

- opm/simulators/linalg/bda/WellContributions.cpp
- opm/simulators/linalg/bda/WellContributions.hpp
- opm/simulators/linalg/bda/WellContributionsOCLContainer.cpp
- opm/simulators/linalg/bda/WellContributionsOCLContainer.hpp
- opm/simulators/linalg/bda/openclSolverBackend.cpp
Reintroduced multisegment wells to the new implementation of the well management of OpenCL backend (https://github.com/OPM/opm-simulators/pull/2816)
> Reintroduced multisegment wells to OpenCL backend

- opm/simulators/linalg/bda/WellContributionsOCLContainer.cpp
- opm/simulators/linalg/bda/WellContributionsOCLContainer.hpp
and does some further cleanup.
> [opencl] deletes assignment operator of WellContributionsOCLContainer

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/StandardWell.hpp
See: https://github.com/OPM/opm-simulators/pull/2824#issuecomment-703065069
> Fix inconsistent-missing-override warnings

- ebos/ecltracermodel.hh
- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/timestepping/SimulatorReport.cpp
This pull request replaces #2803 adapting to recent changes. The new fmt formatting has still not been put into place, but review is still welcome. I believe fmt can come in a follow-up PR.
> Improve output

- opm/simulators/wells/WellState.hpp
- tests/test_ParallelRestart.cpp
- tests/test_ecl_output.cc
This is in preparation of implementing the WELPI feature.
> Provide Simulator's Dynamic CTF in data::Connection

- ebos/eclbasevanguard.hh
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
This was using the sum of the sum of all cells of the partitions. Hence the shared cells were counted twice.
Beware: this might change results (for the better).
> Fixes parallel computation of average formation factors.

- opm/simulators/linalg/ISTLSolverEbos.hpp
It is only used within this context and produces a warning of the form
```
ISTLSolverEbos.hpp:128:25: warning: unused variable ‘gridForConn’
```
unless the build configures accelerator support.
> Move 'gridForConn' Into Cuda/OpenCL Block

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
> changed: remove unused parameters

- CMakeLists.txt
increases parallelism
@atgeirr check if this works better for you.
> changed: compile each flow simulator as a object library

- compareECLFiles.cmake
- tests/update_reference_data.sh
Based on: https://github.com/OPM/opm-tests/pull/380/
> Add integration test for reporforated norne model

- tests/test_ecl_output.cc
> Use boost::test in test_ecl_output

- tests/test_equil.cc
> Use boost::test in test_equil

- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/2069
> Add wellmatcher argument when evaluating UDQ expressions

- ebos/eclproblem.hh
- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/flow/python/PyMaterialState.hpp
- opm/simulators/flow/python/PyMaterialState_impl.hpp
- opm/simulators/flow/python/simulators.hpp
- python/run-python-tests.sh.in
- python/simulators/CMakeLists.txt
- python/simulators/simulators.cpp
- python/test/test_basic.py
- python/test_data/SPE1CASE1/SPE1CASE1.DATA
Depends on #2830. 
Implements access (read/write) to the porosity from Python.
> Implements access to the porosity from Python.

- opm/simulators/wells/GasLiftRuntime.hpp
- opm/simulators/wells/GasLiftRuntime_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Small fixes for the well gas lift implementation.
> Fixes to the wlift implementation 

- compareECLFiles.cmake
- tests/update_reference_data.sh
Enable regression test with `WORPL` and family keywords
> Add regression test for summary + completion variables

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/PerforationData.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
This PR contains changes I did when working on supporting on distributed wells that should work with the current approach, too.
It is posted to:
- get at least some smaller PRs
- Easily test changes that do not rely on wells being distrubuted with the current approach.
Would be nice to merge this if it is ok.
> Parts of the distributed well work backported to original approach.

- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2101
> Add packing test for class PAvg

- debian/control
required after newly introduced test
> add python3-numpy to debian packaging

- opm/simulators/wells/BlackoilWellModel_impl.hpp
In serial we use the first cell of the first well to determine the pvt region index for a group. Previously, we used the first cell of
the first local well in a parallel run. Unfortunately that may lead to different pvt region indices being used for the same goup on
different processes.
We fix this by using the same approach in parallel as we already use in serial. For this we usedWell::seqIndex() to determine the needed ordering.
Closes #2921 (at least the reported parallel inconsistency, not whether the index used makes sense).
> Use consisten pvt region index for groups in parallel.

- CMakeLists.txt
- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
> remove unused variable

- CMakeLists.txt
- ebos/ebos_extbo.cc
- ebos/ebos_extbo.hh
- ebos/ebos_extbo_main.cc
- ebos/ebos_gasoil.cc
- ebos/ebos_oilwater.cc
- ebos/ebos_oilwaterpolymer.cc
- ebos/eclfluxmodule.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- flow/flow_ebos_extbo.cpp
- flow/flow_ebos_extbo.hpp
- flow/flow_ebos_gasoil.cpp
- flow/flow_ebos_oilwater_brine.cpp
- flow/flow_ebos_oilwater_polymer.cpp
- flow/flow_ebos_oilwater_polymer_injectivity.cpp
- flow/flow_onephase.cpp
- flow/flow_onephase_energy.cpp
- opm/core/props/BlackoilPhases.hpp
- opm/core/props/phaseUsageFromDeck.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
A first version, depending on corresponding pr for opm-models (extboModels) and opm-common (kwPVTEXTBO).
> Alternative solvent extension for the black oil model.

- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/2120
> Remove arguments

- ebos/ecloutputblackoilmodule.hh
- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/2122
> Pass the initial inplace values to Summary::eval()

- ebos/ecloutputblackoilmodule.hh
- ebos/eclwriter.hh
Upstream: https://github.com/OPM/opm-common/pull/2127
> Support summary keyword RHPV

- ebos/eclwriter.hh
Pass WBP Calculators to summary::eval()
Upstream: https://github.com/OPM/opm-common/pull/2118
> WIP: Pavg calculators

- CMakeLists_files.cmake
- ebos/eclbasevanguard.hh
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/ParallelWellInfo.cpp
- opm/simulators/wells/ParallelWellInfo.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellHelpers.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_parallelwellinfo.cpp
- tests/test_wellmodel.cpp
These are the first few commits of PR #2945 with a fix for the slight deviations in the well curves.
These were due to doing 
```C++
Y temp(y);
B.mv(x, temp);
y -= temp;
```
instead of `B.mmv(x,y)`.
> Prepares for apply distributed standard wells.

- opm/simulators/wells/WellHelpers.hpp
> Add missing template qualification.

- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Add missing override, and remove extra lambda capture.
> Silence warnings.

- opm/simulators/flow/BlackoilModelEbos.hpp
The convergence check for the extended model must have disappeared in a rebase.
> add convergence check for extended blackoil model

- ebos/eclequilinitializer.hh
- ebos/equil/initstateequil.hh
- tests/test_equil.cc
Tested on norne and it gives the same initial values in parallel and in serial. Should be tested on more models.
> dunify and make the initialization parallel

- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
A small simplification / preparation for #2936
> Change access to connpos to use WellMap instead of index counting

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/ParallelWellInfo.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/MpiFixture.hpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Will be rebased once #2954 is merged.
> Last part of current distributed standard wells.

- opm/simulators/wells/BlackoilWellModel_impl.hpp
We still want to try to compute the well potentials for the rest of the wells. 
See https://github.com/OPM/opm-simulators/pull/2980
> move the try-catch inside the compute potential loop

- CMakeLists.txt
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/ParallelWellInfo.cpp
- opm/simulators/wells/ParallelWellInfo.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_parallelwellinfo.cpp
This an extension of #2954 that produces correct. It is rebased on current master. though (and includes the other PR). Anyway, to be safe, this should only be merged after #2954 and I will probably need to rebase it before.
Relevant changes are only the last 4 commits.
> Make distributed standard well work on SPE9.

- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Small refactorings in the #2936 ordeal
> Msw shut wells

- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
This adds output for stopped wells.
> output stopped wells

- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/2171
> add serialization test for AutoICD

- opm/simulators/utils/ParallelRestart.hpp
> Output typeid(T).name() for types without packing support

- ebos/eclproblem.hh
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2190
> Access tuning class from ScheduleState

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2189
> Use ScheduleState to access nupcol

- ebos/eclproblem.hh
- ebos/eclwellmanager.hh
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2194
> Fetch events from ScheduleState

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2201
> Use ScheduleState to manage well test configuration

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2202
> Manage GConSale and GConSump with ScheduleState object

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2203
> Sched wlist

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Donwstream of: https://github.com/OPM/opm-common/pull/2205
> Use ScheduleState to manage network properties

- examples/printvfp.cpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/VFPInjProperties.cpp
- opm/simulators/wells/VFPInjProperties.hpp
- opm/simulators/wells/VFPProdProperties.cpp
- opm/simulators/wells/VFPProdProperties.hpp
- opm/simulators/wells/VFPProperties.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_vfpproperties.cpp
Have also simplified a bit here and there.
Downstream of: https://github.com/OPM/opm-common/pull/2210
> Vfp refactor

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2211
> Use ScheduleState to manage Actionx

- examples/printvfp.cpp
- opm/simulators/wells/GasLiftRuntime_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/VFPHelpers.hpp
- opm/simulators/wells/VFPInjProperties.cpp
- opm/simulators/wells/VFPInjProperties.hpp
- opm/simulators/wells/VFPProdProperties.cpp
- opm/simulators/wells/VFPProdProperties.hpp
- opm/simulators/wells/VFPProperties.hpp
- tests/test_vfpproperties.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2240
> Use std::reference_wrapper<> instead of pointers for VFP tables

- ebos/equil/initstateequil.hh
only warn about empty regions when none of the partitions contains the region
> Fix empty region output in parallel 

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
Depends on OPM/opm-common#2244
> get connection length and radius from the connection object

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
use info to disable code.
granted, extremely minor optimization but may as well apply it.
> changed: this is known on compile time

- opm/simulators/flow/BlackoilModelEbos.hpp
This hopefully fix seg-fault reported in #3000
> reset the iteration count in the newtonSolver

- opm/simulators/flow/BlackoilModelEbos.hpp
While here, also fix a couple of misprints in a nearby comment.
> Reset Non-Linear Iteration Count Before 'beginTimeStep'

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2275
> Pass simulation time argument to applyAction

- opm/simulators/wells/BlackoilWellModel_impl.hpp
See: https://github.com/OPM/opm-common/pull/2276
> Pass unscaled newWellPI to Schedule::applyWellProdIndexScaling()

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2285
> Add wellpi argument to Schedule::applyAction()

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
Preparation for ACTIONX + WELPI
> Extract functionality to update ecl_well

- ebos/ecltransmissibility.hh
> fix boundary face index on process boundaries

- tests/test_wellprodindexcalculator.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2287
> Use Well::convertDeckPI()

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
To enable reuse of implementation also for ACTIONX
> Extract method wellPI() from existing lambda implementation

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
> Implement BlackoilWellModel::hasWell() method

- opm/simulators/aquifers/AquiferInterface.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2294
> Aquifer connected cell area - unconditional access to double

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/VFPHelpers.hpp
- opm/simulators/wells/VFPInjProperties.cpp
- opm/simulators/wells/VFPInjProperties.hpp
- opm/simulators/wells/VFPProdProperties.cpp
- opm/simulators/wells/VFPProdProperties.hpp
- tests/test_vfpproperties.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2298
> Use class based enums for VFP flow types

- compareECLFiles.cmake
- tests/update_reference_data.sh
Set up integration test for: https://github.com/OPM/opm-tests/pull/478
> Add parallel test of partial TRAN EDIT

- ebos/ecloutputblackoilmodule.hh
Downstream of: https://github.com/OPM/opm-common/pull/2304
> Use ScheduleState for RFT configuration

- opm/simulators/wells/MSWellHelpers.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
Removed a confusing error message from LOG/PRT. @tskille please see if this fixes your issue.
> Do not report confusing error

- ebos/eclproblem.hh
Mainly a dummy to provoke a `update_data`for: https://github.com/OPM/opm-tests/pull/487
> Use fmt::format() for two messages

- ebos/eclproblem.hh
- opm/simulators/utils/ParallelEclipseState.cpp
> Use active index

- ebos/eclcpgridvanguard.hh
Just a comment which would have helped me when I was scratching my head over: https://github.com/OPM/opm-simulators/issues/3091
> Add comment about distribution

- ebos/eclbasevanguard.hh
- ebos/eclproblem.hh
- ebos/eclwellmanager.hh
- examples/printvfp.cpp
- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/SimulatorTimer.cpp
- opm/simulators/timestepping/SimulatorTimer.hpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_timer.cpp
- tests/test_wellmodel.cpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2310
> Remove timemap member from Schedule

- ebos/eclbasevanguard.hh
- ebos/ecloutputblackoilmodule.hh
- opm/simulators/wells/BlackoilWellModel_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2325
> Utilize private restartconfig

- opm/simulators/utils/readDeck.cpp
Dwonstream of: https://github.com/OPM/opm-common/pull/2326
> Add FieldProps argument to SummaryConfig constructor

- ebos/eclbasevanguard.hh
- opm/simulators/flow/Main.hpp
- opm/simulators/utils/readDeck.cpp
- opm/simulators/utils/readDeck.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2332
> Pass ouput interval overeride to Schedule constructor

- opm/simulators/wells/RateConverter.hpp
This is based on #1961, and replaces that PR as well as #3075.
> Fix hydrocarbon volume issue with no oil or gas

- opm/simulators/utils/readDeck.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2327
> Remove TableManager argument when constructing SummaryConfig

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
This is PR for temperature output reporting for producers. This is especially relevant for geothermal reservoir simulations.
A comparison with eclipse is given below for a three phase system:
Applied expressions derived for average well temperature:
> Temperature output for producers

- ebos/eclbasevanguard.hh
- ebos/eclcpgridvanguard.hh
- ebos/eclproblem.hh
This implements the convective DRSDT as described in
Sandve et al. "Convective dissolution in field scale CO2 storage simulations using the OPM Flow simulator" 
Submitted to TCCS 11, 2021
The convective DRSDT is activated with DRSDTCON
Depends on OPM/opm-common#2313
> Implement convective dissolution rate

- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
the unit is days for field and metric and hours for lab
the purpose is to shut down "dead" simulations
> Change minimum timestep size to 1e-12

- opm/simulators/utils/DeferredLogger.hpp
- opm/simulators/utils/DeferredLoggingErrorHelpers.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
Reopen of: https://github.com/OPM/opm-simulators/pull/3118
> Deferred logger will throw "correct" exception

- opm/simulators/timestepping/SimulatorReport.cpp
fix bug that sets global_time to 0
fixes #3069
> fix bug that sets global_time to 0

- python/CMakeLists.txt
- python/simulators/CMakeLists.txt
> Support system pybind11

- opm/simulators/aquifers/AquiferCarterTracy.hpp
This commit adds support for calculating and reporting the dimensionless time (simulator time divided by aquifer's time constant) and pressure (influence function evaluated at dimensionless time) values as part of the Carter-Tracy aquifer's `aquiferData()` reporting function.
These values are useful in their own right, e.g., for summary output through the keywords `AAQTD` and `AAQPD`, but they are also needed for ECLIPSE restart purposes.
> Report Dimensionless Time and Pressure for CT Aquifers

- ebos/eclmpiserializer.hh
- opm/simulators/utils/ParallelSerialization.cpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2347
> Remove references to RestartConfig

- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
Improve user message slightly - clearer to me at least.
> Change output to indicate start of time step

- ebos/collecttoiorank.hh
This is needed to properly communicate type-specific parameters to other processes.  In particular, outputting the Carter-Tracy summary vectors `AAQTD` and `AAQPD` needs this in a parallel simulation run.
> Unpack Aquifer Subobjects Too

- ebos/eclcpgridvanguard.hh
Report cell volume removed due to pinch.
> Report cell volume removed due to MINPV

- opm/simulators/wells/GasLiftStage2.hpp
- opm/simulators/wells/GasLiftStage2_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
I am working on making the gaslift code parallel, but I bang my head into an issue I have not been able to solve. 
The code exits with `free(): invalid pointer. `
after the vector is communicated through `allgatherv` 
Cool if I could get some help on this....
> make gaslift parallel

- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
> Simplify global is grup

- ebos/eclcpgridvanguard.hh
reported in https://github.com/OPM/opm-common/pull/2389#issuecomment-824034013
> fixing the serial running due to including of eclmpiserializer.hh

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Small improvement in the #3174 effort.
> WellState will internalize PhaseUsage member

- opm/simulators/utils/ParallelRestart.cpp
Sorry, I did not see this before the nightly redhat build broke...
> fixed: include <cstring> for strlen

- CMakeLists_files.cmake
- opm/simulators/wells/ALQState.cpp
- opm/simulators/wells/ALQState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_ALQState.cpp
Have extracted the ALQ related stuff from the WellStateFullyImplicitBlackOil class to a separate small class.
> Add class ALQState to manage the ALQ state in the WellState

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
I plan  to do some changes in updateWellStateWithTarget and I don't want to do it twice.
> Remove code duplication between STW and MSW

- CMakeLists_files.cmake
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GlobalWellInfo.cpp
- opm/simulators/wells/GlobalWellInfo.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellstatefullyimplicitblackoil.cpp
Create a small class with global well information in order to extract "stuff" from the WellStateFullyImplicitBlackOil class.
> Add class GlobalWellInfo and use it from WellState

- opm/simulators/wells/GasLiftStage2.hpp
- opm/simulators/wells/GasLiftStage2_impl.hpp
- opm/simulators/wells/GasLiftWellState.hpp
> fixed: do not include headers into Opm namespace

- opm/simulators/utils/UnsupportedFlowKeywords.hpp
Has been supported for a long time.
> The MAPUNITS keyword is supported

- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
> Store the number of connections in separate vector

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
Requires: https://github.com/OPM/opm-common/pull/2460
> Use mutable WellGroupEvents instance to track events in WellState

- tests/test_equil.cc
Downstream of https://github.com/OPM/opm-material/pull/459
> adjust to upstream enum changes

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
Note the first refactoring commit has its own PR #3183
> Improve initialization of the well rates for trivial rates

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Due to the many test failures of #3158 I decided to chop in into three.This is the first part. 
This is almost a pure refactoring, but note that the  the `updateWellControls(local_deferredLogger, /* check group controls */ false);
` inside the `if (param_.solve_welleq_initially_ && iterationIdx == 0) {` is missing.
> move solveWellEquation inside prepareTimeStep

- ebos/collecttoiorank.cc
- ebos/collecttoiorank.hh
- ebos/eclwriter.hh
- tests/test_ecl_output.cc
> fix regression: do not unconditionally dereference equilCartMapper

- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
Granted, this is more about my OCD than any real-world gains, but we may as well do this to get code elimination on compile time instead of runtime checks.
> Small micro-optims in WellInterface

- ebos/eclgenericvanguard.cc
- ebos/eclgenericvanguard.hh
These got stuck in the wrong branch during my PR series.
> Some small cleanups

- CMakeLists_files.cmake
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
> Put WellState in separate compile unit

- ebos/eclgenericcpgridvanguard.cc
- ebos/eclgenericthresholdpressure.cc
- ebos/eclgenerictracermodel.cc
- ebos/ecltransmissibility.cc
We need a test build with dunefem!
> fix building with dunefem

- opm/simulators/wells/TargetCalculator.cpp
Make sure the same type is used.
> FIX wrong type RESV group control

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
Use info available at compile time and if constexpr to eliminate some code.
> Some small code eliminiations in well code 

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.cpp
Extracted part of #3255. Access the bhp / thp / temperature members through a C like api. I am not saying this is how it should eventually be, but need to encapsulate things a bit to be able to refactor reasonably safe.
> Wellstate iget

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
This will need more testing, but is looks promising.
> Only compute potentials at beginTimeStep after an event

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.cpp
Make sure that iterations over segments go over the index for one well. To simplify further refactoring.
> Segment index

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftStage2_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellContainer.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.cpp
- opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp
- tests/test_wellstatefullyimplicitblackoil.cpp
This PR is a somewhat random collection of members from the `WellState` class which are changed to use `WellContainer<>`
> Use wellcontainer2

- ebos/eclgenericcpgridvanguard.cc
- ebos/eclgenericcpgridvanguard.hh
- ebos/eclgenericvanguard.hh
- opm/simulators/utils/ParallelRestart.hpp
- opm/simulators/wells/TargetCalculator.hpp
- opm/simulators/wells/WellGroupHelpers.hpp
Thank you clang for the two first commits, they point to real issues.
The last one however, is bending over backwards to a false clang diagnostic. Whether we want to do this or not I leave up to others to decide.
> Quell various clang warnings

- CMakeLists_files.cmake
- ebos/eclgenericwriter.cc
- ebos/eclgenericwriter.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- tests/test_ecl_output.cc
Sits on top of https://github.com/OPM/opm-simulators/pull/3263
Sits on top of https://github.com/OPM/opm-simulators/pull/3262
> eclwriter: split in typetag dependent and typetag-independent parts

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2482
> Make sure well potentials are recalculated for ACTIONX wells

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellContainer.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- tests/test_wellstate.cpp
More `WellContainer<>` preparations
> Wellcontainer perf

- opm/simulators/wells/WellState.cpp
The purpose of this change is to simplify change of container used for wellrates (`std::map<std::string, T> -> WellContainer<T>`) in a subsequent PR.
> Communicate well rates by directly iterating over container

- opm/simulators/wells/VFPHelpers.hpp
A threshold of 1e-8 is used to "define" small rate
I have tested this on the norne prediction models where it significantly reduce problems, run-time and unwanted peaks in the solution. Setting the "correct" thresholds is not trivial and we may want adjust this value a bit if it has unwanted impact on some cases. i.e. this PR should be tested carefully.
> Avoid division by small rate in divisor in VFP table fraction WFR/GFR.

- CMakeLists_files.cmake
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterface_impl.hpp
This sits on top of #3236 which should be processed first.
> Split out FluidSystem dependent code from WellInterface

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftStage2.hpp
- opm/simulators/wells/GasLiftStage2_impl.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/3299
> GasLiftStage2: drop simulator param

- CMakeLists_files.cmake
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/GasLiftSingleWell.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/GasLiftStage2.hpp
- opm/simulators/wells/GasLiftStage2_impl.hpp
- opm/simulators/wells/WellHelpers.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/3303
> GasLiftStage2: drop typetag dependence

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
Use well index for segment output variables.
> Segment use well index2

- opm/simulators/utils/readDeck.cpp
Upstream: https://github.com/OPM/opm-common/pull/2490
> Check that stdout is connected to tty before applying color coding

- opm/simulators/wells/WellGroupHelpers.cpp
This is a first attempt to fix the computation of reduction rate. This needs further testing.
> fix reduction rate for injection groups

- opm/simulators/linalg/bda/BdaBridge.cpp
- opm/simulators/linalg/bda/WellContributions.cpp
- opm/simulators/linalg/bda/WellContributions.hpp
> Fixes compilation with CUDA but without OpenCL.

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
Use well index to access various per perforation properties.
> Perf well access

- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/GasLiftStage2.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/3304
> GasLiftStage2: some cleanups

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
Use `WellContainer<std::vector<double>>` for various perforation properties.
> Perf wellcontainer

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
Manage  the Well potential using a WellContainer<>
> Manage well potentials with WellContainer<>

- opm/simulators/wells/TargetCalculator.cpp
> Scale target with resv conversion factor

- CMakeLists_files.cmake
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWellGeneric.cpp
- opm/simulators/wells/MultisegmentWellGeneric.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
avoid rebuilding this for all simulators when code  is only dependent on Scalar. specialized for double
Sits on top of https://github.com/OPM/opm-simulators/pull/3348
Downstream of https://github.com/OPM/opm-common/pull/2493
> Add MultisegmentWellGeneric

- CMakeLists_files.cmake
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWellEval.hpp
- opm/simulators/wells/StandardWellGeneric.cpp
- opm/simulators/wells/StandardWellGeneric.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterfaceEval.cpp
- opm/simulators/wells/WellInterfaceEval.hpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterfaceIndices.cpp
- opm/simulators/wells/WellInterfaceIndices.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/3348
> add StandardWellEval

- CMakeLists_files.cmake
- opm/simulators/wells/MSWellHelpers.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellEval.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/WellInterfaceEval.hpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterfaceIndices.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/3351
Downstream of https://github.com/OPM/opm-common/pull/2493
> add MultisegmentWellEval

- compareECLFiles.cmake
- ebos/ebos.hh
- opm/simulators/flow/BlackoilModelParametersEbos.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
This replace the Boolean switch to enable inner iterations with a
int that controls for which maximum number of newton iterations
inner iterations applies.
Default is set to 3
> Change the inner iterations logic

- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
Some variable renames++ in the WellState::report() method.
> Minor renames++ in WellState report

- opm/simulators/utils/ParallelRestart.cpp
- tests/test_ParallelRestart.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2504
> Rename data::WellRates -> data::Wells in opm-common

- tests/test_ParallelRestart.cpp
> Rename data::WellRates -> data::Wells

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
Small drive-by change while fighting with restart
> Use GuideRate value instead of std::unique_ptr<GuideRate>

- opm/simulators/wells/PerfData.cpp
- opm/simulators/wells/PerfData.hpp
- opm/simulators/wells/WellState.cpp
- tests/test_wellstate.cpp
Check injector/producer status in when creating perfdata and save some bytes
> PerfData maintains producre / injector status

- opm/simulators/flow/KeywordValidation.cpp
- tests/test_keyword_validator.cpp
Fixes a bug where validation of keywords that do not have a default value fails.
> Small fix for the keyword validation

- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
- opm/simulators/aquifers/AquiferInterface.hpp
This PR switches to using the analytic aquifer's intrinsic water properties (i.e., the mass density and the viscosity), and to get the time constant from the `*_data` structure instead of calculating this value with separate logic.  Note that this switches to using a single density value for the aquifer instead of separate density values for each aquifer connection.
If the aquifer's initial pressure is defaulted we still compute an equilibrated initial pressure value.  We then use the `*_data` structure's `finishInitialisation()` member function to derive the aforementioned PVT properties.
Finally, report these values in the aquifer type-specific sub structures of `data::AquiferData` for restart output purposes. This in turn entails adding logic to communicate more dynamic aquifer values …
> Use Aquifer's Notion of Water Properties

- ebos/eclgenerictracermodel.cc
- ebos/eclgenerictracermodel.hh
- ebos/ecltracermodel.hh
- ebos/eclwriter.hh
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
There is a corresponding PR for opm-common. 
Upstream: https://github.com/OPM/opm-common/pull/2468
> Tracer summary curves, collect well rates.

- tests/test_cusparseSolver.cpp
Same as the last commit of https://github.com/OPM/opm-simulators/pull/3300
> Added exception handling to cusparse test

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
- opm/simulators/utils/UnsupportedFlowKeywords.cpp
RUNSPEC and GRID keywords for partially supported keywords
> PartiallySupportedKeywords for RUNSPEC and GRID Sections

- opm/simulators/wells/WellInterfaceEval.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
This should be sufficient for UDQ_M1 to pass the test in PR #3409
> make sure the newly switched well is included in the local fraction sum

- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftGroupInfo.hpp
- opm/simulators/wells/GasLiftSingleWell.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_glift1.cpp
Current implemention only support ORAT and GRAT controlled groups
> Potentially reduce gaslift when under well is under group control
