- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
downstream of https://github.com/OPM/opm-common/pull/2537 .
> [new attempt] updating the guide rates for all the wells and groups at the same time

- redhat/opm-simulators.spec
- use system level boost now that RHEL6 is dead
> fix redhat packaging

- ebos/eclgenericoutputblackoilmodule.cc
This may be a preference thing, but imo data should be data and not copy-pasted code.
> changed: replace code with data in restart output

- ebos/ecltracermodel.hh
This hopefully improves the behavior of tracer concentration summary curves, (F/W)T(IR)C.
> Some regularisation of tracer rate reporting.

- flow/flow_ebos_blackoil.cpp
- flow/flow_ebos_blackoil.hpp
- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/utils/readDeck.cpp
With this basic UDQ restarting works - but ....
- There are some white space differences in UDQ expression.
- UDA is not supported yet
- The existing UDQ testcases do not restart - for other reasons ;-(
> Rst load udq

- tests/test_ParallelRestart.cpp
Type added in OPM/opm-common#2559.
> Add Serialization Test for WriteRestartFileEvents

- ebos/ecltracermodel.hh
- opm/simulators/utils/ParallelRestart.cpp
The first commit fixes a link error for me. The second squashes a warning.
> Fix bug and warning

- ebos/eclbaseaquifermodel.hh
- ebos/ecldummygradientcalculator.hh
- ebos/eclfluxmodule.hh
- ebos/eclnewtonmethod.hh
- ebos/eclwellmanager.hh
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/linalg/bda/BdaBridge.cpp
- opm/simulators/linalg/bda/FPGASolverBackend.cpp
- opm/simulators/linalg/bda/amgclSolverBackend.cpp
prefer anonymous parameters or c++17 [[maybe_unused]]
> changed: get rid of OPM_UNUSED macro usages

- opm/simulators/wells/RateConverter.hpp
Fix for the situation that hydrocarbon consist only of gas. Relevant for water-gas twophase system
> Rateconvfixed

- ebos/eclproblem.hh
- ebos/mebos_main.cc
- opm/core/props/phaseUsageFromDeck.cpp
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWellEval.hpp
- opm/simulators/wells/WellInterface.hpp
fixes to allow for gas-water system. This PR is related to https://github.com/OPM/opm-models/pull/665
> adjustments needed for gas-water system

- ebos/eclgenericvanguard.cc
- ebos/eclgenericvanguard.hh
- opm/simulators/flow/Main.hpp
- opm/simulators/flow/python/simulators.hpp
@blattms this what you had in mind right.
@jcbowden this should get you going.
> add collective communication to generic vanguard

- ebos/eclgenericwriter.cc
- ebos/eclgenericwriter.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
Extra command line argument write-lodsmry for creating LODSMRY file
- default is false
- LODSMRY file is re-written for every time step
- file LODSRMY optimized for fast loading of selected vectors
- This PR is dependent on PR OPM/opm-common#2590
> Adding command line argument for writing esmry file 

- CMakeLists.txt
- flow/flow_ebos_blackoil_poly.cpp
- flow/flow_ebos_blackoil_poly.hpp
- flow/flow_ebos_onephase.cpp
- flow/flow_ebos_onephase.hpp
- flow/flow_ebos_onephase_energy.cpp
- flow/flow_ebos_onephase_energy.hpp
- flow/flow_onephase.cpp
Slightly more compile units, but we can then build in parallel with the main library. This improves build time, in particular with many build jobs.
> Improve parallel build

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2618
> Store the action result - when evaluated to true

- ebos/ecltracermodel.hh
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
Also avoid duplication of to equal methods (getWell and well)
> fix case where wells are shut behind our back

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellGeneric.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellContainer.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_wellstate.cpp
> Single well state3

- CMakeLists_files.cmake
- opm/simulators/flow/KeywordValidation.cpp
- opm/simulators/flow/KeywordValidation.hpp
- opm/simulators/flow/ValidationFunctions.cpp
- opm/simulators/flow/ValidationFunctions.hpp
- opm/simulators/utils/readDeck.cpp
- tests/test_keyword_validator.cpp
> Add basic functionality for validating special case keywords

- ebos/ecltracermodel.hh
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellGeneric.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/PerfData.cpp
- opm/simulators/wells/PerfData.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_wellstate.cpp
Final PR in the mechanical refactor of wellState to single well state.
> Single well state

- ebos/eclgenericoutputblackoilmodule.cc
> Improve error message for invalid phase id

- opm/simulators/wells/GroupState.cpp
- opm/simulators/wells/GroupState.hpp
Upstream: https://github.com/OPM/opm-common/pull/2643
> Add GPMaint::State member to GroupState

- opm/simulators/utils/readDeck.cpp
If there are unknown keywords and the parser throws an exception the we nevertheless broadcasted the eclipseState and schedule. Unfortunately, these might be null pointers in this case and the serializer will run into a segmentation fault.
Broadcasting is now only done if parsing was successful.
> [bugfix] Prevent segmentation fault for unkown keywords in parallel.

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
Preparation for GPMAINT
Upstream: https://github.com/OPM/opm-common/pull/2648
> Use the group object to query for controls

- opm/simulators/wells/StandardWell.hpp
> drop unused using statements

- opm/simulators/utils/readDeck.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2651
> Add Runspec argument to restart loader

- CMakeLists_files.cmake
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GroupState.cpp
- opm/simulators/wells/GroupState.hpp
- opm/simulators/wells/RateConverter.hpp
- opm/simulators/wells/RegionAttributeHelpers.hpp
- opm/simulators/wells/RegionAverageCalculator.hpp
- opm/simulators/wells/TargetCalculator.cpp
- opm/simulators/wells/TargetCalculator.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterfaceEval.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
> Support for gpmaint

- opm/simulators/flow/KeywordValidation.hpp
> Add missing include for unordered_map.

- opm/simulators/utils/readDeck.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2663
> Add Parser argument to restart loader

- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
> oil target may be limited by LRAT as well

- ebos/eclproblem.hh
Upstream: https://github.com/OPM/opm-common/pull/2660
> Eavluate all UDQ ASSIGN statements at the start of report step

- opm/simulators/flow/BlackoilModelParametersEbos.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWellEval.hpp
- opm/simulators/wells/StandardWell_impl.hpp
The logic is the same as what's already there for msw
> add option for relaxed convergence for stw

- compareECLFiles.cmake
- tests/update_reference_data.sh
Add regression test of: https://github.com/OPM/opm-tests/pull/600
> Add actionx gconinje test

- opm/simulators/wells/StandardWell_impl.hpp
> use getMobilityScalar in updateIPR

- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
- opm/simulators/aquifers/AquiferInterface.hpp
Depends on OPM/opm-material#471 and OPM/opm-common#2694
If you want to run the test case in opm-tests you will also need OPM/opm-common#2691
> support aquct and co2store

- ebos/eclmpiserializer.hh
- tests/test_ParallelRestart.cpp
Upstream: https://github.com/OPM/opm-common/pull/2712
> Add serializer support for set - closely modelled after map

- opm/simulators/linalg/bda/cusparseSolverBackend.cu
- opm/simulators/linalg/bda/cusparseSolverBackend.hpp
cusparsesolver: wrong size and type in cols,rows fixed
> cusparsesolver wrong size and type in cols,rows fixed

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
We only want to open wells that can operate under both economical and physical reasons.
Depens on OPM/opm-common#2711
> Make wtest more robust

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_wellstate.cpp
> Use SingleWellState to manage parallel well info

- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
Fixup: https://github.com/OPM/opm-simulators/pull/3551#pullrequestreview-766401806
> Use const reference

- ebos/eclmpiserializer.hh
More direct test than looking for a 'serializeObject' member.
> Serializer: Detect Existence of 'serializeOp' Member Function

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2720
> Use WellTestConfig.empty() instead of size()

- opm/simulators/wells/BlackoilWellModel_impl.hpp
depends on https://github.com/OPM/opm-common/pull/2723
solves https://github.com/OPM/opm-simulators/issues/3555
> open completions after well event

- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
Trivial stuff:
- Add some documentation
- Remove unused private functions
- Remove function argument
> Wellstate doc

- ebos/collecttoiorank.cc
- ebos/collecttoiorank.hh
- ebos/eclwellmanager.hh
- ebos/eclwriter.hh
- tests/test_ecl_output.cc
Collect WellTestState on IO rank for restart output.
Upstream: https://github.com/OPM/opm-common/pull/2724
> 1: Pack and unpack WellTestState in CollectIO class

- ebos/eclgenericwriter.cc
- ebos/eclgenericwriter.hh
- ebos/eclwriter.hh
Downstream of: https://github.com/OPM/opm-common/pull/2722
> 2: Add wtest state arguments

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterface_impl.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2742
> Welltest state rename

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
Downstream of: https://github.com/OPM/opm-common/pull/2744
> Remove ecl wells argument to check wells for testing

- tests/test_ParallelRestart.cpp
Upstream: https://github.com/OPM/opm-common/pull/2748
> Add serialization testing for WellTestState

- CMakeLists.txt
- flow/flow_ebos_brine_energy.cpp
- flow/flow_ebos_brine_energy.hpp
> build flow_brine_energy as an object library

- ebos/eclproblem.hh
Drive by fix while debugging restart problems
> Remove unnecessary call to simulator.setStartTime()

- opm/simulators/flow/Main.hpp
In keeping with the other simulation cases.
> Separate MICP Case Out to Helper Function

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
This guarantees, under the assumption that the group tree does not have cycles, that we do not accumulate group-level guide rate values until all of its children are fully evaluated.  We use an iterative depth-first post-order tree traversal with an explicit stack instead of a recursive implementation.
The previous implementation, which tried to do the same kind of child-to-parent accumulation, might visit a parent group multiple times which in turn might lead to losing updates.  This is a more formalised approach to the value accumulation than was originally employed.
> Switch Guide Rate Accumulation to Post-Order Traversal

- opm/simulators/flow/Main.hpp
we do not want to invoke MPI_Abort in this case
> changed: special case no input deck given handling

- ebos/eclgenericvanguard.cc
- flow/flow_ebos_solvent.cpp
- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/linalg/WriteSystemMatrixHelper.hpp
- opm/simulators/linalg/setupPropertyTree.cpp
- opm/simulators/utils/ParallelFileMerger.hpp
- opm/simulators/utils/readDeck.cpp
- tests/test_vfpproperties.cpp
Downstream of https://github.com/OPM/opm-common/pull/2802
> use std::filesystem directly

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/PerfData.cpp
- opm/simulators/wells/PerfData.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_wellstate.cpp
This is the refactor part of: #3647
> Refactor wellstate init

- opm/simulators/wells/WellGroupHelpers.cpp
The reduction rate is computed differently for cases without wells under GRUP
For a well to check whether to switch to GRUP it needed to use the reduction rate
that would have been computed if this particular well was under GRUP control
and thus recompute the reduction rate without entering the no-grup path
> Adjust reduction rate when well control is considered for GRUP

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2818
> Rename EclipseState::apply_geo_keywords -> apply_schedule_keywords

- CMakeLists.txt
- opm/simulators/utils/ParallelRestart.hpp
- tests/test_broadcast.cpp
Then we can micro-optimize thngs like https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/BlackoilWellModel_impl.hpp#L968
> added: utility to broadcast multiple variables in one operation

- opm/simulators/wells/BlackoilWellModel_impl.hpp
This was the motivation for https://github.com/OPM/opm-simulators/pull/3674
Sits on top of that and should be processed after
> Use multivariable broadcast facility to broadcast rates

- opm/simulators/linalg/bda/amgclSolverBackend.cpp
use a regular template parameter instead
> fixed: auto function parameters requires the concept-ts

- opm/simulators/flow/Main.hpp
also avoid an unnecessary close/open for namespace Opm
> cosmetics: do not indent for namespace

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2831
> Use struct SimulatorUpdate as return type from Schedule::applyAction

- tests/update_reference_data.sh
fixes the changed tests output
> fixed: only update files if they actually changed

- compareECLFiles.cmake
to be careful, make it draft first for testing.
> removing --relaxed-max-pv-fraction for num aquifer tests

- opm/simulators/linalg/bda/BdaBridge.hpp
- opm/simulators/linalg/bda/BdaSolver.hpp
- opm/simulators/linalg/bda/WellContributions.cpp
- opm/simulators/linalg/bda/WellContributions.cu
- opm/simulators/linalg/bda/WellContributions.hpp
- tests/test_cusparseSolver.cpp
- tests/test_openclSolver.cpp
Just some obvious simplifications.
> Some simple cleanup in BDA WellContributions

- ebos/eclproblem.hh
Support MULTXYZ in ACTIONX block. Register that MULTXYZ has been invoked in an ACTIONX block and recalculate transmissibilities.
Downstream of: https://github.com/OPM/opm-common/pull/2832
> Geo actionx

- ebos/eclgenericoutputblackoilmodule.cc
Downstream of: https://github.com/OPM/opm-common/pull/2854
> Flag tracer solution data with data type RESTART_TRACER_SOLUTION

- ebos/eclgenericthresholdpressure.cc
- tests/test_keyword_validator.cpp
- tests/test_vfpproperties.cpp
Downstream of: https://github.com/OPM/opm-common/pull/2856
> Update deck access api

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterface_impl.hpp
Negative and trivial potentials creates problems for the guiderates.
> guard against negative and trivial potentials

- ebos/eclgenerictracermodel.cc
Downstream of: https://github.com/OPM/opm-common/pull/2868
> Initialize tracers based on optional values in TracerConfig

- opm/simulators/aquifers/AquiferInterface.hpp
- opm/simulators/aquifers/AquiferNumerical.hpp
Make it possible to use CO2STORE in combination with numerical aquifers.
> fix co2store + aqunum

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenerictracermodel.cc
- ebos/eclgenerictracermodel.hh
- ebos/eclproblem.hh
- ebos/ecltracermodel.hh
- ebos/eclwriter.hh
- ebos/vtkecltracermodule.hh
Will load and initiialize tracer model from restart vectors. NB: This is code I am not veeeery familiar with, and the implementation is on a strict minimum change basis.
test update: https://github.com/OPM/opm-tests/pull/689
> Tracer rst init

- ebos/eclproblem.hh
Add multiplication of missing reference oil density.
> Fix DRSDTDYN

- opm/simulators/linalg/bda/CPR.cpp
Fixes fallout (failing serial build) from #3672
> Fixes compilation of opencl CPR without MPI

- opm/simulators/wells/WellGroupHelpers.cpp
This is a very simple fix, but we should be aware that we do not support WEFAC item 3 (which should turn off well efficiency for network calculations only). I have therefore added a rather verbose comment for the next implementer.
> Account for efficiency when adding lift gas to network flows.

- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
The unmodified rates need to be passed to reduceALQtoGroupTarget(...) to get the right change in group rates.
> Fix when both well and group control restrict gaslift

- ebos/eclequilinitializer.hh
- opm/simulators/aquifers/AquiferInterface.hpp
- opm/simulators/wells/WellInterface.hpp
Extension PR https://github.com/OPM/opm-material/pull/429 and https://github.com/OPM/opm-models/pull/678
> update parameters BlackoilFluidSystem

- ebos/ecloutputblackoilmodule.hh
Downstream of https://github.com/OPM/opm-material/pull/488
> adjust to upstream changes

- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
This commit is a first step in a plan to fix up repetitive code in `GasLiftSingleWellGeneric.cpp`. More specifically: Note that 
the four methods [`getOilRateWithGroupLimit_()`](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/GasLiftSingleWellGeneric.cpp#L607), `getGasRateWithGroupLimit_()`, `getWaterRateWithGroupLimit_()`, and `getLiquidRateWithGroupLimit_()` all has essentially the same structure. The plan is to write a single general method that can be used instead, or possibly be wrapped by the four. 
This first step just fixes up one of the existing methods `getOilRateWithGroupLimit_()`, the plan is to use this method as the basis for deriving a general method that can be wrapped by the four methods mentioned above.
There is also a plan to address #3739 when …
> Consider all groups when reducing oil rate to group limits

- opm/simulators/linalg/bda/cuWellContributions.cu
- opm/simulators/linalg/bda/opencl/kernels/stdwell_apply.cl
- opm/simulators/linalg/bda/opencl/kernels/stdwell_apply_no_reorder.cl
Took @Tongdongq's PR #3746 and adjusted it to the new opencl kernels structure (see #3754 )
> Fix opencl apply stdwells rebased (replaces #3746)

- opm/simulators/wells/WellInterfaceFluidSystem.cpp
The main objective of this PR is to avoid the asserting on some corner cases where the well rates gives ratios that are above the limit while none of the completions does. The only case where I have seen this is when a problematic well is opened up due to well testing and starts to produce with very very small rates. Ratios between very small numbers are sensitive to numerical noise.
> Handle case where no completions have ratio above the limit while the well has

- ebos/eclproblem.hh
Dowstream of: https://github.com/OPM/opm-common/pull/2932
> Pyaction apply keywords

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2939
> Run PYACTION with Schedule::runPyAction() and call simulatorUpdate 

- ebos/eclproblem.hh
Downstream of: https://github.com/OPM/opm-common/pull/2950
> Pass ActionState to Schedule::runPyAction()

- ebos/eclgenericwriter.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- opm/simulators/timestepping/SimulatorReport.cpp
- opm/simulators/timestepping/SimulatorReport.hpp
- opm/simulators/utils/UnsupportedFlowKeywords.cpp
This commit ads: NEWTON, MLINEARS, MSUMLINS, MSUMNEWT
and no also NLINEARS, NLINSMAX and NLINSMIN
> Add more performance summary output

- ebos/eclproblem.hh
- opm/simulators/utils/UnsupportedFlowKeywords.cpp
This PR depends on https://github.com/OPM/opm-common/pull/2931
> allow for explicit initialization of SALT and SALTP

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftGroupInfo.hpp
- opm/simulators/wells/GasLiftSingleWell.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/GasLiftStage2.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWellGeneric.cpp
- opm/simulators/wells/MultisegmentWellGeneric.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
Adds gaslift optimization support for multisegmented wells (MSW).
> Adds gaslift optimization support for multisegmented wells (MSW)

- ebos/ecloutputblackoilmodule.hh
Together with https://github.com/OPM/opm-common/pull/2962
> add BTCNFHEA

- opm/simulators/wells/WellInterface_impl.hpp
This is an alternative to #3803
> Set well control to thp or bhp in well testing

- compareECLFiles.cmake
Sequential regression tests will be added later.
> Add Parallel Comparison Test for RxFy Summary Vectors

- compareECLFiles.cmake
- tests/update_reference_data.sh
This PR is adding regression testing for RXFT summary vectors
This will secure the implementation of Inter-Region Flows
https://github.com/OPM/opm-common/pull/2958
> adding regression testing of RXFT summary cases

- ebos/equil/initstateequil.hh
Fix for https://github.com/OPM/opm-simulators/issues/2029
> fix initialization EQUIL + water and gas

- opm/simulators/wells/MultisegmentWellGeneric.cpp
when initial segment rate is zero.
This PR closes https://github.com/OPM/opm-simulators/issues/3829 . 
With the original code, the oil and water rate will be zeros after scaled because the `perforation_rates` entering `calculateSegmentRates` only have the gas rate and zero water and oil rates. 
With this PR, it will make sure the top segment rates will be same (approximately) with the well rates after scaled from zero rates.
> fixing the scaling of segment rates

- opm/simulators/wells/StandardWell_impl.hpp
This fixes a particular issue exposed while running a field model.
> Handle case where bhp target is violated

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
Avoid singular matrix when initialized with zero rates.
> improve initialization msw new wells

- opm/simulators/wells/StandardWell_impl.hpp
It is from the discussion in https://github.com/OPM/opm-simulators/pull/3853 . 
The version in this  PR is slightly easier to read and saves some unnecessary calculations.
It should not change the running results in any manner.
> reconstructing the if structure for has_energy in function StandardWell<TypeTag>::calculateSinglePerf()

- opm/simulators/wells/WellInterfaceFluidSystem.cpp
Since default is NO for WVFPEXP item 4 this fixes unexpected behavior in Flow that was introduced in https://github.com/OPM/opm-simulators/pull/3824
> support item 4 wvfpexp

- ebos/equil/initstateequil.hh
Discovered when investigating unexpected test failures in https://github.com/OPM/opm-material/pull/498
> fix density in initialization for case without DISGAS

- ebos/equil/initstateequil.hh
> [backport] fix density in initialization for case without DISGAS

- ebos/eclproblem.hh
Following up from OPM/opm-material#502
> fix saturated density in DRSDTCON

- tests/test_cusparseSolver.cpp
- tests/test_openclSolver.cpp
> [backport] Fix GPU tests, use Dune as reference instead of hardcoded

- ebos/eclproblem.hh
> [backport] fix saturated density in DRSDTCON

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
> [backport] Fix STOP in combination with inoperable/unsolvable

- compareECLFiles.cmake
> [backport] changed: also run the parallel onephase tests through flow binary

- opm/simulators/wells/SingleWellState.cpp
> [backport] fixed: add missing config.h include

- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellEval.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
this should be a fallout during the well code refactoring, and the PR should not change any running results.
> renaming function updateWellState to updatePrimaryVariablesNewton . 

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
Output field values of PCOW, PCOG with RPTRST
> output pcow, pcog

- ebos/ecloutputblackoilmodule.hh
Comparison with commercial simulator for SPE1 case:
> add Block Pore Volumes

- opm/core/props/satfunc/RelpermDiagnostics.cpp
Allow keywords SWOF/SGOF to be replaced by LET-based saturation functions. 
This PR depends on https://github.com/OPM/opm-common/pull/2917
> Support for LET-based saturation functions.

- ebos/ecloutputblackoilmodule.hh
This PR calculates the various BxIP* summary output values such as `BOIP` (block-level oil-in-place) and `BGIPL` (block-level gas-in-place in liquid phase).  While here, also extract the block-level dissolved gas-oil-ratio (`BRS`) and vaporised oil-gas-ratio (`BRV`).
> Extract Block-Level Component-in-Place Summary Values

- ebos/eclgenericoutputblackoilmodule.cc
> Fix FOE definition

- opm/simulators/flow/BlackoilModelParametersEbos.hpp
> change default reg factor for MSW to 100

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterface_impl.hpp
See issue https://github.com/OPM/opm-simulators/issues/3850
Depends on https://github.com/OPM/opm-common/pull/2999
Needs more testing and the MSW part is missing.
> WIP implement rsrv item 10 WCONINJE

- opm/simulators/linalg/MatrixMarketSpecializations.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Closes https://github.com/OPM/opm-simulators/issues/3947
> fixed: fix build with dune 2.6

- opm/simulators/linalg/bda/opencl/BILU0.cpp
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply1.cl
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply1_fm.cl
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply2.cl
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply2_fm.cl
- opm/simulators/linalg/bda/opencl/openclKernels.cpp
- opm/simulators/linalg/bda/opencl/openclKernels.hpp
Reverts OPM/opm-simulators#3953
Does not compile on the CI system.
> Revert "Tweak opencl launch params"

- tests/test_relpermdiagnostics.cpp
- tests/test_stoppedwells.cpp
- tests/test_wellstate.cpp
Downstream of https://github.com/OPM/opm-common/pull/3082
> add some missing EclipseState includes

- ebos/eclgenericvanguard.cc
Disclosed by removing include from header in https://github.com/OPM/opm-common/pull/3085
> add missing include

- ebos/eclnewtonmethod.hh
- opm/simulators/linalg/bda/BdaBridge.cpp
- opm/simulators/linalg/bda/FPGASolverBackend.cpp
- opm/simulators/linalg/bda/amgclSolverBackend.cpp
Downstream of https://github.com/OPM/opm-material/pull/522
> remove use of Unused.hpp

- opm/simulators/linalg/bda/opencl/BILU0.cpp
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply1.cl
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply1_fm.cl
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply2.cl
- opm/simulators/linalg/bda/opencl/kernels/ILU_apply2_fm.cl
- opm/simulators/linalg/bda/opencl/openclKernels.cpp
- opm/simulators/linalg/bda/opencl/openclKernels.hpp
Same as https://github.com/OPM/opm-simulators/pull/3953, but without the compile error.
Also reduced the length of some more lines.
> Tweak opencl launch params v2

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/eclgenericproblem.cc
- ebos/eclgenericproblem.hh
- ebos/ecloutputblackoilmodule.hh
Note you will need to set --enable-opm-rst-file=true to get the output
Depens on https://github.com/OPM/opm-common/pull/3080
> output drsdtcon values to restart files

- compareECLFiles.cmake
- tests/update_reference_data.sh
To keep this feature working as intended.
> Add Regression Test for WPIMULT in ACTIONX Block

- ebos/eclgenericproblem.cc
- ebos/eclgenericproblem.hh
- ebos/eclproblem.hh
Less is more, even when less is very little.
> changed: move two more methods to generic problem class

- CMakeLists_files.cmake
- ebos/eclactionhandler.cc
- ebos/eclactionhandler.hh
- ebos/eclproblem.hh
Continuing https://github.com/OPM/opm-simulators/pull/3996 as github got confused by me accidentially pushing the wrong branch into the PR branch.
> Move action handling from eclproblem to separate class

- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/equil/equilibrationhelpers.cc
Downstream of https://github.com/OPM/opm-material/pull/529
> changed: consistently use std::array

- compareECLFiles.cmake
- ebos/eclproblem.hh
Depends on https://github.com/OPM/opm-models/pull/699
> Adapt drift compensation code to the way Flow checks convergence. 

- CMakeLists_files.cmake
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/countGlobalCells.cpp
- opm/simulators/flow/countGlobalCells.hpp
- opm/simulators/linalg/ParallelIstlInformation.cpp
- opm/simulators/linalg/ParallelIstlInformation.hpp
- opm/simulators/wells/RateConverter.hpp
- opm/simulators/wells/RegionAttributeHelpers.hpp
- opm/simulators/wells/RegionAverageCalculator.hpp
In itself this has not much value as such but it is part of a bigger unraveling.
> changed: put ParallelIstlInformation in separate compile unit

- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
Trivial, will self-merge if green.
> Add override qualifier to silence warning.

- ebos/eclactionhandler.cc
Use libfmt's ability for format `std::tm` objects to output unambiguous dates.  While here, also apply 'const' to a number of objects and scalar parameters.
```
The action ACT-01 evaluated to true at 2018/11/02  report:0.
```
```
Action ACT-01 triggered at 02-Nov-2018 00:00:00 (report interval 0 to 1).
```
> Format Action Dates With Libfmt

- opm/simulators/linalg/MILU.cpp
- opm/simulators/linalg/MILU.hpp
- opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
Change from Functor class to functions.
Change white-spaces.
> Code modernization

- opm/simulators/wells/BlackoilWellModel_impl.hpp
one less network latency cost. This is my obligatory summit PR submital.
> avoid two communication calls

- ebos/eclmpiserializer.hh
Replace the two hardcoded variant handlers with one generic implementation.
> added: generalize variant serialization handling

- CMakeLists_files.cmake
- opm/simulators/wells/WellHelpers.cpp
- opm/simulators/wells/WellHelpers.hpp
- tests/test_equil.cc
Every little drop..
Also some unused code removal (optional, I can remove that commit but it is currently unused) plus some cleanup.
> Make WellHelpers templates private

- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
> Make one more template private in WellGroupHelper

- opm/simulators/wells/WellGroupHelpers.cpp
This needs more testing so I will make it a draft.
> Simplify and fix check for violation of GRUP for multiple level of guiderates

- ebos/eclmpiserializer.hh
use has_serializeOp trait
There is going to be a series of these PR's coming. I want to go slow to make sure I don't introduce bugs.
> eclmpiserializer: improve pair handling

- ebos/eclmpiserializer.hh
> eclmpiserializer: improve ptr handler

- tests/test_ParallelRestart.cpp
to better reflect reason for needing two macros
> changed: rename macro

- ebos/eclmpiserializer.hh
> eclmpiserializer: improve array handler

- ebos/eclmpiserializer.hh
Sits on top of https://github.com/OPM/opm-simulators/pull/4052
> eclmpiserializer: improve set handler

- ebos/eclmpiserializer.hh
Sits on top of https://github.com/OPM/opm-simulators/pull/4052
> eclmpiserializer: improve map handler

- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/3126
> added: RestartKey mpiserializer test

- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/3127
> added: data::Solution mpiserializer test

- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/3128
> added: data::Rates mpiserializer test

- tests/test_ParallelRestart.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4066
Downstream of https://github.com/OPM/opm-common/pull/3129
> add data::Connection mpiserializer test

- tests/test_ParallelRestart.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4068
Sits on top of https://github.com/OPM/opm-simulators/pull/4066
Downstream of https://github.com/OPM/opm-common/pull/3131
> add data::Segment mpiserializer test

- tests/test_ParallelRestart.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4069
Downstream of https://github.com/OPM/opm-common/pull/3133
> added: data::Well mpiserializer test

- tests/test_ParallelRestart.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4074
Sits on top of https://github.com/OPM/opm-simulators/pull/4075
Sits on top of https://github.com/OPM/opm-simulators/pull/4076
Downstream of https://github.com/OPM/opm-common/pull/3138
> add data::AquiferData mpiserializer test

- tests/test_ParallelRestart.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4072
Downstream of https://github.com/OPM/opm-common/pull/3134
> add data::Wells mpiserializer test

- tests/test_ParallelRestart.cpp
Downstream of https://github.com/OPM/opm-common/pull/3139
> added: RestartValue mpiserializer test

- opm/simulators/utils/ParallelRestart.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4079
And now we can finally do this.
> ParallelRestart: use eclmpiserializer

- ebos/eclgenericwriter.cc
- ebos/eclmpiserializer.hh
Downstream of https://github.com/OPM/opm-common/pull/3141
> changed: use EclMpiSerializer in eclwriter

- opm/simulators/utils/ParallelEclipseState.hpp
- opm/simulators/utils/PropsCentroidsDataHandle.hpp
Downstream of https://github.com/OPM/opm-common/pull/3143
> changed: use EclMpiSerializer to distribute transmissibilities

- opm/simulators/utils/ParallelEclipseState.cpp
- opm/simulators/utils/ParallelEclipseState.hpp
- tests/test_ParallelRestart.cpp
Also includes a serialization test for TranCalculator.
Downstream of https://github.com/OPM/opm-common/pull/3144
> Remove unused serialization code

- examples/printvfp.cpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/VFPHelpers.cpp
- opm/simulators/wells/VFPHelpers.hpp
- opm/simulators/wells/VFPProdProperties.cpp
- opm/simulators/wells/VFPProdProperties.hpp
- opm/simulators/wells/VFPProperties.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterfaceEval.cpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_vfpproperties.cpp
I will mark this draft since it needs more testing.
> Add option for explicit vfp lookup for problematic wells

- opm/simulators/aquifers/AquiferAnalytical.hpp
- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
Depends on https://github.com/OPM/opm-common/pull/3109
> fix analytical aquifers + energy

- ebos/eclmpiserializer.hh
- opm/simulators/utils/MPIPacker.cpp
- opm/simulators/utils/MPIPacker.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4090
> changed: handle all arrays in eclmpiserializer

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
- opm/simulators/utils/UnsupportedFlowKeywords.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
See comments in https://github.com/OPM/opm-simulators/pull/3837#issuecomment-1244946871
> remove WVFPEXP from unsupported keywords

- ebos/eclmpiserializer.hh
- opm/simulators/utils/MPIPacker.cpp
- opm/simulators/utils/MPIPacker.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4092
> changed: handle all sets in eclmpiserializer 

- opm/simulators/utils/MPIPacker.cpp
- opm/simulators/utils/MPIPacker.hpp
thus we can remove support in MPIPacker
> changed: handle all pairs in eclmpiserializer

- ebos/eclmpiserializer.hh
- opm/simulators/utils/MPIPacker.cpp
- opm/simulators/utils/MPIPacker.hpp
thus we can remove support in MPIPacker
> changed: handle tuples in eclmpiserializer

- opm/simulators/utils/MPIPacker.cpp
ref https://github.com/OPM/opm-common/pull/3149
> simplify and fix MPI packing for strings

- ebos/eclbasevanguard.hh
- opm/simulators/utils/SetupZoltanParams.cpp
Addressing post-merge review comments.
> ZoltanParams: some cleanup

- ebos/eclproblem.hh
Background: This PR is trying to fix the build test problem in https://github.com/OPM/opm-models/pull/714 that was discovered after it was merged into master.
Moves the `updateRelperms()` method in `BlackOilIntensiveQuantities` in `opm-models` to the `EclProblem` class and its parent `MultiPhaseBaseProblem`. This is a more natural place for this method and it avoids having to include `EclMaterialManager` into the `BlackOilIntensiveQuantities` file.
See also the companion PR https://github.com/OPM/opm-models/pull/727 in opm-models
> Move updateRelperms() to the problem class

- ebos/eclbaseaquifermodel.hh
- ebos/equil/initstateequil.cc
- flow/flow_blackoil_alugrid.cpp
Added instantiation to initstateequil.cc and correct invocation of AquiferModel, both needed for flow_alugrid
> some fixes for flow_alugrid

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
Preparation for getting #4094 in.
> avoid oscilation between ORAT and LRAT when they are equal

- opm/simulators/wells/VFPHelpers.cpp
- tests/test_glift1.cpp
> remove cutoff for extrapolation

- tests/test_ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3166
> adjust to renaming of serializeObject

- compareECLFiles.cmake
- tests/update_reference_data.sh
Simulation results are verified and checked.
> add regression test for model WVFPEXT-02

- opm/simulators/utils/VectorVectorDataHandle.hpp
and mark parameter maybe_unused
> fixed: add missing includes

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
Allow some additional input from kw EHYSTR
> Killough hysteresis now supported.

- compareECLFiles.cmake
- tests/update_reference_data.sh
Feature has been merged into master and simulation results have been verify. Hence we are ready to start regression testing on this model,
> start regression testing for SPE1CASE2_KRNUM

- ebos/collecttoiorank.cc
- ebos/eclbasevanguard.hh
- ebos/eclgenericthresholdpressure.cc
- ebos/eclgenerictracermodel.cc
- ebos/eclgenericwriter.cc
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclthresholdpressure.hh
- ebos/ecltracermodel.hh
- ebos/ecltransmissibility.cc
- ebos/eclwriter.hh
- opm/simulators/aquifers/AquiferAnalytical.hpp
- opm/simulators/aquifers/AquiferNumerical.hpp
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/linalg/findOverlapRowsAndColumns.hpp
- opm/simulators/linalg/getQuasiImpesWeights.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/RateConverter.hpp
- opm/simulators/wells/RegionAverageCalculator.hpp
> Use range generators for grid iterations

- ebos/eclwriter.hh
Identified in discussion in #4121
> Do not call assignToSolution() and throw away the result.

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
An improved version of #4145. Now it is more robust in terms of the initial rates.
> Improve convergence for newly opened wells with thp control

- ebos/eclgenerictracermodel.cc
- ebos/eclgenerictracermodel.hh
- ebos/ecltracermodel.hh
This is a continuation of https://github.com/OPM/opm-simulators/pull/4147
As I could not find a model with multiple phase tracers, I butchered SPE10-MOD01-01
```diff
--- SPE10-MOD01-01.DATA 2022-10-05 15:07:11.130820964 +0200
+++ SPE10-MOD01-01-TRACERS.DATA 2022-10-07 11:17:36.771923832 +0200
@@ -120,6 +120,10 @@
--
--       SWITCH ON THE UNIFIED INPUT FILES OPTION
--
+
+TRACERS
+  2 2 2 /
+
UNIFIN                                                                          
--
--       SWITCH ON THE UNIFIED OUTPUT FILES OPTION
@@ -347,6 +351,12 @@
ROCK                                                                                    
6000      1.0E-06                                 / TAKEN FROM MODEL 2
+TRACER
+ WT1  WAT 'g' /
+ WT2  OIL 'g' /
+ WT3  GAS 'g' /
+/
+
-- …
```
> Optimize tracer assembly

- ebos/eclproblem.hh
Pack all BC data in a single struct, instead of having 6 (12) separate vector members.
Cleaner organization imo.
> Make related BC data a single class member

- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/timestepping/ConvergenceReport.hpp
- opm/simulators/timestepping/SimulatorReport.cpp
- opm/simulators/timestepping/SimulatorReport.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_glift1.cpp
This PR checks the well/group controls in the convergence check. Only accept solutions if the controls are not violated. 
Needs more testing....
> Check control

- ebos/eclproblem.hh
- regressionTests.cmake
- tests/update_reference_data.sh
This is downstream of OPM/opm-models#748
> Fix case with MULTFLT in SCHEDULE for the TpfaLinearizer ("fast assembly" path)

- parallelTests.cmake
while it causes no harm, it's still wrong
> fixed: some duplicate test case names

- CMakeLists_files.cmake
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModelRestart.cpp
- opm/simulators/wells/BlackoilWellModelRestart.hpp
> Add class for handling restart initialization in BlackoilWellModel

- CMakeLists_files.cmake
- opm/simulators/wells/BlackoilWellModelConstraints.cpp
- opm/simulators/wells/BlackoilWellModelConstraints.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
> Add class for BlackoilWellModel constraints

- CMakeLists_files.cmake
- opm/simulators/wells/WellGroupControls.cpp
- opm/simulators/wells/WellGroupControls.hpp
- opm/simulators/wells/WellInterfaceEval.cpp
- opm/simulators/wells/WellInterfaceEval.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
> Add class for well group controls

- CMakeLists_files.cmake
- opm/simulators/wells/WellGroupConstraints.cpp
- opm/simulators/wells/WellGroupConstraints.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.hpp
> Add class for well group constraints

- CMakeLists_files.cmake
- opm/simulators/wells/WellConstraints.cpp
- opm/simulators/wells/WellConstraints.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterfaceFluidSystem.hpp
> Add class for well constraints

- opm/simulators/flow/NonlinearSolverEbos.hpp
This one was a little tricky because I had to skip the last commit, cherry-picked the other three manually.
> Backport of pr 4185

- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterface_impl.hpp
no typetag dependence. also no need for this to be virtual
> changed: move isPressureControlled to WellInterfaceGeneric

- opm/simulators/wells/MultisegmentWell_impl.hpp
there should be no change in the results at all.
> fixing some typos in MultisegmentWell_impl.hpp

- ebos/eclproblem.hh
Depends on OPM/opm-common#3135 and OPM/opm-models#739
> implement dirichlet boundary conditions

- CMakeLists.txt
- ebos/eclalugridvanguard.hh
- ebos/eclgenericwriter.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/ecltransmissibility.hh
- opm/simulators/aquifers/BlackoilAquiferModel.hpp
- opm/simulators/linalg/ISTLSolverEbos.cpp
To enable https://github.com/OPM/opm-common/pull/3219
> ISTLSolverEbos: instance for ALUGrid

- opm/simulators/wells/StandardWell_impl.hpp
Reverts OPM/opm-simulators#4262
> Revert "remove derivative in thermal flux for injectors"

- opm/simulators/wells/StandardWell_impl.hpp
- parallelTests.cmake
Try to re-apply https://github.com/OPM/opm-simulators/pull/4262
> remove derivative in thermal flux for injectors

- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/SegmentState.cpp
- opm/simulators/wells/SegmentState.hpp
- opm/simulators/wells/WellState.cpp
This enables calculating the `SOFRF` and `SGFRF` summary vectors.
> Report Solution GOR and OGR at Segment Level

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellBhpThpCalculator.cpp
- opm/simulators/wells/WellBhpThpCalculator.hpp
we need to call WellInterface::getTHPConstraint,
not WellBhpThpCalculator::getTHPConstraint
> fix regression in wells

- ebos/eclproblem.hh
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/wells/MultisegmentWellEval.hpp
> adapt to primary variable refactoring

- opm/simulators/wells/MSWellHelpers.cpp
- opm/simulators/wells/MSWellHelpers.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
this way the matrix type and be deduced from passed parameters
> MSWellHelpers: reverse order of template parameters

- opm/simulators/wells/WellState.cpp
Thanks @bska for the help. It caused a lot of confusion during the development of the keyword WINJMULT. 
@bska , I am pretty shallow when coming to this part of the code, if you have different ideas on how it should be done, go head to come up with a different suggestion.
> using correct CPI indices for connections in WellState::reportConnections()

- CMakeLists_files.cmake
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MSWellHelpers.cpp
- opm/simulators/wells/MSWellHelpers.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWellEquations.cpp
- opm/simulators/wells/MultisegmentWellEquations.hpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellEval.hpp
- opm/simulators/wells/MultisegmentWellGeneric.cpp
- opm/simulators/wells/MultisegmentWellGeneric.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
This adds a separate class for the msw equation system similar to stw.
As in the earlier work, all member variables are still public, will be taken care of later.
> Added: MultisegmentWellEquations

- opm/simulators/flow/BlackoilModelEbos.hpp
This is in preparation of enabling separate convergence output for diagnostic purposes.
> Capture Component Names in Independent Datastructure

- opm/simulators/wells/MSWellHelpers.cpp
- opm/simulators/wells/MSWellHelpers.hpp
it removes some singularity warning from UMFPack.
> rewrting frictionPressureLoss fucntion for better jacobian matrix

- dune.module
- jenkins/build.sh
- opm-simulators-prereqs.cmake
remove opm-material from upstreams / dependencies
Downstream of https://github.com/OPM/opm-common/pull/3234
> adjust jenkins script and buildsystem

- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/timestepping/ConvergenceReport.hpp
- opm/simulators/timestepping/gatherConvergenceReport.cpp
This enables outputting a formatted record of the limiting MB and CNV quantities as time and non-linear iterations progress.  This, in turn, is intended for diagnostic and analysis purposes and will not be output unless specifically requested.
In particular, add a new type,
```
ConvergenceReport::ReservoirConvergenceMetric
```
which captures the convergence metric type (MB or CNV) along with the associate phase and numerical value of the convergence metric. We add a vector of these convergence metric objects as a new data member of the `ConvergenceReport`.
Finally, foreshadowing the intended use case, also store the report time in the `ConvergenceReport` object.
> Capture Timestep's Non-Linear Convergence History

- opm/core/props/satfunc/RelpermDiagnostics.hpp
adjust to upstream header-in-header removals
Downstream of https://github.com/OPM/opm-common/pull/3243
> RelpermDiagnostics: add more forwards

- tests/test_equil.cc
Downstream of https://github.com/OPM/opm-common/pull/3252
> Adjust to upstream enum entry changes

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellEval.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
> MultisegmentWell: avoid mutable primary variables

- opm/simulators/wells/RateConverter.hpp
Noticed while working on #4292
> clamp rs/rv in rate converter between 0.0 and rs/rv max

- CMakeLists.txt
- ebos/eclequilinitializer.hh
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/equil/initstateequil.cc
- flow/flow_ebos_gaswater_dissolution.cpp
- flow/flow_ebos_gaswater_dissolution.hpp
- flow/flow_ebos_gaswater_dissolution_diffuse.cpp
- flow/flow_ebos_gaswater_dissolution_diffuse.hpp
- flow/flow_gaswater_dissolution.cpp
- flow/flow_gaswater_dissolution_diffuse.cpp
- opm/simulators/aquifers/AquiferAnalytical.hpp
- opm/simulators/aquifers/AquiferInterface.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp
- opm/simulators/wells/MultisegmentWellSegments.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/RateConverter.hpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellConnections.cpp
- opm/simulators/wells/StandardWellConnections.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellState.cpp
https://github.com/OPM/opm-material/pull/543
> Add support for gas in water

- opm/simulators/wells/MSWellHelpers.cpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellAssemble.cpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWellEval.hpp
- opm/simulators/wells/StandardWellPrimaryVariables.hpp
- opm/simulators/wells/VFPHelpers.cpp
Downstream of https://github.com/OPM/opm-common/pull/3305
> Evaluation cleanups

- opm/simulators/flow/NonlinearSolverEbos.hpp
- opm/simulators/linalg/FlexibleSolver_impl.hpp
- opm/simulators/linalg/ISTLSolverEbos.cpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/MILU.cpp
- opm/simulators/linalg/OwningTwoLevelPreconditioner.hpp
- opm/simulators/linalg/PreconditionerFactory_impl.hpp
- opm/simulators/linalg/bda/WellContributions.cpp
- opm/simulators/linalg/bda/opencl/BILU0.cpp
- opm/simulators/linalg/bda/opencl/BISAI.cpp
- opm/simulators/linalg/setupPropertyTree.cpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- opm/simulators/timestepping/TimeStepControl.cpp
- opm/simulators/utils/SetupZoltanParams.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/VFPHelpers.cpp
- opm/simulators/wells/WellState.cpp
- tests/test_milu.cpp
- tests/test_wellstate.cpp
Preparatory work for removing sstream usage in OPM_THROW.
>  Remove sstream use in exception handling

- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/linalg/bda/opencl/BISAI.cpp
- opm/simulators/timestepping/AdaptiveSimulatorTimer.hpp
- tests/test_csrToCscOffsetMap.cpp
> Trim some iostream includes

- ebos/ecltransmissibility.cc
Downstream of https://github.com/OPM/opm-common/pull/3318
> adjust to PinchMode now being an enum class

- opm/simulators/utils/ParallelSerialization.cpp
- tests/test_ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3324
> add missing GuideRateConfig.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftGroupInfo.hpp
- opm/simulators/wells/GasLiftSingleWell.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- tests/test_ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3323
> GasLiftOpt.hpp: minimize include

- ebos/eclactionhandler.cc
Downstream of https://github.com/OPM/opm-common/pull/3327
> add missing SimulatorUpdate.hpp include

- ebos/eclactionhandler.cc
- ebos/eclactionhandler.hh
- ebos/eclgenericwriter.cc
- ebos/eclproblem.hh
And move some code to compile unit to avoid including WellMatcher.hpp in eclproblem.hh.
Downstream of https://github.com/OPM/opm-common/pull/3328
> Add missing WellMatcher.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
- tests/test_ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3329
> add missing NameOrder.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- tests/test_ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3332
> add missing GConSump.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/WellGroupControls.cpp
Downstream of https://github.com/OPM/opm-common/pull/3333
> add missing GConSale.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/WellGroupHelpers.cpp
- tests/test_ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3335
> add missing ExtNetwork.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_ParallelSerialization.cpp
And move more code to compile unit to avoid including Balance.hpp in BlackoilWellModel_impl.hpp
Downstream of https://github.com/OPM/opm-common/pull/3337
> add missing Balance.hpp includes

- ebos/eclactionhandler.cc
- opm/simulators/utils/ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3339
> add missing Actions.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3340
> add missing UDQActive.hpp include

- ebos/eclactionhandler.cc
- ebos/eclgenericwriter.cc
- opm/simulators/utils/readDeck.cpp
Downstream of https://github.com/OPM/opm-common/pull/3341
> add missing UDQConfig.hpp includes

- CMakeLists_files.cmake
- ebos/eclgenericoutputblackoilmodule.cc
- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWellSegments.cpp
- opm/simulators/wells/ParallelWellInfo.cpp
- opm/simulators/wells/WellConnectionAuxiliaryModule.cpp
- opm/simulators/wells/WellConnectionAuxiliaryModule.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellTest.cpp
- tests/test_ParallelSerialization.cpp
- tests/test_wellmodel.cpp
- tests/test_wellstate.cpp
Downstream of https://github.com/OPM/opm-common/pull/3343
> Avoid WellConnections.hpp in simulator objects

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterface_impl.hpp
Downstream of https://github.com/OPM/opm-common/pull/3347
> add missing WellFoamProperties.hpp includes

- CMakeLists_files.cmake
- ebos/eclequilinitializer.hh
- ebos/equil/initstateequil.cc
- ebos/equil/initstateequil.hh
- tests/equil_co2store_go.DATA
- tests/equil_co2store_gw.DATA
- tests/test_equil.cc
Seems like most of the work was already done. @bska Did I miss something? Only tested on a simple case without capillary pressure. So definitely it needs more testing.
> Suppot EQUIL + WATER + GAS

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3348
> add missing WellBrineProperties.hpp includes

- ebos/eclgenerictracermodel.cc
- ebos/eclgenerictracermodel.hh
- ebos/ecltracermodel.hh
- opm/simulators/utils/ParallelSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3350
> add missing WellTracerProperties.hpp includes

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
> output gas pressure for gas-water case

- opm/simulators/utils/ParallelEclipseState.cpp
- opm/simulators/utils/PropsCentroidsDataHandle.hpp
- opm/simulators/utils/readDeck.cpp
Required by https://github.com/OPM/opm-common/pull/3361
> add missing FieldData.hpp includes

- ebos/eclgenericvanguard.cc
- opm/simulators/flow/Main.hpp
- opm/simulators/utils/readDeck.cpp
- opm/simulators/utils/readDeck.hpp
- tests/test_norne_pvt.cpp
Downstream of https://github.com/OPM/opm-common/pull/3365
> add missing InputErrorAction.hpp includes

- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellTest.cpp
Required by https://github.com/OPM/opm-common/pull/3366
> add missing WellTestConfig.hpp includes

- ebos/eclactionhandler.cc
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericvanguard.cc
- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/wells/BlackoilWellModelRestart.cpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/GlobalWellInfo.cpp
- opm/simulators/wells/GlobalWellInfo.hpp
- opm/simulators/wells/MultisegmentWellEval.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/WellAssemble.hpp
- opm/simulators/wells/WellConnectionAuxiliaryModule.cpp
- opm/simulators/wells/WellConstraints.cpp
- opm/simulators/wells/WellConstraints.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_stoppedwells.cpp
- tests/test_wellstate.cpp
Downstream of https://github.com/OPM/opm-common/pull/3371
> Clean up Well.hpp includes

- ebos/eclgenericoutputblackoilmodule.hh
- opm/simulators/wells/GasLiftGroupInfo.hpp
- tests/test_ParallelSerialization.cpp
Required by https://github.com/OPM/opm-common/pull/3372
> SummaryState.hpp: add missing and forward where possible

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
- tests/test_equil.cc
- tests/test_glift1.cpp
Reduce hotness of SummaryConfig.hpp by 49% (31 files, 32 files instead of 63)
> Cleanup SummaryConfig.hpp includes and forward

- opm/simulators/flow/Main.cpp
- opm/simulators/flow/Main.hpp
Regression from https://github.com/OPM/opm-simulators/pull/4396
I think this should be fine, @bska
> fix Damaris setup in Main

- ebos/eclgenerictracermodel.cc
- ebos/eclgenerictracermodel.hh
- tests/test_equil.cc
and remove some unneeded ones
Required by https://github.com/OPM/opm-models/pull/778
> add missing includes

- ebos/eclgenericproblem.cc
- ebos/eclgenericproblem.hh
- ebos/eclproblem.hh
See upstream https://github.com/OPM/opm-common/pull/3364 for more information
> Adds support for directional relative permeabilities with hysteresis

- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/flow/Main.cpp
- opm/simulators/flow/Main.hpp
> fixed: regression from 82d2146c90ce74677bd8f04c745c31cd08b430de

- CMakeLists_files.cmake
- opm/simulators/flow/Banners.cpp
- opm/simulators/flow/Banners.hpp
- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/flow/Main.cpp
- opm/simulators/flow/Main.hpp
Less recompile and a little bit tidier.
> changed: move banner printing to separate compile unit

- ebos/collecttoiorank.cc
- ebos/collecttoiorank.hh
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/eclgenericwriter.cc
- ebos/eclgenericwriter.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
Current implementation for compatibility with ResInsight for these two keywords. NNC flows are also written out. For now as a draft to check all tests.
> FLOWS and FLORES support

- opm/simulators/timestepping/TimeStepControl.cpp
The PID time step control will not pose any constraint on the time step size by returning a largest possible time step size.
I am not that familiar with this part, but hopefully this can be the start to fix the corner issues suggested in https://github.com/OPM/opm-simulators/issues/4341 .
> fix the running when solution does not change between time steps

- CMakeLists_files.cmake
- opm-simulators-prereqs.cmake
- opm/simulators/utils/HDF5File.cpp
- opm/simulators/utils/HDF5File.hpp
- tests/test_HDF5File.cpp
bare minimum to enable reading and writing byte arrays
> added: simple HDF5File class

- opm/simulators/wells/BlackoilWellModelConstraints.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/ParallelWellInfo.cpp
- opm/simulators/wells/ParallelWellInfo.hpp
- opm/simulators/wells/StandardWellConnections.cpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
to encapsulate some headers in compile unit. also clean up include list in the process
> ParallelWellinfo: make some more templates private

- ebos/eclgenericvanguard.cc
- ebos/eclgenericvanguard.hh
- tests/test_ParallelSerialization.cpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4419
Sits on top of https://github.com/OPM/opm-simulators/pull/4417
> EclGenericVanguard: add serialization for dynamic state

- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4420
Downstream of https://github.com/OPM/opm-models/pull/779
> BlackoilPrimaryVariables: add serialization support

- ebos/eclgenericproblem.cc
- ebos/eclgenericproblem.hh
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4422
For restart.
> EclGenericProblem: add serialization support

- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/StandardWell.hpp
> Fix a few warnings in recently added code.

- opm/simulators/aquifers/AquiferAnalytical.hpp
- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferFetkovich.hpp
- opm/simulators/aquifers/AquiferInterface.hpp
- opm/simulators/aquifers/AquiferNumerical.hpp
- opm/simulators/aquifers/BlackoilAquiferModel.hpp
- opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4425
Downstream of https://github.com/OPM/opm-common/pull/3388
> BlackoilAquiferModel: add serialization of dynamic state

- ebos/eclgenerictracermodel.hh
- ebos/ecltracermodel.hh
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4426
> EclTracerModel: add serialization of dynamic state

- opm/simulators/wells/SegmentState.cpp
- opm/simulators/wells/SegmentState.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4435
> SegmentState: add serialization support

- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4436
> SingleWellState: add serialization support

- opm/simulators/wells/GroupState.cpp
- opm/simulators/wells/GroupState.hpp
- opm/simulators/wells/WellContainer.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4437
Downstream of https://github.com/OPM/opm-common/pull/3392
> GroupState: add serialization support

- opm/simulators/wells/ALQState.cpp
- opm/simulators/wells/ALQState.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4440
> ALQState: add serialization support

- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4442
> WellState: add serialization support

- opm/simulators/wells/WGState.cpp
- opm/simulators/wells/WGState.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4443
> WGState: add serialization support

- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4445
Downstream of https://github.com/OPM/opm-common/pull/3393
> BlackOilWellModel: add serialization support

- ebos/eclproblem.hh
Sits on top of https://github.com/OPM/opm-simulators/pull/4446
> EclProblem: add serialization support

- opm/simulators/timestepping/SimulatorReport.cpp
- opm/simulators/timestepping/SimulatorReport.hpp
- tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4447
> SimulatorReport: add serialization support

- CMakeLists_files.cmake
- ebos/hdf5serializer.hh
- examples/opmrst_inspect.cpp
- opm-simulators-prereqs.cmake
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/WellState.hpp
- restartTests.cmake
- tests/run-serialization-regressionTest.sh
This finally adds the serialization based restart support to the simulators.
Sits on top of a bunch of things that should be processed before we get here but at least you can see where we are headed..
> Add serialization restart support

- CMakeLists.txt
- compareECLFiles.cmake
- ebos/hdf5serializer.hh
- examples/opmrst_inspect.cpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/utils/HDF5File.cpp
- opm/simulators/utils/HDF5File.hpp
- parallelRestartTests.cmake
- tests/run-serialization-regressionTest.sh
- tests/test_HDF5File.cpp
- tests/test_HDF5File_Parallel.cpp
- tests/test_HDF5Serializer_Parallel.cpp
This extends the restart serialization to support parallel simulations.
> RestartSerialization: add parallel support

- opm/simulators/wells/WellInterfaceGeneric.cpp
Use 0.0 as default alq for injector.
> Fix default alq injector

- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- parallelTests.cmake
- restartTests.cmake
It seems like the connection reservoir rate was never computed.
> compute CVIR and CVPR

- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
will look in both output dir and input file dir on load
> fixed: output OPMRST file to output dir

- ebos/eclproblem.hh
- tests/test_RestartSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3412
> Restart serialization: Store hysteresis params

- opm/core/props/satfunc/RelpermDiagnostics.cpp
- opm/core/props/satfunc/RelpermDiagnostics.hpp
Depends on https://github.com/OPM/opm-common/pull/3406
> GSF WSF diagnostics

- ebos/eclgenericoutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- tests/test_RestartSerialization.cpp
Downstream of https://github.com/OPM/opm-common/pull/3416
> Restart serialization: Store initial fip values

- opm/simulators/utils/HDF5File.cpp
> fixed: add missing HAVE_MPI ifs

- ebos/eclgenerictracermodel.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/OwningBlockPreconditioner.hpp
- opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
- opm/simulators/linalg/PressureBhpTransferPolicy.hpp
Slight modification of #4462 for more consistency.
> Add timing block

- CMakeLists_files.cmake
- opm/simulators/flow/FlowMainEbos.cpp
- opm/simulators/flow/FlowMainEbos.hpp
Small micro optimizations, but every little bit..
> FlowMainEbos: add a compile unit

- ebos/equil/equilibrationhelpers.cc
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/OwningBlockPreconditioner.hpp
- opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
- opm/simulators/linalg/PressureBhpTransferPolicy.hpp
Downstream of https://github.com/OPM/opm-common/pull/3418
> adjust to timing macro header split

- CMakeLists_files.cmake
- opm/simulators/flow/NonlinearSolverEbos.cpp
- opm/simulators/flow/NonlinearSolverEbos.hpp
> NonlinearsolverEbos: add compile unit

- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.cpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- opm/simulators/timestepping/ConvergenceReport.hpp
> AdaptiveTimeSteppingEbos: move more code to compile unit

- opm/simulators/aquifers/AquiferConstantFlux.hpp
- opm/simulators/flow/Banners.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
> Silence warnings: struct/class, missing override.

- ebos/eclgenericthresholdpressure.cc
- ebos/eclgenericthresholdpressure.hh
- ebos/eclthresholdpressure.hh
Downstream of https://github.com/OPM/opm-common/pull/3422
> added: log ThresholdPressures to PRT file

- opm/simulators/wells/RateConverter.hpp
Unless I'm missing something..
> RateConverter: throw an exception, not a bare string

- opm/simulators/wells/RateConverter.hpp
The main cost here is the latency of communication. Now we pay that price at most 2 times, instead of 9.
> RateConverter: coalesce global reductions

- opm/simulators/aquifers/AquiferConstantFlux.hpp
> Tag Unused Parameter as Maybe_Unused

- ebos/eclgenericwriter.cc
This is in preparation of adding actual constructors to the type.
> Switch to Using Constructor Syntax for CellData

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/ecloutputblackoilmodule.hh
Depends on https://github.com/OPM/opm-common/pull/3449
and https://github.com/OPM/opm-common/pull/3448
> convert co2 output from volumes to moles

- ebos/eclgenericoutputblackoilmodule.cc
The output is given if CO2STORE, DISGASW and `--enable-opm-rst-file=true`.
> add molar fraction of CO2 in brine to RST output

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclwriter.hh
- opm/simulators/flow/BlackoilModelEbos.hpp
* removed double evaluation of `processLocalData`
* separated fluid in place work
* removed double evaluation of `processLocalData` from other cell based data
> Optimisation of data processing for actionX and output

- opm/simulators/flow/BlackoilModelParametersEbos.hpp
it should be a type double. With int, it does not looks like it can get proper value at all.
> using double for regularization_factor_wells_

- ebos/eclproblem.hh
- faster updateProperty
- refactored for making local updating in inhereted classes
> faster begintimestep

- ebos/ecloutputblackoilmodule.hh
Only relevant for cases with that allows for dissolved gas in water
> output gas in water to F(R)GIPL for gas-water systems

- opm/simulators/aquifers/AquiferAnalytical.hpp
small change to be able to return local variable for IQ
> - changed pointer to refernace for IQ for possibility of using rvalues

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/RateConverter.cpp
- opm/simulators/wells/RateConverter.hpp
- opm/simulators/wells/WellAssemble.cpp
- opm/simulators/wells/WellGroupConstraints.cpp
- opm/simulators/wells/WellGroupConstraints.hpp
- opm/simulators/wells/WellGroupControls.cpp
- opm/simulators/wells/WellGroupControls.hpp
- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- tests/test_RestartSerialization.cpp
Issue reported by @tskille 
A similar fix may be needed for groups controlled by RESV, but lets fix the wells first.
> fix RESV for undersaturated wells

- opm/simulators/linalg/FlexibleSolver_impl.hpp
> FlexibleSolver: use std::make_shared

- ebos/eclgenericproblem.cc
- ebos/eclgenericproblem.hh
See https://github.com/OPM/opm-models/pull/795
> compute rock fraction

- ebos/eclproblem.hh
Models functions to protected. This make it possible to avoid global update of IQ with property changes, which is need for some models.
> -- changed function to protected

- ebos/eclproblem.hh
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterface.hpp
Downstream from OPM/opm-models#776, see that PR for motivation and discussion.
> Implement functionality to add well source terms to the residual separately

- dune.module
- ebos/collecttoiorank.cc
- ebos/eclgenerictracermodel_impl.hh
- ebos/eclgenericvanguard.hh
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/linalg/MatrixMarketSpecializations.hpp
- opm/simulators/linalg/ParallelOverlappingILU0.hpp
- opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
- opm/simulators/linalg/ParallelRestrictedAdditiveSchwarz.hpp
- opm/simulators/linalg/PreconditionerFactory.hpp
- opm/simulators/linalg/PreconditionerFactory_impl.hpp
- opm/simulators/linalg/PressureBhpTransferPolicy.hpp
- opm/simulators/linalg/PressureTransferPolicy.hpp
- opm/simulators/linalg/amgcpr.hh
- opm/simulators/linalg/bda/MultisegmentWellContribution.hpp
- opm/simulators/linalg/bda/WellContributions.hpp
- opm/simulators/linalg/bda/opencl/CPR.cpp
- opm/simulators/linalg/bda/opencl/CPR.hpp
- opm/simulators/utils/ParallelCommunication.hpp
- opm/simulators/wells/GasLiftGroupInfo.hpp
- opm/simulators/wells/MSWellHelpers.cpp
- tests/DuneIstlTestHelpers.hpp
- tests/test_ParallelSerialization.cpp
- tests/test_blackoil_amg.cpp
- tests/test_broadcast.cpp
- tests/test_csrToCscOffsetMap.cpp
- tests/test_gatherdeferredlogger.cpp
- tests/test_milu.cpp
- tests/test_wellmodel.cpp
Leaving as draft, should be merged close to 23.04 release.
> minimum dune version required is now 2.7

- opm/simulators/wells/WellInterfaceFluidSystem.cpp
- opm/simulators/wells/WellState.cpp
Tested on wgrupcon/02-WGRUPCON.DATA
https://github.com/OPM/opm-tests/pull/937/files
Needs some more testing before I can be merged. Will report back.
> Support WGRUPCON item 2 = no

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
> GCONPROD Item 7, only RATE is supported

- ebos/ecltransmissibility.cc
- ebos/ecltransmissibility.hh
- opm/simulators/utils/UnsupportedFlowKeywords.cpp
For the provided test case the tansmissibilities on the fault look good. Still the results are a bit different.
Needs OPM/opm-common#3459
> Support EDITNNCR keyword

- opm/simulators/aquifers/AquiferCarterTracy.hpp
This is mostly to aid readability by avoiding nested conditionals. While here, also remove redundant 'inline' and 'virtual' keywords.
> Split CO2 Store Handling Out to Helper Functions

- examples/opmrst_inspect.cpp
One stupid and one forgotten update when adding parallel support to opmrst
> opmrst_inspect: some fixes

- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.cpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
One small fix, one added check for being more explicit about what is wrong, and one extra check to avoid misunderstandings.
> Serialized restart: Add some more checks

- CMakeLists.txt
> fixed: only search for Development.Module component for python

- opm/simulators/flow/Main.hpp
See discussion in https://github.com/OPM/opm-simulators/pull/4537
> pick correct version of flow for gas-water-vapwat case

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/PerforationData.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Minor refactor, introduces a struct and passes an instance of this instead of several separate variables.
> Simplify interface for calculation perf rates

- CMakeLists.txt
- tests/test_cusparseSolver.cpp
- tests/test_openclSolver.cpp
- tests/test_rocalutionSolver.cpp
- tests/test_rocsparseSolver.cpp
Downstream of https://github.com/OPM/opm-common/pull/3514
> GPU tests: add a label and make missing device a failure

- compareECLFiles.cmake
rather than forcing parallel tests to run sequentially. no change on jenkins but allows more efficient execution if more than 4 cpus are used for test execution.
> changed: use ctest mechanism for specifying number of processors required

- restartTests.cmake
if not parallel execution of tests fail.
> fixed: need a separate directory for each restart test

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
To avoid manual duplication of code.
> changed: unify getMobility(Eval|Scalar)

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
All the test cases that were provided to me are actually already supported by current master.
> Mark PINCH option 2 NOGAP as fully supported.

- ebos/ecloutputblackoilmodule.hh
Depends on https://github.com/OPM/opm-common/pull/3517
> take into account trapped saturation from hysteresis

- flow/flow_ebos_gaswater_energy.cpp
I suggest we add it to the thermal module rather than adding yet another version with dissolution + thermal.
> enable disgasw and vapwat for thermal model

- opm/simulators/wells/StandardWellPrimaryVariables.cpp
- opm/simulators/wells/StandardWell_impl.hpp
I am debugging a case with rsw/rvw and found some suspicious code. I didn't fix my problem, but I think the fixes are correct.
> Fixes related to rsw/rvw handling in standard well

- opm/simulators/wells/WellGroupHelpers.cpp
in the old code negative gpmaint rates where calculated and then removed by a `max(0.0, rates)`, but this introduce the wrong history to gpmaint which results in wrong rates.
> dont store history of inactive gpmaint rates

- CMakeLists_files.cmake
- opm/simulators/flow/Main.cpp
- opm/simulators/linalg/cuistl/set_device.cpp
- opm/simulators/linalg/cuistl/set_device.hpp
> Setting CUDA device for MPI runs.

- regressionTests.cmake
- tests/update_reference_data.sh
OPM Flow support of keyword VAPPARS used in Solution section was achieve with pr
https://github.com/OPM/opm-common/pull/3550 
This has now been tested and simulation results are excellent and with this PRI would like to start regression testing.
> start regression testing of test case with VAPPARS keyword 

- opm/simulators/wells/StandardWellConnections.cpp
I was debugging another issue and came pass this code. It seems wrong. Why are the saturated B factors used when rs/rv etc. = 0? 
I haven't tested this much, so I will make it a draft. I don't expect it to have huge impact on the solution.
> stop using saturated b-factors for case with zero rates

- ebos/equil/initstateequil_impl.hh
This PR fixes the issue of using a wrong (`GOC`) contact depth for water evaporation (`RVW`) initialization in the special case of a two-phase gas-water system. This issue was raised in [initialize trivial rvw if no table is given #4647](https://github.com/OPM/opm-simulators/pull/4647)
> Fix water evaporation initialization for two-phase gas-water system

- tests/getprop.awk
Mostly to aid future maintainers.
> Add Brief Documentation Block to Test Property AWK Script

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
This PR is related to https://github.com/OPM/opm-common/pull/3526
> allow value NONE for item 7 of GCONPROD

- opm/simulators/linalg/FlexibleSolver.hpp
- opm/simulators/linalg/FlexibleSolver_impl.hpp
- opm/simulators/linalg/FlowLinearSolverParameters.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
These are relatively minor improvements and cleanup. Most were prompted by the work on NLDD methods, and are extracted from #3764.
> Linear solver improvements

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWellPrimaryVariables.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellPrimaryVariables.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
These can be used to manage state in the well models, and will be used in the NLDD solver option. Also added the setupDomains() method, as the getters and setters are working on a domain basis.
> Add methods for getting and setting primary variables.

- opm/simulators/wells/MultisegmentWell_impl.hpp
> Silence shadowing warning.

- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
Also revise treatment of convergence report output, since that depended on new solver object being created every report step.
> Make solver object a member of SimulatorFullyImplicitBlackoilEbos.

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
- opm/simulators/utils/UnsupportedFlowKeywords.cpp
- regressionTests.cmake
- tests/test_RestartSerialization.cpp
This PR replaces. https://github.com/OPM/opm-simulators/pull/4583
Depends on https://github.com/OPM/opm-common/pull/3542
> Wag hysteresis

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_glift1.cpp
Also, remove uneeded function updatePerforationIntensiveQuantities(), and do a slight refactoring of the linearize() function. These are the only two changes that could interfere with existing code, I think.
> Well additions for local solves.

- regressionTests.cmake
Support of MULTFLT both in GRID and EDIT section was implemented correctly with 
https://github.com/OPM/opm-common/pull/3556
Simulation results has been verified today and they are good. Hence, I would like to start regression testing with this model.
> start regression testing of MULTFLT-01

- ebos/eclcpgridvanguard.hh
- ebos/eclgenericcpgridvanguard.cc
- opm/simulators/utils/readDeck.cpp
Add  timing blocks for deck reading, state creation, state broadcasting, grid creation, grid distribution.
> add some timing blocks

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
Just some trivial refactoring moving more code to compile unit.
> BlackoilWellModel: move some more code to generic class

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
To avoid manual duplication of code.
> changed: unify computePerfRate(Eval|Scalar)

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
to share implementation between STW and MSW
> move updateWellStateWithTHPTargetProd to WellInterface

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
now code is shared between StandardWell and MultisegmentWell
> introduce WellInterfaceGeneric::computeWellPotentials and checkNegativeWellPotentials

- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Split into separate methods to increase readability of calculateSinglePerf.
Last commit needs https://github.com/OPM/opm-common/pull/3507
> Refactor connection rate calculations

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Split into separate methods to increase readability of calculatePerfRate
Needs https://github.com/OPM/opm-common/pull/3507
> Refactor perforation rate calculations

- ebos/eclproblem.hh
Depends on https://github.com/OPM/opm-common/pull/3482
> add support for changing boundary conditions

- opm/simulators/wells/WellBhpThpCalculator.cpp
> Silence unused capture warning.

- CMakeLists_files.cmake
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/utils/ComponentName.cpp
- opm/simulators/utils/ComponentName.hpp
> ComponentName: put in separate file

- opm/simulators/utils/readDeck.cpp
We now give a different (more explanatory) error if the input grid has no active cells at all. Often this points to a user error and having a more precise error message might help here.
> Improve error message for input grid without any active cells.

- regressionTests.cmake
Case https://github.com/OPM/opm-tests/pull/988
> add gas condensate case to regression test

- opm/simulators/flow/BlackoilModelEbos.hpp
Separate out code shared by newton and nldd into separate methods.
> BlackoilModeEbos: Reduce some code duplication

- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/BlackoilModelParametersEbos.hpp
- opm/simulators/flow/SubDomain.hpp
Put in separate method and add command line parameter to choose between pressure and residual.
> BlackoilModelEbos: improve domain ordering

- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/BlackoilModelParametersEbos.hpp
- opm/simulators/flow/SubDomain.hpp
Separate out some more code into separate methods to improve higher-level readability.
Add enumeration of solver approach, and command line validation. In particular we get rid of an assert
on user provided data.
Sits on top of https://github.com/OPM/opm-simulators/pull/4738
> BlackoilModelEbos: improve nldd solver approach

- CMakeLists.txt
- CMakeLists_files.cmake
- compareECLFiles.cmake
- tests/run-test.sh
add a post command to the runSimulator script and use this to execute the unit test at the end of the run
> simplify cmake code for tuning tests

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
Just improving the English wording since this is user facing message.
> Improve message when shutting well due to convergence issues

- opm/simulators/linalg/ISTLSolverEbos.hpp
> ISTLSolverEbos: add missing include

- CMakeLists_files.cmake
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/BlackoilModelEbosNldd.hpp
> BlackoilModelEbos: separate out NLDD code to separate class

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
- opm/simulators/wells/BlackoilWellModelConstraints.cpp
- opm/simulators/wells/BlackoilWellModelConstraints.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
This PR depends on https://github.com/OPM/opm-common/pull/3601
> Enable items, 11, 12 and 13 of GCONPROD

- opm/simulators/linalg/ISTLSolverEbos.cpp
This is only done when the linear solver is create()d, so it will not flood the debug file. The info gets dumped in between convergence information lines though, so a little polish would be good (suggestions welcome on where to stick this small piece of code). It looks like this (from running SPE9 with 8 ranks):
```
Report step  0/90 at day 0/900, date = 01-Jan-2015
Using Newton nonlinear solver.
Starting time step 0, stepsize 1 days, at day 0/10, date = 01-Jan-2015
Switching control mode for well INJE1 from RATE to BHP on rank 6
Iter    MB(O)      MB(W)      MB(G)      CNV(O)     CNV(W)     CNV(G) 
0  9.140e-05  1.018e-05  6.955e-05  6.543e-02  2.815e-02  4.979e-02
Linear system rank: 0 blocksize: 3 size:    1573 nonzeroes:      9783
Linear system rank: 1 blocksize: 3 size:    1854 …
```
> Add output of linear system sizes to DBG file.

- opm/simulators/linalg/ISTLSolverEbos.cpp
Trying to fix the regression caused by #4734
> Add code path for the no-MPI case.

- opm/simulators/flow/FlowMainEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
> Rename LinearTimeSteppingBreakdown to TimeSteppingBreakdown.

- opm/simulators/linalg/FlexibleSolver_impl.hpp
- opm/simulators/linalg/ISTLSolverEbos.cpp
- opm/simulators/linalg/MILU.cpp
- opm/simulators/linalg/ParallelOverlappingILU0.hpp
- opm/simulators/linalg/ParallelRestrictedAdditiveSchwarz.hpp
- opm/simulators/linalg/PreconditionerFactory.hpp
- opm/simulators/linalg/PreconditionerFactory_impl.hpp
- opm/simulators/linalg/WellOperators.hpp
- opm/simulators/linalg/amgcpr.hh
- opm/simulators/linalg/bda/BdaBridge.cpp
- opm/simulators/linalg/bda/MultisegmentWellContribution.cpp
- opm/simulators/linalg/bda/opencl/CPR.cpp
- opm/simulators/linalg/bda/opencl/Preconditioner.cpp
- opm/simulators/wells/MSWellHelpers.cpp
- opm/simulators/wells/MultisegmentWellEquations.cpp
- opm/simulators/wells/StandardWellEquations.cpp
- opm/simulators/wells/StandardWellEquations.hpp
- opm/simulators/wells/WellHelpers.cpp
-- added timing macros
-- added include files need
This give nearly full coverage of the cpr solver forexample for tracy profiling.
> -- added more timing to get better coverage of cpr solver

- CMakeLists_files.cmake
- ebos/eclgenericproblem.cc
- ebos/eclgenericproblem.hh
- ebos/eclproblem.hh
- ebos/eclsolutioncontainers.cc
- ebos/eclsolutioncontainers.hh
To make it easy to pass data around. Used to enable refactoring later.
> Add containers for polymer and MICP solution components

- ebos/alucartesianindexmapper.hh
- ebos/collecttoiorank.hh
- ebos/ebos.hh
- ebos/eclalugridvanguard.hh
- ebos/eclbasevanguard.hh
- ebos/eclcpgridvanguard.hh
- ebos/ecldummygradientcalculator.hh
- ebos/eclequilinitializer.hh
- ebos/eclfluxmodule.hh
- ebos/eclgenericcpgridvanguard.hh
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/eclgenerictracermodel.hh
- ebos/eclgenerictracermodel_impl.hh
- ebos/eclgenericvanguard.hh
- ebos/eclgenericwriter.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclpolyhedralgridvanguard.hh
- ebos/eclproblem.hh
- ebos/eclthresholdpressure.hh
- ebos/ecltracermodel.hh
- ebos/ecltransmissibility.hh
- ebos/eclwriter.hh
- ebos/vtkecltracermodule.hh
Not at all claiming this is the end of the story, but this is a contribution towards making these headers standalone.
> ebos/: header cleanups

- ebos/ecltracermodel.hh
I doubt this alone makes much of a difference, but it moves us in the right direction.
> EclTracerModel: replace cout with OpmLog

- CMakeLists_files.cmake
> add new _impl.hh files to public headers

- regressionTests.cmake
we should have some basic testing for these executables.
> add regression tests for flow_blackoil_alugrid and flow_blackoil_polyhedralgrid

- CMakeLists_files.cmake
- ebos/eclgenericproblem.hh
- ebos/eclgenericproblem_impl.hh
- ebos/eclmixingratecontrols.cc
- ebos/eclmixingratecontrols.hh
- ebos/eclproblem.hh
> EclProblem: put drsdtcon with friends in separate class

- CMakeLists_files.cmake
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- opm/simulators/flow/LogOutputHelper.cpp
- opm/simulators/flow/LogOutputHelper.hpp
- opm/simulators/utils/PressureAverage.cpp
- opm/simulators/utils/PressureAverage.hpp
- tests/test_LogOutputHelper.cpp
> Add dedicated class for output of logs

- opm/simulators/linalg/ISTLSolverEbosBda.cpp
- opm/simulators/linalg/bda/BdaBridge.cpp
After introducing of option to use Bda, some more parameters can end up unused. Mark them as such.
> Bda: mark some more parameters maybe_unused

- CMakeLists_files.cmake
- ebos/collecttoiorank.hh
- ebos/eclgenericoutputblackoilmodule.hh
- opm/simulators/flow/EclInterRegFlows.cpp
- opm/simulators/flow/EclInterRegFlows.hpp
- tests/test_eclinterregflows.cpp
> changed: move EclInterRegFlows to opm/simulators/flow

- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
.. and also allow loading from different file than saving to.
> Extended serialization to have negative stride mean 'only save last'

- opm/simulators/wells/BlackoilWellModel_impl.hpp
For stopped/zero-rate-target wells the _alternative_well_rate_init_-procedure currently returns unscaled well-rates resulting from a zero-bhp condition. I don't think this ever is helpful, and in particular it can lead to convergence failures for network balancing (since the initialized rates can off by orders of magnitude ). 
This pull request simply suggests to skip the _alternative_well_rate_init_-procedure for stopped/zero-rate-target wells.
> Skip initialization of rates for stopped/zero-rate-target wells

- opm/simulators/flow/BlackoilModelEbosNldd.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
It seems #4820 broke the serial build, this is attempting to restore it. Also documenting a new function parameter as requested in review, but forgotten.
> Fix serial compile

- CMakeLists_files.cmake
- ebos/eclgenericvanguard.cc
- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
- opm/simulators/utils/UnsupportedFlowKeywords.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GroupEconomicLimitsChecker.cpp
- opm/simulators/wells/GroupEconomicLimitsChecker.hpp
- tests/test_ParallelSerialization.cpp
Implement support for item 2 and 3 of the GECON keyword. See also companion PR https://github.com/OPM/opm-common/pull/3657 in opm-common for more information.
> Implement support for GECON keyword

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclwriter.hh
This is a rebased and processed version of https://github.com/OPM/opm-simulators/pull/4588
> added output writing for geomechanical module

- CMakeLists_files.cmake
- ebos/ebos.hh
- ebos/eclproblem.hh
- ebos/ecltimesteppingparams.hh
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- tests/test_glift1.cpp
this to allow reuse in ebos simulators
> changed: put ecl time stepping parameters in separate struct

- ebos/eclproblem.hh
> anonymize unused parameter

- opm/simulators/flow/Main.hpp
A smaller set of changes relating to Damaris and its initialization.
- Corrects the order for testing if a rank is a simulation rank (isSimulationRank_) after the initialize_() call.
- Adds a check that the number of simulation ranks is > 1 when run with Damaris enabled (command line option: --enable-damaris-output=true), if only 1 rank then Damaris is disabled.
- Places guard around code (using if (isSimulationRank_) )  that stops the Damaris server ranks running the simulation rank code when the Damaris server ranks return from the damaris_start() call. The Damaris ranks return from damaris_start() to the main code after simulation ranks call damaris_stop().
> Damaris fix for deadlock at end of simulation when run with Damaris 

- opm/simulators/wells/MultisegmentWellEquations.cpp
fix of add well contricutions. This fix should probably be followed by a test including cpr.
> fixed add-well-contributions for multisegement wells

- ebos/ecloutputblackoilmodule.hh
This PR splits `updateFluidInPlace_()` into several smaller helper functions, each with a narrow purpose.  They're all just called from the original call site&ndash;the body of `updateFluidInPlace_()`&ndash;but this new version is, in my opinion, easier to reason about and there is less shared state.
In anticipation of adding support for summary vectors `FHPV` and `RHPV` (field and region levels of hydrocarbon pore-volumes), we also split the pore-volume updates out to a branch separate from that needed for average pressure calculations.
> Refactor Fluid-In-Place Calculations For Maintainability

- ebos/eclgenericoutputblackoilmodule.cc
This commit separates the computation of hydrocarbon pore-volumes out from the context of average pressure values.  These pore-volumes go into the `xHPV` summary vectors and are, therefore, useful in their own right&ndash;not just as a means to computing average pressure values.
> Calculate Hydrocarbon Pore-Volumes if Requested

- ebos/ebos.hh
- opm/simulators/linalg/FlowLinearSolverParameters.hpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/ISTLSolverEbosBda.hpp
- tests/test_RestartSerialization.cpp
This has left the acceleration code unavailable for a few weeks.
> Fix typo in macro usage.

- ebos/FIBlackOilModel.hpp
-- safer loop
-- removed asserts which may be triggered in by strange input.
> Safer fluid evaluation

- opm/core/props/satfunc/RelpermDiagnostics.cpp
- regressionTests.cmake
Depends on https://github.com/OPM/opm-common/pull/3445
> Enable WSF/GSF for H2STORE

- opm/simulators/utils/ParallelEclipseState.cpp
This commit switches the region set tag matching algorithm to using unique prefixes.  This enables the simulator to recognise that the region set name
```
FIPUNI
```
should match up with the user defined region set `FIPUNIT`.  In the current master sources, the above summary vector would produce a diagnostic message saying that the region set `FIPUNI` (without the final `T`) does not exist.
To this end, we instruct the `ParallelEclipseState` to always pass the six character substring beginning with `FIP` for FIP-like region arrays and defer to the rank-0 `EclipseState`/`FieldProps` mechanism to match this prefix with its canonical region set.
> Match Region Sets by Unique Prefix

- python/README.md
Moved this PR from opm-common, see https://github.com/OPM/opm-common/pull/3667
> Added some Python documentation

- ebos/eclcpgridvanguard.hh
- ebos/ecltransmissibility.hh
- ebos/ecltransmissibility_impl.hh
* fixed error using NNZ with thermal
also:
* fixed but not checked for diffusion
* bug for zero thermal diffusion (nan in derivatives)
* added checking of consistency between input and taged phases
> fixed error using NNC with thermal

- ebos/ecltransmissibility_impl.hh
Set no connections in tranz if vertical cells has more layers in between and pinch is not set
> No connection without pinch and inactive/collapsed layers inbetween.

- opm/simulators/wells/MultisegmentWell_impl.hpp
> mark variable maybe_unused

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
for the functions related to createWellContainer() and runWellPIScaling().
So it is not exhaustive, but we should do it gradually.
got confused when working with the function createWellContainer(). 
It should NOT change any running results.
> distinguishing report step and time step

- opm/simulators/linalg/ISTLSolverEbos.hpp
Déjà vu
It feels like I have been correcting this multiple times :laughing:
> Fixed spelling: achived -> achieved

- opm/simulators/linalg/ISTLSolverEbos.hpp
> Fixed spelling: achive -> achieved

- ebos/eclgenerictracermodel.hh
- ebos/eclgenerictracermodel_impl.hh
Unnecessary data member removed from EclGenericTraceModel.
> cartToGlobal removed

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
To activte the output you will need to use
--enable-opm-rst-file=true
and
RPTRST
CONV /
> Add output of the residual at the end of a time step

- ebos/eclgenericoutputblackoilmodule.cc
Simple extension of the feature that is already available for CO2STORE
> Output XMF and YMF for H2STORE

- tests/test_dilu.cpp
And yet again some dead stores identified by static analysis.
> avoid more dead stores

- opm/simulators/utils/UnsupportedFlowKeywords.cpp
- regressionTests.cmake
Downstream of https://github.com/OPM/opm-common/pull/3747
> add support for FBHPDEF keyword

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- regressionTests.cmake
Companion to https://github.com/OPM/opm-common/pull/3695
> Network reroute - avoid looking up nonexisting nodes

- opm/simulators/wells/StandardWellConnections.cpp
> Fix rsw computation of wellbore density for StW

- opm/simulators/linalg/ISTLSolverEbos.hpp
> [backport] Bugfix. Deprecated getCollectiveComminication warning

- opm/simulators/utils/MPIPacker.cpp
Needed for serialization of FIPConfig.
Downstream of https://github.com/OPM/opm-common/pull/3756
> add extra instantation for bitset

- opm/simulators/wells/StandardWellConnections.cpp
> [backport] Fix rsw computation of wellbore density for StW

- doc/man1/flow.1
> [backport] Update flow manpage for release.

- opm/core/props/phaseUsageFromDeck.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
As flagged by static analyzers.
> Avoid some dead stores

- opm/simulators/wells/WellGroupHelpers.cpp
Depends on https://github.com/OPM/opm-common/pull/3702
> Support computation of network pressures in networks with multiple roots

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Fix potential infinite loop introduced in https://github.com/OPM/opm-simulators/pull/4999 (sorry).
> Check if well was closed this step before re-opening during history

- tests/test_LogOutputHelper.cpp
parsing logs some errors which meant using uninitialized values if no logger has been set
> fixed: we need to initialize logger before parsing

- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/PerfData.cpp
- opm/simulators/wells/PerfData.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellState.cpp
Depends on https://github.com/OPM/opm-common/pull/3782
> Add output of connection dissolved gas and vaporized oil

- ebos/eclproblem.hh
See https://github.com/OPM/opm-models/pull/833
> fix issue when BCPROP is not set initially

- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
The d factor is already scaled by the rate for WDFACCOR. 
Depends on https://github.com/OPM/opm-common/pull/3781
> dont scale d factor from wdfaccor with connection factor

- opm/simulators/wells/WellInterface_impl.hpp
depends on https://github.com/OPM/opm-common/pull/3788
> Adapt wdfac to wpimult

- opm/simulators/wells/BlackoilWellModel_impl.hpp
We are experiencing singular matrices when solving mulisegment wells sometimes. In that case (here during
`BlackoilModelEbos::assembleReservoir()` :arrow_left: `BlackoilModelEbos::initialLinerization()` :arrow_left:  `BlackoilModelEbos:::nonlinearIterationNewton()` an exception is thrown when updating the controls of a well.
The problem here is that this exception only happens on one process. That one goes to the catch block in `NonLinearSolverEbos::step()`, marks the nonlinear solve as failed and cuts the time step. The others move to the collective communication below. Somehow and somewhen all end up in a non-matching collective communication with different data types and we get an MPI Error that the message was truncated.
Now all processes will throw, terminate the nonlinear solver and …
> [bugfix] Expect singular matrices, terminate updateWellControls/nonlinear and cut timestep

- CMakeLists_files.cmake
- opm/simulators/aquifers/AquiferAnalytical.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.cpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/flow/SimulatorSerializer.cpp
- opm/simulators/flow/SimulatorSerializer.hpp
More separation of concerns. Obviously we cannot entirely decouple these components but I still think this is an improvement.
> Move simulator serialization to separate class

- opm/simulators/flow/SimulatorSerializer.cpp
if HDF5 input/output is requested but no support is available we throw early instead of just logging an error when save/load is to be performed
closes #5037
> changed: throw early in simulator serializer

- ebos/collecttoiorank_impl.hh
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericwriter_impl.hh
- ebos/eclwriter.hh
Downstream of https://github.com/OPM/opm-common/pull/3837
> adjust to data::CellData changes

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/GasLiftCommon.cpp
- opm/simulators/wells/GasLiftCommon.hpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftGroupInfo.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/GasLiftStage2.hpp
in particular avoid including GasLiftStage2.hpp in BlackoilWellModel
> GasLiftXXX: clean up includes

- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellEval.hpp
- opm/simulators/wells/MultisegmentWellSegments.cpp
- opm/simulators/wells/MultisegmentWellSegments.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
Depends on https://github.com/OPM/opm-common/pull/3684
> Allow UDA for WSEGVALV item 4

- ebos/collecttoiorank_impl.hh
- ebos/damariswriter.hh
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/ecloutputblackoilmodule.hh
- ebos/eclwriter.hh
This fixes parallel output of FLOWS and FLORES
It should also give a small speed up of the output part in parallel.
> Only output interior cells

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/eclgenericproblem.hh
- ebos/eclgenericproblem_impl.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- opm/simulators/flow/priVarsPacking.hpp
- tests/test_privarspacking.cpp
Depends on https://github.com/OPM/opm-common/pull/3764 and https://github.com/OPM/opm-models/pull/851
> add output of dissolved solvent rswsol

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
Depends on https://github.com/OPM/opm-common/pull/3823 and https://github.com/OPM/opm-models/pull/854
> Add output of FLOWS- and FLORES-

- ebos/eclproblem.hh
regressed in f508f3d4e8a11a6f32cb1b953ea92b39e6090100
> fixed: setting solvent values should be conditional on enableSolvent

- CMakeLists.txt
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- opm/simulators/flow/LogOutputHelper.cpp
- opm/simulators/flow/LogOutputHelper.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- tests/test_LogOutputHelper.cpp
Adding reservoir volume array custom FIP regions
> PRT file updates

- regressionTests.cmake
Downstream of https://github.com/OPM/opm-common/pull/3851
Downstream of https://github.com/OPM/opm-tests/pull/1112
> add additional regression tests for MULTFLT

- regressionTests.cmake
Test case was added in OPM/opm-tests#1099 and works since merge of OPM/opm-common#3845
> Add MULTREGT regression test.

- ebos/eclproblem.hh
- tests/test_ParallelSerialization.cpp
Depends on https://github.com/OPM/opm-common/pull/3835
> support source term from deck (SOURCE)

- CMakeLists.txt
- CMakeLists_files.cmake
- opm/simulators/flow/RSTConv.cpp
- opm/simulators/flow/RSTConv.hpp
- tests/test_rstconv.cpp
This calculates the vectors that will be written to  CNV_XXX vectors in the restart file.
> added: class for calculating RPTRST CONV

- CMakeLists_files.cmake
- ebos/damaris_properties.hh
- ebos/damariswriter.hh
- opm/simulators/utils/DamarisKeywords.cpp
- opm/simulators/utils/DamarisKeywords.hpp
- opm/simulators/utils/DamarisOutputModule.cpp
- opm/simulators/utils/DamarisOutputModule.hpp
Header scrubs, missing header guard and unnecessary dependencies.
> Some cleanup in damaris classes

- ebos/eclfluxmodule.hh
Should be merged together with https://github.com/OPM/opm-models/pull/858
> use arithmetic averaged compaction transmissibility multipliers

- ebos/eclgenericproblem.hh
- ebos/eclproblem.hh
- ebos/eclproblem_properties.hh
- opm/simulators/wells/WellInterface_impl.hpp
The option is false per default. i.e we use implicit as default.
> add option for explicit pressure for rock compaction (only transmissibility)

- ebos/collecttoiorank.hh
- ebos/eclgenericoutputblackoilmodule.cc
- ebos/eclgenericoutputblackoilmodule.hh
- ebos/eclgenericwriter.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclwriter.hh
- opm/simulators/flow/BlackoilModelEbos.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/5053
Downstream of https://github.com/OPM/opm-common/pull/3838
> added: hook up RPTRST CONV output to restart file if requested

- opm/simulators/linalg/ISTLSolverEbos.cpp
- opm/simulators/linalg/ISTLSolverEbos.hpp
- opm/simulators/linalg/getQuasiImpesWeights.hpp
-- give analytic cpr weights
-- useful for thermal
-- useful for cases with strange pvt
> add analytic true impes

- ebos/eclgenericoutputblackoilmodule.cc
- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/flow/RSTConv.cpp
- opm/simulators/flow/RSTConv.hpp
- tests/test_rstconv.cpp
Extend to support some extensions.
> added: RST CONV support for polymer, solvent and brine

- ebos/eclproblem.hh
See https://github.com/OPM/opm-common/pull/3864
This also fixes a bug if source and wells where combined in the same run.
> Add support for temperature in Source

- ebos/eclproblem.hh
Depends on https://github.com/OPM/opm-models/pull/859
> warn against no dispersion in gas phase

- CMakeLists_files.cmake
- ebos/eclgenericcpgridvanguard.cc
- ebos/eclgenericwriter_impl.hh
- opm/simulators/utils/MPISerializer.hpp
- opm/simulators/utils/ParallelRestart.cpp
- opm/simulators/utils/ParallelSerialization.cpp
- opm/simulators/utils/PropsDataHandle.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_ParallelSerialization.cpp
- tests/test_broadcast.cpp
it does not use the typetag system
> changed: move ebos/eclmpiserializer.hh to opm/simulators/utils/MPISerializer.hpp

- ebos/eclproblem.hh
Unnecessary container actnumData removed
> Unnecessary vector removed

- opm/simulators/flow/BlackoilModelEbos.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
NLDD requires --matrix-add-well-contributions=true for now. With this PR it is checked.
Also: minor improvement to well rank and subdomain output clutter.
> Avoid illegal combination of options.

- ebos/eclgenericoutputblackoilmodule.cc
- ebos/ecloutputblackoilmodule.hh
- opm/simulators/flow/LogOutputHelper.cpp
- tests/test_LogOutputHelper.cpp
Depends on https://github.com/OPM/opm-common/pull/3868
> Add co2 mass in place summary vectors

- CMakeLists_files.cmake
- opm/simulators/utils/DamarisVar.cpp
- opm/simulators/utils/DamarisVar.hpp
- fix some formatting
- avoid stream members in class
- add translation unit
- remove unused base class
Only thing I'm a bit uncertain of is what the purpose of the base class was. As-is it serves no purpose.
> DamarisVar: Some cleanup

- CMakeLists_files.cmake
- flow/flow_blackoil_alugrid.cpp
- flow/flow_blackoil_polyhedralgrid.cpp
- opm/simulators/utils/GridDataOutput.cpp
- opm/simulators/utils/GridDataOutput.hpp
- opm/simulators/utils/GridDataOutput_impl.hpp
- add translation unit
- avoid stringstream member
- add const correctness
- fix some formatting
> GridDataOutput: some cleanup

- ebos/damariswriter.cc
- ebos/damariswriter.hh
Cosmetics and some code shuffling.
> DamarisWriter: some additional cleanup

- ebos/eclbasevanguard.hh
- opm/simulators/linalg/ISTLSolverEbosBda.hpp
- tests/test_equil.cc
- tests/test_wellmodel.cpp
Removal of unused headers, addition of used headers.
> Some header cleanups

- CMakeLists_files.cmake
- ebos/ebos.hh
- opm/simulators/flow/BlackoilModelNldd.hpp
- opm/simulators/linalg/FlowLinearSolverParameters.hpp
- opm/simulators/linalg/ISTLSolver.cpp
- opm/simulators/linalg/ISTLSolver.hpp
- opm/simulators/linalg/ISTLSolverBda.cpp
- opm/simulators/linalg/ISTLSolverBda.hpp
- tests/test_RestartSerialization.cpp
> ISTLSolverEbos: rename to ISTLSolver

- CMakeLists_files.cmake
- ebos/eclproblem.hh
- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.cpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- tests/test_RestartSerialization.cpp
- tests/test_equil.cc
> AdaptiveTimeSteppingEbos: rename to AdaptiveTimeStepping

- regressionTests.cmake
- tests/test_nonnc.cpp
Add NONNC regression test and change the copyright owner of test_nonnc.cpp to Equinor ASA
> Two more enhancements concerning NONNC

- compareECLFiles.cmake
Not just that it has been found.
> fixed: make sure Damaris is enabled before executing test

- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
Header scrub and replace typedef with using.
> SimulatorFullyImplicitBlackoil.hpp: Some janitoring

- opm/simulators/flow/Banners.hpp
- opm/simulators/linalg/ISTLSolver.hpp
- opm/simulators/linalg/ISTLSolverBda.hpp
- opm/simulators/linalg/WellOperators.hpp
- opm/simulators/opm-simulators_doxygen_main.hpp
- opm/simulators/timestepping/SimulatorReport.cpp
These refer to renamed classes etc.
> Fix some comments

- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/BlackoilModelNldd.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
Either ebos -> model or ebos -> nothing
> BlackoilModel: drop ebos in variable names

- ebos/eclproblem.hh
- ebos/eclproblem_properties.hh
- flow/flow_blackoil_alugrid.cpp
> Remove some parameters that are not used by flow

- ebos/ecltransmissibility_impl.hh
> Documentation fixed in skipping indices for trans 

- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
std::to_string doesn't use generic format and thus small numbers are truncated to 0.0000000
> AdaptiveTimeStepping: use {fmt} to format messages

- CMakeLists_files.cmake
- ebos/damariswriter.hh
- ebos/ecloutputblackoilmodule.hh
- ebos/eclproblem.hh
- ebos/eclproblem_properties.hh
- ebos/eclwriter.hh
- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
Requires https://github.com/OPM/opm-models/pull/875
> Move BlackoilOutputModule from ebos to opm/simulators/flow

- CMakeLists_files.cmake
- ebos/damariswriter.hh
- ebos/eclgenericwriter.hh
- ebos/eclgenericwriter_impl.hh
- ebos/eclwriter.hh
- flow/flow_blackoil_alugrid.cpp
- flow/flow_blackoil_polyhedralgrid.cpp
- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/CollectDataOnIORank.cpp
- opm/simulators/flow/CollectDataOnIORank.hpp
- opm/simulators/flow/CollectDataOnIORank_impl.hpp
While at it fix the name of the class. You collect *On* the io rank, not to.
> ebos/collecttoiorank: move to opm/simulators/flow

- opm/simulators/linalg/bda/rocsparseSolverBackend.cpp
I believe this should be fairly straight forward, but I have no way to check runtime.
> Quell rocsparse warnings

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellState.cpp
add necessary headers, remove unused.
Fixes some fallout from https://github.com/OPM/opm-simulators/pull/5262
> BlackoilWellModel: header cleanup and some debug-iterator fixes

- opm/simulators/flow/FlowMain.hpp
Downstream of https://github.com/OPM/opm-models/pull/884
> adjust to EWOMS_END_PARAM_REGISTRATION macro removal

- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/linalg/FlowLinearSolverParameters.hpp
- opm/simulators/linalg/ISTLSolver.hpp
Downstream of https://github.com/OPM/opm-models/pull/885
> adjust to EWOMS_PARAM_IS_SET macro removal

- opm/simulators/flow/BlackoilModelParameters.hpp
- opm/simulators/flow/FlowBaseVanguard.hpp
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
Downstream of https://github.com/OPM/opm-models/pull/887
> adjust to EWOMS_HIDE_PARAM macro removal

- compareECLFiles.cmake
- pyactionComparisons.cmake
- tests/run-comparison.sh
Add tests that compare flow runs with the PYACTION keyword with the corresponding runs with the ACTIONX keyword.
Depends on https://github.com/OPM/opm-common/pull/3999
> Comparison tests for PYACTION

- opm/simulators/flow/BlackoilModelParameters.hpp
- opm/simulators/flow/DamarisWriter.hpp
- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/FlowBaseVanguard.hpp
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/NonlinearSolver.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
- opm/simulators/flow/VtkTracerModule.hpp
- opm/simulators/linalg/FlowLinearSolverParameters.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/EclTimeSteppingParams.hpp
- tests/test_RestartSerialization.cpp
- tests/test_equil.cpp
- tests/test_glift1.cpp
Downstream of https://github.com/OPM/opm-models/pull/890
> Adjust to EWOMS_REGISTER_PARAM macro removal

- opm/simulators/flow/BlackoilModelParameters.hpp
- opm/simulators/flow/FlowBaseVanguard.hpp
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
Downstream of https://github.com/OPM/opm-models/pull/891
> adjust to Parameters::hideParam change

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
- opm/simulators/wells/BlackoilWellModelConstraints.cpp
- opm/simulators/wells/BlackoilWellModelConstraints.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
- tests/test_RestartSerialization.cpp
Depends on https://github.com/OPM/opm-common/pull/3894
> Implement WELL as group limit action

- regressionTests.cmake
The tests can be found in OPM/opm-tests#1142.
Together with OPM/opm-common#3997 this will make sure that the fix in OPM/opm-common#4002 stays.
> Added MULTXYZ tests as regression tests.

- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/linalg/FlowLinearSolverParameters.hpp
- opm/simulators/linalg/ISTLSolver.hpp
Downstream of https://github.com/OPM/opm-models/pull/894
> adjust to Parameters::isSet change

- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
use Parallel::Communication directly instead
> WellState: remove template parameters for comm

- opm/simulators/wells/BlackoilWellModelConstraints.cpp
> BlackoilWellModelConstraints: fix throw of bare string

- opm/simulators/flow/ActionHandler.cpp
- opm/simulators/flow/ActionHandler.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelConstraints.cpp
- opm/simulators/wells/BlackoilWellModelConstraints.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModelGuideRates.cpp
- opm/simulators/wells/BlackoilWellModelGuideRates.hpp
- opm/simulators/wells/BlackoilWellModelRestart.cpp
- opm/simulators/wells/BlackoilWellModelRestart.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GroupEconomicLimitsChecker.cpp
- opm/simulators/wells/GroupEconomicLimitsChecker.hpp
- tests/test_RestartSerialization.cpp
> BlackoilWellModel: template Scalar type

- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/GasLiftStage2.hpp
In master gaslift was only redistributed for group limited by rates
> Redistribute gaslift for groups with alq limit

- opm/simulators/aquifers/AquiferAnalytical.hpp
- opm/simulators/aquifers/AquiferCarterTracy.hpp
- opm/simulators/aquifers/AquiferConstantFlux.hpp
- opm/simulators/aquifers/AquiferInterface.hpp
- opm/simulators/aquifers/AquiferNumerical.hpp
- opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
use the Scalar type in Aquifer classes.
> Aquifer: use Scalar type

- flowexperimental/BlackOilEnergyIntensiveQuantitiesGlobalIndex.hpp
- flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp
- flowexperimental/FIBlackOilModelNoCache.hpp
- flowexperimental/FlowExpNewtonMethod.hpp
- flowexperimental/flowexp_blackoil.cpp
Various cosmetics to align with opm standards.
> FlowExp: spring cleaning

- opm/simulators/flow/equil/EquilibrationHelpers_impl.hpp
- opm/simulators/flow/equil/InitStateEquil_impl.hpp
I preliminary quick fix. Need to test a bit more before merging.
> Fix gas-water initialization with transision zone

- opm/simulators/flow/FlowGenericProblem.hpp
- opm/simulators/flow/FlowGenericProblem_impl.hpp
- opm/simulators/flow/FlowProblem.hpp
found the function unused when looking at HYSTER related code.
> removing unused updateImbnum_ function

- CMakeLists.txt
Lower the CMake version to support RHEL 7 (solving issue #5339)
> Lower CMake version

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/LogOutputHelper.cpp
- opm/simulators/flow/OutputBlackoilModule.hpp
See https://github.com/OPM/opm-common/pull/4060
> Add GMST and modify GMTR output the maximum trapped CO2 in the gas phase

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftCommon.cpp
- opm/simulators/wells/GasLiftCommon.hpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftGroupInfo.hpp
- opm/simulators/wells/GasLiftSingleWell.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/GasLiftStage2.hpp
- opm/simulators/wells/GasLiftWellState.hpp
- opm/simulators/wells/WellInterface.hpp
- tests/test_glift1.cpp
> GasLift: template Scalar type

- tests/test_RestartSerialization.cpp
we want both tests when dune-fem is present
> fixed: also run the RestartSerialization tests without dune-fem

- opm/simulators/flow/ActionHandler.cpp
- opm/simulators/flow/ActionHandler.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/wells/WellAssemble.cpp
- opm/simulators/wells/WellBhpThpCalculator.cpp
- opm/simulators/wells/WellBhpThpCalculator.hpp
- opm/simulators/wells/WellConstraints.cpp
- opm/simulators/wells/WellConstraints.hpp
- opm/simulators/wells/WellConvergence.cpp
- opm/simulators/wells/WellConvergence.hpp
- opm/simulators/wells/WellGroupConstraints.cpp
- opm/simulators/wells/WellGroupConstraints.hpp
- opm/simulators/wells/WellGroupControls.cpp
- opm/simulators/wells/WellGroupControls.hpp
- opm/simulators/wells/WellHelpers.cpp
- opm/simulators/wells/WellHelpers.hpp
- opm/simulators/wells/WellTest.cpp
- opm/simulators/wells/WellTest.hpp
Another part of https://github.com/OPM/opm-simulators/pull/5286
> Various well helpers: template Scalar type

- examples/printvfp.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/VFPHelpers.cpp
- opm/simulators/wells/VFPHelpers.hpp
- opm/simulators/wells/VFPInjProperties.cpp
- opm/simulators/wells/VFPInjProperties.hpp
- opm/simulators/wells/VFPProdProperties.cpp
- opm/simulators/wells/VFPProdProperties.hpp
- opm/simulators/wells/VFPProperties.hpp
- opm/simulators/wells/WellBhpThpCalculator.cpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
- tests/test_vfpproperties.cpp
Another small piece of https://github.com/OPM/opm-simulators/pull/5286
> VFP classes: template Scalar type

- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellAssemble.cpp
- opm/simulators/wells/StandardWellAssemble.hpp
- opm/simulators/wells/StandardWellConnections.cpp
- opm/simulators/wells/StandardWellConnections.hpp
- opm/simulators/wells/StandardWellEquations.cpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWellEval.hpp
- opm/simulators/wells/StandardWellPrimaryVariables.cpp
- opm/simulators/wells/StandardWellPrimaryVariables.hpp
- opm/simulators/wells/StandardWell_impl.hpp
> StandardWell: use Scalar type

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/ParallelPAvgCalculator.cpp
- opm/simulators/wells/ParallelPAvgCalculator.hpp
- opm/simulators/wells/ParallelPAvgDynamicSourceData.cpp
- opm/simulators/wells/ParallelPAvgDynamicSourceData.hpp
- opm/simulators/wells/ParallelWBPCalculation.cpp
- opm/simulators/wells/ParallelWBPCalculation.hpp
- tests/test_parallel_wbp_calculation.cpp
- tests/test_parallel_wbp_sourcevalues.cpp
Downstream of https://github.com/OPM/opm-common/pull/4073
> PAvgCalculator: template Scalar type

- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/BlackoilModelNldd.hpp
- opm/simulators/flow/BlackoilModelParameters.hpp
- opm/simulators/flow/GenericTracerModel.hpp
- opm/simulators/flow/GenericTracerModel_impl.hpp
- opm/simulators/flow/NonlinearSolver.cpp
- opm/simulators/flow/NonlinearSolver.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
- opm/simulators/flow/Transmissibility.hpp
- opm/simulators/flow/Transmissibility_impl.hpp
- opm/simulators/linalg/WellOperators.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/VFPHelpers.cpp
- opm/simulators/wells/VFPProdProperties.cpp
- opm/simulators/wells/WellFilterCake.cpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellProdIndexCalculator.cpp
- opm/simulators/wells/WellProdIndexCalculator.hpp
- tests/test_wellprodindexcalculator.cpp
> Various classes: use Scalar type

- opm/simulators/flow/equil/EquilibrationHelpers.cpp
- opm/simulators/flow/equil/EquilibrationHelpers.hpp
- opm/simulators/flow/equil/EquilibrationHelpers_impl.hpp
- opm/simulators/flow/equil/InitStateEquil.cpp
- opm/simulators/flow/equil/InitStateEquil.hpp
- opm/simulators/flow/equil/InitStateEquil_impl.hpp
- tests/test_equil.cpp
> InitStateEquil: template Scalar type

- opm/simulators/flow/FlowProblem.hpp
Commit 0aaa69c6e (PR #5330) was a little too eager in its effort to handle UDQ ASSIGN operations after action processing[%].  In particular, the assignments, which alter the internal structures of the `SummaryState` and `UDQState` objects, would happen prior to writing summary files.  In turn, this would make it appear as if the assignment happened too early.  This commit defers UDQ assignments triggered by action processing until `FlowProblem<>::endEpisode()` for two reasons
1. The problem originally addressed in 0aaa69c6e only presented when the assignment was triggered on the final time step of an episode (report step), so handling this situation here is a more targeted approach.
2. Member function `FlowProblem<>::endEpisode()` is called after we write the summary file output so any …
> Delay UDQ Assignments Until After Summary Output

- opm/simulators/utils/UnsupportedFlowKeywords.cpp
Needed in PR:  https://github.com/OPM/opm-common/pull/4091
> Support for CNAMES

- opm/simulators/flow/BlackoilModelNldd.hpp
Not ready for merging yet, will refactor to reuse existing implementation instead of duplicating. But results with this seem good on Sleipner at least.
> Add Newton update damping when domain solution oscillates.

- opm/simulators/wells/PerfData.cpp
- opm/simulators/wells/PerfData.hpp
> Ensure the 'injector' member is initialized, compared etc.

- opm/simulators/flow/DamarisWriter.cpp
- opm/simulators/flow/DamarisWriter.hpp
This should improve error handling in parallel, and ensure Damaris problems are logged properly.
> Add and use DamarisOutput::handleError() helper.

- opm/simulators/flow/EclGenericWriter.hpp
- opm/simulators/flow/EclGenericWriter_impl.hpp
- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/FlowProblemProperties.hpp
See https://github.com/OPM/opm-common/pull/4104
> fix option for output every timestep

- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
Depends on https://github.com/OPM/opm-common/pull/4089
> Output maximum/minimum saturations directly for restart hysteresis

- flowexperimental/flowexp.hpp
- flowexperimental/flowexp_blackoil.cpp
- opm/simulators/aquifers/AquiferAnalytical.hpp
- opm/simulators/aquifers/AquiferNumerical.hpp
- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/BlackoilModelParameters.hpp
- opm/simulators/flow/FlowBaseVanguard.hpp
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblemProperties.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/flow/VtkTracerModule.hpp
- tests/TestTypeTag.hpp
Downstream of https://github.com/OPM/opm-models/pull/904
> Adjust to to changes in fvbaseproperties.hh (moving of parameters to Opm::Parmeters namespace)

- flowexperimental/FlowExpNewtonMethod.hpp
- flowexperimental/flowexp.hpp
- flowexperimental/flowexp_blackoil.cpp
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblemProperties.hpp
- opm/simulators/flow/NonlinearSolver.hpp
- tests/TestTypeTag.hpp
Downstream of https://github.com/OPM/opm-models/pull/905
> NewtonMethod: split parameters and properties

- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/FlowProblemProperties.hpp
Downstream of https://github.com/OPM/opm-models/pull/906
> basicproperties:  split out params

- compareECLFiles.cmake
- opm/simulators/utils/DamarisVar.cpp
- tests/update_reference_data.sh
hopefully this is enough to bring back damaris support.
> add missing include and damaris reference file update support

- pyactionComparisons.cmake
I will use this PR to perform amgcl re-enablement so excuse the noise...
> fix typo in test name

- opm/simulators/flow/FlowProblem.hpp
Also restructure to loop over active phases instead of all canonical phases.
This resolves an issue reported by static analysis.
> Ensure all members are initialized in FlowProblem::boundaryFluidState().

- CMakeLists_files.cmake
- opm/simulators/flow/CpGridVanguard.hpp
- opm/simulators/flow/FlowBaseVanguard.hpp
- opm/simulators/flow/FlowGenericVanguard.hpp
- opm/simulators/flow/GenericCpGridVanguard.cpp
- opm/simulators/flow/GenericCpGridVanguard.hpp
- opm/simulators/flow/partitionCells.cpp
- opm/simulators/utils/SetupPartitioningParams.cpp
- opm/simulators/utils/SetupPartitioningParams.hpp
Depends on https://github.com/OPM/opm-grid/pull/736
> Add the metis partitioner as a command line option as well

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
Depends on https://github.com/OPM/opm-common/pull/4142
> Output support for RSWSAT and RVWSAT

- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/FlowProblemProperties.hpp
- opm/simulators/linalg/FlowLinearSolverParameters.hpp
Downstream of https://github.com/OPM/opm-models/pull/913
> Move linear solver parameters to Opm::Parameters namespace

- opm/simulators/flow/Main.hpp
when not setting `OMP_NUM_THREADS` in the environment.
it causes debugging hassle for the environment that not setting `OMP_NUM_THREADS`.
> avoiding exception from std::stoi("")

- opm/simulators/linalg/bda/Preconditioner.hpp
- opm/simulators/linalg/bda/opencl/openclBILU0.hpp
- opm/simulators/linalg/bda/opencl/openclBISAI.hpp
- opm/simulators/linalg/bda/opencl/openclCPR.hpp
- opm/simulators/utils/MPIPacker.cpp
- opm/simulators/utils/MPIPacker.hpp
Missing overrides and static non-inline function in header.
> Quell some clang warnings

- opm/simulators/flow/FlowMain.hpp
Downstream of https://github.com/OPM/opm-models/pull/918
> Remove support for the print-properties parameter

- opm/simulators/flow/FlowBaseVanguard.hpp
- opm/simulators/flow/FlowGenericVanguard.cpp
- opm/simulators/flow/FlowGenericVanguard.hpp
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
To write the .vtu when --enable-vtk-output=1 --enable-dry-run=1
> Write vtk (if enabled) for dry runs

- CMakeLists_files.cmake
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
- tests/parametersystem.ini
- tests/test_glift1.cpp
- tests/test_outputdir.cpp
- tests/test_parametersystem.cpp
Downstream of https://github.com/OPM/opm-models/pull/916
> Support type-tag free parameter system

- flowexperimental/flowexp.hpp
- flowexperimental/flowexp_blackoil.cpp
- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/BlackoilModelParameters.hpp
- opm/simulators/flow/FlowBaseVanguard.hpp
- opm/simulators/flow/FlowMain.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/FlowProblemProperties.hpp
- opm/simulators/flow/Main.hpp
- opm/simulators/flow/VtkTracerModule.hpp
- tests/TestTypeTag.hpp
- tests/test_RestartSerialization.cpp
- tests/test_equil.cpp
- tests/test_glift1.cpp
- tests/test_outputdir.cpp
Downstream of https://github.com/OPM/opm-models/pull/923
> Move parameters to typetag-free parameter system

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
Depends on https://github.com/OPM/opm-common/pull/4163
> rename GMIM to GMTR

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
Depends on https://github.com/OPM/opm-common/pull/4162
> Pass gas mass rate to summary

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
See https://github.com/OPM/opm-common/pull/4003
> Allow Hysteresis option 4

- opm/simulators/wells/ParallelPAvgCalculator.cpp
- opm/simulators/wells/ParallelPAvgDynamicSourceData.cpp
- opm/simulators/wells/ParallelWBPCalculation.cpp
Small batch to separate out the upstream dependency.
Downstream of https://github.com/OPM/opm-common/pull/4168
> Support float simulators - batch 2

- opm/simulators/flow/ActionHandler.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelRestart.cpp
Another small one to isolate the upstream.
Downstream of https://github.com/OPM/opm-common/pull/4169
> ActionHandler: instance for float

- opm/simulators/flow/EclGenericWriter.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/NonlinearSolver.cpp
- opm/simulators/flow/OutputBlackoilModule.hpp
Downstream of https://github.com/OPM/opm-common/pull/4171
> Float support in simulators: Batch 4

- CMakeLists_files.cmake
- opm/simulators/linalg/cuistl/CuDILU.cpp
- opm/simulators/linalg/cuistl/CuDILU.hpp
- opm/simulators/linalg/cuistl/OpmCuILU0.cpp
- opm/simulators/linalg/cuistl/OpmCuILU0.hpp
- opm/simulators/linalg/cuistl/detail/autotuner.hpp
This avoid code duplication currently present in CuDILU and OpmCuILU0.
The former autotuner is also improved by timing with the CUDA events API.
> Generalize thread block tuner

- opm/simulators/linalg/ISTLSolver.hpp
These modeling options are currently incompatible with our CPRW implementation.
In the current master, this will crash with no helpful user message, see #5544.
> Intercept CPRW if MICP or polymer injectivity is used.

- regressionTests.cmake
following the investigation in https://github.com/OPM/opm-models/pull/877.
> hopefully stabilizing some regression test

- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
Needed for https://github.com/OPM/opm-common/pull/4166
> Avoid updating max Rs first step after restart.

- opm/simulators/flow/BlackoilModelNldd.hpp
- opm/simulators/flow/FlowGenericVanguard.cpp
- opm/simulators/linalg/ISTLSolverBda.cpp
- opm/simulators/linalg/bda/BdaBridge.cpp
- opm/simulators/linalg/bda/BlockedMatrix.cpp
- opm/simulators/linalg/bda/CprCreation.cpp
- opm/simulators/linalg/bda/CprCreation.hpp
- opm/simulators/linalg/bda/Misc.cpp
- opm/simulators/linalg/bda/cuda/cusparseSolverBackend.cu
- opm/simulators/linalg/bda/opencl/OpenclMatrix.cpp
- opm/simulators/linalg/bda/opencl/openclBILU0.cpp
- opm/simulators/linalg/bda/opencl/openclBISAI.cpp
- opm/simulators/linalg/bda/opencl/openclCPR.cpp
- opm/simulators/linalg/bda/opencl/openclCPR.hpp
- opm/simulators/linalg/bda/opencl/openclPreconditioner.cpp
- opm/simulators/linalg/bda/opencl/openclSolverBackend.cpp
- opm/simulators/linalg/bda/rocm/hipKernels.cpp
- opm/simulators/linalg/bda/rocm/rocalutionSolverBackend.cpp
- opm/simulators/linalg/bda/rocm/rocsparseBILU0.cpp
- opm/simulators/linalg/bda/rocm/rocsparseCPR.cpp
- opm/simulators/linalg/bda/rocm/rocsparseMatrix.cpp
- opm/simulators/linalg/bda/rocm/rocsparsePreconditioner.cpp
- opm/simulators/linalg/bda/rocm/rocsparseSolverBackend.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
This is the final batch (before enabling the float simulator binary).
Sits on top of https://github.com/OPM/opm-simulators/pull/5550
> Float support in simulators: Batch 5

- CMakeLists.txt
- flow/flow_blackoil_float_main.cpp
- regressionTests.cmake
Sits on top of https://github.com/OPM/opm-simulators/pull/5556
> Add float blackoil simulator

- opm/simulators/flow/BlackoilModelNldd.hpp
If the user chooses a specific number of NLDD domains, there is no need to compute the default number of domains based on a specific target number of cells per domain.  Defer the, potentially costly, calculation to when we know we need it.  I didn't pick up on this detail when reviewing PR #5021.
While here, also split/rejoin a couple of long lines.
> Don't Count Cells Unless Needed

- CMakeLists_files.cmake
- opm/models/utils/parametersystem.cpp
- opm/models/utils/parametersystem.hpp
- opm/models/utils/start.hh
- opm/models/utils/terminal.cpp
- opm/models/utils/terminal.hpp
add opm/models/utils/terminal.[ch]pp and move some functions from parametersystem and start.hh there.
> added: translation unit for terminal manipulation stuff

- CMakeLists.txt
- CMakeLists_files.cmake
- opm/models/discretization/common/fvbaseproblem.hh
- opm/models/io/restart.cpp
- opm/models/io/restart.hpp
- opm/models/utils/parametersystem.cpp
- opm/models/utils/parametersystem.hpp
- opm/models/utils/simulator.hh
- opm/models/utils/simulatorutils.cpp
- opm/models/utils/simulatorutils.hpp
- opm/models/utils/start.hh
- opm/models/utils/terminal.cpp
- opm/models/utils/terminal.hpp
Granted these are very minor optimizations, but small chips...
> Move more opm-models code to translation units

- CMakeLists.txt
- tests/make_failure_report.sh
- tests/plot_well_comparison.py
This creates a pdf for each failed case with plots of summary curves.
I am in no way claiming this is a marvel of engineering but it's a start.
Requires https://github.com/OPM/opm-common/pull/4184
> added: scripts for generating failure reports on jenkins

- opm/simulators/linalg/FlexibleSolver_impl.hpp
- opm/simulators/linalg/gpuistl/set_device.cpp
Forgot to change `cubicgstab` to `gpubicgstab` in #5554
> update the name of the solver to fit with gpuistl

- opm/simulators/linalg/gpuistl/GpuView.hpp
Resolve a todo added because `gpuDecorators.hpp` was not yet merged
> reolve gpuistl macro todo

- opm/models/blackoil/blackoilpolymerparams.hpp
- opm/models/blackoil/blackoilsolventparams.hpp
caused issues for serialization tests in the debug iterator build
> fixed: initialize members

- opm/simulators/flow/FlowProblem.hpp
quells warnings building flowexp_comp
> fixed: make sure we have valid indices in readInitialCondition_

- opm/simulators/wells/StandardWell_impl.hpp
Ensure well and accumulated group efficiency factors are applied to the connection energy rates.
> Apply well/group efficiency factors for connection energy rates. 

- opm/simulators/wells/StandardWell_impl.hpp
The b factor was doubled up for the gas component if DISGASW and VAPWAT was activated. Should only affect the bhp calculations, not the reservoir results itself.
> BUGFIX fix injection bhp pressure for CO2/H2 STORE

- opm/simulators/wells/BlackoilWellModel_impl.hpp
Seems to fix some output problems.
> fixing some of output

- opm/simulators/wells/GlobalWellInfo.cpp
- opm/simulators/wells/GlobalWellInfo.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellState.hpp
Also allow non-zero ALQ for extended network.
> Avoid adding gas lift of non-open wells to network

- opm/simulators/flow/FlowProblemComp.hpp
it needs https://github.com/OPM/opm-common/pull/4200 .
> supporting ZMF explicit solution

- tests/test_LogOutputHelper.cpp
In particular, put more of the common setup code into the test fixture and use more powerful constructors for the `EclipseState` object.  While here, also switch to using the `update_well_var()` and `update_group_var()` member functions on the `SummaryState` object where appropriate since the resulting statements become slightly easier to understand in isolation.
> Simplify Unit Tests for LogOutputHelper

- opm/simulators/wells/WellInterface_impl.hpp
> Delay stopping wells after local well solves until global update agrees (rebased)

- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/OutputBlackoilModule.hpp
Backport of pr #5668 to release branch for OPM 2024.10 release.
> Fix gas-water restart

- CMakeLists_files.cmake
- opm/simulators/flow/AluGridCartesianIndexMapper.hpp
- opm/simulators/flow/AluGridLevelCartesianIndexMapper.hpp
- opm/simulators/flow/AluGridVanguard.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/GenericCpGridVanguard.cpp
- opm/simulators/flow/GenericCpGridVanguard.hpp
- opm/simulators/flow/PolyhedralGridVanguard.hpp
- opm/simulators/utils/satfunc/RelpermDiagnostics.cpp
- opm/simulators/utils/satfunc/RelpermDiagnostics.hpp
- tests/test_relpermdiagnostics.cpp
> Separate non-DUNE methods in LevelCartesianIndexMapper<AluGrid>

- opm/simulators/flow/ActionHandler.cpp
Similar to the logging facilities we have for the regular ACTIONX keyword, although without an explicit list of "matching" wells.
> Add Logging for Python Actions

- opm/simulators/flow/GenericCpGridVanguard.cpp
Downstream of https://github.com/OPM/opm-common/pull/4293
> fixed: set active indices in fieldprops

- opm/simulators/flow/ActionHandler.cpp
This commit switches to using the new guarantees provided by `ActionX::wellpi_wells()` (PR OPM/opm-common#4296), namely that the well names are returned in sorted order on all ranks, to simplify how we exchange the PI/II values.  In particular, given this guarantee, we can calculate the maximum values across all ranks because zero values correspond to missing entries and non-zero values correspond to known entries.
> Simplify Logic for Exchanging PI/II Values in ACTIONX/WELPI

- opm/simulators/linalg/gpuistl/device_management.cpp
Fixes regression from https://github.com/OPM/opm-simulators/pull/5611 if no gpu devices are available on system
> fixed: division by zero if no gpu device was found

- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/GasLiftStage2.hpp
This PR is a first of several that aims to fix the gaslift code for cases with complex group controls with liquid / water constrains.
> Fix gaslift 1

- opm/simulators/linalg/gpuistl/GpuOwnerOverlapCopy.hpp
- add virtual dtor to class with virtual members
- remove unused variable
> Janitoring

- opm/simulators/flow/ActionHandler.cpp
Following OPM/opm-common#4340, the `Action::Result` type no longer uses operator overloading and the matching entity back-end has been revised to no longer expose a vector of strings for the well names directly.
> Chase API Update of Action::Result

- opm/simulators/wells/ParallelWellInfo.hpp
> fixed: add missing include

- opm/simulators/flow/BlackoilModelParameters.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
This reopens https://github.com/OPM/opm-simulators/pull/5737
> Network sub iter

- opm/simulators/flow/python/PyBlackOilSimulator.hpp
- python/simulators/PyBlackOilSimulator.cpp
- python/simulators/PyMain.hpp
- python/test/test_basic.py
This adds the ability to pass standard command line parameters in the python simulator.
Closes #5759
> added: ability to pass command line parameters from python

- opm/simulators/flow/FlowThresholdPressure.hpp
- opm/simulators/flow/GenericThresholdPressure_impl.hpp
Managed to leave this out of https://github.com/OPM/opm-simulators/pull/5743, sorry about that.
> Write correct THRESHPR values also from restart

- dune.module
- opm/simulators/flow/CollectDataOnIORank.cpp
- opm/simulators/flow/EclGenericWriter.cpp
- opm/simulators/flow/FemCpGridCompat.hpp
- opm/simulators/flow/FlowGenericProblem.cpp
- opm/simulators/flow/GenericCpGridVanguard.cpp
- opm/simulators/flow/GenericThresholdPressure.cpp
- opm/simulators/flow/GenericTracerModel.cpp
- opm/simulators/flow/Transmissibility.cpp
- opm/simulators/flow/equil/InitStateEquil.cpp
- opm/simulators/linalg/ExtraSmoothers.hpp
- opm/simulators/linalg/MILU.cpp
- opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/utils/GridDataOutput.cpp
- opm/simulators/utils/VectorVectorDataHandle.hpp
- tests/test_RestartSerialization.cpp
- tests/test_milu.cpp
Downstream of https://github.com/OPM/opm-common/pull/4157
Closes https://github.com/OPM/opm-simulators/issues/5425
> bump minimum dune version to 2.9

- tests/models/test_tasklets_failure.cpp
the boost.test signal handlers do not play nicely with fork()
i am aware this is not optimal but better a stable test than a sometimes broken test. in particular it breaks with dynamic boost test and clang.
> changed: do not use boost.test in test_tasklets_failure

- opm/simulators/flow/KeywordValidation.hpp
- opm/simulators/flow/ValidationFunctions.cpp
- opm/simulators/flow/ValidationFunctions.hpp
- introduce a type alias for the std::function type
- make implementation of specialValidations() private
- make validateBRINE private
> ValidationFunctions: some cleanup

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/ParallelWBPCalculation.cpp
- opm/simulators/wells/ParallelWBPCalculation.hpp
- tests/test_parallel_wbp_calculation.cpp
The WBP result type is now top-level.
> Chase API Update

- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
- parallelTests.cmake
We need to sync time step adjustments across processes
> Fix WCYCLE in parallel

- CMakeLists_files.cmake
- opm/simulators/wells/RatioCalculator.cpp
- opm/simulators/wells/RatioCalculator.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWellEval.hpp
- opm/simulators/wells/StandardWell_impl.hpp
Allows moving 200 lines of code into a translation unit.
> Add dedicated class for some ratio calculation in StandardWell

- opm/simulators/flow/BlackoilModelNldd.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterfaceGeneric.hpp
Reorganizations to enable moving more code into the Generic base class
> More some more code to generic well model

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GlobalWellInfo.cpp
- opm/simulators/wells/GlobalWellInfo.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
> Allow query for efficiency scaling factor in off-process wells where required

- opm/simulators/wells/MSWellHelpers.cpp
- opm/simulators/wells/MSWellHelpers.hpp
- opm/simulators/wells/MultisegmentWellEquations.cpp
- opm/simulators/wells/MultisegmentWellEquations.hpp
Implement mmv and mv functions that do the communication and are called from the business layer.
> Remove the mpi calls from the business logic

- opm/simulators/linalg/WellOperators.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
We already have adapters for this, the additional indirection is seems unnecessary to me. As only const access is required, the additional accessors seems like a small price to pay.
> Move implementation of WellOperators out of BlackoilWellModel

- opm/simulators/wells/TargetCalculator.cpp
We also want to remove the reservoir rates of other phases for wells under group control.
> use reservoir rates not reduction rate in target calculator for VREP

- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
> Remove unneded capture of 'this'.

- opm/simulators/aquifers/BlackoilAquiferModel.hpp
- opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftSingleWell.hpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellInterface.hpp
- opm/simulators/wells/WellInterface_impl.hpp
> changed: use standard header guard structure for _impl.hpp clangd helpers

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
> BlackoilWellModel: move group switching reporting to separate method

- opm/simulators/wells/MultisegmentWellAssemble.cpp
- opm/simulators/wells/MultisegmentWellAssemble.hpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp
- opm/simulators/wells/MultisegmentWellPrimaryVariables.hpp
- opm/simulators/wells/MultisegmentWellSegments.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWellPrimaryVariables.cpp
just started, nothing essential got done yet.
> gas water for multisegment well

- CMakeLists_files.cmake
- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/BlackoilModelProperties.hpp
Easier overview, more consistent, ...
> BlackoilModel: move properties to separate header

- opm/simulators/flow/NonlinearSolver.cpp
- opm/simulators/flow/NonlinearSolver.hpp
and move some more code to the TU. small tidy up enabled by typetag-less parameters system
> NonlinearSolver::Parameters: move to separate struct

- CMakeLists_files.cmake
- opm/simulators/flow/SimulatorConvergenceOutput.cpp
- opm/simulators/flow/SimulatorConvergenceOutput.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
model using has-a in SimulatorFullyImplicitBlackoil
> SimulatorConvergenceOutput: move to separate class

- python/docstrings_simulators.json
This is a PR to test the automatic rebuilt of the pyhton documentation, to be merged by @atgeirr.
> [Python/docs] Change return type of other _init_ of the BlackOilSimulator class

- opm/models/blackoil/blackoilintensivequantities.hh
This is intended as a starting point for further refactoring of the property system for improved performance and GPU portability. The first problem is that the function is too long to understand the relations between the parts and any order dependencies, that is what I am aiming to improve here.
> Refactor BlackoilIntensiveQuantities::update()

- opm/simulators/wells/FractionCalculator.cpp
- opm/simulators/wells/FractionCalculator.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- regressionTests.cmake
This commit includes several fixes related to supporting NETV guide rates that are zero. Depends on https://github.com/OPM/opm-common/pull/4391
> Fixes related to zero guiderates from NETV

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
> BlackoilWellModel::computeWellTemperature: use if constexpr

- opm/models/discretization/common/fvbaseproblem.hh
- opm/simulators/flow/FlowGenericProblem.hpp
- opm/simulators/flow/FlowGenericProblem_impl.hpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/FlowProblemBlackoil.hpp
- opm/simulators/flow/FlowProblemComp.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
typetag less parameter system now allows us to initialize these variables in class that holds them.
> FlowProblem: move some more code to FlowGenericProblem

- opm/simulators/flow/DamarisWriter.hpp
- opm/simulators/flow/Main.cpp
- opm/simulators/utils/DamarisKeywords.cpp
- opm/simulators/utils/DamarisKeywords.hpp
possible with typetag less parameter system
> Damaris: move some more code to TU

- CMakeLists_files.cmake
- opm/simulators/flow/BlackoilModel.hpp
- opm/simulators/flow/BlackoilModel_impl.hpp
- opm/simulators/flow/Main.hpp
This class has grown large enough to warrant splitting into an impl file.
Since this would basically touch every line anyways, I also opted to re-indent the existing header to drop the indent for namespace.
> BlackoilModel: add impl file

- opm/simulators/flow/Transmissibility.hpp
- opm/simulators/flow/Transmissibility_impl.hpp
The loops repeatedly calls distanceVector which recalculates the centroid for a cell. This is not a trivial calculation
> Transmissibility: add a cache for centroids and use this in update()

- opm/simulators/flow/Transmissibility.hpp
- opm/simulators/flow/Transmissibility_impl.hpp
- fix cosmetics
- simplify method signatures by introducing a struct
- reduce code duplication
> Transmissibility: some janitoring

- tests/run-regressionTest.sh
This adds 'only_summary' in jenkins trigger to allow comparing only .UNSMRY files.
> added: option to only compare summary files in regression tests

- examples/problems/co2injectionproblem.hh
- opm/models/blackoil/blackoildispersionmodule.hh
- opm/models/common/multiphasebaseextensivequantities.hh
- opm/models/common/transfluxmodule.hh
- opm/models/discretization/common/baseauxiliarymodule.hh
- opm/models/discretization/common/fvbaseextensivequantities.hh
- opm/models/discretization/vcfv/p1fegradientcalculator.hh
- opm/models/discretization/vcfv/vcfvstencil.hh
- opm/models/ptflash/flashintensivequantities.hh
- opm/models/pvs/pvsmodel.hh
- opm/simulators/flow/CollectDataOnIORank_impl.hpp
- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
- opm/simulators/flow/Transmissibility_impl.hpp
- opm/simulators/linalg/HyprePreconditioner.hpp
- opm/simulators/linalg/gpubridge/opencl/ChowPatelIlu.cpp
- opm/simulators/linalg/gpubridge/opencl/openclBISAI.cpp
- opm/simulators/linalg/gpubridge/opencl/openclSolverBackend.cpp
- opm/simulators/utils/satfunc/GasPhaseConsistencyChecks.hpp
- opm/simulators/utils/satfunc/OilPhaseConsistencyChecks.hpp
- opm/simulators/utils/satfunc/RelpermDiagnostics.hpp
- opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.hpp
- opm/simulators/utils/satfunc/WaterPhaseConsistencyChecks.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/WellBhpThpCalculator.cpp
- opm/simulators/wells/WellState.cpp
https://github.com/OPM/opm-simulators/commit/ec6cba9e0d33bb311180a359b51aecae1144bc39 is a bit eyebrow-raising but in any case it makes no sense as-is.
> Janitoring: address various static analyzer issues

- opm/simulators/wells/BlackoilWellModelGasLift.cpp
- opm/simulators/wells/BlackoilWellModelGasLift_impl.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface_impl.hpp
Added macros for profiling and investigating gaslift, network and well solves.
> added more timing

- opm/models/io/vtkmultiwriter.hh
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
Addresses fallout from some recent additions.
> Fix compile error and warnings

- opm/simulators/flow/FIBlackoilModel.hpp
Using the simpler syntax provided by ElementChunks.
I have two questions though:
1. Is the details::numThreads() ok? I think at least it is better than having `#ifdef _OPENMP` in the initializer list. Maybe we even should make this tiny function generally available so you can ask for the number of threads without any guards?
2. The `gridIsUnchanging` constexpr bool could be used to avoid constructing element_chunks_, but I am not sure how to achieve that in an initializer list. Would it be a good idea to use the ConditionalStorage class?
> Switch property evaluation to using ElementChunks.

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
Downstream of https://github.com/OPM/opm-common/pull/4455
> GenericOutputBlackoilModule: use EclString from Inplace

- opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
- opm/simulators/linalg/PreconditionerFactory_impl.hpp
> Add Preconditions to Avoid Incorrect Interior Sizes

- opm/models/blackoil/blackoilonephaseindices.hh
- opm/models/blackoil/blackoiltwophaseindices.hh
- opm/simulators/flow/OutputBlackoilModule.hpp
Avoid dereferencing negative indices.
Downstream of https://github.com/OPM/opm-common/pull/4459
> Fix compiler warning in FLOWS code

- CMakeLists.txt
- CMakeLists_files.cmake
- opm/simulators/linalg/gpuistl/gpu_resources.hpp
- tests/gpuistl/test_gpu_resources.cu
This is a collection of convenience functions to deal with the typical CUDA/HIP pattern of create/destroy/use.
> Added utility class to hold a GPU resource (stream, event, graph, etc).

- CMakeLists.txt
- CMakeLists_files.cmake
- opm/simulators/linalg/gpuistl/detail/is_gpu_pointer.hpp
- opm/simulators/linalg/gpuistl/gpu_smart_pointer.hpp
- tests/gpuistl/test_gpu_smart_pointers.cu
- tests/gpuistl/test_is_gpu_pointer.cpp
> Added copy functions from GPU smart pointers

- opm/simulators/linalg/WriteSystemMatrixHelper.hpp
While here, also add wrapper functions for outputting systems of linear equations arising in geo-mechanical applications.
---
Extracted from #5801.
> Add Helper Functions for Outputting Vectors/Matrices Separately

- opm/simulators/flow/FIPContainer.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/MechContainer.cpp
- opm/simulators/flow/MechContainer.hpp
Ref discussion in https://github.com/OPM/opm-simulators/pull/5964
> Fixed: Data output should use move semantics

- CMakeLists_files.cmake
- opm/simulators/flow/FlowProblemBlackoil.hpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
- opm/simulators/flow/MICPContainer.cpp
- opm/simulators/flow/MICPContainer.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
Continuing this encapsulation and separation of concerns journey.
> Add a container for MICP data output

- CMakeLists.txt
- CMakeLists_files.cmake
Closes https://github.com/OPM/opm-simulators/issues/5961
> Fix shared library linking issues

- opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp
- opm/simulators/wells/StandardWellPrimaryVariables.cpp
Draft to see if make primary variables more consistent is good.
> Consistent primary variables

- CMakeLists_files.cmake
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
- opm/simulators/flow/OutputCompositionalModule.hpp
- opm/simulators/flow/TracerContainer.cpp
- opm/simulators/flow/TracerContainer.hpp
This adds a container for tracer data output.
> Add TracerContainer, a container for tracer data output

- opm/simulators/flow/DamarisWriter.hpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
add one accessor for the vector, instead of separate ones for size and data
> remove accessors

- CMakeLists_files.cmake
- opm/simulators/flow/DamarisWriter.hpp
- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
- opm/simulators/flow/RFTContainer.cpp
- opm/simulators/flow/RFTContainer.hpp
> Add RFTContainer, a container for RFT data output

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/OutputBlackoilModule.hpp
- regressionTests.cmake
And some small tidy ups.
Requires https://github.com/OPM/opm-tests/pull/1294
> Add RESIDUAL output to a regression test

- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
Issue found by running spe11a.
> double instead of int

- opm/models/discretization/common/tpfalinearizer.hh
- opm/simulators/flow/FlowsContainer.cpp
- opm/simulators/flow/FlowsContainer.hpp
> Fix Summary BFLOW*

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
avoid raw loop, add const correctness and use fmt
small tidy up
> GenericOutputBlackoilModule: small tidy up

- opm/simulators/flow/FIBlackoilModel.hpp
- opm/simulators/flow/Transmissibility_impl.hpp
Downstream of OPM/opm-grid#842.
> Adapt to ElementChunks now requiring partition argument.

- opm/simulators/utils/SetupPartitioningParams.cpp
This is in preparation of exposing the low-level Zoltan hypergraph parameter `PHG_EDGE_SIZE_THRESHOLD` as a (hidden) simulator command line parameter to enable experimental runtime configuration.
To this end, split parameter assignment out to a number of helper functions and extract a common helper for JSON-based configuration of Zoltan and METIS.
> Refactor Partitioning Parameter Setup

- opm/simulators/flow/FIBlackoilModel.hpp
Some drive-by cosmetics;
1) break long lines
2) add some whitespace
3) cleanup includes
> Fix some cosmetics in FIBlackoilModel

- opm/simulators/flow/TracerModel.hpp
> TracerModel: some janitoring

- opm/simulators/flow/TracerModel.hpp
I mixed up some indices in #6044 
Also add parallel exception handling to tracer equation assembly (which would have caught the issue in a more readable way..)
> Fix parallel tracers

- opm/simulators/linalg/ISTLSolver.hpp
- opm/simulators/utils/satfunc/RelpermDiagnostics.cpp
Removing/adding some line breaks and spaces for cosmetics.
> Improving terminal/dbg output

- opm/simulators/flow/TracerModel.hpp
Gives a significant speedup,
|     Revision     |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|------------------|-------------|--------------|-------------|----------------------:|
|tracer_avoid_alloc|30.69 +- 0.05|24.75 +- 0.04 |52.02 +- 0.05|                   0.01|
|master            |31.42 +- 0.25|25.47 +- 0.17 |52.77 +- 0.46|                       |
|     Revision     |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|------------------|-------------|--------------|-------------|----------------------:|
|tracer_avoid_alloc|30.39 +- 0.15|29.32 +- 0.14 |55.23 +- 0.25|                      0|
|master            |32.60 +- 0.22|31.52 +- 0.22 |57.76 +- 0.18|                       |
Sits on top of https://github.com/OPM/opm-simulators/pull/6061
> Tracer: avoid allocations in inner loop

- opm/simulators/flow/ReservoirCouplingMaster.cpp
- opm/simulators/flow/ReservoirCouplingSpawnSlaves.cpp
- opm/simulators/flow/ReservoirCouplingSpawnSlaves.hpp
Reported to me by @akva2. Thank you.
> Fix unused private variable warning

- opm/simulators/flow/FlowProblemBlackoil.hpp
This PR aims to fix the issue raised in https://github.com/OPM/opm-simulators/issues/6073 (with current master SOIL>0 for the deck in the issue given explicit the initial condition (SGAS=0.7535, SWAT=0.2465)).
> Set SOIL to 0 when readExplicitInitialCondition and 1-SGAS-SWAT=0

- opm/models/blackoil/blackoilbrinemodules.hh
- opm/models/blackoil/blackoilbrineparams.cpp
- opm/simulators/flow/FlowProblem.hpp
- opm/simulators/flow/FlowProblemBlackoil.hpp
Depends on https://github.com/OPM/opm-common/pull/4518
> PERMFACT for each saturation region

- opm/simulators/flow/SimulatorConvergenceOutput.cpp
The original code here used move semantics to transfer ownership, but commit 15cb8757 (PR #5874) switched to using the simpler by-reference semantics instead.  Follow through on this change by not creating an intermediate copy only to move that copy into another object.  Instead, copy only the report objects when creating the output requests.
> Don't Copy Only to Move Result

- opm/simulators/flow/TracerModel.hpp
Note: The timings have been done with #6020 reverted, see #6069. No significant change in runtime.
I did templates but it could potentially be a bit cleaner with lambdas (but those would have to pass the index at runtime).
|      Revision      |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|--------------------|-------------|--------------|-------------|----------------------:|
|tracer_dedupe      |30.34 +- 0.06|24.44 +- 0.04 |51.23 +- 0.07|                   0.78|
|master_6020_reverted|30.37 +- 0.17|24.49 +- 0.11 |51.72 +- 0.33|                       |
|      Revision      |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|--------------------|-------------|--------------|-------------|----------------------:|
|tracer_dedupe      |31.10 +- …
> Tracer: Code deduplication

- opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
To make the message consitent with  changes in 920ad68782
> Added WELL as supported to GCONPROD message for unsupported options

- regressionTests.cmake
> add some macros to avoid repeated code in test registration

- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/GenericOutputBlackoilModule.cpp
- opm/simulators/flow/GenericOutputBlackoilModule.hpp
- opm/simulators/flow/LogOutputHelper.cpp
- opm/simulators/flow/LogOutputHelper.hpp
- tests/test_LogOutputHelper.cpp
This adds the msw report for RPTSCHED WELLS=x 
Mixture velocity is calculated as instructed by @GitPaean 
Downstream of https://github.com/OPM/opm-common/pull/4541
> Add support for MSW PRT report

- regressionTests.cmake
This adds tests for functionality added in #6092
> Added regression tests for WCONINJH and WCONHIST in ACTIONX.

- opm/simulators/flow/BlackoilModelNldd.hpp
- opm/simulators/flow/SubDomain.hpp
- opm/simulators/flow/partitionCells.cpp
- opm/simulators/flow/partitionCells.hpp
- tests/test_partitionCells.cpp
Following up on the final comments from https://github.com/OPM/opm-simulators/pull/6103. See the PR for more details.
> Follow up comments from 6103 (NLDD partitioning)

- opm/simulators/flow/FlowProblemBlackoil.hpp
Depends on https://github.com/OPM/opm-common/pull/4543
> Support for RSW in the SOLUTION section

- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/WellInterface_impl.hpp
With network, we need to set the thp limit from the network.
> Set thp from network in well testing

- tests/test_timer.cpp
Following PR OPM/opm-common#4547, the Schedule object's constructor now needs a `NumericalAquifers` container object in order to extract appropriate property values for well connections in numerical aquifer cells.  Pass a default constructed object here to signify no numerical aquifers in the test.
> Chase Schedule Constructor API Update

- opm/simulators/flow/OutputBlackoilModule.hpp
Removing extra saturation computing BOIPG
> Removing extra saturation computing BOIPG

- opm/simulators/wells/BlackoilWellModelConstraints.cpp
i.e. allow for switching to FLD if item 8 is yes
> BUGIFIX: Only respect item 7 in GCONPROD for individual constrains,

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
somehow confused phases and components
> fixed: wrong order of phases

- opm/simulators/flow/GenericOutputBlackoilModule.cpp
And avoid spurious water outputs
> Fix compositional field output names

- opm/models/io/baseoutputmodule.hh
> Fix typo in function name that broke compiling with gcc-15

- opm/simulators/flow/FlowProblemBlackoil.hpp
Accommodate for the changes made to the SOURCE keyword in https://github.com/OPM/opm-common/pull/4553
> Changes in SOURCE structure

- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
> Fix to 2025.04-r1 build candidate in clang

- opm/simulators/flow/FlowProblemBlackoil.hpp
By testing and reviewing 2025-04-r1, this issue came up, i.e., the `permFactTransMultiplier` was always 1 for MICP. This PR gives the right multiplier (in addition to refactoring the if clauses). This is a bug fix and it should be added to the release (sorry for that).
> Missing permFactTransMultiplier by MICP

- opm/models/utils/simulator.hh
the back ground and discussion can be seen at https://github.com/OPM/opm-simulators/pull/6150 .
> using bigger epislon for Simulator class

- opm/simulators/wells/BlackoilWellModel_impl.hpp
> Backport of pr 6164

- opm/simulators/wells/MultisegmentWell.hpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/ParallelWellInfo.cpp
Address the comments to MultisegmentWell_impl.hpp from: https://github.com/OPM/opm-simulators/pull/5937#pullrequestreview-2626084367
> Refactor calls to broadcast in MultisegmentWell_impl.hpp

- opm/simulators/flow/FlowGenericVanguard.cpp
- opm/simulators/utils/ParallelSerialization.cpp
- tests/test_ParallelSerialization.cpp
Must be included in parallel serialisation.
> Adapt to New ScheduleState Data Member

- flowexperimental/comp/wells/CompositionalWellModel_impl.hpp
Missing license header, add IDE convenience, add missing include, mark variable const.
> CompositionalWellModel: some janitoring

- opm/models/utils/parametersystem.cpp
These exceptions shall be thrown.
> parametersystem: add missing throw's

- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
> fixed: gas and water rates swapped

- opm/models/utils/parametersystem.cpp
Regression tests produce the same results on my machine, all other tests pass. I consider this safe to add to RC3.
> backport of pr 6194

- opm/simulators/wells/MSWellHelpers.cpp
- parallelTests.cmake
Regression tests produce the same results as before, all other tests pass. I consider this safe to add to RC3.
> Backport of pr 6184

- regressionTests.cmake
> pinch: put more cases in multi-registration

- opm/simulators/timestepping/AdaptiveTimeStepping.hpp
- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
Quell some static analyzer issues, add some convenience, fix some headers and rectify some clang-format mess.
> AdaptiveTimeStepping: some janitoring

- regressionTests.cmake
More use of multi registration macros to reduce amount of duplicated code.
> Regression tests: more multi registration

- opm/models/common/multiphasebaseextensivequantities.hh
- opm/models/common/multiphasebasemodel.hh
- opm/models/common/multiphasebaseproblem.hh
- opm/models/common/multiphasebaseproperties.hh
> MultiPhase(Model|Problem|ExtensiveQuantities): some janitoring

- opm/models/common/energymodule.hh
> EnergyModule: some janitoring

- opm/models/common/forchheimerfluxmodule.hh
> ForchheimerFluxModule: some janitoring

- opm/models/parallel/mpibuffer.hh
- opm/models/utils/simulator.hh
Some tidy ups. Also some cleanup in mpibuffer.hh.
> Simulator: some janitoring

- opm/models/discretefracture/discretefractureextensivequantities.hh
- opm/models/discretefracture/discretefractureintensivequantities.hh
- opm/models/discretefracture/discretefracturelocalresidual.hh
- opm/models/discretefracture/discretefracturemodel.hh
- opm/models/discretefracture/discretefractureprimaryvariables.hh
- opm/models/discretefracture/discretefractureproblem.hh
- opm/models/discretefracture/discretefractureproperties.hh
- opm/models/discretefracture/fracturemapper.hh
> DiscreteFracture: some janitoring

- opm/simulators/flow/FIPContainer.cpp
- opm/simulators/flow/FIPContainer.hpp
- opm/simulators/flow/LogOutputHelper.cpp
- opm/simulators/flow/OutputBlackoilModule.hpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/PerfData.cpp
- opm/simulators/wells/PerfData.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellState.cpp
Depends on https://github.com/OPM/opm-common/pull/4569
> Summary vectors for water mass

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- tests/test_glift1.cpp
Motivation is both cleanup and to allow for https://github.com/OPM/opm-simulators/pull/5933
> Split network and group update code

- opm/simulators/flow/NlddReporting.cpp
- opm/simulators/flow/NlddReporting.hpp
Avoid some duplication, move some more code to TU.
> NlddReporting: some minor refactoring

- opm/models/utils/simulator.hh
- opm/simulators/flow/CpGridVanguard.hpp
- opm/simulators/flow/FlowBaseVanguard.hpp
By updating the grid view, cell depth and thickness. 
Not relevant for the Reference Manual.
> Reduce discontinuities in serial simulation for CpGrid with LGRs

- opm/simulators/wells/WellState.cpp
Instead of throwing inside the loop over all wells, collect the findings and throw at the end. Throwing inside of the loop over all wells leads to a deadlock in some cases:
Without these changes, the following command locks with the current master:
`mpirun -np 4 ./bin/flow_distribute_z ../../opm-tests/msw/MSW-SIMPLE-5-SHUT-PERFORATIONS.DATA`
This PR also solves the deadlock that happens when adding more MS Wells to the above case, like:
```
Load balancing distributed the wells as follows:
well name            ranks with perforated cells
---------------------------------------------------
PROD1       0       1
PROD2       0       1       2
PROD3       0       1       2
```
as explained in https://github.com/OPM/opm-simulators/pull/6244#discussion_r2079120699.
Not relevant for the reference …
> Move throws inside the loop over all wells to after the end of the loop

- opm/models/discretization/common/baseauxiliarymodule.hh
- opm/models/discretization/common/fvbaseadlocallinearizer.hh
Some janitoring in this class. Includes, avoid raw pointers, cosmetics, ...
> FvBaseAdLocalLinearizer: some janitoring

- opm/models/discretization/common/fvbaseboundarycontext.hh
- opm/models/discretization/common/fvbaseconstraints.hh
- opm/models/discretization/common/fvbaseconstraintscontext.hh
> FvBase(BoundaryContext|Constraints): some janitoring

- opm/models/common/diffusionmodule.hh
> DiffusionModule: some janitoring

- opm/models/common/darcyfluxmodule.hh
> DarcyFluxModule: some janitoring

- opm/models/blackoil/blackoilenergymodules.hh
- opm/models/blackoil/blackoilmicpmodules.hh
- opm/models/blackoil/blackoilmodel.hh
- opm/models/blackoil/blackoilpolymermodules.hh
- opm/models/blackoil/blackoilsolventmodules.hh
- opm/models/common/multiphasebasemodel.hh
- opm/models/discretefracture/discretefracturemodel.hh
- opm/models/discretization/common/fvbasediscretization.hh
- opm/models/discretization/common/fvbasediscretizationfemadapt.hh
- opm/models/flash/flashmodel.hh
- opm/models/immiscible/immisciblemodel.hh
- opm/models/ncp/ncpmodel.hh
- opm/models/ptflash/flashmodel.hh
- opm/models/pvs/pvsmodel.hh
- opm/simulators/flow/FlowProblemBlackoil.hpp
> FvBaseDiscretization(FemAdapt): Some janitoring

- opm/models/discretization/common/fvbaseelementcontext.hh
> FvBaseElementContext: some janitoring

- CMakeLists_files.cmake
- opm/simulators/utils/ComponentName.cpp
- opm/simulators/utils/InstantiationIndicesMacros.hpp
- opm/simulators/wells/MultisegmentWellAssemble.cpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp
- opm/simulators/wells/MultisegmentWellSegments.cpp
- opm/simulators/wells/StandardWellAssemble.cpp
- opm/simulators/wells/StandardWellConnections.cpp
- opm/simulators/wells/StandardWellEval.cpp
- opm/simulators/wells/StandardWellPrimaryVariables.cpp
- opm/simulators/wells/WellInterfaceIndices.cpp
There are some different orders and numbers, it causes confusion when modifying. 
With the first commit of this PR, they are all made the same, so hopefully, it is easier. 
In the second commit, I put the macro definition in a file, while I think the approach might need refinement.
> unifying instantiation of variants related to Indices

- opm/models/discretization/common/fvbaseextensivequantities.hh
- opm/models/discretization/common/fvbasefdlocallinearizer.hh
> FvBase(ExtensiveQuantites|FdLocalLinearizer): some janitoring

- opm/models/discretization/common/fvbasegradientcalculator.hh
- opm/models/discretization/common/fvbaseintensivequantities.hh
> FvBase(IntensiveQuantities|GradientCalculator): some janitoring

- opm/models/discretization/common/fvbaselocalresidual.hh
- opm/models/discretization/common/fvbasenewtonconvergencewriter.hh
- opm/models/discretization/common/fvbasenewtonmethod.hh
- opm/models/discretization/common/fvbaseprimaryvariables.hh
> FvBase(LocalResidual|NewtonConvergenceWriter|NewtonMethod|PrimaryVariables): some janitoring

- opm/models/discretization/common/fvbaseproblem.hh
> FvBaseProblem: some janitoring

- opm/models/discretization/common/linearizationtype.hh
- opm/models/discretization/common/restrictprolong.hh
- opm/models/discretization/common/tpfalinearizer.hh
Some tidy ups
Also some cosmetics in RestrictProlong and Linearization type
> TpfaLinearizer: some janitoring

- opm/models/discretization/ecfv/ecfvbaseoutputmodule.hh
- opm/models/discretization/ecfv/ecfvdiscretization.hh
- opm/models/discretization/ecfv/ecfvgridcommhandlefactory.hh
- opm/models/discretization/ecfv/ecfvstencil.hh
> ECFV classes: some janitoring

- opm/models/blackoil/blackoilboundaryratevector.hh
- opm/models/blackoil/blackoilbrinemodules.hh
- opm/models/blackoil/blackoilconvectivemixingmodule.hh
- opm/models/blackoil/blackoildarcyfluxmodule.hh
- opm/models/blackoil/blackoildiffusionmodule.hh
- opm/models/blackoil/blackoildispersionmodule.hh
- opm/models/blackoil/blackoilenergymodules.hh
- opm/models/blackoil/blackoilextbomodules.hh
- opm/models/blackoil/blackoilfoammodules.hh
Some tidy ups. Splitting it up a little to make reviews bearable..
> BlackoilModel: some janitoring

- opm/models/blackoil/blackoilintensivequantities.hh
- opm/models/blackoil/blackoillocalresidual.hh
- opm/models/blackoil/blackoillocalresidualtpfa.hh
- opm/models/blackoil/blackoilmicpmodules.hh
- opm/models/blackoil/blackoilmodel.hh
- opm/models/blackoil/blackoilnewtonmethod.hpp
- opm/models/blackoil/blackoilpolymermodules.hh
- opm/models/blackoil/blackoilprimaryvariables.hh
- opm/models/blackoil/blackoilproblem.hh
- opm/models/blackoil/blackoilproperties.hh
- opm/models/blackoil/blackoilratevector.hh
- opm/models/blackoil/blackoilsolventmodules.hh
> BlackOilModel: janitoring part2

- opm/models/flash/flashboundaryratevector.hh
- opm/models/flash/flashintensivequantities.hh
- opm/models/flash/flashlocalresidual.hh
- opm/models/flash/flashmodel.hh
- opm/models/flash/flashprimaryvariables.hh
- opm/models/flash/flashratevector.hh
> FlashModel: Some janitoring

- opm/models/ncp/ncpboundaryratevector.hh
- opm/models/ncp/ncpextensivequantities.hh
- opm/models/ncp/ncpindices.hh
- opm/models/ncp/ncpintensivequantities.hh
- opm/models/ncp/ncplocalresidual.hh
- opm/models/ncp/ncpmodel.hh
- opm/models/ncp/ncpnewtonmethod.hh
- opm/models/ncp/ncpprimaryvariables.hh
- opm/models/ncp/ncpproperties.hh
- opm/models/ncp/ncpratevector.hh
> NcpModel: Some janitoring

- opm/models/nonlinear/newtonmethod.hh
- opm/models/parallel/gridcommhandles.hh
- opm/models/parallel/mpibuffer.hh
- opm/models/parallel/tasklets.cpp
- opm/models/parallel/tasklets.hpp
- opm/models/parallel/threadedentityiterator.hh
> models/Utils: Some janitoring

- opm/simulators/utils/readDeck.cpp
This PR pulls the `baseName` out of the file removal regular expression since it's a user-controlled string that might happen to contain regular expression metacharacters like `'+'` or `'-'`.  In rare corner cases, those characters might lead to matching too many or not enough files, thus making `prepareResultOutputDirectory()` too fragile.
This PR therefore switches to using regular string matching for the `baseName`, and only for regular files&ndash;i.e., symbolic links and directories are omitted from consideration.  We also, as an extra special case, exempt grid files from file removal since it's not entirely impossible for `CASE.DATA` to use `CASE.EGRID` as an input file (`GDFILE` keyword).
> Allow For Regex Metacharacters in Case Name During File Removal

- opm/models/ptflash/flashindices.hh
- opm/models/ptflash/flashintensivequantities.hh
- opm/models/ptflash/flashlocalresidual.hh
- opm/models/ptflash/flashmodel.hh
- opm/models/ptflash/flashnewtonmethod.hh
- opm/models/ptflash/flashprimaryvariables.hh
> Ptflash model: some janitoring

- opm/models/pvs/pvsboundaryratevector.hh
- opm/models/pvs/pvsextensivequantities.hh
- opm/models/pvs/pvsindices.hh
- opm/models/pvs/pvsintensivequantities.hh
- opm/models/pvs/pvslocalresidual.hh
- opm/models/pvs/pvsmodel.hh
- opm/models/pvs/pvsnewtonmethod.hh
- opm/models/pvs/pvsprimaryvariables.hh
- opm/models/pvs/pvsproperties.hh
- opm/models/pvs/pvsratevector.hh
> Pvs model: Some janitoring

- opm/simulators/wells/ALQState.cpp
- opm/simulators/wells/ALQState.hpp
- opm/simulators/wells/BlackoilWellModelGasLift.cpp
- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/GasLiftCommon.cpp
- opm/simulators/wells/GasLiftCommon.hpp
- opm/simulators/wells/GasLiftGroupInfo.cpp
- opm/simulators/wells/GasLiftSingleWellGeneric.cpp
- opm/simulators/wells/GasLiftSingleWell_impl.hpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellGroupHelpers.hpp
- opm/simulators/wells/WellInterfaceGeneric.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellState.hpp
- tests/test_ALQState.cpp
First step to facilitate #6245
> move alq_state to singleWellState

- opm/simulators/flow/ActionHandler.cpp
Downstream of https://github.com/OPM/opm-common/pull/4624
> adjust to upstream API change

- opm/simulators/flow/EclWriter.hpp
- opm/simulators/flow/LogOutputHelper.cpp
- opm/simulators/flow/LogOutputHelper.hpp
- opm/simulators/flow/OutputBlackoilModule.hpp
Add output of region data to additional CSV file. This should be controlled with keyword RPTSOL.
```
RPTSOL
'CSVFIP'  /
```
> Add CSV output of FIP and RESV data

- opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
> [BUG] TSMINZ instead of TSFMIN

- opm/simulators/flow/FlowProblemBlackoil.hpp
Downstream from https://github.com/OPM/opm-common/pull/4650.
> Remove unneeded setPc() call.

- opm/simulators/linalg/gpubridge/CprCreation.cpp
- opm/simulators/linalg/gpubridge/CprCreation.hpp
- opm/simulators/linalg/gpubridge/GpuBridge.cpp
- opm/simulators/linalg/gpubridge/Misc.hpp
- opm/simulators/linalg/gpubridge/MultisegmentWellContribution.cpp
- opm/simulators/linalg/gpubridge/Preconditioner.hpp
- opm/simulators/linalg/gpubridge/opencl/openclBILU0.cpp
- opm/simulators/linalg/gpubridge/opencl/openclBILU0.hpp
- opm/simulators/linalg/gpubridge/opencl/openclBISAI.cpp
- opm/simulators/linalg/gpubridge/opencl/openclBISAI.hpp
- opm/simulators/linalg/gpubridge/opencl/openclCPR.cpp
- opm/simulators/linalg/gpubridge/opencl/openclCPR.hpp
- opm/simulators/linalg/gpubridge/opencl/openclPreconditioner.hpp
- opm/simulators/linalg/gpubridge/opencl/openclSolverBackend.cpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseBILU0.cpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseBILU0.hpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseCPR.cpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseCPR.hpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseMatrix.cpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseMatrix.hpp
- opm/simulators/linalg/gpubridge/rocm/rocsparsePreconditioner.cpp
- opm/simulators/linalg/gpubridge/rocm/rocsparsePreconditioner.hpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseSolverBackend.cpp
- opm/simulators/linalg/gpubridge/rocm/rocsparseSolverBackend.hpp
This PR fixes several bug issues including a memory leakage causing a segmentation fault for a bigger model and updates the rocsparse based CPR implementation to be on par with OPM default CPR implementation.
> rocsparseCPR update incl bug fixes

- regressionTests.cmake
to make it a more robustness regression test.
referring to https://github.com/OPM/opm-common/pull/4668#issuecomment-3183024121.
> enable tuning for network_01_wtest

- opm/simulators/flow/equil/EquilibrationHelpers_impl.hpp
* Update handling of depth=contact to correspond to reference (use fluid at and above in this case)
> Update handling of depth=contact to use topmost fluid

- opm/simulators/wells/BlackoilWellModelGeneric.cpp
- opm/simulators/wells/GuideRateHandler.cpp
- opm/simulators/wells/MultisegmentWell_impl.hpp
- opm/simulators/wells/StandardWell_impl.hpp
- opm/simulators/wells/WellGroupHelpers.cpp
- opm/simulators/wells/WellInterface_impl.hpp
- opm/simulators/wells/WellState.cpp
Related to https://github.com/OPM/opm-simulators/pull/6050
> Check status from wellstate not the well object from Schedule

- examples/art2dgf.cpp
- opm/models/blackoil/blackoilpolymerparams.cpp
- opm/simulators/flow/SimulatorSerializer.cpp
- opm/simulators/wells/BlackoilWellModelGasLift_impl.hpp
- opm/simulators/wells/GasLiftCommon.cpp
- opm/simulators/wells/GasLiftStage2.cpp
- opm/simulators/wells/MultisegmentWellEval.cpp
- opm/simulators/wells/VFPHelpers.cpp
- opm/simulators/wells/WellBhpThpCalculator.cpp
The self assignment was traced back to the original commit.
> Janitoring: quell some SCA warnings

- opm/simulators/linalg/gpuistl/GpuSparseMatrixGeneric.cpp
Follow up from #6401 to make sure we support earlier CUDA versions.
Note that in its current use, `GpuSparseMatrixGenric` is only used as a backend in `GpuSparseMatrix` when the block size is 1. So the `cusparseCreateBsr` which requires CUDA version >= 12.3 is not being used, since this is only needed when the block size is greater than 1. In other words, things will still work with older CUDA versions.
The `cusparseSpMV_preprocess` is only an optimisation that can give faster matrix-vector operations, so we still have full support even for CUDA versions older than 12.4.
> Add CUDA version checks for GpuSparseMatrixGeneric

- opm/models/blackoil/blackoilintensivequantities.hh
Downstream from https://github.com/OPM/opm-common/pull/4674 (required for first commit).
> Faster pvt

- opm/simulators/flow/FlowGenericVanguard.cpp
- opm/simulators/utils/ParallelSerialization.cpp
- tests/test_ParallelSerialization.cpp
Chases introduction of new `ScheduleState` data member in OPM/opm-common#4700.  The two PRs must be reviewed and merged in concert.
> Serialise Satellite Injection Rates in Parallel

- pyactionActionXComparisons.cmake
This test was missing among other, but it contrast to the others it already works with master.
> Test WEFAC with PyAction in parallel

- opm/models/blackoil/blackoilprimaryvariables.hh
It is something noticed when working on other development.  Since they are not used, it is good to remove them from the file.
> some cleaning up in blackoilprimaryvariables

- opm/simulators/wells/MultisegmentWellSegments.cpp
depending on https://github.com/OPM/opm-common/pull/4736
> incorporating the item 22 of WSEGAICD

- opm/simulators/wells/BlackoilWellModel.hpp
- opm/simulators/wells/BlackoilWellModel_impl.hpp
- opm/simulators/wells/SingleWellState.cpp
- opm/simulators/wells/SingleWellState.hpp
- opm/simulators/wells/WellState.cpp
- opm/simulators/wells/WellTest.cpp
- regressionTests.cmake
Add support for item 9 in WECON
Depends on https://github.com/OPM/opm-common/pull/4507
> Support opening of following-on well

- opm/simulators/wells/WellInterface_impl.hpp
> Avoid ending up as GRUP when oscillating

- opm/simulators/utils/readDeck.cpp
Only surface rates are allowed to be assigned to satellite production/injection groups. If groups above satellite groups have RESV/VREP-control, the treatment of satellite rates become somewhat ambigous, so we don't want to allow for this situation.
This PR adds a check after deck is read and throws if the schedule shows that the situation above will/can occur (rather than at the time it occurs during simulation). Not sure it's the right place, let me know if it's better suited somewhere else.
> Add check to disallow RESV/VREP-control for groups having satellite sub-groups
