opm/simulators/utils/ParallelSerialization.cpp, opm/simulators/wells/BlackoilWellModelRestart.cpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWellEquations.cpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellGeneric.cpp, opm/simulators/wells/MultisegmentWellGeneric.hpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/WellState.cpp, tests/test_ParallelSerialization.cpp, tests/test_wellstate.cpp
And avoid includes WellSegments.hpp in simulator objects.
Downstream of https://github.com/OPM/opm-common/pull/3344
=> add missing WellSegments.hpp includes

ebos/ecloutputblackoilmodule.hh, ebos/equil/initstateequil.hh, opm/simulators/flow/BlackoilModelEbos.hpp, opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell_impl.hpp
Remove some unnecessary includes and add some includes where symbols from the header is actually used.
Required by https://github.com/OPM/opm-common/pull/3360
=> Units.hpp: some cleanup

opm/simulators/linalg/bda/BdaSolver.hpp, opm/simulators/linalg/bda/amgclSolverBackend.cpp, opm/simulators/linalg/bda/amgclSolverBackend.hpp
Suppresses warnings about unused arguments.  While here, also split a long line for readability.
=> Tag Unused Parameter as [[maybe_unused]]

opm/simulators/flow/Main.hpp
Reduce hotness of ArrayDimChecker.hpp by 88% (29 files, 4 files instead of 33)
=> Main.hpp: remove unnecessary ArrayDimChecker.hpp include

opm/simulators/flow/Main.hpp
Reduce hotness of Parser.hpp by 13% (29 files, 186 files instead of 215)
=> Main.hpp: remove unneccesary Parser.hpp include

ebos/eclgenericvanguard.cc, opm/simulators/flow/Main.hpp, opm/simulators/utils/readDeck.cpp, opm/simulators/utils/readDeck.hpp
Reduce hotness of ParseContext.hpp by 33% (31 files, 62 files instead of 93)
=> Main.hpp: avoid ParseContext.hpp include

ebos/eclgenerictracermodel.cc, opm/simulators/wells/GasLiftGroupInfo.hpp
And forward in GasLiftGroupInfo.hpp (latter not yet of any value)
Required by https://github.com/OPM/opm-grid/pull/618
=> eclgenerictracermodel.cc: add missing Well.hpp include

CMakeLists_files.cmake, opm/simulators/flow/FlowMainEbos.hpp, opm/simulators/flow/Main.cpp, opm/simulators/flow/Main.hpp
Reduce hotness of Python.hpp by 26% (27 files, 78 instead of 105)
Reduce hotness of UDQState.hpp by 60% (30 files, 20 instead of 50)
Reduce hotness of State.hpp by 48% (29 files, 31 instead of 60)
=> Main: introduce a compile unit

ebos/eclgenericwriter.cc
Required by https://github.com/OPM/opm-common/pull/3374
=> eclgenericwriter.cc: add missing PAvgCalculatorCollection.hpp include

opm/simulators/utils/UnsupportedFlowKeywords.cpp
=> Remove CPR from UnsupportedFlowKeywords.cpp

opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/TargetCalculator.cpp, opm/simulators/wells/TargetCalculator.hpp, opm/simulators/wells/WellAssemble.cpp, opm/simulators/wells/WellGroupControls.cpp, opm/simulators/wells/WellGroupControls.hpp, opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellGroupHelpers.hpp, opm/simulators/wells/WellInterfaceFluidSystem.cpp, opm/simulators/wells/WellInterfaceFluidSystem.hpp, opm/simulators/wells/WellInterface_impl.hpp
If GPMAINT is used the group does not need a valid control object. 
See issue reported in https://github.com/OPM/opm-tests/pull/881
=> Fix GPMAINT for groups without control

opm/simulators/wells/WellConstraints.cpp
when checking the THP constraint for producers.
With the master branch, if we default the THP constraint in WCONPROD, the THP constraint will be skipped when checking well constraints because it does not exist in `WellProductionControls`.
=> making sure to check the network nodal pressure constraint

opm/simulators/utils/ParallelRestart.cpp
micro optimization, there is no reason to do this in two operations
=> ParallelRestart: use variadic broadcast

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
- include required headers
- using instead of typedef
- no reason to initialize string with ""
=> AdaptiveTimeSteppingEbos: some cleanups

opm/simulators/timestepping/SimulatorReport.cpp, opm/simulators/timestepping/SimulatorReport.hpp
- avoid explicit ctor by using in-class initialization
- avoid explicit ostringstream
=> SimulatorReportSingle: some cleanups

ebos/eclgenericvanguard.cc, ebos/eclgenericvanguard.hh, opm/simulators/flow/Main.cpp
setParams is a rather generic method name, be more specific
=> EclGenericVanguard: rename setParams to defineSimulationModel

CMakeLists_files.cmake, opm/simulators/timestepping/SimulatorTimer.cpp, opm/simulators/timestepping/SimulatorTimer.hpp, opm/simulators/utils/SerializationPackers.cpp, opm/simulators/utils/SerializationPackers.hpp, tests/test_RestartSerialization.cpp, tests/test_timer.cpp
Downstream of https://github.com/OPM/opm-common/pull/3383
The timer state needs to be serialized for "perfect" restarts.
=> SimulatorTimer: add serialization support

ebos/eclgenericvanguard.cc, ebos/eclgenericvanguard.hh, opm/simulators/flow/Main.cpp
this is a struct that holds the information transferred from the simulator prior to vanguard instantation. this way we can avoid the static members for state, which causes issues for serialization (in particular, it makes it impossible to compare two instances like we do in tests).
=> changed: introduce EclGenericVanguard::SetupParams

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp, opm/simulators/timestepping/TimeStepControl.cpp, opm/simulators/timestepping/TimeStepControl.hpp, tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-simulators/pull/4416
Required for "perfect" restart.
=> AdaptiveTimeSteppingEbos: add serialization support

CMakeLists_files.cmake, ebos/hdf5serializer.hh, opm/simulators/utils/HDF5File.cpp, opm/simulators/utils/HDF5File.hpp, tests/test_HDF5File.cpp, tests/test_HDF5Serializer.cpp
this takes the serialization data and stores it in a hdf5 file,  alternatively reads the data and deserializes.
will be used for restarting purposes.
Downstream of https://github.com/OPM/opm-common/pull/3383
=> added: HDF5 serializer

tests/test_RestartSerialization.cpp
Sits on top of https://github.com/OPM/opm-models/pull/780
For restart.
=> BlockVectorWrapper: add serialization test

opm/simulators/linalg/ParallelOverlappingILU0.hpp, opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp
When the matrix already exists and has the correct sparsity structure (which is assumed by the calling update()), we can copy just the data, avoiding the need for allocation and matrix construction.
This speeds up the linear solver setup part for ILU0 by approximately 15% in my tests (17.2s -> 14.5s for this part on Norne with default parameters and 8 processes).
=> Avoid copying the matrix in the ILU preconditioner.

tests/test_RestartSerialization.cpp
Taking dune-fem into account. Maybe we should undo the "different grid view class when using dune-fem" bit?
=> Fix link and runtime errors when HAVE_DUNE_FEM is true.

examples/opmrst_inspect.cpp, opm/simulators/utils/HDF5File.cpp, tests/test_HDF5File.cpp, tests/test_HDF5Serializer.cpp
Include requisite headers and avoid "most vexing parse" problems.
Follow-up to #4466, but work in progress.
=> Fix Sequential Build

opm/simulators/wells/MultisegmentWell_impl.hpp
Fixing connection pressure output for the MSW model (currently the grid block pressures corrected to perforation depth is output instead).
=> Fixing MSW connection pressure output

opm/simulators/wells/PerfData.cpp, opm/simulators/wells/PerfData.hpp, opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/SingleWellState.hpp, tests/test_RestartSerialization.cpp
Turns out that while perfdata is recreated for the current well state, it is not so for the previous ones. Thus we have to serialize this in order to have it available for the previous well state upon restart.
=> RestartSerialization: add missing PerfData

CMakeLists.txt
We rely on parallel hdf5 for a parallel build of OPM flow. Otherwise compilation will fail. Hence if this is a parallel build but only a serial hdf5 library is found, we now issue an informative warning and deactivate hdf5/parallel restart.
Closes OPM/opm-common#3405
=> [fix] For parallel build with serial hdf5 issue warning and skip hdf5.

ebos/eclgenericoutputblackoilmodule.cc, ebos/ecloutputblackoilmodule.hh
These are summary output that is used for CO2STORE simulations.
Depends on OPM/opm-common#3408
=> WIP add WCD, GCDI, GCDM, WIPG, WIPL summary for F and R

opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
Downstream of https://github.com/OPM/opm-common/pull/3415
=> fixed: mixed-up input and output paths for restart serialization

CMakeLists.txt, flow/flow_ebos_gaswater_energy.cpp, flow/flow_ebos_gaswater_energy.hpp, flow/flow_gaswater_energy.cpp, opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/StandardWellAssemble.cpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/WellInterfaceIndices.cpp
Needed in order to run https://github.com/OPM/opm-tests/pull/903
The plan is to add it to the flow executable after some more testing, but the stand alone simulator should be merged first.
=> Add gaswater energy simulator

opm/simulators/utils/HDF5File.cpp, opm/simulators/utils/HDF5File.hpp
I am keeping this in draft state, but I want to open so we can discuss a little.
Enabling gzip compression (level 9 - the highest compression effort) brings a serialized Norne state down from 43MB to 6.5MB, so there is certainly merit to this.
However, obviously compression eats cpu time, and doing this on the simulator thread will stall the simulator for seconds.
So I have 3 questions;
1) Should we enable this (i think yes).
2) Should we make it configurable (I think maybe not).
3) Should I put effort into moving the compression and storage onto a work thread, akin to the convergence output stuff?
=> HDF5File: enable gzip compression

opm/simulators/flow/Banners.cpp, opm/simulators/flow/Banners.hpp, opm/simulators/flow/Main.cpp, opm/simulators/flow/Main.hpp
we want to avoid these symbols in the library.
fixes shared linking.
this might seem a bit backwards, but thing is, if we put these in the library, every time you reconfigure, every binary is rebuilt because of the compile timestamp / module revision changing.
=> changed: pass the version info as parameters in Banners.cpp/Main.cpp

opm/simulators/timestepping/SimulatorReport.cpp
Admittedly a very minor niggle, but running a small model I got
```
Number of MPI processes:         1
Threads per MPI process:         2
Total time (seconds):            0.01 
Solver time (seconds):           0.01 
Assembly time (seconds):        0.00 (Failed: 0.0; 0.0%)
Well assembly (seconds):      0.00 (Failed: 0.0; -nan%)
Linear solve time (seconds):    0.00 (Failed: 0.0; 0.0%)
Linear setup (seconds):       0.00 (Failed: 0.0; 0.0%)
Update time (seconds):          0.00 (Failed: 0.0; 0.0%)
Pre/post step (seconds):        0.00 (Failed: 0.0; 0.0%)
Output write time (seconds):    0.00
Overall Linearizations:          3    (Failed:   0; 0.0%)
Overall Newton Iterations:       2    (Failed:   0; 0.0%)
Overall Linear Iterations:       0    (Failed:   0; -nan%)
```
now we get zeros.
=> SimulatorReport: protect against division by zero

tests/update_reference_data.sh
Missed this when merging material into common.
=> fixed: remove opm-material from data update script

opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellAssemble.cpp, opm/simulators/wells/StandardWellAssemble.hpp, opm/simulators/wells/StandardWell_impl.hpp
During the refactoring of other well part, this confusing code showed up again. 
We tried to do something in the opposite way in another old PR https://github.com/OPM/opm-simulators/pull/4183,  while this PR should be the more correct direction to go. 
Referring to the discussion in the PR https://github.com/OPM/opm-simulators/pull/4183, especially the following comment. 
https://github.com/OPM/opm-simulators/pull/4183#issuecomment-1303071931
=> make sure computeWellRatesWithBhpIterations honor bhp limit (can change) for StandardWell

ebos/equil/initstateequil.cc
Otherwise one may have link problems on clang systems, the reason for this is not quite clear.
=> Add explicit instantiation of cellZMinMax().

CMakeLists.txt
Whadya know. I tested sibling builds and now I understand why people got in trouble with the hdf5 library selection.
Did not see this locally because I use the super-build. Did not see this on jenkins because it explicitly sets USE_MPI in its toolchain file.
=> fixed: wrong order of OpmInit and use of the USE_MPI option

opm/simulators/aquifers/AquiferConstantFlux.hpp, opm/simulators/aquifers/BlackoilAquiferModel.hpp, opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp, tests/test_RestartSerialization.cpp
In particular, split the 'static' aquifer object initialisation of member function `init()` into a new helper function
```
initializeStaticAquifers()
```
This is in preparation of adding a similar function to handle dynamic aquifer object initialisation from a restart file.  To that end, also add a new member function
```
createDynamicAquifers(episode_index)
```
containing the current implementation of `beginEpisode()`.  Creating the dynamic objects from a restart file then amounts to calling this function with a different 'episode_index'.  As another aid to maintainability, add a new templated member function
```
createAnalyticAquiferPointer()
```
which forms `unique_ptr<AquiferInterface>` objects for every known type of analytic aquifer.  This, in turn, requires reordering the …
=> Refactor Construction of Analytic Aquifer Objects

opm/core/props/BlackoilPhases.hpp
We need to make sure that all pods are initialzed when using the default constructor. Fixes
```
RateConverter.hpp:83:50: warning: ‘phaseUsage’ may be used uninitialized in this function [-Wmaybe-uninitialized]
83 |                 , attr_      (rmap_, Attributes())
|                                                  ^
```
=> [cleanup] Fix that phaseUsage might be used uninitialzed in test.

opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/StandardWellAssemble.cpp, opm/simulators/wells/WellAssemble.cpp, opm/simulators/wells/WellAssemble.hpp
This is a bit broader than OPM/opm-common#3430, in that it targets not just WCONHIST-induced situations. It works, but gives slightly different results than the other PR on the Norne case. Why is not clear to me.
=> Treat rate control with zero target same as stopped well.

opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
This commit fixes the current broken built with clang 
```
/Users/dmar/Github/opm/opm-simulators/opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp:273:47: error: reference to local binding 'id' declared in enclosing function 'Opm::BlackoilAquiferModel<Opm::Properties::TTag::EclFlowProblemWaterOnlyEnergy>::createDynamicAquifers'
return aquPtr->aquiferID() == id;
```
=> fix to broken built with clang

ebos/eclgenericoutputblackoilmodule.cc, ebos/ecloutputblackoilmodule.hh
Mostly to split long lines and to add a few blank lines for readability.  While here, also apply 'const' in a few locations and flip the order of a conditional to (potentially) save a bit of work.
This is in preparation of revising the output destination categories of numerous 3D result vectors.
=> Adjust Whitespace in Output Module

opm/simulators/utils/HDF5File.cpp
seems to be broken (in particular 1.8.12 on rh7)
=> changed: disable HDF5 compression with hdf5 <= 1.8

ebos/ecloutputblackoilmodule.hh
An alternative is to change this to for all water + gas cases not only when CO2STORE is used.
=> output average pressure in all cells unconditionally with co2store

ebos/FIBlackOilModel.hpp, ebos/eclproblem.hh, opm/simulators/aquifers/AquiferAnalytical.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface_impl.hpp
Added explicit call to intensive quantities to make it possible to run the code with calculation the property on the fly.
It also add better checking and error messages, if wrong options or logical errors in the code.
=> Avoid cache

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellAssemble.cpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWellPrimaryVariables.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellAssemble.cpp, opm/simulators/wells/WellAssemble.hpp, opm/simulators/wells/WellHelpers.cpp, opm/simulators/wells/WellHelpers.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
We want to make sure the simulated well rates will be `0` for zero rate constrained wells or STOPped wells . With master branch, we might obtain small well rates values for those wells, which might make problem for the output of ratios. 
```
-- Days   dd/mm/yyyy         WMCTL:B-1H        WOPR:B-1H        WWPR:B-1H        WWCT:B-1H 
2822.00   29/07/2005                  0      4.46914e-30      2.74773e-30         0.380737 
```
Although numerically correct, while it might cause a spurious well ratios (WGOR or WWCT) plots.
In this PR, what we do is that we make sure the primary variable related to total rate will be initialized to be `0`. It turns out to be sufficient.
=> making sure zero rate controlled production wells have zero rate in the simulation results

ebos/eclgenericoutputblackoilmodule.cc
The `base` arrays are compatible in both name and interpretation to those emitted in the `SOLUTION` section from other simulators whereas the `extended` arrays are specific to Flow.  Tag extended arrays as `OPM_EXTENDED` instead of `AUXILIARY` as the latter is deprecated and will be removed at some point in the future.
While here, also re-tag the `TEMP` array as `OPM_EXTENDED` when not required for thermal simulations and add support for the per-phase fluid density `RPTRST` request keys (`DENx`, with `x` being `O`, `G`, or `W`) in addition to the collective key `DEN` that we already support.
=> Split 3D Vectors into Base and Extended Categories

opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellAssemble.cpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellEval.hpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWellPrimaryVariables.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellBhpThpCalculator.cpp, opm/simulators/wells/WellBhpThpCalculator.hpp, opm/simulators/wells/WellHelpers.cpp, opm/simulators/wells/WellHelpers.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterfaceGeneric.cpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellInterface_impl.hpp
From some reference output, it shows that under zero rate control, the output of the THP will always be zero, which is the main focus of this PR. 
At the same time, the first commit complement the PR https://github.com/OPM/opm-simulators/pull/4518 ,  including the injectors with zero rate control in the same category (zero rate control), hoping to make the logic simpler by avoiding distinguishing injector and producers. 
So far, from some reference output, it looks like the wells under zero rate control behave more or less like a well with STOP status and the main difference might be the output for WMCTL (well set with STOP will output WMCTL 0, zero rate controlled wells with OPEN status will output WMCTL corresponding to the rate control type). But not sure when coming to SHUT well due …
=> for the wells under zero rate target control, the THP output will be zero 

opm/simulators/wells/GasLiftSingleWell.hpp, opm/simulators/wells/GasLiftSingleWellGeneric.cpp, opm/simulators/wells/GasLiftSingleWellGeneric.hpp, opm/simulators/wells/GasLiftSingleWell_impl.hpp, opm/simulators/wells/GasLiftStage2.cpp, opm/simulators/wells/GasLiftStage2.hpp
Fixes a bug in `recalculateGradientAndUpdateData_()` in gaslift stage 2. Also adds some minor improvement to the formatting of gaslift debugging output.
=> Fix bug when recalculating gaslift gradient

opm/simulators/linalg/FlexibleSolver_impl.hpp
the compilation mistake was introduced in https://github.com/OPM/opm-simulators/pull/4564
=> removing extra bracket to restore compilation

opm/simulators/wells/StandardWell_impl.hpp
It fixes a reported issue regarding shutting injectors.
=> checking Producer or Injector when comparing bhp against BHP constraint during well operability check

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp
for StandardWell only at this moment.
It improves the results of a reported case with **zero RESV** control (black line referee result, green line master branch, red line this PR ). 
And more importantly, with the defaulted relative slack tolerance, there is some error when coming to the connection rates and the well rates (**0** for this circumstance), potentially affecting the mass balance of the whole system (it means the flow out from the reservoir is not equal the flow into the reservoir through the wellbore with **0** well rates).  
Ideally stricter tolerance should be applied to all the wells (https://github.com/OPM/opm-simulators/pull/4556), but not sure how we should test and proceed with that direction, there might be some substantial investigation efforts involved.  This PR is …
=> stricter tolerance for wells with zero rate target

opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
Only Rate is supported in Item 7 and the simulator should not continue if other options are given. 
Notice that the default value (NONE) is not yet supported. 
A PR has been submitted to opm-tests to update 3 date decks the data
see PR  OPM/opm-tests#945
Notice that this PR should not be merged before OPM/opm-tests#945 is merged.
=> GCONPROD Item 7, only RATE is supported

opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
When testing a gaslift well under THP control, if the well does not converge with maximum alq try to reduce alq in increments to check if the well equations converge with a smaller alq.
=> Check all ALQ values when testing a gaslift well for reopening

opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
Moving the well controls and network update out of assembleImpl to avoid call assmebleImpl in a recursive manner. 
More importantly, we can solve the network in an iterative manner until we are happy. 
There is also suggestions to decouple the updateWellControls and network update further. It is not taken care in its current form of this PR yet.
=> refactor the network update

opm/simulators/wells/WellGroupHelpers.cpp
This is necessary to allow wells directly parented to FIELD. This is not currently allowed, but will be relaxed by an upstream PR.
=> Minor adjustment avoids exception when used with FIELD group.

opm/simulators/wells/WellGroupHelpers.cpp
this is not the case when WTEST executes at the beginning of (the first time step of) a report step if the well was created at that report step. this led to an exception being thrown trying to deref the potentials array
thanks to [at]bska for helping me pinpoint where to apply the fix
=> WellGroupHelpers: make sure we have a GuideRate value or potential for well

CMakeLists.txt
=> Backport #4612: fixed: only search for Development.Module component for python

opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellConnections.hpp, opm/simulators/wells/StandardWellEval.hpp, opm/simulators/wells/StandardWell_impl.hpp
Introduce a struct to group parameters, and use this to simplify method signatures.
=> Simplify WellconnectionPressures properties signatures

opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/SingleWellState.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellState.cpp
introduce an enum for indexing into the array. this again allows us to coalesce 4 parallel reductions into one.
another micro optimization.
=> changed: store rates in an array in SingleWellState

regressionTests.cmake, tests/update_reference_data.sh
These two test has been supported since 
https://github.com/OPM/opm-simulators/pull/4575
Simulation results was checked before this was merged. To be on the safe side, simulation results has checked again today.
=> start regression testing of WGRUPCON tests

flow/flow_ebos_gaswater_saltprec_vapwat.cpp
Any reasons for not allowing dissolved gas in water here? Or should I rather add a separate simulator for this?
=> Add disgasw to gas water saltprec vapwat simulator

opm/simulators/wells/StandardWell_impl.hpp
The updateWaterMobilityWithPolymer method updates values, it does not rewrite them. Hence we have to feed it the scalar values not zeros.
I noticed this while doing is some other refactoring. It does not affect any current tests.
=> fixed: copy the mobility values into the temporary Eval vector

CMakeLists.txt, flow/flow_ebos_gaswater_saltprec_energy.cpp, flow/flow_ebos_gaswater_saltprec_energy.hpp, flow/flow_gaswater_saltprec_energy.cpp, opm/simulators/flow/Main.hpp, opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/StandardWellAssemble.cpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/WellInterfaceIndices.cpp
The combination allows for modelling of salt precipitation in combination of thermal effects for a gas-brine system. Only tested in combination with CO2STORE.
=> Add energy + precipitation of salt in brine-gas simulator

ebos/eclgenericoutputblackoilmodule.cc
With this temperature is stored in the restart file if TEMP is used in RPTRST or THERMAL is set in RUNSPEC even if enable-opm-rst-file=false
=> output temperature if TEMP is set in RPTRST or THERMAL is set in RUNSPEC

opm/simulators/wells/WellInterface_impl.hpp
Since the assert is nop the reference will be unused.
=> avoid unused variable warning with NDEBUG

opm/simulators/aquifers/AquiferAnalytical.hpp, opm/simulators/aquifers/AquiferConstantFlux.hpp, opm/simulators/aquifers/AquiferInterface.hpp, opm/simulators/aquifers/AquiferNumerical.hpp, opm/simulators/aquifers/BlackoilAquiferModel.hpp, opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
This is in preparation of reinitialising the total produced volume from the constant flux aquifer from the restart file in the case that the aquifer's connections are split across multiple MPI ranks.
In particular, we need a global view of face-area fractions if aquifer connections happen to be shared between processes.  To this end, add a new helper function,
```C++
BlackoilAquiferModel::computeConnectionAreaFraction()
```
that performs a collective operation to compute the total face areas and then defers to the local aquifer objects to compute their face area fractions.
=> Calculate Local Face Area Fraction for Aquifer's Connections

opm/simulators/flow/FlowMainEbos.hpp
Following commits f4f8c033d and c7016854d (PR #4286), the "vanguard" no longer maintains an internal `Deck` data member.  Don't pretend that it does by providing member functions to access that data member.  If someone tries to actually call these member functions then they will get an unfriendly diagnostic message and a build failure.
=> Don't Provide Deck Accessors in FlowMainEbos

opm/simulators/flow/BlackoilModelParametersEbos.hpp, opm/simulators/flow/FlowMainEbos.hpp, opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/MultisegmentWellAssemble.hpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellEval.hpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/MultisegmentWellSegments.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp
* rewrite segment hydrostatic p-drop as average of neighboring nodes
* slightly hacky inclusion of "skipped" derivatives in the friction-term for reverse-flow cases. Could be done similarly also for valve-models, but currently not included for these.
=> Update of multisegment well pressure equations - testing

ebos/eclproblem.hh
Necessary to use intensive quantities at start of timestep.
=> Update timeIdx 1 intensive quantities if necessary.

CMakeLists.txt, CMakeLists_files.cmake, opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/cuistl/CuSeqILU0.cpp, opm/simulators/linalg/cuistl/CuSeqILU0.hpp, opm/simulators/linalg/cuistl/PreconditionerAdapter.hpp, opm/simulators/linalg/cuistl/PreconditionerConvertFieldTypeAdapter.hpp, opm/simulators/linalg/cuistl/detail/fix_zero_diagonal.hpp, opm/simulators/linalg/cuistl/detail/has_function.hpp, opm/simulators/linalg/cuistl/detail/preconditioner_should_call_post_pre.hpp, tests/cuistl/test_converttofloatadapter.cpp, tests/cuistl/test_cuseqilu0.cpp
We are creating a new linear solver GPU path compatible with the DUNE ISTL library. This first PR provides a wrapper to the CuSparse implementation of the sequential ILU0 algorithm. 
This new preconditioner is then exposed in the PreconditionerFactory, and can be run by specifying a `json` file of the form
```json
{
"preconditioner" : {"type":"CUILU0"},
"solver" : "bicgstab"
}
```
[This is related to the issue 3932](https://github.com/OPM/opm-simulators/issues/3932)
[This PR partially replaces PR 4137](https://github.com/OPM/opm-simulators/pull/4137)
This PR builds upon [PR 4634](https://github.com/OPM/opm-simulators/pull/4634), and is a prerequisite for [PR4636](https://github.com/OPM/opm-simulators/pull/4636)
=> Path to multigpu: Cuistl preconditioners

parallelRestartTests.cmake, tests/run-parallel-restart-regressionTest.sh
this should be controllable on a per-test level as other options.
keep current behavior for existing test by re-adding the option using TEST_ARGS.
=> changed: stop forcing no adaptive time stepping in parallel restart test driver

ebos/eclproblem.hh
to properly handle vappars updates in SCHEDULE
Downstream of https://github.com/OPM/opm-common/pull/3553
=> added: set vappars in fluidsystem/pvt at start of report step

ebos/equil/equilibrationhelpers_impl.hh
=> Fix rvw and rv initialization

ebos/eclgenericvanguard.cc, opm/simulators/utils/ParallelSerialization.cpp, opm/simulators/utils/UnsupportedFlowKeywords.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellEval.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellBhpThpCalculator.cpp, opm/simulators/wells/WellBhpThpCalculator.hpp, tests/test_ParallelSerialization.cpp
This PR together with https://github.com/OPM/opm-common/pull/3504 implements support for keyword WVFPDP. The implementation show good agreement with an Eclipse reference solution for test case [WVFPDP-01.DATA](https://github.com/OPM/opm-tests/blob/master/vfp/WVFPDP-01.DATA) :
=> Add support for WVFPDP

opm/simulators/wells/BlackoilWellModelConstraints.cpp
The `RESV` constraint was not honored specifying e.g.
```
GCONPROD 
-- if item 14 (RESV) is non-default this constraint should be honored (irrespective of item 7)
--   1     2      ORATE  WRATE GRATE LRATE    7	     8   ...      RESV           
'PROD' 'LRAT'   1000. 1*     1.E6  2500.  'RATE' 'YES' 1* 1*  3* 800 
```
With the proposed change OPM-flow behaves the same as the commercial simulator, see figure below where also the RESV volume rate (orange line) is shown using the OPM master that clearly violates the constraint.
=> correct reservoir rate constraint calculation

compareECLFiles.cmake, tests/getprop.awk, tests/update_reference_data.sh
rather specify it as properties on the tests themself and extract using some awk-ing.
let's streamline this a bit more. it's a bit nasty digging into the ctest file but i cannot get the information otherwise.
tested through https://github.com/OPM/opm-simulators/pull/4673 (removed from that PR again now).
=> changed: no need to manually specify test data in update script

opm/simulators/wells/StandardWellConnections.cpp
For this part of code in the master branch, it was assumed that the total_mobility will not be zero. 
But for one case that we are looking at, there are some cells with oil-water (zero gas saturation), we have the relative permeability (also mobility) for all the three phases are zero. 
This PR assuming the mobility for all the phases are equal for the situation above. 
Since the original perfRates initialization is far from accurate,  mostly hoping to have a not too bad perfRates ratios for the wellbore density calculation. 
The PR only aims to recover the running for the special situation of that specific case without attempting to improve the original initialization design.  
I mark it as draft before confirmed by the reporter. 
It contains the PR …
=> Fixing the perfRates initialization with all zero motiblity

ebos/eclfluxmodule.hh
With zero threshold pressure and zero pressure difference, the existing code will set the pressure diff explicitly to zero. This will also set any derivatives to zero as well, which may disconnect the corresponding matrix rows.
=> Do not set pressure diff to zero when not necessary.

ebos/eclactionhandler.cc, ebos/eclgenericwriter.cc
The `eval_assign()` and `eval()` member functions of `UDQConfig` now take a `const Schedule&` parameter.
=> Chase Upstream API Update

opm/simulators/flow/FlowMainEbos.hpp, opm/simulators/flow/Main.hpp
Note that this needs OPM/opm-models#811
There is a strange interaction when using MPI and OpenMP on some hardware/MPI implementations. I a serial run omp_get_num_procs() would return the number of processors but when started under mpirun it would always return 1.
With this we now allow users to use any amount of threads as we want to be able to use 2 threads on such machines.
Together with the companion PR we also make sure that the number of threads used by the linearizer is consistent with here (Prefer OMP_NUM_THREADS over command-line ThreadsPerProcess and use 2 if nothing is specified).
=> OpenMP: allow oversubscribing to prevent only 1 thread on some hardware

ebos/equil/initstateequil.hh, ebos/equil/initstateequil_impl.hh, opm/simulators/utils/UnsupportedFlowKeywords.cpp, regressionTests.cmake
This implements changes accommodating PPCWMAX when applying SWATINIT in equilibration, in particular the re-calculation of initial water saturation.
Depends on https://github.com/OPM/opm-common/pull/3570
=> Equilibration with PPCWMAX

ebos/equil/equilibrationhelpers_impl.hh
Round off errors in satOil leads to using saturated rv instead of rv from depth.
=> Fix  rv initialization

opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellConnections.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellInterfaceIndices.hpp
Thus we get to put more code in a compile unit instead of simulator objects.
=> Move connection rate helpers to StandardWellConnections

regressionTests.cmake
This supersede an earlier PR that includes the CO2STORE_GASWAT test 
https://github.com/OPM/opm-simulators/pull/4525
that was never merged. The code change seems to have been merged in other PRs.
The two tests are similar but test different input setup. 
Especially the CO2STORE_GW test salinity which recently was broken and should be fixed by 
https://github.com/OPM/opm-common/pull/3574
My plan is to frist merge these tests. Then rerun with https://github.com/OPM/opm-common/pull/3574. The test should then fail and we can update the reference with bugfix.
=> Add CO2STORE_GW and CO2STORE_GASWAT to regression tests

opm/simulators/flow/Banners.cpp, opm/simulators/flow/Banners.hpp, opm/simulators/flow/BlackoilModelEbos.hpp, opm/simulators/flow/BlackoilModelParametersEbos.hpp, opm/simulators/flow/FlowMainEbos.hpp, opm/simulators/linalg/setupPropertyTree.cpp, opm/simulators/linalg/setupPropertyTree.hpp, opm/simulators/timestepping/SimulatorReport.cpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
Making draft PR to provide a place to discuss aspects of the code. It still contains a lot of hacks, and when the time comes to get the functionality into the master branch it will be refactored to reduce the size: many methods have been added to support local solves that largely duplicate existing methods. I also think that there will be a series of smaller PRs instead of one large PR. There should be no change in performance or results for the existing fully implicit Newton(-like) method from the addition of new methods by themselves, but there could be some small improvements here and there. Any such will also be done in separate PRs.
=> Add nonlinear solver based on domain decomposition method

ebos/eclgenericthresholdpressure.cc, ebos/eclgenericthresholdpressure.hh
Previously we stored the equil region idx as unsigned short which imposed this limit. Apparently there models that use more regions than allowed. Hence we now store the idx using unsigned short which allows 65535 regions.
Still there is a caveat in the code: The region interaction is stored as a dense matrix. This means that using the maximum allowed number of regions now would consume 32 GB of memory. In the future we actually store the interactions in a sparse matrix to get rid of this memory requirement. For now we just issue a warning if there are more than 2048 regions used.
=> Increase supported equil regions from 255 to 65525

CMakeLists.txt
Otherwise, we risk oversubscribing the host system when running multiple tests in parallel (`ctest --parallel`).
=> Tag Parallel Unit Tests With Accurate Number of Processors

ebos/eclequilinitializer.hh, ebos/eclgenericproblem.hh, ebos/eclproblem.hh, ebos/equil/initstateequil.cc, ebos/equil/initstateequil.hh, ebos/equil/initstateequil_impl.hh
Adding a developer parameter (invisible to end users) to change the number of pressure table points used in equilibration.
=> Adding --num-pressure-points-equil as a developer parameter 

opm/simulators/flow/BlackoilModelEbos.hpp, opm/simulators/flow/partitionCells.cpp, opm/simulators/flow/partitionCells.hpp
This moves some of the partitionCells code from BlackoilModelEbos into partitionCells.cpp. Now all this code is in one compile unit. 
Also removes the indent for namespace which afaik is what we want.
=> PartitionCells: move all related code to compile unit

CMakeLists.txt
commit e5e7ff7287 introduced a dependency on a generated header in a header file. this is problematic with super-builds as there is no explicit dependency for the simulator objects to these generated headers.
with the ninja-generator it is smart enough to figure out this across the subdirectories, but the make generator is not. hence we explicitly add a dependency on the opmcommon target in this case. ideally we would only depend on the generated header to allow compiling opmcommon and simulator objects in parallel. however there is as far as i know no way to depend on OUTPUT targets across subdirectories.
=> fixed: parallel super builds

ebos/ecloutputblackoilmodule.hh, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/MultisegmentWellSegments.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/SegmentState.cpp, opm/simulators/wells/SegmentState.hpp, opm/simulators/wells/WellState.cpp
This commit adds logic and backing storage in the `SegmentState` to provide the segment level summary vectors
* SDENx -- Phase density of phase 'x' (O, G, W)
* SDENM -- Mixture density without flowing fraction exponents
* SMDEN -- Mixture density with flowing fraction exponents
We defer the calculation of SDENM and, especially, SMDEN, to the `MultisegmentWellSegments` class since this class maintains the current flowing fractions.
=> Calculate Segment Phase and Mixture Densities for Summary Output

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/SingleWellState.hpp, opm/simulators/wells/VFPHelpers.cpp, opm/simulators/wells/VFPProdProperties.cpp, opm/simulators/wells/VFPProperties.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterfaceGeneric.cpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellInterface_impl.hpp, regressionTests.cmake
When ~= zero rates are encountered during iterations (pre convergence), gas/water fractions become highly inaccuate which in turn may lead to solver getting stucked/well getting shut prematurely. A possible remedy suggested here is to switch to explicit lookup whenver rate drops below lowest value in table. To ensure that this approach also works for just opened wells, the logic around explicit lookup is also updated (since master implementation always employ implicit lookup for first step regardless).
The PR fixes issues for a few simple test-cases, but requires further testing
=> Include fallback to explicit vfp lookup for tiny rates - testing

CMakeLists.txt, CMakeLists_files.cmake, opm/simulators/wells/ParallelPAvgCalculator.cpp, opm/simulators/wells/ParallelPAvgCalculator.hpp, opm/simulators/wells/ParallelWBPCalculation.cpp, opm/simulators/wells/ParallelWBPCalculation.hpp, tests/test_parallel_wbp_calculation.cpp
This PR adds a parallel calculation object derived from the serial `PAvgCalculator` class.  This parallel version is aware of MPI communicators and knows how to aggregate contributions from wells that might be distributed across ranks.
We also add a wrapper class, `ParallelWBPCalculation`, which knows how to exchange information from `PAvgCalculatorCollection` objects on different ranks and, especially, how to properly prune inactive cells/connections.
=> Add Parallel Calculation Support for WBPn/WPAVE

ebos/eclwriter.hh, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellConnections.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp
This PR activates the support for calculating WBPn summary result values per well in parallel.  To affect the calculation we add two new data members in BlackoilWellModelGeneric:
- `conn_idx_map_`:  Maps well's connection index (`0..getConnections().size() - 1`) to connections on current rank.  Its `local()` connections are negative 1 (`-1`) if the connection is not on current rank, and a non-negative value otherwise.  The `global()` function maps well connections on current rank to global connection ID for each well.  Effectively the reverse of `local()`.  Finally, the `open()` function maps well connections on current rank to open/flowing connections on current rank. Negative 1 if connection is not flowing.
- `wbpCalculationService`: Parallel collection of WBPn calculation objects that …
=> Hook New WBPn Calculation Up to Well Model

opm/simulators/flow/FlowMainEbos.hpp, opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
Changes
```
Program threw an exception: [/home/mblatt/src/dune/opm/opm-simulators/opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp:586] Solver failed to converge after cutting timestep 11 times.
```
to
```
Simulation aborted: Solver failed to converge after cutting timestep 11 times.
```
Which seems more user friendly.
Needs OPM/opm-common#3599
=> Improve error message when time step is cut too often/much.

opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellGroupHelpers.hpp
In preparation of adding support for opening/creating wells or groups in the middle of a report step.  This is needed if an `ACTIONX` block runs something like `WELOPEN` or `WELSPECS`/`COMPDAT`.
=> Extract Well and Group Initialization

CMakeLists_files.cmake
Some may be possible to argue for leaving out, but it is better to include one that may be unneeded than not including one that is needed.
=> Add all ebos headers to public header list.

opm/simulators/flow/BlackoilModelEbos.hpp
Was left when I put the nldd solver in a separate class.
=> remove accidentially left-over member

.clang-format
removing a warning when using an IDE.
same with https://github.com/OPM/opm-common/pull/3616 and will self-merge.
=> removing the duplicated AlignAfterOpenBracket entries in .clang-format

ebos/equil/equilibrationhelpers_impl.hh
Rs and Rv given by RSVD/RVVD should be limited by the saturated values for rs/rv also if depth is outside the given interval.
=> Fix out of range rs/rv

ebos/eclgenericproblem_impl.hh, opm/simulators/wells/MultisegmentWellEval.cpp
Two minor fixes addressing compile warnings. The header guard fix solves a real potential problem.
=> Fix guard and warning

ebos/collecttoiorank.cc, ebos/eclgenericcpgridvanguard.cc, ebos/eclgenericproblem.cc, ebos/eclgenericthresholdpressure.cc, ebos/eclgenerictracermodel.cc, ebos/eclgenericwriter.cc, ebos/eclproblem_properties.hh, ebos/ecltransmissibility.cc, ebos/equil/initstateequil.cc
It is now typetag configurable. Should be enabled where used.
Downstream of https://github.com/OPM/opm-models/pull/821
=> Changed: Do not use dune-fem in default simulators even if it is available

opm/simulators/linalg/bda/BdaBridge.cpp
This restores the build on machines which enable the BDA bridge, but which do not have OpenCL installed.
=> Bring WellContributions Declaration in Scope

ebos/equil/initstateequil.hh, ebos/equil/initstateequil_impl.hh, opm/simulators/aquifers/AquiferAnalytical.hpp, opm/simulators/aquifers/AquiferCarterTracy.hpp, opm/simulators/aquifers/AquiferConstantFlux.hpp, opm/simulators/aquifers/AquiferInterface.hpp
Enable aquifer keywords when H2STORE is active with OIL phase (as brine). Pretty much an extension of what is already available for CO2STORE.
=> Enable aquifers with H2STORE

opm/simulators/flow/FlowMainEbos.hpp
If an exception is thrown during simulator setup, the ebosSimulator_ object might not be instanced. We then deref a nullptr calling the eclState() member further down.
=> fixed: avoid segfault in cleanup if simulator has not been set up

CMakeLists_files.cmake, ebos/eclproblem.hh, opm/simulators/flow/EclActionHandler.cpp, opm/simulators/flow/EclActionHandler.hpp
Since there is no opm-models usage, we should move this out of the ebos/ folder.
=> EclActionHandler: move from ebos/ to opm/simulators/flow

CMakeLists.txt, opm-simulators-prereqs.cmake
To make it easy to enable tracy profiling. Downstream of https://github.com/OPM/opm-common/pull/3631
=> added: build system option to enable Tracy profiler

ebos/eclgenericproblem.hh, ebos/eclgenericproblem_impl.hh, ebos/eclproblem.hh, ebos/eclproblem_properties.hh, opm/simulators/flow/FlowMainEbos.hpp, tests/test_RestartSerialization.cpp, tests/test_equil.cc, tests/test_glift1.cpp
Remove some unused methods and members. Avoid duplicate (and hidden) command line parameters.
I don't quite know the history here. It's either leftovers or duplicates that were required for the old ebos simulators. In any case I believe this can now be cleaned up without any fallout.
=> EclProblem: cleanup time stepping related members

ebos/ecltransmissibility.hh, ebos/ecltransmissibility_impl.hh
The return value from `applyNncToGridTrans_()` was never used and the author confirms that this is intentional.  Remove the entire return value to signal this intention.
Resolves #4799.
=> Remove Unused Return Value

ebos/FIBlackOilModel.hpp, opm/simulators/flow/BlackoilModelEbosNldd.hpp
-- changed spesicic nldd calls to use subDomain instead of gridview (-- clang formated FIBlackoil)
-- moved fully implict related updates to FIblackoil
This pullrequest should be followed up with a delete of similar functions in fvbasediscretization.
=> moved fully implicit calls to opm-simulators

opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
With this change
```
--time-step-after-event-in-days=
```
will also restrict the timestep after `WCONPROD`/`WCONINJE` etc. keywords.
=> Include production/injection update as timestepping event

ebos/eclgenericthresholdpressure.hh, ebos/eclgenericthresholdpressure_impl.hh
To search data via element Index and Cartesian Index, the classes LookUpData and LookUpCartesianData have been added. Subjected to OPM/opm-grid#670.
=> Refactor lookup of cartesian index and element data 

CMakeLists.txt, compareECLFiles.cmake, ebos/eclproblem.hh, opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp, tests/test_tuning_TSINIT_NEXTSTEP.cpp
Use max time step from TUNING.TSINIT or NEXTSTEP only when specified.
Requires https://github.com/OPM/opm-common/pull/3528
=> TUNING/NEXT[STEP]: Use max next time step only when specified

opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellEval.hpp
Valves may be placed in long segments with significant depth differences (e.g., at branch inlets), where the hydrostatic contribution in particular may be significant.
=> Adding hydrostatic and acceleration pressure losses to icd segments

CMakeLists_files.cmake, ebos/FIBlackOilModel.hpp, opm/simulators/flow/BlackoilModelEbosNldd.hpp, opm/simulators/flow/priVarsPacking.hpp, opm/simulators/linalg/ISTLSolverEbos.cpp, opm/simulators/linalg/ISTLSolverEbos.hpp, tests/test_privarspacking.cpp
I find these fixes quite nonintrusive, and they are required to make NLDD work with MPI. Most of the new lines are in a few new functions, and a new test.
A brief reminder of our current NLDD+MPI concept: each MPI rank will have its owned cells partitioned into a number of subdomains, the overlap (i.e. not owned) cells will not be part of its subdomains. After solving locally (with either Jacobi or Gauss-Seidel approach) overlap cells will be updated from the owning MPI rank, before doing the regular Newton update. This means that between MPI ranks, the approach is more Jacobi than Gauss-Seidel.
There is one more missing piece: using Zoltan to make the subdomain partition on each rank. For now, only the "simple" domain partitioning approach works with MPI. This work is done independently.
=> Fixes to enable using the NLDD nonlinear solver option in MPI parallel runs

opm-simulators-prereqs.cmake, opm/simulators/utils/initDamarisXmlFile.cpp
Damaris was updated in version 1.8.0 to support the HDF5 H5Sselect_elements() capability to rewrite data in memory to another order on disk. This allows (MPI decomposed) local simulation data to be written back to its original global position on disk.
To support this there was a new element added to the Damaris XML <variable...> type, named "select-file", along with some other options (not required by OPM Flow). This keyword is added to the basic in-built Daamris XML file of OPM Flow.
See here for some details: 
[Damaris website: hdf5-backend](https://project.inria.fr/damaris/hdf5-backend/)
[Damaris github wiki: Damaris-HDF5-Select-Points-Support](https://gitlab.inria.fr/Damaris/damaris/-/wikis/Damaris-HDF5-Select-Points-Support)
=> Damaris internal XML file update to support HDF5 local to global write.

opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp
In some special cases, `volumeFraction` can return slightly negative (~epsilon) oil faction due to round-off. This can lead to failure if segment represents e.g., an AICD-valve. Suggest to check for this and set value to zero if negative.
=> Prevent negative oil fractions in well segments

ebos/eclproblem.hh, regressionTests.cmake
Fixed a bug with DIRICHLET option in BCPROP not working in gas-water runs. Additionally, fixed a bug where BCPROP had to be defined at every report step.
Test case for DIRICHLET and gas-water added in regression test commit is in the opm-tests PR: https://github.com/OPM/opm-tests/pull/1037
=> Fix DIRICHLET option in BCPROP

opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWell_impl.hpp
These fixes are necessary to run the co2eor norne model described in [OPM/opm-publications/ghgt14](https://github.com/OPM/opm-publications/tree/1aef1411ac4ad953cece5684a380b46fddfb9357/ghgt14).
=> Solvent well fix

opm/simulators/wells/SingleWellState.cpp
This gives injectors that that is setup using BHP control some start help.
=> initialize all injectors with a rate to avoid singularities

opm/simulators/flow/countGlobalCells.hpp
This is mostly to prepare for implementing `partitionCells()` for grid views instead of grids.
=> Implement Interior Cell Counts for Grid Views

opm/simulators/wells/StandardWellPrimaryVariables.cpp
Reset values slightly outside the interval to the interval limits, while keeping the assertion to possibly pick up failure cases.
=> Avoid fraction relaxation factors outside [0,1] (standard wells)

CMakeLists_files.cmake, ebos/eclbasevanguard.hh, ebos/eclcpgridvanguard.hh, ebos/eclgenericcpgridvanguard.cc, ebos/eclgenericcpgridvanguard.hh, opm/simulators/utils/ParallelEclipseState.hpp, opm/simulators/utils/PropsDataHandle.hpp
The new structure LookUpCellCentroid is added, replacing code for search centroids of elements. Associated with OPM/opm-grid#672 (merged).
Currently, this new structure is used only when the rank is different from zero (CpGrid). Refactoring the code for the case zero rank (other grids), breaks many tests and it's (temporary ) postponed. 
EclBaseVanguard::centroids_ is removed. 
ProsCentroidsDataHandle.hpp now is called PropsDataHandle.hpp (centroids is removed too).
=> Refactor element centroids lookup

ebos/ecltransmissibility.hh, ebos/ecltransmissibility_impl.hh
This commit adds a new member function,
```C++
EclTransmissibility<>::applyNncMultreg_()
```
which applies regional transmissibility multipliers such as those entered in the `MULTREGT` keyword to the explicit input NNCs.  We make the application conditional on a new parameter, default value `false`, and pass `true` as the argument from `finishInit()`.
Along with `TransMult::getRegionMultiplierNNC()`, this implements all known connection behaviours for inter-region connections. Multipliers internal to a region in `MULTREGT` are not yet supported.
=> Apply Regional Multipliers to Initial Transmissibilities

opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
Otherwise it is hard to tell for the (newbie?) user what went wrong.
=> Include name of missing OPM restart file in error.

opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/GroupEconomicLimitsChecker.cpp, opm/simulators/wells/GroupEconomicLimitsChecker.hpp
Also contains https://github.com/OPM/opm-simulators/pull/4854 (cleaner to get this in first?)
Might consider removing debug print at a later stage.
=> Adding .PRT output when GECON is activated

CMakeLists_files.cmake, ebos/damariswriter.hh, ebos/eclproblem.hh, ebos/eclproblem_properties.hh, ebos/eclwriter.hh, opm/simulators/utils/DamarisKeywords.cpp, opm/simulators/utils/DamarisOutputModule.cpp, opm/simulators/utils/DamarisOutputModule.hpp, opm/simulators/utils/initDamarisXmlFile.cpp
Step one for moving Damaris calls out of EclWriter class and into its own DamarisWriter class; 
EclProblem now calls the writeOutput methods of DamarisWriter  and EclWriter and passes in the data::Solution object that is shared between them; 
Currently has an issue in the first iteration (iteration 0 in Damaris) there is no PRESSURE data - perhaps DamarisWriter does not initialize data::Solution correctly?
Moved setupDamarisWritingPars into the DamarisWriter class from DaamrisOutputModule (which now only has initialization code)
=> Damaris - Moving Damaris functionality to it's own class

ebos/eclalugridvanguard.hh, ebos/eclbasevanguard.hh, ebos/eclcpgridvanguard.hh, ebos/eclpolyhedralgridvanguard.hh
This is a follow-up/completition of #4778 where we separate the case when centroids are searched for a grid with LGRs and rank zero.
=> Supporting centroids lookup for rank 0 and LGRs

opm/simulators/wells/BlackoilWellModel_impl.hpp
Previously, we did a global summation of the size of the well_perf_data vector to determine the number of perforations of a well. In the case of distributed wells this will try to access more perforations than stored for the well in well_perf_data and hence might use data from cells that actually are not perforated by this cell. Note that for well not distributed the code worked as the summation has no effect.
This commit changes this to only query peforations on the local process. This should be enough to fix this problem.
In addition it removes the computation of connpos which is never used.
=> Fixes computation of temperature for distributed wells.

ebos/eclgenericoutputblackoilmodule.cc
Currently these buffers are not allocated unless restart output is requested, causing segfault initially if BFLOW[I|J|K] is requested without RPTRST in the SOLUTION section.
=> Always allocate buffers for storing flows if BFLOW[I|J|K] is requested

opm/simulators/wells/BlackoilWellModel_impl.hpp
We did only break in the loop for rank 0 and not the other ones. Hence all other processes kept iterating beyond the maximum number of allowed iterations. This lead to hard to find crashes because of non-matching MPI communication.
=> [bugfix] Fix stopping network update in parallel at max steps.

ebos/eclgenericwriter_impl.hh, opm/simulators/flow/EclActionHandler.cpp
In particular, pass a "segment matcher factory" into every function that forms UDQ context objects.
=> Chase API Change for UDQ Evaluation

opm/simulators/linalg/cuistl/set_device.cpp
`cudaThreadExit` has been deprecated in favour of `cudaDeviceReset`, which is already being called.
=> Removed call to deprecated cudaThreadExit

opm/simulators/linalg/ISTLSolverEbos.cpp
Due to issues with anonymous enums, newer versions of {fmt} (v10) do not seem to handle the implicit conversion from enum value to `int`. Hence we need a cast for `fmt::format`-calls involving `Matrix::block_matrix::rows` (or `cols`) to compile. This seems to only be relevant for one part of the code. 
For an isolated example, see https://github.com/kjetilly/fmt_fails_with_enum
=> Casting to support {fmt} v10.

ebos/ecltransmissibility_impl.hh
The connections entered in the `EDITNNC` keyword are already fully accounted for in the main 'update()' loop followed by the helper function `applyEditNncToGridTrans_()`.  Therefore, it is wrong to include those connections when applying `MULTREGT` to NNCs.  This commit removes the pertinent connections from the main loop in helper function `applyNncMultreg_()`.
Commit ddcafa8a91 (PR #4822) got this wrong, so pointy hat to [at]bska.
=> Don't Apply Regional Multipliers Twice to EDITNNC Connections

opm/simulators/flow/BlackoilModelEbos.hpp, opm/simulators/flow/BlackoilModelParametersEbos.hpp
The NLDD solver would always take one global non-linear (Newton) iteration before starting the local non-linear iterations.  This commit introduces a new command-line parameter,
```
--nldd-num-initial-newton-iter (NlddNumInitialNewtonIter)
```
which allows the user to configure this value at runtime.  The default value, 1, preserves the current behaviour.
=> Make Number of Initial Global Iterations Configurable

ebos/eclproblem.hh
If `--enable-vtk-output=true` and `--enable-write-all-solutions=false` (it is false as default), then the VTK files are written for all solutions. This commit fixes that, i.e., the VTK files are written for the report steps (unless we set `--enable-write-all-solutions=true`).
=> Fix to write vtks on report steps

opm/simulators/wells/WellState.cpp
backport of #4930 
we set the thp to be zero in the WellState. The previous logic related this to THP constraints does not hold in multiple situations:
1. VFP table is specified, we need the THP value for output purpose
2. network is involved, we need the THP value for constraint check.
=> if there is no VFP table associated with the well

ebos/eclgenericproblem.cc, ebos/eclgenericproblem.hh, ebos/eclgenericproblem_impl.hh, ebos/eclproblem.hh
To be able to support LGRs, lookup of origin cell is included in EclGenericProblem and EclProblem. This means that some features of a leaf grid view cell are taken from its origin cell, which is either a parent cell or the equivalent (non-refined) cell from level zero (global grid).
=> LookUp origin cell indices in eclgenericproblem

opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/MultisegmentWellSegments.hpp
In the case when the flow direction through valves/icd's is reversed, some derivatives are currently omitted (there is no _room_ for them in the current implementation). This PR fixes this by performing a second call to the respective functions and by doing a seperate assembly of the _extra_ derivatives. This is the same approach that was taken for acceleration pressure loss in #4640 (which helped in preventing singular well systems). 
The changes here have been tested on larger models and although results are not very conclusive, some positive effects have been observed. I think it's not unlikely though, that we will run into cases where these derivatives really matter (convergence and/or singularities), so unless they turn out to make things worse I think they should be incuded.
=> Add missing reverse flow derivatives for valve/icd/aicd

opm/simulators/linalg/ISTLSolverEbos.hpp
This information already goes to the `.DBG` file so there's no need to echo it to the main console as well.
=> Remove Leftover Debug Printout

ebos/ecloutputblackoilmodule.hh
We switch to using the `applyRestartSwatInit()` member function (PR OPM/opm-common#3731) instead of directly mutating a data member of the `EpsInfo` structure. This way we defer the rescaling to a context with a more complete view of the changes needed to convey the information to all components involved.
=> Apply Full SWATINIT-Like PCOW Rescaling at Restart

opm/simulators/flow/FlowMainEbos.hpp, opm/simulators/flow/python/PyBlackOilSimulator.hpp, python/simulators/CMakeLists.txt, python/simulators/PyBlackOilSimulator.cpp, python/test/pytest_common.py, python/test/test_basic.py, python/test/test_schedule.py, python/test/test_throw.py
Adds a `get_dt()` to the `opm.simulators.BlackOilSimulator` Python module. This will return the size of the previous simulator time step.
=> Get simulator time step size from Python BlackOilSimulator module

tests/cuistl/test_cujac.cpp, tests/test_dilu.cpp
These are only used as template parameters. Make them compile time variables.
=> avoid dead stores

opm/simulators/linalg/ISTLSolverEbos.hpp, opm/simulators/linalg/ISTLSolverEbosBda.hpp
Factor out the initialization code needed before doing a ILU decomposition to remove the redundant software decomposition when we also perform it on the GPU. This was previously done in #4558, but lost in the adaptation to ISTLSolverEbosBda.
=> Remove redundant CPU decomposition when done also on GPU

opm/simulators/linalg/ISTLSolverEbos.hpp
After DUNE version 2.7, the method getCollectiveCommunication() was changed to getCommunication(). The getCollectiveCommunication() issues the deprecation warning  and assumes all process take part in the communication. However, this might not be the case, namely, only a subset might be used. 
The fix consists in getting the communication object used be the grid as this uses only processes that are actually computing and not only outputting.
=> [bugfix] Deprecated getCollectiveComminication 

ebos/eclgenericvanguard.cc, opm/simulators/utils/ParallelSerialization.cpp, opm/simulators/utils/UnsupportedFlowKeywords.cpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/PerfData.cpp, opm/simulators/wells/PerfData.hpp, opm/simulators/wells/PerforationData.hpp, opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp, opm/simulators/wells/WellState.cpp, tests/test_ParallelSerialization.cpp, tests/test_parallel_wbp_calculation.cpp, tests/test_wellstate.cpp
Depends on https://github.com/OPM/opm-common/pull/3661
The Forchheimer term is added as a additional skin term that depends on the rate (explicitly). If the rate changes significantly we may want to solve this implicitly. That will require more refactoring / coding to implement. 
We use the viscosity of the connection cell here. In the dake book (Fundamentals of Reservoir Engineering) he suggest using the viscosity evaluated at the bhp pressure.
=> Implement Forchheimer term in wellIndex

ebos/eclproblem.hh, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell_impl.hpp
This commit includes the reduction on the well connection transmissibilities due to salt precipitation. This is expected to change the current solutions for the cases in opm-tests including salt precipitation, i.e., the  [SPE1CASE_PRECSALT.DATA](https://github.com/OPM/opm-tests/blob/master/spe1_precsalt/SPE1CASE1_PRECSALT.DATA).
=> Multiply well trans due to perm reduction in salt prec

ebos/eclgenericproblem_impl.hh, ebos/eclgenericthresholdpressure_impl.hh
To hide implementation details when assigning a field property to elements on the leaf grid view, using LookUpData methods (OPM/opm-grid#683).
=> Assign Field Property to all leaf grid view elements

opm/simulators/utils/UnsupportedFlowKeywords.cpp, regressionTests.cmake, tests/update_reference_data.sh
Remove keywords from unsupported list and add regression tests.
Only 1D UDTs are supported, however as this limitation is on the parser level I did not add it to partially supported since it will error out earlier.
Downstream of https://github.com/OPM/opm-common/pull/3728
Downstream of https://github.com/OPM/opm-tests/pull/1069
=> Enable (limited) support  for UDT

opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
I forgot to remove the warning when implementing the D factor in COMPDAT. 
https://github.com/OPM/opm-common/pull/3661
=> Remove warning for unsupported D factor in COMPDAT

opm/simulators/wells/BlackoilWellModel_impl.hpp
Also for well-testing it's important to have a non-zero initial guess for rates, and that there are non-zero _explicit_ water/gas fractions available for vfp-interpolation (e.g., non-zero _previous rates_). Otherwise the well is likely to converge to the zero rate/zero fractions case and deemed inoperable.
=> Initialize rates/previous rates before well-test

opm/simulators/flow/EclActionHandler.cpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, parallelTests.cmake, regressionTests.cmake
This commit adds a new flag data member,
```C++
bool wellStructureChangedDynamically_
```
to the generic black-oil well model.  This flag captures the
```C++
well_structure_changed
```
value from the `SimulatorUpdate` structure in the `updateEclWells()` member function.  Then, in `BlackoilWellModel::beginTimeStep()`, we key a well structure update off this flag when set.  This, in turn, enables creating or opening wells as a result of an `ACTIONX` block updating the structure in the middle of a report step.
=> Update Well Topology if Triggered From ACTIONX

opm/simulators/utils/DeferredLoggingErrorHelpers.hpp, opm/simulators/wells/MSWellHelpers.cpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWell_impl.hpp
This should replace OPM_DEFLOG_THROW in places where the problem category is more appropriate than the error category.
In this commit, uses of OPM_DEFLOG_THROW have been replaced whenever the exception class used was NumericalProblem.
This also addresses the same problem as #4957 but at the problem sites, instead of afterwards when the DeferredLogger's messages are logged.
Closes #4957 as it is an alternative solution that is even broader.
=> Add and use OPM_DEFLOG_PROBLEM macro.

opm/simulators/flow/ExtraConvergenceOutputThread.cpp
This will add extra information about well convergence failures to the INFOITER file (if that file is requested, it remains off by default).
Instead of
```
113           0  1.8260e+03          18  1.8038e-04  9.0530e+01  3.3362e-04  8.3487e+02  1.8634e-04  4.9056e+02        FAIL
```
you will get (scroll right to see the difference)
```
113           0  1.8260e+03          18  1.8038e-04  9.0530e+01  3.3362e-04  8.3487e+02  1.8634e-04  4.9056e+02        FAIL { A5 MassBalance NormalSeverity Phase 1 } { OP5 Unsolvable }
```
In the above, A5 and OP5 are well names, the next item is the type of failure, and for mass balance errors (only) we add the severity of the error (Normal, TooLarge, NotANumber) and the phase index affected. For iterations with no well failures (CONV not FAIL in the well …
=> Add extra output to INFOITER file detailing unconverged wells.

ebos/eclgenericoutputblackoilmodule.cc, opm/simulators/flow/LogOutputHelper.cpp, opm/simulators/flow/LogOutputHelper.hpp, tests/test_LogOutputHelper.cpp
only do one output per call. allow passing the name of the regions to process.
This will be necessary to support RTPSCHED/RPTSOL
=> changed: refactor LogOutputHelper::fip

ebos/ecltransmissibility.hh, ebos/ecltransmissibility_impl.hh
To support LGRs, the lookup of NTG has been updated, namely, for a leaf grid view cell, the ntg value is looked up via its parent cell (if existent), or its equivalent cell in level 0.  
Needs OPM/opm-grid#689 .
=> Lookup NTG on Leaf Grid View

opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
The user has explicitly asked for this behavior using --solver-continue-on-convergence-failure=true in this rare case.
Completes #4977
=> log problem if asked to continue with nonconverged nonlinear solver.

opm/simulators/utils/readDeck.cpp
… (in various schedule keywords). 
Depends on https://github.com/OPM/opm-common/pull/3698
=> If parsing strictness is set to 'low', proceed (with warning) if no matching wells found

ebos/eclequilinitializer.hh, flow/flow_ebos_brine_precsalt_vapwat.cpp, flow/flow_ebos_gaswater_brine.cpp, flow/flow_ebos_gaswater_dissolution.cpp, flow/flow_ebos_gaswater_dissolution_diffuse.cpp, flow/flow_ebos_gaswater_energy.cpp, flow/flow_ebos_gaswater_saltprec_energy.cpp, flow/flow_ebos_gaswater_saltprec_vapwat.cpp, opm/simulators/aquifers/AquiferAnalytical.hpp, opm/simulators/wells/WellInterface.hpp, tests/test_equil.cc
This allows to run decks with 
```
WATER
GAS
BRINE
CO2STORE
VAPWAT
DISGASW
```
=> Enabling disGas and watVap at compile time for gasWaterBrine systems

ebos/ecltransmissibility_impl.hh
To process intersections only once, Cartesian indices were used. When LGRs, two neighbors might have the same Cartesian index. Now, checking that each intersection is considered only once is done via element indices.
=> Check connect only once, with elemIdx instead of cart

ebos/ecltransmissibility_impl.hh
All neighbors in each LGR (if existent) are Cartesian neighbors on the level grid representing the LGR. 
When elements on the leaf grid view have the same parent cell, then their Cartesian Index on the leaf grid View coincide. 
This case is also taken into account in removeSmallNonCartesianTransmissibilities_().
=> Lgrs neighbors considered in removeSmallNonCart

CMakeLists_files.cmake, opm/simulators/flow/BlackoilModelEbosNldd.hpp, opm/simulators/flow/partitionCells.cpp, opm/simulators/flow/partitionCells.hpp, opm/simulators/utils/ParallelNLDDPartitioningZoltan.cpp, opm/simulators/utils/ParallelNLDDPartitioningZoltan.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
This PR switches the current implementation of `partitionCellsZoltan()`, i.e., `partitionCells("zoltan", ...)` into using a new, MPI-aware partitioning utility, `ParallelNLDDPartitioningZoltan`.  In doing so we make `partitionCellsZoltan()` private since its availability is not guaranteed.  We also slightly reorder the parameters and switch from passing a `Grid` into passing a `GridView` as an argument to `partitionCells()`, and specialise this function for the known grid views in OPM Flow.
We extract the Zoltan-related parameters out to an Entity-dependent helper structure and move the complexity of forming this type to a new helper function, `BlackoilModelEbosNldd::partitionCells()`.
The new `ParallelNLDDPartitioningZoltan` partitioner ultimately invokes the Zoltan library and therefore …
=> Make Zoltan-Based NLDD Domain Partitioning MPI Aware

ebos/eclgenericoutputblackoilmodule.cc, ebos/eclgenericoutputblackoilmodule.hh, ebos/eclproblem.hh, ebos/eclwriter.hh
This implements the configured FIP output from RPTSOL / RPTSCHED.
Sits on top of https://github.com/OPM/opm-simulators/pull/4978
Sits on top of https://github.com/OPM/opm-simulators/pull/4980
Downstream of https://github.com/OPM/opm-common/pull/3756
=> Implement support for RPTSOL and RPTSCHED configuration of FIP output

ebos/eclbasevanguard.hh, ebos/eclcpgridvanguard.hh, ebos/eclgenericcpgridvanguard.cc, ebos/eclgenericvanguard.hh, opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp
This commit introduces new, experimental support for loading a partitioning of the cells from a text file.  The name of the file is passed into the simulator using the new, hidden, command line option
```
--external-partition=filename
```
and we perform some basic checking that the number of elements in the partition matches the number of cells in the `CpGrid` object.
=> Add Support for Reading MPI Partitioning From File

ebos/eclalugridvanguard.hh, ebos/eclcpgridvanguard.hh, ebos/eclproblem.hh, ebos/eclproblem_properties.hh, ebos/ecltransmissibility.hh, ebos/ecltransmissibility_impl.hh, flow/flow_ebos_gasoil_energy.cpp, flow/flow_ebos_gasoildiffuse.cpp, flow/flow_ebos_gaswater_dissolution_diffuse.cpp, flow/flow_ebos_gaswater_energy.cpp, opm/simulators/flow/BlackoilModelEbos.hpp
With https://github.com/OPM/opm-common/pull/3737 and https://github.com/OPM/opm-models/pull/847, this PR adds support for the linear disperison model described in the SPE CSP11 benchmark document (Eq. 2.3) (https://github.com/Simulation-Benchmarks/11thSPE-CSP/blob/main/description/spe_csp11_description.pdf). Two cases are added in https://github.com/OPM/opm-tests/pull/1072 , where the effect of adding dispersion is assessed for a finger and injection problem.
=> Support for mechanical dispersion

CMakeLists_files.cmake, ebos/eclcpgridvanguard.hh, opm/simulators/flow/BlackoilModelEbos.hpp, opm/simulators/flow/BlackoilModelEbosNldd.hpp, opm/simulators/flow/BlackoilModelParametersEbos.hpp, opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp, opm/simulators/flow/partitionCells.cpp, opm/simulators/utils/ParallelNLDDPartitioningZoltan.cpp, opm/simulators/utils/compressPartition.cpp, opm/simulators/utils/compressPartition.hpp
This PR adds support for loading a three-column NLDD partitioning scheme of the form
```
MPI_Rank  Cartesian_Index  NLDD_Domain_ID
```
from a text file.  In an MPI run it is assumed that the first column holds integers in the range `0..MPI_Size()-1`, and typically that each such integer is listed at least once.  In a sequential run, the MPI rank column is ignored.
This PR also adds support for outputting such text files in both sequential and MPI runs.  If the user activates the new, and hidden, debugging option
```
DebugEmitCellPartition (--debug-emit-cell-partition)
```
each rank will write one such three-column text file into the special-purpose subdirectory `partition/CaseName` of the run's output directory.  That file will be named according to the process' MPI rank, so the first …
=> Enable Loading Parallel NLDD Partition From File

CMakeLists.txt
I swear last time I looked at this ninja managed to resolve the dependency on its own, but maybe I was just hallucinating or something. In any case, let us get it right now.
The simulator objects depends on the generated headers in opm-common. When doing a super build we have to explicitly declare this dependency or simulator objects might start building too early with many build threads. While optimally we'd declare the dependency on the generated headers, these are not grouped under a single target so we'd have to have a long list of headers. Instead we simply use the opmcommon library as the proxy.
=> fixed: also add dependency with ninja generator

opm/simulators/wells/WellInterface_impl.hpp, parallelTests.cmake, regressionTests.cmake
This is a rebased version of #4902 which additionally limits the timestep size of certain sensitive regression tests for improved determinism and stability.
Supersedes and closes #4902.
=> Fix shut-in logic for wells with shut-instructions (revised)

opm/simulators/wells/BlackoilWellModel_impl.hpp
Using bool here is at least frowned upon. To be honest, I have no idea what happens underneath here if we pass a bool. In contrast to other pod types we do not associate it with a builtin type of MPI (not even sure what to use). Hence we probably create a custom type for sending and receiving. That should work. But I have no idea what will be used for summation. Hence this might have very unpredictable results.
BTW: I am debugging a case that previously crashed and now suddenly works. This seems to be the only relevant change I made in the meantime.
=> [fix] Do parallel sums with int instead of bool.

opm/simulators/flow/BlackoilModelEbosNldd.hpp, opm/simulators/flow/BlackoilModelParametersEbos.hpp, opm/simulators/flow/SubDomain.hpp
This fixes a bug for the `gauss-seidel` NLDD approach that would actually do a `jacobi` initialization for the very first iteration of a local domain solve.
We add the `maxpressure` option for Gauss-Seidel NLDD domain ordering, and make it the new default ordering, and make `gauss-seidel` the default approach.
Finally, we make the default number of domains equal to one domain per 1000 cells, instead of just a single domain, and tweak the default cnv tolerance scaling for local solves.
These changes are intended to lower the bar to testing the `--nonlinear-solver=nldd` option. You still need to use `--matrix-add-well-contributions=true` to run with NLDD, otherwise defaults should be sufficient for reasonable behaviour.
=> Nldd refinements

opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.cpp
Both can safely be used together.
=> Do not warn about OutputDir when combined with LoadStep.

opm/simulators/wells/WellGroupHelpers.cpp, regressionTests.cmake
A sign was removed in #4664.
I notice that we don't have any `GPMAINT` cases under regression testing. I will put this as draft until we have double checked that this does not create an issue for the other gpmaint cases in https://github.com/OPM/opm-tests/tree/master/gpmaint
And we should out them under regression testing asap.
=> Bugfix sign of gpmaint prod

ebos/alucartesianindexmapper.hh, opm/core/props/satfunc/RelpermDiagnostics.cpp
For a cell on the leaf grid view, cartesianIndexMapper.cartesianCoordinate( cell idx, ...) computes the ijk index of the parent cell or the equivalent cell on level zero, for CpGrid with LGRs. For every level, included level 0, a new method to compute the ijk index, given the index cell on a certain level and its level, is included. See OPM/opm-grid#696. 
Such a method has been added also for ALUGrid and is needed in RelpermDiagnostics.cpp, to create the string of a cell index, from level zero.  To unify calls between the different grid types (CpGrid, Polyhedral, ALU).
=> CartesianCoordinateLevel added for ALUGrid

opm/simulators/wells/BlackoilWellModel_impl.hpp
Numerical problems during well testing (often: inf/nan in MSW matrices) will currently be caught at a higher level, causing time step chops in serial mode and possibly MPI communication errors in parallel. 
With this change wells that experience such problems during testing will simply not open, and MPI errors (mainly experienced during testing of https://github.com/OPM/opm-simulators/pull/4986) are no longer present.
=> Catch exceptions from well testing 

ebos/eclgenericoutputblackoilmodule.cc, opm/simulators/utils/ParallelEclipseState.cpp, opm/simulators/utils/ParallelEclipseState.hpp
not from SummaryConfig. the latter only holds regions with summary keywords.
Downstream of https://github.com/OPM/opm-common/pull/3813
=> fixed: grab list of FIP regions from FieldPropsManager

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp
For multi segment well the underlying call to
MultisegmentWell::updateWellStateWithTarget (at least if updateWellStateWithTHPTargetProd is called for a producer under thp control) might throw as there might be a singular matrix during the solve needed in MultisegmentWell::iterateWellEqWithControl.
Previously, if that happened then the MPI process where it happened would stop the nonlinear iteration as failed and try with a chopped time step. The others might go one with the current time step and we would see MPI errors about truncated messages.
Now we communicate any exception happening during this part of WellModel::updateAndCommunicate and all processes will stop the nonlinear iteration as failed and chop the time step.
=> Communicate exceptions during WellModel::updateAndCommunicate

opm/simulators/wells/MultisegmentWellSegments.cpp
Most power expressions in `pressureDropSpiralICD` and `pressureDropAutoICD` will return nan if given a negative base number. Even though these numbers should be positive (e.g., denisty, phase-fractions etc.), there is currently no guarantee for this (happened for a model I was looking at).  Although this PR just provides a quick-fix and does't attack the root of the problem (which seems to be during initialization), I think it doesn't hurt to have some safety-measures when dealing with general power expressions.
Hopefully, will not break any tests (_famous last words_).
=> Guard against nans from certain expressions in the valve models

opm/simulators/flow/BlackoilModelParametersEbos.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWellEquations.cpp, opm/simulators/wells/MultisegmentWellEquations.hpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellEval.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/SingleWellState.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellEquations.cpp, opm/simulators/wells/StandardWellEquations.hpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellEval.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/VFPHelpers.cpp, opm/simulators/wells/VFPHelpers.hpp, opm/simulators/wells/VFPProdProperties.cpp, opm/simulators/wells/VFPProdProperties.hpp, opm/simulators/wells/VFPProperties.hpp, opm/simulators/wells/WellBhpThpCalculator.cpp, opm/simulators/wells/WellBhpThpCalculator.hpp, opm/simulators/wells/WellConvergence.cpp, opm/simulators/wells/WellConvergence.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterfaceGeneric.cpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellInterface_impl.hpp
This draft PR contains functionality for computing implicit IPR (dq/dp derivative at current solution). Moreover several functions utilizing this for stability checking, estimating operability of stopped/unconverged wells and searching for solutions (vfp/IPR intersections) for use in problematic cases. In addition, direct computation of potentials is included.
For the new code to take effect, currently simulations must be run with _both_ options `--local-well-solve-control-switching=true` and `--use-implicit-ipr=true`.
**Note:** this code always aims at getting converged local well equations. If a well is not operable, it will converge to a stopped well. Currently, this may cause problems in the startup of networks (with zero rate initial guess) since branch vfp's don't support explicit …
=> Implicit IPR for stability/operablity checks and solution of thp-wells

ebos/eclgenericoutputblackoilmodule.cc, ebos/ecloutputblackoilmodule.hh
That way, the user gets a little more information and will be in a better position to assess whether or not the missing support is a real problem.
=> Report Destination File for Unhandled Report Keywords

opm/simulators/utils/ParallelEclipseState.cpp
That way, in-place quantities will go through the short-to-canonical name translation in `FieldProps` regardless of their origin&ndash;e.g., `RPTSOL`/`RPTSCHED` or explicit `SUMMARY` section vectors.
This is the downstream counterpart to OPM/opm-common#3839.
=> Publish Short Region Set Names Only

opm/simulators/wells/GroupEconomicLimitsChecker.cpp, opm/simulators/wells/GroupEconomicLimitsChecker.hpp
Pass a parameters as a const ref instead of value and use std::array.
=> GroupEconomicLimitsChecker: cleanup includes

ebos/eclgenericproblem.hh, ebos/eclproblem.hh
Two member functions have been added in EclProblem, to assign field properties of type double or int, unsigened int, ..., on the leaf grid view. 
For CpGrid with local grid refinement, the field property is inherited from the origin cell (parent or equivalent cell) in level zero. 
These new members: getFieldPropDoubleAssigner_ and getFieldPropIntTypeAssigner_, are used here to get thermal field properties on the leaf grid view, and in OPM/opm-simulator#5060, to get material field properties on the leaf grid view.
=> Function to lookup origin cell indices added in thermal field props.

ebos/eclproblem.hh
A function has been added to lookup the origin cell indices to populate material field properties on the leaf grid view.
This is downstream of and needs a merge of OPM/opm-common#3841.
=> Assign int on leaf added for material props

CMakeLists_files.cmake, ebos/damariswriter.hh, ebos/eclproblem.hh, ebos/eclproblem_properties.hh, opm/simulators/flow/Main.cpp, opm/simulators/flow/Main.hpp, opm/simulators/utils/DamarisKeywords.cpp, opm/simulators/utils/DamarisKeywords.hpp, opm/simulators/utils/DamarisOutputModule.cpp, opm/simulators/utils/DamarisOutputModule.hpp, opm/simulators/utils/DamarisVar.hpp, opm/simulators/utils/GridDataOutput.hpp, opm/simulators/utils/initDamarisXmlFile.cpp
Added access to DUNE mesh geometry and passing through data to Damaris; 
Updated flow command line options so users can specify Python or Paraview script names and other parameters that control Damaris:
- Simulation name
- Number of dedicated cores or dedicated nodes
- Shared memory region size
- switch to turn off HDF5 output.
- Damaris logging level
=> Geometric mesh data added for Damaris in-situ visualisation

opm/simulators/utils/DamarisVar.hpp
=> Order variables the same as in constructor init list.

ebos/ecltransmissibility_impl.hh
For CpGrid with LGRs, the field properties of a cell on the leaf grid view is inherited from its parent or equivalent cell from level zero. Now, extractPorosity_() and extractDispersion_() are modified to support that.
=> Lookup for extractPorosity and extractDispersion_

ebos/ecltransmissibility_impl.hh
For CpGrid with LGRs, the field properties of a cell on the leaf grid view is inherited from its parent or equivalent cell from level zero. Now, extractPermeability_() is modified to support that.
=> Lookup origin index for correct extractPermeability_  

ebos/ecltransmissibility_impl.hh
When the grid is a CpGrid with LGRs, and two cells on the leaf have the same parent cell on level zero, their Cartesian indices of the leaf grid cells coincide since they inherit the one of their parent cell from level zero.  
This PR modifies an assert to take into account this feature/issue, when checking if there are inactive cells in between and setting the transmissibility.
=> Assert refactored to include same-parent-leaf-cells

opm/simulators/wells/WellInterface_impl.hpp
In `computeConnectionDFactor` the function `gasPvt().saturationPressure(...)` is called to obtain a pressure for which the gas phase becomes saturated for a given `rv`-value. For cases where saturated `rv` is non-monotonic in pressure, this is not well defined. Also non-monotonicity may lead to convergence failures for the local Newton solver in the `saturationPressure`-function.
This PR simply swithces to rather use saturated `rv`-value at `connection_pressure` to test whether the gas phase is saturated or not.
=> Avoid use of problematic 'saturationPressure'-function

CMakeLists.txt, CMakeLists_files.cmake, opm/simulators/flow/Main.cpp, opm/simulators/flow/Main.hpp, tests/test_outputdir.cpp
Handle this case for Damaris, which needs to be told the output dir before this is available from the IOConfig.
=> Avoid modifying outputDir, leave empty if defaulted.

ebos/ecltransmissibility_impl.hh
For now, LGRs do not support MULTZ. However, a minor change has been added in applyAllZMultipliers_() to take into account that, when a grid is a CpGrid with LGRs, then cells on the leaf grid view with the same parent cell on level same have the same Cartesian indices.
=> Throw for LGR combined with MULTZ keyword

ebos/ecltransmissibility_impl.hh
For now, LGRs do not support TRANX, TRANY, TRANZ, therefore a throw has been added.
=> Throw for LGRs combine with TRANX/Y/Z

ebos/ecltransmissibility_impl.hh
A corner case was hit when running a model in MPI.
The condition became something like:
elemIdx < outsideElemIdx
insideFaceIdx == 4
useSmallestMultiplier == true
Which ultimately leads to an assert failure in applyAllZMultipliers().
Unfortunately, the model itself is proprietary thus I cannot share its detailed information. But changing the line to a comparison between insideCartElemIdx and outsideCartElemIdx does serve as a workaround.
=> Bugfix for a corner case in MPI

ebos/eclgenericoutputblackoilmodule.cc, opm/simulators/flow/LogOutputHelper.cpp, opm/simulators/flow/LogOutputHelper.hpp, tests/test_LogOutputHelper.cpp
There is no need to restrict PRT file flow reports to those wells which are active on the current rank since the `SummaryState` object holds information for all wells active at the current report step.
---
As an example of the impact of this change, here's the difference between abridged cumulative flow reports from the last report step of [`NORNE_ATW2013`](https://github.com/OPM/opm-tests/blob/4d1ef6e376f16f8a792056e13873e529f799c2ec/norne/NORNE_ATW2013.DATA) when run as
```sh
OMP_NUM_THREADS=1 mpirun -np 6  ${flow} --ecl-deck-file-name=${cse}
```
with different output directories (`np/6/dev` for this PR and `np/6/master` for the current master sources).  Flow values omitted here to avoid cluttering the display.
```diff
--- np/6/master/cumulative.rpt.last	2024-01-04 14:00:32.737251300 …
```
=> Output Well Flow Sheets for All Wells

opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/MultisegmentWellAssemble.hpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellEval.hpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/MultisegmentWellSegments.hpp
In master, the assembling of the acceleration pressure drop term skips certain derivatives for reverse flow (I also believe one of the derivatives is misplaced). This PR rewrites this and includes all derivatives analogously to what has been done for other terms.
For most cases, I would expect this to have minor effect, however, have seen cases where it improves convergence.
=> Include all derivatives for acceleration term in MS wells

opm/simulators/flow/BlackoilModelEbos.hpp, opm/simulators/flow/NonlinearSolverEbos.hpp
This bug has been around for some time. In practice master will always use 2 newton iterations even though default is to use 1. A lot of the tests will fail so this need some testing before it can be merged. A faster merge would be to change the default to 2, then all test will pass, but I think default should be 1.
=> Fix minimum newton iteration

opm/simulators/wells/WellFilterCake.cpp, parallelTests.cmake, tests/test_parallel_wbp_calculation.cpp
Downstream follow-up to OPM/opm-common#3763.  This must be merged in concert with the upstream PR.
=> Chase Constructor API Change for Opm::Connection Class

opm/simulators/linalg/ISTLSolverEbos.hpp
Nothing is saved by the lazy initialization, and the NLDD code needs this object to communicate values on process boundaries which can happen even before any global linear solve is done.
=> Initialize the communication object in initialize().

ebos/eclequilinitializer.hh, ebos/eclproblem.hh
The flux computation for the boundary assumes that the enthalpy is computed and set in the fluidstate.
=> Compute enthalpy for thermal boundary

ebos/ecltransmissibility_impl.hh
When the grid is a CpGrid with LGRs, and two cells on the leaf have the same parent cell on level zero, their Cartesian indices of the leaf grid cells coincide since they inherit the one of their parent cell from level zero.
This PR modifies `createTransmissibilty_()` and `resetTransmissibility_()` to take this into account.
=> Support LGRs when creating/resetting transmissibilities

ebos/damariswriter.hh
Fix for crash when cleaning up damaris mesh offset variable due to shared memory buffer being size off by one.
=> Fix for crash when Damaris is deallocating variables

CMakeLists_files.cmake, opm/simulators/flow/BlackoilModelEbosNldd.hpp, opm/simulators/flow/ExtraConvergenceOutputThread.cpp, opm/simulators/timestepping/ConvergenceReport.cpp, opm/simulators/timestepping/ConvergenceReport.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
This improves diagnostics and error logging for NLDD.
Most code line changes are because the to_string() functions related to convergence failure output were moved to make them available for the NLDD diagnostics need.
=> Parallel well domain and error logging for NLDD

ebos/eclgenericoutputblackoilmodule.cc, opm/simulators/flow/EclInterRegFlows.cpp, opm/simulators/flow/EclInterRegFlows.hpp, tests/test_eclinterregflows.cpp
This commit ensures that we have backing support for region IDs up to and including NTFIP (TABDIMS(5), REGDIMS(1)).  The existing setup would fail (segmentation violation) in the case of a summary vector of the form
ROFT
36 31 /
/
when the maximum FIPNUM value was 30.  We nevertheless support maximum FIPNUM values exceeding NTFIP.
We add a new optional parameter to the EclInterRegionFlowMap constructor.  The parameter allows client code to specifiy a "minimum maximum" region ID that all ranks must support.  This value will be enforced during parallel aggregation.
=> Support at Least NTFIP Distinict Regions for Inter-Region Flow

opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
This PR follows the API change of `WDFAC::getDFactor()` (PR OPM/opm-common#3765) to take the dynamic viscosity and gas density values in addition to a `Connection` object.
While here, also restructure the logic a little bit in order to avoid computing viscosity values unless they're actually needed.
=> Calculate D-Factor in Terms of Connection Class

opm/simulators/wells/PerfData.cpp, opm/simulators/wells/PerfData.hpp, opm/simulators/wells/WellInterface_impl.hpp, opm/simulators/wells/WellState.cpp
This PR captures the rock compaction transmissibility multiplier in the `PerfData` during the non-linear iterations and communicates the converged value back to the output layer through the new data member to the `data::Connection` structure,
```C++
double data::Connection::compact_mult
```
added in upstream PR OPM/opm-common#3766.
=> Communicate Dynamic Transmissibility Multiplier to Output Layer

ebos/eclgenericproblem_impl.hh, ebos/eclgenericthresholdpressure_impl.hh, ebos/eclproblem.hh, ebos/ecltransmissibility_impl.hh
Unnecessary function argument numElements removed. Associated with OPM/opm-common#3876 and OPM/opm-grid#704
=> [refactor] Remove numElems from LookUpData methods

opm/simulators/wells/BlackoilWellModel_impl.hpp
Also tries to fix some accidental well opening with local well solve control switching. Pairs with https://github.com/OPM/opm-common/pull/3873.
=> Revert always open history wells

opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/twolevelmethodcpr.hh
@blattms: With the tests in opm-simulators, I've checked that the flag gets propagated correctly to the respective method 'sync' in the indicessyncer dune-common (see https://gitlab.dune-project.org/core/dune-common/-/merge_requests/1335 and https://gitlab.dune-project.org/core/dune-istl/-/merge_requests/553).
We can merge this now and as soon as the changes in dune-common and dune-istl are available on earlier dune version, I can adapt the DUNE_VERSION_GTE query here.
=> Construct the matrices in the AMG hierarchy with deterministic indices.

opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/StandardWell_impl.hpp
During testing, two culprits for network convergence problems were identified:
1. The current lower bound on network pressure update may lead to convergence issues, so it's suggested simply to remove this.
2. The default (standard) well convergence tolerance is in some cases not sufficiently strict to get network convergence. This PR suggest a rather _ad-hoc_  solution by simply tightening the tolerance by a factor 10 for wells that are controlled under dynamic thp-limit.
=> Fix network convergence issues

CMakeLists_files.cmake, examples/opmrst_inspect.cpp, opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp, opm/simulators/flow/SimulatorSerializer.cpp, opm/simulators/utils/HDF5Serializer.cpp, opm/simulators/utils/HDF5Serializer.hpp, tests/test_HDF5Serializer.cpp, tests/test_HDF5Serializer_Parallel.cpp
Does not interact with the typetag system. While at it put some methods in a tu.
=> HDF5Serializer: move out of ebos folder

CMakeLists.txt, ebos/eclgenericoutputblackoilmodule.cc, ebos/eclgenericoutputblackoilmodule.hh, ebos/ecloutputblackoilmodule.hh, opm/simulators/flow/LogOutputHelper.cpp, opm/simulators/flow/LogOutputHelper.hpp, tests/test_LogOutputHelper.cpp
We accomplish that by passing the module version as a string to the constructors of LogOutputHelper and EclGenericOutputBlackoilModel instead of calling moduleVersionName() in LogOutputHelper. That way moduleVersionName is not needed by libopmsimulators anymore and compilation works again for people requesting shared libraries via CMake's BUILD_SHARED_LIBS variable.
Closes #5122
=> Fix linking errors when using shared libraries.

ebos/eclgenericoutputblackoilmodule.cc, ebos/eclgenericoutputblackoilmodule.hh, ebos/ecloutputblackoilmodule.hh
This PR allows to write in the restart file the capillary pressure for gas water systems using `PCOG`.
=> Write pc for watergas systems

opm/simulators/wells/StandardWellAssemble.cpp
Solvent production rate is now added to gas production rate such that their total rate is limited by GRAT control mode in WCONPROD.
From a (poorly constructed) example:
With current master, WNPR gets very large, and only the gas rate shown by (WGPR - WNPR) plot is limited by GRAT = 100 000 SM3/DAY
With PR, the total gas rate (WGPR) is limited by GRAT = 100 000 SM3/DAY
=> Fix WCONPROD GRAT control mode with solvent

opm/simulators/utils/UnsupportedFlowKeywords.cpp
COORDSYS is often used for single reservoir systems. Lets ignore it. Note that if NUMRES > 1 the simulator will stop.
=> Ignore Coordsys and print a warning

opm/simulators/utils/DeferredLoggingErrorHelpers.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
In a model I'm looking into the simulator quits with the rather uninformative message:
```
Simulation aborted as program threw an unexpected exception: computeWellPotentials() failed:
```
The problem is that the exception does not happen on the root process, and thus the exception message
only contains the prefix. Instead of adding new code to sync the exception message between processes,
I opted to use the existing functionality for the deferred logger and add the exception message as errors in there.
Furthermore since we are queuing up exceptions here, we should also concatenate the messages from all exceptions.
The output is now a lot more informative,
```
Error: [Exception on rank 2]: computeWellPotentials() failed: 
For well WELL1: …
```
=> Improve computeWellPotentials() exception output

CMakeLists_files.cmake
Currently files are built if Damaris is found but disabled. Fix the conditional.
=> fixed: do not build Damaris files if it is not enabled

opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell_impl.hpp
https://github.com/OPM/opm-simulators/pull/5124 revealed a bug in the local well control switching option where previously stopped wells will re-open during the local solve. This PR simply updates the `allow_switching`-flag to `false` whenever the well state status is *not* `OPEN`. 
For reference, it's the well status in the well interface that potentially gets updated during the local solve, not the well state status.
=> Avoid re-opening previously stopped wells

opm/simulators/flow/Banners.cpp, opm/simulators/flow/Banners.hpp, opm/simulators/flow/FlowMain.hpp, opm/simulators/timestepping/SimulatorReport.cpp
Some minor improvements to address some long-nagging issues, in particular the lack of output of setup timing. Before:
```
Number of MPI processes:         4
Threads per MPI process:         1
Number of timesteps:            93
Total time (seconds):            7.74 
Solver time (seconds):           7.69 
Assembly time (seconds):        1.92 (Failed: 0.0; 0.0%)
Well assembly (seconds):      0.37 (Failed: 0.0; 0.0%)
Linear solve time (seconds):    1.29 (Failed: 0.0; 0.0%)
Linear setup (seconds):       0.30 (Failed: 0.0; 0.0%)
Update time (seconds):          1.45 (Failed: 0.0; 0.0%)
Pre/post step (seconds):        2.00 (Failed: 0.0; 0.0%)
Output write time (seconds):    0.63
Overall Linearizations:        317    (Failed:   0; 0.0%)
Overall Newton Iterations:     224    (Failed:   0; 0.0%) …
```
=> Time reporting improvements

ebos/eclgenericproblem_impl.hh, opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp
Previously, it was ignored if the user did not run OPM-FlOW explicitly using the command line parameter --enable-tuning=true. Now it will be applied regardless which parameter is used.
=> Ensure NEXTSTEP is respected also without --enable-tuning=true

opm/simulators/utils/readDeck.cpp
(when reprocessing the schedule section after action application.)
=> Respect low parsing strictness in actions 

ebos/ebos.hh, ebos/eclproblem.hh, ebos/eclproblem_properties.hh, opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/linalg/ISTLSolver.hpp, opm/simulators/linalg/ISTLSolverBda.hpp, tests/test_equil.cc
Some meat for the manual:
- `--ecl-well-model` is now `--well-model`
- `--ecl-aquifer-model` is now `--aquifer-model`
=> Drop Ecl from two typetag entries/cl-parameters

CMakeLists.txt, CMakeLists_files.cmake, opm/simulators/flow/RegionPhasePVAverage.cpp, opm/simulators/flow/RegionPhasePVAverage.hpp, tests/test_region_phase_pvaverage.cpp
The initial use case is calculating the phase-filled pore-volume weighted average of the fluid mass densities per PVT region.  This value goes into calculating depth-corrected per-cell phase pressure values such as the `BPPO` and `BPPG` summary vectors.
This class manages a single linear array which separately tracks the averages' numerators and denominators as running sums per region and region set.  We pick this data structure to simplify the cross-rank reduction needed in MPI parallel runs.  Client code is expected to add individual per-cell and per-phase contributions using the `addCell()` member function and then call the `accumulateParallel()` member function to affect the cross-rank reduction.  The averages will then be available through the `fieldValue()` and `value()` member …
=> Add Utility for Region-Based Phase-Filled Averages

ebos/collecttoiorank_impl.hh
fixes regression after 7dcc411397baa585dca1fb6b804d074d9c3203d3
=> fixed: if we write the size as a size_t we better read it as a size_t

ebos/eclgenericoutputblackoilmodule.cc, ebos/eclgenericoutputblackoilmodule.hh, ebos/ecloutputblackoilmodule.hh, ebos/eclwriter.hh
This PR calculates the block-level depth-corrected phase pressures `BPPO`, `BPPG`, and `BPPW`.  We use the simulation configuration's `DatumDepth` feature to extract the reference depths for the `FIPNUM` region set per cell and accumulate average phase densities per PVT regions using the `RegionPhasePoreVolAverage` utility.  To that end, add a new `optional<>` data member of this type to the generic output module and initialise this if the input model requests such summary output.
=> Add Support for Calculating Block Level Depth Corrected Pressures

ebos/eclgenericoutputblackoilmodule.cc, parallelTests.cmake, restartTests.cmake
In particular, output the per-cell oil, gas, and water fluid in place vectors using compatible array names and surface condition unit conversion tags.
While here, also relax certain parallel and restart case regression test tolerances to make the tests pass once we generate the arrays.
=> Add Special Case Handling for Fluid-In-Place of Pure Phases

opm/simulators/flow/python/PyBlackOilSimulator.hpp, opm/simulators/flow/python/PyFluidState.hpp, opm/simulators/flow/python/PyFluidState_impl.hpp, opm/simulators/flow/python/PyMaterialState.hpp, opm/simulators/flow/python/PyMaterialState_impl.hpp, opm/simulators/flow/python/Pybind11Exporter.hpp, python/simulators/CMakeLists.txt, python/simulators/PyBlackOilSimulator.cpp, python/test/test_basic.py, python/test/test_fluidstate_variables.py, python/test/test_primary_variables.py, python/test/test_schedule.py
Added methods to the Python module `opm.simulators.BlackOilSimulator` to access primary variables and fluid state variables.
=> Get primary variables and fluid state from Python

python/docstrings.json, python/generate_docstring_hpp.py, python/simulators/CMakeLists.txt, python/simulators/PyBlackOilSimulator.cpp
This PR builds on #4950 which should be merged first.
Adds docstrings for the Python bindings. Currently, the docstrings can be used to get context help in editors or in IPython. However, the plan is to also use these docstrings to generate sphinx documentation for the Python bindings. This is the reason why we are generating the docstrings at build time using a JSON input file. Since the JSON input file can also be read by a sphinx extension to generate sphinx documentation without having to build the pybind11 opm-simulators module first (which would involve having to build the whole opm-simulators). The plan is to build the sphinx documentation and deploy it to GitHub pages using a GitHub Action workflow. To avoid large resource usage in the GitHub action workflow, we therefore  try to …
=> Add docstrings for Python bindings

opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/AdaptiveSimulatorTimer.cpp, opm/simulators/timestepping/AdaptiveSimulatorTimer.hpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp
Previously, the step size would only have used for the first time step of the next report step (at least of --enable-tuning=true was used).
Needs OPM/opm-common#3949
=> [Fix] Correct handling of NEXTSTEP in ACTIONX

opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterfaceFluidSystem.cpp, opm/simulators/wells/WellInterfaceFluidSystem.hpp, opm/simulators/wells/WellInterfaceIndices.cpp, opm/simulators/wells/WellInterfaceIndices.hpp, opm/simulators/wells/WellInterface_impl.hpp
=> Drop ebos in index functions

CMakeLists_files.cmake, opm/simulators/flow/FlowMain.hpp, opm/simulators/flow/FlowUtils.cpp, opm/simulators/flow/FlowUtils.hpp
and add a dedicated header.
this way we don't need to pull in FlowMain.hpp for the prototypes, avoiding pulling in the entire simulator machinery just to build some simple utility functions.
=> changed: rename FlowMain.cpp to FlowUtils.cpp

opm/simulators/flow/BlackoilModelNldd.hpp
For NLDD local solves, this meant that the metrics were always 0 and we would always accept non-converged local solves as good enough to keep.
=> Add missing convergence metrics to domain convergence report.

CMakeLists_files.cmake, flow/flow_blackoil_alugrid.cpp, flow/flow_blackoil_polyhedralgrid.cpp, opm/simulators/aquifers/BlackoilAquiferModel.hpp, opm/simulators/aquifers/SupportsFaceTag.hpp
this way we don't have to pull in alugrid and polyhedralgrid in simulator objects that does not use them
=> changed: put SupportsFaceTag in separate header

opm/simulators/wells/BlackoilWellModelGeneric.cpp
we need to read in group data even if there are no local wells
=> fixed: we need to call loadRestartData on all processes

opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/ParallelPAvgDynamicSourceData.cpp, opm/simulators/wells/PerforationData.hpp
If a well is nominally connected in inactive cells, i.e., if its connections have not been filtered down to the active connections only, then `allIndices` may not be a permutation of
```
0 .. allIndices.size()-1
```
Handle this case by sizing `storageIndex_` according to the maximum index value instead of `allIndices.size()`.
While here, also switch to constructing `PerforationData` objects in place since this is (slightly) faster than "construct"+"copy".
=> Allow for Sparse Source-Location Subsets

opm/simulators/flow/FlowProblem.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/GenericCpGridVanguard.hpp, opm/simulators/flow/Transmissibility_impl.hpp
Simulation (partially) supported for CpGrid with multiple LGRs (local grid refinement). The assumptions are: 
- disjoint LGRs,
- all the cells have to active,
- each set of cells to be refined has cuboid shape.
Future work: Output files.
=> Simulation (partially) supported for CpGrid with LGRs

opm/simulators/timestepping/AdaptiveTimeStepping.hpp
The step size might still need to be smaller than suggested to not simulate beyond the end of the current report step. To ensure this we now use AdaptiveTimeSimulationTimer::provideTimeStepEstimate which will limit it and also make sure that subsequent time steps will not get to small either.
=> [bugfix] Use reasonable timestep if  NEXTSTEP in ACTIONX is used.

opm/simulators/flow/DamarisWriter.hpp, opm/simulators/flow/EclGenericWriter.hpp, opm/simulators/flow/EclGenericWriter_impl.hpp, opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/utils/ParallelSerialization.cpp
In the current approach, the full list of summary vectors, especially those that are defined at the region level, is not known until we've processed all UDQ and/or ACTIONX definitions.  As a quick solution to this, switch to using the `SummaryConfig` object that's defined in the `EclipseIO` container instead of the object that gets constructed when reading the input files.
It is likely that we will have to rethink and refactor this construction process later.
=> Defer SummaryConfig Initialisation

tests/test_parallel_wbp_calculation.cpp
The WBP calculation service holds on to a reference to the given parameter so we have to use a local and not a temporary.
=> fixed: segfault due to taking a reference to temporary

opm/simulators/flow/FlowBaseVanguard.hpp, opm/simulators/flow/FlowGenericVanguard.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/linalg/ISTLSolverBda.hpp
This PR fixes a bug introduced when we removed the rocm dependency on opencl (#4883), which disabled the possibility to run the rocsparse and cusparse backends with the optimized version of block Jacobi ILU.
=> Bug fix: remove dependencies for rocm & cuda on opencl to run block Jacobi ILU

opm/simulators/flow/EclWriter.hpp, opm/simulators/utils/ParallelEclipseState.cpp, opm/simulators/utils/ParallelEclipseState.hpp
This PR implements the parallel version of
```
EclipseState::computeFipRegionStatistics()
```
which computes a `FIPRegionStatistics` object for the current run's fluid-in-place regions.  The object construction uses an MPI-aware reduction process to compute the maximum region IDs across all MPI ranks.
While here, also unconditionally form the statistics object as part of the `EclWriter`'s constructor to ensure that all ranks participate in the process.  The initial approach of constructing the object on first use is not robust in parallel.  We may however wish to compute these statistics only when needed.  If so, that will be the subject of follow-up work.
=> Add Procedure for Calculating Basic FIP Region Statistics

opm/simulators/flow/EclGenericWriter_impl.hpp
Meet the new `UDQConfig::eval()` API requirement (OPM/opm-common#3977) by adding a matcher factory for region-level summary vectors.
=> Prepare for Including Region Level Quantities in Field Level UDQs

tests/test_LogOutputHelper.cpp
In the test methods of the test suite we construct a new logger that logs to a local stringstream. This logger will be stored in a static map and hence live longer that the test method and the stringstream.
Some methods use `Opm::Log::MessageType::Note`, others `Opm::Log::MessageType::Warning` for adding the logging backend . There is one map per `MessageType` and sometimes (e.g. previous method used Note and this one uses Warning) we will log to the old logger with dangling references.
This problem materialized in a segmentation fault on ppc64el architecture.
=> [fix] Prevent dangling refernces in Logger for test_LogOutputHelper

opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellGroupHelpers.hpp
use Parallel::Communication type directly
also break some long lines
=> WellGroupHelpers: drop unnecessary template parameter

opm/simulators/linalg/bda/opencl/CPR.cpp, opm/simulators/linalg/bda/opencl/CPR.hpp, opm/simulators/linalg/bda/opencl/Preconditioner.cpp, opm/simulators/linalg/bda/opencl/Preconditioner.hpp, opm/simulators/linalg/bda/opencl/openclSolverBackend.cpp
this to avoid symbol clashes with the implementations. while at it rename it to Type as Preconditioner::PreconditionerType is redundant.
I ran into this while working in this area and found it a bit annoying so let's improve.
=> changed: make PreconditionerType an enum class

opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/PreconditionerWithUpdate.hpp
Atgeirr suggested that the famg preconditioner should have an update that reconstructs the preconditioner, this is fixed in this PR.
While doing this the RebuildOnUpdatePreconditioner wrapper class was made more general using parameter packs to keep the factory as clean as possible.
=> Fix fast amg wrapper and generalize RebuildOnUpdatePreconditioner

pyactionComparisons.cmake
Add test from https://github.com/OPM/opm-tests/pull/1150 to the python comparison tests.
=> Add test for NEXT keyword (and WELTARG) as python comparison tests

opm/simulators/linalg/bda/WellContributions.cpp, opm/simulators/linalg/bda/WellContributions.hpp, opm/simulators/linalg/bda/cuda/cuWellContributions.cu, opm/simulators/linalg/bda/opencl/openclWellContributions.cpp, opm/simulators/linalg/bda/rocsparseWellContributions.cpp
Instead of rebuilding 'the world' touching MultisegmentWellContribution.hpp now rebuilds just a handful of sources.
=> avoid including MultisegmentWellContribution in WellContributions.hpp

parallelTests.cmake, regressionTests.cmake
This PR adds sequential and parallel regression tests for the [`UDQ_REG-01`](https://github.com/OPM/opm-tests/blob/51a0015859d8724f17b95fa4ea6648ce8c0e55b1/udq_actionx/UDQ_REG-01.DATA) example model which uses region-level summary vectors in field-level UDQs.  Restarted tests are missing at this time.
=> Activate Regression Tests for Region Vectors in Field UDQs

opm/simulators/flow/RSTConv.cpp
even though it's perfectly fine to do so in this case, mpich will error out with an error if send and recv buffer is the same.
fixes mpich based (rhel7/8) builds.
=> fixed: do not send and recv from same buffer

opm/simulators/wells/BlackoilWellModelConstraints.cpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGuideRates.cpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/FractionCalculator.cpp, opm/simulators/wells/FractionCalculator.hpp, opm/simulators/wells/GroupEconomicLimitsChecker.cpp, opm/simulators/wells/TargetCalculator.cpp, opm/simulators/wells/TargetCalculator.hpp, opm/simulators/wells/WellGroupConstraints.cpp, opm/simulators/wells/WellGroupControls.cpp, opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellGroupHelpers.hpp
Make WellGroupHelpers and some related classes templates over the Scalar type.
To avoid having to explicitly instance every single function (now template) in there I have changed WellGroupHelpers from a namespace to a class with static members.
=> WellGroupHelpers: template Scalar type

opm/simulators/aquifers/BlackoilAquiferModel.hpp, opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/GasLiftSingleWell.hpp, opm/simulators/wells/GasLiftSingleWell_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
The _impl.hpp pattern is not very friendly to code analyzers such as clangd used in IDEs.
This adds logic so clangd see the _impl.hpp as a proper translation unit (include config.h and include the main .hpp file).
I've been carrying these locally for a long time. Let's see if this is acceptable for the main repo.
=> Improve IDE experience

tests/test_nonnc.cpp
if we use a separate instance the actnum arrays get out of sync. in
particular the two cells with PORV == 0 will not be marked as inactive
in the actnum array of the separate instance. this leads to a segfault
in lookUpData as the field props will have those cells filtered, while the grid
still has the cells active.
also convert to a boost unit test while at it.
=> fixed: use the eclipse grid from the eclipse state in test_nonnc 

opm/simulators/flow/FlowProblem.hpp
This causes almost 10% performance loss on Norne, avoid easily by doing the parameter get in the constructor.
=> Avoid getting parameters in hot path.

opm/simulators/linalg/cuistl/CuOwnerOverlapCopy.hpp, opm/simulators/linalg/cuistl/CuVector.cpp, opm/simulators/linalg/cuistl/CuVector.hpp, opm/simulators/linalg/cuistl/SolverAdapter.hpp, opm/simulators/linalg/cuistl/detail/vector_operations.cu, opm/simulators/linalg/cuistl/detail/vector_operations.hpp, tests/cuistl/test_cuowneroverlapcopy.cpp
This PR adds support for MPI communication being performed directly between GPUs instead of being sent via the CPU when using a multi-gpu linear solver. This is done by checking if we have a CUDA aware MPI implementation available at runtime and compile time, and then use regular MPI calls with memory buffers residing on the GPU instead of the CPU.
The first commit on this branch is Georg Zitzlsberger's prototype for the functionaity.
=> Add GPU Direct

opm/simulators/flow/Main.cpp, opm/simulators/flow/Main.hpp, opm/simulators/flow/python/PyBlackOilSimulator.hpp, python/docstrings.json, python/simulators/CMakeLists.txt, python/simulators/PyBlackOilSimulator.cpp, python/test/test_basic.py, python/test/test_mpi.py, python/test/test_throw.py
Allows the Python bindings to control whether `MPI_Init()` and `MPI_Finalize()` will be called when creating an `Opm::Main` object. This allows the Python unit test files to run more than a single unit test. Currently, only a single unit test could be run per test file since each test would create a new simulator object (calling the `Opm::Main` constructor) which would call `MPI_Init()` a second time (after `MPI_Finalize()` had been called for the first test case) which would give an error like:
```
*** The MPI_Init() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```
(This is because it is not possible to unload the Python module `opm.simulators.BlackOilSimulator` (which btw links dynamically with …
=> Allow Python bindings to control MPI setup in the OPM::Main constructor

opm/simulators/linalg/cuistl/CuVector.cpp, opm/simulators/linalg/cuistl/detail/vector_operations.cu, opm/simulators/linalg/cuistl/detail/vector_operations.hpp
To solve compilation issues with cuda&hip in PR #5253 this contribution removes the usage of thrust in OPM.
This only requires changing one part of the GPU dot product implementation which is only ever used in multi-gpu MPI code, which is not a prominent use case in OPM. The PR introduces slower sum reduction, but I do not expect it to be a problem, TODO added.
=> remove usage of thrust

opm/simulators/flow/FlowProblem.hpp
The issue is related to restart of cases using CO2STORE
=> Bugfix: initialize the input temperature in restart run without temperature in the restart file

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/flow/ExtraConvergenceOutputThread.cpp, opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/ConvergenceReport.hpp, opm/simulators/timestepping/gatherConvergenceReport.cpp, tests/test_tuning_XXXMBE.cpp
This commit includes the fraction of pore-volume whose CNV targets are violated as a new per-iteration quantity in the INFOITER file (`--output-extra-convergence-info=iteration`), with the column header `CnvErrPvFrac`.  We collect the values which are already calculated in
```
BlackoilModel<>::getReservoirConvergence()
```
and store these as a pair of numerator and denominator in the `ConvergenceReport` class.  Note that we need both the numerator and the denominator in order to aggregate contributions from multiple ranks.
While here, also make a few more objects 'const' and calculate column widths directly instead of the maximum number of characters in `writeConvergenceHeader()`.
=> Report CNV Violation Pore-Volume Fraction to INFOITER

opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
Since it appears to be allowed and working: 
https://github.com/OPM/opm-common/blob/95795867abc0a2a9a8af1a568387fd4799b0de10/opm/input/eclipse/Schedule/RSTConfig.cpp#L647-L648
=> Tag 'BASIC=0' as allowed in RPTRST

opm/simulators/flow/BlackoilModelParameters.hpp
Relaxed tolerances being more strict than the strict tolerances does not make sense in our use case.
=> Enforce Relaxed Tolerances Not Stricter Than Strict

opm/simulators/flow/AluGridVanguard.hpp, opm/simulators/flow/CpGridVanguard.hpp
from AluGridVanguard and CpGridVanguard.
they exist is becaluse of typo in the function name. There is another releaseGlobalTransmissibilities() function actually gets used.
=> removing unused releaseGlobalTransmissibility()

opm/simulators/wells/WellGroupHelpers.cpp
When we reach the pressure we will stop injecting (setting gpmaint rate to zero), we then also need to reset the state to avoid oscillations. 
Depends on https://github.com/OPM/opm-common/pull/4067
=> Reset gpmain state when rate is zero

opm/simulators/linalg/PreconditionerWithUpdate.hpp
These lines makes sure that the derived preconditionerMaker class has a destructor to avoid the clang warning -
> Wdelete-abstract-non-virtual-dtor
=> Resolve warning delete-abstract-non-virtual-dtor

opm/simulators/flow/equil/InitStateEquil.cpp, opm/simulators/flow/equil/InitStateEquil.hpp, opm/simulators/flow/equil/InitStateEquil_impl.hpp, opm/simulators/linalg/PreconditionerWithUpdate.hpp
use Parallel::Communication directly
in the process this quells a deprecation warning for Dune::CollectiveCommunication usage.
replace #5348 
Also takes care of niggle https://github.com/OPM/opm-simulators/pull/5355#discussion_r1601241011
=> InitStateEquil: remove template parameter from Comm

opm/simulators/linalg/cuistl/SolverAdapter.hpp
Strange and inconsistent capitalization would cause problems if compiled using cuda aware mpi.
Changed
> mpiSUpportsCudaAwareAtCompileTime
to 
> mpiSupportsCudaAwareAtCompileTime
=> fix typo that would cause crash cuda aware openmpi

opm/simulators/flow/CollectDataOnIORank.cpp, opm/simulators/flow/EclGenericWriter.cpp, opm/simulators/flow/FemCpGridCompat.hpp, opm/simulators/flow/FlowGenericProblem.cpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/GenericThresholdPressure.cpp, opm/simulators/flow/GenericTracerModel.cpp, opm/simulators/flow/Transmissibility.cpp, opm/simulators/flow/equil/InitStateEquil.cpp, opm/simulators/utils/GridDataOutput.cpp, tests/test_RestartSerialization.cpp
Interface has changed in 2.9 and including compat headers causes an error to be emitted.
=> fixed: build with dune-fem 2.9

opm/simulators/flow/FlowProblem.hpp
If an action block happens to run a UDQ ASSIGN operation and, furthermore, happens to run at the last time step of an episode then the ["clear pending assignments"](https://github.com/OPM/opm-common/blob/6af6865727aa4b513adf40b37f56656772fcf7f3/opm/input/eclipse/Schedule/ScheduleState.cpp#L160-L168) behaviour of the `ScheduleState` copy constructor leads to not performing the UDQ assignment at all.  This PR works around this problem by invoking the action handler's UDQ assignment function after processing all active action blocks.
The underlying problem has been present since at least PR OPM/opm-common#3587 which introduced the "clear pending assignments" behaviour of `ScheduleState`'s copy constructor.
While here, also make a few whitespace adjustments to `FlowProblem::endTimeStep()` to …
=> Rerun UDQ Assignments After Action Processing

opm/simulators/linalg/bda/amgclSolverBackend.cpp, opm/simulators/linalg/bda/amgclSolverBackend.hpp
amgcl cannot use the block matrices for block_size == 1 with the built-in backend so we need to specialize the CPU code.
While the BDA solver currently only supports block size 3, and thus we never hit this code path, it created problems for me while adding support for floats because I instance the whole class and not just the constructor. If the restriction of bs=3 is lifted at some time, we are at least ready in this aspect now.
=> amgclSolverBackend: fix for block_size == 1

opm/simulators/linalg/ISTLSolverBda.cpp, opm/simulators/linalg/bda/cuda/cusparseSolverBackend.cu, opm/simulators/linalg/bda/cuda/cusparseSolverBackend.hpp, opm/simulators/linalg/bda/rocsparseSolverBackend.cpp, opm/simulators/linalg/bda/rocsparseSolverBackend.hpp
This PR optimizes the memory operations time by overlapping the creation (which includes a host memory copy) of the jacobian matrix used in the blockJacobi ILU with copying the matrix data to the GPU. For NORNE this gives a 17% reduction in the total transfer/copy time, while for the bigmodel this reduction is around 50% on a system with a AMD EPYC 7763 64-Core Processor + AMD MI210 GPU / NVIDIA A100 GPU.
=> Overlap creation of jacobian matrix with GPU data transfers

regressionTests.cmake
to make the regression checking more stable.
it was investigated during the checking for the regression failures for https://github.com/OPM/opm-simulators/pull/5232 .
=> limiting max time step to 10 days for PYACTION_WCONPROD

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWellAssemble.cpp, opm/simulators/wells/MultisegmentWellAssemble.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellAssemble.cpp, opm/simulators/wells/StandardWellAssemble.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterfaceFluidSystem.cpp, opm/simulators/wells/WellInterfaceFluidSystem.hpp, opm/simulators/wells/WellInterfaceGeneric.cpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellInterface_impl.hpp
Several places in the code we check whether a well is set to inject/produce at zero rate since this case requires special treatment. This is currently done by the function `wellUnderZeroRateTarget` (often called from `stopppedOrZeroRateTarget`). Wells under group control are currently not included in this check, although the _special treatments_ are equally required if a well is assigned zero rate from a group.
I've written draft versions of the two above mentioned functions that also take group-controlled wells into account. Would just like some feedback/discussion whether this seems reasonable before I go ahead and suggest updating all relevant function calls (the new functions have temporary names `*Version`).   
I've verified that this approach fixes an issue with …
=> When checking for zero target rates, also check wells under group control where required

opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp
Since std::clamp returns a reference we must be careful to not capture the return value by reference, when there is a temporary among the input parameters.
For the second change (adding the explicit Scalar return type to a lambda) this is strictly speaking not necessary, as the lambda's return type is not a reference, but that is obscure so the change is just done as to clarify.
=> Bugfix: Avoid possible use of out-of-scope temporary.

opm/simulators/flow/FlowGenericVanguard.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/WGState.cpp, opm/simulators/wells/WGState.hpp
The transferWTestState() function leaks the originally pointed to object and returns a copy.
Changed to move the unique_ptr all the way to the destination.
=> Avoid memory leak from the *unique_ptr<X>.release() antipattern.

examples/printvfp.cpp, opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/utils/readDeck.cpp, tests/test_wellmodel.cpp, tests/test_wellstate.cpp
This PR switches to calling the `SummaryState` constructor which is aware of the value of undefined UDQs (OPM/opm-common#4052) directly.
While here, also sort headers, split some long lines, and prefer initialisation lists to constructor body assignments.
=> Make SummaryState Objects Aware of Undefined UDQ Value

regressionTests.cmake
Undefined UDQs get the value in `UDQPARAM(3)`.  The UDQ-01 test model triggers an action block [if and only if](https://github.com/OPM/opm-tests/blob/1925c493cc8e4a4bb905c5bfc09da731391c3123/actionx/UDQ-01.DATA#L206) we implement that behaviour.
=> Add Regression Test for Undefined UDQ Variables

opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, tests/test_RestartSerialization.cpp
We are not calculating any rates, so the original names are misleading. 
Saw this when reviewing other PRs.
=> renaming calcRates to calcResvCoeff, and calcInjRates to calcInjResvCoeff.

opm/simulators/linalg/ISTLSolverBda.cpp
Fix to the error:
```
/Users/dmar/Github/opm/opm-simulators/opm/simulators/linalg/ISTLSolverBda.cpp:127:15: error: use of undeclared identifier 'copyThread'
copyThread = std::make_shared<std::thread>([&](){this->copyMatToBlockJac(matrix, *blockJacobiForGPUILU0_);});
^
/Users/dmar/Github/opm/opm-simulators/opm/simulators/linalg/ISTLSolverBda.cpp:127:50: error: no member named 'thread' in namespace 'std'
copyThread = std::make_shared<std::thread>([&](){this->copyMatToBlockJac(matrix, *blockJacobiForGPUILU0_);});
```
=> [FIX]: Build issue if OpenMP is not present

opm/simulators/flow/NonlinearSolver.cpp, opm/simulators/flow/NonlinearSolver.hpp
We should not require two phases to have oscillating residuals to start handling it. Also remove unneeded numPhases function argument.
=> Detect oscillation in just one phase.

opm/simulators/utils/UnsupportedFlowKeywords.cpp
Basic support for this keyword was added in commit OPM/opm-common@5e3e20c552c10f69f0717d19fe88c13119ec3e71 (PR OPM/opm-common#2763) and this PR enables running models which use that basic support. Advanced uses, such as including user-defined arguments for the multipliers, will still be rejected at the input level.
=> Enable WTMULT as an Input Operation

opm/simulators/flow/FlowGenericVanguard.cpp
More small cleanup from static analysis.
=> Initialize double member for serialization test.

opm/simulators/flow/AluGridVanguard.hpp, opm/simulators/flow/CpGridVanguard.hpp, opm/simulators/flow/FlowProblem.hpp, opm/simulators/flow/Transmissibility.hpp, opm/simulators/flow/Transmissibility_impl.hpp
others are not needed for globalTrans_ for now. It will help to flatten the peak memory usage for rank 0 during a parallel running.
=> only allocate trans_ for globalTrans_

opm/simulators/flow/Transmissibility_impl.hpp
Once the simulator has computed the transmissibilities from the grid and the properties, we check whether the transmissibilties were explicitly modified in the deck. If that is the case, we create TRANX/TRANY/TRANZ from the calculated values and apply the modifications (`Transmissibility::updateFromEclState`). This allows the user to overwrite values, multiply them with a scalar, etc.
In a parallel run there was a bug. we assumed that the local ordering of the elements is the same as when they would ordered by cartesian index. This does not hold in parallel as the elements in the ghost/overlap layer will have a higher index than the other ones. Due to this values in the created arrays where were wrong (at the wrong place) for ghost/overlap elements. We might have overwritten values for …
=> Fix modifications of TRANX/Y/Z in parallel (e.g. MULTIPLY of TRANX in EDIT)

opm/simulators/flow/Transmissibility_impl.hpp
This is a follow up of the fix in #5414.
The comment said that the ordering of the compressed index of cells is coherent with the cartesian index. THis is not the case in parallel where cells in the overlap/ghost region might be ordered last (default).
=> Update wrong comment about storage of transmissibilities

opm/simulators/linalg/cuistl/detail/cusparse_matrix_operations.cu
Eliminate a warning from static analysis. Cannot really test this locally due to no appropriate hardware, please advise on proper Jenkins treatment @akva2.
@multitalentloes please check logic.
=> Ensure 'mid' is always initialized.

CMakeLists_files.cmake, opm/simulators/linalg/FlexibleSolver_impl.hpp, opm/simulators/linalg/ISTLSolver.cpp, opm/simulators/linalg/ParallelOverlappingILU0_impl.hpp, opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/PressureBhpTransferPolicy.hpp, opm/simulators/linalg/PressureTransferPolicy.hpp, opm/simulators/linalg/WellOperators.hpp, tests/test_ghostlastmatrixadapter.cpp
=> Ghost entries skipped for ILU apply and SpMV operator in all levels of AMG/CPR hierarchy

opm/simulators/flow/Transmissibility.hpp, opm/simulators/flow/Transmissibility_impl.hpp
If we use transmissibilities for loadbalancing, then we calculate transmissibilities twice. First on the global grid before loadbalancing and then on the local grid after that. This is the default. In this case all warnings will be shown correctly when calculating the global transmissibilities.
If the user requests the same weights for all faces (command line parameter --edge-weights-method=0) then the transmissibilities are only calculated on the loadbalanced grid. Unfortunately, in this case only rank 0 will issue warnings for his part including the false positives mentioned below.
Due to load balancing many NNCs might be stored on another process, but we still use all EDITNNC entries when computing transmissibilties locally. Hence when applying EDITNNC on the loadbalanced grid we will …
=> Prevent spurious warnings about NNCs when applying EDITNNC in parallel.

opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/GenericTracerModel.cpp, opm/simulators/flow/GenericTracerModel.hpp, opm/simulators/flow/GenericTracerModel_impl.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/TracerModel.hpp, opm/simulators/flow/VtkTracerModule.hpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, tests/test_RestartSerialization.cpp
Extended the tracer model to include partitioning of tracers into free and solution states whenever dissolved gas/vaporized oil exist. Essentially the tracer linear system has been extended with equations for free and solution tracers with simple mass transfer coupling between them. Both free and solution tracers are now outputted in restart files.
The PR is in draft mode to discuss and further improve/develop the tracer model. Per now it seems the results for the solution tracer part generally does not match reference results (e.g. in the [gas tracer test](https://github.com/OPM/opm-tests/tree/master/tracer)); only matches for simple test cases (e.g., one cell partitioning tracers). However, results for the free tracer part does generally match reference results and are also improved …
=> Partitioning tracers

opm/simulators/utils/readDeck.cpp
Recursive deletion causes results in all subfolders to be deleted if cmdline-arg output-dir happens to be empty in a single instance..
=> Do NOT delete files recursively

regressionTests.cmake
Removing the test as it is broken. More specifically, the last part of the simulation is unstable with oscillating results, making regression assessment futile. See #4855 for further discussion and details.
I did not see where to turn off data updating, maybe that is handled automatically these days?
=> Remove the MOD4_GRP regression test

opm/simulators/flow/FlowProblem.hpp
In master mass is created if DRSDT/DRSDTCON.
PR https://github.com/OPM/opm-models/pull/806 fixed the issue when hysteresis was activated but not when it was deactivated.
=> avoid mass creation with drsdt

opm/simulators/utils/DeferredLoggingErrorHelpers.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp
Nearly all exceptions throw when computing well potentoals will not abort the simulator but result in timestep chops. Hence those should not be counted as errors (e.g. by calling the OPM_*THROW* macros) and be reported in the PRT file.
This change will cause at least two more  occurences (in MSWellHelpers) to be treated as problems. For this we added a new helper function.Nearly all exceptions throw when computing wells will not abort the simulator but result in timestep chops. Hence those should not be counted as errors (e.g. by calling the OPM_*THROW* macros) and be reported in the PRT file.
=> Only indicate problems for exceptions whem updating well potentials,

opm/simulators/flow/BlackoilModel.hpp
The simulation will just chop the time step and continue. Note, that the error count in the PRT file is used by engineers to decide whether a simulation was successfull. Hence the error count should not be increased here.
Downstream of OPM/opm-common#4113
=> [fix] Do not count experiencing nans as error in PRT file.

opm/simulators/flow/EclGenericWriter.hpp, opm/simulators/flow/EclWriter.hpp
- simulator note was copied from the typetag dependent class (EclWriter)
- opm-output is no longer a separate module
=> clean up some comments

opm/simulators/wells/StandardWell_impl.hpp
Minor update in preparation for New defaults #5157.
* Fix missing treatment of solvent for STW potential calculations
* Do update of connection pressures relative to bhp before calculating STW potentials. Probably not neccessary, but this give closer match with current master when potentials are computed at defaulted bhp
=> Minor updates in preparation for New defaults #5157.

CMakeLists_files.cmake, opm/simulators/utils/satfunc/SatfuncConsistencyChecks.cpp, opm/simulators/utils/satfunc/SatfuncConsistencyChecks.hpp, tests/test_SatfuncConsistencyChecks.cpp
The intention is that this will ultimately replace the existing `RelpermDiagnostics` component which does not really work in parallel and which does not report enough context to help diagnose underlying issues.  For now, though, we just add the shell of a new set of checks and hook that up to the build.
Class `SatfuncConsistencyChecks<Scalar>` manages a configurable set of consistency checks, the implementations of which must publicly derive from `SatfuncConsistencyChecks<Scalar>::Check`.  Client code will configure a set of checks by first calling
```
SatfuncConsistencyChecks<Scalar>::resetCheckSet()
```
then register individual checks by calling
```
SatfuncConsistencyChecks<Scalar>::addCheck()
```
and finally build requisite internal structures by calling
``` …
```
=> Add New Platform for Saturation Function Consistency Checks

CMakeLists_files.cmake
the outputs will be generated when needed by the custom_command
since these outputs are not intended to be edited, there is no reason to hipify them up front. in particular this removes the long sequential process at configure time, allowing all hipification to run in parallel (if using multiple build jobs, ie. ninja -jx or make -jx)
=> changed: remove hipification at configure time

opm/simulators/wells/WellState.cpp
Avoid copying uninitialized data.
=> Initialize member for WellState serialization test constructor.

opm/simulators/flow/Transmissibility_impl.hpp
this removes some explicit loops.
=> [refactor] Use DUNE's dot product to hide code complexity.

CMakeLists.txt, CMakeLists_files.cmake, opm/simulators/utils/satfunc/SatfuncConsistencyChecks.cpp, opm/simulators/utils/satfunc/SatfuncConsistencyChecks.hpp, tests/test_SatfuncConsistencyChecks.cpp, tests/test_SatfuncConsistencyChecks_parallel.cpp
This PR adds a new public member function
```
SatfuncConsistencyChecks<>::collectFailures(root, comm)
```
which aggregates consistency check violations from all ranks in the MPI communication object `comm` onto rank `root` of `comm`.  This amounts to summing the total number of violations from all ranks and potentially resampling the failure points for reporting purposes.
To this end, extract the body of function `processViolation()` into a general helper which performs reservoir sampling and records point IDs and which uses a call-back function to populate the check values associated to a single failed check.  Re-implement the original function in terms of this helper by wrapping `exportCheckValues()` in a lambda function.  Extract similar helpers for `numPoints()` and …
=> Add MPI Support to Saturation Function Consistency Checks

opm/simulators/wells/BlackoilWellModel_impl.hpp
Otherwise, we might try to test a well that do not exist in the process, which will cause failure when trying to retrieve information from wells_ecl_.
=> make sure a well exists in the process before closing it due to group action

opm/simulators/flow/Transmissibility.hpp, opm/simulators/flow/Transmissibility_impl.hpp
We stored 3 copies of each cell centroid in axisCentroid. This seemed to be a waste of memory and also made the function distanceVector_ hard to understand.
With this change we omit this copy of information and simplify distanceVector_
=> [refactor] Remove unnecessary copy in axisCentroid and simply code.

opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/cuistl/CuDILU.cpp, opm/simulators/linalg/cuistl/CuDILU.hpp, opm/simulators/linalg/cuistl/detail/cusparse_matrix_operations.cu, opm/simulators/linalg/cuistl/detail/cusparse_matrix_operations.hpp, opm/simulators/linalg/cuistl/detail/vector_operations.cu, tests/cuistl/test_cudilu.cpp
Using cudaOccupancyMaxPotentialBlockSize/calibration to more dynamically pick the thread block size we see 1.3-1.5 speedup on linear iterations.
The calibration step is made more general and placed in a separate file in a following PR
=> Autotune thread block size

opm/simulators/utils/MPIPacker.cpp, opm/simulators/utils/MPIPacker.hpp, opm/simulators/utils/MPISerializer.hpp, opm/simulators/utils/SerializationPackers.cpp, opm/simulators/utils/SerializationPackers.hpp
Depends on https://github.com/OPM/opm-common/pull/4139
=> Avoid buffers exceeding intmax in MPI calls

opm/simulators/flow/FlowMain.hpp, opm/simulators/flow/Main.hpp
Also warn early if valid value of OMP_NUM_THREADS overrides --threads-per-process.
Motivation: Situation where an empty (but defined) OMP_NUM_THREADS caused OMP to select number of threads based on hardware information, resulting in a poor choice. Appears safer to stick with Flow default in this case.
=> Handle empty or invalid OMP_NUM_THREADS by Flow default

python/test_data/SPE1CASE1a/SPE1CASE1.DATA, python/test_data/SPE1CASE1b/SPE1CASE1.DATA
With this keyword, the SPE1CASE1.UNRST file could not be read in correctly at some point, until I've added a check in opm-models that checks this, this went unnoticed probably.
=> Remove UNIFOUT keyword from python test data file SPE1CASE1.DATA

parallelTests.cmake
The PID part of the timestep controller triggers and results in timestep sizes depending on the state of the simulation. This can lead to different timestepping for parallel and serial runs. Using only newton iteration count for timestep calculations addresses this.
Also, tighten CNV tolerances to avoid solution differences that are accepted by the simulator as within tolerances, but outside comparison tolerances.
Also also, reindent, no idea why it is different for the network tests.
I think the changes made to tolerances and timestepping would benefit other tests as well, coming in later PRs.
=> Improve parallel network test.

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterfaceFluidSystem.cpp, opm/simulators/wells/WellInterfaceFluidSystem.hpp, opm/simulators/wells/WellState.cpp, opm/simulators/wells/WellState.hpp, tests/test_wellstate.cpp
Depends on https://github.com/OPM/opm-common/pull/4152
See description there.
=> Use cell temperature in perforated cell to compute reservoir rates

opm/simulators/linalg/cuistl/CuView.hpp
OPM cuISTL does not compile at the momet because OPM_THROW allocates a type of string not allowed in device code.
This PR fixes this for now by separating device and host code where necessary and using asserts instead. 
A TODO is also added because when https://github.com/OPM/opm-common/pull/4153 is merged we can use macros from opm-common.
=> Avoid exception macro in device code

opm/simulators/linalg/cuistl/CuView.hpp
these will automagically be generated in both compiler passes so the specifiers are meaningless and causes nvcc to emit a warning
=> fixed: don't add device/host annotations to defaulted functions

opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/GenericCpGridVanguard.hpp, opm/simulators/flow/partitionCells.cpp, opm/simulators/flow/partitionCells.hpp, opm/simulators/linalg/ISTLSolverBda.cpp, opm/simulators/linalg/ISTLSolverBda.hpp, opm/simulators/linalg/findOverlapRowsAndColumns.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, parallelTests.cmake
This PR fixes a simulation runs with well connections that are added through an ACTIONX with the COMPDAT keyword and these connections need to be taken into account by the NLDD solver.
Without this fix, the simulator stops with an error (https://ci.opm-project.org/job/opm-simulators-PR-builder/6462/). This PR fixes sequential runs, there is a [separate PR](https://github.com/OPM/opm-simulators/pull/5510) for parallel runs.
This PR depends on https://github.com/OPM/opm-common/pull/4159 and https://github.com/OPM/opm-grid/pull/747.
This PR is not relevant for the reference manual.
I've triggered the tests in https://github.com/OPM/opm-common/pull/4159.
=> Fix the usage of the COMPDAT keyword in an ACTIONX for the NLDD solver for sequential runs

opm/simulators/flow/FlowMain.hpp, opm/simulators/flow/Main.hpp
in FlowMain.hpp
Same with https://github.com/OPM/opm-simulators/pull/5504, while it is in a different file `FlowMain.hpp` due to code duplication. 
The exception was caught also when I do debugging, while not digging into how everything works here.
=> avoiding unnecessary exception from std::stoi("")

parallelTests.cmake, regressionTests.cmake
The necessity of ILU0 for MICP and injectivity runs must be handled by either error message of fix, this just works around the issue by forcing the tests to run with ILU0.
This PR should eliminate three test errors for #5157.
=> Adjust test parameters for stability.

flowexperimental/flowexp.hpp
A very minor change that does not impact usage as far as I know. It is unclear why it was set to true in the first place (defaults has always been false for regular Flow).
This should address one of the test failures of #5157.
=> Flowexperimental: set MatrixAddWellContribution default to false.

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/WellState.cpp, opm/simulators/wells/WellState.hpp
Fixes an MPI bug for cases where a well switches from producer to injector at the restart step.
=> Ensure default ALQ is set for all production wells on all processes

opm/simulators/flow/FlowGenericVanguard.cpp
=> fixed: do not try to hide parameters that are not registered without MPI

opm/simulators/utils/UnsupportedFlowKeywords.cpp
Apparently Petrel now exports binary .GSG files instead of GRDECL by default, so this case may become more common.
=> More helpful message for PETGRID.

tests/test_RestartSerialization.cpp
Test this separately as upcoming reshuffles will remove it from the FlowGenericProblem test.
=> added: (restart-)serialization test for MixingRateControls

opm/simulators/flow/FlowProblem.hpp
Well is active condition for drift compensation was added some time ago due to convergence issues for a case without any dynamics. For CO2 injection simulation the drift compensation is still beneficial even when wells are no longer active. An alternative to this PR is to add a parameter like onlyEnableDriftCompensationWhenWellsAreActive, but I would rather just disable driftCompensation for these cases completely.
=> Remove check for active wells for drift compensation

opm/simulators/linalg/DILU.hpp, opm/simulators/linalg/ISTLSolver.hpp, opm/simulators/linalg/OwningBlockPreconditioner.hpp, opm/simulators/linalg/OwningTwoLevelPreconditioner.hpp, opm/simulators/linalg/ParallelOverlappingILU0.hpp, opm/simulators/linalg/PreconditionerWithUpdate.hpp, opm/simulators/linalg/amgcpr.hh, opm/simulators/linalg/cuistl/CuBlockPreconditioner.hpp, opm/simulators/linalg/cuistl/CuDILU.hpp, opm/simulators/linalg/cuistl/CuJac.hpp, opm/simulators/linalg/cuistl/CuSeqILU0.hpp, opm/simulators/linalg/cuistl/OpmCuILU0.hpp, opm/simulators/linalg/cuistl/PreconditionerAdapter.hpp, opm/simulators/linalg/cuistl/PreconditionerConvertFieldTypeAdapter.hpp, tests/cuistl/test_converttofloatadapter.cpp
The cpr-reuse-setup option is currently not limited to CPR and is being used for all preconditioners. The default option is to recreate the linear solver every 30th linear iteration. The motivation behind this option is that the AMG hierarchy depends on the values of the matrix, such that as the values of the matrix changes, the preconditioner should be updated. For preconditioners where the construction of the preconditioner only depends on the matrix structure, it is never needed to recreate the preconditioner, as the matrix structure should be constant throughout the simulation. 
I therefore suggest that we make this option only apply to CPR. This will also make the effect of the option match the name.
=> Make CPR reuse setup option only apply to CPR

opm/simulators/wells/BlackoilWellModelGeneric.cpp
Cases with CO2STORE and was broken by https://github.com/OPM/opm-simulators/pull/5528. This is a fix.
=> BUGFIX Fix no wells case

opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/linalg/FlowLinearSolverParameters.cpp, opm/simulators/linalg/FlowLinearSolverParameters.hpp, opm/simulators/linalg/ISTLSolver.hpp
For the NLDD nonlinear solver, we are solving a linear system locally for each subdomain. Currently the linear solver for this task is hardcoded to use ilu0 and default max iterations and reduction tolerance. For more flexibility and easier experiments I propose we set this as a command line argument using the non-invasive changes in this PR.
=> Make local solver in NLDD a runtime specified ISTLSolver

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellConnections.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface_impl.hpp
This PR switches the approach introduced in commit eeb1b7e36c9ae3c30ba5d262fa623dc0eea2e10b (PR #3169) to using a mobility weighted average of cell level densities for the connection level mixture densities in no-flow producing wells.  We also use the recent `stoppedOrZeroRateTarget()` predicate to identify those no-flow producing wells instead of inspecting the connection flow rates.
The mobility weighted average gives a more monotone pressure buildup for the stopped wells and this is usually what the engineer wants. This revised approach furthermore needs fewer cell-level dynamic properties so simplify the `computeProperties()` signature by introducing a structure for the property callback functions and update the callers accordingly.
While here, also refactor parts of the …
=> Revise Mixture Density Method for No-Flow Producers

tests/test_SatfuncConsistencyChecks_parallel.cpp
=> do not capture compile time data in lambda

opm/simulators/linalg/amgcpr.hh
Since ```hasPerfectUpdate()``` was marked override, the rest of the methods needs to use modern style as well or compilers warn.
=> amgcpr: use override

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/ExtraConvergenceOutputThread.cpp, opm/simulators/timestepping/ConvergenceReport.hpp, opm/simulators/timestepping/gatherConvergenceReport.cpp, opm/simulators/timestepping/gatherConvergenceReport.hpp, tests/test_gatherconvergencereport.cpp
This PR tracks the number of cells and their associate fraction of the model's "eligible" pore volume (total pore volume in numerical aquifers subtracted from the model's total pore volume) in three distinct categories as a function of the non-linear iteration number:
- 0: $\max_p { \mathrm{CNV}_p } \le \text{strict CNV tolerance}$
- 1: $\max_p { \mathrm{CNV}_p } \in (\text{strict}, \text{relaxed}]$
- 2: $\max_p { \mathrm{CNV}_p } > \text{relaxed CNV tolerance}$
We then output these cell counts and pore volume fractions as new items in the INFOITER file to enable more targeted analysis of the non-linear convergence behaviour.
To this end, introduce a type alias `CnvPvSplit` in the `ConvergenceReport` and aggregate these across the MPI ranks before we
collect them in the …
=> Output CNV Histogram to INFOITER File

opm/simulators/flow/BlackoilModel.hpp
This is an error before C++20, and clang refuses it.
=> Avoid capturing structured bindings.

python/Dockerfile, python/MANIFEST.in, python/build-deps.sh, python/generate-pypi-package.sh, python/opm/CMakeLists.txt, python/pyproject.toml, python/requirements.txt, python/setup-docker-image.sh, python/setup.py.in, python/simulators/CMakeLists.txt
This is the fluff required to deploy the opm-simulators module to pypi.
It also builds the opm-common package to ensure that there are no version differences between the bindings.
Strictly speaking we could thus remove the packaging Docker from opm-common as it will not be used, but I keep it intact for now in case somebody wants to just build those.
In the process I was forced to abandon manylinux2014 and bump to manylinux_2_28. Basically this means dropping RH7 support. manylinux2014 is based on centos7 and all the repos are gone so it's .. very tedious to build for and frankly not worth it any longer. Those on those platforms can stick to the 2024.04 stable release.
=> add python packaging fluff

opm/simulators/flow/MixingRateControls.cpp
It does not make sense to pass
```C++
episodeIdx && maxDRv_.empty()
```
as an argument to `drvdtActive()`.
=> Fix DRVDT Initialisation Conditional

python/simulators/CMakeLists.txt
if not, building just the python binding won't end up in a complete build
=> fixed: make python simulator object depend on copy_python

CMakeLists_files.cmake, opm/simulators/utils/satfunc/OilPhaseConsistencyChecks.cpp, opm/simulators/utils/satfunc/OilPhaseConsistencyChecks.hpp, opm/simulators/utils/satfunc/PhaseCheckBase.cpp, opm/simulators/utils/satfunc/PhaseCheckBase.hpp, opm/simulators/utils/satfunc/SatfuncConsistencyChecks.hpp, tests/test_OilSatfuncConsistencyChecks.cpp
This commit introduces a set of consistency checks for the oil phase saturation functions.  These plug into the framework introduced in commit c3939c544 (PR #5438).  We implement the following four checks for the gas/oil two-phase system
* $0 \le S_{\mathrm{OG},\mathrm{CR}} < 1$
* $S_{\mathrm{WL}} + S_{\mathrm{GU}} \le 1$
* $S_{\mathrm{OG},\mathrm{CR}} < 1 - S_{\mathrm{WL}} - S_{\mathrm{GL}}$
* $S_{\mathrm{OG},\mathrm{CR}} < 1 - S_{\mathrm{WL}} - S_{\mathrm{G},\mathrm{CR}}$
which all guarantee a non-negative (mobile) oil saturation in the gas/oil system.  Similarly, we implement the following four checks for the oil/water two-phase system
- $0 \le S_{\mathrm{OW},\mathrm{CR}} < 1$
- $S_{\mathrm{GL}} + S_{\mathrm{WU}} \le 1$
- $S_{\mathrm{OW},\mathrm{CR}} < 1 - S_{\mathrm{WL}} - …
=> Add Oil Phase Saturation Function Consistency Checks

CMakeLists_files.cmake, opm/simulators/utils/satfunc/GasPhaseConsistencyChecks.cpp, opm/simulators/utils/satfunc/GasPhaseConsistencyChecks.hpp, tests/test_GasSatfuncConsistencyChecks.cpp
This commit introduces a set of consistency checks for the gas phase saturation functions.  These plug into the framework introduced in commit c3939c544 (PR #5438).  We implement the following three checks
- $0 \le S_{\mathrm{GL}} < 1$
- $0 \le S_{\mathrm{GU}} < 1$
- $S_{\mathrm{GL}} \le S_{\mathrm{G},\mathrm{CR}} < S_{\mathrm{GU}}$
which collectively enable a non-negative oil saturation in the two phase gas/oil system.
=> Add Gas Phase Saturation Function Consistency Checks

CMakeLists_files.cmake, opm/simulators/utils/satfunc/WaterPhaseConsistencyChecks.cpp, opm/simulators/utils/satfunc/WaterPhaseConsistencyChecks.hpp, tests/test_WaterSatfuncConsistencyChecks.cpp
This commit introduces a set of consistency checks for the water phase saturation functions.  These plug into the framework
introduced in commit c3939c544 (PR #5438).  We implement the following three checks
- $0 \le S_{\mathrm{WL}} < 1$
- $0 < S_{\mathrm{WU}} \le 1$
- $S_{\mathrm{WL}} \le S_{\mathrm{W},\mathrm{CR}} < S_{\mathrm{WU}}$
which collectively enable a non-negative oil saturation in the two phase oil/water system.
=> Add Water Phase Saturation Function Consistency Checks

CMakeLists_files.cmake, opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.cpp, opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.hpp, tests/test_ThreePointHorizontalSatfuncConsistencyChecks.cpp
This commit introduces consistency checks for the scaled displacing saturation in the three point horizontal scaling method (`SCALECRS=YES`).  These plug into the framework introduced in commit c3939c54 (PR #5438).  We implement the following two checks
- $S_{\mathrm{G},\mathrm{CR}} < 1-S_{\mathrm{OG},\mathrm{CR}}-S_{\mathrm{WL}} < S_{\mathrm{GU}}$
- $S_{\mathrm{W},\mathrm{CR}} < 1-S_{\mathrm{OW},\mathrm{CR}}-S_{\mathrm{GL}} < S_{\mathrm{WU}}$
which collectively guarantee a mobile displacing oil saturation in the two phase gas/oil and oil/water systems.
=> Add Saturation Function Consistency Checks for SCALECRS

opm/models/utils/terminal.cpp
The `strsignal()` function is declared in `<string.h>` on those.
=> Fix Build on Older Compilers

python/generate-pypi-package.sh, python/simulators/CMakeLists.txt
i forgot the package version tag in last iteration.
remove opm-models cloning as it is no longer required
optimize build a little by building both bindings in one build directory
=> fix python package versioning

opm/simulators/flow/Main.hpp, opm/simulators/flow/python/PyBlackOilSimulator.hpp, python/simulators/PyBlackOilSimulator.cpp, python/simulators/PyMain.hpp
This saves us hundreds of MB per simulator object.
The entire blackoil simulator has been instanced (instanced, not built mind you) in every single simulator object due to the member type.
=> Move python initialization function

opm/simulators/utils/satfunc/GasPhaseConsistencyChecks.cpp, opm/simulators/utils/satfunc/GasPhaseConsistencyChecks.hpp, tests/test_GasSatfuncConsistencyChecks.cpp
The earlier condition
```math
0 \le S_{\mathrm{GU}} < 1
```
was not appropriate and would, for instance, fail the `NORNE_ATW2013` test case in which [`SGU` = 1](https://github.com/OPM/opm-data/blob/eaa2261683a97027e057c2bc49612ad1c86390b3/norne/INCLUDE/RELPERM/SCAL_NORNE.INC#L82) in the unscaled table for saturation region 1.  Revise the condition to be more in line with that of SWU, i.e., as
```math
0 < S_{\mathrm{GU}} \le 1
```
Pointy Hat: @bska
=> Fix Consistency Check for Maximum Gas Saturation

opm/simulators/utils/MPIPacker.cpp, opm/simulators/utils/MPIPacker.hpp, opm/simulators/utils/SerializationPackers.cpp, opm/simulators/utils/SerializationPackers.hpp
Same as https://github.com/OPM/opm-common/pull/4189 but for the mpi packer. Also contains a commit that is required by the former since it is extending the mempacker (hosted here as it is only used for restart serialization and we don't want to pull in boost date_time in opm-common in case you wonder).
=> MPIPacker: mark buffer const in unpacker functions

opm/simulators/timestepping/TimeStepControl.cpp
For the simple iteration timestep controller, used for both the "iterationcount" and "newtoniterationcount" timestep controller, we are currently subtracting 1 from the target iterations. This is not correct and is misleading from the time-step-control-target-newton-iterations option. For example, if one set the target to 2 Newton iterations, which works well for NLDD, the timestep will not change.
=> Set correct target iterations in SimpleIterationTimestepControl

opm/simulators/wells/WellInterface_impl.hpp
Switching to group control during local well solves may occationally lead to inconsistencies. This is for testing effect of disallowing that particular switch.
=> Testing: Disallow switcing to group controls during local well solves

opm/simulators/linalg/FlexibleSolver.hpp, opm/simulators/linalg/FlexibleSolver_impl.hpp, opm/simulators/linalg/gpuistl/SolverAdapter.hpp, tests/gpuistl/test_solver_adapter.cpp
This fixes the MPI issues with CUDA/HIP/GPUISTL that were introduced with the `GhostLastMatrixAdapter` operator. The previous design of the SolverAdapter relied on the presence of the function `getCommunication` to determine if one should run the GPU solver with MPI. This updated version now decides this on the type of communication sent in. For a general communication type, it assumes it is an MPI run, while for `Dune::Amg::SequentialInformation`, it defaults to a serial (no MPI) run. 
The upside of this change is that any new, similar issues where the interface of the operator or communication changes will be detected at compile time and not runtime.
=> Make SolverAdapter explicitly depend on the communication object

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp
The `FIP` mnemonic continues to be an alias for 'SFIP' in the current implementation, and the output layer will create the `SFIP*` arrays as copies of `FIP*` if passed only the `FIP` arrays.
To this end, make `outputFipRestart_` into a structure that tracks which of the `*FIP` mnemonics have been requested, and insert the pertinent solution arrays into the data::Solution object when needed.
---
While here, also properly initialise the output module's `bool` flags and insert blank lines in the copyright header to make it more in line with the rest of the copyright statements in this repository.
=> Implement 'RFIP' and 'SFIP' Mnemonics For RPTRST

opm/simulators/aquifers/AquiferNumerical.hpp
There is no need to update the stencil if we are skipping the cell. Also, the extensive quantities will not change while iterating over the neighbours, so that update can be moved out of the loop.
=> AquiferNumerical: speed up calculations.

opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellEval.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellBhpThpCalculator.cpp, opm/simulators/wells/WellBhpThpCalculator.hpp
In `updateThp`, the thp is set to zero if the well is stopped or set to zero rate (individual or group). This is problematic for cases where e.g., a well _temporarily_ gets assiged a zero rate from group as the zero thp subsequently will be interpreted as a thp-limit violation. This PR simply suggests to always update thp as long as the vfp is active (we have reasonnable fallbacks for zero rate vfp-interpolation).
=> Update THP also for zero-rate wells

CMakeLists.txt, CMakeLists_files.cmake, tests/gpuistl/test_gpu_ad.cu, tests/gpuistl/test_gpu_linear_two_phase_material.cu
These test just verify that AD and PiecewiseLinearTwoPhaseMaterials can be used on GPU. This is a part of supporting property evaluation on GPU
=> add ad & TwoPhaseMaterial gpu instantiation tests

flow/flow_blackoil_alugrid.cpp, opm/simulators/flow/AluGridVanguard.hpp, opm/simulators/flow/FlowProblem.hpp, opm/simulators/wells/RateConverter.hpp, regressionTests.cmake
This PR enables SFC (Space-Filling Curve) reordering in AluGrid as the default choice. The changes has been tested both with and without MPI across multiple cases from the opm-tests and opm-data!
=> add changes to fix the order

opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/flow/Main.cpp, opm/simulators/flow/Main.hpp, opm/simulators/utils/readDeck.cpp, opm/simulators/utils/readDeck.hpp, python/simulators/PyMain.hpp
in the python simulator we cannot make this decision up front since the schedule can be modified from python code so we have to do the safe thing
Downstream of https://github.com/OPM/opm-common/pull/4234
=> changed: don't store schedule keywords unless required in simulators

opm/simulators/flow/FlowProblemComp.hpp
the master branch is 1.e-2, which is too slack. It might be a mistake introduced during the refactoring.
=> set newton tolerance to be 1.e-7 for compositional running

regressionTests.cmake, tests/update_reference_data.sh
Thus these options have had no effect.
=> fixed: missing TEST_ARGS in test specifications

opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.cpp, tests/test_ThreePointHorizontalSatfuncConsistencyChecks.cpp
These are supposed to verify that the displacing saturation is strictly between the critical and the maximum saturation values.
Introduced in #5573, found while adding unit tests to #5592.
=> Fix Lower Bound Conditions for Three Point Checks

opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp, opm/simulators/wells/WellInterface_impl.hpp
Unfortunately #5613 not only solved problems, but also created a few. 
As a (hopefully) temporary solution, this PR reverts to behaviour before 5613 by default, but adds parameter `check_group_constraints_inner_well_iterations_` which if set to `false` includes changes in 5613.
=> Revert #5613 but keep as option

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp, opm/simulators/flow/ExtraConvergenceOutputThread.cpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/timestepping/ConvergenceReport.cpp, opm/simulators/timestepping/ConvergenceReport.hpp, opm/simulators/wells/StandardWellEval.cpp
This PR introduces a new convergence monitoring feature to improve the robustness and efficiency of the simulator. It is based on the following publication:
Lie, K., Moyner, O., Klemetsdal, Ø., Skaflestad, B., Moncorgé, A., & Kippe, V. (2024). Enhancing Performance of Complex Reservoir Models via Convergence Monitors. ECMOR, 2024(1), 1-9. (https://doi.org/10.3997/2214-4609.202437057)
The convergence monitoring system tracks the convergence behaviour across iterations, applying penalties for non-convergence. If the total penalty count exceeds the specified cut-off limit, the simulator will cut the timestep.
This feature allows early-exiting for steps that are not converging, saving wasted iterations and assembly.
This is the first version that will be iterated on before considering to …
=> Convergence monitors

opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/Transmissibility.hpp, opm/simulators/flow/Transmissibility_impl.hpp
In that case processEclipseFormat will create NNCs over the pinched out cells with correct transmissibilities. Those NNCs are marked as being created in PINCH and used to overwrite calculated transmissibilties for the horizontal intersections (transmissibilities of normal NNCs are usually added).
Note that the transmissibilities (without the multipliers) do not change later. Only the multipliers can change them in the schedule and that will still happen to some extend. Canges of MULTZ for pinched out cells will currently not be honored.
This is tested to work for all provided test cases.
Needs OPM/opm-common#4181 and OPM/opm-grid#756
=> Correctly treat transmissibilities for PINCH option(4) ALL.

opm/simulators/utils/UnsupportedFlowKeywords.cpp
The keyword's implementation has reached a point where we can justify its addition to the simulator's feature set.
=> Enable EQUALREG for Array Operations

opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/WellFilterCake.cpp, opm/simulators/wells/WellFilterCake.hpp
Also report actual thickness for radial case
=> Handle cleaning of filter cake in a more intuitive way

opm/simulators/flow/EclWriter.hpp
In particular,
- Split some long lines
- Mark objects `const` where possible
- Reduce scope of objects
- Add braces to single statement control structures
- Prefer pre-increment
- Prefer type deduction for induction variables
=> Varnish EclWriter::beginRestart() Implementation

opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/gpuistl/GpuSparseMatrix.cpp, opm/simulators/linalg/gpuistl/GpuSparseMatrix.hpp, opm/simulators/linalg/gpuistl/OpmGpuILU0.cpp, opm/simulators/linalg/gpuistl/OpmGpuILU0.hpp, opm/simulators/linalg/gpuistl/detail/deviceBlockOperations.hpp, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/ILU0Kernels.cu, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/ILU0Kernels.hpp
This PR introduces a mixed precision version of ILU0 on the GPU.
By storing the factorized ILU matrix in float the apply function will be sped up as the memory transfers needed are faster. To ensure high accuracy the factorization is still computed in double, the result is just casted down later, and the result is casted back up to double inside the apply when the values are needed for computation. This has been shown to give significant speedups on very large cases (1.4 apply speedup on 8M cell spe11c), while there is little to none iteration count increase. This has been tested on spe1, spe11c (1M and 8M cells), Norne, and Sleipner.
| ILU0 version (GPU = Pro W7900)       | SPE1 (LIT) | SPE1 (NIT) | SPE1 (Apply) | SPE11C 1M (LIT) | SPE11C 1M (NIT) | SPE11C 1M (Apply) | SPE11C 8M (LIT) | …
=> Add mixed precision ilu0 on gpu

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/linalg/ISTLSolver.hpp, opm/simulators/linalg/WellOperators.hpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWellEquations.cpp, opm/simulators/wells/MultisegmentWellEquations.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWellEquations.cpp, opm/simulators/wells/StandardWellEquations.hpp, opm/simulators/wells/StandardWell_impl.hpp
The PR addresses the following changes:
1. Make well equations use only perforated cells. Previously, the B and C equations for the well equations had dimensions of the total number of cells but with only non-zero elements for the perforated cells. After this fix it only uses the perforated cells. This requires the global input vectors and matrices in the well operators to be mapped to a local vector for only the perforated cells.
2. Introduce a well operator for NLDD domains, such that when applying the well operator for NLDD, the necessary mapping from global cell indexes to the NLDD subdomain indexes is done and the well apply is only applied to wells on that is in the domain.
These two changes, has made these two new features possible:
1. Remove the need for using add well …
=> Remove the need for add well contributions to matrix for NLDD

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWellEquations.cpp, opm/simulators/wells/MultisegmentWellEquations.hpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellEval.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWellEquations.cpp, opm/simulators/wells/StandardWellEquations.hpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellEval.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
The `num_cells` argument is no longer used (and should not have been there to begin with as cells is already an argument and can be used to get the number of cells). This removes the warnings that #5341 introduced.
=> Remove unused num_cells argument from well equations

CMakeLists_files.cmake, opm/simulators/utils/satfunc/SatfuncCheckPointInterface.hpp, opm/simulators/utils/satfunc/ScaledSatfuncCheckPoint.cpp, opm/simulators/utils/satfunc/ScaledSatfuncCheckPoint.hpp, opm/simulators/utils/satfunc/UnscaledSatfuncCheckPoint.cpp, opm/simulators/utils/satfunc/UnscaledSatfuncCheckPoint.hpp, tests/test_SatfuncCheckPoint.cpp
This PR introduces a set of callback functions, packaged in an abstract base class `SatfuncCheckPointInterface<Scalar>`, for querying and populating the saturation function end-points that get probed by the individual consistency checks.  Member function
```
SatfuncCheckPointInterface::pointID(cellIdx)
```
translates the active cell index `cellIdx` into a point ID, assumed to be unique on at least the current MPI rank.  This function will return `nullopt` if the `cellIdx` is not eligible for this particular end-point.  This typically happens for the region based tabulated (unscaled) saturation function checks when the `cellIdx` happens to be in a region that's already been visited.  Member function
```
SatfuncCheckPointInterface::populateCheckPoint(cellIdx, endPoints)
```
fills in …
=> Add Protocol for Populating Saturation Function End Points per Cell

opm/simulators/flow/EclWriter.hpp
The `globalIdx` generated by `localIdxToGlobalIdx()` is in the range zero to number of active cells in global model, not zero to number of active cells on rank.  Using `globalIdx` as an argument to `set*TracerConcentration()` therefore ends up indexing out-of-bounds for the internal arrays in the tracer model object in parallel restarted simulation runs.
The problem has been present since the restart support for tracers was added in commit e9c45f4ca (PR #3708).
This commit switches to using the `elemIdx` instead, as we already do when calling the output module's `setRestart()` member function. Following this, we are able to restart the standard Norne benchmark case (NORNE_ATW2013.DATA) in parallel.  The numerical results for the tracer concentrations are, however, a little questionable …
=> Use Rank's Local Cells for Tracer Concentration Restart

opm/simulators/wells/MultisegmentWell_impl.hpp
Sets the correct start of memcpy to 
```cpp
for (int ii = 0; ii < num_seg; ++ii) {
const auto start = it + ii * num_eq;
```
such that it starts from `segment_index * num_eq` instead of `num_seg * num_eq`.
Note that this function is only used when using the NLDD nonlinear solver, where we have an unconverged local NLDD domain, which has a multisegment well on that domain. This was exposed after #5341 was merged which motivated to try NLDD with more complex cases.
=> Fix memory bug in setPrimaryVars for MSW

opm/simulators/aquifers/BlackoilAquiferModel_impl.hpp
to avoid shadowing warnings with clang
=> rename capture variable

CMakeLists_files.cmake, opm/simulators/utils/satfunc/SatfuncConsistencyCheckManager.cpp, opm/simulators/utils/satfunc/SatfuncConsistencyCheckManager.hpp, opm/simulators/utils/satfunc/SatfuncConsistencyChecks.cpp, opm/simulators/utils/satfunc/SatfuncConsistencyChecks.hpp, tests/test_SatfuncConsistencyCheckManager.cpp, tests/test_SatfuncConsistencyChecks.cpp, tests/test_SatfuncConsistencyChecks_parallel.cpp
This PR introduces a new top-level "manager" for all saturation function consistency checks.  This component associates collections of saturation function curves with per-cell or per-region end-point definitions and provides an inteface to run all checks for all interior entities (i.e., active cells) in a DUNE grid view.  We form one set of `SatfuncConsistencyChecks` objects for each `SatfuncCheckPointInterface<>` object, thereby enabling running the same set of consistency checks for both the unscaled, tabulated, per-region saturation functions and the per-cell scaled saturation functions.  The latter is executed only if the run enables end-point scaling for the saturation functions.
As an aid to enabling the pertinent individual checks, we add a private factory function which considers …
=> Add Top Level Container for Saturation Function Consistency Checks

opm/simulators/flow/FlowProblem.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/flow/FlowProblemParameters.cpp, opm/simulators/flow/FlowProblemParameters.hpp, opm/simulators/utils/satfunc/SatfuncConsistencyCheckManager.hpp, tests/test_equil.cpp
Currently opt-in by the new parameter `CheckSatfuncConsistency` (command line option `--check-satfunc-consistency`), this PR hooks up the `SatfuncConsistencyCheckManager<>` pass to the `FlowProblem`.  I hope to make the parameter be "opt-out" at some point, but for now the new pass breaks one of the cases in our `benchmark` suite.
The new parameter `--num-satfunc-consistency-sample-points` allows the user to select the maximum number of reported failures for each individual consistency check.  By default, the simulator will report at most five failures for each check.
We check the unscaled curves if the run does not activate the end-point scaling option and the scaled curves otherwise.  At present we're limited to reversible and non-directional saturation functions for the drainage …
=> Enable New Saturation Function Consistency Checks

opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/OutputBlackoilModule.hpp
This removes and fixes some parts in the restart that asserts that there is an oil component to allow for restarts for gas-water cases. 
@bska I add the release tag since this is a bug fix.
=> FIX gas-water restart

opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/utils/DamarisVar.cpp
- Remove an unused capture
- Restructure to avoid a capture that causes warnings in clang but is required by g++-14
=> Some lambda fixes

opm/simulators/utils/DamarisVar.cpp
clang doesn't want us to capture t1, and g++-14 requires us to capture t1. this workaround avoids warnings with both.
---
This PR back-ports parts of PR #5682 to the release branch ahead of the 2024.10 OPM release.
=> avoid declaring t1 outside lambda

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp
without invalidating the output data, many quantities will not be evaluated/updated and output to RESTART files.
=> in flowexp_blackoil, invalidate output data after solution is updated

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp
Without invalidating the output data, many quantities will not be evaluated/updated and output to RESTART files.
---
Backport of pr #5664 to 2024.10 release branch.
=> Mark Solution Data as Invalid at the End of a Time Step

opm/simulators/flow/ActionHandler.cpp
There's no need for us to invoke the `WellMatcher` constructor when the `Schedule` object already knows how to do that.
Missed opportunity in commit ff51c2d7e (PR #3050).
=> Get WellMatcher Object Directly From Schedule

opm/simulators/flow/CpGridVanguard.hpp, opm/simulators/flow/FlowBaseVanguard.hpp, opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/flow/FlowGenericVanguard.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/GenericCpGridVanguard.hpp, opm/simulators/wells/WellState.cpp
This intends to fix a couple of issues introduced with #5609:
* Properly add inactive wells to all ranks with connections (but not others) ( ParallelWells <string,bool> instead of <string,int> )
* Also inform the users about these wells (and where they end up)
* Disallow splitting inactive wells for parallel restarts (currently causes issues, will look into it)
* Also introduces a command-line option to disallow this for non-restarts.
Sorry for the mess!
=> Bugfixes #5609

opm/simulators/flow/GenericThresholdPressure.hpp
in GenericThresholdPressure
I saw some compiler dependent behavoir related to this with the flowexp_comp simulator.
=> enableThresholdPressure_ initialized to be false

opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/utils/ParallelSerialization.cpp, tests/test_ParallelSerialization.cpp
now that Schedule(State) properly serializes the member
Downstream of https://github.com/OPM/opm-common/pull/4290
=> add missing ReservoirCouplingInfo.hpp includes

opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp
This commit switches to using the `welpi_wells` information from the `SimulatorUpdate` structure (OPM/opm-common#4292) as a basis to decide the wells for which it is safe/sufficient to update only the CTFs in response to an ACTIONX block running WELPI.  To this end, we split the actions of the existing member function `updateEclWells()` into two parts,
1. `updateEclWellsConstraints()`
2. `updateEclWellsCTFFromAction()`
in which the first handles well status and well control updates while the second deals with CTF updates in response to WELPI.  We do not run the second part if the well structure has changed&ndash;e.g., due to COMPDAT or WELOPEN&ndash;since the update loop depends on a static connection topology.
We add a new member function `wellUpdateLoop()` which will traverse a sequence …
=> Handle WELPI from ACTIONX Separately From Constraints

opm/simulators/flow/ActionHandler.cpp, opm/simulators/flow/ActionHandler.hpp
This is in preparation of making the match set for `ACTIONX` more general.  Having a fully private `WELPI` framework means we can change the types more freely without having to rebuild all users of `ActionHandler`.
While here, also add Doxygen-style documentation to the `ActionHandler`.
=> Make WELPI Infrastructure for ACTIONX Fully Private

CMakeLists_files.cmake, opm/simulators/flow/Main.cpp, opm/simulators/flow/Main.hpp, opm/simulators/linalg/gpuistl/device_management.cpp, opm/simulators/linalg/gpuistl/device_management.hpp, opm/simulators/linalg/gpuistl/set_device.cpp, opm/simulators/linalg/gpuistl/set_device.hpp
Slight improvement in use of gpuISTL to show what device is used in the simulation
TODO: make sure we get the output from all the ranks
=> Print gpus used on simulator startup

opm/simulators/wells/WellInterface_impl.hpp
As the code is now switching to/from GRUP in the local iterations is problematic as the group reduction rates (the combined rates of all wells that are not on group rate) are not updated. With this PR, individual controls are not checked if the well is on GRUP if check-group-constrains-well-iterations=false. 
I would also suggested to set check-group-constrains-well-iterations=false as default while fixing the reduction rate.
=> dont switch from GRUP if check_group_constrains_well_iterations=false

opm/simulators/flow/AluGridLevelCartesianIndexMapper.hpp
Clang gets chatty. As I'm not entirely sure what the plan is I have suppressed the warning using maybe_unused.
If this member is not required, we should perhaps consider removing it instead.
=> quell unused private member warning

opm/simulators/flow/ActionHandler.cpp, opm/simulators/flow/EclGenericWriter_impl.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp
Following PR OPM/opm-common#4317, the functions no longer use the `episodeIdx` or `Schedule` parameters.  Update callers accordingly.
While here, split some long lines and remove unneeded local objects.
=> Chase API Update of UDQConfig's Evaluation Functions

examples/problems/co2injectionproblem.hh, opm/models/blackoil/blackoilpolymermodules.hh, opm/models/flash/flashindices.hh, opm/models/immiscible/immiscibleindices.hh, opm/models/ncp/ncpindices.hh, opm/models/ncp/ncpmodel.hh, opm/models/ptflash/flashindices.hh, opm/models/pvs/pvsindices.hh, opm/simulators/flow/RegionPhasePVAverage.cpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/utils/MPIPacker.hpp
- use constexpr instead of anonymous enums
- avoid use of std::is_pod_v
- mark comparison operator const
- add some casts to avoid enum arithmetics
=> Quell c++-20 warnings

opm/simulators/wells/GasLiftSingleWell_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
This gives a 10 times speed up of the gaslift optimization for many cases as we dont repeatedly try to compute bhp from thp for alq values that dont converge anyway.
=> Dont iterate when computing bhp from thp for computing of the well potentials for gaslift optimization

opm/simulators/flow/ActionHandler.cpp
Following OPM/opm-common#4322 this is no longer needed so we can go back to using `const` objects.
=> Don't Pass Action::Result By Value Into Add_Run()

opm/simulators/wells/WellFilterCake.cpp
A hybrid filter cake model where the cake thickness is computed assuming linear geometry. This thickness is then used to compute a damage skin in radial geometry. Requested for comparisons with some other tools.
=> Add LINRAD (hybrid linear-radial) filter cake model

opm/models/utils/alignedallocator.hh
One cannot just add another license when there are no substantial creative changes and you are changing existing code only.
There is no need either as we can use code under Boost license next to GPL.
=> Removed GPL copyright header from licensed under Boost license.

opm/simulators/wells/MultisegmentWellEquations.cpp, opm/simulators/wells/StandardWellEquations.cpp
Gpubridge separate wells implementation requires the global index. Fix needed after the update to using local indexes introduced in PR #5341
=> Fix index bug in gpubridge separate wells

CMakeLists.txt, CMakeLists_files.cmake, opm/simulators/linalg/gpuistl/GpuBuffer.cpp, opm/simulators/linalg/gpuistl/GpuBuffer.hpp, tests/gpuistl/test_gpuPvt.cu
Adds test verifying that new classes work on the GPU, classes that are now tested include:
The test depends on new functionality in https://github.com/OPM/opm-common/pull/4222
- Constants
- IdealGas
- Brine_CO2
- UniformTabulated2DFunction
- BrineDynamic
- CO2
- SimpleHuDuanH20
- Co2GasPvt
=> Gpu support co2gaspvt

opm/simulators/linalg/gpubridge/MultisegmentWellContribution.hpp, opm/simulators/linalg/gpubridge/WellContributions.hpp
The file needs the defines in `umfpack.h` further down the file which is not inside any `#if`.
=> Remove #if HAVE_SUITESPARSE_UMFPACK in WellContributions.hpp

tests/make_failure_report.sh
Noticed https://ci.opm-project.org/job/opm-simulators-PR-builder/6898/console failed due to no failures..
=> fixed: don't fail build if there are no failures

opm/simulators/utils/readDeck.cpp
Currently, some errors from parsing, like topology errors when processing sections, are not included in the log files or the final standard output before aborting. If there are no other errors the user will only see a line like this without further explanation: "Error: Unrecoverable errors while loading input:"
With this commit now print the string returned by ErrorGuard::dump to the logs and standard output. Hence the user might see somthing like this:
```
Error: Unrecoverable error while loading input: SECTION_TOPOLOGY_ERROR: The GRID section must be followed by EDIT or PROPS instead of GRID at: SPE1CASE2_ERR.DATA, line: 108
```
Depends on OPM/opm-common#4305.
=> Make sure all errors from parsing show up in the log files.

opm-simulators-prereqs.cmake
This is what DUNE uses since 2015 makes OPM modules usable as DUNE modules in all cases.
Downstream of OPM/opm-common#4349
=> Cmake: Use upper case for COMPONENTS of FindSuiteSparse

opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp
if one well on individual control (typical thp/bhp) in a group struggles to converge
it may lead to problems for the other wells in the group
we dont want to shut all the wells in a group only the one creating the problems.
=> dont shut well with GRUP control that struggles to converge

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/GasLiftSingleWellGeneric.cpp, opm/simulators/wells/GasLiftSingleWellGeneric.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
The current master version of well test (WTEST keyword) with gas lift typically resulted in max ALQ given to well after re-opening. With this PR we use gas lift facilities to increase ALQ until max. incremental gradient instead. Running the gas lift test cases in [opm-tests](https://github.com/OPM/opm-tests/tree/master/gaslift) show that large ALQ spikes after re-opening well(s) are avoided with the PR compared to master.
=> Well testing using gas lift facilities

opm/simulators/wells/BlackoilWellModel_impl.hpp
The `updateWellStateWithTarget` for all wells can be problematic here. In particular, this is the case for thp-wells, since in this case `updateWellStateWithTarget` only provides an _initial guess_ well-state. This means that at this stage, we may have converged thp-wells that after going through `updateWellStateWithTarget` are no longer convereged, which again may prevent overall convergence. 
I can't see that `updateAndCommunicateGroupData` changes any well control-modes, so there should be no reason to update the target of wells not under group control here?
This PR just skips the `updateWellStateWithTarget` for wells not under group control
=> Only update target of group-controlled wells during updateAndCommunicate

opm/simulators/wells/WellBhpThpCalculator.cpp
Especially fro cases with gaslift the .PRT file is flooded with THP related output. I think it make sense to move this to the debug file since is this is mostly of interest when debugging.
=> Move debug output from thp calcuations from .PRT to .DBG

opm/simulators/utils/readDeck.cpp
This is the minimal change needed for https://github.com/OPM/opm-common/pull/4123 in to build. The real companion PR of https://github.com/OPM/opm-common/pull/4123 is https://github.com/OPM/opm-simulators/pull/5620. But it has not been reviewed yet and can be merged later. I am putting this in draft mode until https://github.com/OPM/opm-common/pull/4123 is ready to be merged. When that is merged, this one should be merged immediately after.
=> Update Schedule constructor

opm/simulators/utils/readDeck.cpp
No longer calling dump() means we avoid the extra dumping to stderr of the warnings and errors.
Downstream from OPM/opm-common#4362
=> Use formattedErrors() and simplify.

opm/simulators/linalg/OwningTwoLevelPreconditioner.hpp, opm/simulators/linalg/twolevelmethodcpr.hh
When using two level preconditioners in OPM (CPR like), it consists of two parts:
1. Extracting the pressure system and applying an AMG cycle on the scalar system.
2. Apply a block preconditioner on the complete system.
The second part is typically an ILU0 preconditioner, where we must perform a factorisation based on the values of the matrix. When the matrix values changes (but not the sparsity), this factorisation needs to be recomputed.
At the moment, this ILU0 preconditioner was recreated every single Newton iteration, which involves recreating the memory and other optimisations. This is not necessary, and only an update is needed. Which is what this PR changes it to. This is especially important when we start using GPU preconditioners with CPR, as these GPU preconditioners typically …
=> Update second stage preconditioner for CPR instead of recreate

opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellGroupHelpers.hpp
1) Dont allow wells to change to GRUP when iter >NUPCOL
2) Update VREP even for iter > NUPCOL if it changes significantly. For now hardcoded to relative change > 0.01 (TODO make this a parameter. Update: DONE)
TODO
=> Changes in how the simulator handles NUPCOL

opm/simulators/wells/BlackoilWellModel_impl.hpp
if umfpack encounters a singular matrix on any process, the exception propagated up across communication boundaries leading to deadlock as the other processes tried to do global reductions.
=> fixed: well model could deadlock

opm/simulators/flow/GenericCpGridVanguard.cpp
This adds a new option to partition for a parallel run.
Running flow with the parameter --partition-method=3 will use Zoltan partitioner with the grid represented by a graph (class GraphOfGrid [OPM/opm-grid#790](https://github.com/OPM/opm-grid/pull/790). All cells potentially perforated by a  well are represented by a single vertex, therefore the partitioning is unable to split a well into several processes.
This should lead to better partitioning results on problems with a complex well structure, where other partitioners might split wells over several processes after which some well cells have to be remapped (when distributed wells are not allowed).
=> Zoltan partitioner with all perforated cells of a well merged to one vertex

opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp
this can be used by various Schedule keywords even if FIP is not in RPTSOL
=> fixed: always calculate initial FIP

opm/simulators/linalg/setupPropertyTree.cpp
The CPR AMG implementation in OPM has two sets of pre/post smoothing parameters:
1. AMG-level smoothing parameters that control smoothing operations between AMG levels
2. Fine-level smoothing parameters that control how many times the block preconditioner (currently ILU0) is applied before and after the AMG V-cycle
While the AMG-level parameters were already exposed, the fine-level parameters were hardcoded in `OwningTwoLevelPreconditioner` (defaulting to pre_smooth=0, post_smooth=1) and not visible in the JSON configuration tree that is printed in the DBG file.
This PR exposes these parameters by adding them to the CPRW and CPR setup, such that the resulting linear solver JSON tree will show up in the DBG file.
```json
{
"maxiter": "20",
"tol": "0.0050000000000000001",
"verbosity": "0", …
```
=> Expose finesmoother pre/post smooth parameters in CPR setup

compareECLFiles.cmake, opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWellEquations.cpp, opm/simulators/wells/WellState.cpp, opm/simulators/wells/WellState.hpp, parallelTests.cmake, tests/run-parallel-regressionTest.sh, tests/test_wellstate.cpp
This PR is based on https://github.com/OPM/opm-simulators/pull/5680.
This PR enables simulations with MSWell distributed across several processes. The PR https://github.com/OPM/opm-simulators/pull/5680 covered the assembly of the system, this PR covers the straightforward option of solving.
This PR adds communication when multiplying x_well with the matrix B of the Schur complement as explained on slide 13 of [24-10-21-MSWells.pdf](https://github.com/user-attachments/files/17869352/24-10-21-MSWells.pdf).
This approach is the easiest way to solve, using preconditioners for the well system is to be implemented in the future.
I've added two tests comparing the SMRY files of a parallel and a sequential simulation with distributet MSWells. These tests fail in the PR …
=> Feature/ms wells - part 2: Solving, straightforward option

opm/simulators/timestepping/AdaptiveTimeStepping.hpp
This PR is for testing. Both the time-stepping, convergence and well models has improved since this hard-coded limit was enforced. Is it time to remove it? The initial testing I have done indicates so, but more testing is needed.
=> remove 16 days restriction for timestep in predicition mode

opm/simulators/utils/MPIPacker.cpp
Avoids losing resolution (ms to s).
Downstream of OPM/opm-common#4374.
=> Do not serialize time_point via time_t.

opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp
also allows to drop the default value for the tuningUpdater callback
=> remove unused fipnum argument

opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/utils/UnsupportedFlowKeywords.cpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/GasLiftGroupInfo.cpp, opm/simulators/wells/GasLiftStage2.cpp, opm/simulators/wells/GasLiftStage2.hpp, opm/simulators/wells/SingleWellState.hpp, opm/simulators/wells/WellAssemble.cpp, opm/simulators/wells/WellGroupConstraints.cpp, opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterfaceFluidSystem.cpp, opm/simulators/wells/WellInterface_impl.hpp, opm/simulators/wells/WellState.cpp, regressionTests.cmake
This adds support for WCYCLE. This is a keyword for cycling wells on / off, with time step control and efficiency factor scalings. Support for all of this is a bit of a layer violation in flow, I have tried to keep it as tight as possible, but it has to be split in two parts as we have to select time step before we open / close wells. In particular I have to provide a callback to look into the schedule to check if a well will be opened at a report step in order to avoid unwanted cycling.
Downstream of https://github.com/OPM/opm-common/pull/4371
=> added: support WCYCLE

compareECLFiles.cmake, parallelTests.cmake
This PR contains regression test for the flow option --partition-method=3. This partitioning method represents each well by one cell, therefore a well can not be split over several subdomains by the partitioner. The regression test uses SPE3CASE1 which has wells that have multiple cells (unlike e.g. spe1 or spe5).
Since there is already a test for SPE3CASE1, we got a name conflict with the new test. We extended the macro generating the test to accept the POSTFIX keyword, which enabled us to distinguish two tests (with different partitioners) having the same CASENAME and FILENAME.
=> Regression test for --partition-method=3

opm/simulators/flow/FlowProblemBlackoil.hpp
Unfortunately, for CpGrid with LGRs we need to skip - for now - the computation of initial FIP. This affects the "always calculate initial FIP" done in OPM/opm-simulators#5784 in the sense that CpGrid with LGRs is excluded for the moment.
=> Do not write initial FIP for CpGrid with LGRs for now

opm/simulators/flow/FlowGenericProblem.hpp, opm/simulators/flow/FlowGenericProblem_impl.hpp, opm/simulators/flow/FlowProblem.hpp, opm/simulators/utils/PartiallySupportedFlowKeywords.cpp
If ROCKOPTS item 2 is equal to STORE, initial pressure is used in ROCK and ROCKTAB. For ROCK, the reference pressure input is replaced by initial pressure of the cell, while for ROCKTAB, effective pressure  (i.e. P_eff = P - P_init) will be used in the ROCKTAB table. Note that OVERBURD is ignored if ROCKOPTS item 2 is equal to STORE.
Depends on https://github.com/OPM/opm-common/pull/4370
=> Use initial pressure if ROCKOPTS item 2 is STORE

opm/simulators/linalg/HyprePreconditioner.hpp
HYPRE_Bigint are 64 bit integers on some platforms by default, and can be configured as such in any case. The HYPRE API asks for HYPRE_BigInt* so it is better to use that type rather than int.
=> Necessary to compile with my Hypre install.

opm/simulators/flow/AluGridLevelCartesianIndexMapper.hpp, opm/simulators/flow/AluGridVanguard.hpp, opm/simulators/flow/PolyhedralGridVanguard.hpp
Minor refactor was made to LevelCartesianIndexMapper AluGrid specialization, removing the first unused argument from its constructor.
Design issue identified with the help of OPM/opm-simulators#5712.
Not relevant for the Reference Manual.
=> LevelCartesianIndexMapper constructor for AluGrid taking only a grid as an argument

opm/simulators/wells/MultisegmentWellEquations.cpp, parallelTests.cmake
Now I can use solver-max-time-step-in-days=15 instead of solver-max-time-step-in-days=10 in the test msw-simple (this test without the fix from this PR is failing in #5821)
=> Fix really stupid communication mistake

opm/models/discretization/common/fvbasediscretization.hh
Iterate over the grid and evaluate initial condition skips non-interior cells, so it seems not necessary to double-check the Interior partition type before adding dofVolume to gridTotalVolume_
Not relevant for the Reference Manual
=> Remove nnecessary check isInterior

opm/simulators/linalg/gpuistl/GpuDILU.cpp, opm/simulators/linalg/gpuistl/OpmGpuILU0.cpp, opm/simulators/linalg/gpuistl/detail/autotuner.hpp
This PR refines the autotuning output a bit.
Additionally it changes the thread-block size used for the lower solve when tuning the upper triangular solve. That fixes confusing output that could make it look like the tuning was making the triangular solve slower when it wasn't.
=> adjust output and parameters in gpu autotuner

CMakeLists_files.cmake, opm/simulators/timestepping/AdaptiveTimeStepping.cpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
So much code here that an impl file is advantageous. Also the approach taken in https://github.com/OPM/opm-simulators/pull/5620
=> split AdaptiveTimeStepping to use an impl file

opm/models/blackoil/blackoilprimaryvariables.hh, opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
This PR saves 75% on the enum storage in the primary variable objects without any other changes. One could probably devise a way to store these flags with fewer bits, but I am not sure it would be worth it.
=> Reduce size of enums to save 15 bytes per cell.

CMakeLists_files.cmake, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGasLift.cpp, opm/simulators/wells/BlackoilWellModelGasLift.hpp, opm/simulators/wells/BlackoilWellModelGasLift_impl.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/GasLiftSingleWell.hpp, opm/simulators/wells/GasLiftSingleWell_impl.hpp, opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/WellInterface.hpp, tests/test_RestartSerialization.cpp, tests/test_glift1.cpp
move to has-a instead of is-a for modelling in BlackoilWellModel
=> changed: move GasLift code in BlackoilWellModel to separate class

opm/simulators/wells/BlackoilWellModelGasLift.hpp, opm/simulators/wells/BlackoilWellModelGasLift_impl.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
Also make one more if constexpr.
Error message was like this example:
```
/Users/atgeirr/opm/src/opm-simulators/opm/simulators/wells/BlackoilWellModelGasLift_impl.hpp:113:23: error: constexpr if condition is not a constant expression
113 |         if constexpr (this->glift_debug) {
|                       ^~~~~~~~~~~~~~~~~
```
=> Fix clang complaints about incorrect constexpr usage.

opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/gpuistl/GpuDILU.cpp, opm/simulators/linalg/gpuistl/GpuDILU.hpp, opm/simulators/linalg/gpuistl/detail/deviceBlockOperations.hpp, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/DILUKernels.cu, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/DILUKernels.hpp, tests/gpuistl/test_GpuDILU.cpp
This PR adds mixed precision to GPU DILU in the style of GPU ILU0 (https://github.com/OPM/opm-simulators/pull/5552)
Basically add a flag that will store the factorization as a float after it is computed in double, cast it back to double inside the preconditioner apply to maintain maximum precision while halving the memory read required in the apply
=> Add gpudilu mixed precision

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp
and also for permanently inactive wells that are split across processors (partition method 3 issue only).
To see the issue for shut distributed wells, run attached example ([shut-distributed-wells-rft-issue.tar.gz](https://github.com/user-attachments/files/18209079/shut-distributed-wells-rft-issue.tar.gz)) as:
>```sh
> mpirun -np 4 flow \
>    --external-partiton=part4.txt \
>    --allow-distributed-wells=true \
>    TEST-RFT-SHUT-DISTRIBUTED-WELL.DATA
>```
and for inactive wells split across processors with partition method 3 (where root does not appear to contain all cells):
>```sh
> mpirun -np 3 flow \
>    --partition-method=3 \
>    --allow-distributed-wells=true \
>    TEST-RFT-INACTIVE-SPLIT-WELL-PARTMETHOD3.DATA
>```
In these cases current master outputs 0 for RFT data for some …
=> Fix RFT output for shut distributed wells 

opm/simulators/flow/ActionHandler.cpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModelRestart.cpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
this to avoid confusion as there is already a hasWell in BlackoilWellModelGeneric which queries the schedule.
1) the one in BlackoilWellModelGeneric is renamed to hasLocalWell, as this queries list of all wells having connections on rank
2) the one in BlackoilWellModel is renamed to hasOpenWell, as this queries list of all open wells having connection on rank
Also moves the definition of hasOpenWell to the generic class
=> Fix BlackoilWellModel::hasWell mixups

tests/gpuistl/test_gpuPvt.cu, tests/gpuistl/test_gpu_linear_two_phase_material.cu
To avoid confusion with move semantics in C++ `move_to_gpu` is renamed to `copy_to_gpu` as the movement of data to the GPU does not invalidate the existing CPU copy.
Should be updated in tandem with https://github.com/OPM/opm-common/pull/4420
=> refactor move_to_gpu

opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/flow/FlowGenericVanguard.hpp, parallelTests.cmake
The new loadbalancer approach will create a graph representing the grid where all cells that a well perforates are represented by one vertex. The weight of that cell will be the number of cells it represents. Also the weights of the faces will be added up due to the merging of cells. A cell that is not perforated by any well is still represented by one vertex with weight one.
In the old default approach the number of vertices in the grid was equal to the number of cells. Vertex weights were not used. For each well we added an edge between all its perforated cells for which we did set a very edge weight to force the cells to the same process during partitioning.
For realistic cases we have seen improvements across the board due to this. E.g. this resolved convergence issues on hard cases. …
=> Switch default load balancer to Zoltan with vertex = all cells of a well

opm/simulators/flow/BlackoilModel.hpp
No idea why this was public in the first place, but in any case there does not seem to be a reason any longer.
=> BlackoilModel: make wasSwitched_ private

python/docstrings_simulators.json
This PR is to test the automatic build of the python documentation at https://github.com/OPM/opm-python-documentation.
=> Add missing return type to check_simulation_finished function of BlackOilSimulator.

CMakeLists_files.cmake, opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/BlackoilModelConvergenceMonitor.cpp, opm/simulators/flow/BlackoilModelConvergenceMonitor.hpp, opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp
In particular this allows better encapsulation of relevant member variables.
=> BlackoilModel: move to has-a instead of is-a modelling of penalty cards

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp
typetag less parameter system now allows us to initialize these variables in class that holds them.
=> OutputBlackoilModule: move some more code to GenericOutputBlackoilModule

opm/simulators/wells/BlackoilWellModel_impl.hpp, regressionTests.cmake
This fixes WCYCLE when there are multiple WCYCLE blocks, multiple cycling well and these are combined with manual WELOPEN statements. Downstream of https://github.com/OPM/opm-common/pull/4426 and requires https://github.com/OPM/opm-tests/pull/1282
=> Fix WCYCLE for multiple blocks

examples/problems/co2ptflashproblem.hh, opm/models/ptflash/flashintensivequantities.hh, opm/simulators/flow/FlowProblemComp.hpp
Use the changes in https://github.com/OPM/opm-common/pull/4429 to accommodate for other EOS formulations given by the keyword `EOS`. Available EOS formulations are now `PR`, `PRCORR`, `RK` and `SRK`.
=> Compositional simulations with more cubic EOS formulations

opm/simulators/flow/FlowUtils.cpp
Avoid 'EclDeckFileName specified multiple times' in case of empty positional arguments.
=> Skip empty positional arguments

opm/simulators/wells/BlackoilWellModelRestart.cpp, opm/simulators/wells/WellState.hpp
Fallout from https://github.com/OPM/opm-simulators/pull/5751  (causes segfault if any well present in the restart is found to be inactive in the restarted run).
=> Bugfix: Upon restart, do not try to restore segment info for inactive wells

opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/utils/ParallelSerialization.cpp, opm/simulators/utils/PartiallySupportedFlowKeywords.cpp, opm/simulators/utils/UnsupportedFlowKeywords.cpp, opm/simulators/wells/GlobalWellInfo.cpp, opm/simulators/wells/GlobalWellInfo.hpp, opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellGroupHelpers.hpp, opm/simulators/wells/WellState.hpp, tests/test_ParallelSerialization.cpp
Depends on
https://github.com/OPM/opm-common/pull/4188
Sufficient to run https://github.com/OPM/opm-tests/pull/1207 where GSATPROD only interact with output and new test case https://github.com/OPM/opm-tests/pull/1286
=> Implement gsatprod

opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/discretefracture/discretefractureprimaryvariables.hh, opm/models/discretization/common/fvbaseprimaryvariables.hh, opm/models/flash/flashprimaryvariables.hh, opm/models/immiscible/immiscibleprimaryvariables.hh, opm/models/ncp/ncpprimaryvariables.hh, opm/models/ptflash/flashprimaryvariables.hh, opm/models/pvs/pvsprimaryvariables.hh, opm/models/richards/richardsprimaryvariables.hh
these were only in use for assignments to a constant. 
Instead of detouring all of these assignments through a temporary, use the base field vector assignment operator to do inplace assignments.
=> xxxPrimaryVariables: remove ctor from Scalar

CMakeLists_files.cmake
USE_XXX variables are user provided and should not be used to check whether or not a component is enabled (at least not those backed by some required library).
In particular the build system will configure a build without MPI if no mpi was found -> trouble.
Should fix nightly python packaging again, ref https://ci.opm-project.org/job/opm-nightly-pypi/1495/console
=> fixed: condition on MPI_FOUND, not USE_MPI

compareECLFiles.cmake
Even though CARFIN keyword is not fully supported yet, this PR adds the simulation run (in serial) of SPE1CASE1_CARFIN.DATA. 
Not relevant for the Reference Manual.
=> Add run SPE1CASE1_CARFIN.DATA

opm/models/parallel/mpibuffer.hh
this was being copied and it had pointer members
and change to std::size_t
=> fixed: use a vector in mpibuffer 

opm/simulators/flow/ActionHandler.cpp, opm/simulators/flow/EclGenericWriter_impl.hpp
Following PR OPM/opm-common#4433, we must now pass a `GroupOrder` object into `eval()` in order to support group name pattern matching in group level UDQ assignments.
=> Chase UDQConfig::Eval() API Change

regressionTests.cmake, restartTests.cmake
In particular
1. Activate [`UDQ_REG-02`](https://github.com/OPM/opm-tests/blob/a07d04e7f01b101eb190407584d4dcec622d5bc4/udq_actionx/UDQ_REG-02.DATA) (OPM/opm-tests#1279) as a restart test to ensure that we do not overflow the `ZUDL` character limit (PR OPM/opm-common#4422).
2. Activate [`UDQ_GRP-01`](https://github.com/OPM/opm-tests/blob/a07d04e7f01b101eb190407584d4dcec622d5bc4/udq_actionx/UDQ_GRP-01.DATA) (OPM/opm-tests#1174) as a regression test to ensure that we continue to support assigning subsets of group level UDQs (PR OPM/opm-common#4433).
=> Add Regression/Restart Tests for Recent UDQ Work

opm/simulators/flow/Transmissibility_impl.hpp
This adds multi-threading to the transmissibility calculations.
Downstream of https://github.com/OPM/opm-common/pull/4432
Downstream of https://github.com/OPM/opm-grid/pull/820
=> Add multi-threading to transmissibility calculation

opm/simulators/timestepping/AdaptiveTimeStepping.cpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
In particular allow for failed wells to shut even though they haven't failed consistently in the last 3 attempts if the time step is reduce enough already.
=> Improve well shutting logic

opm/simulators/flow/FlowGenericVanguard.cpp
When `--allowDistributedWells=true` is set in a problem with multisegment wells, program outputs a message where the command line argument `--use-multisegment-well` is misnamed.
=> Correct a keyword in a message

CMakeLists_files.cmake, flow/flow_blackoil.hpp, opm/simulators/flow/TTagFlowProblemTPFA.hpp
Makes this accessible for out-of-tree uses.
=> Install Type Tag for TPFA Flow Problems

opm/simulators/flow/python/PyBlackOilSimulator.hpp, python/simulators/PyMain.hpp
These were originally obtained through transitive includes, especially from `Main.hpp`, but that's not a stable condition if the set of transitive includes changes.
=> Add Missing Headers to Python Simulator

CMakeLists_files.cmake
Needed for `Main::runStatic<>()` to be usable out-of-tree.
=> Install More Headers

examples/problems/reservoirproblem.hh, tests/test_equil.cpp
Downstream of https://github.com/OPM/opm-common/pull/4197
=> adjust to constructor being marked explicit

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/OutputCompositionalModule.hpp
Instantiating FluidSystem<0> at this stage due to how it is implemented. 
After https://github.com/OPM/opm-simulators/pull/5882, the flowexp_comp can not be run anymore. 
Not totally sure this is the proper fix, but just bring it up here to start the conversation.
=> hacking to register the parameter ForceDisableFluidInPlaceOutput

opm/models/blackoil/blackoilintensivequantities.hh
Makes using the header from an installed location harder than it needs to be.
=> Remove Unused FMT Header

opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWell_impl.hpp
Implicit potential calculations makes a copy of the well-state and use that for initial guess. However, `WellTesting` also deals with a copy of the well-state, so when called from there we need to pass that copy as an argument (the currently used _actual_ well-state may have nonsense values at this stage and occasionally lead to convergence issues when used as initial guess)
=> Pass on current well state to (implicit) potential calculations

CMakeLists_files.cmake, opm/simulators/flow/FIPContainer.cpp, opm/simulators/flow/FIPContainer.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp
Try to clean up this code a little. Still some mysteries I haven't gotten my head around.
=> OutputBlackoilModule: add a container for the FIP data

opm/models/blackoil/blackoilintensivequantities.hh
while we are never actually here without an index, compiler cannot know since the enum is a runtime argument
```
In member function ‘constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = double; long unsigned int _Nm = 3]’,
inlined from ‘const K& Dune::FieldVector<K, SIZE>::operator[](size_type) const [with K = double; int SIZE = 3]’ at /usr/include/dune/common/fvector.hh:194:19,
inlined from ‘Opm::BlackOilPrimaryVariables<TypeTag>::Evaluation Opm::BlackOilPrimaryVariables<TypeTag>::makeEvaluation(unsigned int, unsigned int, Opm::LinearizationType) const [with TypeTag = Opm::Properties::TTag::FlowGasWaterBrineProblem]’ at /home/akva/kode/opm/opm-simulators/opm/models/blackoil/blackoilprimaryvariables.hh:216:55,
inlined from ‘void …
```
=> fixed: use if constexpr to avoid compiler warning

opm/simulators/flow/CpGridVanguard.hpp, opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/flow/FlowGenericVanguard.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/GenericCpGridVanguard.hpp
We introduce two new run-time parameters,
```
AddCorners (--add-corners=BOOL, default 'false')
NumOverlap (--num-overlap=INT, default '1')
```
that are passed on to the grid's load-balancing engine as the `addCornerCells` and `overlapLayers` settings.
---
Extracted from #5801.
=> Expose CornerCells and OverlapLayers Load Balancing Settings

opm/simulators/linalg/PropertyTree.cpp, tests/test_propertytree.cpp
While here, also add a simple unit test that `as_vector<T>()` returns `nullopt` for non-existing property nodes.
---
Extracted from #5801.
=> Support Inserting Bools Into Property Trees

CMakeLists_files.cmake, opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/flow/SubDomain.hpp, opm/simulators/linalg/WellOperators.hpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModelNldd.cpp, opm/simulators/wells/BlackoilWellModelNldd.hpp, opm/simulators/wells/BlackoilWellModelNldd_impl.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/WellConnectionAuxiliaryModule.hpp, opm/simulators/wells/WellInterface.hpp
This mostly separates the NLDD code in the BlackoilWellModel. There are a few leftovers which require further restructuring in the well operator and/or auxillary well connection module that I plan to handle later, but step by step..
=> changed: move NLDD BlackoilWellModel code to separate class

opm/simulators/flow/ActionHandler.hpp, opm/simulators/flow/FlowProblem.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp
In particular, this PR
1. Makes `ActionHandler::applySimulatorUpdate()` "public"
2. Splits the action processing part of `FlowProblemBlackoil::endTimeStep()` out to a separately callable member function, `FlowProblemBlackoil::endStepApplyAction()`.
Together, these provide hooks which make the simulator's event processing at the end of a converged time step customisable.
---
Extracted from #5801.
=> Make Simulator Operations Generally Accessible

CMakeLists_files.cmake, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/wells/RuntimePerforation.hpp, opm/simulators/wells/WellInterfaceGeneric.cpp, opm/simulators/wells/WellInterfaceGeneric.hpp
In particular, this lays the foundation for adding new well connections as a result of fracturing processes.
=> Add Infrastructure for Geomechanical Analysis

opm/simulators/linalg/gpuistl/detail/is_gpu_pointer.hpp, opm/simulators/linalg/gpuistl/gpu_smart_pointer.hpp
The previous implementation used some template syntax that older versions of NVCC did not seem to accept. The current version includes explicit overloads for `unique_ptr` and `shared_ptr`.
=> Fixes for NVCC older than 12.5.1

CMakeLists_files.cmake, opm/simulators/utils/SymmTensor.cpp, opm/simulators/utils/SymmTensor.hpp, opm/simulators/utils/VoigtArray.cpp, opm/simulators/utils/VoigtArray.hpp, tests/test_SymmTensor.cpp, tests/test_VoigtArray.cpp
These are data structures for holding vectors or scalars stored using Voigt notation.
In particular these containers enforce access through an enumerated index. In my experience it is so easy to get these things wrong if you keep accessing using numeric indices everywhere that a safety layer is warranted.
=> Add VoigtArray and SymmTensor classes

.clang-format
Note that this change requires clang-format 16 or newer.
=> clang-format now adds newline at the end of file.

CMakeLists.txt
Some code in implementation depends on the libfmt headers.
=> Link MainDispatchDynamic to LibFMT

opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/flow/FlowGenericVanguard.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/PolyhedralGridVanguard.hpp
In particular
1. Reduce scope of some objects
2. Remove unneeded objects
3. Split some long lines.
4. Realign some code that was indented multiple levels
5. Tag `#endif` pre-processor statements with their condition
This is in preparation of introducing support for edge-conformal processing of corner-point descriptions.
---
Extracted from #5806.
=> Tidy Up Parts of Grid Processing Implementation

opm/simulators/linalg/ISTLSolver.hpp, opm/simulators/linalg/PreconditionerFactory_impl.hpp
This pull request uses the new `CriticalError` exception class introduced the [opm-common PR 4467]( https://github.com/OPM/opm-common/pull/4467) to rethrow some exceptions happening in the initialisation of the linear solver as critical.
I am open to discussion if this is the correct level to introduce this exception. The reasoning behind the `prepare` choice was simply that in `initPrepare`, one access ```"preconditioner.type"``` which can lead to exceptions with ill-formed JSON input. It is also doubtful that any error occurring in `prepare` can be fixed by retrying with a smaller timestep.
=> Using the CriticalException in PreconditionerFactory and ISTLSolver

opm/models/blackoil/blackoilindices.hh, opm/models/blackoil/blackoilonephaseindices.hh, opm/models/blackoil/blackoiltwophaseindices.hh, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.hpp, opm/simulators/wells/RatioCalculator.cpp, opm/simulators/wells/RatioCalculator.hpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWellPrimaryVariables.hpp, opm/simulators/wells/WellInterfaceIndices.cpp, opm/simulators/wells/WellInterfaceIndices.hpp
inactive components are represented using negative values in the index(traits) class so we should not be using unsigned values in the fluidsystem
while at it make activeToCanonicalComponentIndex usable at compile time
Downstream of https://github.com/OPM/opm-common/pull/4460
=> component indices are now int

opm/simulators/linalg/gpuistl/GpuBuffer.cpp, opm/simulators/linalg/gpuistl/GpuBuffer.hpp, opm/simulators/linalg/gpuistl/GpuDILU.cpp, opm/simulators/linalg/gpuistl/GpuDILU.hpp, opm/simulators/linalg/gpuistl/GpuVector.cpp, opm/simulators/linalg/gpuistl/GpuVector.hpp, opm/simulators/linalg/gpuistl/OpmGpuILU0.cpp, opm/simulators/linalg/gpuistl/OpmGpuILU0.hpp, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/DILUKernels.cu, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/DILUKernels.hpp, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/ILU0Kernels.cu, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/ILU0Kernels.hpp
Using cudagraphs reduces the overhead associated with many consecutive kernel launches in GPU ILU and DILU.
Code changes contain very few linechanges in the apply, though the stream has to be specified and many functions need an updated signature.
Speedups on spe1, spe11 and sleipner are typically around 1.1 to 1.2 in the preconditioners apply.
Also no speedup yet in the update, seems strange given the same kernel pattern...
=> Improve gpuistl using cudaGraphs

CMakeLists_files.cmake, opm/simulators/flow/CompositionalContainer.cpp, opm/simulators/flow/CompositionalContainer.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp, opm/simulators/wells/BlackoilWellModel.hpp
This adds a container for the compositional output. Furthermore it refactors the code a little such that the compositional output is completely contained within the compositional output module.
There is one additional unrelated commit that replaces some typedefs. I can separate that out if you want but it happend to sit in the tree on my laptop so..
=> Add CompositionalContainer, a container for compositional data output

opm/simulators/flow/CompositionalContainer.cpp
This fixes the instantiation for CompositionalContainer. Things were tested, then this merged in the mean time, then the other PRs got merged.
=> fix: instantiation of CompositionalContainer

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp
Get rid of bool parameters. Note I have passed the hysteresis config as a pointer to allow passing a nullptr for CompositionalOutput. I'm not sure if this is strictly required or not.
Downstream of https://github.com/OPM/opm-common/pull/4485
=> Simplify GenericOutputBlackoilModule::doAllocBuffers

opm/simulators/utils/FullySupportedFlowKeywords.cpp, opm/simulators/utils/PartiallySupportedFlowKeywords.cpp, opm/simulators/utils/UnsupportedFlowKeywords.cpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/GroupState.cpp, opm/simulators/wells/GroupState.hpp, opm/simulators/wells/WellGroupHelpers.cpp, opm/simulators/wells/WellGroupHelpers.hpp
Needs https://github.com/OPM/opm-common/pull/4094
=> Support instantaneous flow rates in extended network (WEFAC and GEFAC item 3)

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp
use a table for the entries.
centralize conditionals, map fiddling and resizing
It turned out more complicated than what would be optimal, but it is what it is.
=> GenericOutputBlackoilModule: unify data resizing

CMakeLists_files.cmake, opm/models/discretization/common/tpfalinearizer.hh, opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/FlowsContainer.cpp, opm/simulators/flow/FlowsContainer.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp
Sits on top of https://github.com/OPM/opm-simulators/pull/5950
=> Add a container for FLOWS data output

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/BlackoilModel_impl.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/flow/FlowProblemComp.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp, opm/simulators/flow/RSTConv.cpp, opm/simulators/flow/RSTConv.hpp, tests/test_rstconv.cpp
move member from model to output module. this way we don't have to shuffle data around
=> move output of conv data into RSTConv class

opm/simulators/flow/GenericOutputBlackoilModule.cpp
This fixes the writing of residuals (e.g., for a gas water system the current master only writes the residuals for the gas phase).
=> Fix to write residuals

opm/models/discretization/common/tpfalinearizer.hh, opm/simulators/flow/BlackoilModel_impl.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/flow/FlowProblemComp.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp
the pointer is allocated in the ctor, so the fact that it is a unique_ptr
can be kept as an implementation detail. furthermore, the previous
accessor did not properly enforce constness, as a const unique_ptr<EclWriter>
only applies const to the pointer class, not the data the pointer points to.
Sits on top of https://github.com/OPM/opm-simulators/pull/6000
=> FlowProblem(Blackoil|Comp): Return a reference to EclWriter

opm/simulators/wells/WellState.cpp, opm/simulators/wells/WellState.hpp
In particular, split this function into distinct steps:
1. Computing the linearised IJK index of each connection.
2. Reporting multiplicative factors such as the CTF, the D factor, and the transmissibility multiplier due to rock compaction.
3. Reporting pressures, flow rates, and productivity indices.
4. Reporting filter cake values for injectors
While here, also reverse a condition in init() to enable "early continue" and reduce levels of nesting and to reduce scope of some objects.
---
Extracted from #5811.
=> Refactor Connection Value Report Function

opm/simulators/wells/WellInterface_impl.hpp
Output of stopping / reviving of wells has a tendency of filling the terminal output. Move it to .DBG . If the wells end up stopping/shutting after the timestep. This will still be reported to the terminal/PRT.
=> clean up terminal output

CMakeLists_files.cmake, opm/simulators/wells/ConnFracStatistics.hpp, opm/simulators/wells/PerfData.cpp, opm/simulators/wells/PerfData.hpp, opm/simulators/wells/RunningStatistics.hpp, opm/simulators/wells/WellState.cpp, opm/simulators/wells/WellState.hpp, tests/test_ParallelSerialization.cpp, tests/test_RunningStatistics.cpp
Populates the new `data::Connection::fract` data member from PR OPM/opm-common#4388.
To this end, introduce two helper classes to compute statistics of a running sample:
* `RunningStatistics` calculates basic statics measures of a running sample
* `ConnFracStatistics` aggregates those measures for connection level fracture pressure, fracture width, and flow rate
=> Report Connection Level Fracturing Statistics to I/O Layer

opm/models/io/basevanguard.hh, opm/models/utils/simulator.hh, opm/simulators/flow/AluGridVanguard.hpp, opm/simulators/flow/CpGridVanguard.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/PolyhedralGridVanguard.hpp
This PR extracts "adding lgrs" from GenericCpGridVanguard::doCreateGrids_() and moves this into the Simulator constructor body, before load balancing, model and problem initialization. 
Not relevant for the Reference Manual.
=> Extract addLgrs, invoke it before loadBalance

CMakeLists.txt
link to targets to get include paths set up.
Discovered these now as I do not have tracy in system paths.
=> fix tracy support

opm/simulators/flow/OutputBlackoilModule.hpp
Clangd complains the template is called before it has been defined and that it is a c++-20 extension.
Kinda weird, but don't want to fight it...
=> move template to avoid clang warning

opm/simulators/wells/MultisegmentWell.hpp, opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/MultisegmentWellSegments.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/ParallelWellInfo.cpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterfaceGeneric.cpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellInterface_impl.hpp, opm/simulators/wells/WellState.cpp, parallelTests.cmake
This PR adds communication to three spots where it was missing before (commits adb7223eeb97fa475e50b0721e1e460350d4216b, d454d03d38f809295ab22a7b2b8faf9f1c465d50 and  f0fbe62056c0dfeab59b8c978d00778026b3a522) and renames some variables to make it obvious if they contain local or global quantities.
With these changes, the test added in commit 3b68c4eb114ed63225065542ce4f96e5e5ec8174 passes. The test does not pass without these changes, see #5999, there the parallel simulation runs into a deadlock due to the missing communication.
This PR is not relevant for the reference manual.
=> Add missing communication for parallel runs with MSWells

CMakeLists.txt, CMakeLists_files.cmake, tests/gpuistl/test_throw_macros_on_gpu.cu
Some simple tests for the new error macros defined in [the opm-common PR 4465](https://github.com/OPM/opm-common/pull/4465).
=> Added tests for error macros on GPU.

opm/simulators/linalg/gpuistl/GpuBuffer.cpp, opm/simulators/linalg/gpuistl/GpuBuffer.hpp, tests/gpuistl/test_GpuBuffer.cu, tests/gpuistl/test_gpuPvt.cu, tests/gpuistl/test_gpu_linear_two_phase_material.cu
Avoids the unneeded `consts` propagating through the GPU types
connected to https://github.com/OPM/opm-common/pull/4482
=> Refactor make view and copy to gpu

opm/simulators/linalg/gpubridge/Preconditioner.hpp, opm/simulators/linalg/gpubridge/opencl/openclBILU0.hpp, opm/simulators/linalg/gpubridge/opencl/openclBISAI.hpp, opm/simulators/linalg/gpubridge/opencl/openclCPR.hpp, opm/simulators/linalg/gpubridge/opencl/openclPreconditioner.hpp, opm/simulators/linalg/gpubridge/rocm/rocsparseBILU0.cpp, opm/simulators/linalg/gpubridge/rocm/rocsparseBILU0.hpp, opm/simulators/linalg/gpubridge/rocm/rocsparseCPR.cpp, opm/simulators/linalg/gpubridge/rocm/rocsparseCPR.hpp, opm/simulators/linalg/gpubridge/rocm/rocsparsePreconditioner.hpp
use this to have this be cl::Buffer for openclPreconditioner
there is no code using Preconditioner in a base class context and this cleans up ifdefs and overloads
=> Preconditioner: add another template parameter for the apply constants

opm/simulators/flow/GenericTracerModel_impl.hpp
=> Tracer: no reason to setup parameter tree if solver is sequential

opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
This makes the summary output correct for these cumulative quantities also at substeps, not just report steps.
=> Ensure MSUMLINS and MSUMNEWT is updated.

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/MICPContainer.hpp, opm/simulators/flow/TracerContainer.cpp, opm/simulators/flow/TracerContainer.hpp
I cannot explain this, but this fixes the problem. 
For some reason, we get calls to tracerC_ where the eclState_ reference member is nullptr. By not holding this as a member this is avoided. I cannot figure out how tracerC_ gets in such a state.
=> Fix tracercontainer in flowexp_comp

opm/simulators/flow/TracerModel.hpp
=> Tracer: some janitoring

opm/simulators/flow/GenericTracerModel_impl.hpp
Mostly irrelevant, but why not?
|    Revision    |tracerAdvance|tracerSolve |Pre/post step|p-value(tracerSolve)|
|----------------|-------------|------------|-------------|-------------------:|
|tracer_avoid_ilu|32.55 +- 0.13|5.16 +- 0.00|55.03 +- 0.13|                   0|
|master          |32.17 +- 0.23|5.34 +- 0.00|54.89 +- 0.51|                    |
|    Revision    |tracerAdvance|tracerSolve |Pre/post step|p-value(tracerSolve)|
|----------------|-------------|------------|-------------|-------------------:|
|tracer_avoid_ilu|32.76 +- 0.48|0.13 +- 0.00|59.05 +- 0.81|                   0|
|master          |35.99 +- 0.42|3.10 +- 0.00|61.63 +- 0.66|                    |
=> TracerModel: avoid setting up ILU if no solves will be performed

CMakeLists.txt
if not parallel builds wll fail with the super-build
=> fixed: make MainDispatchDynamic dependent on the opmcommon target

opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/SingleWellState.hpp, opm/simulators/wells/WellConstraints.cpp, opm/simulators/wells/WellInterface_impl.hpp
Fix not checking THP control for other controls that GRUP
=> Only check trivial_target for GRUP when checking in THP

flowexperimental/flowexp.hpp, opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
This replaces https://github.com/OPM/opm-simulators/pull/6014 make make the pre-solve optional.
=> Make pre-solve network optional

CMakeLists_files.cmake, opm/simulators/flow/GenericTracerModel.hpp, opm/simulators/flow/TracerModel.hpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/WellTracerRate.hpp, tests/test_RestartSerialization.cpp
Not really inner-loopy so not much gained in terms of efficiency. But seems to yield, if anything, a small speedup
|     Revision      |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|-------------------|-------------|--------------|-------------|----------------------:|
|tracer_rate_structs|31.91 +- 0.27|25.72 +- 0.22 |53.72 +- 0.35|                   0.04|
|master             |32.68 +- 0.23|26.31 +- 0.20 |54.69 +- 0.33|                       |
|     Revision      |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|-------------------|-------------|--------------|-------------|----------------------:|
|tracer_rate_structs|35.27 +- 0.11|31.19 +- 0.10 |61.14 +- 0.20|                   0.09|
|master             |35.80 +- 0.26|31.61 +- 0.23 |62.16 +- …
=> Tracer: add some structs for well rate output and avoid complex keys

CMakeLists_files.cmake, opm/simulators/flow/DamarisWriter.hpp, opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp, opm/simulators/flow/OutputExtractor.hpp
This applies the same strategy as https://github.com/OPM/opm-simulators/pull/5994 but to the extraction of element level data, with the same merits.
This is a hotter loop, so we may pay a cost for the increased abstraction. Should be tested on some large models
=> OutputBlackoilModule::processElement: use a table for data extraction

opm/simulators/flow/FlowProblemBlackoil.hpp
In #5499 this was tested for cases with oil. For a case without it, then some assertions fail (e.g., [updateRelpermAndPressures](https://github.com/OPM/opm-simulators/blob/96ec6ad143b4106ac601546e196ecb318faaca3f/opm/models/blackoil/blackoilintensivequantities.hh#L297)).
This PR fixes this.
=> Fix to write vtk (if enabled) for dry runs in cases without oilPhase

opm/simulators/wells/MultisegmentWellGeneric.cpp, opm/simulators/wells/MultisegmentWellGeneric.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp
If the well stagnates 5 times with full damping we give up. (and hope it convergence at the next newton iteration).
=> modify stagnation and oscillation code for MSW

opm/simulators/flow/TracerModel.hpp
No significant impact on runtime, but neater code (imo).
|   Revision   |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|--------------|-------------|--------------|-------------|----------------------:|
|tracer_unify_2|32.05 +- 0.07|25.98 +- 0.06 |52.85 +- 0.15|                   0.48|
|master        |32.11 +- 0.10|26.10 +- 0.08 |53.90 +- 0.11|                       |
|   Revision   |tracerAdvance|tracerAssemble|Pre/post step|p-value(tracerAssemble)|
|--------------|-------------|--------------|-------------|----------------------:|
|tracer_unify_2|31.25 +- 0.20|30.15 +- 0.24 |55.88 +- 0.29|                   0.37|
|master        |31.64 +- 0.71|30.56 +- 0.69 |57.29 +- 2.16|                       |
=> Tracer: Unify some helper functions

opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputExtractor.hpp
unconditional deref while creating (unused) extractor will trigger asserts in debug iterator builds
=> fixed: capture as optional

opm/simulators/flow/CpGridVanguard.hpp, opm/simulators/flow/FlowGenericVanguard.cpp, opm/simulators/flow/FlowGenericVanguard.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/GenericCpGridVanguard.hpp, opm/simulators/utils/SetupPartitioningParams.cpp, opm/simulators/utils/SetupPartitioningParams.hpp
This commit introduces a new hidden runtime parameter,
```
ZoltanPhgEdgeSizeThreshold (--zoltan-phg-edge-size-threshold, double, default value = 0.35)
```
which maps to Zoltan's low-level control parameter
```
PHG_EDGE_SIZE_THRESHOLD
```
that controls which hypergraph edges to omit/discard.  We add a new parameter to `setupZoltanParameters()` and thread the command line parameter through as an argument to this function.
This is to enable runtime experimentation with this aspect of the partitioning algorithm, but end-users should typically not alter the default value without good reason.
=> Make Zoltan's Hyperedge Size Threshold Runtime Controllable

tests/gpuistl/test_GpuVector.cpp
Removes a warning from a `.cpp` file. The assignment should not have been there to begin with (it probably came about during debugging)
=> Remove assigning to self

opm/simulators/flow/FlowProblemBlackoil.hpp
This showed up when dry running the SPE1CASE1.DATA with vtk output, which has DRSDT in the SCHEDULE.
=> Fix to write vtk (if enabled) for dry runs in cases with drsdt

opm/simulators/flow/LogOutputHelper.cpp
If rate that is the nominator is zero just store zero instead of dividing it by another rater that might also be zero.
Makes searching for other nans more easy.
=> Prevent some nan creations during output generation.

opm/simulators/wells/StandardWellEquations.cpp
This bug concerns cprw linear solver (the default one) in the situation when a well has no active perforations on some rank. Other linear solvers are fine.
The diagonal element of the coarse (pressure) system's Jacobian for the well equation is normally calculated from the average cell weight over well's perforations. If there are no perforations we end up dividing zero by zero. This fix prevents the zero division and also adds a positive number to the Jacobian's diagonal. Other entries of that row are zero, so this regularizes the matrix. Since the well has no active perforations, the value of the variable has no effect on the solution. (Any nonzero value on the diagonal would work - tested with 1 and 1e-100).
=> Prevent zero division

opm/simulators/wells/BlackoilWellModelGasLift.cpp, opm/simulators/wells/GasLiftCommon.cpp, opm/simulators/wells/GasLiftSingleWellGeneric.cpp
Otherwise, we risk overrunning the INFO (PRT file) stream message limits in runs with many timesteps.
=> Log GLO Debug Messages to Debug Log Stream

opm/simulators/flow/SimulatorConvergenceOutput.cpp, opm/simulators/flow/SimulatorConvergenceOutput.hpp, opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
The EclipseState reference is used only for `startThread()`, so we might as well request that the caller pass an object when calling the `startThread()` function instead of keeping a reference to the object throughout the simulation run.
While here, also rename the `already_reported_steps_` to camel case.
=> Don't Store EclipseState Reference in Convergence Output Object

bin/hipify_file.sh
If something fails to hipify (eg. because `hipify_perl` is misisng), the `hipify_file.sh` script will not fail but simply carry on. This PR adds the `set -e` command at the start of the script to make it return a non-zero return value if any command fails.
=> Added set -e to hipify_file.sh

regressionTests.cmake
Case is supported and tested. So let's make sure we do not break it, again.
Should we try to make the run time of the test shorter?
=> Add ACTIONX_GCONINJE to regression test suite.

opm/simulators/linalg/ISTLSolver.hpp, opm/simulators/wells/StandardWellEquations.cpp, regressionTests.cmake
This makes MICP and PolymerMolarWeight to work with the default linear solver settings. 
Update: While the 2D_POLYMER_INJECTIVITY.DATA runs locally in my machine (macOS, clang) with this PR, this is not the case in jenkins. I tried to play with other flags to make it run using the default linear solver, but it still failed. Then setting back the runtime_error for the polymer injectivity model and cprw.
=> Bug fix in linear solver

opm/simulators/wells/BlackoilWellModel.hpp
Saw this when reviewing another PR.
=> removing undefined and unused function computeWellGroupTarget() from BlackoilWellModel

opm/simulators/flow/CollectDataOnIORank.hpp, opm/simulators/flow/CollectDataOnIORank_impl.hpp, opm/simulators/flow/DamarisWriter.hpp, opm/simulators/flow/EclGenericWriter_impl.hpp, opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/LogOutputHelper.cpp, opm/simulators/flow/LogOutputHelper.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp, tests/test_LogOutputHelper.cpp
This adds support for RPTSCHED WELLS=2. In particular this appends connection level data to the injection/production/cumulative PRT logs.
Downstream of https://github.com/OPM/opm-common/pull/4532
=> Support for RTPSCHED WELLS=2

opm/simulators/wells/StandardWellEquations.cpp
The original fix assumed mistakenly that the well block size (number of equations and unknowns for the wells) would be smaller than the reservoir block size. This is wrong for most models, such as the 3-phase black oil model (4 vs 3).
Fix should handle this situation correctly, and adds explanations.
Note that I have not tested this with debug iterators, so it would be good to sanity check before merging.
Original (buggy) fix in #6091.
=> Fix a recent bug indexing in the CPRW cell weights.

opm/simulators/wells/ALQState.cpp, opm/simulators/wells/ALQState.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/PerfData.cpp, opm/simulators/wells/PerfData.hpp, opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/SingleWellState.hpp, opm/simulators/wells/WellState.hpp
Downstream of OPM/opm-common#4527
Comparison with other simulator looks good for the test cases actionx/ACTIONX_WCONINJH.DATA actionx/ACTIONX_WCONHIST.DATA
I needed to make the container set up for producers/injector to work for the other types.  This here seems to work if the ACTIONX is executed at the end of a report step. I am bit skeptical whether this also works during the time stepping. Maybe there is  a better way?
=> Support WCONHIST/WCONINJ in ACTIONX

opm/simulators/linalg/FlexibleSolver_impl.hpp, opm/simulators/linalg/ISTLSolver.cpp, opm/simulators/linalg/PreconditionerFactory_impl.hpp, opm/simulators/linalg/WellOperators.hpp, tests/gpuistl/test_solver_adapter.cpp
This PR simplifies the `WellModelMatrixAdapter` by removing its parallel/MPI-specific functionality, since parallel operations are now handled by `WellModelGhostLastMatrixAdapter`.
The parallel functionality in `WellModelMatrixAdapter` was redundant since `WellModelGhostLastMatrixAdapter` is now used for all parallel operations. This change simplifies the codebase by removing unused functionality and makes the intended usage of each adapter class clearer. This is also motivated by the ongoing work to get well operators into the GPUIstl framework, where this hybrid serial/parallel class was causing issues. Another option for keeping this functionality is to split this into a serial and a parallel version, but I did not want to introduce a new class that is not actually used.
When testing …
=> Make wellModelMatrixAdapter serial only

opm/models/discretization/common/fvbaseproblem.hh, opm/models/io/vtkmultiwriter.hh, opm/models/parallel/gridcommhandles.hh, opm/simulators/flow/CollectDataOnIORank.hpp, opm/simulators/linalg/ExtraSmoothers.hpp, opm/simulators/linalg/elementborderlistfromgrid.hh, opm/simulators/linalg/gpubridge/MultisegmentWellContribution.cpp, opm/simulators/linalg/ilufirstelement.hh, opm/simulators/linalg/matrixblock.hh, opm/simulators/linalg/vertexborderlistfromgrid.hh, opm/simulators/wells/MSWellHelpers.cpp, opm/simulators/wells/MultisegmentWellEquations.cpp
DUNE_VERSION_NEWER has been removed. Falling back to DUNE_VERSION_GTE which exists since at least DUNE 2.7.
Removed switches for older version than 2.7.
=> Prepare OPM for DUNE 2.10

opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp, opm/simulators/flow/partitionCells.cpp, opm/simulators/flow/partitionCells.hpp, opm/simulators/utils/ParallelNLDDPartitioningZoltan.cpp, opm/simulators/utils/ParallelNLDDPartitioningZoltan.hpp, tests/test_partitionCells.cpp
This PR introduces several improvements to the Nonlinear Domain Decomposition (NLDD) implementation, with a main focus on better handling cells perforated by wells during subdomain partitioning.
- Cells perforated by the same well are now merged into a single entity before partitioning
- This ensures that all perforated cells of a well stay in the same subdomain
- Prevents wells from being split across NLDD subdomains, which is a requirement for the NLDD implementation
- Creates naturally better partitions than the previous fix to manually move the distributed cells after partitioning
- Uses the new vertex merging functionality from https://github.com/OPM/opm-common/pull/4537 in opm-common
- Added a new method to grow partitions around wells
- Controlled with the parameter …
=> Add support for merging well cells for NLDD partitioning

opm/models/blackoil/blackoilintensivequantities.hh, opm/simulators/flow/EclWriter.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/Transmissibility_impl.hpp, opm/simulators/utils/ParallelRestart.cpp, opm/simulators/utils/ParallelRestart.hpp
Currently the FIP table data in the restart file is not understood, and this meant that the original FIP was had zero values in a restart run. This adds a workaround for this; On restart we first try to load data for step 0. If there, we can use this to generate the OIP.
Downstream of https://github.com/OPM/opm-common/pull/4545
=> Calculate original FIP by reading restart data for step 0

opm/simulators/wells/BlackoilWellModelGeneric.cpp
The previous_well_state was used to avoid oscillations long time ago. Using the nupcol rates aligns more with what we do elsewhere in the code and will be more accurate in particular at startup of wells. Test failures are expected. A qualitative look at the failed tests indicates that results looks more plausible.
=> Use well rates from well_state_nupcol instead of previous_well_state in updateWellRates

flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp, opm/models/blackoil/blackoilconvectivemixingmodule.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/simulators/flow/FlowGenericProblem.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp
Gives a significant speedup with DRSDTCON.
Same idea as OPM/opm-common#4364 and #5771, but with some differences. I managed to avoid noticing that one, or I would not have made this...
=> For convective mixing, store the saturated dissolution factor.

CMakeLists_files.cmake, flowexperimental/comp/EmptyModel.hpp, flowexperimental/comp/flowexp_comp.hpp, flowexperimental/comp/wells/CompWell.hpp, flowexperimental/comp/wells/CompWellEquations.hpp, flowexperimental/comp/wells/CompWellEquations_impl.hpp, flowexperimental/comp/wells/CompWellInterface.hpp, flowexperimental/comp/wells/CompWellInterface_impl.hpp, flowexperimental/comp/wells/CompWellPrimaryVariables.hpp, flowexperimental/comp/wells/CompWellPrimaryVariables_impl.hpp, flowexperimental/comp/wells/CompWellState.hpp, flowexperimental/comp/wells/CompWellState_impl.hpp, flowexperimental/comp/wells/CompWell_impl.hpp, flowexperimental/comp/wells/CompositionalWellModel.hpp, flowexperimental/comp/wells/CompositionalWellModel_impl.hpp, flowexperimental/comp/wells/SingleCompWellState.hpp, flowexperimental/comp/wells/SingleCompWellState_impl.hpp, regressionTests.cmake
This reverts commit c782a9f5129b062ada21608dce0aef9a9ba7ec65.
=> Reapply "Compositional well"

CMakeLists_files.cmake, opm/simulators/flow/Banners.cpp, opm/simulators/flow/Banners.hpp, opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/flow/BlackoilModel_impl.hpp, opm/simulators/flow/FlowMain.hpp, opm/simulators/flow/NlddReporting.cpp, opm/simulators/flow/NlddReporting.hpp, opm/simulators/timestepping/SimulatorReport.cpp, opm/simulators/timestepping/SimulatorReport.hpp, opm/simulators/wells/BlackoilWellModelNldd.hpp, opm/simulators/wells/BlackoilWellModelNldd_impl.hpp, opm/simulators/wells/WellConnectionAuxiliaryModule.hpp
This PR fixes some bugs that were present in the Non-Linear Domain Decomposition (NLDD) reporting and improves how statistics from the NLDD solver are collected, displayed, and analyzed. 
The key improvements are:
1. Fixed a bug that the simulation summary reported the NLDD summary for rank 0 only. Now, it only reports the total local solve time in the simulation summary, and more detailed reports are shown in the DBG file. Removing the breakdown from the final summary report is motivated by the fact that this does not make sense for NLDD in parallel, where all the ranks have to wait for the slowest rank. Instead, we now output detailed reports per domain and per rank in the DBG file, which makes more sense.
2. There were also some inconsistencies in the NLDD assembly reporting, which …
=> Fix and improve nldd timing and output reporting

regressionTests.cmake
We're in the lead-up to creating release branches for 2025.04 and must not have a broken build.  We will re-enable the test once the underlying issue has been resolved.
=> Temporarily Disable 1D_COMP Regression Test

regressionTests.cmake
Reverts OPM/opm-simulators#6141
Trying to get the test back.
=> Revert "Temporarily Disable 1D_COMP Regression Test"

opm/simulators/wells/WellInterface_impl.hpp
Resolving the equation in updateWellStateWithTarget may lead to a long simulation time for problematic wells. I will put this in draft mode as it would need more testing.
=> Dont resolve well equation when computing initial guess for thp in  updateWellStateWithTarget

opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/utils/BlackoilPhases.cpp, opm/simulators/utils/BlackoilPhases.hpp, opm/simulators/utils/phaseUsageFromDeck.cpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/PerfData.cpp, opm/simulators/wells/PerfData.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellState.cpp
Depends on https://github.com/OPM/opm-common/pull/4550
=> Extending the SUMMARY keywords for CO2STORE and H2STORE

opm/simulators/wells/MSWellHelpers.cpp, opm/simulators/wells/MultisegmentWellEquations.cpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/ParallelWellInfo.cpp, opm/simulators/wells/ParallelWellInfo.hpp, opm/simulators/wells/WellState.cpp, parallelTests.cmake
This PR fixes parallel runs with multisegment wells that have SHUT perforations.
The tests added in the last commit of this PR fail without the changes before (https://github.com/OPM/opm-simulators/pull/6139).
In order to address such simulations, I've changed the behavior when accessing structures that work with only the OPEN perforations, like std::vector<std::vector<int>> perforations_ of MultisegmentWellSegments.
For this, an active_to_local_map_ is constructed in the function WellState<Scalar>::initWellStateMSWell. This map maps the global indices of the active perforations to the local indices of the active perforations.
This map and its conterpart local_to_active_map_ are added to the ParallelWellInfo class and then used by the functions: ParallelWellInfo<Scalar>::activeToLocal and …
=> Changes for parallel runs with multisegment wells that have shut perforations

opm/simulators/flow/OutputBlackoilModule.hpp
Using .emplace() on vector is not a good idea. Compiler also doesn't want to use braced init for the struct for some reason, so resort to push_back().
=> fix mech extractor

opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
While testing 2025.04-r1, this issue appears, and this PR fixes this.
=> Fix to 2025.04-r1 build candidate in clang

opm/simulators/wells/WellInterfaceFluidSystem.cpp, opm/simulators/wells/WellInterfaceFluidSystem.hpp, opm/simulators/wells/WellInterfaceIndices.cpp, opm/simulators/wells/WellInterfaceIndices.hpp
so it will be together with other index conversion functions. it is not a significant deal, while it makes easier to find them. 
originally, I thought there are only two of them since WellInterfaceIndices class only has two of them.
=> moving flowPhaseToModelPhaseIdx to WellInterfaceIndices

opm/simulators/wells/MSWellHelpers.cpp, parallelTests.cmake
Fixes the tests added in https://github.com/OPM/opm-tests/pull/1330.
Without the fix from this PR, the tests fail (see https://github.com/OPM/opm-simulators/pull/6176).
This PR is not relevant for the reference manual.
=> Fix runs with distributed MSWells with only shut perforations on one process

opm/simulators/wells/VFPHelpers.cpp
`intersectWithIPR` was mainly intended to find stable operating points for close to inoperable thp-wells. However, we may also end up here for other reasons, e.g., wells that don't converge because they are forced to operate at too high rate. In this case, if (flo, bhp) ipr-line lies above all points from table  (and hence is _very_ operable) , current code will return an empty intersection.
To prevent this, this PR simpy adds extrapolation based on the two largest flo-values such that an intersection is found also for this case.
=> intersectWithIPR - add extrapolation for last interval whenever it applies

opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp
We use the network pressures for initialization and want to save a valid network pressure we can restart from in case the iterations fails
=> Store and use last valid network pressure

opm/simulators/flow/EclGenericWriter_impl.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/partitionCells.cpp, opm/simulators/utils/MPISerializer.hpp, opm/simulators/utils/ParallelRestart.cpp, opm/simulators/utils/ParallelSerialization.cpp, opm/simulators/utils/PropsDataHandle.hpp, opm/simulators/wells/BlackoilWellModelGasLift_impl.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/ParallelWellInfo.cpp, opm/simulators/wells/WellConnectionAuxiliaryModule.hpp, tests/test_broadcast.cpp
Addresses the same problem as #6173.
Note that this changes the order of arguments for some calls: now the root always comes first, there is no possible mixup between the root argument and the data arguments.
Most changes are due to no longer having a default argument for the root. I consider that a good thing in itself.
There was only a single case where the two-argument version of the deleted overload was used, so I actually had to change the order, and that was in MPISerializer itself.
=> Remove unneeded broadcast() overload.

opm/simulators/timestepping/SimulatorReport.cpp
The column name for `local_solve_time` is missing. This should be also added to the release.
=> Adding missing column name in INFOSTEP

opm/simulators/wells/WellInterface_impl.hpp
In the master, we don't log control switching during local solves, which could lead to changing controls without or with the wrong output in the terminal.  The log also detects oscillations, and controls may oscillate significantly during the local solves. I added a safeguard to restrict only changing controls for iter>nupcol and the local solves, but we may need a more robust solution. I tagged this with release since it is a bug fix, but I also made it a draft as it requires more testing. 
UPDATE: After some thinking and testing, I suggest starting to count oscillations only after NUPCOL iterations. After NUPCOL iterations, the control target is fixed, and we should, in principle, experience fewer oscillations. With this change, we less frequently end up with the "wrong" control, while …
=> Log local switching

opm/simulators/linalg/StandardPreconditioners_mpi.hpp, opm/simulators/linalg/StandardPreconditioners_serial.hpp
CPRW is only available when the operator is a well operator variant.
=> Fix error in comment.

CMakeLists_files.cmake
Otherwise, the [StandardPreconditioners.hpp](https://github.com/OPM/opm-simulators/blob/ca92b6906c797278278feab3591b354cb1c1a01b/opm/simulators/linalg/StandardPreconditioners.hpp#L26) header is not usable from an installed location.
=> Install is_gpu_operator.hpp Header

opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
The shut connection handling should be the final stage of this reporting.  While here, also split the tracer rate assingments out to a separate helper function.
=> Reorder Well Data Report Function

opm/simulators/linalg/linearsolverreport.hh
we are already in the `Opm::linear` namespace.
=> fix namespace in linearsolverreport.hh

opm/simulators/flow/CpGridVanguard.hpp
In OPM/opm-simulators#6235, a warning is logged in parallel runs even when the grid does not contain any LGRs. Issue found in https://github.com/OPM/opm-simulators/pull/6235#discussion_r2079157470
This PR implements the correction suggested in that comment. 
Not relevant for the reference manual.
=> Correct warning 

opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/SingleWellState.cpp, opm/simulators/wells/SingleWellState.hpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp, opm/simulators/wells/WellState.cpp
Revised and rebased, based on #5990 originally. Removed some changes to simplify investigation.
For now, just for testing.
=> Store primary variables in well state, and improve well initialization

opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/VFPHelpers.cpp
The canary died.
```
//Canary in a coal mine: shouldn't really be required
assert(found == true);
static_cast<void>(found); //Silence compiler warning
```
If bhp_arg is NaN we trigger this assert.
=> Throw if bhp is NaN in findTHP

opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp, opm/simulators/flow/RFTContainer.cpp, opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp
Otherwise, `BlackoilWellModel<>::wellData()` will generate reports for non-owned wells if the wells are distributed.  This, in turn, opens the door to race conditions when collecting contributions on the I/O rank.
=> Assign Shut Connection Data for Owned Wells Only

opm/simulators/linalg/ISTLSolver.cpp, opm/simulators/linalg/ISTLSolver.hpp
while harmless, as the result is unused, we currently deref a null ptr in serial builds. this causes issues for builds enabling cxxlib assertions
=> fixed: pass by pointer instead of reference

opm/simulators/timestepping/AdaptiveTimeStepping.hpp
changing  friend class AdaptiveTimeStepping<TypeTag>::template SubStepIteration<Solver>;
to be     friend class SubStepIteration<Solver>;
It was reported by @ElyesAhmed and solution proposed by @bska .
=> fixing compilation with older gcc compiler (GCC 9.X)

opm/simulators/flow/RFTContainer.cpp
There's no need to use construct+move here.
=> Prefer In-Place Construction of Data::Connection Objects

python/generate-pypi-package.sh
these were eol'd in 2021/2023 and have now been removed from the docker image.
add python 3.13 package
=> remove python 3.6 and 3.7 packages

opm/simulators/wells/MultisegmentWellEval.cpp, opm/simulators/wells/MultisegmentWellGeneric.cpp, opm/simulators/wells/MultisegmentWellSegments.cpp, opm/simulators/wells/StandardWellConnections.cpp, opm/simulators/wells/StandardWellEval.cpp, opm/simulators/wells/StandardWellPrimaryVariables.cpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellConvergence.cpp, opm/simulators/wells/WellFilterCake.cpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellInterface_impl.hpp
First two commits: Rename local objects such that the name says "local" in them.
Last commit: Add comment about the only member local_perforation_depth_diffs_ of MultisegmentWellSegments that contains local information. I've thought about changing that in commit e55fa7642e6c136f76146ccc2ecba2b82bf65e22, yet after feedback from @blattms  (https://github.com/OPM/opm-simulators/pull/6250#pullrequestreview-2825618030), we're not going to do that.
=> Refactor some of the MSWell code

flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/common/directionalmobility.hh, opm/models/common/multiphasebaseproblem.hh, opm/simulators/flow/FlowProblem.hpp
Some tidy ups, remove unnecessary template parameter, simplify storage, make it a class.
=> DirectionalMobility: janitoring

opm/simulators/flow/TracerModel.hpp
This PR improves the performance of the TracerModel by adding OpenMP parallelization over grid elements. The main changes include:
1. In a similar manner as https://github.com/OPM/opm-simulators/pull/5912, use `ElementChunks` for efficient chunk-based parallelization of grid operations
2. Added OpenMP parallelization to element loops in:
- `assembleTracerEquations_()` - parallelizes the equation assembly process
- `updateStorageCache()` - parallelizes the storage computation and updates
3. Added early-exit checks to avoid unnecessary work for empty tracer batches
| Processors | Pre-post Time (s) | speedup |
|------------|-------------------|-----------------|
| 1          | 77.98               | 1             |
| 2          | 58.26               | 1.34             |
| 4          | 51.10 …
=> Make TracerModel thread parallel

CMakeLists_files.cmake, opm/simulators/linalg/StandardPreconditioners_gpu_serial.hpp, opm/simulators/linalg/StandardPreconditioners_mpi.hpp, opm/simulators/linalg/StandardPreconditioners_serial.hpp, opm/simulators/linalg/gpuistl/GpuDILU.cpp, opm/simulators/linalg/gpuistl/GpuDILU.hpp, opm/simulators/linalg/gpuistl/GpuJac.cpp, opm/simulators/linalg/gpuistl/GpuJac.hpp, opm/simulators/linalg/gpuistl/GpuSeqILU0.cpp, opm/simulators/linalg/gpuistl/GpuSeqILU0.hpp, opm/simulators/linalg/gpuistl/GpuSparseMatrix.cpp, opm/simulators/linalg/gpuistl/GpuSparseMatrix.hpp, opm/simulators/linalg/gpuistl/GpuVector.cpp, opm/simulators/linalg/gpuistl/GpuVector.hpp, opm/simulators/linalg/gpuistl/OpmGpuILU0.cpp, opm/simulators/linalg/gpuistl/OpmGpuILU0.hpp, opm/simulators/linalg/gpuistl/PreconditionerCPUMatrixToGPUMatrix.hpp, opm/simulators/linalg/gpuistl/detail/CuSparseResource.hpp, opm/simulators/linalg/gpuistl/detail/CuSparseResource_impl.hpp, opm/simulators/linalg/gpuistl/detail/gpusparse_matrix_operations.cu, opm/simulators/linalg/gpuistl/detail/gpusparse_matrix_operations.hpp, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/JacKernels.cu, opm/simulators/linalg/gpuistl/detail/preconditionerKernels/JacKernels.hpp, opm/simulators/linalg/is_gpu_operator.hpp, tests/gpuistl/test_GpuDILU.cpp, tests/gpuistl/test_GpuJac.cpp, tests/gpuistl/test_preconditioner_factory_gpu.cpp
This pull request makes the GPU preconditioners hold the GPU matrix as a reference (instead of owning it as a value). The motivation for this change is three-fold:
1) Reduce the memory usage on the GPU when more than just the preconditioner is using the matrix on the GPU, for instance when the full linear solver loop runs on the GPU, which is the case now with `gpubicgstab`.
2) Reduce host-to-device copy overhead.
3) Reduce the responsibility of the GPU Preconditioners. 
We still need something to copy the matrix from the CPU to the GPU in the setting where we assemble the matrix on the CPU (which is always at the time of writing). This is done through the added class `Opm::gpuistl::PreconditionerCPUMatrixToGPUMatrix` which responsibility is owning the GPU matrix and copying the CPU …
=> Instatiate preconditioners directly with GPU matrices

opm/simulators/flow/NonlinearSolver.hpp, opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/AdaptiveTimeStepping.cpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp, opm/simulators/timestepping/TimeStepControl.cpp, opm/simulators/timestepping/TimeStepControl.hpp, opm/simulators/timestepping/TimeStepControlInterface.hpp
I've implemented rejection of a completed time step if the relative change is larger than the time step control tolerance (only for the general 3rd order controller). The code seems to work as it should, but I might have missed something, so please let me know if you find anything wrong.
An earlier version of this can be found in #5317, but the current one is up to date with the current master.
=> Time step rejection if tolerance test fails

opm/simulators/flow/FlowProblemBlackoil.hpp
We currently do not support saturation function end-point scaling in LGRs, so there's no need to try.  Therefore, limit the checks to the main grid&ndash;`levelGridView(0)`&ndash;only.
=> Run Saturation Function Consistency Check on Main Grid Only

opm/simulators/flow/FlowProblemParameters.hpp
This is to gain experience ahead of making a decision for this setting in the next (2025.10) OPM release.
=> Enable New Saturation Function Consistency Checks by Default

parallelTests.cmake, regressionTests.cmake
Following PR OPM/opm-common#4439, we can activate most of the aspects of the model in PR OPM/opm-tests#1299.
=> Add Regression Tests for UDA Compatibility

opm/simulators/flow/NonlinearSolver.hpp, opm/simulators/timestepping/AdaptiveTimeStepping.cpp, opm/simulators/timestepping/AdaptiveTimeStepping.hpp, opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp, opm/simulators/timestepping/SimulatorReport.cpp, opm/simulators/timestepping/SimulatorReport.hpp, opm/simulators/timestepping/TimeStepControl.cpp, opm/simulators/timestepping/TimeStepControl.hpp, opm/simulators/timestepping/TimeStepControlInterface.hpp
This PR includes a different reduction in time step size if tolerance test fails (than if we get numerical difficulties), the possibility to set controller parameters for the general 3rd order controller, the option to use control error filtering as tolerance test instead of comparing relative change directly to the tolerance, as well as adjustments/fixes to the general 3rd order controller code.
=> Further updates and fixes to general controller

opm/simulators/wells/MultisegmentWellAssemble.hpp
MultisegmentWellAssemble reuses the indices and flags defined in MultisegmentWellPrimaryVariable.
It triggered problems when developing https://github.com/OPM/opm-simulators/pull/5818 , while did not think to reuse the indices and flags back then.
=> reusing primary variable indices and flags defined

opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell_impl.hpp, opm/simulators/wells/WellInterface.hpp, opm/simulators/wells/WellInterface_impl.hpp
In NORNE_ATW2013_1A_MSW and NORNE_ATW2013_1A_STW
there is no THP control, and the operability check does not work. It will instead cut the time step until it closes the wells due to repeated convergence issues. 
This PR adds the new operability check introduced for the controlled wells to wells without the THP controls. 
The issue reported on slow runs on the above-mentioned models is fixed with this PR. See also https://github.com/OPM/opm-simulators/pull/6069, which is no longer needed.
=> Also check operability for wells without thp control

opm/simulators/wells/BlackoilWellModelConstraints.cpp
it depends on PR https://github.com/OPM/opm-common/pull/4609
=> using  group_limit_action.oil instead of allRates for better code readability and potentially better flexibility

opm/models/blackoil/blackoilintensivequantities.hh
Without this PR, the simulation with `--enable-dry-run=1` will fail to end with a message (using a case with `CO2STORE`):
> Simulation aborted as program threw an unexpected exception: InvalideAndUpdateIntensiveQuantities: state errorvector
With this PR, the simulation finishes as it used to:
> ================ Simulation turned off ===============
=> Fixing --enable-dry-run=1

opm/simulators/linalg/FlexibleSolver_impl.hpp
An error was introduced in the previous PR where the build would fail without CUDA. This PR should fix that.
=> Fixed brace locations when compiling without CUDA

opm/simulators/wells/GuideRateHandler.cpp
Needed because of bug in some versions of libfmt.
=> Add include to get fmt::join.

opm/models/blackoil/blackoillocalresidualtpfa.hh, opm/models/discretization/common/tpfalinearizer.hh
The member `neighborInfo_` is used to make the `tpfalinearizer` faster, by storing all the required data in a struct that is fast to access. It contains an instance of the struct `ResidualNBInfo` for every neighbour of every cell. For this reason, it takes up a significant amount of memory. Recent profiling measured this to be around 8 % of the peak heap memory allocations. Removing a double in this struct will save 6 * 8 bytes = 48 bytes per cell. So any members we don't need here should not be stored. 
For this reason I made the members that are required for `energy`, `diffusion` and `dispersion` conditional.
There might be more chances to reduce the memory use here, but this has to be carefully evaluated to not make this critical code slower.
- One example is to remove `Vin` and `Vex` …
=> tpfalinearizer: Add conditional storage for energy, diffusion and dispersion

compareECLFiles.cmake, opm/simulators/flow/CollectDataOnIORank_impl.hpp, opm/simulators/flow/CpGridVanguard.hpp, opm/simulators/flow/GenericCpGridVanguard.cpp, opm/simulators/flow/GenericCpGridVanguard.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/utils/ParallelEclipseState.hpp
In OPM/opm-grid, distributing the level zero grid of a CpGrid with LGRs is supported. This PR allows adding LGRs in the simulation grid. 
The strategy used is to add (the same) LGRs in both global and distributed view, and synchronize the cell ids.
Main changes:
1. Replace cartesianIndexMapper_ for levelCartesianIndexMapper_  when distributing field properties. This allows access to the Cartesian indices of the distributed level zero grid, where the field properties are given - for now.
2.  Skip - for now - in parallel runs for CpGrid with LGRs building index maps in CollectDataInIORank. 
3.  Resize 'region' since, for CpGrid with LGRs, where level zero grid has been distributed, the total amount of elements - per process - in level zero grid and leaf grid do not coincide, in general.
To …
=> (Partial) Support for parallel runs with CpGrid with LGRs

opm/simulators/flow/BlackoilModelNldd.hpp, opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp, opm/simulators/flow/BlackoilModel_impl.hpp, opm/simulators/flow/SubDomain.hpp, opm/simulators/timestepping/SimulatorReport.cpp, opm/simulators/timestepping/SimulatorReport.hpp
This PR introduces an a new feature to the NLDD (Nonlinear Domain Decomposition) solver that reduces the time spent on local solves by skipping subdomains that haven't changed significantly between iterations.
Mobility in reservoir simulation represents the ease with which a fluid phase can flow through porous media. It is calculated as the ratio of relative permeability to viscosity for each phase $\alpha$:
```math
\lambda_\alpha = \mathrm{kr}_\alpha / \mu_\alpha
```
Mobility changes indicate significant alterations in fluid flow characteristics, making it an effective indicator for determining when subdomain re-solving is necessary.
- To determine if we need to solve a domain the relative change in mobility is compared to a previous value and if it is above a given tolerance, the domain …
=> Add mobility thresholding to NLDD

flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/discretization/ecfv/ecfvstencil.hh, opm/simulators/flow/EquilInitializer.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/flow/OutputBlackoilModule.hpp
Also added some more convenience enums to avoid repeated getPropValue() clutter.
Downstream of https://github.com/OPM/opm-common/pull/4651
=> Use if constexpr to handle conditionally stored members.

flowexperimental/comp/wells/CompWellInterface_impl.hpp, flowexperimental/comp/wells/CompWellModel_impl.hpp
having it in the CompWellModel makes it can not run the cases with water phase while without wells.
=> moving FluidSystem::waterEnabled runtime_error to CompWellInterface

flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp, opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoildiffusionmodule.hh, opm/models/blackoil/blackoilenergymodules.hh, opm/models/blackoil/blackoilextbomodules.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilsolventmodules.hh, opm/simulators/aquifers/AquiferAnalytical.hpp, opm/simulators/wells/StandardWell.hpp, opm/simulators/wells/StandardWell_impl.hpp
This is to make it a better fit for GPU code, but it should also allow some more optimizations on the CPU, such as doing static dispatch for the "multiplexed" (runtime switched) functions of the fluid and material subsystems.
Requires https://github.com/OPM/opm-common/pull/4657
=> Allow calling BlackoilIntensiveQuantities::update() without an ElementContext

opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.cpp, opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.hpp, tests/test_SatfuncConsistencyCheckManager.cpp, tests/test_ThreePointHorizontalSatfuncConsistencyChecks.cpp
This PR switches from a strict inequality for the upper bound on the mobile displacing oil saturation in the three-point scaling method to allowing equality as well.  Some recent experience demonstrates that equality is okay in this case.
=> Relax Upper Bound Check for Mobile Displacing Oil

opm/simulators/wells/WellGroupHelpers.cpp
When a well is distributed, we can run into a deadlock in _MultisegmentWellGeneric.cpp::scaleSegmentRatesWithWellRates_ when `segment_rates` differ between ranks and one rank picks an if-branch with a communication and the other without. The difference originates in the function _WellGroupHelpers.cpp:updateWellRatesFromGroupTargetScale_ that changes `surface_rates` only on the rank owning the well.
This commit makes all ranks change the `surface_rates`. It fixes a deadlock I encountered but needs further testing to see if it breaks something else. Alternative solution would be adding a communication copying the well from the owner to other ranks.
=> Remove the if that discoordinates values on different ranks

opm/simulators/timestepping/AdaptiveTimeStepping.cpp, opm/simulators/timestepping/TimeStepControl.cpp, opm/simulators/timestepping/TimeStepControl.hpp
The verbosity argument for the time step controllers wasn't used. I've cleaned up the code a bit and improved the feedback when verbosity is set to true. I also removed some default arguments, as well as comments about default values.
Question: Should `time-step-verbosity` be set to false by default, or should we keep it set to true?
=> Cleaned up and fixed verbosity for time step controllers

opm/simulators/flow/FlowProblem.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/flow/FlowProblemComp.hpp
This is arguably a hack.  The default implementation in terms of [`Simulator<>::episodeWillBeOver()`](https://github.com/OPM/opm-simulators/blob/cb049fcd657b48a47508db1a708b1c65f31204ac/opm/models/utils/simulator.hh#L555) is known to have non-trivial false negatives in certain regression tests.  These are in turn possibly related to using the simulation start time point (often a large number of seconds) and subtracting values of similar size.  The custom implementation in `FlowProblemBlackoil<>` uses a floating-point comparison involving `Schedule::seconds()` instead, thereby reducing the size of the numbers involved.  We're still vulnerable to "catastrophic cancellation" errors, but potentially less so.
A complete fix for the problem may involve switching to representing the simulated …
=> Add End-of-Episode Predicate to Flow Problem Classes

opm/simulators/wells/FractionCalculator.cpp, opm/simulators/wells/WellGroupHelpers.cpp
I guess satellite groups are only partly supported, but currently satellite production is only added into parent group production rates, and do not get added into reduction rates (so available rates for group control will be too high). This PR is just a simple fix, if prioritized at a later stage, we might want to reformulate this treatment (see comment in code) 
**Also**: guard against division by zero in fraction calculator (which may happen if no wells are on group-control)
=> Add in satellite production in reduction rates

CMakeLists_files.cmake
To avoid a warning, we need to add `--expt-relaxed-constexpr` when compiling `test_gpuBlackOilFluidSystem`.
=> Added --expt-relaxed-constexpr to test_gpuBlackOilFluidSystem

opm/simulators/wells/BlackoilWellModel.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp
this renders reportStepIndex unused, so remove it from interface.
Quells a clang warning
=> remove unused lambda capture

opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/LogOutputHelper.hpp
=> fixed: argument order differ in prototype and implementation

opm/simulators/wells/GasLiftSingleWellGeneric.cpp
to quell uninitialized use compiler warnings.
GCC LTO emits possibly uninitialized use warnings. obviously not happening in reality but let's shut it up.
=> initialize variables

flowexperimental/flowexp.hpp, opm/simulators/flow/BlackoilModelParameters.cpp, opm/simulators/flow/BlackoilModelParameters.hpp, opm/simulators/wells/MultisegmentWell_impl.hpp, opm/simulators/wells/StandardWell_impl.hpp
Add a cap on the number of allowed switches per local well solve. (set to 3)
=> Reduce osscilations between stop and open

opm/simulators/wells/BlackoilWellModelConstraints.cpp, opm/simulators/wells/BlackoilWellModelConstraints.hpp, opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, opm/simulators/wells/BlackoilWellModel_impl.hpp
This will make the behaviour for groups similar to wells.
=>  For oscillation detection we only count gr switching after nupcol. 

flow/flow_blackoil.cpp, opm/models/blackoil/blackoilintensivequantities.hh, opm/simulators/flow/FIBlackoilModel.hpp, opm/simulators/flow/FlowBaseProblemProperties.hpp, opm/simulators/flow/FlowProblem.hpp
The companion of https://github.com/OPM/opm-common/pull/4658, this does two things:
- Avoid using an ElementContext just to evaluate IntensiveQuantities.
- Demonstrate the compile time dispatch to select a particular three-phase model (EclipseDefault) to avoid run-time switching per cell.
The first seems to give a 5-10% speedup for the property calculations. The second will need to be expanded to give a significant speedup, and is just a proof of concept.
Update: this has now been modified to also perform a proper run-time dispatch on the threephase approach, demonstrating the goal of moving such dispatches out of the inner loop.
=> Compiletime threephaseswitch

opm/simulators/linalg/ISTLSolver.hpp, opm/simulators/linalg/getQuasiImpesWeights.hpp
This PR parallelizes the CPR weight calculation using OpenMP threading to improve performance, particularly important for GPU configurations where the CPU is idle and the CPU-based weight calculation can become a significant proportion of linear solve time.
- Both `getTrueImpesWeights` and `getTrueImpesWeightsAnalytic` functions now use OpenMP parallel loops over element chunks
- Parallelized quasi-IMPES weight calculation using OpenMP over matrix rows
Testing on the first month of the 2M cell Sleipner case shows significant speedups:
- **cpr_trueimpes**: Linear solve time reduced from 9.74s to 8.33s (~15% reduction)
- **cpr_trueimpesanalytic**: Linear solve time reduced from 8.64s to 7.73s (~11% reduction)
This change was extracted from the larger CPR-AMG GPU implementation in …
=> Make cpr weight calculation thread parallel

opm/simulators/flow/ReservoirCoupling.cpp, opm/simulators/flow/ReservoirCoupling.hpp, opm/simulators/flow/ReservoirCouplingMaster.cpp, opm/simulators/flow/ReservoirCouplingMaster.hpp, opm/simulators/flow/ReservoirCouplingSlave.cpp, opm/simulators/flow/ReservoirCouplingSlave.hpp, opm/simulators/flow/ReservoirCouplingSpawnSlaves.cpp, opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp, opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp, opm/simulators/wells/GuideRateHandler.cpp, tests/rescoup/test_chopstep.cpp
This allows slaves and master processes to activate at different times. It also fixes a bug in the current implementation where a slave that started later than the master, did not wait for the master to catch up.
- A slave may now run independently until it is activated by a `GRUPSLAV` keyword in the schedule. Before that point it determines its own timestepping strategy. After activation, its timestepping is controlled and synced by the master.
-   If the slave activates later (schedule `DATE`) than the master, it will have to wait until the master reaches that point of time, before it synchronizes with the master.
-  The master may run independently until it is activated by a `SLAVES` keyword in the schedule. Before that point it determines its own timestepping strategy. After …
=> Reservoir coupling: Allow slaves and master to activate at different times

CMakeLists_files.cmake, opm/simulators/flow/GenericOutputBlackoilModule.cpp, opm/simulators/flow/GenericOutputBlackoilModule.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/OutputCompositionalModule.hpp, opm/simulators/flow/RFTContainer.cpp, opm/simulators/flow/RFTContainer.hpp, opm/simulators/wells/BlackoilWellModelGeneric.hpp, parallelUnitTests.cmake, tests/test_rftcontainer.cpp
Commit 6295bd08c (PR #6238) restricted RFT data reporting to only those wells that are owned by the current rank.  In so doing, however, we failed to properly account for distributed wells.  Such wells will typically have RFT contributions from multiple MPI ranks in a parallel run and we did not allow for this situation. Moreover, as the simulator by default will distribute "inactive" wells&ndash;wells that are never opened, but which exist primarily to collect RFT-style data&ndash;the problem becomes more pronounced for these wells.
We solve the problem by splitting the `RFTContainer`'s "`wellQuery_`" into two responsibilities.  One for determining if a particular named well is owned by the current rank and another for determining if the well is intersected on the current rank.  The …
=> Fix RFT State Collection for Distributed Wells

opm/simulators/utils/InstantiationIndicesMacros.hpp
could not figure out where they are used so asked the compiler to help. 
But still could not find where they are used. We can remove them, which can be good thing to do since they are not used.
=> removing instantiation for two Indices setup with non-zero PVOffset

python/docker/scripts/generate-pypi-package.sh, python/pyproject.toml, python/setup.py.in
From private communication with @akva2: When building the python modules in the docker container (see [python/docker](https://github.com/OPM/opm-simulators/tree/master/python/docker)) some warnings were shown when running `python setup.py`, see [generate-pypi-package.sh](https://github.com/OPM/opm-simulators/blob/00e9b6b276e0f5d0f9e4cdf619987a327c40294c/python/docker/scripts/generate-pypi-package.sh#L145). Try to modernize to use [pypa/build](https://build.pypa.io/en/stable/) instead to get rid of warnings, see also companion PR https://github.com/OPM/opm-common/pull/4732
Example warning:
```
#16 959.8 /opt/python/cp312-cp312/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
#16 959.8 !!
#16 959.8 
#16 959.8 …
```
=> Fix python setup.py warnings

opm/simulators/wells/WellInterface_impl.hpp
The "classical" well operability check does not work correctly and is thus not a good fallback. It often wrongly opens inoperable wells during well testing.
=> Dont go back to classical approach during un-converged operability check

opm/simulators/wells/WellHelpers.hpp
The enum is based on `std::unint16_t`, which is not available without including `cstdint`.
=> Added include of cstdint

opm/simulators/wells/BlackoilWellModelGeneric.cpp, opm/simulators/wells/BlackoilWellModel_impl.hpp, opm/simulators/wells/WellInterfaceGeneric.hpp, opm/simulators/wells/WellState.cpp, opm/simulators/wells/WellState.hpp
Wells may be temporarily stopped due to convergence or operability issues during local well solves. Temporarily stopped wells do not contribute to groups and are therefore not considered in the group target calculations.
=> Dont include temporary stopped wells among the wells considered for group control

python/docker/run-docker-build.sh
Use the target that builds all python modules to avoid having to update this if any new modules are added in the future.
=> python packaging: update to use python_simulator_modules target

CMakeLists_files.cmake, opm/simulators/linalg/StandardPreconditioners_gpu_mpi.hpp, opm/simulators/linalg/StandardPreconditioners_gpu_serial.hpp, opm/simulators/linalg/gpuistl/ISTLSolverGPUISTL.hpp, opm/simulators/linalg/gpuistl/detail/FlexibleSolverWrapper.cpp, opm/simulators/linalg/gpuistl/detail/FlexibleSolverWrapper.hpp, opm/simulators/linalg/gpuistl/detail/gpu_preconditioner_utils.hpp
This PR contains three different additions:
- A fix to ensure that the GPU communicator stays alive.
- Adds a couple of missing steps for the parallel setup for the new ISTLSolverGPUISTL class, which is only used when `--linear-solver-accelerator=gpu` and we are running MPI parallel.
- Registers the GPU preconditioners into the preconditioner factory for MPI parallel GPU preconditioners.
=> Fix MPI parallel ISTLSolverGPUISTL and register parallel GPU preconditioners

opm/models/blackoil/blackoilbioeffectsmodules.hh, opm/models/blackoil/blackoilintensivequantities.hh, opm/models/blackoil/blackoilnewtonmethod.hpp, opm/models/blackoil/blackoilonephaseindices.hh, opm/models/blackoil/blackoilprimaryvariables.hh, opm/models/blackoil/blackoiltwophaseindices.hh, opm/models/blackoil/blackoilvariableandequationindices.hh, opm/models/io/vtkblackoilbioeffectsmodule.hpp, opm/models/io/vtkblackoilbioeffectsparams.cpp, opm/models/io/vtkblackoilbioeffectsparams.hpp, opm/simulators/flow/BioeffectsContainer.cpp, opm/simulators/flow/BioeffectsContainer.hpp, opm/simulators/flow/BlackoilModel.hpp, opm/simulators/flow/FlowGenericProblem.hpp, opm/simulators/flow/FlowGenericProblem_impl.hpp, opm/simulators/flow/FlowProblemBlackoil.hpp, opm/simulators/flow/OutputBlackoilModule.hpp, opm/simulators/flow/SolutionContainers.cpp, opm/simulators/flow/SolutionContainers.hpp, opm/simulators/utils/ComponentName.cpp
The variables `biofilm` and `calcite` are actually volume fractions, setting the correct names in this PR. Related to https://github.com/OPM/opm-common/pull/4750
=> Biofilm and Calcite set to volume fraction instead of concentration

opm/simulators/linalg/HyprePreconditioner.hpp
Restores setting the member `use_gpu_backend_` which was removed in https://github.com/OPM/opm-simulators/pull/6453 (probably by accident).
=> Fix GPU backend specification for Hypre

flow/flow_brine.cpp, flow/flow_brine_energy.cpp, flow/flow_brine_precsalt_vapwat.cpp, flow/flow_brine_saltprecipitation.cpp, flow/flow_gaswater_brine.cpp, flow/flow_gaswater_saltprec_energy.cpp, flow/flow_gaswater_saltprec_vapwat.cpp, flow/flow_oilwater_brine.cpp, opm/models/blackoil/blackoilbrinemodules.hh, opm/models/blackoil/blackoillocalresidual.hh, opm/models/blackoil/blackoillocalresidualtpfa.hh
Making the TPFA lineariser default for simulators with `EnableBrine=true` (and fixing some format in a few files while working on this as well).
=> Use new lineariser for simulators with EnableBrine

CMakeLists.txt, examples/problems/co2ptflashproblem.hh, examples/problems/cuvetteproblem.hh, examples/problems/infiltrationproblem.hh, examples/problems/reservoirproblem.hh, flow/flow_blackoil_nohyst.cpp, flow/flow_blackoil_nohyst.hpp, flow/flow_blackoil_nohyst_main.cpp, opm/simulators/flow/FlowBaseProblemProperties.hpp, opm/simulators/flow/FlowProblemBlackoilProperties.hpp, opm/simulators/flow/FlowProblemCompProperties.hpp, opm/simulators/flow/MainDispatchDynamic.cpp, opm/simulators/flow/equil/EquilibrationHelpers.cpp, opm/simulators/flow/equil/InitStateEquil.cpp
Downstream of https://github.com/OPM/opm-common/pull/4766.
Adds flow_blackoil_nohyst, standalone simulator for testing. Not yet integrated in main flow executable with dynamic dispatch.
=> Add no-hysteresis variant of Flow
